### ISSUE TITLE
[1.20.1 & 1.21.1] An issue between structure containing transformable tiles and structure using transparent texture

### ISSUE THREAD

**Issue by kazumadh** [CreativeMD/LittleTiles#1000]
**(Reposted from Discord)**
**Only Creative Core v2.11.31 & Little Tiles v1.6.0 Beta Pre 110 are installed**
_**[Update] (8/21/2024):
For 1.20.1: Only CreativeCore v2.11.37 & Little Tiles v1.6.0 Beta Pre113 are installed
For 1.21.1: Only CreativeCore v2.12.8 & Little Tiles v1.6.0 Alpha Pre113 are installed**_
In the first video, I place down the concrete bar, which is chamfered by using transformable tiles, make sure at least one of its face is at the edge of the 1 x 1 x 1 block's border. Next, I build a wall using purple glass which's also at the edge of the block's border, but from the other side. Looking at the glass wall from the glass's side, nothing weird, but from the other side (concrete bar), it loses its color and becomes completely transparent.
In the second video, I place down the same bar, but not at the 1 x 1 x 1 block's edge, then I build the same glass wall next to the bar's side. Nothing happens when you look at the glass at both sides.
First video
https://github.com/user-attachments/assets/9d1b2cc8-d7b6-4db6-9ccb-3d7700c4a68b
Second video
https://github.com/user-attachments/assets/19ad2844-60aa-4484-90da-261112246374
Structure 
[concrete bar 125 x 187.5 c64.txt](https://github.com/user-attachments/files/16512078/concrete.bar.125.x.187.5.c64.txt)

**Comment by CreativeMD** [comment]
The face culling issue has been fixed as well. It actually had nothing to do with a transformable box. Thanks for your detailed issue description. Thanks for all the effort you put into this.
