### ISSUE TITLE
[1.20.1 & 1.21.1] Issues of Little Paint Brush, caused by painting a large area

### ISSUE THREAD

**Issue by kazumadh** [CreativeMD/LittleTiles#1001]
**(Reposted from Discord)**
**Only CreativeCore v2.11.31 & Little Tiles v1.6.0 Beta Pre110 are installed**
_**[Update] (8/21/2024):
For 1.20.1: Only CreativeCore v2.11.37 & Little Tiles v1.6.0 Beta Pre113 are installed
For 1.21.1: Only CreativeCore v2.12.8 & Little Tiles v1.6.0 Alpha Pre113 are installed**_
1.Build a one-way slab using LT-Chisel, its thickness must be lower than a full block. In the screenshot, I built 2-pixel-thick slab (1/8 of a full block). The longer span shall be at least 3-chunk long (~ 50 blocks). **The top of this slab must be the same as the top of a full block or a vanilla top slab (Which means the Y shall be Y.00000 when you stand on it).**
2.Place down the railings along the longer span.
3.Use Little Paint Brush, select "Box" mode, choose the color you want, paint a small part of each railings (for example, the top of their posts) (don't paint the entire of those railings, since maybe this issue happens because the railings have at least 2 different colors(?))
4.Press Undo keybind and then Redo keybind, repeat that until you see something wrong with the slab where the railings are placed on.
As you can see, some parts of the slab are missing, but there are some "ghost blocks" using the slab's texture, appear above the missing parts. F3 + A doesn't help, the only way to fix this is to leave the world and rejoin again. 
In addition, the sound effect of the undo/redo action is extremely annoying, as if it plays after each loop. The game FPS also drops down during these actions. There should be a way to improve performance of those.
First video
https://drive.google.com/file/d/1cALZmHjWAjoQSsWoPdwqurzNi52z75aA/view?usp=drive_link
Second video
https://drive.google.com/file/d/1EgfR9p2IthqPBk_oAQq3tVRxXNnp3wYi/view?usp=drive_link
First image
![one way slab](https://github.com/user-attachments/assets/2e55b1d8-444a-4e2a-89d5-551b6ad097a2)
Second image
![one way slab with railings](https://github.com/user-attachments/assets/78bdde54-a528-4b59-b33b-adc0285fcf14)
Structure
[test railing type 3B gird 64.txt](https://github.com/user-attachments/files/16512153/test.railing.type.3B.gird.64.txt)

**Comment by CreativeMD** [comment]
Thanks a lot for reporting this issue. It is fixed in the newest version.
