### ISSUE TITLE
[1.20.1 & 1.21.1] Issues caused by interacting with "Sliding Door" and "Chair" structures

### ISSUE THREAD

**Issue by kazumadh** [CreativeMD/LittleTiles#1002]
**(Reposted from Discord)**
**Only CreativeCore v2.11.31 & Little Tiles v1.6.0 Beta Pre110 are installed**
_**[Update] (8/21/2024):
For 1.20.1: Only CreativeCore v2.11.37 & Little Tiles v1.6.0 Beta Pre113 are installed
For 1.21.1: Only CreativeCore v2.12.8 & Little Tiles v1.6.0 Alpha Pre113 are installed**_
Rotating the direction of the structure's appearance doesn't change its moving direction, it just keeps its initial moving direction in the blueprint.
Interacting with the sliding door, which is a part of a larger structure, then break it causes some issues. Let's take the cabinet as an example:
a) I pull out one of the drawers, then break it. When I press "undo" keybind, I have to click on the same drawer twice to open it.
b) Breaking the drawer while it's animating, then press "undo" keybind, only the same drawer remain.
Breaking "chair" structure by hand or "undo" keybind while you're sitting on it doesn't force you to dismount. This also happens in 1.12.2, no idea whether this "works as intended".
First Video
https://drive.google.com/file/d/1GHeDSoKnG0rc0GBUzcL5MXK6oY-PKRbI/view?usp=drive_link
Second Video
https://github.com/user-attachments/assets/ddaffd7f-176b-435e-9e95-ac7752eae003
Cabinet structure
[cabinet by alaginho.txt](https://github.com/user-attachments/files/16512217/cabinet.by.alaginho.txt)
Cart structure
[test cart sliding door south direction.txt](https://github.com/user-attachments/files/16512225/test.cart.sliding.door.south.direction.txt)
**[1.21.1] Only**
When you sit on a LT-Chair, your player is inaccurately positioned:
![Inaccurately Sit Position](https://github.com/user-attachments/assets/67d4be1a-a336-42ff-a3b3-1c862ee9cdfb)

**Comment by kazumadh** [comment]
Update: I found another issue that relates to shaders: Activated Structures become invisible when changing shaders, you have to interact with them to make them visible again.
https://github.com/user-attachments/assets/c489a975-1e3f-4a34-8cfc-bf9fb18bb189
Embeddium 0.3.28 & Oculus 1.7.0

**Comment by CreativeMD** [comment]
Can you test the first and second issue and see if there are fixed in the newest version?

I will take a look at the door vanishing issue.

**Comment by CreativeMD** [comment]
The third issue should be fixed in the newest version as well.

**Comment by kazumadh** [comment]
All of them, except the rotating issue, are yet to be fixed, 

> Can you test the first and second issue and see if there are fixed in the newest version?
> 
> I will take a look at the door vanishing issue.



> Can you test the first and second issue and see if there are fixed in the newest version?
> 
> I will take a look at the door vanishing issue.

**Comment by CreativeMD** [comment]
Totally overlooked the b) issue. The sit position works for me just fine.

The door vanishing issue and the b) issue, will both be fixed in the next pre-release, which has not been released yet. Sorry for my incorrect statement.

**Comment by CreativeMD** [comment]
New version is out. I hope all issues are solved if not feel free to open a new issue. Thanks again for your help!
