### ISSUE TITLE
[1.20.1 & 1.21.1] Issue of "Activated" "Sliding/Axis Door" when updating Resource Pack

### ISSUE THREAD

**Issue by kazumadh** [CreativeMD/LittleTiles#1003]
**Only CreativeCore v2.11.31 & LittleTiles v1.6.0 Beta Pre110 are installed**
_**[Update] (8/21/2024):
For 1.20.1: Only CreativeCore v2.11.37 & Little Tiles v1.6.0 Beta Pre113 are installed
For 1.21.1: Only CreativeCore v2.12.8 & Little Tiles v1.6.0 Alpha Pre113 are installed**_
When I activate the signal-related structures (open axis/sliding doors), then I change the game's resource pack, the textures of those activated structures (b0:[true]) get corrupted, while nothing happens to those which don't get activated (b0[false])
https://github.com/user-attachments/assets/f55dc5f6-45b2-4fc0-96f6-d774f6b89d0f

**Comment by CreativeMD** [comment]
This was actually the same issue as door vanishing when changing shaders. Is also fixed in the newest version.
