### ISSUE TITLE
Using "Optimize World" function causes LittleTiles worlds to be unable to load

### ISSUE THREAD

**Issue by TheMysteriousGray** [CreativeMD/LittleTiles#1004]
After using LT on a large, complicated build, my world seemed to be slowing down all of a sudden and I couldn't understand why, so I used the Optimize World function and erased all cached data. Unfortunately, after it was done, any time I attempt to load the world while LittleTiles is active, the loading screen hangs at 0% and the world never loads. Deactivating LT and loading the world causes it to load normally, but doing so erases any LT builds I've made even after reactivating. I can still make edits to the world with programs like AMulet, but the world simply refuses to load while LT is active. The game doesn't _crash_ so there is unfortunately no crash report.

**Comment by CreativeMD** [comment]
Can you send me your log file? Pretty sure there most be some kind of error.

**Comment by TheMysteriousGray** [comment]
[MultiMC version 0.7.0-3863.txt](https://github.com/user-attachments/files/16681874/MultiMC.version.0.7.0-3863.txt)

The log text as I saw it in the MultiMC launcher. Whenever the map launches, it hangs at 0% as seen in the log, but does nothing else. It can stay this way for hours, and the only way I've ever been able to stop it is to manually kill the program either through the launcher or Task Manager. If I load the map without LittleTiles, the map launches fine but all LT builds are destroyed. If I then replace the region files from this "refreshed" version with the region files from the busted version, the problem happens again.

**Comment by CreativeMD** [comment]
What is this "optimize world" feature?

**Comment by TheMysteriousGray** [comment]
it's a feature that's been in Minecraft for a while. When you port in a world from an older version, you can use the Optimize World function to update the map's files and level data to the most recent version of the game, which is faster than manually exploring the world to force-update the information, at the cost of the map no longer being playable on older versions. Additionally, it prompts you to erase cached data, which is stuff like light levels and biome data, which must then be recalculated for the map in the newer version's formatting. It's most useful for big jumps between game versions. I hadn't done so, I just figured "refreshing" the map data might help with a lagspike I was experiencing (it didn't).

What's extra interesting is that I tried to replicate the issue with a test map, putting a small LT build on it and then optimizing the world, and it worked without any issues. it was a tiny and simple build on a superflat world though, while the busted map is 20 GB in size and features a datapack to give a max build height of 1536 blocks. The LT structure I was working on was also very large and complicated. From a layman's perspective, it might have all just been too much to handle and now the map won't load anymore without removing the LT stuff and starting over.

**Comment by CreativeMD** [comment]
Interesting. I don't see a way to help out without further testing. I would need your world, so I can where it hangs up. You do not have the send the entire map in theory. You can also only include the region files which cause the issue.

**Comment by CreativeMD** [comment]
Any news here?

**Comment by TheMysteriousGray** [comment]
Sorry for taking so long to get back to this.


I haven't tinkered much with the map, but I still can't get it to load. I can try process-of-eliminating region files to see if I can find the problem child, but my map is _huge_, so this may take a while. I can't send the whole thing either, it's 20 GB in size. I'll try your suggestion and see what I can figure out

**Comment by CreativeMD** [comment]
Can try out the newest version and see if it works?

**Comment by TheMysteriousGray** [comment]
Holy Mother of God, it worked!

I don't know what you did but it finally loaded! Thank you so much, you saved me a ton of lost work!

![2024-08-06_18 07 10](https://github.com/user-attachments/assets/8e8ff359-4030-4220-bd00-e0a59397c2f5)

have a pretty little picture as thanks

**Comment by CreativeMD** [comment]
Very nice to hear that!!!
