### ISSUE TITLE
[1.20.1 & 1.21.1] Issue of Little Paint Brush using "Connected Tiles" Mode

### ISSUE THREAD

**Issue by kazumadh** [CreativeMD/LittleTiles#1005]
**Only CreativeCore v2.11.31 & LittleTiles v1.6.0 Beta Pre110 are installed**
_**[Update] (8/21/2024):
For 1.20.1: Only CreativeCore v2.11.37 & Little Tiles v1.6.0 Beta Pre113 are installed
For 1.21.1: Only CreativeCore v2.12.8 & Little Tiles v1.6.0 Alpha Pre113 are installed**_
1. When you're 3-4 blocks away from the structure you want to paint, hold the Little Paint Brush with "Connected Tiles" Mode, then look at the structure. The hitbox instead of being the entire structure, only a 1 x 1 x 1 minecraft block that you look at is selected as the hitbox. **_(This issue may be fixed in 1.21.1, I suppose)_**
https://github.com/user-attachments/assets/7d37f0d1-548a-4fec-adb9-e6f5ecf22f4e
2. When you let your character move and paint at the same time, there's a low chance that it only paints the region of a 1 x 1 x 1 minecraft block that you look at. This chance may be likely higher if you're 3-4 blocks away from the structure **_(not yet fixed in both version)._**
https://github.com/user-attachments/assets/40c5a17b-c196-4e63-b844-4469ab2ab965
You can use structure from this post to reproduce:
https://github.com/CreativeMD/LittleTiles/issues/1001

**Comment by CreativeMD** [comment]
Oh yes!!! I have noticed a few of these issues here and there, but could never figure out why they are there. Through your example I could find an easy way to catch these errors and then find out what is going wrong. They are finally fixed. Thank you so much! That was a nasty one.
