### ISSUE TITLE
Little Tiles server crash?

### ISSUE THREAD

**Issue by HatelessHeart** [CreativeMD/LittleTiles#1006]
Not exactly sure what happened here but I think it was because of little tiles. 
[crash-2024-08-08_20.10.41-server.txt](https://github.com/user-attachments/files/16553102/crash-2024-08-08_20.10.41-server.txt) Disregard if there was no issue coming from the mod.

Another server crashed when right clicking using the hammer tool from little tiles:
[crash-2024-08-08_20.34.55-server.txt](https://github.com/user-attachments/files/16553198/crash-2024-08-08_20.34.55-server.txt)

**Comment by JS-Fi** [comment]
Was playing today with latest version of LittleTiles (LittleTiles_BETA_v1.6.0-pre115_mc1.20.1) and it seems that server freezes, if player leaves a blueprint (with a shape) in to inventory, and re-joins server. Being on 1.20.1, and also CreativeCore is on latest version. Might not be the same case here, but just telling the finding, in case it can be helpful.

**Comment by HatelessHeart** [comment]
I am quite unfamiliar with the little tiles mod. So I don't think I had a blueprint. I just made the hammer and then tried to edit an oak log. This happened three or four times in different versions of the little tiles mod but maybe I just need to update the creative core to the most recent version.... idk

**Comment by HatelessHeart** [comment]
> Was playing today with latest version of LittleTiles (LittleTiles_BETA_v1.6.0-pre115_mc1.20.1) and it seems that server freezes, if player leaves a blueprint (with a shape) in to inventory, and re-joins server. Being on 1.20.1, and also CreativeCore is on latest version. Might not be the same case here, but just telling the finding, in case it can be helpful.

Creative core version : ends in 33

**Comment by JS-Fi** [comment]
I'm using CreativeCore v2.11.37_mc1.20.1. Haven't used anything else than Little Chisel and Little Blueprint tools so far though. So yeah, it seems that we have faced different kind of server crashes, or at least, by different actions, that leaded to crashing.

**Comment by HatelessHeart** [comment]
I’m using multiple mods. I’m using the Escape from the Skylands modpack.

Branden Dickerson

**Comment by CreativeMD** [comment]
Seems to be an issue with the diet mod. I reported the issue to them: https://github.com/illusivesoulworks/diet/issues/200

Let's hope it can be solved soonish.

**Comment by HatelessHeart** [comment]
Yes i do have that mod installed too. I thought It could be about embeddium
as it was mentioned in the crash report.

Branden Dickerson

**Comment by CreativeMD** [comment]
It's definitely this mod.

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!

**Comment by HatelessHeart** [comment]
Awesome, thanks for the update!
