### ISSUE TITLE
[1.20.1 & 1.21.1] Place position gets inaccurately calculated when interacting with Slope Tiles (part 2)

### ISSUE THREAD

**Issue by kazumadh** [CreativeMD/LittleTiles#1008]
**Only CreativeCore v2.11.31 & LittleTiles v1.6.0 Beta Pre110 are installed**
_**[Update] (8/21/2024):
For 1.20.1: Only CreativeCore v2.11.37 & Little Tiles v1.6.0 Beta Pre113 are installed
For 1.21.1: Only CreativeCore v2.12.8 & Little Tiles v1.6.0 Alpha Pre113 are installed**_
I build slopes with different gradient (from 1 to 1/32), and these issues are what I find out:
1. While you aren't moving your POV camera, the place position when using LT Hammer and LT-Chisel with "Replace Mode" are different.
2. The higher the grid is and the lower the slope gradient is, the more inaccurately the place position gets.
https://github.com/user-attachments/assets/6955ee5a-e0f4-4c5a-a91d-2d0eb0c5209b

**Comment by CreativeMD** [comment]
I realized several issues with calculation the correct position. The replace mode position was totally off. Reworked how that one is calculated and fixed the other errors. Now it should finally work. Thanks a lot for your help again!
