### ISSUE TITLE
Unloading bug

### ISSUE THREAD

**Issue by GubirGrebs** [CreativeMD/LittleTiles#1009]
me and my friend downloaded this mod and thought it was very fun but there is a very annoying glitch that unloads the little tile blocks so i can only see the hitbox whenever i move away or place or break a block near it. Sometimes they just turn invisible randomly for no reason. i remember playing this mod about 3-4 years ago and i didn't have any of those issues.

**Comment by CreativeMD** [comment]
What version of the mod are you using? What other mods do you have installed?

**Comment by GubirGrebs** [comment]
I use 1.20.1, dont remember what version of the mod i use, but i think i have the latest one. I have the crayfish furniture mod, ultimate cars mod, forge, and the mod loader you need to download the tiles mod.

**Comment by CreativeMD** [comment]
I would need your log file and maybe a series of screenshot of what is actually help as well.

**Comment by CreativeMD** [comment]
Will close this due to inactivity.

**Comment by GubirGrebs** [comment]
hi, sorry i was gone for a while but i switched to 1.12 and it works perfectly there. thanks though

**Comment by samsan-gif** [comment]
i have the same issue, my tiles blocks are invisible, 1.20.1 forge, 201 mods

**Comment by CreativeMD** [comment]
If you can please switch to 1.21.1. 1.20.1 is not supported anymore.
