### ISSUE TITLE
Game crashes after attempting to make a Door Activator

### ISSUE THREAD

**Issue by ashe-attacc** [CreativeMD/LittleTiles#1010]
Essentially what it sounds like. I'm making models for a Sonic map I'm constructing and one of these is the check point. It has 2 moving parts and one "base" or something that just doesn't move and just sits there. The orb spins 180 and the rod it sits on spins 360, just like it does in Sonic 1. The issue comes when I add them to the pole then try and pack all of them into a Door Activator. Leading up, everything is fine - but as soon as I click on "Axis 0" under "Right-Click," the game crashes. No clue why it does this. Video attached.
And, no, the names aren't the issue. I later went on to name one "Axis 1" and the other "Axis 2" but it still crashes when I click on the box regardless.

https://github.com/user-attachments/assets/0028a1f2-8c05-4df5-8158-af5b6c74f7cf

**Comment by CreativeMD** [comment]
Can you export your structure so I can test it myself? Would also be helpful if you could provide the crash-report. Sorry for responding that late.

**Comment by CreativeMD** [comment]
Will close this due to inactivity.
