### ISSUE TITLE
[1.20.1] Game freezes with embeddium

### ISSUE THREAD

**Issue by Plasmatic19** [CreativeMD/LittleTiles#1012]
Anytime i place a tile with the embeddium mod installed the game just freezes.

I've even waited hours to see if it would unfreeze but it never does.

**Comment by CreativeMD** [comment]
What version of Embeddium, CreativeCore and LittleTiles are you using?

**Comment by Plasmatic19** [comment]
the latest versions

**Comment by CreativeMD** [comment]
Can you send me the log file of when this happened?

**Comment by lapp2333xhj** [comment]
[latest.log](https://github.com/user-attachments/files/16884312/latest.log)

I have the same problem, here is the log file.

**Comment by CreativeMD** [comment]
Should be fixed in the newest version. Thanks a lot for the help! Sorry that it took me so long.
