### ISSUE TITLE
[1.20.1] Problem with pathfinder

### ISSUE THREAD

**Issue by Ildar375** [CreativeMD/LittleTiles#1013]
Entity blocks do not see little tiles. When trying to call mob.getNavigation().moveTo(x, y, z, 1) in my mod, they get stuck.
I'm using the latest version of little tiles and creative core.
![изображение](https://github.com/user-attachments/assets/6c3aaf9e-78dc-4e7e-9ac2-428c4808c785)

**Comment by CreativeMD** [comment]
It's better in the newest version. Blocks from littletiles will be considered unpassable, which should at least allow them to navigate around them.
