### ISSUE TITLE
REI incompatible with LittleTiles

### ISSUE THREAD

**Issue by Barerock** [CreativeMD/LittleTiles#1014]
When opening the menu, this log is spammed hundreds of times per second
[REI] Screen team.creative.creativecore.common.gui.integration.ContainerScreenIntegration did not render background and foreground! This might cause rendering issues!

Nothing else in the log shows any problems other than basic rendering info being logged as the menu closing and opening resets the scene, causing a hitch. The menu itself works fine as far as I can tell.

**Comment by CreativeMD** [comment]
What version are you using? Is there any reason not use JEI, which runs perfectly fine?

**Comment by CreativeMD** [comment]
Will close this due to inactivity.
