### ISSUE TITLE
[1.20.1][Crash]Crash when attempting to open the Tetra Workbench.

### ISSUE THREAD

**Issue by Tollainmear** [CreativeMD/LittleTiles#1017]
Hi, I only tested this issue on the 1.20.1 version. In the case of b121, this crash issue does not exist, and the workbench can be normally openned. 

However, when I upgraded the LittleTiles mod to B122, regardless of whether interacting with the workbench or trying to open the holo ball, it would cause the game to crash. 

Here is the crash log I collected:
https://gist.github.com/Tollainmear/824eca59d32a1e807bbc2e37f3578a0a

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
