### ISSUE TITLE
Problem with Embeddium, Oculus and Little Tiles when placing and using Little Tiles sliding doors.

### ISSUE THREAD

**Issue by BenGamesMC523** [CreativeMD/LittleTiles#1018]
[2nd Crash Report.txt](https://github.com/user-attachments/files/17018074/2nd.Crash.Report.txt)
[1st Crash Report.txt](https://github.com/user-attachments/files/17018075/1st.Crash.Report.txt)

I am using the newest versions of Little Tiles, Embeddium and Oculus as of 16/9/24. Whenever I place a custom door or window it causes these giant visual glitches in the distance and any glass that is being used in the custom door appears next to the door or where an old custom door used to be. I have a better video showing this, that I have uploaded to YouTube because it is too big to be uploaded here.

**https://www.youtube.com/watch?v=khRw1m2kSu8**

**Comment by CreativeMD** [comment]
At least the crash should be fixed. The visual glitches are still a thing. However I will solve them for sodium and iris. As I will not continue supporting Embeddium and Oculus.

Also very sorry to responding that late. If the crash still occur for some reason let me know here.
