### ISSUE TITLE
Glitchy or Invisible tiles with OptiFine shaders

### ISSUE THREAD

**Issue by F0x06** [CreativeMD/LittleTiles#102]
HI, first of all, thank you for this amazing mod ! Awesome work !

I really like using shaders, but when i enable them, all tiles start glitching, in the bellow images i used the `(internal)` one from OptiFine

I searched on old issues, but nothing resolved my issue, i tried to change `Render regions` and `VBOS` settings, `Render regions` just make tiles turn completely invisible like said in previous issues.

I downloaded all your mods from CurseForge,

Minecraft version: `1.12.2`
Forge version: `14.23.4.2729`
CreativeCore version: `1.9.22_mc1.12.2`
LittleTiles version: `1.5.0-pre97_mc1.12.2`

Loaded mods:
* OptiFine_1.12.2_HD_U_E1.jar
* jei_1.12.2-4.11.0.204.jar
* CreativeCore_v1.9.22_mc1.12.2.jar
* LittleTiles_v1.5.0-pre97_mc1.12.2.jar

Screenshots:

With Shaders enabled
![with_shaders](https://user-images.githubusercontent.com/7167311/43152292-810dec1a-8f6e-11e8-8242-32e26574463c.png)

Without Shaders:
![without_shaders](https://user-images.githubusercontent.com/7167311/43152302-86deb4da-8f6e-11e8-8f34-34ac926d9e16.png)

Maybe i use the worng forge version ? Thank you.

**Comment by CreativeMD** [comment]
Just try to out pre100, it should solve your issue. Don't forget to update CreativeCore as well.
