### ISSUE TITLE
Crash when opening LT's creative tab

### ISSUE THREAD

**Issue by emanuele246gi** [CreativeMD/LittleTiles#1020]
The game crashed when I opened the creative tab of Little Tiles' items (Minecraft 1.20.1, 0.9.0-1.20-forge) https://gist.github.com/emanuele246gi/da2cbdfabc58b8634becba2a8332033b

**Comment by CreativeMD** [comment]
Seems like a crash from Lightman's Currency. This has nothing to do with my mod.

**Comment by emanuele246gi** [comment]
By the way, I still didn't manage to see what's in that gui, is there a list of bits from all the blocks in the modpack? Because the reason it crashed is probably because Lightman's Currency doesn't add full vanilla-style blocks.

**Comment by CreativeMD** [comment]
No in the LittleTiles tab there are only a few tools and white blocks.
