### ISSUE TITLE
Valkirien Skies compatibility

### ISSUE THREAD

**Issue by Kevadroz** [CreativeMD/LittleTiles#1022]
[(Already reported on the VS2 repo)](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/969)

Basically tiles are very buggy when on VS2 ships.
IDK if anything can be done on LittleTiles's end.

**Comment by Aiwen094** [comment]
The advanced doors created with the LittleTiles mod cannot be used on dynamic structures as well.

**Comment by CreativeMD** [comment]
Sorry but this will not be fixed at the moment. LittleTiles has a weird way of rendering things, that's why it will not be compatible by default. It can only fixed with special support. Something I cannot do at the moment, because I'm lacking the time.
