### ISSUE TITLE
Light goes through blocks. How to fix it.

### ISSUE THREAD

**Issue by EtreialCraft** [CreativeMD/LittleTiles#1023]
I encountered this when building thin walls. Roughly speaking, the light shone through the walls and spoiled all the pleasure from the mod. I would be very grateful for help.

Version game: 1.12.2
Version mod: 1.5.0

![photo_2024-10-04_21-19-01](https://github.com/user-attachments/assets/6f8e25c6-2b1e-4212-a10e-45341ca0499a)

**Comment by CreativeMD** [comment]
This cannot be fixed sorry. The light calculations do not allow it. I doubt this will ever change. Better effects can be achieved via shaders. Sorry, but I cannot help you there.
