### ISSUE TITLE
Doors crashing game

### ISSUE THREAD

**Issue by Hopingfordespair** [CreativeMD/LittleTiles#1024]
Forge 47.3.0
1.20.1 little tiles beta v1.6.0 pre131
When opening or shutting animated door, half the time the game freezes, a visual bug happens like blocks stretching across screen, and it crashes.
[crash-2024-10-09_13.50.24-client.txt](https://github.com/user-attachments/files/17319792/crash-2024-10-09_13.50.24-client.txt)
[crash-2024-10-09_13.50.24-client.txt](https://github.com/user-attachments/files/17319794/crash-2024-10-09_13.50.24-client.txt)
![Screenshot (3060)](https://github.com/user-attachments/assets/42edc71c-821c-4d89-9013-6e1c450dfe2a)
![Screenshot (3061)](https://github.com/user-attachments/assets/44924ad1-5f3c-4042-a158-b29119ced133)

**Comment by CreativeMD** [comment]
Please remove embeddiumplus and update Embeddium that should resolve the crash. The visual glitches are a think I will try to tackle in 1.21 for sodium and iris. Sorry for responding that late. Things have been quite busy.
