### ISSUE TITLE
Mobs going through LittleTiles blocks

### ISSUE THREAD

**Issue by JS-Fi** [CreativeMD/LittleTiles#1025]
Hello,

Noticed problem that if I have a LittleTiles block as a floor, mobs goes through it.
![Screenshot_LittleTiles](https://github.com/user-attachments/assets/cc71523f-4c4a-43c1-becc-60de0dbb5fc8)

Minecraft version 1.20.1
Creativecore version 2.12.17
LittleTiles version 1.6.0-pre131

Thanks if this can get fixed!

PS. Facing often an issue, that when player joins server, LittleTiles blocks loads up as invisible for the player, and rejoining fixes it. Could this perhaps be something that gets fixed by adjusting LittleTiles render settings? Theyre on default settings atm and have not played with them yet.

Best regards,
JS

**Comment by CreativeMD** [comment]
Sorry for responding so late. Any other mods installed or just these two?

**Comment by JS-Fi** [comment]
No problem! Here's full list of mods in the server:
> AI-Improvements-1.20-0.5.2.jar
> alexsmobs-1.22.9.jar
> amendments-1.20-1.2.12.jar
> architectury-9.2.14-forge.jar
> astikorcarts-1.20.1-1.1.8.jar
> bettercombat-forge-1.8.6+1.20.1.jar
> BiomesOPlenty-forge-1.20.1-19.0.0.91.jar
> blockui-1.20.1-1.0.156-RELEASE.jar
> CarbonConfig-1.20-1.2.6.jar
> carryon-forge-1.20.1-2.1.2.7.jar
> CBMultipart-1.20.1-3.3.0.146-universal.jar
> Chunk-Pregenerator-1.20-4.4.4.jar
> citadel-2.6.0-1.20.1.jar
> cloth-config-11.1.118-forge.jar
> CodeChickenLib-1.20.1-4.4.0.516-universal.jar
> create-1.20.1-0.5.1.j.jar
> CreativeCore_FORGE_v2.12.22_mc1.20.1.jar
> cristellib-1.1.6-forge.jar
> domum_ornamentum-1.20.1-1.0.282-snapshot-universal.jar
> effortlessbuilding-1.20.1-3.9-all.jar
> exposure-1.20.1-1.7.7-forge.jar
> FarmersDelight-1.20.1-1.2.5.jar
> ferritecore-6.0.1-forge.jar
> [Forge]CTOV-3.4.9b.jar
> FramedBlocks-9.3.1.jar
> framework-forge-1.20.1-0.7.11.jar
> geckolib-forge-1.20.1-4.4.9.jar
> GlitchCore-forge-1.20.1-0.0.1.1.jar
> GoodEnding-1.20.1-1.0.1-Forge.jar
> ImmediatelyFast-Forge-1.3.1+1.20.4.jar
> ImmersiveEngineering-1.20.1-10.1.0-171.jar
> jei-1.20.1-forge-15.20.0.105.jar
> journeymap-1.20.1-5.10.3-forge.jar
> kotlinforforge-4.11.0-all.jar
> lithostitched-forge-1.20.1-1.3.4.jar
> LittleTiles_BETA_v1.6.0-pre133_mc1.20.1.jar
> mcw-bridges-3.0.0-mc1.20.1forge.jar
> mcw-doors-1.1.1forge-mc1.20.1.jar
> mcw-fences-1.1.2-mc1.20.1forge.jar
> mcw-furniture-3.3.0-mc1.20.1forge.jar
> mcw-lights-1.1.0-mc1.20.1forge.jar
> mcw-paths-1.0.5-1.20.1forge.jar
> mcw-roofs-2.3.1-mc1.20.1forge.jar
> minecolonies-1.20.1-1.1.723-snapshot.jar
> minecraft-comes-alive-7.5.20+1.20.1-universal.jar
> Mob\ Compack-forge-1.20.1-0.0.5\ .jar
> modernfix-forge-5.19.1+mc1.20.1.jar
> moonlight-1.20-2.13.22-forge.jar
> multipiston-1.20-1.2.43-RELEASE.jar
> player-animation-lib-forge-1.0.2-rc1+1.20.jar
> radium-mc1.20.1-0.12.4+git.26c9d8e.jar
> refurbished_furniture-forge-1.20.1-1.0.6.jar
> SereneSeasons-forge-1.20.1-9.1.0.0.jar
> simpleplanes-1.20.1-5.3.3.jar
> spawn-1.0.2-forge.jar
> structurize-1.20.1-1.0.742-RELEASE.jar
> supermartijn642corelib-1.1.17a-forge-mc1.20.1.jar
> supplementaries-1.20-3.1.0.jar
> tectonic-forge-1.20.1-2.4.1.jar
> TerraBlender-forge-1.20.1-3.0.1.7.jar
> theoneprobe-1.20.1-10.0.2.jar
> ThirstWasTaken-1.20.1-1.3.11.jar
> Towns-and-Towers-1.12-Fabric+Forge.jar
> towntalk-1.20.1-1.1.0.jar
> VTweaks-1.20.1-4.0.14.jar

Edit: So yeah, atm it's many versions behind. I can later try with the latest version.

**Comment by kazumadh** [comment]
> No problem! Here's full list of mods in the server:
> 
> > AI-Improvements-1.20-0.5.2.jar
> > alexsmobs-1.22.9.jar
> > amendments-1.20-1.2.12.jar
> > architectury-9.2.14-forge.jar
> > astikorcarts-1.20.1-1.1.8.jar
> > bettercombat-forge-1.8.6+1.20.1.jar
> > BiomesOPlenty-forge-1.20.1-19.0.0.91.jar
> > blockui-1.20.1-1.0.156-RELEASE.jar
> > CarbonConfig-1.20-1.2.6.jar
> > carryon-forge-1.20.1-2.1.2.7.jar
> > CBMultipart-1.20.1-3.3.0.146-universal.jar
> > Chunk-Pregenerator-1.20-4.4.4.jar
> > citadel-2.6.0-1.20.1.jar
> > cloth-config-11.1.118-forge.jar
> > CodeChickenLib-1.20.1-4.4.0.516-universal.jar
> > create-1.20.1-0.5.1.j.jar
> > CreativeCore_FORGE_v2.12.22_mc1.20.1.jar
> > cristellib-1.1.6-forge.jar
> > domum_ornamentum-1.20.1-1.0.282-snapshot-universal.jar
> > effortlessbuilding-1.20.1-3.9-all.jar
> > exposure-1.20.1-1.7.7-forge.jar
> > FarmersDelight-1.20.1-1.2.5.jar
> > ferritecore-6.0.1-forge.jar
> > [Forge]CTOV-3.4.9b.jar
> > FramedBlocks-9.3.1.jar
> > framework-forge-1.20.1-0.7.11.jar
> > geckolib-forge-1.20.1-4.4.9.jar
> > GlitchCore-forge-1.20.1-0.0.1.1.jar
> > GoodEnding-1.20.1-1.0.1-Forge.jar
> > ImmediatelyFast-Forge-1.3.1+1.20.4.jar
> > ImmersiveEngineering-1.20.1-10.1.0-171.jar
> > jei-1.20.1-forge-15.20.0.105.jar
> > journeymap-1.20.1-5.10.3-forge.jar
> > kotlinforforge-4.11.0-all.jar
> > lithostitched-forge-1.20.1-1.3.4.jar
> > LittleTiles_BETA_v1.6.0-pre133_mc1.20.1.jar
> > mcw-bridges-3.0.0-mc1.20.1forge.jar
> > mcw-doors-1.1.1forge-mc1.20.1.jar
> > mcw-fences-1.1.2-mc1.20.1forge.jar
> > mcw-furniture-3.3.0-mc1.20.1forge.jar
> > mcw-lights-1.1.0-mc1.20.1forge.jar
> > mcw-paths-1.0.5-1.20.1forge.jar
> > mcw-roofs-2.3.1-mc1.20.1forge.jar
> > minecolonies-1.20.1-1.1.723-snapshot.jar
> > minecraft-comes-alive-7.5.20+1.20.1-universal.jar
> > Mob\ Compack-forge-1.20.1-0.0.5\ .jar
> > modernfix-forge-5.19.1+mc1.20.1.jar
> > moonlight-1.20-2.13.22-forge.jar
> > multipiston-1.20-1.2.43-RELEASE.jar
> > player-animation-lib-forge-1.0.2-rc1+1.20.jar
> > radium-mc1.20.1-0.12.4+git.26c9d8e.jar
> > refurbished_furniture-forge-1.20.1-1.0.6.jar
> > SereneSeasons-forge-1.20.1-9.1.0.0.jar
> > simpleplanes-1.20.1-5.3.3.jar
> > spawn-1.0.2-forge.jar
> > structurize-1.20.1-1.0.742-RELEASE.jar
> > supermartijn642corelib-1.1.17a-forge-mc1.20.1.jar
> > supplementaries-1.20-3.1.0.jar
> > tectonic-forge-1.20.1-2.4.1.jar
> > TerraBlender-forge-1.20.1-3.0.1.7.jar
> > theoneprobe-1.20.1-10.0.2.jar
> > ThirstWasTaken-1.20.1-1.3.11.jar
> > Towns-and-Towers-1.12-Fabric+Forge.jar
> > towntalk-1.20.1-1.1.0.jar
> > VTweaks-1.20.1-4.0.14.jar
> 
> Edit: So yeah, atm it's many versions behind. I can later try with the latest version.

Uninstall Radium, hope there aren't any mods which need Radium.

**Comment by CreativeMD** [comment]
In 1.21 this bug should be fixed as this setting will be automatically disabled.
