### ISSUE TITLE
Crash by interacting in the GUI

### ISSUE THREAD

**Issue by DraGonFiirE** [CreativeMD/LittleTiles#1026]
The client crashes by interacting in the GUI of a specific blueprint
Base GUI:
![grafik](https://github.com/user-attachments/assets/b7d3f59f-28f4-4eea-8f18-383f35d0eeab)
by activating the "Roller" like this and saving:
![grafik](https://github.com/user-attachments/assets/0089a26e-8591-4ca7-8797-739b8d980b6c)
makes it crash by viewing the blueprint GUI

Forge 47.3.7
CreativeCore_FORGE_v2.12.17_mc1.20.1
LittleTiles_BETA_v1.6.0-pre131_mc1.20.1
[pre change blueprint.txt](https://github.com/user-attachments/files/17402476/pre.change.blueprint.txt)
[crashing blueprint.txt](https://github.com/user-attachments/files/17402411/crashing.blueprint.txt)
[crash-2024-10-16_22.25.15-client.txt](https://github.com/user-attachments/files/17402383/crash-2024-10-16_22.25.15-client.txt)

**Comment by CreativeMD** [comment]
Thanks a lot for reporting this issue! Also thanks for all the detailed information. This made it quite easy for me to fix. New version is out which fixes this issue. Sorry for responding that late.
