### ISSUE TITLE
Spin box crash on 1.20.1Mohist server

### ISSUE THREAD

**Issue by LCEN1361** [CreativeMD/LittleTiles#1028]
With a chisel in hand, press the rotation shortcut such as <- or ->, and the server crashes immediately.
I removed all the plugins and other mods, kept only the LT block and CC front (the front CC core is 2.12.17) and updated the mohist version, the problem is still there. 
Going back to the LT box, I found this bug starting from pre124 until the latest pre131, pre123 does not have this problem. 

[2024-10-20-13.log](https://github.com/user-attachments/files/17449572/2024-10-20-13.log)

[crash-2024-10-20_15.25.28-server.txt](https://github.com/user-attachments/files/17449573/crash-2024-10-20_15.25.28-server.txt)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
