### ISSUE TITLE
Falling through tiled blocks

### ISSUE THREAD

**Issue by lightningwolfblade** [CreativeMD/LittleTiles#1029]
When i have the "Radium Reforged" mod installed. If i make a slab or half a stair, i dont fall or clip through, but when i make a stair i clip and fall through. Im on 1.20.1 Forge 47.3.0
![Screenshot 2024-10-25 115839](https://github.com/user-attachments/assets/3b4085bd-49eb-41ac-8a99-da9b26c2fd46)
![2024-10-25_12 04 02](https://github.com/user-attachments/assets/52923cb1-2165-4162-8884-804dc6674950)

**Comment by kazumadh** [comment]
Uninstall Radium, replace it with Embeddium.
