### ISSUE TITLE
Standing on moving sliding door feels like earthquake

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#103]
And also may crash, especially if you move a bit on that "door"
same applies to mobs
[crash-2018-07-22_15.00.22-client.txt](https://github.com/CreativeMD/LittleTiles/files/2229608/crash-2018-07-22_15.00.22-client.txt)

**Comment by ghost** [comment]
that door was an elevator, moving up/down

**Comment by ghost** [comment]
with me and/or butterflies (mobs from Aether 2) inside

**Comment by CreativeMD** [comment]
The crash is an issue with the portal gun mod. I will contact the author about that soon. The earthquake behavior is something I'm working on, but it's rather difficult to fix on multiplayer (will probably take some time).

**Comment by ghost** [comment]
I dont have portal gun mod...

**Comment by CreativeMD** [comment]
but you use ichunutil

**Comment by ghost** [comment]
That is for Morph mod

**Comment by CreativeMD** [comment]
Can you try to reproduce this issue with only CreativeCore, LittleTiles and iChunUtils installed?

**Comment by ghost** [comment]
[crash-2018-07-27_18.53.41-client.txt](https://github.com/CreativeMD/LittleTiles/files/2236422/crash-2018-07-27_18.53.41-client.txt)
Here it is

**Comment by CreativeMD** [comment]
The new version is uploaded and should fix all of the issue (crash and bouncy behavior).
