### ISSUE TITLE
Rendering issue with Gauges and Switches mod

### ISSUE THREAD

**Issue by MrRedstoneA1** [CreativeMD/LittleTiles#1032]
When the "enhanced resorting" setting is enabled, it causes rendering issues with LED indicators as seen in the screenshots.
Also affects some other blocks from other mods. Using Optifine.
(to replicate, disable the setting and reload minecraft)

Not necessarily a game breaking bug. I don't know what exactly the setting does either.

Forge-1.12.2-14.23.5.2860
LittleTiles_v1.5.87_mc1.12.2
rsgauges-1.12.2-1.2.6
CreativeCore_v1.10.71_mc1.12.2
preview_OptiFine_1.12.2_HD_U_G6_pre1
![kuva_2024-11-04_210829472](https://github.com/user-attachments/assets/c4d308fd-826a-437a-be18-6e0cdcbc5386)
![kuva_2024-11-04_211055874](https://github.com/user-attachments/assets/19756632-cdb5-4989-b6fe-3b35f78039aa)

**Comment by CreativeMD** [comment]
Sorry, but I do not support 1.12 anymore. I cannot help you there unfortunately.
