### ISSUE TITLE
Transparent materials disappear on block entities

### ISSUE THREAD

**Issue by XxFreddy-FuzbearxX** [CreativeMD/LittleTiles#1033]
I was making a glass door animation when noticed that the glass disappears, moves or crashes my game when its moving.
The issue goes away when i turn off "Translucent Face Sorting" in Embeddium.
Still, since it's an issue, i wanted to get it reported.

Minecraft 1.20.1
Embeddium 0.3.31
LittleTiles 1.6.0 pre134

Translucent Face Sorting OFF
![f1](https://github.com/user-attachments/assets/38c78516-c01b-485a-b2a4-4fde82f63a53)

Translucent Face Sorting ON
![f2](https://github.com/user-attachments/assets/5910c75d-9e59-49ca-8895-9843276a04c3)

**Comment by CreativeMD** [comment]
I'm very sorry, but the support for Embeddium will not be continued any further. I will try to focus on making it all work for Sodium in 1.21.
