### ISSUE TITLE
cmdconfig options not saving

### ISSUE THREAD

**Issue by bwrainbow21** [CreativeMD/LittleTiles#1034]
Hi, i wanted to change number of blocks that I'm allowed to place and edit on survival mode, but after changing them in the cmdconfig menu and saving changes, i still cant't place more than 10 blocks and when i come back to cmdonfig menu, i don't see any configuration for survival and creative mode anymore, i only have one set of settings and when i try to edit them and save, they keep coming back to default every time

I'm playing  on 1.20.1, newest version of littletiles
![image](https://github.com/user-attachments/assets/073b10f8-f4a6-4520-aeb2-244c07f8cb20)

**Comment by DraGonFiirE** [comment]
On which CreativeCore version are you playing?
The newest release has fixes for that issue

**Comment by CreativeMD** [comment]
Yep @DraGonFiirE is right. It has been fixed in creative core.
