### ISSUE TITLE
Some suggestion.

### ISSUE THREAD

**Issue by olegikoligik** [CreativeMD/LittleTiles#107]
If some suggestion already were, I apologize for it.

1. Create armour from tiles (like Armourer's Workshop mod)
2. Add clean white block with emmisive texture. (but emmisive texture not work in version pre 102)
3. Animation for tiles (continuous rotation... etc?), frame animation (next frame - next tiles structure)
4. Redstone update. I see mention of this.

**Comment by CreativeMD** [comment]
1. Convert it to C&B and use [ExtraBitManipulation](https://minecraft.curseforge.com/projects/extra-bit-manipulation)
2. Can you send me a resourcepack so I can test it, because in theory it should work already
3. and 4. Planned, will be there in within a few months (hopefully).

**Comment by olegikoligik** [comment]
2. Any. [Example](https://www.planetminecraft.com/texture_pack/emissive-textures/). And grass block invisible when i convert it to tiles.

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming update.

**Comment by olegikoligik** [comment]
5. More option for paint (custom brush, paint from image)

**Comment by CreativeMD** [comment]
Sorry, but paint from image would be very horrible performance wise. Use OnlinePictureFrame if you want to have this kind of feature.

**Comment by olegikoligik** [comment]
Hmmm... Probably still some options? It is just very heavy to do texture of tiles various, especially at a high grid

**Comment by Dushess** [comment]
SignPicture is an option

**Comment by CreativeMD** [comment]
Each pixel would be a tile with a different color, it would get messy rather fast. Again, OnlinePictureFrame supports LittleTiles so you can place pictures as you want to.

**Comment by olegikoligik** [comment]
Ok. Just example what i mean. But i understand, realise random brush or something similar difficult, and isn't priority.
Here is realisation of the road in three ways: (1->2->3)
1. Tiles, with 1 color.
2. Tiles, with ~15 color, and 5 min work (for 1 tiles 32x32) (create: change color and random clicks many many times)
3. OnlinePictureFrame.
![2018-08-07_23 49 47](https://user-images.githubusercontent.com/22132987/43802265-f283ecde-9a9d-11e8-85c1-3bbb553a833e.png)

**Comment by CreativeMD** [comment]
Sorry, but I don't get what you mean.
