### ISSUE TITLE
Tiles viewed through translucent tiles become invisible

### ISSUE THREAD

**Issue by Neuron67** [CreativeMD/LittleTiles#109]
I created a door with a window made from Colored Block Clean and reduced the opacity. I placed the door inside a frame made from same block but solid color. I painted the frame with the brush and when door reaches fully opened state the frame blocks become invisible. If I remove the color by resetting the default brush color, the blocks remain invisible. Replacing the frame blocks makes them visible again.
Hard to explain but I did take screenshots.

Also, water and particles not visible while looking through moving door.

**Comment by CreativeMD** [comment]
Can you send me the screenshots?

**Comment by Neuron67** [comment]
Can't post them here right?

**Comment by Neuron67** [comment]
![2018-08-03_12 26 12](https://user-images.githubusercontent.com/24964976/43660482-8fc6764a-9735-11e8-8e4c-5e938ee510ca.png)
![2018-08-03_11 42 22](https://user-images.githubusercontent.com/24964976/43660548-b9a2d206-9735-11e8-9eb6-2db161cca7e7.png)
![2018-08-03_11 35 26](https://user-images.githubusercontent.com/24964976/43660579-d1bcc31a-9735-11e8-9362-681cdeacd901.png)

**Comment by Neuron67** [comment]
Initially I thought it was caused by placing the door offset to the grid so I made another following the grid and got same result. I don't have any screenshots of the water and particles disappearing but that should be easy to recreate.

**Comment by Neuron67** [comment]
It can't be Optifine related because I don't have it installed.

**Comment by Neuron67** [comment]
Oh by the way, it seems to be only the blocks that are touching the hinge side of the door.

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming update, which should be available tomorrow. Thanks for reporting this issue!!!
