### ISSUE TITLE
Door glitch caused by Valkyrien Warfare

### ISSUE THREAD

**Issue by xunto** [CreativeMD/LittleTiles#112]
Valkyrien Warfare installed causes LittleTiles' doors to fly away when you open them. If you disable Valkyrien Warfare mod the doors work as expected.

I don't expect LittleTiles to work on ships from Valkyrien Warfare but maybe there is way to make them stop breaking each other.

Minecraft version: 1.12

Valkyrien Warfare version: Valkyrien Warfare 0.9_prerelease_5 [Optimization Update]
LittleTiles version: LittleTiles_v1.5.0-pre102_mc1.12.2.jar

Video: https://www.youtube.com/watch?v=fKdVk2Kjx9Y

**Comment by CreativeMD** [comment]
Can you try out pre104, it might fix this issue.

**Comment by xunto** [comment]
@CreativeMD No, still the same.

**Comment by CreativeMD** [comment]
Reported it to the author of Valkyrien Warfare, maybe we can fix it.

**Comment by xunto** [comment]
Cool :+1:

**Comment by CreativeMD** [comment]
Looks like the closed it, maybe try it again since it might be fixed.

**Comment by xunto** [comment]
I don't think so, they just closed old ones recently...

**Comment by CreativeMD** [comment]
If it still persist just reopen the issue, although I don't think it will be solved ever (because I have no clue how something like this can happen).
