### ISSUE TITLE
Crash when placing door structure

### ISSUE THREAD

**Issue by SanAndreaP** [CreativeMD/LittleTiles#114]
CreativeCore: v1.9.26
LittleTiles: v1.5.0-pre104
MinecraftForge: 14.23.4.2739

When placing a door structure, I was greeted by this NPE, crashing my game:
https://paste.dimdev.org/bicexazoqo.mccrash

It happens every single time. Static structures work fine.
Here's my latest.log: https://gist.github.com/SanAndreasP/f4ea9d6ac3cbef5f3e0db6a6cd92eb94

**Comment by SanAndreaP** [comment]
PS: could you also add gradle to your repo? I'd like to help out on issues but can't, since I don't have any buildscript to test it with.

**Comment by CreativeMD** [comment]
I made a video about how I setup my workspace: https://www.youtube.com/watch?v=7Ahshi_QjM4

**Comment by CreativeMD** [comment]
Fixed in pre105. Thanks for reporting this issue.
