### ISSUE TITLE
Crash when closing door structure, again

### ISSUE THREAD

**Issue by SanAndreaP** [CreativeMD/LittleTiles#115]
CreativeCore 1.9.27
LittleTiles v1.5.0-pre105

Basically like #104, just a different line number in the first line of the stack trace

https://paste.dimdev.org/cohiviqaro.mccrash

**Comment by CreativeMD** [comment]
Not the same issue, but a new one :( I will try to fix it.

**Comment by CreativeMD** [comment]
Does it happen every time? No idea how this could happen.

**Comment by CreativeMD** [comment]
Maybe this version fixes the problem? https://www.dropbox.com/s/aadfxk7eziio7yw/LittleTiles_v1.5.0-pre106_mc1.12.2.jar?dl=1

**Comment by SanAndreaP** [comment]
With that version I don't get a crash, even after multiple openings and closings in a row, so I'd say it works now.

**Comment by CreativeMD** [comment]
The new version has been uploaded, it should be available soon.
