### ISSUE TITLE
Client crash  - Gathering more information from the player.

### ISSUE THREAD

**Issue by ProsperCraft** [CreativeMD/LittleTiles#120]
https://paste.dimdev.org/vobalununa.mccrash

This does not happen every time, as other players have loaded and logged in to the server without issues.

This is a fresh world.

**Comment by CreativeMD** [comment]
Maybe try to use forge prior to 14.23.4.2759?

**Comment by CreativeMD** [comment]
Okay Forge isn't the problem. Looks like an issue caused by another mod. Although LT appears in the crash-report something is messed up (not caused by LT). Maybe try to remove other mods and see if the crash still occurs?

**Comment by CreativeMD** [comment]
Any news about this issue?

**Comment by ProsperCraft** [comment]
I have not had any new reports of this happening

**Comment by CreativeMD** [comment]
I will close it for now, just reopen it if it happens again.
