### ISSUE TITLE
[suggestion] add method to update(relight) all loaded LTte's at once.

### ISSUE THREAD

**Issue by Dushess** [CreativeMD/LittleTiles#121]
Yes it will be slow, but manual restoring of lighting after some things is really difficult. When you have lot of them, working with wrench is looong procedure. (Yup, that's me with mcedit. But doing it ingame with worldedit - not sure, game already using ~60-80% ram on his workspace + building, managing large parts ingame is not an option)

**Comment by Dushess** [comment]
Of course a+f3 absolutely useless

**Comment by CreativeMD** [comment]
You can use mcedit to mark it, so no minecraft will recalculate the lighting

**Comment by Dushess** [comment]
I can't find it, RELIGHT will do it wrong, as i know. Maybe already outdated 1.6.0.32, that i have, don't have it? Thet will check on 52

**Comment by CreativeMD** [comment]
Relight should be it. Once minecraft will load it the light will be recalculated, but I'm not 100% sure about it.  I hope it works. I will close this issue, because it's not something i'm going to add to LT, sorry :(..

**Comment by Dushess** [comment]
Wrong, relight will do his job, but it don't know, that LT blocks are not vanilla cubic things, every tile will be unlit, and i'll need to update every of them manually. Just saving the world gives same result on any custom tile-entity. Probably i need to disable light recalc on save event.

**Comment by CreativeMD** [comment]
Maybe there are other tools for it? I never had this problem, so I can't really help you :(

**Comment by Dushess** [comment]
Uhh, i have a crunchy idea, use combining event from wrench. It works, but currently only manual. Easiest thing should be apply it to all currently loaded tiles(one button somewhere in grid selection window to activate). Rought, but simple. To save perfomance, not every LT block, but each 5th on all axis.

**Comment by Dushess** [comment]
Ah, i know, that's because map generator template is mcedit, not mc server.

**Comment by CreativeMD** [comment]
I hope it is solved now, if not maybe worledit has a command for it.

**Comment by Dushess** [comment]
Will check it
Nah, 1.12.1 only

**Comment by ghost** [comment]
@Dushess placing glowstone will relight nearby blocks (blocks which no more than 16 blocks away) - a quick way to manually relight stuff.

**Comment by Dushess** [comment]
I will try to place glowstones in affected area and save it, probably it can fix broken lightmap.

**Yep, it works.**

**Comment by Dushess** [comment]
Oh, just now remember about it (continuing discord thread) it should be enabling option, setting grid back to 16 and loading again used map?

**Comment by CreativeMD** [comment]
There is a config option for that: forceToSaveDefaultSize, just enable that one load the entire world and make sure every chunk has been loaded at least once. Afterwards disable the option again and set your new preferred default grid size.
