### ISSUE TITLE
Client crash - 

### ISSUE THREAD

**Issue by ProsperCraft** [CreativeMD/LittleTiles#124]
I was getting out of a betweenlands boat, 

https://gist.github.com/ProsperCraft/c9550b9b8a3737116f8e867347f0f167

https://minecraft.curseforge.com/projects/ancient-towncraft

**Comment by ProsperCraft** [comment]
Reproduced here - https://paste.dimdev.org/ufopetelik.mccrash
https://paste.dimdev.org/ahogeqabut.mccrash
https://paste.dimdev.org/xuxayugoza.mccrash
https://paste.dimdev.org/utodimotax.mccrash
No crash on exit.
then crash by another player death- https://paste.dimdev.org/gitiyeloxu.mccrash
No crash on exit
https://paste.dimdev.org/azugawirex.mccrash
https://paste.dimdev.org/nibuqusequ.mccrash
https://paste.dimdev.org/epoyiyujip.mccrash

**Comment by CreativeMD** [comment]
Should be fixed in the upcoming version.
