### ISSUE TITLE
Performance review request. - GetCollisionBoxesEvent.

### ISSUE THREAD

**Issue by ProsperCraft** [CreativeMD/LittleTiles#125]
This Event subscriber is taking an insane amount of tick - 

![2018-09-11_23 38 52](https://user-images.githubusercontent.com/4427684/45404493-6edb3780-b61c-11e8-8fe3-cdfdf7839912.png)

Find attached sampler nps file for viewing in visualvm
[littletiles.zip](https://github.com/CreativeMD/LittleTiles/files/2373740/littletiles.zip)

Here is a warmroast -

https://sparkprofiler.github.io/?wnml2tmIUN

**Comment by CreativeMD** [comment]
Ok, I'm not really sure whether this is anything serious or not. I can't find anything on the warmroast you send me. Can you record another? I don't know how the ingame profiler works, so I need more information in order to tell whether this is a bottleneck or not.

**Comment by ProsperCraft** [comment]
I don't think warmroast catches Event Subscribers like lagoggles does.

Anything in the nps samples?

**Comment by CreativeMD** [comment]
Yeah, that's the thing, my impression is that the performance impact is ignorable.

I don't know how to open the nps samples.

**Comment by ProsperCraft** [comment]
https://wiki.industrial-craft.net/index.php?title=Using_Sampler

**Comment by CreativeMD** [comment]
![](https://i.imgur.com/X6ejuTq.png)

**Comment by ProsperCraft** [comment]
Did you unzip it?

**Comment by CreativeMD** [comment]
Of course :D

**Comment by CreativeMD** [comment]
I will close this issue for now, if you have any further information about it (another record or something similar), just reopen it.
