### ISSUE TITLE
Crash w/ Thut Crafts Mod

### ISSUE THREAD

**Issue by WenXin20** [CreativeMD/LittleTiles#126]
Forge 14.23.4.2757-1.12.2
[Thut Crafts](https://minecraft.curseforge.com/projects/thutcrafts) v0.2.1
Little Tiles v1.5.0 Pre 111
After creating a simple chiseled block using Little Tiles, I got a crash when using the Little Recipe item from that mod to try to select and copy that block. I wasn't sure where to post it, so I also reported it here: 
Thutmose/ThutCrafts#3
[Crash Report](https://paste.dimdev.org/qecemehabu.mccrash)

**Comment by CreativeMD** [comment]
I can't see anything suspicious on my end.

**Comment by CreativeMD** [comment]
I will close this issue for now, because I don't think it's an issue of LittleTiles. If the author of ThutCrafts replies to his issue, I will be there to help out if necessary.
