### ISSUE TITLE
Crash with a door

### ISSUE THREAD

**Issue by DcNdrew** [CreativeMD/LittleTiles#127]
Hey!
I tried to make a sliding door. I don't know if it counts, but here is what I did, and in every step I put the tiles to a recipe.
First I made the body of the door. Next I made the frames of it and the third part was the handle.
I put the whole to a recipe and made it a sliding door. Clicking on the door itself it didn't do anything, but clicking on the handle opened it. When I clicked on the handle again, before the door has closed, the game crashed. Here is the log:
https://paste.ee/p/rrhyU

**Comment by CreativeMD** [comment]
Can you send me your world so I can try to reproduce it?

**Comment by DcNdrew** [comment]
I'm sorry, but I removed the door and the recipe too. :/
Well, other thing, it may has connection to the problem: I made wardrobes, but their doors doesn't work sometimes. They are in block. Can be problem if the opening door will reach in another chunk? I din't try it yet.

**Comment by CreativeMD** [comment]
No, but a door has to have space, otherwise it won't open. Can you try to rebuild this sliding door?

**Comment by DcNdrew** [comment]
I'll try. Sorry, but I forgot to answer.

**Comment by DcNdrew** [comment]
I think I got it! I set the body of the door fixed!
https://www.dropbox.com/s/p2bl0opt8k5e0q2/Testing%20world.zip?dl=0

**Comment by CreativeMD** [comment]
Can you update to pre114 and see if it is fixed?

**Comment by DcNdrew** [comment]
Same crash with pre114.

**Comment by CreativeMD** [comment]
Fixed it in pre115, thank you very much for reporting this issue, it was a rather serious issue!
