### ISSUE TITLE
Request: Redstone

### ISSUE THREAD

**Issue by zISKo666** [CreativeMD/LittleTiles#128]
Hello,

I am kindly request the implementation of redstone signals for the doors and maybe other things.
Would be more survival friendly then the command block stuff.

And an up to date tutorial for 1.5.0 would be also really nice.

Kind regards

zISKo

**Comment by Dushess** [comment]
Planned, we all waiting.

**Comment by CreativeMD** [comment]
It is planned and will be part of 1.5.0.
There is an wiki on github which is up to date: https://github.com/CreativeMD/LittleTiles/wiki
