### ISSUE TITLE
Advanced recipe bugs

### ISSUE THREAD

**Issue by Achievable** [CreativeMD/LittleTiles#129]
Here's a list of bugs I've found with the latest update (pre113) 

- Using the advanced recipe on an existing structure results in huge scale when set to default. Manually changing to bigger scales does not let you save, while smaller scales work properly.

- Using the advanced recipe on an existing structure _while adding any kind of tile_ works as intended.

- This logic seems to accumulate further on. Using the recipe on the working result breaks it again, while adding an additional tile to that fixes it all over again. 

- Adding regular blocks instead of tile breaks as well.

- Doors seems to be the exception of this, since combing then with tile results in the same bug.

- Combining multiple sliding doors can be placed as a structure, but when interacted with results in a  [crash](https://github.com/CreativeMD/LittleTiles/files/2475312/crash-2018-10-13_12.31.08-server.txt)

I'm attaching my [test world](https://github.com/CreativeMD/LittleTiles/files/2475319/Tilestest.zip) with all my experiments.

**Comment by CreativeMD** [comment]
Can you try out pre115 and see which of those bugs still persist?

**Comment by CreativeMD** [comment]
All of these issues will be resolved in pre116, thanks taking to the time to report it!
