### ISSUE TITLE
v1.3.0 for 1.10.2 Crashes while loading

### ISSUE THREAD

**Issue by Kumomo** [CreativeMD/LittleTiles#13]
No crash log, but I think this is the [correct client log](http://pastebin.com/EATWC8W4). 

I started with LittleTiles, Chisel, C&B, and JEI installed and it crashed. Removing LittleTiles allows for regular startup. Having just LittleTiles crashes.

LittleTiles v1.3.0
Minecraft 1.10.2
Forge 12.18.3.2221

**Comment by CreativeMD** [comment]
Don't forget to install CreativeCore as well.

**Comment by Kumomo** [comment]
Ah ok, I'll go try that. You should note that on the LittleTiles page though or most people won't know it's needed. Usually when it's missing a dependency the game still loads then goes to that brown screen that tells you that you're missing x dependency instead of crashing.

**Comment by CreativeMD** [comment]
Yep, totally right i added it.
