### ISSUE TITLE
wierd hollow elipsoids

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#130]
Hollow elipsoids created with chisel:sphere have holes

**Comment by ghost** [comment]
![2018-10-13_22 21 38](https://user-images.githubusercontent.com/32820765/46915991-f53cbd80-cfbc-11e8-864c-c5417c942be5.png)

**Comment by CreativeMD** [comment]
That's a known issue, if you have a perfect sphere it works fine, but as soon as you stretch it this occurs. I recommend to increase the thickness to fix it.
