### ISSUE TITLE
Outline of where LT blocks are being placed isn't there anymore (

### ISSUE THREAD

**Issue by stupidoemstero** [CreativeMD/LittleTiles#131]
I had other issues in the past so I downloaded the newest versions of LT and CreativeCore, but now the outline of where made blocks, doesn't matter if hammered or full doors/beds/etc, isn't there anymore, glitchy at best.
I do believe it's a problem with either OptiFine or thaumcraft but I would like to keep playing with both. 
If you could help it would be great, Thanks! 

forge1.10.2-12.18.3.2254
![image](https://user-images.githubusercontent.com/44178591/47003270-25a46900-d12f-11e8-8e6c-6d00e822281f.png)

**Comment by CreativeMD** [comment]
Sorry, but I don't support 1.10.2 anymore. I highly recommend to update to 1.12.2. Thaumcraft has already updated.

**Comment by stupidoemstero** [comment]
alright, I'll try it out. Thanks for the quick answer

Ok just changed all mods to 1.12.2 and tried it again, same problem. When OptiFine is in the mods folder I can't see the outline of the LT blocks

![image](https://user-images.githubusercontent.com/44178591/47011006-01518800-d141-11e8-8169-4d91bc96d810.png)
