### ISSUE TITLE
LT blocks Outline isn't visible

### ISSUE THREAD

**Issue by stupidoemstero** [CreativeMD/LittleTiles#132]
Ok just changed all mods to 1.12.2 and tried it again, same problem. When OptiFine is in the mods folder I can't see the outline of the LT blocks

forge version: 14-23-4-2759

![image](https://user-images.githubusercontent.com/44178591/47093843-50bfb300-d22a-11e8-96c8-250d0efefe35.png)

**Comment by kirokadura** [comment]
I tested it out and I couldn't replicate it. When you say outline, you mean like this, right?
![2018-10-17_16 01 41](https://user-images.githubusercontent.com/29471180/47109954-02a8b080-d226-11e8-946a-fa88598d3273.png)

Or maybe the preview?

![2018-10-17_16 07 00](https://user-images.githubusercontent.com/29471180/47110273-bc078600-d226-11e8-820a-afaf172a62fc.png)


I'm also using the same mod versions as you, so maybe an setting on Optifine is disabling it?

**Comment by stupidoemstero** [comment]
ok yeah, I did mean the preview

here's without OptiFine in the mods folder (or shaders disabled)
![20181017221550_1](https://user-images.githubusercontent.com/44178591/47113939-a318c800-d25a-11e8-9e12-f4f2f1e6912f.jpg)

and with Optifine active (shaders enabled)
![20181017221725_1](https://user-images.githubusercontent.com/44178591/47113957-b4fa6b00-d25a-11e8-9d10-d5b1c2c2efbf.jpg)

Now when I turn shaders off in the shaders menu, the preview is back

shader I use: Wisdom-Shaders-V3.2-Release-Build3230

**Comment by kirokadura** [comment]
Yeah that's a shader specific problem. I seen the preview work on some shaders, but never 100%.

**Comment by stupidoemstero** [comment]
Alright, do you maybe have a list of shaders (that might work) that I could try out?

**Comment by CreativeMD** [comment]
BSL, Seus, Slidur, actually most shaders should work. Unfortunately there is nothing I can do about it. It's an issue of the shader.
