### ISSUE TITLE
Crash during startup... on ANY mod version

### ISSUE THREAD

**Issue by esotericdesign** [CreativeMD/LittleTiles#135]
I tried a few of the last mod versions, and they all crash with a UCHEE code (which I have never seen before. shouldn't it do so after a first error?). I downgraded to the first 1.12.2 release and it still gave the same code.
Am I missing something?
Can't find any logs at the moment (probably erased them), but if necessary, I can easily get one by reproducing

**Comment by kirokadura** [comment]
A crash log would be very helpful, but can you also describe what CreativeCore version you are using?

**Comment by esotericdesign** [comment]
1.9.32, but when I downgraded, I reverted it as well.

P.S. There are also OPFrame and IGCM in my modpack, neither ever complained

**Comment by esotericdesign** [comment]
Let me get one for you...

**Comment by esotericdesign** [comment]
Er... anyone there? here's a crash log...
[2018-10-28-1.log](https://github.com/CreativeMD/LittleTiles/files/2531089/2018-10-28-1.log)

**Comment by CreativeMD** [comment]
Please update CreativeCore, LittleTiles, OnlinePictureFrame and IGCM, this should fix your issue.
