### ISSUE TITLE
[pre123] Bug Report and Suggestions

### ISSUE THREAD

**Issue by kirokadura** [CreativeMD/LittleTiles#137]
Here I am with a few bug reports and a couple of suggestions.

Using:

CreativeCore v1.9.36
LittleTiles pre123
Forge 2658

**BUGS**

**1-** Sleeping your bed always makes you face the same way, regardless of the chosen direction. It seems your character body adapts to the select position but your vision is always facing the same direction.

Here's the beds I'll be using, each set to a different direction:
<img src="https://user-images.githubusercontent.com/29471180/48919095-0ad4bb00-ee78-11e8-9c2a-df5beb7c83ec.png" width="400">

South:
<img src="https://user-images.githubusercontent.com/29471180/48919097-0c9e7e80-ee78-11e8-86ec-eda489a5fd1c.png" width="400">

West:
<img src="https://user-images.githubusercontent.com/29471180/48919098-0dcfab80-ee78-11e8-8499-ad45bc5c70a3.png" width="400">

North:
<img src="https://user-images.githubusercontent.com/29471180/48919099-0e684200-ee78-11e8-8277-c25366c84381.png" width="400">

_______________________________________________________________________________________________________
**2-** Undoing Slices sometimes causes weird leftovers when they overlap other structures.

Using this structure as an example:
<img src="https://user-images.githubusercontent.com/29471180/48919240-b847ce80-ee78-11e8-98c6-0f7d9eae209f.png" width="400">

Covering it in slices (using grid 2):
<img src="https://user-images.githubusercontent.com/29471180/48919242-bb42bf00-ee78-11e8-94de-a33a6b5f4a1e.png" width="400">

Undoing:
<img src="https://user-images.githubusercontent.com/29471180/48919246-bd0c8280-ee78-11e8-8fce-2b3b1e50753a.png" width="400">

Here's the stairs structure used on this case: [Undo bug.txt](https://github.com/CreativeMD/LittleTiles/files/2609088/Undo.bug.txt)

_______________________________________________________________________________________________________
**3-** Under certain circumstances, you are unable to place fill a space above a slice:

Using grid 2, try placing a pixel like this:
<img src="https://user-images.githubusercontent.com/29471180/48919411-cc400000-ee79-11e8-9bfb-b6a98401c29b.png" width="400">

Then, place slices as to form a ramp:
<img src="https://user-images.githubusercontent.com/29471180/48919413-ccd89680-ee79-11e8-8798-68d230b19ccc.png" width="400">

Next, **using a different material**, place upside down slices against the other slices
<img src="https://user-images.githubusercontent.com/29471180/48919415-cea25a00-ee79-11e8-89fb-385b18d1ddd2.png" width="400">

After that, you're unable to put another pixel above that slice. You can place it on top of the other one.
<img src="https://user-images.githubusercontent.com/29471180/48919417-cfd38700-ee79-11e8-90e9-657f0bbb14f4.png" width="400">

_______________________________________________________________________________________________________
**4-** Replacing a material from an non editable structure type (such as chairs or doors) using the screwdriver causes the structure to replace the materials but turn into a "None" type structure. Attempting to undo that with CTRL+Z crashes the game. Here's the crashlog:

[crash-2018-11-22_16.19.00-client.txt](https://github.com/CreativeMD/LittleTiles/files/2609092/crash-2018-11-22_16.19.00-client.txt)
_______________________________________________________________________________________________________

**5-** There's a major FPS drop when opening a chest full of recipes. The FPS will go back to normal once you close the chest.

Before opening - 116 fps:
<img src="https://user-images.githubusercontent.com/29471180/48919545-859ed580-ee7a-11e8-9dac-b61d947acae8.png" width="400">

After opening - 30 fps:
<img src="https://user-images.githubusercontent.com/29471180/48919547-86376c00-ee7a-11e8-811c-6747ef83bd10.png" width="400">

_______________________________________________________________________________________________________
_______________________________________________________________________________________________________
_______________________________________________________________________________________________________

**SUGGESTIONS**

1- Currently, you can't import a recipe that contains modded blocks into a survival world that doesn't have these mods. Doing so in Creative Mode creates a default pink and black checkered texture, but in Survival Mode the recipe still counts these blocks, and they are unobtainable, so you won't be able to import the structure. So I believe an option to automatically replace these unobtainable modded blocks with a default block (such as Cobblestone, Stone or Dirt), so you have the same type of functionality as in Creative Mode, would be pretty useful.

2- On the same note, you can't easily craft a structure if it contains flowing water/lava (from the LT lava and water blocks) or sideways blocks (such as logs or pillars from chisel). You'd have to, for example, place the water with the chisel, use the bucket on it, then use the hammer to collect it into the bag so the flowing version of the water would go into your bag. If it were somehow possible to detect cases like this and use the default variant of that block automatically, it'd be a great help!

![2018-11-22_16 58 06](https://user-images.githubusercontent.com/29471180/48919852-6acd6080-ee7c-11e8-90ad-94b7ee3df771.png)
![2018-11-22_16 58 44](https://user-images.githubusercontent.com/29471180/48919853-6bfe8d80-ee7c-11e8-9c0f-1484455b24cc.png)

**Comment by CreativeMD** [comment]
Issue 1 & 2 have been fixed. Could not reproduce issue 3. Furthermore issue 4 has been resolved. There is nothing I can do about issue 5. Implemented your suggestions for flowing water. I will expand it in the near future.

If any of the issues still persists just reopen this issue. Thanks for your help!
