### ISSUE TITLE
Chair on Door

### ISSUE THREAD

**Issue by Doc-1** [CreativeMD/LittleTiles#138]
Hello,
The title might be little confusing but let me explain. After learning that doors will push entities I began to see what I could make other than just doors. Elevators worked perfectly then I tried a horizontal lift but they slide from under me. I first tried to add a seat to it and it worked for the most part but it left me where I first sat once the sliding door moved. The only way I got it to work was if I had a wall behind me and was standing.
![2018-11-28_11 11 21](https://user-images.githubusercontent.com/45431412/49165101-70a0c700-f2fe-11e8-8171-d9e447bf9f71.png)
![2018-11-28_11 11 33](https://user-images.githubusercontent.com/45431412/49165106-739bb780-f2fe-11e8-8313-5e4d7cb070a3.png)
Lastly, if you hold shift while riding the door you fall out once you hit the edge.
Thank you, 
This is a amazing mod.

**Comment by CreativeMD** [comment]
It's still a door, elevators might be added in the future till then a door can only push you, there is no way to actually sit on it. If there is an issue related to collision just make short video of it and post it here (that's way easier for me to understand).

**Comment by Doc-1** [comment]
Alas, one can only dream of seattable doors. 
My apologies for not thinking of posting a video of it. I only pass through the door if shift is held, I am on it and the base I am standing on is above the ground by at least 10 pixels. The thickness of the wall is irrelevant. 
![2ccc74e8475d77d4c4c4d44695e5458a](https://user-images.githubusercontent.com/45431412/49259276-c19be280-f406-11e8-8568-fed38a75d6fd.gif)

Thank you,
I look forward to the mod's future updates.

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming version. Thanks for reporting this issue!!!
