### ISSUE TITLE
Phantom Block

### ISSUE THREAD

**Issue by Doc-1** [CreativeMD/LittleTiles#139]
Hello again,
When multiply doors open at the same time and are next to each other sometimes create a phantom block that has collision. It will disappear if the door is updated or after a few seconds.
![ezgif-1-19ecd9cbd427](https://user-images.githubusercontent.com/45431412/49517441-338e8480-f86a-11e8-8c0e-bc9aa7a7c0ed.gif)
Thank you for reading.

**Comment by CreativeMD** [comment]
This might be fixed in the upcoming release. I hope I can release it soon, I would be very happy if you could test it once it is out.

**Comment by Doc-1** [comment]
Of course, I will post my results here.

**Comment by CreativeMD** [comment]
pre123 has been released. Can you see if this issue still persist? If yes can you send me your world?

**Comment by Doc-1** [comment]
Yes the issue still persists. I tried to recreate it but I crash when selecting sliding door, added the crash report here. I did remove chisel so there might be odd shadows here and there. Lastly, you should spawn near the stairs if not, here is the cords (1079, 17, -937). 
(Edit: It doesn't always create the phantom blocks might have to press it a few times.)

[crash.txt](https://github.com/CreativeMD/LittleTiles/files/2789706/crash.txt)

[DOORS! Backup #2 - Copy.zip](https://github.com/CreativeMD/LittleTiles/files/2789698/DOORS.Backup.2.-.Copy.zip)

**Comment by CreativeMD** [comment]
Can you send me your log file? Something must have happened before the crash.

**Comment by CreativeMD** [comment]
Your issue has been fixed and will be part of the next release. Most likely in a few hours (once the crash has been resolved as well).

**Comment by Doc-1** [comment]
Thank you, it works fantastically now. Sorry was at work couldn't send you the log.
