### ISSUE TITLE
Tiles Are Invisible?

### ISSUE THREAD

**Issue by YaBoyEnder** [CreativeMD/LittleTiles#140]
Whenever I try to use LittleTiles, the tiles are invisible, and I figured out that it's an issue with OptiFine. I disabled it and the tiles appeared fine, but after enabling it they disappeared again. I'm using a shader pack, but when I disable the shader pack and leave OptiFine enabled it doesn't fix the issue. This is a problem because I want to be able to use my Shader Pack and LittleTiles at the same time. Any way to fix this issue?

**Comment by kirokadura** [comment]
What version of LT are you using? For the lastest LT version (1.12.2 pre122) you gotta use Optifine E1 or above. Also make sure to disable Render Regions and enable VBOs. If you have trouble with grass and leaves, try changing mipmap to 1 then back to whatever was set before.

**Comment by YaBoyEnder** [comment]
I've already enabled VBO's, but how do you disable Render Regions? (I didn't see it in the video settings (Also, forgive me if that's a stupid question)). But I'll try updating my OptiFine and see if that solves the problem.

**Comment by YaBoyEnder** [comment]
Nevermind, updating my Optifine did the trick. Thanks for the help!

**Comment by CreativeMD** [comment]
Btw you can enable Render Regions, LittleTiles does support it.
