### ISSUE TITLE
Client Crash when opening a bag of tiles looted from a chest.

### ISSUE THREAD

**Issue by ProsperCraft** [CreativeMD/LittleTiles#141]
This was a player on my Ancient TownCraft server - 

First crash
https://gist.github.com/ProsperCraft/5eadabba03027019032e33c63c963055

Crash after whenever he logs in.

https://gist.github.com/ProsperCraft/4e331e8eb5d9a4f5e6b264b8aeab18d0

Playerfile attached-
[littletiles.zip](https://github.com/CreativeMD/LittleTiles/files/2707504/littletiles.zip)

**Comment by CreativeMD** [comment]
The crash should be fixed in the upcoming pre-release. I will let you know once it is out.

**Comment by CreativeMD** [comment]
pre123 has been released
