### ISSUE TITLE
Broken textures with Optifine

### ISSUE THREAD

**Issue by WhiteScorpion7** [CreativeMD/LittleTiles#143]
LittleTiles+Optifine +Odissey resourcepack break vines textures, if "Connected textures" is enabled.

Forge 2770
Little Tiles v1.5.0-pre122
Optifine E2

**Comment by CreativeMD** [comment]
Can you send me a screenshot of it?

**Comment by WhiteScorpion7** [comment]
Sorry, but broken ID is likely not because of your mod. I will delete this string. LittleTiles only make vines invisible.

**Comment by kirokadura** [comment]
Could you try setting Mipmap level to 1?

**Comment by WhiteScorpion7** [comment]
I set it to 1 but nothing has changed.

**Comment by CreativeMD** [comment]
Can you provide a screenshot?

**Comment by WhiteScorpion7** [comment]
![2019-01-23_03 04 28](https://user-images.githubusercontent.com/41969580/51614650-2e2eeb80-1f37-11e9-931e-91c8d63fbb69.png)
Without LittleTiles

![2019-01-23_02 54 57](https://user-images.githubusercontent.com/41969580/51614771-6afae280-1f37-11e9-9c70-2351e9bb9c8d.png)
With LittleTiles

**Comment by WhiteScorpion7** [comment]
![2019-01-23_18 06 39](https://user-images.githubusercontent.com/41969580/51616236-b5319300-1f3a-11e9-8c88-8dfa1ba969f0.png)
With Little Tiles when "Connected textures" are off.
The new version of LT is still the same.

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!

**Comment by WhiteScorpion7** [comment]
Thank you too!
