### ISSUE TITLE
incompatibility between littletile and worldeditMOD

### ISSUE THREAD

**Issue by 9vek** [CreativeMD/LittleTiles#144]
emmm... here just a suggestion from a Chinese high school student...
I did some great works in minecraft with the help of littletilesMOD and worldeditMOD (tried to build a copy of my school!:)), you can't image how excited I was when I found and used littletiles :D. But there are some problems when the littletiles and worldedit are working together.

1, I couldn't use //replace 0 (or some other methods in worldedit) to clean up or replace a small area created by littletiles, when I did this ,it had an impact on the entire cube(16*16*16)
2, It seems that  //copy and //paste also affect  entire cubes. I had some troubles when I just wanted to copy a bar(or etc.) created by littletiles and had to copy the entire 16*16*16 area.
3,  //rotate acted strange on things built with littletiles,.
4......

A lot of incredible works can be done if littletiles get a wonderful compatibility with worldedit!! 
I really like littletiles so I hope you can take my suggestion into consideration,PLEASE!! :D

**Comment by 9vek** [comment]
:D
![image](https://user-images.githubusercontent.com/39913345/52177758-dc247a80-2800-11e9-80ac-162610431665.png)

**Comment by CreativeMD** [comment]
Okay, first of all: WorldEdit is about blocks, so you cannot copy anything smaller than that.
1. Use //set 0
2. As I said WorldEdit can only copy an entire block. Even the recipe of LT only copies blocks, to make things a little bit easier. You should leave space around the stuff you have built. You might want to checkout [LT Recipe](https://github.com/CreativeMD/LittleTiles/wiki/Advanced-Recipe).
3. You can do that with a recipe.

You might want to checkout my youtube channel to learn some of the features of LT and how to use them: https://www.youtube.com/watch?v=HZUqPp7AUzE&index=2&list=PLlH1j2SwU8QqUQIEeUm6MRVZiTFmZtFDW&t=0s
