### ISSUE TITLE
Moving a sliding door to invalid position crashes the game

### ISSUE THREAD

**Issue by PortalInTime** [CreativeMD/LittleTiles#145]
I set a sliding door to go beneath bedrock I had broken in creative mode, only to have it crash the game. I figure the same would happen at any of the other world barriers?

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming update (Most likely today). Thanks for reporting this issue.

**Comment by CreativeMD** [comment]
pre130 fixes it.

Sorry I accidentally clicked the wrong button.
