### ISSUE TITLE
lt-open command does not work on server

### ISSUE THREAD

**Issue by kencinder** [CreativeMD/LittleTiles#146]
Forge 1.12.2-14.23.5.2768
Creative Core 1.9.39
Little Tiles 1.5.0-pre126

No other mods present, the following spams the debug.log when the command is used and a door is at the location and works manually. Issuing the command from the server console, a command block or the player does nothing. Only results in the following in debug.log

https://gist.github.com/kencinder/4a41b4293d2aec07d4341ddac4285f09

I originally noticed an issue with the command on SpongeForge, which oddly unlike plain Forge does work but throws this error on 2nd use of the door(Closing it) when used from the console or a command block.

https://gist.github.com/kencinder/bfce505e051ef90580ba30d6b0359a75

They informed me that you are not checking if on Client or Server, and need to be. Specifically not sending client to server packets when on server.

**Comment by CreativeMD** [comment]
Should be fixed in the newest pre release 127, if it still persists just reopen this issue.
