### ISSUE TITLE
failed to start v1.5.0

### ISSUE THREAD

**Issue by vladislav12384** [CreativeMD/LittleTiles#148]
no other mods are installed, but the launcher still crashes
minecraft v1.11.2
f you need to attach the data

**Comment by CreativeMD** [comment]
You have to install CreativeCore as well.

**Comment by vladislav12384** [comment]
thank you very much, you helped me a lot) also thank you for partially translated the mod into Russian!

**Comment by CreativeMD** [comment]
Somebody else translated it, if you want to contribute as well feel free to do so :D
