### ISSUE TITLE
Structure sudden broken

### ISSUE THREAD

**Issue by eleanoryeung** [CreativeMD/LittleTiles#154]
## Bug
After I reenter the server all my LittleTiles structure is broken including the Little Workbench. I have no idea what is going on, and here are some clues for devs:
* All multiblock structure leaves a single block behind.
* Some of the storage structure can be accessed and some cannot.
* Some of the blocks around the structures are rotated.

## Version
v1.5.0-pre130

**Comment by CreativeMD** [comment]
Can you send me your world?

**Comment by eleanoryeung** [comment]
@CreativeMD I'll ask the server owner if he can sent it here

**Comment by eleanoryeung** [comment]
[world.zip](https://github.com/CreativeMD/LittleTiles/files/3068338/world.zip)
the tiles are at about -1000 65 1000, some of them are fixed in the save file.

**Comment by CreativeMD** [comment]
I couldn't fine any issue. All storage structures just work fine. Same goes for the workbench. Can you provide some screenshot of how it looks for you? Maybe it's an issue from the server?

**Comment by eleanoryeung** [comment]
That's really weird. It might be a server problem or some mods interactions.
At that time it looks like this:
![Snipaste_2019-04-12_10-32-59](https://user-images.githubusercontent.com/7261604/56008334-87284780-5d0e-11e9-92d0-610586b66b95.png)
If you try to break them it tells something like: structure not formed (I cannot clearly remember)

**Comment by CreativeMD** [comment]
So is it fixed now? I'm pretty confused at the moment. It might just be a server issue. If it happens again just reopen this issue.

**Comment by eleanoryeung** [comment]
We have roll back the chunk so I cannot provide much useful information, I'll report if something happen again.
