### ISSUE TITLE
[pre130] Bugs and Suggestions

### ISSUE THREAD

**Issue by kirokadura** [CreativeMD/LittleTiles#155]
Bugs:

1 -Glove colors revert to default (255) when changing from Pixel Mode to Replace. 

Steps to reproduce: Go to pixel mode, select a block and color. Change to Replace Mode and exit the GUI. The color will have reverted back.

2-Glove tile size in Pixel Mode resets when changing from Replace Mode

Steps to reproduce: Go to Pixel Mode, select a size, exit GUI. Then reopen the GUI, go to Replace Mode, then back to Pixel Mode. The sizes will  go back to 1.

--------------------------------------------------

Improvements/suggestions:

-Change the block icons on the bag so they are always full, even if it's less than a block. Sometimes it's hard to tell at a glance what that block is.

-Adjust the size of the block currently selected in some tools (such as the chisel and glove) that shows in the inventory icon texture. Currently the block completely obscures the tool, so it's difficult to tell the difference between the glove and chisel.

-Add a block preview for the the chisel menu, so you can better see what it'll look like when colored, just like in the glove's Pixel Mode.

-Show bit amounts when hovering over the block selection on the chisel, so you know how much material you have in your bags.

-Add colors selection on the Glove Replace Mode. Currently you have to go to Pixel Mode to select the color and then back to replace.

-Allow the search bar to lookup the block descriptions too (for things like Chisel variants)

-Hability to rename bags. When you have a lot of bags it's kinda of hard to know where that specific material you're looking for is.

-Maybe add bags with more slots?

**Comment by CreativeMD** [comment]
**Block preview in chisel menu:**
Hm ... the player can see the selected block and color. It would require to redo the gui as there is not enough space. What are your thoughts?

**Ability to rename bag:**
Not sure about that one either, you can use the anvil to rename items. In my eyes that is enough (recipes are an exception to this because you will have many of them).

**Adding more slots:**
I don't want it to be overpowered, it should not replace a regular bag. What is causing it? Is it the amount of space or the number of different materials?

**Comment by kirokadura** [comment]
**About the block preview in the chisel menu:**

I think the best solution would be to make the color preview square smaller (since it only shows the color, it being smaller shouldn't interfere) and move it slightly upwards so there is enough room for the preview (which shouldn't use as much room as it does in the the glove GUI, since there's no need for size sliders). I currently don't feel like the color preview+selected block is enough to determine the result, as there are cases where a darker block may distort the original color too much.

**About the ability to rename bag:**

Completely forgot about the anvil, my fault there.

**About adding more slots**

I feel like two things are the major problems: 

- The lack of ability to easily remove materials that are not full blocks: you can easily remove things you don't use as long as they are full blocks, but lots of leftovers are a pain to remove.

- The amount of different materials: especially if you count Chisel variants and blocks that have different orientations (such as sideways logs, or different LT water/lava flows).

If the first issue is resolved, I believe there wouldn't be a need for an upgraded bag.

**Comment by CreativeMD** [comment]
Ok did the first thing, the second one was already on my todo list. It requires some more work and thoughts. I will attack it after the door rework.

Thank you very much for you help!!!
