### ISSUE TITLE
Modified Blocks Turn Completely Black

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#156]
I been wanting to use this mod but every customized block I make with the hammer, the texture on items are coming on as they should but when they are placed down their completely black and I been trying to fix this myself in ways but I have no luck on fixing this playing with this mod in 1.7.10. Please help update this fix for a new version in 1.7.10 because all of most mods I have 1.7.10 and no other higher versions of Minecraft.
![2019-04-10_17 14 01](https://user-images.githubusercontent.com/32603949/55914022-1836db80-5bb4-11e9-8de8-f337dd3fd8df.png)

**Comment by kirokadura** [comment]
Do you perhaps have Smooth Lighting Off? It needs to be On for the mod to work on the 1.7.10 version.

**Comment by CreativeMD** [comment]
Yep, turning on smooth lighting should fix it.

**Comment by ghost** [comment]
Thank you for letting me know.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
