### ISSUE TITLE
Crash [IndexOutOfBoundsException]

### ISSUE THREAD

**Issue by Freebi85** [CreativeMD/LittleTiles#157]
Crash after placing blocks with Little Tiles advanced recipe and undone it.

Minecraft 1.12.2
Forge .2822
LittleTiles_v1.5.0-pre130
https://paste.dimdev.org/xibehutala.mccrash

**Comment by CreativeMD** [comment]
This crash is caused by architecturecraft (https://minecraft.curseforge.com/projects/architecturecraft-elytradev).
