### ISSUE TITLE
Doors break when closing over rail

### ISSUE THREAD

**Issue by Larky2k** [CreativeMD/LittleTiles#159]
Hi, When making a door with a notch cut out of it for Vanila Rail/Immersive Railroading Rails the doors close then break after the animation. Is it possible for the doors not to do this as I'm trying to make a locomotive shed door and little tiles would be perfect except for this small issue.

**Comment by kirokadura** [comment]
For things like rails, torches and fences, cutting out the shape is not enough, as the whole block is occupied by that torch, rail, etc. There are a couple things you can try doing: 

- Make it an Advanced Door, give it a slight rotation (enough so it can't place itself, but not enough to be noticeable) and place it in the spot where it would be open before, so when it opens it actually does not place itself, but stays as an entity. That way it can go "through" the rails without breaking.

- Mark the option "Keep Animated" from the latest version, place the door down (without the rail), open the door, place the rail, then close the door. I suggest this method.

You can keep the notch on the door so it looks more natural, but in the end it'll not matter.
