### ISSUE TITLE
Getting a client crash. :<

### ISSUE THREAD

**Issue by CMCarlsen** [CreativeMD/LittleTiles#16]
MC Version: 1.10.2
Forge version: 12.18.3.2221

Working with the utility knife, I cut a (I believe) ExtraUtils glass block. It seemed to drop the half-block, but upon placing the block, it disappeared. It had a collision box, but the second I touched it, it crashed my client. I relaunched and then, in an attempt to remove the ghost-blocks I hit it with a T-Construct hammer. I crashed again.

Update!:
I was able to use the Utility knife to cut a glass block in an width 8 plane. I then proceeded to place it. It was visually fine, but upon stepping on it/touching it, my client crashed again. D:

Looking forward to getting this puppy working though! Thanks for your work. <3

Crash log:
http://pastebin.com/3wR2nYT5

**Comment by CreativeMD** [comment]
Tested it with Thickened Glass and had no crashes, it would be interesting to see what the crash log of the second crash was. If you have troubles to destory the block just use `/setblock <x> <y> <z> minecraft:air` command to remove it.

**Comment by shortybsd** [comment]
Minecraft 1.11.2
Forge 2223
LittleTiles v1.3.1 mc1.11.2

Getting same exact issue http://pastebin.com/E95BfH34
I tried to cut a piece of stone floor with the knife, the whole block disappeared then every time i am in game and look at the missing block I get that crash. Removed the mod and no more crashes. I will check back later after this is resolved to try out the mod again. Also recipe for knife conflicts with RFTools wrench. I had to use a Super Crafting Frame to flip through the conflicting recipes.

**Comment by CreativeMD** [comment]
Please try to use the newest version 1.3.3, maybe this fixes it.

**Comment by CreativeMD** [comment]
Issue closed due to inactivity. I assume the crash is fixed.

**Comment by CMCarlsen** [comment]
I honestly haven't had a chance to test this due to school and such. I'll do what I can to try and test it when I get some time, but I'm not sure when that'll be.

I'd say just leave this closed if that's cool. I'll notify otherwise if I get a chance.

Thanks for your time!
