### ISSUE TITLE
Missing english translation for controls

### ISSUE THREAD

**Issue by LemADEC** [CreativeMD/LittleTiles#163]
As of LittleTiles_v1.5.0-pre135_mc1.12.2, key control descriptions are missing English translation.
![image](https://user-images.githubusercontent.com/4776032/57049473-85500500-6c78-11e9-927e-cb8fe6a88446.png)

**Comment by EdgewalkerBlue** [comment]
Yes, I have the same problem here, too，and  Advanced drawing for door animation effects preview, sometimes not shown

**Comment by CreativeMD** [comment]
Added them, will be part of the upcoming pre-release (maybe this week). I will close this issue for now. Thanks for reminding me!
@EdgewalkerBlue create a new issue and it would be awesome if you could provide a screenshot of the problem.
