### ISSUE TITLE
[Forge/LittleTiles] Shader visual artifacts (research)

### ISSUE THREAD

**Issue by KobaltCode** [CreativeMD/LittleTiles#165]
I noticed the closed issues pertaining to using LittleTiles with shader packs.
I did some research. Specifically previews not showing for tools such as the chisel and hammer. I observed a similar issue with Immersive Engineerings [tank ](https://ftb.gamepedia.com/Tank_(Immersive_Engineering))multi-block structure (the gauge that shows the levels). 

I've compiled some [screenshots](https://imgur.com/a/kmoClxG) of the issue.

Reducing or turning off settings (specifically) bloom and temporal AA) will bring the preview grid back. A possible solution (workaround?) could be to increase alpha values for the lines drawn in previews so they don't get torn apart so bad during post-processing.

**Comment by CreativeMD** [comment]
Actually this is an issue of the shaderpack and not the other mods. There is nothing I can do about it sorry :(
