### ISSUE TITLE
Doors unopenable; interacting with door "clones" and spawns a new door

### ISSUE THREAD

**Issue by noobanidus** [CreativeMD/LittleTiles#166]
This is from a user on my server. They have a double door set up:

![](https://cdn.discordapp.com/attachments/550101067140956170/574469336450859019/2019-05-05_02.33.25.png)

Unfortunately, while it is possible to open the right-hand door, opening the left one simply spawns a "clone" door that opens, while the left one remains stationary. Here's a video of myself opening the right door successfully but failing to open the left door:

![](https://thumbs.gfycat.com/IncompatibleNeatBufflehead-size_restricted.gif)

We did somehow manage to break all of the doors that had spawned, including the original, which all appear to be client-side "duplicates" as relogging removed them. However, after replacing the door (which did not appear on my client), the right hand door started bugging out.

It appears as though this is a purely client-side glitch. However, in all instances, TOP did not report that I was targetting "anything", but I was able to right click on the area where the door should be (the user had already broken it) and "open" it again.

I understand this is a confusing issue. I'll try to give as much information as I can on the matter should you need it.

The mod-list for the server is [here](https://gist.github.com/duely/53900d9eb872a5db2e828777842b8e9c) but that list is outdated, as Malisis Doors and Malisis Core were removed for performance reasons.

Quark's "double doors open together" functionality is enabled, but I'm not sue if that has any impact on your code.

Let me know what further information I can provide and how I can help!

**Comment by CreativeMD** [comment]
That is a weird issue. I have reworked the code last week, but it's not released yet. It will be part of the upcoming pre-release (not sure when it will be ready). I hope it fixes this issue, I will let you know once it is out so you can test it.

**Comment by katubug** [comment]
We are also having this issue, so I'll happily help you test out the new version when it's ready!

**Comment by CreativeMD** [comment]
This should be fixed now. If it still occurs just reopen this issue.
