### ISSUE TITLE
Resizing a piece with the hammer causes it to lose meta value

### ISSUE THREAD

**Issue by tlitookilakin** [CreativeMD/LittleTiles#17]
causes all wood pieces to become oak, wool pieces to white, little-tiles texture blocks all become "clean" texture, etc.

To replicate:
hammer an item with a meta value of >0 (birch planks)
hammer the pieces a second time

**Comment by CreativeMD** [comment]
Should be fixed in the newest version (v1.3.2). Thanks for reporting.
