### ISSUE TITLE
Dupe bug with Little Bag

### ISSUE THREAD

**Issue by Aiidoneus** [CreativeMD/LittleTiles#171]
Forge Version: forge-1.12.2-14.23.5.2837-universal.jar
CreativeCore Version: CreativeCore_v1.9.45_mc1.12.2.jar
LittleTiles Version: LittleTiles_v1.5.0-pre135_mc1.12.2.jar

Steps to reproduce:
1. Install the mods with the forge version on a server. (Dupe only works on a server environment) 
2. Get yourself a Little bag and a items that go in the bag. (I used Iron Ore)
3. Put the items in the bag
4. Open and drop the bag at the same time. 
5. Take the items from the bag in the GUI. 
6. Go and pick the bag dropped on the ground.
7. Take duplicated items

Video of dupe: https://youtu.be/QEwdykfMG8c

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming version. Thank you very much for pointing it out!!!

**Comment by CreativeMD** [comment]
It is out now! Thanks again for your report.

**Comment by Aiidoneus** [comment]
You are welcome!
