### ISSUE TITLE
[SUGGESTION] Door animation

### ISSUE THREAD

**Issue by Archilyte** [CreativeMD/LittleTiles#174]
It would be very cool to have different animations for door closing and door opening. It will be helpful for making rotating doors, as well as other things. For example, the door opens using a specific animation, but closes using another, instead of using a reversed version of the opening animation.

**Comment by CreativeMD** [comment]
Thanks for your suggestion. I will add it to my todo list and close this issue for now. I can't promise when I will implement it (might take some time, not sure whether to do it before redstone or after).
