### ISSUE TITLE
Little Importer and Little Exporter aren't compatible with The One Probe?

### ISSUE THREAD

**Issue by katubug** [CreativeMD/LittleTiles#177]
When I hover over the Little Importer and Little Exporter, TOP only shows me what tool to harvest them with, not the name of the item. And it's not easy to tell which is which unless you open their interface.

Versions:
LittleTiles_v1.5.0-pre135_mc1.12.2
theoneprobe-1.12-1.4.28
forge-1.12.2-14.23.5.2838-universal

Screenshot:
![2019-05-28_20 52 00](https://user-images.githubusercontent.com/20935286/58523583-94987480-818a-11e9-8f26-b9939658891c.png)

**Comment by CreativeMD** [comment]
TOP caused many many issues with LT (performance wise and crashes), so I had to remove all interactions. That's why TOP doesn't show any information anymore.

**Comment by katubug** [comment]
Ah, understood. Thanks for the response!
