### ISSUE TITLE
Some tile structures save to Little Recipes as giant white boxes?

### ISSUE THREAD

**Issue by katubug** [CreativeMD/LittleTiles#178]
I'm hovering over the recipe in this screenshot. It's meant to be a large bay window, but you can see it's showing up as a vaguely-window-shaped white box thing.

![2019-05-28_20 50 57](https://user-images.githubusercontent.com/20935286/58523688-0ffa2600-818b-11e9-856c-a24234a7aca9.png)

The problem persists when trying to place it: 
![2019-05-28_20 51 06](https://user-images.githubusercontent.com/20935286/58523729-2acc9a80-818b-11e9-971c-ae11e3f18ad2.png)

But once placed on the ground, it looks like it's supposed to:
![2019-05-28_20 51 15](https://user-images.githubusercontent.com/20935286/58523736-3029e500-818b-11e9-8514-1d324b0b6b7f.png)

My only guess is that it might be tied to the amount of bits used? Because when I selected everything but the front face of the window, it renders fine. Or maybe it's to do with selecting non-bit LittleTiles blocks like Tile Structures or Slices? I really don't know enough to say, but I hope that gives you a good starting point.

Please let me know if you have any questions or want me to test anything. Thanks!

Versions:
LittleTiles_v1.5.0-pre135_mc1.12.2
theoneprobe-1.12-1.4.28
forge-1.12.2-14.23.5.2838-universal

**Comment by CreativeMD** [comment]
That's not a bug, but a feature. It's called low resolution mode and has been added to prevent your game from excessive lag ([video](https://www.youtube.com/watch?v=-cXUvL1D8SQ)).

If you want to see the preview in all the detail, you use the markmode. Just activate it by pressing 'M', it will make the preview stick to the current position. Then press 'CTRL + M' and deselect low resolution. You can move it by using the arrow keys (and move it up/down when holding sneak and using the up/down arrow keys).

**Comment by katubug** [comment]
Ah, I see! Thanks very much for the detailed explanation and the video!
