### ISSUE TITLE
Storage Blocks Will Not Work With Hoppers/AE2/RS/SSN/RFTools

### ISSUE THREAD

**Issue by Guswut** [CreativeMD/LittleTiles#180]
Hello,

It appears that storage blocks aren't able to interface with any external method of dealing with storage such as vanilla hoppers, and external storage connectors for Applied Energistics 2, Refined Storage, Simple Storage Networks, and the remote storage scanner from RFTools.

The ideal solution would be that we could use any Little Tiles storage block like any other storage block such as connecting them to a storage system, using hoppers, etc.

Attached is a video showing how it isn't interacting.

https://imgur.com/7Su33sb

Thanks!

**Comment by CreativeMD** [comment]
Unfortunately that is not a bug, but this feature has not been implemented. It's not that easy to be honest. LT is very dynamic and its impossible to do this properly with the current system. It has been requested several times and i have added it to my todo list, but I can't tell you when I will find the time for it. I won't implement it in 1.5.0, sorry. So you will have to wait very long for it :(
