### ISSUE TITLE
Complex Door Glitch

### ISSUE THREAD

**Issue by arceste** [CreativeMD/LittleTiles#182]
Minecraft Version: 1.12.2
LittleTiles Version: 1.5.0-pre135
I made a complex door, however when I travel a distance from the door, it disappears yet I'm still unable to pass through the space. When I reload the game the door reappears, however doing this whenever I make a long trip away from my base can be a bit annoying. I've tried reloading chunks in-game to see if this would fix the issue, however it does not.

**Comment by CreativeMD** [comment]
Sorry, but doors are not meant to travel far distances at the moment. Once the door rework is done, I will fix some bugs regarding collisions. This might fix your issue (but there is no guarantee), just keep in mind those are just doors not vehicles. I will closes this issue for now. Vehicles are on my todo list, but there are far away at the moment. First of all I have to finish 1.5.0. So this is not my focus at the moment :(

**Comment by kirokadura** [comment]
I believe he meant traveling a distance **from** the door, not **with** the door. As in he went away to gather supplies and when he came back the door wouldn't load with the chunk.

**Comment by CreativeMD** [comment]
Oh damn ... sorry, that should not happen of course. Is it possible to send me your world (so i can test it myself)?

**Comment by arceste** [comment]
I had another go at troubleshooting and found that the glitch doesn't seem to happen when using vanilla algorithm in BetterFPS (I was using Riven's Algorithm before), so this may have been the issue. I can send the world file, but will you need the full modpack as well? I'm using a somewhat modified version of Enigmatica 2.

**Comment by CreativeMD** [comment]
If it does not happen anymore I would call it fixed. Just reopen the issue if it happens again.
