### ISSUE TITLE
Compatibility w/ the Dark Theme Mod

### ISSUE THREAD

**Issue by WenXin20** [CreativeMD/LittleTiles#183]
The mod makes it so that almost all GUIs have a dark theme, but I've noticed it doesn't work with this mod. 
Normally, support could be added by the user by using a texture file of the GUI, but I noticed that this mod doesn't have a texture file for that. 

Would support be possible to add? Thanks!

I'm using the [Dark Theme](https://minecraft.curseforge.com/projects/dark-theme-mod) v6r.

**Comment by CreativeMD** [comment]
Sorry for not responding earlier. I have created my own gui api, there is no way to manipulate it using a resourcepack. I plan to add this feature when porting it to 1.14.2. But for now I will leave it like that sorry :( .

**Comment by WenXin20** [comment]
Ok, although I meant that I'm using a mod called Dark Theme, which isn't a resource pack. 

It manipulates the color of most GUIs through scripting, although I'm not sure what exactly would need to be done to support the API since you use your own method. 
But thanks anyways!

**Comment by CreativeMD** [comment]
Yeah the api is not designed for that at the moment, that's why I will rewrite it for 1.14.2
