### ISSUE TITLE
Leaves Turning Invisible

### ISSUE THREAD

**Issue by nicholasandrzej** [CreativeMD/LittleTiles#185]
The moment I remove any part of a leaf block (optifine, tried with shader off, internal, and several shaders) with the hammer, the entire remaining block turns invisible. Not sure what's causing this.

**Comment by kirokadura** [comment]
You need to have mipmap enabled, otherwise things like leaves and grass will be invisible.

**Comment by nicholasandrzej** [comment]
Thanks, that fixed the visibility issue - but the leaf waving stops. Is there a way to fix that?

**Comment by kirokadura** [comment]
Do they stop after turning on mipmap for vanilla leaf blocks or after using the hammer? 

What shader are you using? Does it happen with other ones?

Does the water behave in the same way?

**Comment by nicholasandrzej** [comment]
Leaves still work with mipmap, only when I use they hammer do they stop. It happens with both of the current publicly available SEUS shaders (v11 and renewed 1.0.0), sildurs 1.21 extreme and the internal. The little tiles water block continues to hold its shader properties.

**Comment by nicholasandrzej** [comment]
It may be a SEUS issue. All of the vanilla stained glass has a nice reflective property - but the color fades and it looks almost like the water waving visual when modified with C&B or Little Tiles. I'll get back if I figure it out.

**Comment by CreativeMD** [comment]
Can you provide some screenshots?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persist just reopen it and provide some screenshots.
