### ISSUE TITLE
Cant remove advanced door with "stay animated" enabled

### ISSUE THREAD

**Issue by juh9870** [CreativeMD/LittleTiles#186]
I was wondering what does "stay animated" checkbox do, so i created advanced door with stay animated enabled, opened and closed it couple of times, but when i tried to remove it, i failed, even in closed state it doesn't have hitbox like other doors and can't be destroyed, only oppened and closed

**Comment by kirokadura** [comment]
You can only destroy the animation using a wrench. Right click on the door with a wrench and click Destroy Animation

**Comment by juh9870** [comment]
Yep, it works, thanks
