### ISSUE TITLE
Advanced Recipe doesn't remember axis position

### ISSUE THREAD

**Issue by juh9870** [CreativeMD/LittleTiles#187]
I was making complex doors, and noticed that each time i open the recipe to edit timeline, its axis options reset to default, so i have to re-setup them every single time.

**Comment by CreativeMD** [comment]
Maybe you forgot to hit save? It works fine for me.

**Comment by juh9870** [comment]
Here is video demonstration
https://youtu.be/qzRcmgycteM

**Comment by CreativeMD** [comment]
Thanks for reporting this issue. I fixed it and it will be part of the upcoming pre-release, which hopefully will be released soon.

**Comment by CreativeMD** [comment]
It is out now!
