### ISSUE TITLE
Cannot see translucid preview with little chisel

### ISSUE THREAD

**Issue by Assassinsquid** [CreativeMD/LittleTiles#189]
I cannot see the preview of the placed blocks when I am using little chisel.
Please help, thanks.

**Comment by CreativeMD** [comment]
If you are using Shaders, there is nothing I can do about it. Certain shaders do not support it, sorry :(

**Comment by Assassinsquid** [comment]
Ok, thanks for the fast reply :) Do you have some advise about good shader that can support it ?

**Comment by CreativeMD** [comment]
Not at the moment sorry :(

**Comment by Assassinsquid** [comment]
OK no worry. Thanks a lot for your help !
