### ISSUE TITLE
Always crash

### ISSUE THREAD

**Issue by Potsukin** [CreativeMD/LittleTiles#19]
Crash log : http://pastebin.com/iDm6KEwv

**Comment by CreativeMD** [comment]
Could you try to find out which mod is causing this issue with LittleTiles? I suspect it is "IVToolkit", because its the only other coremod. So you would really help me by testing it out.

**Comment by Potsukin** [comment]
Removed IVtoolkit but same crash happened. Place the hammered block, player moved, then freeze or crash.
Crash log 2: http://pastebin.com/0qLRB9wT

**Comment by CreativeMD** [comment]
Fixed particle issue, could you try out the newest CreativeCore version and check if it still happens?

**Comment by Potsukin** [comment]
New version works well, thanks for fixing.

**Comment by CreativeMD** [comment]
Nice thanks for reporting this issue. Wish you a lot of fun playing with my mod.
