### ISSUE TITLE
Adding children activators in advanced door recipe causes preview to disappear

### ISSUE THREAD

**Issue by juh9870** [CreativeMD/LittleTiles#194]
![image](https://user-images.githubusercontent.com/15922601/60734876-0f0e9e00-9f5a-11e9-881c-90249b7d18bf.png)
When i'm adding children activation into this menu, whole structure preview disappears

**Comment by CreativeMD** [comment]
This can happen sometimes. Is it fixed when you close the gui and open it again?

**Comment by juh9870** [comment]
Yes, most of times, but sometimes i need to remove all childs activators, set them back and reopen GUI to see preview

**Comment by CreativeMD** [comment]
Can you send me your structure?

**Comment by juh9870** [comment]
Oof, i already deleted it, will try to reroduce it

**Comment by juh9870** [comment]
Oof, i can't reproduce it, should i close this issue then?

**Comment by CreativeMD** [comment]
Yeah, just open it again if the issue reappears.
