### ISSUE TITLE
Child's collision box do now move along child animation

### ISSUE THREAD

**Issue by juh9870** [CreativeMD/LittleTiles#195]
When i trigger "activateChild" and child door changes it location, its collision box remains in old position.
closed door: ![2019-07-05_20 32 27](https://user-images.githubusercontent.com/15922601/60737755-86492f80-9f64-11e9-8b82-cd55de877770.png)

open door, actual collision box is the same as for closed door: ![2019-07-05_20 32 34](https://user-images.githubusercontent.com/15922601/60737764-8ea16a80-9f64-11e9-94d4-7acf856a632c.png)

**Comment by CreativeMD** [comment]
Yeah, that's on my todo list. Updating the bounding box is not implemented yet. I will close this issue for now, because it's nothing major and already on my todo list.
