### ISSUE TITLE
Moving Childs Sometimes leaves glitched parts behind

### ISSUE THREAD

**Issue by juh9870** [CreativeMD/LittleTiles#196]
Sometimes when i open a door with childs, part of a child clones and remains at the old position
How it should look
![2019-07-05_20 46 48](https://user-images.githubusercontent.com/15922601/60738304-84806b80-9f66-11e9-9e42-f2fe705dadac.png)

How it looks
![2019-07-05_20 46 33](https://user-images.githubusercontent.com/15922601/60738309-8b0ee300-9f66-11e9-9e6b-e8b432b53c04.png)

**Comment by juh9870** [comment]
Accidentaly oppened isue before finished writing it

**Comment by CreativeMD** [comment]
Can you send me the structure or the world?

**Comment by juh9870** [comment]
Hmm, how do i send structure?

**Comment by CreativeMD** [comment]
/lt-export, put it in the slot and hit copy.

**Comment by juh9870** [comment]
https://pastebin.com/37aJcthc
It uses Chisel mod

**Comment by juh9870** [comment]
Gliched parts appears like 1 out of 10 oppenings

**Comment by CreativeMD** [comment]
I have tested it like 30 times, no problem at all. Maybe the blocks around the door are causing the issue. Can't really tell from the screenshot. Could you send me your world?

**Comment by juh9870** [comment]
This is multiMC instance that i play in (with all mods and current save) https://drive.google.com/file/d/1DK2CANxpJZxJ1wFj2lGr7jRLd3Vvklhj/view?usp=sharing

**Comment by CreativeMD** [comment]
Did not even happen once. Maybe this issue occurs more like with less FPS. I got around 300 to 400. How many do you have?

**Comment by juh9870** [comment]
~30 fps, will try to record video of this glitch later

**Comment by CreativeMD** [comment]
Does this version fix it? https://www.dropbox.com/s/g91ot22owfbmsoc/LittleTiles_v1.5.0-pre147_mc1.12.2.jar?dl=1

**Comment by CreativeMD** [comment]
I will close this issue for now, just reopen it if it happens again.
