### ISSUE TITLE
Little tiles sometimes render invisible when adjacent door opens

### ISSUE THREAD

**Issue by juh9870** [CreativeMD/LittleTiles#197]
How it should look: ![2019-07-05_20 58 19](https://user-images.githubusercontent.com/15922601/60738747-176dd580-9f68-11e9-88d5-06a3c5d19ad6.png)

How it looks: ![2019-07-05_20 56 56](https://user-images.githubusercontent.com/15922601/60738755-205ea700-9f68-11e9-993d-a16b3d05e7ba.png)

Same issue sometimes appearing when i undo tiles placement or break adjacent little tile

**Comment by CreativeMD** [comment]
Wrong issue :D

EDIT yeah this can happen, just use the wrench to fix it.
