### ISSUE TITLE
Preview block not rendering with GLSL shaders active.

### ISSUE THREAD

**Issue by Encryption767** [CreativeMD/LittleTiles#2]
Shaders are looking for textures and since one isn't bound for the preview block then it appears invisible.

In PreviewRenderer.java, 
Replace the GL11 functions with : 
                    GL11.glEnable(GL11.GL_BLEND);
                    mc.renderEngine.bindTexture(TextureMap.locationBlocksTexture);

This will show a ghost block with shaders enabled so the player can at least see where the block will be placed.

**Comment by Encryption767** [comment]
This quick fix allows the user to also see the preview block with shaders disabled.

I am not well versed in obsolete ogl. Maybe you can improve this to look better.

**Comment by CreativeMD** [comment]
I noticed this error, the box sometime get invisible if you use a shader, maybe this fixes this bug i will try it out.

**Comment by CreativeMD** [comment]
I'm now trying to fix it: https://github.com/sp614x/optifine/issues/663

**Comment by CreativeMD** [comment]
Looks like this issue has been solved somehow (at least for 1.11.2)
