### ISSUE TITLE
Wrong movement of door

### ISSUE THREAD

**Issue by Potsukin** [CreativeMD/LittleTiles#20]
![2017-01-29_20 11 59](https://cloud.githubusercontent.com/assets/11745850/22403653/7a6d7e1e-e661-11e6-89df-7b9efd9e7f66.png)

This should be a double door, but top and bottom moves separately and disappear after moved. additionaly, sometimes client crash when snow falling. 

Crash log  http://pastebin.com/thArYzhP

**Comment by CreativeMD** [comment]
Looks like you have not setup the door properly: https://youtu.be/XR5dmXEhGaY?t=13m29s

**Comment by Potsukin** [comment]
![2017-01-30_07 13 31](https://cloud.githubusercontent.com/assets/11745850/22408461/922d8426-e6bc-11e6-90cc-720109a92233.png)
It happens only on multiplay server. I can make doors in backup world of server in single player mode, which have same mods and configs.

**Comment by CreativeMD** [comment]
Could you send me your Map? Maybe i can find out what is going on.

**Comment by Potsukin** [comment]
I can send my map, but probably something happening with other mod. I can send mods, configs and maps as a modpack to you, but how can I do it?

**Comment by CreativeMD** [comment]
You can either upload it via a cloud service or you could join on discord so you could send it to me there (https://discord.gg/W9QM3fS).

**Comment by CreativeMD** [comment]
It is fixed in LittleTiles v1.3.7. Thanks for reporting this issue.
