### ISSUE TITLE
Unclear/missing description to the exporter gui

### ISSUE THREAD

**Issue by Lovatic123** [CreativeMD/LittleTiles#200]
The exporter is quite confusing to use, because its unclear what type of file, you are exporting. It turns out that the 'export x' button shows, what will be exported, IF YOU CLICK IT, and not what you are currently exporting. This is quite confusing, as you Arent informed by this anywhere.

A solution could be a drop down menu like in the chisel gui, where you have to choose what kind of text, you want to export (Idea from Kiro)

Latest CreativeCore and LittleTiles mod.

**Comment by CreativeMD** [comment]
Done in the newest pre-release. Thanks for you suggestion @kirokadura :D
