### ISSUE TITLE
right click don't work?!

### ISSUE THREAD

**Issue by 1hoorn** [CreativeMD/LittleTiles#201]
if i right click with the hammer, nothing will pop up. i can't do anything now xD

**Comment by CreativeMD** [comment]
I highly recommend to check out the wiki, many things have changed since you could right click the hammer. https://github.com/CreativeMD/LittleTiles/wiki

**Comment by 1hoorn** [comment]
@CreativeMD  i watched the video, something with ''z'' but that doesn't work to. idk how the hammer thing works then, i can't get that pop up that i can change the block size thingy (sorry for my bad english)

**Comment by CreativeMD** [comment]
It's 'c' and I highly recommend to watch this tutorial series: https://www.youtube.com/watch?v=Bfg88rRNocA&list=PLQzDSnrhrcyyJ4DiirrFtGhyfd8ws-fpf

**Comment by CreativeMD** [comment]
1.

**Comment by 1hoorn** [comment]
@CreativeMD  oh okay sorry xD, but thank you so much!
