### ISSUE TITLE
Cleared recipes don't stack with unused recipes

### ISSUE THREAD

**Issue by QBFreak** [CreativeMD/LittleTiles#202]
## Description
When a recipe is cleared (either a Little Recipe or an Advanced Recipe), the NBT retains an empty compound tag. Newly crafted recipes don't have this at all. This prevents cleared recipes from stacking with unused recipes.

There is a workaround for the Little Recipe: shift-right-click the cleared recipe on a block. It will clear the empty tag and the recipe will stack with the others. This does not work for the Advanced Recipe, as this action is part of the position setting mechanic.

## Expected Behavior
Using the clear button on a recipe should return it to the same state as the crafting output, such that one will stack with the other.

## Steps to reproduce
- Acquire two blank little recipes (or two advanced recipes, but not one of each)
- Observe that they stack in your inventory
- Populate one of the recipes with some tiles
- Clear the recipe
- Observe that the two recipes will no longer stack

## Details
|| Versions |
|---|---|
| **Minecraft** | 1.12.2 |
| **Forge** | 14.23.5.2838 |
| **LittleTiles** | 1.5.0-pre149 |
| **CreativeCore** | 1.9.54 |
| **Other mods** | No, reproducible with just LittleTiles and CreativeCore |

If there's anything I forgot to mention, or testing I can help with, please don't hesitate to ask. I'm having a blast with LittleTiles.

**Comment by CreativeMD** [comment]
Wow, your description is insane. Thank you very much for your effort! Fixed in pre150, which should be available by now.
