### ISSUE TITLE
Tile placement still previews when HUD is hidden

### ISSUE THREAD

**Issue by QBFreak** [CreativeMD/LittleTiles#204]
## Description

When the HUD is hidden (`F1`) the tile preview still displays when targeting a block with a tool, recipe, or structure.

## Steps to reproduce

- Hold Little Chisel in main hand
- Point it at a nearby block
- Observe the "ghost" preview of the bit that would be placed
- Press `F1` to toggle the HUD off
- Observe that while all other UI elements disappear, the preview does not

## Expected Behavior

In my opinion (I suspect this is going to be a subjective matter with varying opinions), the preview should not show when the HUD is off.

- The voxel selection box for the hammer disappears when the HUD is hidden
- All other UI elements are hidden (unless the user performs an action invoking a GUI)
- Other mods (that I'm familiar with) that display things on my screen hide their content when the HUD is hidden
- I personally (and probably quite a few other users) use this mode for screenshots, the kind where I don't want any distracting elements

No hard feelings if you simply disagree and close this.

## Details
|| Versions |
|--|--|
| **Minecraft:** | 1.12.2 |
| **Forge:** | 14.23.5.2768 |
| **LittleTiles:** | 1.5.0-pre150 |
| **CreativeCore:** | 1.9.54 |
| **Other mods:** | No, reproducible with just LittleTiles |

**Comment by CreativeMD** [comment]
Also fixed in the upcoming version! Thanks for you report again!

**Comment by CreativeMD** [comment]
Now version is out!
