### ISSUE TITLE
Issues using Little Hammer in Cube mode when changing voxel sizes

### ISSUE THREAD

**Issue by QBFreak** [CreativeMD/LittleTiles#205]
## Description

If the Little Hammer is in `Cube` mode, the maximum size is restricted to a single block worth of voxels. However if you set the hammer to a full block size, and then reduce the number of voxels, it will continue to operate on the same number of voxels, thus affecting a greater number of blocks. Opening and closing the Tool Configuration GUI will reset it.

## Steps to reproduce

- Acquire Little Hammer
- Open Advanced Configuration GUI and set voxel count to 16 or 32
- Open Configuration GUI and set size to maximum (16 or 32, whichever you chose above)
- Target a block, observe single block size selection
- Open Advanced Configuration GUI and set voxel count to 1
- Target a block, observe that block size selection is now 16x16 or 32x32 blocks (matching your voxel count)
- If desired, test using the hammer, it will operate on an area that large
- Open Configuration GUI
- Close Configuration GUI without changing any settings
- Target a block, observe proper single block size selection

## Expected Behavior

Selection voxel count should reset to match single-block size when voxels are changed. This matches the limits of the size selection in the GUI.

## Details
|| Versions |
|--|--|
| **Minecraft:** | 1.12.2 |
| **Forge:** | 14.23.5.2768 |
| **LittleTiles:** | 1.5.0-pre150 |
| **CreativeCore:** | 1.9.54 |
| **Other mods:** | No, reproducible with just LittleTiles |

**Comment by CreativeMD** [comment]
Is fixed as well, again thanks for your report. You make it really easy for me, means I can fix it a lot faster.

**Comment by CreativeMD** [comment]
Now version is out!
