### ISSUE TITLE
Crash when operating both doors of a multi-door structure

### ISSUE THREAD

**Issue by QBFreak** [CreativeMD/LittleTiles#207]
## Description

I have a pair of doors. They are in a single structure something like this:

- Axis Door
  - Advanced Door

If I open the Axis Door, and while it is open attempt to operate the Advanced Door, the game crashes with a Null Pointer Exception.

## Steps to reproduce

Note: There is an example structure with the log files, see link below

- Create an Advanced Door
- Create some tiles
- Place Advanced Door on tiles
- Create Axis Door from Advanced Door and tiles
- While editing the Axis Door, click `Children` and add the Advanced Door such that it operates at the same time
- Place new structure
- Open door, no issues
- Close door, crash

This can also be duplicated without explicitly adding the child door to be triggered, however you have to operate it manually while the parent door is in motion.

## Expected Behavior

There is a mechanism for operating child doors with the parent, so I assume this should work properly.

## Logs

Crash report, latest.log, and an example structure that reproduces the problem: https://gist.github.com/QBFreak/76e0e01fd53b36a4f523772f6fb9996a

## Details
|| Versions |
|--|--|
| **Minecraft:** | 1.12.2 |
| **Forge:** | 14.23.5.2768 |
| **LittleTiles:** | 1.5.0-pre150 |
| **CreativeCore:** | 1.9.54 |
| **Other mods:** | No, reproducible with just LittleTiles |

**Comment by CreativeMD** [comment]
Should be fixed in the newest version.

**Comment by CreativeMD** [comment]
Newest version is released.
