### ISSUE TITLE
Door speed 1 crash

### ISSUE THREAD

**Issue by Devilofether** [CreativeMD/LittleTiles#21]
I got a crash when I tried setting the door speed to 1 and using it :P, I personally think the door animation is pointless and un-minecraft-like, but I can't argue with results

---- Minecraft Crash Report ----

WARNING: coremods are present:
LittlePatchingLoader ([Content] Little Tiles 1.11.2.jar)
MMFMLCorePlugin ([Feature] MultiMine 1.11.2.jar)
BetterAutoJumpCore ([Misc] Better Auto Jump 1.11.2.jar)
CreativePatchingLoader ([Dependancy] Creative Core (Little Tiles) 1.11.2.jar)
IvToolkit ([Dependancy] Iv Toolkit (Rec;Com) 1.11.0.jar)
LoadingPlugin ([Content] Quark 1.11.2.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 1/31/17 3:56 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
at java.util.ArrayList.<init>(ArrayList.java:177)
at com.creativemd.littletiles.common.entity.EntityAnimation.createClient(EntityAnimation.java:169)
at com.creativemd.littletiles.client.render.entity.RenderAnimation.doRender(RenderAnimation.java:57)
at com.creativemd.littletiles.client.render.entity.RenderAnimation.func_76986_a(RenderAnimation.java:42)
at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:415)
at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:809)
at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1742)
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1569)
at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1346)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
at java.util.ArrayList.<init>(ArrayList.java:177)
at com.creativemd.littletiles.common.entity.EntityAnimation.createClient(EntityAnimation.java:169)
at com.creativemd.littletiles.client.render.entity.RenderAnimation.doRender(RenderAnimation.java:57)
at com.creativemd.littletiles.client.render.entity.RenderAnimation.func_76986_a(RenderAnimation.java:42)

-- Entity being rendered --
Details:
Entity Type: littletiles:animation (com.creativemd.littletiles.common.entity.EntityAnimation)
Entity ID: 2741944
Entity Name: entity.animation.name
Entity's Exact location: 186.00, 56.00, 442.00
Entity's Block location: World: (186,56,442), Chunk: (at 10,3,10 in 11,27; contains blocks 176,0,432 to 191,255,447), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Entity's Momentum: 0.00, 0.00, 0.00
Entity's Passengers: []
Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
Assigned renderer: com.creativemd.littletiles.client.render.entity.RenderAnimation@5b55e181
Location: -0.75,0.00,-3.18 - World: (-1,0,-4), Chunk: (at 15,0,12 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Rotation: 0.0
Delta: 0.79568416
Stacktrace:
at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:415)
at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:809)
at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1742)
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1569)

-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityPlayerSP['Devilofether'/1, l='MpServer', x=186.75, y=56.00, z=445.18]]
Chunk stats: MultiplayerChunkCache: 588, 588
Level seed: 0
Level generator: ID 01 - flat, ver 0. Features enabled: false
Level generator options: 
Level spawn location: World: (189,4,449), Chunk: (at 13,0,1 in 11,28; contains blocks 176,0,448 to 191,255,463), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 53607 game time, 124607 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Forced entities: 34 total; [EntityPlayerSP['Devilofether'/1, l='MpServer', x=186.75, y=56.00, z=445.18], EntityAnimation['entity.animation.name'/2270882, l='MpServer', x=186.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2152165, l='MpServer', x=187.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2676656, l='MpServer', x=186.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2140525, l='MpServer', x=187.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2153714, l='MpServer', x=187.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2687481, l='MpServer', x=186.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2741944, l='MpServer', x=186.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2665597, l='MpServer', x=186.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2204088, l='MpServer', x=186.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2268982, l='MpServer', x=187.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2142138, l='MpServer', x=186.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2229759, l='MpServer', x=186.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2257151, l='MpServer', x=187.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2203140, l='MpServer', x=187.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2667789, l='MpServer', x=187.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2231557, l='MpServer', x=186.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2138124, l='MpServer', x=187.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2227787, l='MpServer', x=187.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2660951, l='MpServer', x=187.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2686727, l='MpServer', x=187.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2660058, l='MpServer', x=186.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2190998, l='MpServer', x=187.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2226454, l='MpServer', x=186.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2134038, l='MpServer', x=186.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2664543, l='MpServer', x=187.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2675295, l='MpServer', x=187.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2180823, l='MpServer', x=187.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2672209, l='MpServer', x=187.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2134939, l='MpServer', x=187.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2130460, l='MpServer', x=187.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2131358, l='MpServer', x=186.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2254688, l='MpServer', x=186.00, y=56.00, z=442.00], EntityAnimation['entity.animation.name'/2136736, l='MpServer', x=186.00, y=56.00, z=442.00]]
Retry entities: 0 total; []
Server brand: fml,forge
Server type: Integrated singleplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.11.2
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 406088064 bytes (387 MB) / 849391616 bytes (810 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.38 Powered by Forge 13.20.0.2206 Optifine OptiFine_1.11.2_HD_U_B5 30 mods loaded, 30 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAAAA minecraft{1.11.2} [Minecraft] (minecraft.jar) 
UCHIJAAAA mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
UCHIJAAAA FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2206.jar) 
UCHIJAAAA forge{13.20.0.2206} [Minecraft Forge] (forge-1.11.2-13.20.0.2206.jar) 
UCHIJAAAA littletilescore{1.0.0} [LittleTilesCore] (minecraft.jar) 
UCHIJAAAA creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
UCHIJAAAA ivtoolkit{1.3.1} [IvToolkit] (minecraft.jar) 
UCHIJAAAA mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
UCHIJAAAA betterfoliage{2.1.3} [Better Foliage] ([Aesthetic] Better Foliage 1.11.x.jar) 
UCHIJAAAA jei{4.2.2.215} [Just Enough Items] ([Cheat] Just Enough Items 1.11.2.jar) 
UCHIJAAAA blockdispenser{1.0} [BlockDispenser] ([Content] Block Dispenser 1.1.2.jar)
UCHIJAAAA littletiles{1.3.0} [LittleTiles] ([Content] Little Tiles 1.11.2.jar) 
UCHIJAAAA morphtool{1.1-13} [Morph-o-Tool] ([Content] Morph-o-Tool 1.11.2.jar) 
UCHIJAAAA quark{r1.2-77} [Quark] ([Content] Quark 1.11.2.jar) 
UCHIJAAAA chameleon{1.11-3.0.2} [Chameleon] ([Dependancy] Chameleon (Drawers) 1.11.x.jar) 
UCHIJAAAA storagedrawers{1.11-4.0.3} [Storage Drawers] ([Content] Storage Drawers 1.11.x.jar) 
UCHIJAAAA autoreglib{1.1-4} [AutoRegLib] ([Dependancy] Auto Reg Lib (Quark)1.11.x.jar) 
UCHIJAAAA creativecore{1.5.0} [CreativeCore] ([Dependancy] Creative Core (Little Tiles) 1.11.2.jar) 
UCHIJAAAA fastleafdecay{v12} [Fast Leaf Decay] ([Feature] Fast Leaf Decay 1.11.x.jar) 
UCHIJAAAA mousetweaks{2.7} [Mouse Tweaks] ([Feature] Mouse Tweaks 1.11.2.jar) 
UCHIJAAAA multimine{1.5.6} [Multi Mine] ([Feature] MultiMine 1.11.2.jar) 
UCHIJAAAA simulatednights{1.11.2-1.1.2} [Simulated Nights] ([Feature] Simulated Nights 1.11.2.jar) 
UCHIJAAAA treechopper{1.1.1a} [Tree Chopper] ([Feature] Tree Chopper 1.11.x.jar) 
UCHIJAAAA veinminer{0.35.3} [Vein Miner] ([Feature] Vein Miner 1.11.x.jar) 
UCHIJAAAA veinminermodsupport{0.35.3} [Mod Support] ([Feature] Vein Miner 1.11.x.jar) 
UCHIJAAAA appleskin{1.0.5} [AppleSkin] ([Misc] Apple Skin 1.11.x.jar) 
UCHIJAAAA betterautojump{1.1.0-mc1.11.2} [Better Auto Jump] ([Misc] Better Auto Jump 1.11.2.jar) 
UCHIJAAAA waila{1.8.6} [Waila] ([Misc] Hwyla 1.11.x.jar) 
UCHIJAAAA multihotbar{1.0} [Multi-Hotbar] ([Misc] Multi Hotbar 1.11.2.jar) 
UCHIJAAAA reccomplex{1.2.6.2} [Recurrent Complex] ([World] Recurrent Complex 1.11.2.jar) 
Loaded coremods (and transformers): 
LittlePatchingLoader ([Content] Little Tiles 1.11.2.jar)
com.creativemd.littletiles.LittleTilesTransformer
MMFMLCorePlugin ([Feature] MultiMine 1.11.2.jar)
atomicstryker.multimine.common.fmlmagic.MMTransformer
BetterAutoJumpCore ([Misc] Better Auto Jump 1.11.2.jar)
com.mmyzd.betterautojump.asm.ClassTransformer
CreativePatchingLoader ([Dependancy] Creative Core (Little Tiles) 1.11.2.jar)

IvToolkit ([Dependancy] Iv Toolkit (Rec;Com) 1.11.0.jar)

LoadingPlugin ([Content] Quark 1.11.2.jar)
vazkii.quark.base.asm.ClassTransformer
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.91' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
Launched Version: 1.11.2-forge1.11.2-13.20.0.2206
LWJGL: 2.9.4
OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 358.91, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 6x AMD FX(tm)-6300 Six-Core Processor 
OptiFine Version: OptiFine_1.11.2_HD_U_B5
Render Distance Chunks: 12
Mipmaps: 0
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.5.0 NVIDIA 358.91
OpenGlRenderer: GeForce GTX 750 Ti/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 6

**Comment by CreativeMD** [comment]
Thanks for reporting should be fixed in v1.3.4
