### ISSUE TITLE
Little Bag sometimes has slots that only display "volume: 0 pixel"

### ISSUE THREAD

**Issue by QBFreak** [CreativeMD/LittleTiles#210]
## Description

Occasionally I will open my Little Bag and find a blank slot in the middle, when I mouse over it instead of telling me the block type and the quantity, the tooltip only displays `volume: 0 pixel`. Using an NBT Editor on the bag reveals that the slot in question has an incredibly small amount. In the most recent case it was `3.0808688933348094E-15`. The rest of the block data is there in the NBT, but not displaying in the GUI (perhaps the GUI is rounding down to zero and thus displaying an empty slot?).

See attached screenshot for a better description of the issue.

## Steps to reproduce

Unknown at this time.

## Expected Behavior

The Little Bag should display all contents. If the smallest workable unit is a pixel than perhaps nothing smaller should be stored, or the remainder should be cleared when the last full pixel is removed from the bag.

## Logs

I don't presently have any logs, however if you truly wish a `latest.log` let me know and I can attach one next time I notice this occurring.

Here is the screenshot:

![Screenshot at 2019-07-24 13-25-37.png](https://user-images.githubusercontent.com/17347092/61824301-a6656380-ae2b-11e9-825a-ba317a48c88f.png)

## Details
|| Versions |
|--|--|
| **Minecraft:** | 1.12.2 |
| **Forge:** | 14.23.5.2768 |
| **LittleTiles:** | 1.5.0-pre150 |
| **CreativeCore:** | 1.9.54 |
| **Other mods:** | Yes. Lots. |

**Comment by CreativeMD** [comment]
Fixed this particular issue. These ingredients will not be saved/ loaded anymore. However there are some more issues with the bag. I will take care of them later. Any thanks again for your report. I will upload the new version now.
