### ISSUE TITLE
Performance issue due to excessive chunk updates

### ISSUE THREAD

**Issue by tst5000** [CreativeMD/LittleTiles#211]
I'm having major performance issues while running, but apparently not using, LittleTiles. While I have creativecore and littletiles installed, and I look at my largely brick-based factory which USED to have a 300-or-so stay animated door, I will experience constistent 40-80 chunk updates/sec (or tick idk which the f3 menu points to) until I place down a block in front of where the door used to be, which will solve the issue. When I do not have creativecore or Littletiles installed, this doesn't happen, and when I look at my factory, I don't get a consistently large amount of chunk updates.
 
Here are images - 
With LT before placing block: https://imgur.com/a/eD5iorQ and after: https://imgur.com/a/STHfc8l 
Without LT before: https://imgur.com/a/ojCk2No after: https://imgur.com/a/8ERhQsGsG

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming update. Thanks for reporting this issue! Hope I will get the new version out this week.

**Comment by CreativeMD** [comment]
Now version is out!
