### ISSUE TITLE
[BUG] - Crash at exiting world

### ISSUE THREAD

**Issue by BasieBrinkie** [CreativeMD/LittleTiles#212]
LitleTiles Version: 1.5.0-pre151
CreativeCore Version:  1.9.55
Minecraft Version: 1.12.2

###How to reproduce:
1. Open a singleplayer world (Mine did run well before with version pre150)
2. Exit the world by clicking "save and exit to menu"
After that, it will immediately crash.

###Crash Log
https://gist.github.com/BasieBrinkie/6699ae3124790c8e68b6ba22be4a23e6

NOTE: I have optimization mods running like vanillafix, betterfps, randompatches and phosphor

**Comment by kreezxil** [comment]
confirmed

https://paste.dimdev.org/mekavuwoqu.mccrash

I have even more loaded in my pack.

**Comment by kreezxil** [comment]
going back to the 7/15/2019 version resolves the issue. the library doesn't have to be rolled back tho so that's a minor plus.

**Comment by CreativeMD** [comment]
Will be fixed soon! Thanks for reporting this issue.
