### ISSUE TITLE
All tiles are invisible

### ISSUE THREAD

**Issue by QBFreak** [CreativeMD/LittleTiles#213]
## Description

I updated to 1.5.0-pre151 (CreativeCore as well) and now all tiles are invisible. It does not appear to be a mod interaction issue, it even occurs with just LT and CC. I am not using Optifine. My log is full of exceptions related to rendering.

## Steps to reproduce

- Create a tile with LittleTiles 1.5.0-pre151 or open an existing world with tiles already in it
- Observe that the tile(s) do not render

## Expected Behavior

I'd like to be able to see my tiles :wink: 

## Logs

https://gist.github.com/QBFreak/523bab743e79d07a6617345e556c2552

## Details
|| Versions |
|--|--|
| **Minecraft:** | 1.12.2 |
| **Forge:** | 14.23.5.2836 |
| **LittleTiles:** | 1.5.0-pre151 |
| **CreativeCore:** | 1.9.55 |
| **Other mods:** | No, reproducible with just LittleTiles |
| **Operating System** | Linux Mint 18.3 Sylvia |
| **Kernel** | 4.15.0-45-generic #48~16.04.1-Ubuntu |
| **Video card** | GeForce GTX 1050 |
| **Driver** | NVIDIA binary driver version 384.130 |

**Comment by CreativeMD** [comment]
Fixed in the newest pre-released.
