### ISSUE TITLE
Invisible Tiles on Server

### ISSUE THREAD

**Issue by Lesabeilles** [CreativeMD/LittleTiles#214]
Yes, I know another invisible tiles was posted and it may be related, but I did not want to hijack their thread and mine is slightly different.

For some people on my small server, the blocks are invisible Those on the wifi as the host computer can see it while those utilizing the public IP address cannot. They are invisible, but solid - they cannot walk through it. And the game clearly recognizes the existence of the blocks, as my friends get the "Not enough space for material." message when they have no bag. They just can't see it. We all have the same exact mods and none of us have Optifine.

Edit: we all have Creative Core V1.9.55 and Little Tiles V1.5.0.

**Comment by CreativeMD** [comment]
Fixed in the newest pre-released.
