### ISSUE TITLE
Crash when trying to log on to a server

### ISSUE THREAD

**Issue by CammiePone** [CreativeMD/LittleTiles#216]
Something to do with a world unload, and returning null. You should probably add a != null check wherever this is crashing.

https://paste.dimdev.org/toqicadite.mccrash

**Comment by ClockworkFountain** [comment]
I'm getting the same issue...

**Comment by Litoprobka** [comment]
I get the same issue when I try to log into a world

https://paste.dimdev.org/gagefurapi.rb

**Comment by CreativeMD** [comment]
Fixed in the newest pre-released.
