### ISSUE TITLE
Connected Textures Don't Work w/ ExtraUtils2

### ISSUE THREAD

**Issue by WenXin20** [CreativeMD/LittleTiles#219]
Minecraft 1.12.2
Forge v14.23.5.2838
Creative Core v1.9.55
Little Tiles v1.5.0-pre151
EU2 v1.9.9

In this example, I am using the Crossed Stone Brick/Tile, but the textures aren't connecting properly. Is support able to be added?
![2019-07-29_15 54 50](https://user-images.githubusercontent.com/12000593/62083116-d772d900-b21b-11e9-9226-8ab1610135d3.png)

**Comment by CreativeMD** [comment]
Can you update to the newest CC and LT version? I fixed a couple of things related to this.

**Comment by WenXin20** [comment]
I updated to LT v1.5.0-pre153 and CC v1.9.57, but the textures still look like the above image.

**Comment by CreativeMD** [comment]
Wait ... did it work on previous versions?

**Comment by WenXin20** [comment]
I actually don't know, I only recently started using this mod again and realized Extra Util blocks doesn't seem to work for connected textures.

**Comment by CreativeMD** [comment]
Yeah, sorry. I added connected textures support for CTM and Optifine. No idea what Extra Utils is doing :( I will most likely not add support for it.
