### ISSUE TITLE
[1.10.2] Bug JEI/NEI integration issue

### ISSUE THREAD

**Issue by XvSkItZvX** [CreativeMD/LittleTiles#22]
I have been working on compiling a mod pack privately, current collection can be found [HERE](http://www.modlister.com/user/XvSkItZvX).

Upon installing this mod I load my world to begin my first round of testing. Basically to see if it will load completely and what it adds to the game.

I use the combination of JEI/NEI as I've had terrible luck with JEI by itself and frankly I've grown accustomed to NEI from 1.7.10. This combination however has been proven to be a bit glitchy at times so I initially thought that was the problem. I mention this so you understand that I went to great pains to pinpoint eliminate "TinyTiles" as the cause of the issue before concluded that it indeed was.

After installing the "Tiny Tiles" mod and opening player inventory, with the NEI side item panel and search bar, loaded, I began to search the keyword "Tiny" in the search bar. Upon typing the the letters "tin", all items in the side panel, hot bar, and player inventory ceased to render. I was able to see stack counts and could hover over each space to read the information provided by the "HWYLA" for each item in the side panel, hot bar, and player inventory so I didn't lose the items. They simple quite rendering in the interface.

After going through a number of settings for JEI/NEI I was unable to correct this issue. Even went as far as disabling NEI to see if I had the same issue with just JEI, However I have had a long standing issue with JEI not working as expected which is why I use it with NEI but not related to Tiny Tiles. 

By this time I had restarted the client several times only to have the items appear up reloading and disappear whenever I began searching for "tiny". It was at this point I disabled the Tiny Tiles mod and loaded the client back up. I was able to search for anything desired without issue, including "tiny".

So I closed the client and re-enabled tiny tiles and opened the player menu again. I performed a number of searches based on other existing mods "Tinkers", "Immersive", and "Pickaxe" specifically.  But, when I typed "tin" again for tiny it happened again.

**Comment by XvSkItZvX** [comment]
Please excuse my errors in the above post. It was late when I filed this, it's not "tin" or "tiny", it is "lit" for "little"...I'll should have gone to bed and reported the issue in the morning. 

and to expand upon the previous description, the issue presents when I search for "tiles" triggering on "til"

**Comment by CreativeMD** [comment]
Report this issue to the author of jei, because i have no clue what could possibly be the problem https://github.com/mezz/JustEnoughItems/issues/718.

**Comment by CreativeMD** [comment]
This issue should be fixed in v1.3.5. Thanks for reporting this issue. I wish you a lot of fun using my mod, hopefully without any further issues.
