### ISSUE TITLE
Lighting glitches when next to solid blocks

### ISSUE THREAD

**Issue by Tschipp** [CreativeMD/LittleTiles#222]
![image](https://user-images.githubusercontent.com/11649893/62400596-0ffa1600-b580-11e9-976d-4003ebd02269.png)

When glowstone is applied to a tile and that tile is touching solid blocks, these lighting glitches appear.

LittleTiles 1.5.0-155
CreativeCore 1.9.59
Forge 14.23.5.2838

**Comment by CreativeMD** [comment]
Will be fixed in the newest version.
