### ISSUE TITLE
NPE when trying to take out invalid block out of little bag

### ISSUE THREAD

**Issue by Tschipp** [CreativeMD/LittleTiles#223]
[crash-2019-08-02_23.30.25-client.txt](https://github.com/CreativeMD/LittleTiles/files/3463020/crash-2019-08-02_23.30.25-client.txt)

**Comment by Tschipp** [comment]
Update: Apparently it also happens when taking out anything from the bag.

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming pre-release.
