### ISSUE TITLE
[Feature Request] Little Bag clear button

### ISSUE THREAD

**Issue by Tschipp** [CreativeMD/LittleTiles#224]
Please add a button to clear the Little Bag. Once it fills up with pixels it's basically useless as I won't spend hours taking out thousands of pixels. ((unless such a feature already exists and I'm missing it))

**Comment by kirokadura** [comment]
This feature is planned and will be worked on once we start working on the tools.

**Comment by CreativeMD** [comment]
I will close the issue for now, I think I will start to work on same survival enhancements after redstone is done.
