### ISSUE TITLE
Crash when operating parent door if child door is left open

### ISSUE THREAD

**Issue by QBFreak** [CreativeMD/LittleTiles#226]
## Description

First off, awesome job fixing that last bug with child doors. My specific use case no longer crashes. That said, with some fiddling, I was able to find another crash.

Assume two axis doors, both fixed, as parent and child that are _not_ configured to operate together. When the parent door is opened, and the child door is opened, and then the parent door closed and opened again, the child door vanishes. Attempting to open and then close the parent door a few times after this causes a crash.

Confused yet? There's a structure and steps to reproduce it below.

I'm guessing this is because the child remains an entity since it was never closed. It gets lost somewhere along the way, and when the parent goes to open that last time it can't find the child to move it too. Crash.

## Steps to reproduce

- Place this structure: [parent-child-door.txt](https://github.com/CreativeMD/LittleTiles/files/3483227/parent-child-door.txt)
- Open parent door (red/green)
- Open child Door (blue)
- Close parent door
- Open parent door, note that child door vanishes as animation starts
- Close parent door
- Open parent door, crashes (presumably because child door is missing)

If you reload the world, both doors will be missing.

## Expected Behavior

Child door should not vanish. LT should not crash.

## Logs

[crash-2019-08-08_14.43.52-client.txt](https://github.com/CreativeMD/LittleTiles/files/3483233/crash-2019-08-08_14.43.52-client.txt)

[latest.log](https://github.com/CreativeMD/LittleTiles/files/3483301/latest.log)

## Details
|| Versions |
|--|--|
| **Minecraft:** | 1.12.2 |
| **Forge:** | 14.23.5.2838 |
| **LittleTiles:** | 1.5.0-pre158 |
| **CreativeCore:** | 1.9.62 |
| **Other mods:** | No, reproducible with just LittleTiles |

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming version. Thanks for your report!!! It was a rather weird issue (chunks in fake worlds were not marked as loaded).

**Comment by CreativeMD** [comment]
It's out now!
