### ISSUE TITLE
[Bug] While trying to use the mod on a server [1.10.2]

### ISSUE THREAD

**Issue by AstralDestiny** [CreativeMD/LittleTiles#23]
http://pastebin.com/p3csJsjW
Happens when trying to use the knife or door recipe the blocks in a door also disappear if they are right clicked anywhere.

1.10.2
CreativeCore v1.6.18 mc1.10.2
LittleTiles v1.3.3 mc1.10.2

- Sorry forgot to list the versions of the mod.

**Comment by AstralDestiny** [comment]
1.10.2
CreativeCore v1.6.18 mc1.10.2
LittleTiles v1.3.3 mc1.10.2

- Sorry forgot to list the versions of the mod.

**Comment by CreativeMD** [comment]
Thanks for reportnig, should be fixed in v1.3.4
