### ISSUE TITLE
Glove in replace mode without enough material causes desync

### ISSUE THREAD

**Issue by QBFreak** [CreativeMD/LittleTiles#231]
## Description

Using the Little Glove in replace mode in survival without enough material to complete the replace operation will cause the affected tile to appear to vanish. Moving through that space causes the player to get partially stuck. The wrench does not affect the missing tile to correct it. Reloading the world causes the original tile to reappear.

## Steps to reproduce

- Survival mode
- Acquire an empty Little Bag, a Little Chisel, and a Little Glove
- Place a stack of stone and one grass block in the Little Bag
- Use the chisel to create two stone tiles, each larger than a half a block
- Set the glove for replace mode, Grass Block
- Use the glove to replace one of the stone tiles with grass
- Use the glove to attempt to replace the second stone tile with grass
- An error message appears and the replace fails
- Observe that the second tile appears to have vanished
- Attempt to walk through the space of the second tile
- Observe that it is difficult to move as (I believe) the client and server differ on the player location
- Close and reopen the world
- Observe that the second tile has reappeared and is now stone

## Expected Behavior

Tiles should not vanish if a replace operation fails.

## Details
|| Versions |
|--|--|
| **Minecraft:** | 1.12.2 |
| **Forge:** | 14.23.5.2838 |
| **LittleTiles:** | 1.5.0-pre158 |
| **CreativeCore:** | 1.9.62 |
| **Other mods:** | No, reproducible with just LittleTiles |

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming pre-release as well. Thanks for your detailed description!!! Very helpful.

**Comment by CreativeMD** [comment]
The new pre-release it out.
