### ISSUE TITLE
Client crash with StackOverflow when another player opens a door

### ISSUE THREAD

**Issue by LemADEC** [CreativeMD/LittleTiles#234]
As of CreativeCore_v1.9.62_mc1.12.2 + LittleTiles_v1.5.0-pre158_mc1.12.2, a player crashed with a StackOverflow error when another player opened a door next to them.

https://gist.github.com/LemADEC/bb25a7bb72817bb266a2c898f7b4f4b2

Issue appears to be intermittent.

**Comment by CreativeMD** [comment]
You are using pre157, this issue has been fixed in pre158.
