### ISSUE TITLE
Client can't render Little Chisel

### ISSUE THREAD

**Issue by SomeRandomPetey** [CreativeMD/LittleTiles#236]
Every time i try to render the little chisel item, in any gui, and even in the world as an entity, my game just crashes. 

this was after using /give to give the item
https://paste.dimdev.org/zehasotagu.mccrash

this was after trying to render the item in jei
https://paste.dimdev.org/asiwuxidum.mccrash

I'm using v1.5.0 pre 155

**Comment by kirokadura** [comment]
You are using outdated versions of both LittleTiles and CreativeCore.

Please always use the latest versions:

https://www.curseforge.com/minecraft/mc-mods/creativecore/files/2757265

https://www.curseforge.com/minecraft/mc-mods/littletiles/files/2757264
