### ISSUE TITLE
BetterPortals compatibility

### ISSUE THREAD

**Issue by Johni0702** [CreativeMD/LittleTiles#237]
https://github.com/Johni0702/BetterPortals/issues/225

It appears like both BP and LT replace MC's `ChunkRenderDispatcher`.

BP basically re-implements the `ChunkRenderDispatcher` ([here](https://github.com/Johni0702/BetterPortals/blob/d8072440f0bc336a93c2798cf50c7b3e76f5e285/src/view/kotlin/de/johni0702/minecraft/view/impl/client/render/ViewChunkRenderDispatcher.kt)) to allow it to be shared by multiple `RenderGlobal` instances (i.e. multiple worlds).

LT, afaict, seems to only overwrite a single method (`uploadChunk`) to add its tiles into the vertex buffer.
Is there some other reason which I'm missing?

If there isn't, then I'd suggest changing LT to merely inject into the `uploadChunk` method of the original `ChunkRenderDispatcher` instead of fully replacing it.
BP also eventually delegates the chunks it has handled to that method, so any of LT's additions to it would be functional with BP as long as they aren't assuming there to only be one world.

**Comment by CreativeMD** [comment]
That's the best idea indeed. I changed it, can you try out whether it works now?

https://www.dropbox.com/s/6g3mqe7r7omvmy6/CreativeCore_v1.9.63_mc1.12.2.jar?dl=1
https://www.dropbox.com/s/gzaenymi8mg584d/LittleTiles_v1.5.0-pre159_mc1.12.2.jar?dl=1

**Comment by Johni0702** [comment]
Great, appears to be fully working now afaict.

**Comment by CreativeMD** [comment]
Nice to hear that! Thanks for your help. I will release the new version this week.

**Comment by VirtualGaming1** [comment]
I will test it in my modpack as well if there is anything improved as well. also @CreativeMD are there any other mod(s) dose the same thing as well that I might have installed?

**Comment by CreativeMD** [comment]
It took a lot longer, but it's finally released.
