### ISSUE TITLE
Large Doors still cause problems

### ISSUE THREAD

**Issue by Tschipp** [CreativeMD/LittleTiles#238]
I'm sure you're aware of this, but large doors frequently have animation  issues when opening and closing, sometimes even when standing still.

I don't know if it's possible to improve, but if you could look into it would be nice.

**Comment by CreativeMD** [comment]
Can you provide a screenshot? Not sure what you mean.

EDIT
Would also be very helpful if you could export the structure and post it here.

**Comment by Tschipp** [comment]
Ok, will do.

**Comment by Tschipp** [comment]
Structure: https://pastebin.com/CXbqRRqc

How it's supposed to look like:
![image](https://user-images.githubusercontent.com/11649893/63024301-3a64a100-bea7-11e9-87f1-1c54b90f6945.png)

How it can look like when it glitches:
![2019-08-14_15 20 21](https://user-images.githubusercontent.com/11649893/63024447-81eb2d00-bea7-11e9-8a6f-55c9427d4f65.png)

**Comment by Dushess** [comment]
Seems to be it's just too large to animate smooth.

**Comment by CreativeMD** [comment]
Tried it out and it looks like it's fixed in the newest pre-release. You will have to test it once it's out. Hope to release it the next two days.

**Comment by Tschipp** [comment]
Nice!

**Comment by Arkunar** [comment]
almost the exact same problem on the version of the mod "Little Tikes_v1.5.0-pro 158_mc1.12.2"
Only the doors open fine, when I open them, but if they are opens someone else, I see the result just like in the screenshot above

**Comment by nexitem** [comment]
Having similar issues when other players interact with my big doors
https://cdn.discordapp.com/attachments/471464469634088962/627632015780610098/unknown.png
https://cdn.discordapp.com/attachments/471464469634088962/627639600197926912/unknown.png

**Comment by CreativeMD** [comment]
Should be fixed now!
