### ISSUE TITLE
[Bug] [1.10.2] 

### ISSUE THREAD

**Issue by AstralDestiny** [CreativeMD/LittleTiles#24]
Using
- LittleTiles v1.3.5 mc1.10.2
- CreativeCore v1.6.18 mc1.10.2

http://pastebin.com/L3hhfPht

Upon updating to your latest release the server will no longer start, It fails with the included error/debug log.

- forge-1.10.2-12.18.3.2202

**Comment by CreativeMD** [comment]
Which forge version do you use? I'm using the newest Forge Version (1.10.2-12.18.3.2221) and it works fine.

**Comment by AstralDestiny** [comment]
2202 due to SpongeForge

Without SpongeForge and with still shows that error.

Could try and update and drop SpongeForge, Only getting the "Moved to quickly" rubber banding users but with SpongeForge installed the "Moved to quickly" is disabled and or bypassed.

**Comment by AstralDestiny** [comment]
Without SpongeForge and with still shows that error.

**Comment by AstralDestiny** [comment]
Could try and update and drop SpongeForge, Only getting the "Moved to quickly" rubber banding users but with SpongeForge installed the "Moved to quickly" is disabled and or bypassed.

**Comment by CreativeMD** [comment]
I tested it using spongeforge-1.10.2-2123-6.0.0-BETA-1902 and it works just fine, no crashes during startup.

EDIT
Maybe try out the newest version of CreativeCore, this might fix this bug as well.

**Comment by AstralDestiny** [comment]
Seems to be fixed. Though No idea if it will break in the future I'm using Sponge Bootstrap which can be found [here](https://forums.spongepowered.org/t/spongebootstrap-fixes-ordering-issue-with-other-coremods/12275/5)

**Comment by AstralDestiny** [comment]
Nevermind.. When using a door for a recipe, upon right clicking the door the door moves followed by vanishing, http://pastebin.com/q43j0ZHx

**Comment by CreativeMD** [comment]
Could you try out the newest version of CreativeCore (v1.6.20)? The issue may be fixed.

**Comment by AstralDestiny** [comment]
Will do soon, already pushed the update out to users, haven't tried it yet
(I'm the only one who has Creative, the others are busy expanding their
automation before they work on cosmetic and such.)

**Comment by AstralDestiny** [comment]
http://pastebin.com/vxA58DU0 Upon right clicking the door as soon as it hits the end of the opening it disappears, I could provide you with the pack download and such, Though how would I message you?
I could also provide real time console access to the server also..

**Comment by CreativeMD** [comment]
Ok, yes i forgot something. Hope now it will work out:
https://www.dropbox.com/s/nnkgdhe72juedkf/CreativeCore%20v1.6.21%20mc1.10.2.jar?dl=1
https://www.dropbox.com/s/zej7gzc5ea5csm6/LittleTiles%20v1.3.9%20mc1.10.2.jar?dl=1

**Comment by AstralDestiny** [comment]
The door works, but a bit glitchy in movement. No console errors so far, Haven't done extensive tests on other parts, Though modded blocks don't work it seems (EnderIO glass doesn't work for hammers) Will report later on today, EST here, 6:15 pm at the time of writing this.

**Comment by AstralDestiny** [comment]
Also wondering what's the "/creative-gui" for?

**Comment by CreativeMD** [comment]
Can test if it's better with that version?
https://www.dropbox.com/s/7hqb7mnvvzd1nmq/LittleTiles%20v1.3.10%20mc1.10.2.jar?dl=1

The command is used for a test gui, showing some stuff my gui-api is able to do.

**Comment by AstralDestiny** [comment]
Still a bit buggy, jitters when it moves. Shall I send a link to the pack? or?

**Comment by CreativeMD** [comment]
Yeah, but that's another think, for now i will call this fixed. I will try to find out why the client is rotating the door faster than the server.

**Comment by AstralDestiny** [comment]
It seems to be slower, Even though the server uses a module to prefer realtime instead of 20ticks.
