### ISSUE TITLE
[Crash] 1.5.0-pre158 StackOverflowError

### ISSUE THREAD

**Issue by MichaelKotwica** [CreativeMD/LittleTiles#240]
Context:

Mod Versions:

- `CreativeCore_v1.9.62_mc1.12.2`
- `LittleTiles_v1.5.0-pre158_mc1.12.2`

- Door before opening
![image](https://user-images.githubusercontent.com/45274996/63204829-8ce9bd00-c061-11e9-999e-6823b7113544.png)

- Door after opening

![image](https://user-images.githubusercontent.com/45274996/63204857-e9e57300-c061-11e9-9b51-b88ad4d1c583.png)

Note: Works in preview but gives `java.lang.StackOverflowError: Exception in server tick loop` when opening the door as an object in game.

- The main door consists of the 18 grey rectangles, the orange door, and a white strip in the front.
- The grey rectangles and the orange door are children of a small white strip in the front.

![image](https://user-images.githubusercontent.com/45274996/63205153-25823c00-c066-11e9-8203-0d8f75a31df4.png)
![image](https://user-images.githubusercontent.com/45274996/63205158-35018500-c066-11e9-9421-a35335538055.png)

- The grey rectangles rotate Z +1800 degrees and forward +6 Z on a 32 grid then goes down to their respected locations. They all activate at 20 tick intervals apart and are children of the white strip in the back as shown below.
![image](https://user-images.githubusercontent.com/45274996/63205008-b0156c00-c063-11e9-99c4-46711f829acd.png)

![image](https://user-images.githubusercontent.com/45274996/63205198-e6081f80-c066-11e9-976c-6b38be6670f1.png)

![image](https://user-images.githubusercontent.com/45274996/63205018-cae7e080-c063-11e9-88e4-0cda413a2d02.png)

- This is the orange door by itself (It does not have any children).
![image](https://user-images.githubusercontent.com/45274996/63205124-a1c84f80-c065-11e9-838a-01d60d3f55b6.png)

Crash Report:
[crash-2019-08-16_19.43.22-server.txt](https://github.com/CreativeMD/LittleTiles/files/3511506/crash-2019-08-16_19.43.22-server.txt)

The Door (Used little exporter):
[Orange Door with Grey Screws.txt](https://github.com/CreativeMD/LittleTiles/files/3511542/Orange.Door.with.Grey.Screws.txt)

I hope I provided enough information for you to resolve this issue. Please let me know if you need more. I am happy to help if needed :)

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming version as well, unfortunately some other issues appeared, which are rather minor (just some rendering glitches). Hope I can fix them as well.

**Comment by CreativeMD** [comment]
It's out!
