### ISSUE TITLE
Some blocks are not rendering when exiting/re-entering chunks.

### ISSUE THREAD

**Issue by SlayerTheChikken** [CreativeMD/LittleTiles#241]
![l2](https://user-images.githubusercontent.com/20819543/63206967-bf5cdf80-c08c-11e9-86ee-01c46e70668a.PNG)
![l1](https://user-images.githubusercontent.com/20819543/63206968-bf5cdf80-c08c-11e9-97e4-c87728a8ec52.PNG)

Some of the littletiles blocks are not rendering if you teleport away and come back or leave the chunk and travel back and the blocks are still registered as existing as you cannot go through them, the exact reproduction environment is Tekxit 3. I love the mod by the way! It's one of my favs in the modpack :)

Let me know if I can provide more details, or if this issue has already been solved; I looked to see if it was solved and found semi-similar issues but wasn't sure if they are the same issue.

**Comment by CreativeMD** [comment]
Should be fixed in the upcoming pre-release.

**Comment by SlayerTheChikken** [comment]
Yay, thank you :)

**Comment by CreativeMD** [comment]
Finally it's out!
