### ISSUE TITLE
Smooth lighting

### ISSUE THREAD

**Issue by CRE4TIVE** [CreativeMD/LittleTiles#242]
The blocks of little tiles don't have as good smooth lighting as default MC blocks so they don't look too much plastic and lack shading!

**Comment by CreativeMD** [comment]
Can you provide an example screenshot?

**Comment by CRE4TIVE** [comment]
yes wait...

**Comment by CRE4TIVE** [comment]
It'll take some time I can't take screenshots with my keyboard.

**Comment by CRE4TIVE** [comment]
How do I put here photos?

**Comment by CreativeMD** [comment]
you have to upload it somewhere else (I would suggest imgur) and link it here.

**Comment by CRE4TIVE** [comment]
ok

**Comment by CRE4TIVE** [comment]
https://i.imgur.com/RLOwegO.jpg
https://i.imgur.com/h307v4U.jpg
https://i.imgur.com/h6SYFkT.jpg

**Comment by CRE4TIVE** [comment]
From the side view I can see the separation of the bits but from the front view all bits will merge to the stone texture without shading. The default stone block looks more separated from the other ones which are behind thanks to the the smooth lighting. But the bits on the stone ball don't.

**Comment by CreativeMD** [comment]
There are some shading issues, but it's still smooth lighting. Unfortunately there is not much I can do about it. Just keep in mind that LT blocks don't block light, this might cause some unwanted shading effects.

Other than that, if Optifine is installed there are a few more shading issues compared to just forge. Sorry about that, hope you can enjoy the mod nonetheless.

**Comment by CRE4TIVE** [comment]
Yes this mod is just amazing for creativity. One thing I wish to add is redstone to doors and animated structures like spinning wheels or structures where the tiles are moving or appearing and disappearing. This would be amazing!

**Comment by CreativeMD** [comment]
Redstone is planned and will be implement this year (hopefully).

**Comment by CRE4TIVE** [comment]
I just look forward that. Keep it up!

**Comment by CRE4TIVE** [comment]
Can I ask where do I put pictures about my building? I use this mod to build roller-coaster and it looks awesome.

**Comment by CreativeMD** [comment]
You can join our discord server and post it there: https://discord.gg/W9QM3fS
