### ISSUE TITLE
Advanced recipe axis door

### ISSUE THREAD

**Issue by SimexOriginal** [CreativeMD/LittleTiles#243]
Hello, i made a door and i wanted just to test how it works, i put it on the ground and it turned 180 degrees and it retunrs again to the 90 degree position and i cant remove it because it can't go in the original position on the 0 degree, i am trying to hit it nothing happens, i tried removing it with worldedit that didn't help either now the door is just staying on the ground and im unable to remove it.. i dont know if this is a glitch or not but i would like to get a solution to this problem because its annoying its just staying in mid of the road.

**Comment by CreativeMD** [comment]
You probably figured it out already, but you can remove it using the wrench (just right click and hit 'destroy animation'
