### ISSUE TITLE
Shadowing issue

### ISSUE THREAD

**Issue by beefycomputer** [CreativeMD/LittleTiles#245]
https://gfycat.com/frenchlinedgrouse black where no black should be.

**Comment by SlayerTheChikken** [comment]
I think in general this is an issue with default minecraft lighting (I think even in vanilla I had this issue with slabs and stairs awhile back) and if it were to be fixed it may change the way mc lighting works.. I could be wrong tho :3

**Comment by CreativeMD** [comment]
I can't reproduce this issue. Is optifine installed as well?

**Comment by beefycomputer** [comment]
Yes, I do have optifine installed. The latest version for 1.12.2

**Comment by CreativeMD** [comment]
Can you remove Optifine and see if it fixes the issue?

**Comment by CreativeMD** [comment]
Have you tried it already?

**Comment by beefycomputer** [comment]
> Have you tried it already?

sorry no. when I do I will tell you

**Comment by CreativeMD** [comment]
Sorry this issue will not be fixed in 1.12. Let's hope things are better in 1.16.
