### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by axin0452** [CreativeMD/LittleTiles#246]
When the player uses the storage box to make the storage items, player A places this block and puts the items in it. player B opens and takes out the items. player B does not need to open them, digs them directly and puts them back. The contents are still there.

CreativeCore_v1.9.62_mc1.12.2
LittleTiles_v1.5.0-pre158

forge-1.12.2-14.23.5.2825-universal
spongeforge-1.12.2-2825-7.1.6

**Comment by CreativeMD** [comment]
Hey there! Sorry for not responding earlier. Your issue is rather complicated to solve, that's why I haven't done anything yet. There were plenty of other issues I had to fix first. I will attempt to fix it the next days.

**Comment by CreativeMD** [comment]
Fixed in the newest pre-release. Thanks for reporting this issue!
