### ISSUE TITLE
Door incompatibility with Cubic Chunks

### ISSUE THREAD

**Issue by Deliphin** [CreativeMD/LittleTiles#247]
```
MOD          VER
CreativeCore 1.7
CubicChunks  1.12.2-0.0.990.0-SNAPSHOT
CubicGen     1.12.2-0.0.67.0-SNAPSHOT
LittleTiles  v1.5.0-pre158_mc1.12.2
MalisisCore  1.12.2-6.5.1
MCMultiPart  2.5.3
```

Sliding Door below Y=0 Crashlog: https://pastebin.com/KkhA5dYS

My MultiMC instance: https://mega.nz/#!MDBnzADb!wodvyoczotNY52lCivUYUG7-A61vduaeXOLNDr3LxMg

Made this test modlist, with literally as few mods as possible to have both a Cubic Chunks world and LittleTiles.

The only thing that causes a crash is LittleTiles' Doors, when outside of Y=0 and Y=256.
It doesn't appear to cause any corruption, it just crashes the server. When reloading, the door disappears.

The crash occurs when the door is used. It places fine, but as soon as you right click it, the game crashes.

Replicating is simple. Install all these mods, and try to place a door outside of Y=0 and Y=256. I had a friend test fixed, ladders, beds, chairs and storage, all those work, this only occurs with doors. Axis doors, sliding doors, etc.. doesn't matter.
I've provided my MultiMC instance above so you don't have to collect it all yourself. Even has a world with some doors and a stairway to below Y=0.

**Comment by kirokadura** [comment]
This is unfortunately a known issue. We would have to hear it directly from CreativeMD, but I think it's got something to do with how the doors create a "fake parallel world" to render the doors movements, but that clashes when used out of vanilla limits. Basically, anything that requires animation is affected, so all the door types.

**Comment by Deliphin** [comment]
If I could at least have a config option to disable all items with this problem (all doors), I'd be much happier.

**Comment by CreativeMD** [comment]
I have fixed the crash, the doors will not attempt to move. It will be part of the upcoming pre-release.

**Comment by Deliphin** [comment]
Thanks, that's a lot better than crashing. Although do you think making doors work outside of 0-255 would be possible in the future?

**Comment by CreativeMD** [comment]
Not in the near future. Already talked to the author of CubicChunks and it's not that easy. Maybe it will be better for newer versions.

**Comment by CreativeMD** [comment]
It's out now!

**Comment by Dushess** [comment]
You will laugh, but it still(?) crashes. CC is 1055 shapshot on 1.12.2, LT is pre199_72, core is 1.10.25 Seems to be outdated Cubic CHunks...
