### ISSUE TITLE
Trouble when using sliding door

### ISSUE THREAD

**Issue by Lucatim** [CreativeMD/LittleTiles#248]
Hi,

I've build this door with Chisel & bits : https://cdn.discordapp.com/attachments/584481100966002698/585215128857870336/2019-06-03_22.48.07.png

I tried to animate it with Little Tiles. I transformed the structure in Little Tiles, I followed your tutorial with animated door (including door activator). Everything is fine, But when the Little Tiles structure (the two doors, and the structure around the two doors) is installed back in decor, and I activate it, I have trouble like this thing when it's opening : https://image.prntscr.com/image/QCzdGhJgQVGsYD9gIao0gw.jpeg

When it's closing, I don't have such problem : https://image.prntscr.com/image/BjTsfmNjS6mfxTlAMOqmDQ.jpeg

Do you have any idea what could cause this problem?

Mods installed in my modpack : http://prntscr.com/p09zpd

Thank you.

**Comment by kirokadura** [comment]
Sorry, but those first couple links are not working.

**Comment by Lucatim** [comment]
![door_build](https://user-images.githubusercontent.com/33254902/64075950-2c908780-ccbf-11e9-8ea8-340ddbe79cca.png)
![door_glitch](https://user-images.githubusercontent.com/33254902/64075951-2c908780-ccbf-11e9-91b4-f7d009141cea.jpeg)
![door_open_ok](https://user-images.githubusercontent.com/33254902/64075952-2c908780-ccbf-11e9-893b-27cf883f49b9.jpeg)
![mod_list](https://user-images.githubusercontent.com/33254902/64075953-2c908780-ccbf-11e9-94fc-f8a2fc368ddb.jpg)

**Comment by kirokadura** [comment]
Does it persist if you activate the "Stay Animated" option?

**Comment by Lucatim** [comment]
Ok, if I activate "Stay Animated", it's glitching only the first time, but then it's ok.

If it's desactivated, it's glitching each time I open it.

Do wou want the structure code with little exporter?

**Comment by kirokadura** [comment]
It seems to glitch out when it goes between the "placed" and "entity" states. Stay Animated garantees that it'll always stay in an entity state, so the placing won't make weird rendering issue. It's hard to say precisely what's causing it, but since you have Foamfix and BetterFPS, one of them might be messing with the rendering. This can also happen in servers with too much lag, or on singleplayer with very little FPS. 

Give me the export and I can test it out.

**Comment by kirokadura** [comment]
On a side note, fantastic job with the build! Great color choices and models.

**Comment by CreativeMD** [comment]
@Lucatim could you send me the exported code? I would love to test it myself.

**Comment by CreativeMD** [comment]
This bug might be fixed in the newest pre-release, not sure though.

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still happens, make sure to send me the structure code, so I can test it myself.
