### ISSUE TITLE
Rendering for water becomes quite ugly when re-entering a world

### ISSUE THREAD

**Issue by Sourpowerpete** [CreativeMD/LittleTiles#249]
https://i.imgur.com/xdVyxUr.png

I'm not quite sure what caused this, but basically, it was a small issue while building the aquarium, but now the issue is *everywhere*.

**Comment by CreativeMD** [comment]
Can you export the aquarium?

**Comment by CreativeMD** [comment]
Still there?

**Comment by Sourpowerpete** [comment]
Here's the aquarium.

https://pastebin.com/w5KTi33W

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming version.

**Comment by CreativeMD** [comment]
New pre-release is out. Thanks for reporting this issue!
