### ISSUE TITLE
[Bug][MC1.10.2][LT1.3.5] Little Recipe/Wrench/Storage not working in Survival Mode

### ISSUE THREAD

**Issue by Aedda** [CreativeMD/LittleTiles#25]
In survival mode it is not possible to create structures such as storage, doors, or fixed.

Steps to reproduce (as storage):
1) Get a block for the decor/outside of the storage, wood, marble, whatever
2) Get the Little Storage Block
3) Place storage block and carve away sides, and the top twice to get 14x14x14 or use hammer per tutorial
4) Use rubber mallet to raise block 1 bit off surface
5) Use hammer tool to turn decor block into an LT block
6) Place decor block over storage block as per tutorial

All is well up to this point, this is where it breaks in survival.

7) Take a Little Recipe and right click block twice to record it (in creative the Little Recipe item will now display an icon of the structure, in survival the entire texture will break and become magenta/black checkers)
8) Right click Little Recipe and choose Storage, it will show the expected storage capacity and hit save (this seems to work)
9) Use Little Wrench to turn Little Recipe into final structure (in creative the object will be created, in survival it will display a list of blocks I presume are missing from the inventory and nothing else happens)
10) If in creative and structure has been created place structure and enjoy, if in survival try to figure out what just went wrong...

Then
1) Give yourself a Little Container, which was obviously missing from the above process
2) Give yourself several of the Little Storage blocks and several of whatever decor block you chose, I tried 1 of each, 20 of each, 200 of each... and put them in the Little Storage
3) Little Recipe will still display broken texture, resume from step 9 above, get same result like the materials are missing

Mod versions used:
Minecraft 1.10.2
Forge 2221
Little Tiles 1.3.5
Creative Core 1.6.18

**Comment by CreativeMD** [comment]
I'm on it, hope i can release a fix soon.

**Comment by CreativeMD** [comment]
Could you try out the newest version pre7 and see if your issue are fixed?

EDIT
v1.4.0 has been released, everything should work now.
