### ISSUE TITLE
Exporting big model with low resolution

### ISSUE THREAD

**Issue by em411** [CreativeMD/LittleTiles#253]
LT ver: pre158
CC ver: 62

When im trying to export model with a few thousands of tiles as json it's exporting in low res mode.

Model: https://cdn.discordapp.com/attachments/256109634769780737/620288040778203136/unknown.png
https://cdn.discordapp.com/attachments/256109634769780737/620288147267256368/unknown.png

Result:
https://cdn.discordapp.com/attachments/256109634769780737/620288378981711892/unknown.png

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming version. Thanks for reporting this issue!

**Comment by CreativeMD** [comment]
New pre-release it out!
