### ISSUE TITLE
Unbreakable tiles still cause durability damage

### ISSUE THREAD

**Issue by DarkYuan** [CreativeMD/LittleTiles#254]
If you have no Little Bag, trying to break something would tell you that there's not enough room in your inventory. If you were using a tool to break it, like a pickaxe, it would still be damaged from the interaction. Considering how fast these tiles break, you can drain a tool just by misclicking.

**Comment by CreativeMD** [comment]
I plan to add some quality of life improvements for survival:
* increase the duration of mining tiles
* add a way to mine tiles without a bag

I don't know when I will get to it, first of all I need to fix the game breaking issues.

**Comment by CreativeMD** [comment]
This issue has been solved in the recent update. Make sure to update CreativeCore and LittleTiles.
