### ISSUE TITLE
No tiles made when hammering double slab blocks without item IDs

### ISSUE THREAD

**Issue by DarkYuan** [CreativeMD/LittleTiles#255]
Tested by hammering a double Crag Stone Slab from Traverse. I assume since there's no entry for the double slab as an item (at least it can't be found in JEI), it produces no tiles for your bag.

Expected behaviour: when a block like this is found not to have any tiles, produce tiles of the slab instead?

**Comment by kirokadura** [comment]
You can't hammer a slab, same for stairs, fences, farmland, etc. Only full blocks are acceptable for LT.

**Comment by DarkYuan** [comment]
Oops. Still kinda sucks that it doesn't give anything back.

**Comment by kirokadura** [comment]
Technically that is not supposed to happen. Can you replicate this behavior with vanilla double slabs, such as stone or wooden planks?

**Comment by DarkYuan** [comment]
Well that's... something
![2019-09-25_13 58 23](https://user-images.githubusercontent.com/3029695/65622802-d6042980-df9c-11e9-81c8-3aefa659fba0.png)
![2019-09-25_13 59 53](https://user-images.githubusercontent.com/3029695/65622808-d997b080-df9c-11e9-82c9-4ea167fc19e2.png)

**Comment by kirokadura** [comment]
Does it still break the slabs or does it just give air?

**Comment by DarkYuan** [comment]
When hammering double slabs, it breaks down and I get tiles of those blocks called "Air." They still place like normal, but only by taking the tiles out of the bag, the chisel won't work.

**Comment by CreativeMD** [comment]
Does it still happen in pre162?

**Comment by DarkYuan** [comment]
Ok, so now when I hammer double slabs, it still works, but I get no tiles. In fact, I get no tiles from **anything**.

**Comment by CreativeMD** [comment]
It's fixed in the newest pre-release. Slabs are now excluded entirely. Thanks for reporting this issue!
