### ISSUE TITLE
Door teleports back when closing it with little opener and commands

### ISSUE THREAD

**Issue by MichaelKotwica** [CreativeMD/LittleTiles#256]
When I was testing out a door with the little opener, it opens normally. However, when trying to close it, it teleports back instead of moving back. Manually Right-clicking the door normally opens and closes the door.

An example is shown in this video:
https://youtu.be/XGaFiR9SoIw

Additionally, I did further testing using the command `/lt-open [x, y, z]` and it the results were the same as shown in the video.

Edit: 

- I am using Little tiles version 1.12.2 Pre158

- Manually Right-clicking the door normally opens and closes the door.

**Comment by CreativeMD** [comment]
Should be fixed in the newest pre-release, if not just reopen this one.
