### ISSUE TITLE
New version doesn't fix LittleTiles doors from crashing the game outside of 0-256

### ISSUE THREAD

**Issue by Deliphin** [CreativeMD/LittleTiles#258]
Tested on a test modpack of literally nothing but the newest Cubic Chunks, CubicWorldGen and Little Tiles.

https://pastebin.com/58MfMrRD

Still crashed the second I tried opening a door below Y=0. I did a 2 block tall door at Y=-6

This is a modpack with only the following:
CreativeCore_v1.9.66_mc1.12.2
CubicChunks-1.12.2-0.0.1003.0-SNAPSHOT-all
CubicWorldGen-1.12.2-0.0.68.0-SNAPSHOT-all
LittleTiles_v1.5.0-pre161_mc1.12.2
malisiscore-1.12.2-6.5.1

**Comment by CreativeMD** [comment]
I have fixed the crash, but what about the invisible blocks. Is there anything in the logs? Maybe it's caused by Malisiscore?

**Comment by Deliphin** [comment]
Ah, sorry, I had the title issue first, and then I noticed the crash, and forgot to change the title.
The invisibility issue I found was likely a config issue, as on a brand new modpack and map, it wasn't there.

**Comment by Deliphin** [comment]
Just tested LittleTiles_v1.5.0-pre163_mc1.12.2.
Doors don't move, but the game doesn't crash. While not perfect, this is significantly better. Thanks :D
