### ISSUE TITLE
[Bug][MC1.10.2][LT1.3.5] Little Utility Knife block break speed inconsistant in Survival

### ISSUE THREAD

**Issue by Aedda** [CreativeMD/LittleTiles#26]
This had me confused for a while, I thought the tool was breaking.

In Survival the first action by the Little Utility Knife has no block break delay, as if it were Creative mode. All subsequent actions on the same block have a delay such as wooden shovel vs. dirt. This makes the tool usage confusing as it gives the impression only the first action can be taken.

Steps to reproduce:
1) Place any block, use Little Utility Knife once, action will be instant.
2) Use Little Utility Knife again on the same block, action will take a couple seconds.

Also worth considering is the time it takes to break a single bit, at current each bit takes as long as breaking an entire dirt block with a wooden shovel.
 
Mod versions used:
Minecraft 1.10.2
Forge 2221
Little Tiles 1.3.5
Creative Core 1.6.18

**Comment by CreativeMD** [comment]
It is fixed in LittleTiles v1.3.7. Thanks for reporting this issue.
