### ISSUE TITLE
When trying to destroy a LittleTiles Block game crashes

### ISSUE THREAD

**Issue by nexitem** [CreativeMD/LittleTiles#261]
https://paste.dimdev.org/ayaluwuyad.mccrash

After updating CreativeCore, Online Pciture Frames and LittleTiles to the latest versions I cannot destroy any littletiles block or the game crashes.

**Comment by nexitem** [comment]
This does not happen when I launch a singleplayer game and do it on a fresh world...

Only on the multiplayer server. hmm

**Comment by CreativeMD** [comment]
Fixed in the newest version, which should be available by now. Thanks for reporting this issue!
