### ISSUE TITLE
Grid align option 

### ISSUE THREAD

**Issue by vinz243** [CreativeMD/LittleTiles#262]
Hello, 

I was transitioning from C&B to LittleTiles and one feature that really is lacking is the align option. I can use the glove to place 8x8x8 tiles, but I can't easily align them on a 2x2x2 grid as easily as C&B. It would be a really good addition to C&B tools. Maybe pressing like +/- to select grid size and align everything easily. 

I'd like to help but I don't have a lot of time, but if you could point me in the right direction that would be really useful

Thanks in advance

**Comment by kirokadura** [comment]
Have you tried changing the grid size to 2 in the CTRL+C menu? Ir essentially changes the grid to be 2x2x2 and it'll snap to that grid.

**Comment by vinz243** [comment]
Exactly what I was looking for, thank you very much !
