### ISSUE TITLE
Z-Fighting, CTM issues with Chisel Marble Pillar blocks

### ISSUE THREAD

**Issue by loudwhitenoise** [CreativeMD/LittleTiles#264]
Minecraft 1.12.2, Forge 14.23.5.2847, Chisel 0.2.1.35, CTM 0.3.3.22, CC 1.9.66, LT pre-164 *and* -167.
Issue persists after client restart. Difficulties replicating issue in creative testing world. Issue created anyway as per request.
Demonstration video: https://youtu.be/0xe9fSx6QEk
Creative testing image: https://cdn.discordapp.com/attachments/276752435869908993/629322973639213086/2019-10-04_00.23.02.png

**Comment by CreativeMD** [comment]
Just a question do connected textures still work?

**Comment by OmaiGrundles** [comment]
Just to chime in here, the pillar blocks from chisel seem to be very buggy/unreliable in general. Ive had several issues with them over the years all the way back to 1.7.10 and carpenter's blocks.

**Comment by CreativeMD** [comment]
I have tried to reproduce this issue myself, but everything works fine for me. I used the newest version of CTM, Chisel and LittleTiles:

Chisel-MC1.12.2-1.0.0.42
CTM-MC1.12.2-1.0.0.29
CreativeCore_v1.9.68_mc1.12.2
LittleTiles_v1.5.0-pre168_mc1.12.2
preview_OptiFine_1.12.2_HD_U_F4_pre3

![](https://i.imgur.com/sp2oiXl.png)

**Comment by CreativeMD** [comment]
I will close this issue for now. I think it can be fixed by updating all the mods.
