### ISSUE TITLE
'No space for material' when using materials out of bag

### ISSUE THREAD

**Issue by Lovatic123** [CreativeMD/LittleTiles#265]
Since I started using this mod, its been so you can either put stuff into the little bag and use materiels from there, or you could choose to use materials from your inventory, and then the materials left, that would be less than a full block, would go into the bag.

This doesnt work anymore. I can use the materials from the bag, but not from my inventory. Im using LittleTiles 1.5.0., pre 167, and CreativeCore 1.9.67.

-Lovatic123

**Comment by CreativeMD** [comment]
Your issue has been fixed. Thanks for reporting it! I will upload the new pre-release soon.

**Comment by CreativeMD** [comment]
It's out now.
