### ISSUE TITLE
How to programatically add a new box

### ISSUE THREAD

**Issue by vinz243** [CreativeMD/LittleTiles#267]
I'm trying to programatically add new Box to an extisting tile :

```java
TileEntity tileEntity = world.getTileEntity(new BlockPos(vector.getBlockX(), vector.getBlockY(), vector.getBlockZ()));
if (tileEntity instanceof TileEntityLittleTiles) {
    TileEntityLittleTiles tiles = (TileEntityLittleTiles) tileEntity;
    LittleTileBlock tile = new LittleTileBlock(littleTile.getBlock(), littleTile.getMeta());// LittleTile.CreateandLoadTile
    tile.te = tiles;
    tile.setBox(littleTileBox);
    tiles.place()
}
```

However when this is executed nothing happens

**Comment by CreativeMD** [comment]
You should rather use one of the Actions, like LittleActionPlaceStack or LittleActionPlaceAbsolute. Everything is done there already.

**Comment by vinz243** [comment]
I'm trying to do something lower level, because I need to apply geometric 3d transforms (like mirroring etc)

**Comment by CreativeMD** [comment]
There is already mirroring. Besides that you should rather work with previews and hand them over to the actions. You might want to take a look at the door code, it might give you an idea of how this works ([source](https://github.com/CreativeMD/LittleTiles/blob/1.12/src/main/java/com/creativemd/littletiles/common/structure/type/door/LittleDoorBase.java#L195)).

**Comment by vinz243** [comment]
I found that it was a lack of a few things (needed to convert grid context, updateTiles, etc). However in a few stiuations I have a few glitches, but I guess Ill check it on my own

**Comment by CreativeMD** [comment]
I can only highly recommend to use the Actions because it takes care of literally everything. It doesn't make sense to do it somewhere else again, but that's your choice.

**Comment by vinz243** [comment]
I needed something lower level to replicate the effects of actions into other blocks. With actions I would have to do this for every action, or redefine the whole caller hierarchy

**Comment by CreativeMD** [comment]
Maybe create a new action, don't know.
