### ISSUE TITLE
Crashing bug

### ISSUE THREAD

**Issue by ACrazyD** [CreativeMD/LittleTiles#268]
This happens anytime a user attempts to "Chisel" blocks in survival, does not affect users in creative.

The Log i pinned below shows the mods/Error  I was thinking it was some sort of issue with mods, but i cant tell what mods in order to fix them

LOG: [https://paste.dimdev.org/ugokegunir.mccrash](url)

**Comment by CreativeMD** [comment]
This crash has been fixed already, please update to the newest version of CreativeCore and LittleTiles.
