### ISSUE TITLE
[Bug][MC1.10.2][LT1.3.5] Little Utility Knife breaks Bedrock in Survival

### ISSUE THREAD

**Issue by Aedda** [CreativeMD/LittleTiles#27]
When in Survival one is able to carve right through Bedrock, and it appears there is no blacklist to prevent this action.

Steps to reproduce:
1) Carve Bedrock with Little Utility Knife

Mod versions used:
Minecraft 1.10.2
Forge 2221
Little Tiles 1.3.5
Creative Core 1.6.18

**Comment by CreativeMD** [comment]
It is fixed in LittleTiles v1.3.7. Thanks for reporting this issue.
