### ISSUE TITLE
Unlimited Crafting at Little Workbench

### ISSUE THREAD

**Issue by MeycsHD** [CreativeMD/LittleTiles#270]
Hey!

Crafting on Little Workbench doesn't consume the blocks.

Mod version: LittleTiles_v1.5.0-pre168_mc1.12.2
Forge: forge-14.23.5.2847
Minecraft 1.12.2

Meycs / Marco :)

LOVE THIS MOD <3

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming version.

**Comment by MeycsHD** [comment]
Thank you! :)

**Comment by CreativeMD** [comment]
Finally released the new version! Thanks for reporting this issue!
