### ISSUE TITLE
Can't make use of sideways logs

### ISSUE THREAD

**Issue by Xemiru** [CreativeMD/LittleTiles#271]
*Little Tiles v1.5.0-pre168*
*Minecraft Forge 14.23.5.2836*
*Minecraft 1.12.2*

While attempting to use the sideways log texture for sculpting a bridge, I've noticed there wasn't a way for me to tell the chisel to specifically use the sideways log for placing tiles.

I'm told that in previous iterations it was possible to do so **by breaking a placed sideways log in the direction I wish to use it in** so it would be placed into the bag and be made usable albeit with a broken texture, however this currently doesn't seem to be possible anymore as **the sideways log seems to merge with the normal log inside the bag.**

**Comment by CreativeMD** [comment]
That's not a bug but a feature. If you want to use sideway logs you have to pick the placed log with the middle mouse button. It consume normal logs (which is the need feature), no separate ingredients for each log variant.
