### ISSUE TITLE
[Feature Request] Redstone Button

### ISSUE THREAD

**Issue by Deliphin** [CreativeMD/LittleTiles#274]
Not exactly sure how it would work, but I would like to be able to make custom buttons.

**Comment by CreativeMD** [comment]
It's planned, but I don't know when I will get to it.

**Comment by SlayerTheChikken** [comment]
@CreativeMD to add to this, maybe even redstone-wire like stuff, that would replace many many mods, though im not sure how difficult it would be..

**Comment by CreativeMD** [comment]
I will start to work on it soon.

**Comment by Deliphin** [comment]
FYI, SimpleLogic's Wires work perfectly fine with LittleTiles, including even being blocked (no redstone connection) on sides that have LT blocks blocking the path.
Meaning, adding redstone wire stuff probably shouldn't be a high priority, since if you want to hide wire, you could just put it a block under or in a wall and cover it up with LT's blocks.

**Comment by CreativeMD** [comment]
We shall see.
