### ISSUE TITLE
Random Crash when Dying

### ISSUE THREAD

**Issue by nexitem** [CreativeMD/LittleTiles#276]
I wanna say that I'm not sure Little Tiles is responsible for this crash becuase it also says on the error report it might be "Dynamic Surroundings" or "Galacticcraft Core" (doubtful) but maybe someone can point me in the right direction.

This sometimes happens when I die and respawn

https://paste.dimdev.org/upuvuvujed.mccrash

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming version.

**Comment by CreativeMD** [comment]
New version is out!
