### ISSUE TITLE
GUI not coming up

### ISSUE THREAD

**Issue by win10Device** [CreativeMD/LittleTiles#278]
Right clicking the Hammer Is supposed to bring up A GUI
BUT for some reason it doesn't work 
Right clicking the Hammar does nothing but everything else works
LittleTitles Version: 1.5.0
CreativeCore Version: 1.9.9

https://drive.google.com/file/d/1IYVWNU0KwJC_JJQRWlDW6GpLXbt7rxb2/view?usp=sharing

**Comment by CreativeMD** [comment]
Make sure you are using the newest version of LT and CreativeCore (the version ingame is outdated, so only the filename matters). Furthermore tools have been reworked, you have to press 'C' if you want to configure the tool. You can find more information and some tutorials on the wiki: https://github.com/CreativeMD/LittleTiles/wiki

**Comment by win10Device** [comment]
Ok thanks
I'm going to try the one that you released not long ago
