### ISSUE TITLE
Little Tiles no longer compatible with Chisels and Bits

### ISSUE THREAD

**Issue by Tschipp** [CreativeMD/LittleTiles#283]
I recently upgraded to Little Tiles 1.5.0 pre175, and Chisels and Bits support doesn't seem to be working anymore. I can't place pixels into C&B structures or remove them with the hammer. Is it possible that this broke when changing the TileEntity format?

**Comment by CreativeMD** [comment]
Which version of C&B are you using? Is there anything in the logs (maybe send me your log file)?

**Comment by Tschipp** [comment]
I'm using C&B 14.33, which is latest. There's nothing unusual in the log file, but I'll send it anyway. 
[latest.log](https://github.com/CreativeMD/LittleTiles/files/3805457/latest.log)

**Comment by CreativeMD** [comment]
Can you explain your problem a little bit more? Maybe provide some screenshots?

**Comment by Tschipp** [comment]
Sure. I even made a small video (is inside zip, can't directly send mp4's)
[2019-11-04 20-45-08.zip](https://github.com/CreativeMD/LittleTiles/files/3805783/2019-11-04.20-45-08.zip)

**Comment by CreativeMD** [comment]
Can you try out if this version fixes it?
https://www.dropbox.com/s/cyx3ym8nwn8uhoi/LittleTiles_v1.5.0-pre177_mc1.12.2.jar?dl=1

**Comment by Tschipp** [comment]
Sadly not. The hitbox shows up again but it doesn't convert the block. Converting LT-Blocks to C&B blocks works fine though.
[2019-11-04 22-23-57.zip](https://github.com/CreativeMD/LittleTiles/files/3806141/2019-11-04.22-23-57.zip)

**Comment by CreativeMD** [comment]
Fixed and released it! Sorry for the inconvenience. Really hope everything works fine now. New version should be available in a few minutes. Thanks for your help and the time spent!

**Comment by Tschipp** [comment]
Awesome! Thank you for the quick fix! I'm blown away by the speed at which you fix these things! I try to  respond to issues for my mods as soon as I can, but I rarely ever release a bugfix update for in the next day :D

**Comment by CreativeMD** [comment]
It was a rather easy fix. Just messed up one variable name ...
