### ISSUE TITLE
Server crash when animating an advanced door.

### ISSUE THREAD

**Issue by NoxyNixie** [CreativeMD/LittleTiles#284]
We just experienced a server crash: https://paste.dimdev.org/uleyihejic.mccrash

`java.lang.NoSuchMethodError: com.creativemd.littletiles.common.entity.EntityAnimationController.isWaitingForRender()Z`

The structure was this (A WIP where we were trying to figure out multiple doors and parenting): https://pastebin.com/uPdL0R96

**Comment by CreativeMD** [comment]
Released a fix for it! Thanks for reporting this issue!
