### ISSUE TITLE
Configurable recipe hardness

### ISSUE THREAD

**Issue by mopsled** [CreativeMD/LittleTiles#285]
Hello! Love your mod, just getting into it. I tried searching the issues and wiki, but couldn't find a similar question. Please let me know if this has already been covered.

Currently, materials don't seem to keep any of their previous hardness after modification. In the example below, I remove one bit from an obsidian block, and it loses all hardness:

![obsidian-missing-one-bit5](https://user-images.githubusercontent.com/427393/68417550-e7914180-0196-11ea-8859-b70c0794ee94.gif)
(Please excuse the quality, had to fit on GitHub).

This feels a little odd when a big iron vault door can be destroyed in a couple of punches. Is there any way to configure hardness for created recipes? Ideally, I'd love for this could be derived from the materials for balance, or configurable with a tool.

Thank you!

**Comment by mopsled** [comment]
Here is a recipeless example with painting a Colored Block:

![paintbrush-breakable](https://user-images.githubusercontent.com/427393/68487133-daca2780-0242-11ea-9441-b6848b88d430.gif)

Should I be doing this another way that can retain the original hardness?

**Comment by CreativeMD** [comment]
It's planned to improve the mining speed of different materials. Furthermore structures will get the hardness of their "strongest" block. Not sure when I will get to it, but it will definitely be part of 1.5.0.
