### ISSUE TITLE
Feature request: little recipe organization

### ISSUE THREAD

**Issue by technojunkie** [CreativeMD/LittleTiles#288]
Hello,

I apologize if this has been requested already, I didn't find anything in a quick search.

Would it be possible to create an item like a 'recipe book' to holdrecipes so that they don't take up a bunch of inventory space?
My thoughts on how it could work: 
- Use recipe from book as if it were held in hand 
- sneak-right-click to open book and add/remove recipes
- Shift-scroll to flip between recipes

Thank you for your time and for this great mod!

**Comment by CreativeMD** [comment]
I might add a personal recipe book (in the future), but not an item which stores all the recipes, because that would sooner or later exceed the chunk limit too fast. Sorry :(
