### ISSUE TITLE
Rendering glitch with two panes of colored glass

### ISSUE THREAD

**Issue by mopsled** [CreativeMD/LittleTiles#289]
Hello! I've encountered an issue when placing panes of colored glass on top of LittleTiles glass:

https://imgur.com/a/Oh16oFe

As I walk back and forth above, some of the colored panes seem to pop in and out of transparency. More generally this can be replicated with two colored panes of glass on one cube:

https://imgur.com/a/477fn7p

When one pane is added, there are no issues, but two panes show the same problem.

I'm using v1.5.0pre177 w/ Omnifactory 1.2.1, and Optifine is not installed.

**Comment by CreativeMD** [comment]
Those are limitations of the rendering engine. There is no way to fix it. You should avoid multiple layers of different colored glass or make it thicker. I recently attempted to fix it, but just realized that there is no way to do so. Sorry :(

**Comment by mopsled** [comment]
Thank you for the response @CreativeMD. For anyone else encountering the same issue, putting a solid plane between the transparent tiles fixes the issue:

![glass-solid-plane](https://user-images.githubusercontent.com/427393/68966283-01a5d200-07de-11ea-8c68-64c499f87daf.png)

[GIF of the workaround here](https://imgur.com/a/p5llaob).

**Comment by CreativeMD** [comment]
good idea!
