### ISSUE TITLE
Almost Instant crash

### ISSUE THREAD

**Issue by Kittenlover647** [CreativeMD/LittleTiles#290]
I don't know exactly if this mod is causing this problem but once I add this mod to my mods folder minecraft almost instantly crashes when trying to play with forge! This is strange because every other mod works fine..

I feel like this problem has been adressed before and I am just being stupid but I need to understand what is happening at least.

**Comment by CreativeMD** [comment]
Have you installed creativecore as well?

**Comment by KeykeeperMC** [comment]
I've downloaded CreativeCore but it still crashes.

**Comment by CreativeMD** [comment]
Can you send me the crash-report?

**Comment by CreativeMD** [comment]
I will close this issue for now. Just make sure to install the newest version of CreativeCore and LittleTiles (including OnlinePictureFrame if that one is installed as well).
