### ISSUE TITLE
Using doors in multiplayer creates ghost entities for other players

### ISSUE THREAD

**Issue by sleurk** [CreativeMD/LittleTiles#292]
When on a multiplayer server, if a player opens a door, it will appear to work fine for them, but other players seem to have many ghost entities of the door spawning only on their clients in various positions. I've only tried this with the axis doors but it may happen with others as well.

**Comment by CreativeMD** [comment]
Somebody else has reported a similar issue however we could not reproduce it again. Can you provide some screenshots? If possible a short video showcasing the issue?

**Comment by sleurk** [comment]
https://youtu.be/DiwscPGBQ-w

Apparently I was wrong about it happening only on other player's clients - when trying to record this video, I could only get it to happen when I opened the door myself, and when my friend opened it for me repeatedly this wouldn't happen. Not sure why. 

This was in the pack "Dungeons, Dragons, and Space Shuttles" but I was also experiencing the same problem in the pack "Builder's Paradise."

**Comment by CreativeMD** [comment]
Can you try out the newest versions of CreativeCore and LittleTiles?

**Comment by CreativeMD** [comment]
The newest version of LittleTiles should fix your issue. I would be very happy if you could test it.

**Comment by CreativeMD** [comment]
After days of trail and error I finally fixed several synchronization issues. The newest version should work without these kind of issues.
