### ISSUE TITLE
Crashes as soon as I click play.

### ISSUE THREAD

**Issue by SkittyChips** [CreativeMD/LittleTiles#293]
**Yes** I'm using the official Twitch client.
**Yes** I'm using CreativeCore which was installed automatically.
**Yes** I'm on version 1.12.2
**Yes** I'm on mac.
**Yes** I just downloaded this a couple minutes ago.
**No** I don't know why non of the image mods work.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.ajar)
  CorePlugin (ForgeEndertech-1.12.2-4.4.8.0-build.0249.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.9.39_mc1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre180_mc1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 11/24/19 9:38 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from LittleTiles (littletiles)
Caused by: java.lang.NoClassDefFoundError: com/creativemd/creativecore/common/utils/sorting/BlockSelector$BlockSelectorClass
	at com.creativemd.littletiles.common.utils.ingredients.rules.IngredientRules.loadRules(IngredientRules.java:55)
	at com.creativemd.littletiles.LittleTiles.PreInit(LittleTiles.java:248)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.common.utils.sorting.BlockSelector$BlockSelectorClass
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 42 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.1
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 564619640 bytes (538 MB) / 1612709888 bytes (1538 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 3 total; -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2811 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version           | Source                                            | Signature                                |
	|:----- |:-------------------------------------------- |:----------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                                    | 1.12.2            | minecraft.jar                                     | None                                     |
	| LCH   | mcp                                          | 9.42              | minecraft.jar                                     | None                                     |
	| LCH   | FML                                          | 8.0.99.99         | forge-1.12.2-14.23.5.2811.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                                        | 14.23.5.2811      | forge-1.12.2-14.23.5.2811.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy                            | 1.0.0             | minecraft.jar                                     | None                                     |
	| LCH   | littletilescore                              | 1.0.0             | minecraft.jar                                     | None                                     |
	| LCH   | com.elytradev.movingworld.common.asm.coremod |                   | minecraft.jar                                     | None                                     |
	| LCH   | foamfixcore                                  | 7.7.4             | minecraft.jar                                     | None                                     |
	| LCH   | obfuscate                                    | 0.2.6             | minecraft.jar                                     | None                                     |
	| LCH   | architecturecraft                            | @VERSION@         | architecturecraft-1.12-3.80.jar                   | None                                     |
	| LCH   | bibliocraft                                  | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
	| LCH   | buildinggadgets                              | 2.6.1             | BuildingGadgets-2.6.1.jar                         | None                                     |
	| LCH   | cameraobscura                                | 0.0.1             | CameraObscura-1.0.3.jar                           | None                                     |
	| LCH   | ctm                                          | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                         | None                                     |
	| LCH   | chisel                                       | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar                      | None                                     |
	| LCH   | chiselsandbits                               | 14.30             | chiselsandbits-14.30.jar                          | None                                     |
	| LCH   | cjcm                                         | 1.0               | cjcm-1.0.jar                                      | None                                     |
	| LCH   | creativecore                                 | 1.9.9             | CreativeCore_v1.9.39_mc1.12.2.jar                 | None                                     |
	| LCH   | movingworld                                  | 1.12-6.342        | movingworld-1.12-6.342-full.jar                   | None                                     |
	| LCH   | davincisvessels                              | @DVESSELSVER@     | davincisvessels-1.12-6.340-full.jar               | None                                     |
	| LCH   | dimdoors                                     | 3.0.9+287         | DimensionalDoors-3.0.9-287.jar                    | None                                     |
	| LCH   | shadowmc                                     | 3.8.0             | ShadowMC-1.12-3.8.0.jar                           | None                                     |
	| LCH   | extrarails                                   | 1.3.0             | ExtraRails-1.12-1.3.0.jar                         | None                                     |
	| LCH   | fenceoverhaul                                | 1.3.4             | FenceOverhaul-1.3.4.jar                           | None                                     |
	| LCH   | foamfix                                      | 0.10.3-1.12.2     | foamfix-0.10.3-1.12.2.jar                         | None                                     |
	| LCH   | forgeendertech                               | 1.12.2-4.4.8.0    | ForgeEndertech-1.12.2-4.4.8.0-build.0249.jar      | None                                     |
	| LCH   | forgelin                                     | 1.8.4             | Forgelin-1.8.4.jar                                | None                                     |
	| LCH   | cfm                                          | 6.2.0             | furniture-6.2.0-1.12.2.jar                        | None                                     |
	| LCH   | globe                                        | 0.0.1             | Globe-1.12.2-0.0.1.jar                            | None                                     |
	| LCH   | waila                                        | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	| LCH   | industrialrenewal                            | 0.8.0             | IndustrialRenewal_1.12.2-0.8.0.jar                | None                                     |
	| LCH   | jei                                          | 4.14.4.264        | jei_1.12.2-4.14.4.264.jar                         | None                                     |
	| LCH   | journeymap                                   | 1.12.2-5.5.3      | journeymap-1.12.2-5.5.3.jar                       | None                                     |
	| LCE   | littletiles                                  | 1.5.0             | LittleTiles_v1.5.0-pre180_mc1.12.2.jar            | None                                     |
	| LC    | malisiscore                                  | 1.12.2-6.4.0      | malisiscore-1.12.2-6.4.0.jar                      | None                                     |
	| LC    | malisisdoors                                 | 1.12.2-7.3.0      | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
	| LC    | radixcore                                    | 1.12.x-2.2.1      | RadixCore-1.12.x-2.2.1-universal.jar              | None                                     |
	| LC    | mca                                          | 1.12.2-5.3.1      | MCA-1.12.x-5.3.1-universal.jar                    | None                                     |
	| LC    | mcpaint                                      | 1.2.4             | mcpaint-1.2.4.jar                                 | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LC    | mcwbridges                                   | 1.0               | mcw-bridges-1.0.2-mc1.12.2.jar                    | None                                     |
	| LC    | placeableitems                               | 3.3               | placeableitems-3.3.jar                            | None                                     |
	| LC    | ptrmodellib                                  | 1.0.3             | PTRLib-1.0.3.jar                                  | None                                     |
	| LC    | rcroads                                      | 0.3.0             | RC Roads 0.3.0.jar                                | None                                     |
	| LC    | signals                                      | 1.4.1-30          | Signals-1.12.2-1.4.1-30-universal.jar             | None                                     |
	| LC    | signpost                                     | 1.07.2            | signpost-1.12-1.07.2.jar                          | None                                     |
	| LC    | stupidthings                                 | 1.1.5             | Stupid Things-1.12.X-1.1.5.jar                    | None                                     |
	| LC    | trackapi                                     | 1.2               | TrackAPI-1.2.jar                                  | None                                     |
	| LC    | uteamcore                                    | 2.2.4.133         | u_team_core-1.12.2-2.2.4.133.jar                  | None                                     |
	| LC    | vehicle                                      | 0.35.0            | vehicle-mod-0.35.0-1.12.2.jar                     | None                                     |
	| LC    | worldedit                                    | 6.1.10-SNAPSHOT   | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
CorePlugin (ForgeEndertech-1.12.2-4.4.8.0-build.0249.jar)
  
ForgelinPlugin (Forgelin-1.8.4.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CreativePatchingLoader (CreativeCore_v1.9.39_mc1.12.2.jar)
  
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
LittlePatchingLoader (LittleTiles_v1.5.0-pre180_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-2.2.8' Renderer: 'AMD Radeon Pro 555X OpenGL Engine'

**Comment by CreativeMD** [comment]
**No** the newest creative core version is not installed :stuck_out_tongue:
Just update and it should work just fine.

**Comment by SkittyChips** [comment]
Thanks! I appreciate it. Finally I can add some images to my world. :)

**Comment by TomyLobo** [comment]
@SkittyChips Hi, if I create a custom profile and add LittleTiles, I get the correct CreativeCore version:
![image](https://user-images.githubusercontent.com/963797/69725507-a26d8900-111e-11ea-9629-85c0f911f65f.png)
If you don't mind, can you tell me how you installed LittleTiles? You mentioned you downloaded "this" and it automatically installed CreativeCore.
Does "this" happen to be a modpack of some sort?
