### ISSUE TITLE
Instant crash when loading

### ISSUE THREAD

**Issue by jackieenr** [CreativeMD/LittleTiles#295]
My game will load, get to the point where it tries to load the mod, then crashes witha "fatal error", i checked and i have the most recent update of the mod and of creative core, crash report is below:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.9.62_mc1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre180_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 11/26/19 11:22 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from LittleTiles (littletiles)
Caused by: java.lang.NoClassDefFoundError: com/creativemd/creativecore/common/utils/sorting/BlockSelector$BlockSelectorClass
	at com.creativemd.littletiles.common.utils.ingredients.rules.IngredientRules.loadRules(IngredientRules.java:55)
	at com.creativemd.littletiles.LittleTiles.PreInit(LittleTiles.java:248)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.common.utils.sorting.BlockSelector$BlockSelectorClass
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.11.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1496817776 bytes (1427 MB) / 3892314112 bytes (3712 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 7 total; -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 72 mods loaded, 72 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                      | Version           | Source                                             | Signature                                |
	|:----- |:----------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft               | 1.12.2            | minecraft.jar                                      | None                                     |
	| LCH   | mcp                     | 9.42              | minecraft.jar                                      | None                                     |
	| LCH   | FML                     | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCH   | forge                   | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCH   | creativecoredummy       | 1.0.0             | minecraft.jar                                      | None                                     |
	| LCH   | littletilescore         | 1.0.0             | minecraft.jar                                      | None                                     |
	| LCH   | openmodscore            | 0.12.2            | minecraft.jar                                      | None                                     |
	| LCH   | biomesoplenty           | 7.0.1.2441        | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar      | None                                     |
	| LCH   | baubles                 | 1.5.2             | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCH   | botania                 | r1.10-361         | Botania+r1.10-3615.jar                             | None                                     |
	| LCH   | redstoneflux            | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | cofhcore                | 4.6.3             | CoFHCore-1.12.2-4.6.3.27-universal.jar             | None                                     |
	| LCH   | craftstudioapi          | 1.0.0             | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCH   | mantle                  | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCH   | natura                  | 1.12.2-4.3.2.69   | natura-1.12.2-4.3.2.69.jar                         | None                                     |
	| LCH   | harvestcraft            | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zf5.jar                   | None                                     |
	| LCH   | animania                | 1.7.3             | animania-1.12.2-1.7.35.jar                         | None                                     |
	| LCH   | backpack                | 3.0.2             | backpack-3.0.2-1.12.25.jar                         | None                                     |
	| LCH   | bno                     | 1.12.2-1.0.4.0    | BasicNetherOres-1.12.2-1.0.4.05.jar                | None                                     |
	| LCH   | forgelin                | 1.8.4             | Forgelin-1.8.4.jar                                 | None                                     |
	| LCH   | betterportals           | 0.3.7.1           | betterportals-0.3.7.1.jar                          | None                                     |
	| LCH   | bibliocraft             | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| LCH   | bookshelf               | 2.3.585           | Bookshelf-1.12.2-2.3.5855.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | buildcraftlib           | 7.99.24.3         | buildcraft-all-7.99.24.35.jar                      | None                                     |
	| LCH   | buildcraftcore          | 7.99.24.3         | buildcraft-all-7.99.24.35.jar                      | None                                     |
	| LCH   | buildcraftbuilders      | 7.99.24.3         | buildcraft-all-7.99.24.35.jar                      | None                                     |
	| LCH   | buildcrafttransport     | 7.99.24.3         | buildcraft-all-7.99.24.35.jar                      | None                                     |
	| LCH   | buildcraftsilicon       | 7.99.24.3         | buildcraft-all-7.99.24.35.jar                      | None                                     |
	| LCH   | buildcraftcompat        | 7.99.24.3         | buildcraft-all-7.99.24.35.jar                      | None                                     |
	| LCH   | buildcraftenergy        | 7.99.24.3         | buildcraft-all-7.99.24.35.jar                      | None                                     |
	| LCH   | buildcraftfactory       | 7.99.24.3         | buildcraft-all-7.99.24.35.jar                      | None                                     |
	| LCH   | buildcraftrobotics      | 7.99.24.3         | buildcraft-all-7.99.24.35.jar                      | None                                     |
	| LCH   | car                     | 1.2.10            | car-1.2.10.jar                                     | None                                     |
	| LCH   | ctm                     | MC1.12.2-1.0.0.29 | CTM-MC1.12.2-1.0.0.29.jar                          | None                                     |
	| LCH   | chisel                  | MC1.12.2-1.0.1.44 | Chisel-MC1.12.2-1.0.1.445.jar                      | None                                     |
	| LCH   | chiselsandbits          | 14.33             | chiselsandbits-14.33.jar                           | None                                     |
	| LCH   | codechickenlib          | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | cofhworld               | 1.3.1             | CoFHWorld-1.12.2-1.3.1.7-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | cyclopscore             | 0.11.1            | CyclopsCore-1.12.2-0.11.1.jar                      | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCH   | colossalchests          | 1.6.8             | ColossalChests-1.12.2-1.6.8.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCH   | creativecore            | 1.9.9             | CreativeCore_v1.9.62_mc1.12.2.jar                  | None                                     |
	| LCH   | cutehamstermod          | 1.1               | cutehamstermod-1.1.jar                             | ac38a3286ab9f4777b0023f0f6280caa9369d575 |
	| LCH   | ptrmodellib             | 1.0.4             | PTRLib-1.0.4.jar                                   | None                                     |
	| LCH   | props                   | 2.6.3             | Decocraft-2.6.3_1.12.2.jar                         | None                                     |
	| LCH   | cdm                     | 0.2.1             | device-mod-0.2.1-1.12.2.jar                        | None                                     |
	| LCH   | dungeontactics          | DT-0.16.6         | DungeonTactics-1.12.2-0.16.65.jar                  | None                                     |
	| LCH   | tconstruct              | 1.12.2-2.13.0.171 | TConstruct-1.12.2-2.13.0.1715.jar                  | None                                     |
	| LCH   | extrautils2             | 1.0               | extrautils2-1.12-1.9.95.jar                        | None                                     |
	| LCH   | fairylights             | 2.1.2             | fairylights-2.1.2-1.12.x.jar                       | None                                     |
	| LCH   | forgemultipartcbe       | 2.6.2.83          | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | microblockcbe           | 2.6.2.83          | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
	| LCH   | minecraftmultipartcbe   | 2.6.2.83          | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
	| LCH   | cfm                     | 6.3.1             | furniture-6.3.1-1.12.25.jar                        | None                                     |
	| LCH   | teslacorelib            | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | industrialforegoing     | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.12.13-237.jar         | None                                     |
	| LCE   | littletiles             | 1.5.0             | LittleTiles_v1.5.0-pre180_mc1.12.2.jar             | None                                     |
	| LC    | mrtjpcore               | 2.1.4.43          | MrTJPCore-1.12.2-2.1.4.43-universal.jar            | None                                     |
	| LC    | openmods                | 0.12.2            | OpenModsLib-1.12.2-0.12.2.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LC    | openblocks              | 1.8.1             | OpenBlocks-1.12.2-1.8.1.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LC    | personalcars            | 1.4               | PersonalCars-1.4.jar                               | None                                     |
	| LC    | placeableitems          | 3.3               | placeableitems-3.3.jar                             | None                                     |
	| LC    | projectred-core         | 4.9.4.120         | ProjectRed-1.12.2-4.9.4.120-Base.jar               | None                                     |
	| LC    | projectred-illumination | 4.9.4.120         | ProjectRed-1.12.2-4.9.4.120-lighting.jar           | None                                     |
	| LC    | projectred-exploration  | 4.9.4.120         | ProjectRed-1.12.2-4.9.4.120-world.jar              | None                                     |
	| LC    | railcraft               | 12.0.0            | railcraft-12.0.05.jar                              | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LC    | sb                      | 1.0               | sb-3.jar                                           | None                                     |
	| LC    | thermalfoundation       | 2.6.3             | ThermalFoundation-1.12.2-2.6.3.27-universal5.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalexpansion        | 5.5.4             | ThermalExpansion-1.12.2-5.5.4.43-universal5.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermaldynamics         | 2.5.5             | ThermalDynamics-1.12.2-2.5.5.21-universal5.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | tropicraft              | 7.1.9.115         | tropicraft-MC1.12.2-7.1.9.115.jar                  | None                                     |
	| LC    | vehicle                 | 0.1.0             | vehicle-mod-0.1.0-1.12.2.jar                       | None                                     |
	| LC    | teslacorelib_registries | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                   | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
CreativePatchingLoader (CreativeCore_v1.9.62_mc1.12.2.jar)
  
LittlePatchingLoader (LittleTiles_v1.5.0-pre180_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.0.52 310.90.10.05b46' Renderer: 'NVIDIA GeForce 9400M OpenGL Engine'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

**Comment by kirokadura** [comment]
You're using an outdated version of CreativeCore, please update.

**Comment by jackieenr** [comment]
> You're using an outdated version of CreativeCore, please update.

which would i use then?? that’s the most updated one i found and it said it was updated 4 days ago? any link?

**Comment by kirokadura** [comment]
This is the newest one, from 4 days ago

https://www.curseforge.com/minecraft/mc-mods/creativecore/files/2831308

The one you're currently using is from August 8th.

**Comment by CreativeMD** [comment]
I will close this issue for now. Just make sure to use the newest CreativeCore and LittleTiles version.
