### ISSUE TITLE
Mods are installed but wont show up in game.

### ISSUE THREAD

**Issue by JygoFx** [CreativeMD/LittleTiles#296]
I just added littletiles 1.7.10 into my mods folder for my modded single player. Everything is installed including creativecore. And nothing shows up for littletiles?

**Comment by CreativeMD** [comment]
Can you find it in the mods menu?

**Comment by CreativeMD** [comment]
I will close this issue for now as I'm very sure it's an issue on your end. If you need any further help just let me know.
