### ISSUE TITLE
Crash when opening tool GUIs

### ISSUE THREAD

**Issue by RangerNorth** [CreativeMD/LittleTiles#297]
Im using the newest beta as of 11/28/19. There is a 50/50 chance when I press the open GUI button on my keyboard to select my tool specs it will load the RGB bars and nothing else. Then the game freezes, or it will completely crash on button press. It Does ocasionally work and I can use the tool as intended but Im thinking this has to be a bug.

**Comment by CreativeMD** [comment]
Can you send me the crash-report?

**Comment by RangerNorth** [comment]
[crash-2019-11-28_10.33.28-client.txt](https://github.com/CreativeMD/LittleTiles/files/3902757/crash-2019-11-28_10.33.28-client.txt)

**Comment by RangerNorth** [comment]
Here is another more recent one. 

[crash-2019-11-28_12.17.21-client.txt](https://github.com/CreativeMD/LittleTiles/files/3902768/crash-2019-11-28_12.17.21-client.txt)

**Comment by CreativeMD** [comment]
Can you send me your log file as well? Something happens before the crash.

**Comment by RangerNorth** [comment]
[latest.zip](https://github.com/CreativeMD/LittleTiles/files/3905089/latest.zip)

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming pre-release.

**Comment by CreativeMD** [comment]
New version has been released.
