### ISSUE TITLE
Using doors in multiplayer only render and work for the person who initially activated the door.

### ISSUE THREAD

**Issue by GlassCrab** [CreativeMD/LittleTiles#298]
When I place a door down, everyone can see it and it's solid for them, but once anyone activates it for the first time, only that person can see and stand on it and such, its completely invisible and has no hitbox, the only person who can destroy the animation is the person who can still see the door. It seems to apply to both doors that have stay animated checked and not.
The doors also do not interact with things like item entities, and the hitbox is only visible to the person who activated the door. I can send a video if needed

**Comment by CreativeMD** [comment]
Which version are you using?

**Comment by GlassCrab** [comment]
Version 1.5.0-pre173 for 1.12.2

**Comment by CreativeMD** [comment]
Please update to the newest version of CreativeCore and LittleTiles. This should hopefully fix your issue.
