### ISSUE TITLE
No plane mode for chisel?

### ISSUE THREAD

**Issue by bigorados** [CreativeMD/LittleTiles#299]
the saw can "extrude" block sections but, if I want to do a simple operations such as make circle and extrude it into a cilinder the chisel doesn't have a plane mode, but the hammer does

**Comment by kirokadura** [comment]
There's a cilinder option in the chisel menu. Furthermore, you can use Mark Mode (Default to key M) to control the thickness with precision.

**Comment by CreativeMD** [comment]
I will close the issue for now, since there is no issue here.
