### ISSUE TITLE
Loading a world with LittleTiles blocks doesn't allways load all of them properly.

### ISSUE THREAD

**Issue by Encryption767** [CreativeMD/LittleTiles#3]
Sometimes when a world with many LittleTiles is loaded, some of them will not appear. The missing tiles seem to be random and a reload of the world will sometimes fix it but not always as other tiles which was loaded might not be loaded when entering the world again.

**Comment by CreativeMD** [comment]
Yes i know this bug, but it is really complicated to fix it, i will try to do my best and fix it soon.

**Comment by CreativeMD** [comment]
Already has been fixed a long time ago.
