### ISSUE TITLE
Redstone door interaction

### ISSUE THREAD

**Issue by AstralDestiny** [CreativeMD/LittleTiles#30]
Allow Redstone to interact with doors. Self Explanatory.

**Comment by Dushess** [comment]
Also another suggestion: Sliding single/double doors.

**Comment by CreativeMD** [comment]
I'm closing this issue, because it's not an issue. I have added this idea to my todo list already. It will be part of the v1.5.0 Update. If you like to hear more about it you can join my discord server.
