### ISSUE TITLE
Game crash when open Little Chisel

### ISSUE THREAD

**Issue by M0faZza** [CreativeMD/LittleTiles#300]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.9.74_mc1.12.2.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  LogisticsPipesCoreLoader (Logistics-Pipes-Mod-1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre177_mc1.12.2.jar)
  OTGCorePlugin (OTG-Core.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 12/1/19 7:38 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at com.creativemd.littletiles.client.gui.SubGuiChisel.saveConfiguration(SubGuiChisel.java:109)
	at com.creativemd.littletiles.client.gui.configure.SubGuiConfigure.onClosed(SubGuiConfigure.java:35)
	at com.creativemd.creativecore.common.gui.container.SubGui.closeLayer(SubGui.java:79)
	at com.creativemd.creativecore.common.gui.container.SubGui.closeLayer(SubGui.java:75)
	at com.creativemd.creativecore.common.gui.container.SubGui.closeGui(SubGui.java:102)
	at com.creativemd.creativecore.common.gui.container.SubGui.onKeyPressed(SubGui.java:166)
	at com.creativemd.littletiles.client.gui.configure.SubGuiConfigure.onKeyPressed(SubGuiConfigure.java:22)
	at com.creativemd.creativecore.common.gui.mc.GuiContainerSub.func_73869_a(GuiContainerSub.java:215)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
	at com.creativemd.creativecore.common.gui.mc.GuiContainerSub.func_146269_k(GuiContainerSub.java:226)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.client.gui.SubGuiChisel.saveConfiguration(SubGuiChisel.java:109)
	at com.creativemd.littletiles.client.gui.configure.SubGuiConfigure.onClosed(SubGuiConfigure.java:35)
	at com.creativemd.creativecore.common.gui.container.SubGui.closeLayer(SubGui.java:79)
	at com.creativemd.creativecore.common.gui.container.SubGui.closeLayer(SubGui.java:75)
	at com.creativemd.creativecore.common.gui.container.SubGui.closeGui(SubGui.java:102)
	at com.creativemd.creativecore.common.gui.container.SubGui.onKeyPressed(SubGui.java:166)
	at com.creativemd.littletiles.client.gui.configure.SubGuiConfigure.onKeyPressed(SubGuiConfigure.java:22)
	at com.creativemd.creativecore.common.gui.mc.GuiContainerSub.func_73869_a(GuiContainerSub.java:215)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
	at com.creativemd.creativecore.common.gui.mc.GuiContainerSub.func_146269_k(GuiContainerSub.java:226)

-- Affected screen --
Details:
	Screen name: com.creativemd.creativecore.common.gui.mc.GuiContainerSub

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Just_Lisa'/52, l='MpServer', x=-6535.06, y=170.00, z=-1089.96]]
	Chunk stats: MultiplayerChunkCache: 3481, 3481
	Level seed: 0
	Level generator: ID 07 - OTG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-58,92,86), Chunk: (at 6,5,6 in -4,5; contains blocks -64,0,80 to -49,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 42522 game time, 23444 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 35 total; [EntityBat['Bat'/256, l='MpServer', x=-6502.53, y=58.38, z=-1099.11], EntitySquid['Squid'/259, l='MpServer', x=-6574.30, y=85.86, z=-1043.35], EntityRoosterWyandotte['Wyandotte Rooster'/260, l='MpServer', x=-6571.73, y=168.00, z=-1047.42], EntityBat['Bat'/261, l='MpServer', x=-6504.52, y=57.03, z=-1100.75], EntityRoosterLeghorn['Leghorn Rooster'/262, l='MpServer', x=-6480.33, y=20.00, z=-1125.49], EntitySquid['Squid'/263, l='MpServer', x=-6508.60, y=87.19, z=-1102.40], EntityRoosterLeghorn['Leghorn Rooster'/264, l='MpServer', x=-6552.51, y=69.00, z=-1146.34], EntityBat['Bat'/265, l='MpServer', x=-6565.59, y=62.10, z=-1124.75], EntityBat['Bat'/268, l='MpServer', x=-6568.40, y=80.10, z=-1143.16], EntityBat['Bat'/204, l='MpServer', x=-6535.43, y=75.07, z=-1108.34], EntityBat['Bat'/205, l='MpServer', x=-6544.18, y=78.04, z=-1095.55], EntityMinecartChest['Minecart with Chest'/207, l='MpServer', x=-6593.50, y=65.06, z=-1156.50], EntityBat['Bat'/272, l='MpServer', x=-6541.75, y=69.10, z=-1135.13], EntityBat['Bat'/273, l='MpServer', x=-6541.39, y=70.10, z=-1131.71], EntityMinecartChest['Minecart with Chest'/274, l='MpServer', x=-6551.50, y=67.06, z=-1119.50], EntityBat['Bat'/275, l='MpServer', x=-6534.45, y=66.57, z=-1145.51], EntitySquid['Squid'/213, l='MpServer', x=-6579.89, y=86.00, z=-1047.16], EntitySquid['Squid'/214, l='MpServer', x=-6572.16, y=86.00, z=-1043.47], EntitySquid['Squid'/215, l='MpServer', x=-6573.95, y=86.31, z=-1044.99], EntityRoosterLeghorn['Leghorn Rooster'/279, l='MpServer', x=-6555.50, y=68.00, z=-1121.50], EntitySquid['Squid'/216, l='MpServer', x=-6576.60, y=84.13, z=-1042.40], EntityBat['Bat'/280, l='MpServer', x=-6552.25, y=70.10, z=-1134.25], EntityRoosterWyandotte['Wyandotte Rooster'/217, l='MpServer', x=-6576.82, y=168.00, z=-1046.41], EntityMinecartChest['Minecart with Chest'/220, l='MpServer', x=-6582.50, y=62.06, z=-1125.50], EntityBat['Bat'/221, l='MpServer', x=-6580.50, y=73.60, z=-1128.25], EntityRamJacob['Jacob Ram'/223, l='MpServer', x=-6580.07, y=173.00, z=-1089.97], EntityEweJacob['Jacob Ewe'/224, l='MpServer', x=-6577.01, y=170.00, z=-1097.19], EntityPlayerSP['Just_Lisa'/52, l='MpServer', x=-6535.06, y=170.00, z=-1089.96], EntityEweFriesian['Friesian Ewe'/237, l='MpServer', x=-6482.89, y=168.00, z=-1085.07], MagicEntity['unknown'/-31415, l='MpServer', x=-6533.58, y=170.89, z=-1088.84], EntityBat['Bat'/250, l='MpServer', x=-6559.99, y=77.04, z=-1079.95], EntityBat['Bat'/251, l='MpServer', x=-6538.15, y=77.05, z=-1096.08], EntityBat['Bat'/253, l='MpServer', x=-6546.10, y=79.75, z=-1095.60], EntityBat['Bat'/254, l='MpServer', x=-6543.93, y=56.10, z=-1055.60], EntityEweFriesian['Friesian Ewe'/255, l='MpServer', x=-6559.80, y=153.00, z=-1035.15]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3553972752 bytes (3389 MB) / 7952400384 bytes (7584 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2846 Optifine OptiFine_1.12.2_HD_U_F4 92 mods loaded, 92 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                        | Version           | Source                                             | Signature                                |
	|:------ |:------------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                 | 1.12.2            | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                       | 9.42              | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                       | 8.0.99.99         | forge-1.12.2-14.23.5.2846.jar                      | None                                     |
	| LCHIJA | forge                     | 14.23.5.2846      | forge-1.12.2-14.23.5.2846.jar                      | None                                     |
	| LCHIJA | creativecoredummy         | 1.0.0             | minecraft.jar                                      | None                                     |
	| LCHIJA | littletilescore           | 1.0.0             | minecraft.jar                                      | None                                     |
	| LCHIJA | otgcore                   | 1.12.2 - v8_r8    | minecraft.jar                                      | None                                     |
	| LCHIJA | openmodscore              | 0.12.2            | minecraft.jar                                      | None                                     |
	| LCHIJA | voxelmap                  | 1.9.10            | VoxelMap-Mod-1.12.2.jar                            | None                                     |
	| LCHIJA | biomesoplenty             | 7.0.1.2419        | BiomesOPlenty-1.12.2-7.0.1.2419-universal.jar      | None                                     |
	| LCHIJA | redstoneflux              | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore                  | 4.6.3             | CoFHCore-1.12.2-4.6.3.27-universal.jar             | None                                     |
	| LCHIJA | craftstudioapi            | 1.0.0             | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCHIJA | openterraingenerator      | v8_r8             | OpenTerrainGenerator-1.12.2-v8.jar                 | None                                     |
	| LCHIJA | animania                  | 1.6.2             | animania-1.12.2-1.6.2.jar                          | None                                     |
	| LCHIJA | applecore                 | 3.2.0             | AppleCore-mc1.12.2-3.2.0.jar                       | None                                     |
	| LCHIJA | ctm                       | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                          | None                                     |
	| LCHIJA | appliedenergistics2       | rv6-stable-6      | appliedenergistics2-rv6-stable-6.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | bno                       | 1.12.2-1.0.4.0    | BasicNetherOres-1.12.2-1.0.4.0.jar                 | None                                     |
	| LCHIJA | betterbuilderswands       | 0.11.1            | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar    | None                                     |
	| LCHIJA | bluepower                 | 0.3.148           | BluePower_1.12.2_0.3.148_universal.jar             | None                                     |
	| LCHIJA | buildcraftlib             | 7.99.24.1         | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| LCHIJA | buildcraftcore            | 7.99.24.1         | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| LCHIJA | buildcraftbuilders        | 7.99.24.1         | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| LCHIJA | buildcrafttransport       | 7.99.24.1         | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| LCHIJA | buildcraftsilicon         | 7.99.24.1         | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| LCHIJA | buildcraftcompat          | 7.99.24.1         | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| LCHIJA | buildcraftenergy          | 7.99.24.1         | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| LCHIJA | buildcraftfactory         | 7.99.24.1         | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| LCHIJA | buildcraftrobotics        | 7.99.24.1         | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| LCHIJA | cave_expansion            | 1.5.0             | CaveExpansionV1.5.jar                              | None                                     |
	| LCHIJA | codechickenlib            | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chickenchunks             | 2.4.2.74          | ChickenChunks-1.12.2-2.4.2.74-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chiselsandbits            | 14.22             | Chisels-and-Bits-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | cofhworld                 | 1.3.1             | CoFHWorld-1.12.2-1.3.1.7-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | computercraft             | 1.80pr1           | ComputerCraft-Mod-1.12.2.jar                       | None                                     |
	| LCHIJA | creativecore              | 1.9.9             | CreativeCore_v1.9.74_mc1.12.2.jar                  | None                                     |
	| LCHIJA | criogonals_zombies_mod    | 1.0.0             | criogonalszombiesmod-1.1.jar                       | None                                     |
	| LCHIJA | custommainmenu            | 2.0.9             | CustomMainMenu-MC1.12.2-2.0.9.jar                  | None                                     |
	| LCHIJA | jei                       | 4.15.0.289        | jei_1.12.2-4.15.0.289.jar                          | None                                     |
	| LCHIJA | cyclicmagic               | 1.19.18           | Cyclic-1.12.2-1.19.18.jar                          | None                                     |
	| LCHIJA | enchdesc                  | 1.1.15            | EnchantmentDescriptions-1.12.2-1.1.15.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | enderstorage              | 2.4.5.135         | Ender-Storage-Mod-1.12.2.jar                       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | projecte                  | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1.jar                        | None                                     |
	| LCHIJA | refinedstorage            | 1.6.14            | refinedstorage-1.6.14.jar                          | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | eqs                       | 1.0.3             | EquivalentStorage-1.0.3.jar                        | None                                     |
	| LCHIJA | farfromhome               | 1.0               | FFH_FULL-1.12.2-2.1.jar                            | None                                     |
	| LCHIJA | followingvillagers        | 1.0.1             | Following-Villagers-Mod-1.12.2.jar                 | None                                     |
	| LCHIJA | forgelin                  | 1.8.2             | Forgelin-1.8.2.jar                                 | None                                     |
	| LCHIJA | forgemultipartcbe         | 2.6.2.83          | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe             | 2.6.2.83          | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
	| LCHIJA | minecraftmultipartcbe     | 2.6.2.83          | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
	| LCHIJA | ftblib                    | 5.4.3.147         | FTBLib-5.4.3.147.jar                               | None                                     |
	| LCHIJA | waila                     | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCHIJA | mrtjpcore                 | 2.1.4.43          | MrTJPCore-1.12.2-2.1.4.43-universal.jar            | None                                     |
	| LCHIJA | projectred-core           | 4.9.4.120         | ProjectRed-Base-1.12.2.jar                         | None                                     |
	| LCHIJA | projectred-exploration    | 4.9.4.120         | ProjectRed-World-1.12.2.jar                        | None                                     |
	| LCHIJA | ic2                       | 2.8.1000          | IC2Classic+1.12-1.5.4.4.jar                        | None                                     |
	| LCHIJA | ic2-classic-spmod         | 0.0.0.0           | IC2Classic+1.12-1.5.4.4.jar                        | None                                     |
	| LCHIJA | trackapi                  | 1.1               | Track-API-1.12.2.jar                               | None                                     |
	| LCHIJA | immersiverailroading      | 1.5.0             | ImmersiveRailroading-1.5.0_1.12-402.jar            | None                                     |
	| LCHIJA | ironchest                 | 1.12.2-7.0.67.844 | Iron-Chests-Mod-1.12.2.jar                         | None                                     |
	| LCHIJA | littletiles               | 1.5.0             | LittleTiles_v1.5.0-pre177_mc1.12.2.jar             | None                                     |
	| LCHIJA | thermalfoundation         | 2.6.2             | ThermalFoundation-1.12.2-2.6.2.26-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalexpansion          | 5.5.3             | ThermalExpansion-1.12.2-5.5.3.41-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | logisticspipes            | 0.10.2.147        | Logistics-Pipes-Mod-1.12.2.jar                     | e0c86912b2f7cc0cc646ad57799574aea43dbd45 |
	| LCHIJA | mantle                    | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCHIJA | mcwbridges                | 1.0               | mcw-bridges-1.0.2-mc1.12.2.jar                     | None                                     |
	| LCHIJA | mycommands                | 1.12.2-01         | MyCommands-Mod-1.12.2.jar                          | None                                     |
	| LCHIJA | openmods                  | 0.12.2            | OpenModsLib-1.12.2-0.12.2.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks                | 1.8.1             | OpenBlocks-1.12.2-1.8.1.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | projectred-compat         | 1.0               | ProjectRed-Compat-1.12.2.jar                       | None                                     |
	| LCHIJA | projectred-integration    | 4.9.4.120         | ProjectRed-Integration-1.12.2.jar                  | None                                     |
	| LCHIJA | projectred-transmission   | 4.9.4.120         | ProjectRed-Integration-1.12.2.jar                  | None                                     |
	| LCHIJA | projectred-fabrication    | 4.9.4.120         | ProjectRed-Fabrication-1.12.2.jar                  | None                                     |
	| LCHIJA | projectred-illumination   | 4.9.4.120         | ProjectRed-Lighting-1.12.2.jar                     | None                                     |
	| LCHIJA | projectred-expansion      | 4.9.4.120         | ProjectRed-Mechanical-1.12.2.jar                   | None                                     |
	| LCHIJA | projectred-relocation     | 4.9.4.120         | ProjectRed-Mechanical-1.12.2.jar                   | None                                     |
	| LCHIJA | projectred-transportation | 4.9.4.120         | ProjectRed-Mechanical-1.12.2.jar                   | None                                     |
	| LCHIJA | ptrmodellib               | 1.0.4             | PTRLib-1.0.4.jar                                   | None                                     |
	| LCHIJA | resourceloader            | 1.5.3             | ResourceLoader-MC1.12.1-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | tconstruct                | 1.12.2-2.12.0.135 | TConstruct-1.12.2-2.12.0.135.jar                   | None                                     |
	| LCHIJA | thermaldynamics           | 2.5.5             | ThermalDynamics-1.12.2-2.5.5.21-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thutcore                  | 5.19.8            | ThutCore-1.12.2.jar                                | None                                     |
	| LCHIJA | thutcore_compat           | 1.0               | ThutCore-1.12.2.jar                                | None                                     |
	| LCHIJA | thuttech                  | 6.1.6             | Thutmoses-Elevators-Mod-1.12.2.jar                 | None                                     |
	| LCHIJA | veinminer                 | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
	| LCHIJA | veinminermodsupport       | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
	| LCHIJA | wawla                     | 2.5.273           | Wawla-1.12.2-2.5.273.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | worldedit                 | 6.1.10-SNAPSHOT   | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar  | None                                     |
	| LCHIJA | yabba                     | 1.1.2.51          | YABBA-Mod-1.12.2.jar                               | None                                     |
	| LCHIJA | snowrealmagic             | 0.3.3             | SnowRealMagic-0.3.3.jar                            | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.9.74_mc1.12.2.jar)
  
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
LogisticsPipesCoreLoader (Logistics-Pipes-Mod-1.12.2.jar)
  logisticspipes.asm.LogisticsClassTransformer
LittlePatchingLoader (LittleTiles_v1.5.0-pre177_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 419.72' Renderer: 'Quadro K620/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2846
	LWJGL: 2.9.4
	OpenGL: Quadro K620/PCIe/SSE2 GL version 4.6.0 NVIDIA 419.72, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F4
	OptiFine Build: 20191023-234904
	Render Distance Chunks: 29
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 419.72
	OpenGlRenderer: Quadro K620/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by CreativeMD** [comment]
This will be fixed in the upcoming pre-release.

**Comment by kirokadura** [comment]
Also seems like you're using an outdated version of LittleTiles.

**Comment by CreativeMD** [comment]
Fix has been released. Please update CreativeCore and LittleTiles.
