### ISSUE TITLE
Incompatible with Optifine?

### ISSUE THREAD

**Issue by RoseaBee** [CreativeMD/LittleTiles#304]
I've had to remove Optifine from my mods whenever i plan on using the mod in the sense that I'm making custom doors, otherwise it crashes whenever I open the GUI on the Little Recipe. Is there a fix where i don't have to take Optifine out?

**Comment by kirokadura** [comment]
Can you tell me versions of LittleTiles, CreativeCore and Optifine you're using? And please provide the crashlog too.

**Comment by RoseaBee** [comment]
As far as I understand, the Optifine is "OptiFine 1.12.2 HD U C9" I'm probably dumb and that isn't it. The LittleTiles and CreativeCore are the latest ones. And I've tried to get a crash report but when I hit "View Log" it's just a blank page.

**Comment by CreativeMD** [comment]
Update Optifine that should fix your issue. If not reopen the issue. You can find the crash-report in your minecraft folder.
