### ISSUE TITLE
In tool configuration menu can't choose blocks

### ISSUE THREAD

**Issue by Smollet777** [CreativeMD/LittleTiles#305]
In tool configuration menu for glow can't choose blocks from last row(in creative mode).
Mod v1.5.0 for mc1.12.2
Screen resolution 1336x768
![image](https://user-images.githubusercontent.com/41921653/70318300-c9b80a80-1830-11ea-967a-a17e44bc3a3e.png)

**Comment by kirokadura** [comment]
Can you tell me the full file name for both CreativeCore and LittleTiles?

**Comment by Smollet777** [comment]
CreativeCore_v1.9.74_mc1.12.2 and LittleTiles_v1.5.0-pre180_mc1.12.2 latest from the forge.
 I've checked. Chisel has this gui element and this behavior also.

**Comment by kirokadura** [comment]
I can't replicate this issue using the same versions and screen resolution. Are you sure you got the mods from Curseforge?

**Comment by Smollet777** [comment]
Absolutely. Ok then. This bug isn't critical. Just annoying.

**Comment by CreativeMD** [comment]
I couldn't reproduce this issue either. Neither with the chisel nor with the grabber. The screenshot you posted also seems to be outdated. (Except if you have set useStencil to false for some reason).
