### ISSUE TITLE
Bits/Tiles disappearing as if they weren't there in the first place.

### ISSUE THREAD

**Issue by PurpleIvaylo** [CreativeMD/LittleTiles#307]
I was trying to make a window with the mod when I realized that the bits disappear every time I came back to add to them.

At first I thought it was because of Secret Rooms mod, (tried placing Ghost Blocks and walking trough after placing bits with the LittleTiles mod) and I came to the conclusion that it wasn't the problem.

I tried looking online trough other's issues and complains, and I saw lots of Optifine problems, so I got shaders off, checked if i had VBOs on and Render Regions off, and yet the bits still disappeared,

I've noticed that it happens whenever I go further away, but not always! At times I go the same distance/place and yet they still remain there.
 
**LittleTiles version: v1.5.0-pre180_mc1.12.2
CreativeCore version: v1.9.74_mc1.12.2
I have optifine(F5) but VBOs are on and Render Regions off.**

**Videos:**  https://www.youtube.com/watch?v=YNhKYFF-J2E&feature=youtu.be
https://www.youtube.com/watch?v=jCiN3VxJ1Jk&feature=youtu.be

**Comment by CreativeMD** [comment]
Can you backup the world and try it without any other mod installed (Optifine should't matter) and so if it still occurs then?

**Comment by PurpleIvaylo** [comment]
Yes I'll try now. Give me a second.

**Comment by PurpleIvaylo** [comment]
I have tested it again, and it seems to be working now, Only LittleTiles and Optifine. I have went further and yet no disappearing blocks.
Works absolutely fine now. Only problem is, which mod/mods interfere with LittleTiles. (the modded version is on a server I have with a friend, on Aternos)

**Video of the test:** https://youtu.be/2n3bkuh_Tk0

**Comment by CreativeMD** [comment]
Is there anything in the log files (either client or server)? If it happens in singleplayer as well you could readd mod by mod (or even multiple ones) and figure out which mod interferes.

**Comment by PurpleIvaylo** [comment]
I looked trough the server's logs, and while the blocks keeps disappearing nothing seems out of the ordinary or different besides the casual **"Can't keep up! Did the system time change, or is the server overloaded? Running 6541ms behind, skipping 130 tick(s)"** that I always get no matter what.

 I will try to see if it happens the same in singleplayer with all the mods, and if so, I'll add one by one and keep you updated if I find a potential problem!

**Comment by CreativeMD** [comment]
Thank you very much! Really hope you can track done the mod (depending on how many mods you have I highly recommend to add more mods at once otherwise it will take ages).

**Comment by PurpleIvaylo** [comment]
After putting all the mods and the same map on singleplayer, **I have came to the conclusion that no mods have interfered with LittleTiles but actually the server that is hosting the multiplayer world is the problem.**
  It could be maybe because of distance/chunks? I really don't have an exact clue to why the server makes the bits disappear, but not all of them.

**Chisels & Bits**, the other mod I also have on the server **seems to have no issues though**. I can go as far as I can and also teleport to waypoints, and **when I come back the blocks would still be there** (rocks on the ground, or the arch of the house are all made with that mod)


**Video of the singleplayer test with all of the mods:**  https://youtu.be/ote2dz5YJf4

**Comment by PurpleIvaylo** [comment]
Oh, now that I remembered, I also want to say that the mod OnlinePictureFrame **I have tried it on the server** has caused a lot of lag and server shutting down, but I'm pretty sure that both LittleTiles and OPF are acting like this because of the server, it's really disappointing though not knowing the reason for it.

**Comment by CreativeMD** [comment]
Can you get the log files of the server?

**Comment by PurpleIvaylo** [comment]
Yes I can, I'll get home in a few hours and I'll open the server and give the logs.

**Comment by PurpleIvaylo** [comment]
Huh, this is strange. I have tried the same again, running the world, everything on the server, using LT and now nothing seemed to have disappeared. For now I suppose the issue is temporary fixed? Though I will definitely make another post with logs too if it occurs again in the future.

**Comment by CreativeMD** [comment]
Ok, I will close this issue for now. Just reopen it once it occurs again.
