### ISSUE TITLE
Door Bug(Multiplayer Only)

### ISSUE THREAD

**Issue by Allinardo** [CreativeMD/LittleTiles#308]
I had no idea how to describe the issue I've been having. Let me be clear, the mod works as intended in single player. It's only in multiplayer that any issues arise, and they always look like this.

https://youtu.be/CncUh23yiiU 

I have both the latest versions of CreativeCore and LittleTiles for 1.12.2

**Comment by CreativeMD** [comment]
Can you give me a list of all mods installed? Pretty sure it's caused by another mod or plugin (if you are using spongeforge).

**Comment by Allinardo** [comment]
Nope. I tried it with only CreativeCore and LittleTiles, and with other mods installed, with and without optifine. I'm using a jar file provided to my by BisectHosting, forge-1.12.2-14.23.5.2847-universal.jar, for the server.

**Comment by CreativeMD** [comment]
Pretty sure it's the jar file provided by BisectHosting, because normally it should work fine. Can you try to use an ordinary forge server?

**Comment by Allinardo** [comment]
I tried connecting to my friend's forge server and there were no issues. He's using the same universal forge jar, so now I'm really wondering. Everyone else on my server experiences the same glitchiness so it's definitely not just on my end.

**Comment by CreativeMD** [comment]
So it's obviously the jar from BisectHosting or am I getting something wrong?

**Comment by Allinardo** [comment]
I have no idea, because my friend uses the same hosting service and the same jar. I'm unsure how to diagnose further.

**Comment by CreativeMD** [comment]
I'm a little confused. You are using the same jar? Then there is no difference? Obviously something has to be wrong. Have you already tried to install the forge server again?

**Comment by CreativeMD** [comment]
Still there?

**Comment by Allinardo** [comment]
It seems to have fixed itself? I didn't change anything, but I went in to test it again for different variables and now it just...works. Weird, whatever. Just happy it's fixed.

**Comment by CreativeMD** [comment]
Glad it's fixed. Just reopen the issue if it occurs again.
