### ISSUE TITLE
Always Crashing Becaus of Core Mod Stuff(?)

### ISSUE THREAD

**Issue by MotivationalHat** [CreativeMD/LittleTiles#309]
Hi, i'm using the latest version of littletiles on 1.12.2 with forgeoptifine and there's been crashes everytime i try to launch mc, and from what i read in the crash report i think it's because of littletiles and how the core mod should be in a seperate jar file, if that's the case, i would need to have an edited version of the jar file without the core mod embedded in it and a jar file for the core mod. Here's the crash report: https://pastebin.com/hEYxWUyJ if you find anything i couldn't find that caused the crash please tell me and i'll fix it right away.

**Comment by kirokadura** [comment]
Please download the latest version of CreativeCore as well.

**Comment by MotivationalHat** [comment]
that wasn't on the curseforge page, thank you!

**Comment by kirokadura** [comment]
It's...actually the first thing in the page.
