### ISSUE TITLE
LittleTiles not currently on curse?

### ISSUE THREAD

**Issue by userequaltonull** [CreativeMD/LittleTiles#310]
I tried to install littletiles, but couldn't find it on the Twitch Launcher. I then searched it up on google, and found a curseforge link, but it was listed as "not found", despite it being one of the first results. I have noticed other mods that seem to have disappeared from Curse all at once, though I am not sure exactly what happened to them. Maybe it's something that you can fix by re-uploading it to curse. Here is the curseforge page for littletiles, which is as you can see nonexistent.

https://www.curseforge.com/minecraft/mc-mods/littletiles

**Comment by kirokadura** [comment]
It's currently pending approval by the Curseforge moderation team.

**Comment by zISKo666** [comment]
Why is this mod no longer available on curseforge?
I can't believe that an approval needs sooo long.

**Comment by CreativeMD** [comment]
You are not the only one, already contacted the support, still nothing.

**Comment by CreativeMD** [comment]
Finally it's been approved.

**Comment by zISKo666** [comment]
Hohoho, it's back :)
