### ISSUE TITLE
Game crashes when using children in advanced recipes

### ISSUE THREAD

**Issue by Alesimon98** [CreativeMD/LittleTiles#311]
Hi, I'm new on GitHub, nice to meet you! Hope I'll be useful with the develop of this awesome mod.
Let's get to the point. I found this issue during the build of an advanced recipe which consists of a sliding door and a rotating handle as the child.
Everything works until I click the button to save the child's settings, and the game instantly crashes.
I'll report the log file in the next lines.

![save](https://user-images.githubusercontent.com/58987830/71015659-47fb9300-20f4-11ea-94cf-893d0c7ae2fb.png)

So basically, am I not able to manage any child or any type of complex animation?

### LOG

[hs_err_pid17404.log](https://github.com/CreativeMD/LittleTiles/files/3974461/hs_err_pid17404.log)

### SPECS

**Game version:** 1.12.2
**Forge version:** 1.12.2-14.23.5.2768
**Launcher:** SKlauncher 3-beta.14
**LittleTiles:** v1.5.0-pre180_mc1.12.2

### ADDONS:

- **CubicChunks** 1.12.2-0.0.926.0-SNAPSHOT-all

- **CreativeCore** v1.9.74_mc1.12.2

I don't know if this problem has already been fixed in more recent versions of the mod, let me know if I missed it :thinking:
Thank you for your support! :innocent:

**Comment by kirokadura** [comment]
Can you try updating CreativeCore and LittleTiles to the latest versions available on Curse? That might fix your issue.

**Comment by kirokadura** [comment]
If the issue persists after the update, can you provide me with an export of both structures? I'll put them together and see if I can reproduce the issue.

**Comment by Alesimon98** [comment]
Okay, here we are. Thank you a lot!
Sorry for the stupid question, this proves I'm a newbie 😄
