### ISSUE TITLE
Crashes on Startup

### ISSUE THREAD

**Issue by vicp-iq** [CreativeMD/LittleTiles#313]
I'm launching minecraft version 1.12-forge1.12-14.21.1.2443 with LittleTiles and CreativeCore and it crashes on startup, even before I see the forge loader screen.  These are the mods I've got installed:

- CreativeCore_v1.9.80_mc1.12.2.jar
- LittleTiles_v1.5.0-pre186_mc1.12.2.jar

I've uploaded my crash report: 
[crash-2019-12-21_10.58.56-client.txt](https://github.com/CreativeMD/LittleTiles/files/3991630/crash-2019-12-21_10.58.56-client.txt)

**Comment by kirokadura** [comment]
You're playing on Minecraft version 1.12, the mod is for 1.12.2.
