### ISSUE TITLE
Axis Door vanishing on server.

### ISSUE THREAD

**Issue by PurpleIvaylo** [CreativeMD/LittleTiles#314]
The problem with vanishing tiles, has been solved? I still have the same mods on the server yet they don't disappear now. But when I tried making a window *Axis door*, it keeps vanishing after a bit, after I keep testing it. Or especially when I tried breaking it. If I don't mess with it just place and then pick it up, it works, but if i only use it once, it disappears once I try to break it, so do the blocks I created it with.

**Logs: https://mclo.gs/uHOLfz3**
**Some screenshots I tried taking of it happening:**
**Edit:** After the last pic saying "Tile not found" the half window disappeared.
**Edit 2**: After I logged out *to see my hedgehog* I came back to my house and the windows are back? (last picture)
![2019-12-22_16 59 14](https://user-images.githubusercontent.com/57375359/71323543-2d069580-24dd-11ea-807a-4135698ffadb.png)
![2019-12-22_16 59 21](https://user-images.githubusercontent.com/57375359/71323544-2d069580-24dd-11ea-8dac-6fa14e3b86b2.png)
![2019-12-22_16 59 34](https://user-images.githubusercontent.com/57375359/71323545-2d9f2c00-24dd-11ea-8aa3-720d1a69b6c1.png)
![2019-12-22_16 59 49](https://user-images.githubusercontent.com/57375359/71323546-2d9f2c00-24dd-11ea-8c3f-d525c89a444f.png)
![2019-12-22_17 34 16](https://user-images.githubusercontent.com/57375359/71323941-896bb400-24e1-11ea-9223-de52ba05d6a2.png)

**Comment by kirokadura** [comment]
You seem to be using an outdated version of LittleTiles and CreativeCore. Update and check if the issue persists.

**Comment by PurpleIvaylo** [comment]
Hmm, Ok thank you! I didn't even notice there was an update. I will check and see if it still happens.

**Comment by PurpleIvaylo** [comment]
https://mclo.gs/7MKYt6G ---So they work now! they vanished half of the window for a second or two but they got replaced now. And I can destroy them. Problem is every time I press on the window, it opens, and i press on it again it kicks me out.

**Comment by CreativeMD** [comment]
This issue will be fixed in the next update.

**Comment by PurpleIvaylo** [comment]
Ok. thank you!
