### ISSUE TITLE
request: Check box to disable right click to open door and opencomputer compat. 

### ISSUE THREAD

**Issue by mindcloud69** [CreativeMD/LittleTiles#316]
I understand #1 may be difficult. Both of these would need to have a checkbox to disable right click interaction to be effective.

1. I would love to be able to control doors with OpenComputers a simple open close would be great. But the ability to also enable altering all of the parameters of a animations would be absolutely game changing. Imagine the stuff you could build!

2. If 1 is not possible the ability to just disable door interaction with right click would let you control doors with only commands which would be great for maps and serve as a interim solution for opencomputers as you can enable computer controlled commands with OC.

**Comment by CreativeMD** [comment]
It's added in the newest pre-release. Merry Christmas!

**Comment by mindcloud69** [comment]
You are freaking awesome! 
Just the disabled interaction or opencomputer compat?

**Comment by CreativeMD** [comment]
https://www.youtube.com/watch?v=_kgqR4K87qM

**Comment by mindcloud69** [comment]
Thank you! Would/Are you considering direct OpenComputers integration?

**Comment by CreativeMD** [comment]
Not at the moment. I plan to implement redstone so once that is done you should be able to control doors from OpenComputers as well (using redstone).
