### ISSUE TITLE
Sliding doors leaving ghost blocks when activated via the command in some places

### ISSUE THREAD

**Issue by GlassCrab** [CreativeMD/LittleTiles#317]
(Don't know if this is an issue in multiplayer, only tested in single) Absolutely no idea what's causing it, it seems like it only happens in certain areas, breaking and replacing the door does not fix it, and the specific ghost blocks the door leaves behind differ from door to door. The only thing I've found that fixes it is manually closing and reopening the door yourself, or re logging into the world. Youtube vid showcasing it here https://youtu.be/wtnZhS7bqFM and mod list here if its needed https://i.imgur.com/nNylYu7.png (vid might look a bit laggy but in game there wasn't a problem)

**Comment by CreativeMD** [comment]
I removed sending the block update from server to the client because I was afraid it could cause synchronization issues, but actually it wasn't. So it's added back in now and will be part of the next pre-release.

**Comment by CreativeMD** [comment]
New version has been released.
