### ISSUE TITLE
Connected Textures not working with Little Tiles

### ISSUE THREAD

**Issue by pneumaticLance** [CreativeMD/LittleTiles#318]
![2019-12-27_23 09 53](https://user-images.githubusercontent.com/40832595/71522374-6edd7480-28ff-11ea-8ee2-0987193d08c9.png)

The above screenshot was taken in an isolated instance with only the following:
- Minecraft 1.12.2
- Forge 14.23.5.2847
- Chisel-MC1.12.2-1.0.1.44
- CTM-MC1.12.2-1.0.1.30
- CreativeCore_v1.9.82_mc1.12.2
- LittleTiles_v1.5.0-pre188_mc1.12.2

(Top of each block type is a full block, while the bottom half slabs made with LittleTiles. On the right with 3x3 Chisel purple carpet blocks, left column is a mix of full blocks and LittleTiles half slab, while right column showing which block is a full block.)

I updated my modpack recently and found connected textures no longer work properly with LittleTiles. Here a comparison of my in game screenshot before and after the update. 

![bugreport](https://user-images.githubusercontent.com/40832595/71523601-be726f00-2904-11ea-9186-7fe96f106d0e.png)

I created an instance with only Chisel, CTM, LittleTiles and CreativeCore and managed to reproduce the same result, so I figured I'd report it.

Also, the broken texture seem to load differently on each game start (exit minecraft completely and restart the game). 
![2019-12-28_00 06 07](https://user-images.githubusercontent.com/40832595/71524025-9421b100-2906-11ea-911a-b8cf160b8baa.png)
![2019-12-28_00 06 21](https://user-images.githubusercontent.com/40832595/71524026-9421b100-2906-11ea-8378-cfb650eaf833.png)
![2019-12-28_00 07 52](https://user-images.githubusercontent.com/40832595/71524027-9421b100-2906-11ea-9a24-343be8c69d2c.png)
 
(Most obvious on the big fan and the purple 3x3, but smaller 2x2 had some differences too.)

**Comment by CreativeMD** [comment]
This is an issue of the Connected Textures Mod. I have reported it to them already, but they haven't replied yet (https://github.com/Chisel-Team/ConnectedTexturesMod/issues/119). I recommend to use the version earlier 1.0.1.29 that one works fine.

**Comment by pneumaticLance** [comment]
Thanks for responding. Using 1.0.1.29 fixed the issue for my game. Hope they can find a solution for the newer updates
