### ISSUE TITLE
Game crash when opening/closing doors in multiplayer.

### ISSUE THREAD

**Issue by Mightyjack22** [CreativeMD/LittleTiles#319]
Anytime we open/close a door we made, it crashes. Here is the crash log from my client and the log from the server if that will help as well. The crash in the client is right at the end, and the line in the server just before the crash (when I interacted with the door) is at [22:29:48]
[2019-12-27-6 (Client).log](https://github.com/CreativeMD/LittleTiles/files/4006714/2019-12-27-6.Client.log)
[latest (Server).log](https://github.com/CreativeMD/LittleTiles/files/4006715/latest.Server.log)

**Comment by CreativeMD** [comment]
This issue should be fixed in the upcoming pre-release.

**Comment by CreativeMD** [comment]
It's out now.
