### ISSUE TITLE
BlockUtils class is missing

### ISSUE THREAD

**Issue by vinz243** [CreativeMD/LittleTiles#320]
I'm trying to pull the latest version on branch 1.12 and it says BlockUtils is missing, as well as VecUtils and some other classes. I believe you have forgot to add them to git

**Comment by CreativeMD** [comment]
I have created a tutorial video which might help you: https://www.youtube.com/watch?v=7Ahshi_QjM4

Furthermore don't forget to add CreativeCore and IGCM if you want to work on LittleTiles.
