### ISSUE TITLE
Game crash shaders

### ISSUE THREAD

**Issue by SPARTAN188** [CreativeMD/LittleTiles#322]
Here is my story CreativeMD, I hope you read it, Im making my whole school with this mod, is actually beautiful
![image](https://user-images.githubusercontent.com/59324666/71561269-84eb5200-2a31-11ea-826e-f8bc2b9501a6.png), so I changed some values on the mod configuration on the game menu and this happened 
![image](https://user-images.githubusercontent.com/59324666/71561317-1ce93b80-2a32-11ea-8263-0db670b2c6ac.png)
then i realised that I made a backup, so i past that backup with MCedit to the world that was damaged and i tried to copy the parts that werent affected, 5 days ago I was copying the parts to the old backup, yeah in the same world with world edit, so I updated the mods (littletiles and creativecore) and I put performance mods (betterfps, foamfix and texfix), after i did that I went to my world and anything happended, 1 hour later a friend invited me to play on a server, and I went to the server with the mods and when I got back to my world it started crashing(there is the crashing report) i realised that betterfps, foamfix and texfix werent the roblem so I removed them, there was conflict with forge, optifine, shaders becasue when i wanted to run the world with the updated mods and the performance mods without shaders it ran correctly and no crash, but when I activate the sahders it insgtantly crashes(its the same crash report down below), so i ttied to reset settings of optfine, i ttied to uninstall miencraft I tried to change the game launcher (Tlauncher to Shiginima, when i did this and put all the saves and mods back the first laod of the world didnt crash, then the second time i load the save it rashes giving me the Tesellation wrror) I did anything even trying to update my graphics card, so I remember something when I was about to start building my school with the sahders, I was on the internet searching if there was compatibility with shaders and littletiles mod, and every page i read said that was incompaitble, so isntantly I started to try different versions of littetiles, the one that wokred for me to play with shaders was pre186 and creativecore 1.93, now i need to check if everything workd, like doors, because before I started writting this I started the world with shaders and didnt crash, so i dont know if the structures will work, lets see what happened
CreativeMD you know the minecraft java its bad optimized and its crap, but also want to thank for this awsome mod,

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre189_mc1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.9.83_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 12/28/19 5:44 PM
Description: Tesselating block model

java.nio.ReadOnlyBufferException
	at java.nio.DirectFloatBufferRU.put(Unknown Source)
	at net.optifine.shaders.SVertexBuilder.calcNormal(SVertexBuilder.java:292)
	at net.optifine.shaders.SVertexBuilder.endAddVertexData(SVertexBuilder.java:183)
	at net.minecraft.client.renderer.BufferBuilder.func_178981_a(BufferBuilder.java:605)
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsFlat(BlockModelRenderer.java:398)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:153)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:65)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:79)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:58)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:328)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.DirectFloatBufferRU.put(Unknown Source)
	at net.optifine.shaders.SVertexBuilder.calcNormal(SVertexBuilder.java:292)
	at net.optifine.shaders.SVertexBuilder.endAddVertexData(SVertexBuilder.java:183)
	at net.minecraft.client.renderer.BufferBuilder.func_178981_a(BufferBuilder.java:605)
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsFlat(BlockModelRenderer.java:398)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:153)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:65)

-- Block model being tesselated --
Details:
	Block: minecraft:bedrock
	Block location: World: (-1488,0,656), Chunk: (at 0,0,0 in -93,41; contains blocks -1488,0,656 to -1473,255,671), Region: (-3,1; contains chunks -96,32 to -65,63, blocks -1536,0,512 to -1025,255,1023)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:79)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:58)

-- Block being tesselated --
Details:
	Block type: ID #7 (tile.bedrock // net.minecraft.block.BlockEmptyDrops // minecraft:bedrock)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-1488,0,656), Chunk: (at 0,0,0 in -93,41; contains blocks -1488,0,656 to -1473,255,671), Region: (-3,1; contains chunks -96,32 to -65,63, blocks -1536,0,512 to -1025,255,1023)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Gamersp112'/63, l='MpServer', x=-1531.06, y=40.52, z=634.94]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1569,4,705), Chunk: (at 15,0,1 in -99,44; contains blocks -1584,0,704 to -1569,255,719), Region: (-4,1; contains chunks -128,32 to -97,63, blocks -2048,0,512 to -1537,255,1023)
	Level time: 6731047 game time, 29844 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 19 total; [EntityCow['Cow'/32, l='MpServer', x=-1586.92, y=4.00, z=582.82], EntityCow['Cow'/33, l='MpServer', x=-1588.57, y=4.00, z=668.21], EntityCow['Cow'/34, l='MpServer', x=-1577.99, y=4.00, z=568.99], EntityChicken['Chicken'/35, l='MpServer', x=-1579.32, y=4.00, z=630.93], EntitySheep['Sheep'/36, l='MpServer', x=-1569.54, y=4.00, z=624.14], EntityPlayerSP['Gamersp112'/63, l='MpServer', x=-1531.06, y=40.52, z=634.94], EntityCow['Cow'/39, l='MpServer', x=-1560.82, y=4.00, z=610.39], EntityChicken['Chicken'/42, l='MpServer', x=-1525.93, y=4.00, z=579.87], EntitySheep['Sheep'/43, l='MpServer', x=-1530.27, y=4.00, z=621.67], EntityPig['Pig'/47, l='MpServer', x=-1511.59, y=4.00, z=630.77], EntitySheep['Sheep'/49, l='MpServer', x=-1487.80, y=4.00, z=599.27], EntityPig['Pig'/50, l='MpServer', x=-1475.40, y=4.00, z=675.23], EntityChicken['Chicken'/51, l='MpServer', x=-1483.35, y=4.00, z=692.04], EntityChicken['Chicken'/52, l='MpServer', x=-1456.79, y=4.00, z=597.54], EntityPig['Pig'/56, l='MpServer', x=-1450.47, y=4.00, z=622.34], EntityChicken['Chicken'/57, l='MpServer', x=-1455.76, y=4.00, z=680.49], EntityChicken['Chicken'/27, l='MpServer', x=-1602.46, y=4.00, z=655.13], EntityCow['Cow'/28, l='MpServer', x=-1605.30, y=4.00, z=674.42], EntityChicken['Chicken'/31, l='MpServer', x=-1584.07, y=4.00, z=580.98]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:49)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 318861056 bytes (304 MB) / 981258240 bytes (935 MB) up to 15985803264 bytes (15245 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx15257M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version         | Source                                            | Signature |
	|:------ |:----------------- |:--------------- |:------------------------------------------------- |:--------- |
	| LCHIJA | minecraft         | 1.12.2          | minecraft.jar                                     | None      |
	| LCHIJA | mcp               | 9.42            | minecraft.jar                                     | None      |
	| LCHIJA | FML               | 8.0.99.99       | forge-1.12.2-14.23.5.2847.jar                     | None      |
	| LCHIJA | forge             | 14.23.5.2847    | forge-1.12.2-14.23.5.2847.jar                     | None      |
	| LCHIJA | creativecoredummy | 1.0.0           | minecraft.jar                                     | None      |
	| LCHIJA | littletilescore   | 1.0.0           | minecraft.jar                                     | None      |
	| LCHIJA | creativecore      | 1.9.9           | CreativeCore_v1.9.83_mc1.12.2.jar                 | None      |
	| LCHIJA | waila             | 1.8.26          | Hwyla-1.8.26-B41_1.12.2.jar                       | None      |
	| LCHIJA | jei               | 4.15.0.268      | jei_1.12.2-4.15.0.268.jar                         | None      |
	| LCHIJA | journeymap        | 1.12.2-5.5.4    | journeymap-1.12.2-5.5.4.jar                       | None      |
	| LCHIJA | littletiles       | 1.5.0           | LittleTiles_v1.5.0-pre189_mc1.12.2.jar            | None      |
	| LCHIJA | worldedit         | 6.1.10-SNAPSHOT | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None      |

	Loaded coremods (and transformers): 
LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
  com.creativemd.littletiles.LittleTilesLateTransformer
LittlePatchingLoader (LittleTiles_v1.5.0-pre189_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CreativePatchingLoader (CreativeCore_v1.9.83_mc1.12.2.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: Forge 1.12.2
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx 
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-v10.1-Ultra-Motion-Blur.zip
	OpenGlVersion: 4.6.13571 Compatibility Profile Context 19.9.3 26.20.13025.1004
	OpenGlRenderer: Radeon RX 560X Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by CreativeMD** [comment]
This issue will be fixed in the upcoming pre-release.
