### ISSUE TITLE
Ghost left behind when opening door with the /lt-open command.

### ISSUE THREAD

**Issue by WraithHunter** [CreativeMD/LittleTiles#327]
Ghost entities are being left behind when using the /lt-open command to open doors that contain a another little tiles entity or bit in the same block.

![2020-01-05_06 15 36](https://user-images.githubusercontent.com/59531600/71780815-80b8ba80-2f84-11ea-9703-b0d7d3ee493a.png)
![2020-01-05_06 12 17](https://user-images.githubusercontent.com/59531600/71780816-81515100-2f84-11ea-8082-9e4b8b65da28.png)
![2020-01-05_06 12 28](https://user-images.githubusercontent.com/59531600/71780817-81515100-2f84-11ea-8a88-ada25603429c.png)

**Comment by CreativeMD** [comment]
Which version are you using?

**Comment by WraithHunter** [comment]
v1.5.0-pre195 mc1.12.2.

**Comment by CreativeMD** [comment]
The newest version of CreativeCore and LittleTiles might fix your issue.

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still occurs with the newest version just reopen it.
