### ISSUE TITLE
Fence Error in log (multiplayer)

### ISSUE THREAD

**Issue by Silencx** [CreativeMD/LittleTiles#328]
This error happens when i place a fence inbetween 2 walls that i have created using Little Tiles.
The fence also becomes a ghost block until the chunk reloads 

Running :
- CreativeCore v1.9.83
- LittleTiles v1.5.0-pre189

Pastebin : https://pastebin.com/FGsAC207

![2020-01-06_00 28 01](https://user-images.githubusercontent.com/36223318/71787732-bfe61a80-301b-11ea-87fd-906cef8efa5d.png)
![2020-01-06_00 28 14](https://user-images.githubusercontent.com/36223318/71787733-bfe61a80-301b-11ea-9ae8-50bec3867c8f.png)

**Comment by CreativeMD** [comment]
This issue has been fixed already, just update CreativeCore and LittleTiles.
