### ISSUE TITLE
Connected player crashes when sliding door closes

### ISSUE THREAD

**Issue by Tim3Game** [CreativeMD/LittleTiles#329]
Hello,
I'm currently playing a LAN game with my friend on my singleplayer world. Every time, we interact with a sliding door, it's fine for me (as a host), but for him, it crashes his game.

His crash report: [https://paste.dimdev.org/qubaxosuqe.mccrash](https://paste.dimdev.org/qubaxosuqe.mccrash)
Video example: [https://youtu.be/ZHH7-fyLRe8](https://youtu.be/ZHH7-fyLRe8)

**Comment by CreativeMD** [comment]
This will be fixed in the upcoming version.

**Comment by CreativeMD** [comment]
New version has been released.
