### ISSUE TITLE
Is this a mechanic of the mod?

### ISSUE THREAD

**Issue by ricey125** [CreativeMD/LittleTiles#330]
I was wondering, can the moving function of little tiles possibly create the effect that the stretching room in Disneylands Haunted Mansion ride does?

**Comment by kirokadura** [comment]
I don't have much experience with it, but from the footage I found it seems totally doable. Of course the tiles wouldn't be stretching (just like the room isn't) but you can create that illusion with some creativity and patience.

**Comment by CreativeMD** [comment]
If you need further help, join our discord server! https://discord.gg/W9QM3fS
