### ISSUE TITLE
Crash when someone built a little workbench

### ISSUE THREAD

**Issue by TheRealDadbeard** [CreativeMD/LittleTiles#333]
[latest.log](https://github.com/CreativeMD/LittleTiles/files/4050699/latest.log)

Whole server just crashed. Crash is at the end of the log

MC12.2.2
Forge 2847
Sponge 1.12.2-2838-7.1.8
Littletiles LittleTiles_v1.5.0-pre197_mc1.12.2
CreativeCore CreativeCore_v1.9.88_mc1.12.2

**Comment by TheRealDadbeard** [comment]
Removing Spongeforge does not fix it

**Comment by TheRealDadbeard** [comment]
After downgrading there was still a half of it left and it became little tiles that I had to remove with the hammer.

**Comment by TheRealDadbeard** [comment]
Another crash https://paste.dimdev.org/alononeqof.mccrash

**Comment by CreativeMD** [comment]
The second crash has been fixed already. Just make sure to update CreativeCore.

**Comment by TheRealDadbeard** [comment]
okay good so this is just a core issue got it thx

**Comment by CreativeMD** [comment]
Download the newest version of CreativeCore and LittleTiles (even though it has the same version number) to fix this issue.
