### ISSUE TITLE
[Question] How far is LT compatible to Advanced Rocketry?

### ISSUE THREAD

**Issue by KleinGrrmpf** [CreativeMD/LittleTiles#334]
You wrote that the tiles don't render when building a rocket. That's fin with me. My question is, how far the compat goes in case of sealing a room. Are the LT blocks sealable, so that you can i.e. make an airlock door out of them or even build a whole space station with little tiles?

**Comment by kirokadura** [comment]
The user reports we received were only about rockets. If it accepts only blocks as seal, then LT most likely won't work.

**Comment by CreativeMD** [comment]
I will close this issue for now as I can't fix it from my end anyway.
