### ISSUE TITLE
Multiplayer glitch

### ISSUE THREAD

**Issue by jordijordiMAX** [CreativeMD/LittleTiles#338]
Hello, im using the little tiles mod on a server, 1.12 version, and it seems to be a glitch, while making doors, when i try to open them it opens, but when i try to close them they just dissapear, this issue isnt present in singleplayer. Any way to solve this ?

**Comment by MarbleGateKeeper** [comment]
Please specific mod verson

**Comment by jordijordiMAX** [comment]
LittleTiles v1.5.0-pre18 mc1.12, tried also pre19 and pre20, CreativeCore v1.8.10 mc1.12

**Comment by kirokadura** [comment]
Version 1.12 is no longer supported. Please use the latest versions for 1.12.2

**Comment by jordijordiMAX** [comment]
It should be fixed when i use the latest versions ?

**Comment by kirokadura** [comment]
Yes, I suggest picking out version pre199 from our Discord.

**Comment by CreativeMD** [comment]
I will close this issue for now. This should be fixed in the newer version.
