### ISSUE TITLE
Doors glitching out and duplicating

### ISSUE THREAD

**Issue by Tschipp** [CreativeMD/LittleTiles#340]
After a few times of opening/closing the door, it can somehow duplicate itself: 
![image](https://user-images.githubusercontent.com/11649893/73542049-25b79d80-4434-11ea-9e55-d66091e90165.png)
The door is actually there, it's not just a visual glitch. When I try to break it, I get "structure is not loaded", so it can only be removed with the little wrench.

**Comment by CreativeMD** [comment]
Which version are you using?

**Comment by Tschipp** [comment]
Right, sorry.
LT pre198
CreativeCore 1.9.90

**Comment by CreativeMD** [comment]
In multiplayer?

**Comment by Tschipp** [comment]
Yes

**Comment by CreativeMD** [comment]
Can you download these versions and see if the issue is fixed?

https://cdn.discordapp.com/attachments/326729168266199040/674237457612537876/CreativeCore_v1.9.91_mc1.12.2.jar
https://cdn.discordapp.com/attachments/326729168266199040/674238698044522497/LittleTiles_v1.5.0-pre1995_mc1.12.2.jar

**Comment by sirrobindoger** [comment]
Hi.

The versions you attached seem to launch successfully on the client end, but when trying to use it on my dedicated Linux server, it crashed.

log: https://pastebin.com/ngijktkE

**Comment by Tschipp** [comment]
Sorry @CreativeMD I am not at home to test it for now, will be able to do it earliest next friday...

**Comment by CreativeMD** [comment]
@sirrobindoger fixed it: https://cdn.discordapp.com/attachments/326729168266199040/676148113328570398/LittleTiles_v1.5.0-pre199_8_mc1.12.2.jar

@Tschipp no need to test it. Other people did so already and it seems to be fixed.

**Comment by Tschipp** [comment]
great to hear!

**Comment by sirrobindoger** [comment]
> @sirrobindoger fixed it: https://cdn.discordapp.com/attachments/326729168266199040/676148113328570398/LittleTiles_v1.5.0-pre199_8_mc1.12.2.jar
> 
> @Tschipp no need to test it. Other people did so already and it seems to be fixed.

Did you delete that link? It doesn't seem to be working.

**Comment by CreativeMD** [comment]
@sirrobindoger 
https://cdn.discordapp.com/attachments/326729168266199040/676397142478159873/LittleTiles_v1.5.0-pre199_10_mc1.12.2.jar

**Comment by CreativeMD** [comment]
It's out now!
