### ISSUE TITLE
Updated to newest versions of creative core and littletiles, game crashes after right clicking door twice

### ISSUE THREAD

**Issue by nerdlordollie** [CreativeMD/LittleTiles#343]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  CreativePatchingLoader (CreativeCore_v1.9.91_mc1.12.2.jar)
  FarseekCoreMod (Farseek-1.12-2.4.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre199_9_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 2/9/20 11:42 PM
Description: Unexpected error

java.lang.IllegalStateException: Function is not supported
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.GL30.glMapBufferRange(GL30.java:998)
	at com.creativemd.littletiles.client.render.world.RenderUploader.glMapBufferRange(RenderUploader.java:144)
	at com.creativemd.littletiles.client.render.world.RenderUploader.uploadRenderData(RenderUploader.java:104)
	at com.creativemd.littletiles.common.entity.DoorController.place(DoorController.java:264)
	at com.creativemd.littletiles.common.entity.DoorController.endTransition(DoorController.java:189)
	at com.creativemd.littletiles.common.util.animation.AnimationController.tick(AnimationController.java:155)
	at com.creativemd.littletiles.common.entity.DoorController.tick(DoorController.java:168)
	at com.creativemd.littletiles.common.entity.EntityAnimation.onTick(EntityAnimation.java:593)
	at com.creativemd.littletiles.common.entity.EntityAnimation.onUpdateForReal(EntityAnimation.java:643)
	at com.creativemd.littletiles.client.world.LittleAnimationHandlerClient.tickClient(LittleAnimationHandlerClient.java:500)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_394_LittleAnimationHandlerClient_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at farseek.world.gen.structure.package$.post(package.scala:38)
	at farseek.world.gen.structure.package.post(package.scala)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.GL30.glMapBufferRange(GL30.java:998)
	at com.creativemd.littletiles.client.render.world.RenderUploader.glMapBufferRange(RenderUploader.java:144)
	at com.creativemd.littletiles.client.render.world.RenderUploader.uploadRenderData(RenderUploader.java:104)
	at com.creativemd.littletiles.common.entity.DoorController.place(DoorController.java:264)
	at com.creativemd.littletiles.common.entity.DoorController.endTransition(DoorController.java:189)
	at com.creativemd.littletiles.common.util.animation.AnimationController.tick(AnimationController.java:155)
	at com.creativemd.littletiles.common.entity.DoorController.tick(DoorController.java:168)
	at com.creativemd.littletiles.common.entity.EntityAnimation.onTick(EntityAnimation.java:593)
	at com.creativemd.littletiles.common.entity.EntityAnimation.onUpdateForReal(EntityAnimation.java:643)
	at com.creativemd.littletiles.client.world.LittleAnimationHandlerClient.tickClient(LittleAnimationHandlerClient.java:500)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_394_LittleAnimationHandlerClient_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at farseek.world.gen.structure.package$.post(package.scala:38)
	at farseek.world.gen.structure.package.post(package.scala)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['NerdLordOllie'/271, l='MpServer', x=-639.68, y=64.00, z=47.93]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-180,64,192), Chunk: (at 12,4,0 in -12,12; contains blocks -192,0,192 to -177,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 12259773 game time, 52481 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 103 total; [EntityPlayerSP['NerdLordOllie'/271, l='MpServer', x=-639.68, y=64.00, z=47.93], EntityCreeper['Creeper'/275, l='MpServer', x=-578.50, y=33.00, z=99.50], EntityCreeper['Creeper'/276, l='MpServer', x=-571.72, y=41.00, z=86.46], Nile Hippopotamus, EntitySockeyeSalmon['Sockeye Salmon'/282, l='MpServer', x=-564.15, y=62.00, z=144.15], Hawksbill Sea Turtle, Hawksbill Sea Turtle, Hawksbill Sea Turtle, Gaur, Gaur, Meerkat, Cockatoo, Gaur, Meerkat, EntitySkeleton['Skeleton'/357, l='MpServer', x=-691.47, y=31.00, z=33.29], EntityCreeper['Creeper'/358, l='MpServer', x=-681.50, y=21.00, z=21.50], EntitySkeleton['Skeleton'/359, l='MpServer', x=-664.50, y=19.00, z=9.50], EntityBat['Bat'/360, l='MpServer', x=-649.97, y=27.89, z=12.06], EntityBat['Bat'/362, l='MpServer', x=-710.31, y=13.10, z=62.75], Japanese Giant Salamander, EntitySkeleton['Skeleton'/366, l='MpServer', x=-668.50, y=36.00, z=-4.50], EntityItem['item.item.arrow'/367, l='MpServer', x=-660.88, y=68.00, z=-5.86], EntityBat['Bat'/376, l='MpServer', x=-635.02, y=38.42, z=-24.61], EntityBat['Bat'/380, l='MpServer', x=-695.14, y=15.34, z=93.59], EntityTumbleweed['entity.Tumbleweed.name'/381, l='MpServer', x=-664.96, y=66.22, z=45.36], Nile Hippopotamus, Nile Hippopotamus, Meerkat, EntitySkeleton['Skeleton'/387, l='MpServer', x=-631.30, y=55.00, z=33.51], EntityCreeper['Creeper'/388, l='MpServer', x=-601.50, y=28.00, z=6.50], EntitySpider['Spider'/389, l='MpServer', x=-599.07, y=29.00, z=3.95], EntityEnderman['Enderman'/390, l='MpServer', x=-718.50, y=20.00, z=123.50], EntityCreeper['Creeper'/391, l='MpServer', x=-664.43, y=64.00, z=73.78], Cockatoo, EntityAnimation['entity.animation.name'/497, l='MpServer', x=-641.00, y=64.00, z=48.00], Red Kangaroo, EntityBat['Bat'/400, l='MpServer', x=-590.68, y=24.03, z=0.44], EntityBat['Bat'/401, l='MpServer', x=-591.20, y=24.06, z=0.80], Gaur, EntitySkeleton['Skeleton'/403, l='MpServer', x=-584.50, y=31.00, z=-13.29], EntitySkeleton['Skeleton'/404, l='MpServer', x=-581.50, y=78.00, z=-27.50], EntitySkeleton['Skeleton'/405, l='MpServer', x=-580.50, y=78.00, z=-27.50], EntitySkeleton['Skeleton'/406, l='MpServer', x=-584.50, y=78.00, z=-24.50], EntitySpider['Spider'/408, l='MpServer', x=-669.35, y=64.00, z=59.93], EntityCreeper['Creeper'/409, l='MpServer', x=-649.50, y=16.00, z=35.50], EntityCreeper['Creeper'/410, l='MpServer', x=-647.81, y=16.00, z=34.42], EntityBat['Bat'/411, l='MpServer', x=-646.83, y=17.75, z=38.43], EntitySpider['Spider'/412, l='MpServer', x=-636.50, y=22.00, z=22.50], EntityCreeper['Creeper'/413, l='MpServer', x=-630.50, y=22.00, z=28.50], EntityCreeper['Creeper'/414, l='MpServer', x=-635.56, y=55.00, z=30.20], Nile Hippopotamus, Nile Hippopotamus, EntityItem['item.item.string'/430, l='MpServer', x=-624.78, y=69.00, z=6.22], EntityItem['item.item.seeds_melon'/431, l='MpServer', x=-624.75, y=69.00, z=5.66], EntityItem['item.tile.deadbush'/432, l='MpServer', x=-624.77, y=69.00, z=5.76], EntityItem['item.item.goldNugget'/433, l='MpServer', x=-624.77, y=69.00, z=6.20], EntityItem['item.item.ingotGold'/434, l='MpServer', x=-624.59, y=69.00, z=5.76], EntityItem['item.item.wheat'/435, l='MpServer', x=-624.53, y=69.00, z=6.32], EntitySpider['Spider'/436, l='MpServer', x=-609.70, y=26.10, z=1.03], EntityCreeper['Creeper'/437, l='MpServer', x=-618.50, y=25.00, z=-0.50], EntitySkeleton['Skeleton'/438, l='MpServer', x=-617.77, y=26.00, z=-2.54], EntityBat['Bat'/439, l='MpServer', x=-622.25, y=25.10, z=-1.25], EntitySkeleton['Skeleton'/441, l='MpServer', x=-646.50, y=31.00, z=22.50], EntitySkeleton['Skeleton'/442, l='MpServer', x=-655.50, y=18.00, z=24.50], EntityEnderman['Enderman'/443, l='MpServer', x=-650.27, y=55.00, z=20.49], EntityBat['Bat'/445, l='MpServer', x=-698.72, y=13.00, z=87.66], Nile Hippopotamus, Meerkat, Nile Hippopotamus, Nile Hippopotamus, EntityZombie['Zombie'/451, l='MpServer', x=-645.50, y=23.00, z=12.50], EntityItem['item.item.goldNugget'/452, l='MpServer', x=-628.65, y=69.00, z=-5.65], EntityItem['item.item.wheat'/453, l='MpServer', x=-628.64, y=69.00, z=-5.64], EntitySkeleton['Skeleton'/454, l='MpServer', x=-612.50, y=20.00, z=-18.50], EntityBat['Bat'/455, l='MpServer', x=-612.25, y=38.10, z=-19.41], EntityBat['Bat'/456, l='MpServer', x=-705.11, y=15.10, z=69.43], EntityBat['Bat'/457, l='MpServer', x=-708.28, y=12.29, z=63.32], Gaur, EntityCreeper['Creeper'/459, l='MpServer', x=-657.41, y=18.00, z=15.50], EntitySkeleton['Skeleton'/460, l='MpServer', x=-656.50, y=18.00, z=23.10], EntitySkeleton['Skeleton'/461, l='MpServer', x=-660.70, y=16.18, z=26.70], EntitySkeleton['Skeleton'/462, l='MpServer', x=-574.50, y=44.00, z=32.50], EntityZombie['Zombie'/463, l='MpServer', x=-573.50, y=44.00, z=35.50], Nile Hippopotamus, EntitySkeleton['Skeleton'/466, l='MpServer', x=-665.48, y=17.00, z=129.71], EntitySkeleton['Skeleton'/467, l='MpServer', x=-574.50, y=24.00, z=19.50], EntitySkeleton['Skeleton'/469, l='MpServer', x=-576.50, y=44.00, z=32.50], EntitySkeleton['Skeleton'/470, l='MpServer', x=-579.50, y=44.00, z=35.50], EntitySkeleton['Skeleton'/471, l='MpServer', x=-578.50, y=44.00, z=32.50], Gaur, EntitySkeleton['Skeleton'/473, l='MpServer', x=-671.50, y=17.00, z=116.50], EntityZombie['Zombie'/474, l='MpServer', x=-654.50, y=20.00, z=111.50], Nile Hippopotamus, EntityZombie['Zombie'/477, l='MpServer', x=-581.50, y=44.00, z=31.50], EntityBat['Bat'/478, l='MpServer', x=-576.23, y=44.09, z=30.36], EntityBat['Bat'/479, l='MpServer', x=-577.58, y=13.15, z=16.42], EntitySpider['Spider'/480, l='MpServer', x=-657.50, y=35.00, z=96.50], Meerkat, EntityCreeper['Creeper'/482, l='MpServer', x=-596.50, y=28.00, z=18.50], EntitySkeleton['Skeleton'/483, l='MpServer', x=-567.50, y=20.00, z=-10.50], EntityTumbleweed['entity.Tumbleweed.name'/485, l='MpServer', x=-648.76, y=71.25, z=-12.50], EntityTumbleweed['entity.Tumbleweed.name'/486, l='MpServer', x=-681.98, y=66.35, z=-29.76], EntityTumbleweed['entity.Tumbleweed.name'/487, l='MpServer', x=-688.91, y=67.45, z=14.09]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.15.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1236482152 bytes (1179 MB) / 2113929216 bytes (2016 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 38 mods loaded, 38 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version                 | Source                                             | Signature                                |
	|:------ |:----------------- |:----------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2                  | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp               | 9.42                    | minecraft.jar                                      | None                                     |
	| LCHIJA | FML               | 8.0.99.99               | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCHIJA | forge             | 14.23.5.2847            | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCHIJA | creativecoredummy | 1.0.0                   | minecraft.jar                                      | None                                     |
	| LCHIJA | littletilescore   | 1.0.0                   | minecraft.jar                                      | None                                     |
	| LCHIJA | bspkrscore        | 7.6.0.1                 | [1.12]bspkrsCore-universal-7.6.0.1.jar             | None                                     |
	| LCHIJA | treecapitator     | 1.43.0                  | [1.12]TreeCapitator-client-1.43.0.jar              | None                                     |
	| LCHIJA | akashictome       | 1.2-12                  | AkashicTome-1.2-12.jar                             | None                                     |
	| LCHIJA | autoreglib        | 1.3-32                  | AutoRegLib-1.3-32.jar                              | None                                     |
	| LCHIJA | biomesoplenty     | 7.0.1.2441              | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar      | None                                     |
	| LCHIJA | bookworm          | 1.12.2-2.3.0            | bookworm-1.12.2-2.3.0.jar                          | None                                     |
	| LCHIJA | ctm               | MC1.12.2-1.0.1.30       | CTM-MC1.12.2-1.0.1.30.jar                          | None                                     |
	| LCHIJA | jei               | 4.15.0.291              | jei_1.12.2-4.15.0.291.jar                          | None                                     |
	| LCHIJA | chisel            | MC1.12.2-1.0.1.44       | Chisel-MC1.12.2-1.0.1.44.jar                       | None                                     |
	| LCHIJA | chiselsandbits    | 14.33                   | chiselsandbits-14.33.jar                           | None                                     |
	| LCHIJA | creativecore      | 1.9.9                   | CreativeCore_v1.9.91_mc1.12.2.jar                  | None                                     |
	| LCHIJA | fairylights       | 2.1.10                  | fairylights-2.1.10-1.12.2.jar                      | None                                     |
	| LCHIJA | farseek           | 2.4                     | Farseek-1.12-2.4.jar                               | None                                     |
	| LCHIJA | fastleafdecay     | v14                     | FastLeafDecay-v14.jar                              | None                                     |
	| LCHIJA | llibrary          | 1.7.19                  | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | fossil            | 8.0.3                   | fossilsarcheology-8.0.3.jar                        | None                                     |
	| LCHIJA | cfm               | 6.3.1                   | furniture-6.3.1-1.12.2.jar                         | None                                     |
	| LCHIJA | journeymap        | 1.12.2-5.5.7            | journeymap-1.12.2-5.5.7.jar                        | None                                     |
	| LCHIJA | kagic             | X11p13                  | kagic-X11p13.jar                                   | None                                     |
	| LCHIJA | keywizard         | 1.12.2-1.7.3            | keywizard-1.12.2-1.7.3.jar                         | None                                     |
	| LCHIJA | zawa              | 1.12.2-1.7.0            | zawa-1.12.2-1.7.0.jar                              | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| LCHIJA | lilcritters       | 1.12.2-0.0.1.3-beta4    | lilcritters-1.12.2-0.0.1.3-beta4.jar               | None                                     |
	| LCHIJA | littletiles       | 1.5.0                   | LittleTiles_v1.5.0-pre199_9_mc1.12.2.jar           | None                                     |
	| LCHIJA | placebo           | 1.6.0                   | Placebo-1.12.2-1.6.0.jar                           | None                                     |
	| LCHIJA | magicalmap        | 3.3.2                   | Magical+Map-1.12.2-3.3.2.jar                       | None                                     |
	| LCHIJA | faunanatural      | 1.12.2-1.5.0            | NaturalFauna+Mod-1.12.2-1.5.0.jar                  | None                                     |
	| LCHIJA | naturescompass    | 1.8.3                   | NaturesCompass-1.12.2-1.8.3.jar                    | None                                     |
	| LCHIJA | streams           | 0.4.8                   | Streams-1.12-0.4.8.jar                             | None                                     |
	| LCHIJA | tumbleweed        | 1.11-0.4.5              | tumbleweed-1.11-0.4.5.jar                          | None                                     |
	| LCHIJA | villagenames      | 3.2.3                   | VillageNames-1.12.2-3.2.3.jar                      | None                                     |
	| LCHIJA | structurize       | 1.12.2-0.10.124-ALPHA   | structurize-1.12.2-0.10.124-ALPHA.jar              | None                                     |
	| LCHIJA | minecolonies      | 1.12.2-0.10.592-RELEASE | minecolonies-1.12.2-0.10.592-RELEASE-universal.jar | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CreativePatchingLoader (CreativeCore_v1.9.91_mc1.12.2.jar)
  
FarseekCoreMod (Farseek-1.12-2.4.jar)
  farseek.core.FarseekClassTransformer
LittlePatchingLoader (LittleTiles_v1.5.0-pre199_9_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-14.4.23' Renderer: 'Intel Iris Pro OpenGL Engine'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.2
	OpenGL: Intel Iris Pro OpenGL Engine GL version 2.1 INTEL-14.4.23, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz

**Comment by CreativeMD** [comment]
Does this version fix your issue?
https://cdn.discordapp.com/attachments/326729168266199040/676397142478159873/LittleTiles_v1.5.0-pre199_10_mc1.12.2.jar

**Comment by nerdlordollie** [comment]
It does! Thank you so much!

**Comment by CreativeMD** [comment]
New version is out!
