### ISSUE TITLE
"Stay animated" option never seems to work

### ISSUE THREAD

**Issue by OTDrake** [CreativeMD/LittleTiles#347]
Pretty much, i'm trying to make a back and forth motion with a door/block. However, after selecting the "stay animated" option, it only does it once and i have to click on the block again for it to start the animation once again. I'm not sure if I'm doing something wrong or whatever but I would like some insight on this seeing as there are barely any reliable information online about the mod it seems.
Thank you for reading.

**Comment by CreativeMD** [comment]
Stay animated means the door will not place itself after the animation is done. It's not looping. If you want to loop the door you have to use the open command or the addon little opener.
