### ISSUE TITLE
Parent Structure has to have at least one tile

### ISSUE THREAD

**Issue by stupidoemstero** [CreativeMD/LittleTiles#348]
I've been trying my hand at door activators, but every time I try to "connect" two structures with an advanced recipie, I get this message 
![image](https://user-images.githubusercontent.com/44178591/75546228-694bfa00-5a28-11ea-8266-64be95071bbc.png)

Now the door I built looks like this
![image](https://user-images.githubusercontent.com/44178591/75546314-8f719a00-5a28-11ea-92f6-d8c88fb8c507.png)

And around that I wanted a simple doorframe: (2 blocks wide, 3 high)
![image](https://user-images.githubusercontent.com/44178591/75546357-a31d0080-5a28-11ea-8c92-84a3aa2eb915.png)

When I put the two together, select them with the advanced recipie and want to make a door activator I get the error from the first screenshot. And if I then disable remember structure, both become a door.
I built the double door like in your YouTube video "LitteTiles Preview 90 Introducing Door Activator" and somehow it worked without issue.

I'm using the most recent versions of LittleTiles (LittleTiles_v1.5.0-pre198_mc1.12.2), CreativeCore(CreativeCore_v1.9.90_mc1.12.2) and the recommended version of Forge (1.12.2-forge1.12.2-14.23.5.2768). 
Also these mods:
AmbientSounds_v3.0.9_mc1.12.2
CraftStudio-1.0.0.93-mc1.12-alpha
Animania-Mod-1.12.2
jei_1.12.2-4.12.1.217
JourneyMap-Mod-1.12.2-Unlimited
OptiFine_1.12.2_HD_U_E2
PeacefulSurface-1.12.2-v2
Sound-Physics-Mod-1.12.2
tektopia-1.1.0

Perhaps I just made a stupid mistake, but thanks for the help in advance

**Comment by stupidoemstero** [comment]
I played around with it some more. I rebuilt the door, made a recipie, put that down and then built the frame around it and saved the entire structure as a door activator and it worked.
But when I put down the door as a structure, then the frame as a structure, I can't "combine" them.

**Comment by CreativeMD** [comment]
There is no way to combine structures. If you use the recipe it requires tiles, otherwise there is no way to actually setup the parent. Don't set the frame to fixed, place the door and the frame (but not as a structure) then you can setup a recipe and make the frame fixed and have the door as a child.
