### ISSUE TITLE
No GUI to select axis for creating doors!

### ISSUE THREAD

**Issue by Neuron67** [CreativeMD/LittleTiles#35]
In 1.11.2 and 1.10.2 right clicking with Little Recipe brings up GUI but without the axis adjustment.
Followed along with your tutorial on YouTube many times with the same result each time.

All other features appear to be working as they should.

**Comment by CreativeMD** [comment]
Could you send me a screenshot?

**Comment by Neuron67** [comment]
I'll get on it right away

**Comment by Neuron67** [comment]
![no axis adjust](https://cloud.githubusercontent.com/assets/24964976/23340858/f3229110-fc13-11e6-843f-87c8476be56f.PNG)
If I click save I get a crash.

**Comment by CreativeMD** [comment]
which version are you using?
Can you send me your log file?

**Comment by Neuron67** [comment]
1.11.2 right now but same result with 1.10.2
will get the log. May take another few min. as It is another computer that is offline

**Comment by Neuron67** [comment]
[crash-2017-02-26_11.13.30-client.txt](https://github.com/CreativeMD/LittleTiles/files/802048/crash-2017-02-26_11.13.30-client.txt)

**Comment by CreativeMD** [comment]
Oh ... i'm gonna release a pre-release of v1.4.0 in a few hours. That should fix it, but for now you can download it here:
https://cdn.discordapp.com/attachments/256109634769780737/283729265193779200/LittleTiles_v1.4.0-pre4_mc1.11.2.jar

**Comment by Neuron67** [comment]
Thanks very much!

**Comment by Neuron67** [comment]
Yessssss. That worked! Thanks again

**Comment by Neuron67** [comment]
You have done a great job with this mod and all of the videos. I will definitely be watching out for any new mods and updates you share.
Anxious to try out the Online Picture Frame mod as well but as I said my gaming computer stays offline for security reasons. I will have to install it on another one.
Thanks and Have a nice day!
