### ISSUE TITLE
Thoughts about a possible fabric version of this mod?

### ISSUE THREAD

**Issue by Jarfeh** [CreativeMD/LittleTiles#351]
Since nobody's asked about it before, is there a possibility for this mod to have a fabric port for newer versions of minecraft?

**Comment by CreativeMD** [comment]
I will stick to forge and yes this question has been asked plenty of times.

**Comment by Jarfeh** [comment]
Where has it been asked? I've checked on curseforge and this github itself, and found no mention of it

**Comment by CreativeMD** [comment]
To be fair not for LittleTiles, but there were a few people on discord and countless comments for AmbientSounds.

My comment above wasn't meant in a rude way, more of a joke.

**Comment by walksanatora** [comment]
you should port to architectury 🙃

**Comment by CreativeMD** [comment]
That wouldn't change anything.

**Comment by walksanatora** [comment]
~~the sisaphean urge to port to architectury and keep on the latest minecraft version~~

**Comment by ayakasuki** [comment]
oh so sad to see the message. I want to support to the fabric very much
