### ISSUE TITLE
[1.12.2] Client crash when using JEI and typing @ti

### ISSUE THREAD

**Issue by ProsperCraft** [CreativeMD/LittleTiles#352]
Crash-
https://gist.github.com/ProsperCraft/89c9d28f89e3532884ac9a58f05bf22c
LittleTiles_v1.5.0-pre199_14_mc1.12.2
CreativeCore_v1.10.0_mc1.12.2

Modpack- https://www.curseforge.com/minecraft/modpacks/ancient-towncraft

**Comment by CreativeMD** [comment]
Update CreativeCore, this issue should be fixed already.
