### ISSUE TITLE
Crash when triggering new Door Activator

### ISSUE THREAD

**Issue by Nonsanity** [CreativeMD/LittleTiles#353]
I built two sliding door objects, placed them in position and added some tiles at the base to act as a frame. I used an advanced recipe to copy the whole thing, set it to be a door activator and selected the two sub door checkboxes. I placed a copy of this structure in the world and clicked it. The doors slid open, then the game froze and crashed.

Crash log:
    https://pastebin.com/w0WuDY1q

Version:
    LittleTiles_v1.5.0-pre199_14_mc1.12.2.jar
    CreativeCore_v1.10.1_mc1.12.2.jar

The remaining mods from the All the Mods 3 Remix pack, release version 1.5.4. This was in single player—I have not tested the same thing on a server.

**Comment by CreativeMD** [comment]
That is very very weird. You graphic card is not able to use this function, but vbo are still enabled and in use. The only way to fix it is to disable the smooth transition feature in the config (it's called `uploadToVBODirectly`).

**Comment by Nonsanity** [comment]
I changed the rendering option in the client config:
    "uploadToVBODirectly": false

And tried activating the door, but it crashed again:
    https://pastebin.com/RpMPZMzm

This is on a Mac:
    2.9 GHz Quad-Core Intel Core i7
    16 GB 2133 MHz LPDDR3
    Radeon Pro 460 4 GB

I also updated to the following versions:
    LittleTiles_v1.5.0-pre199_15_mc1.12.2.jar
    CreativeCore_v1.10.3_mc1.12.2.jar

**Comment by CreativeMD** [comment]
You can configure it in game using the mod options menu or the `littletiles-client.json`. You probably used the old `littletiles.cfg` file which is obsolet.

**Comment by Nonsanity** [comment]
That was the json file I edited. I've also confirmed the uploadToVBODirectly is set to false through the in-game mod options. Activating the door still crashes.

Are there any tests I can do to aid in a solution?

**Comment by CreativeMD** [comment]
What does it say in the ingame mod config?

**Comment by CreativeMD** [comment]
The newest version should fix your issue. The config was ignored for some reason. Sorry for the inconvenience.

**Comment by Nonsanity** [comment]
It does fix the crash.
