### ISSUE TITLE
Crashing When ALT TABBED

### ISSUE THREAD

**Issue by CitrusHappy** [CreativeMD/LittleTiles#357]
This crash occurs about 30 seconds or less after you ALT TAB out of modded minecraft. We also have the borderless windowed mod that we use and that was turned on at the time of this crash.

***
Both same crash, different logs

https://paste.dimdev.org/irajiqahul.mccrash

https://paste.dimdev.org/xivibeyeci.mccrash

**Comment by CreativeMD** [comment]
Should be fixed in the newest version. Thanks for reporting this issue!
