### ISSUE TITLE
Issue with using any Export

### ISSUE THREAD

**Issue by SouthernPixel** [CreativeMD/LittleTiles#358]
I have tried using several different "Exports" and every export I try keeps giving me a crash every time I paste it in. I have already updated Littletiles and Creativecore so I know that's not why it isn't working. Everything in Littletiles works except for the exporter. 

Here is the crash report.
https://paste.dimdev.org/afiribuweh.mccrash

**Comment by CreativeMD** [comment]
This should be fixed in the newest CreativeCore version, make sure to update it!
