### ISSUE TITLE
Falling through platform that is 2 blocks thick?

### ISSUE THREAD

**Issue by ricey125** [CreativeMD/LittleTiles#359]
[crash-2020-03-19_20.20.33-client.txt](https://github.com/CreativeMD/LittleTiles/files/4357889/crash-2020-03-19_20.20.33-client.txt)
(SEE BELOW)

Version is LittleTiles_v1.5.0-pre199_17_mc1.12.2.jar

I have an advanced door that acts as an elevator, and when it stops going down the floor of the elevator continues going down another two blocks. I can stand on the floor until its needs to travel that next two blocks down. I have a video of it but GitHub will not let me post it. The platform itself is also two blocks thick.

NOTE: It works perfectly fine if I start it 3 blocks off the Y axis (in the advanced door) but won't work if I instead start at 0 and go -3 on the y-axis. I don't want it teleporting 3 blocks up for it to work.

(BELOW) This is a crash report when I try and create a door activator to just activate the two elevators at once instead of trying it out with the advanced door.

**Comment by CreativeMD** [comment]
This can happen, you can make the advanced door stay animated to fix it (but this affects performance a little more).
