### ISSUE TITLE
Freeze error

### ISSUE THREAD

**Issue by Dec0ded1** [CreativeMD/LittleTiles#360]
The game freezes when a custom door tile is closed, not during the animation, but at the transition point from entity to tile. I have yet to test stay_animated as a possible fix.

Edit: stay_animated fixed the error, recommend adding that to the troubleshooting log.

**Comment by CreativeMD** [comment]
This issue should be fixed in the newer LittleTiles versions. Also make sure to update CreativeCore as well (there were plenty of issues).
