### ISSUE TITLE
Little tiles bug

### ISSUE THREAD

**Issue by donutnotnut** [CreativeMD/LittleTiles#361]
When open setting with chisel tool and trying to select a block minecraft crashes.
here is crash report:
[crash-2020-03-22_13.56.24-client.txt](https://github.com/CreativeMD/LittleTiles/files/4365156/crash-2020-03-22_13.56.24-client.txt)
All mods were updated today 10 minutes ago.

**Comment by CreativeMD** [comment]
Fixed in the newest version of CreativeCore.
