### ISSUE TITLE
Game crashed during the starting process

### ISSUE THREAD

**Issue by Cankuna08** [CreativeMD/LittleTiles#363]
I just installted the newest version of CC and LT and now my game crash during the starting process. 
Thanks for helping me out :) 

[crash-2020-03-23_19.39.43-client.txt](https://github.com/CreativeMD/LittleTiles/files/4371438/crash-2020-03-23_19.39.43-client.txt)

**Comment by CreativeMD** [comment]
You have to update OnlinePictureFrame.
