### ISSUE TITLE
Request for authorization to transfer youtube videos to bilibili (China)

### ISSUE THREAD

**Issue by EdgewalkerBlue** [CreativeMD/LittleTiles#366]
There are many MC Chinese players who want to use LittleTiles to create richer details for their world, but they are struggling to use this tool well, and have repeatedly asked me to do video explanations, but I have not been able to do so because of my working time. As a commentary video, I hope to carry your video on youtube to bilibili for the convenience of MC Chinese players, can you? It would be better if you could carry videos of your other mods

Thanks!

**And my EN is not very good, the following is Chinese**

现在有好多ＭＣ中国玩家想使用LittleTiles去为他们的世界创造更丰富的细节，但苦于不能很好的使用这个工具，多次请求我做视频解说，但由于我的工作时间问题一直没能有时间做解说视频，现希望能搬运你在youtube上的视频去bilibili，方便MC中国玩家，可以吗？如果可以搬运你的其他mod的视频那就更好了

My bilibili url:[Edgewalker_Blue](https://space.bilibili.com/17916561)

**Comment by CreativeMD** [comment]
Yes, you do have the permissions to reupload my showcase videos to bililbili!
