### ISSUE TITLE
Cannot see the little workbench

### ISSUE THREAD

**Issue by Liiw** [CreativeMD/LittleTiles#367]
Hello!

Using:
 LittleTiles_v1.5.0-pre199_19_mc1.12.2,
 CreativeCore_v1.10.9_mc1.12.2

also using OnlinePicFrame_v1.4.35_mc1.12.2

The little workbench is nowhere to be found in JEI or creative tab. I am hosting a private server and pack and after downgrading to the previous versions I had installed:

LittleTiles_v1.5.0-pre198_mc1.12.2
CreativeCore_v1.9.90_mc1.12.2
OnlinePicFrame_v1.4.31_mc1.12.2

I had it working again. I'm not entirely sure if it is perhaps something to do with OnlinePicFrame?

**Comment by CreativeMD** [comment]
I don't know why but the Workbench is not visible in JEI, you have to craft it or get it from the creative menu.
