### ISSUE TITLE
Suggestion: add redstone activation for doors

### ISSUE THREAD

**Issue by DelviousCrafts** [CreativeMD/LittleTiles#368]
Minecraft doors have activation by redstone. In my testing I have found that doors made by little tiles do not react to redstone in any way. Perhaps consider opening doors when a redstone signal is recieved to allow for automated door opening.

**Comment by Dushess** [comment]
First we need Redstone update, WIP, please wait.

**Comment by CreativeMD** [comment]
Redstone is in the works, more information can be found on discord.
