### ISSUE TITLE
[1.11.2][LT-1.4.3] Rendering issues with tiled blocks.

### ISSUE THREAD

**Issue by starg09** [CreativeMD/LittleTiles#37]
[Visualization of the issue](https://gfycat.com/SimplisticWeirdBluejay)

Seems like all blocks tiled with any tool from the mod doesn't render when placed in-world...

Versions used:

* Forge 2258
* CreativeCore 1.6.27
* LittleTiles 1.4.3

**Comment by CreativeMD** [comment]
Have you enabled vbo?

**Comment by starg09** [comment]
Yes.

**Comment by CreativeMD** [comment]
If you hold F3+C for 6 seconds you will force a crash. Could you send me this crash log?

**Comment by starg09** [comment]
Sure, give me a second!

**Comment by starg09** [comment]
http://paste.feed-the-beast.com/view/152036d3

(Created a new superflat world, converted a lime wool block into a 16x16x1 tile (think like a carpet), placed it in world and forced the crash while looking at it with an empty hand)

**Comment by CreativeMD** [comment]
Ok, thank you. I will try to reproduce this issue.

**Comment by starg09** [comment]
Ok, great. Thanks! ^^

~~PS, a bit off-topic: Could I contact you about something over discord/twitter?~~ nvm, just saw we share a discord server, can contact you through there :P

**Comment by CreativeMD** [comment]
Seems like this issue appears of you run minecraft without Optifine. Sorry, but i was rather busy the last days. Hope i can fix it tomorrow.

**Comment by CreativeMD** [comment]
Ok, uploaded the newest version, it should be fixed now. If not reopen the issue. Thanks for reporting. Sorry that it took so long.
