### ISSUE TITLE
Crash error.

### ISSUE THREAD

**Issue by xombiekilla** [CreativeMD/LittleTiles#371]
[crash-2020-04-05_00.26.13-client.txt](https://github.com/CreativeMD/LittleTiles/files/4432960/crash-2020-04-05_00.26.13-client.txt)

I have unfortunately received this crash report. Judging by what its saying, this would imply that there're missing crucial files that should be in this mod but aren't. This is the latest version of Little tiles and Creative Core. It worked before in earlier versions, but now there seems to be this problem. You might want to look into this for your work.

**Comment by CreativeMD** [comment]
Update OnlinePictureFrame, this should fix the issue.
