### ISSUE TITLE
Shader causing sky to turn black with thin blocks

### ISSUE THREAD

**Issue by Daphadoo** [CreativeMD/LittleTiles#372]
https://imgur.com/Be0Tkui
I'm using SEUS, I want to use other shaders but I don't like how any other ones look. Not sure if its a problem with this shader or if there is a setting I can change to help this?

**Comment by CreativeMD** [comment]
Which version of SEUS are you using. Furthermore it would be very helpful to see what you actually build with LittleTiles. I have never seen this bug before.

**Comment by CreativeMD** [comment]
Any news?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists make sure to contact me again with more information.
