### ISSUE TITLE
Recipes Wont Place

### ISSUE THREAD

**Issue by CamBDragon** [CreativeMD/LittleTiles#373]
I am in my server with some friends and this mod is in our modpack but when i try to make door into a working one it works fine until i craft it from a recipe to an item and for some reason i can not place it anywhere it was working before but now its not it be nice to get some help or some advise
![Untitled](https://user-images.githubusercontent.com/63504144/79045223-e2cb3080-7c01-11ea-9297-eede0b8c01b1.png)

**Comment by CreativeMD** [comment]
Maybe the area is protected?
Which version are you using?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still occurs, make sure to provide more information.
