### ISSUE TITLE
Issue with doors

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#378]
![2E707A0A-5B75-4F45-9863-5B28F3431466](https://user-images.githubusercontent.com/63751495/79387784-8a32c500-7f6c-11ea-86d8-3a0e46d8d3d6.png)
![7B32D9A2-CE41-49B7-84EE-4BA8F5EB8CB2](https://user-images.githubusercontent.com/63751495/79387787-8acb5b80-7f6c-11ea-8bf8-183b598a6104.png)

 I cannot create a door with the recipe on my server. When I click on the save button I don’t see the door. I can’t place it on my server. I tried to place it in single player but it doesn’t work either. So I decided to remove the other mods and keep only little tiles and creative core but it still doesn’t work. I have the latest version of Forge in 1.12.2. I tried different versions of the mod as well but nothing works. Thank you in advance for your answer.

**Comment by CreativeMD** [comment]
You are using the ordinary recipe. You need a workbench in order to craft it. You can't place the recipe itself. If you use the advanced recipe you can place it directly. You might want to check out the wiki for more information: https://github.com/CreativeMD/LittleTiles/wiki/Advanced-Recipe
