### ISSUE TITLE
Render Crash?

### ISSUE THREAD

**Issue by BSKCorp** [CreativeMD/LittleTiles#38]
Forge 1.11.2-13.20.0.2279
MC 1.11.2
Little Tiles 1.4.6

Crash - https://pastebin.com/d5iSZMXp

**Comment by CreativeMD** [comment]
Consistent issue or does it happen from time to time?

**Comment by BSKCorp** [comment]
Time to Time.

**Comment by CreativeMD** [comment]
Thanks for reporting. This was really really important to fix. Had to redesign some parts of my mod, but now everything should be fixed. Just download the newest version of LittleTiles.

**Comment by BSKCorp** [comment]
Awesome, thanks for the fix. Having a lot of fun with your mod btw XD
