### ISSUE TITLE
Disappearing Door

### ISSUE THREAD

**Issue by Dragoonat** [CreativeMD/LittleTiles#382]
Hi, some of my sliding doors disappear when moving back to their original position. Any idea how to fix this? They previously worked and now don't since I updated to the latest version.
Again not all doors but many doors/ Once I open them again they can be seen. But when I close (original position) they disappear. I can hit it and break it and place a new door but the problem persists with the new door.

Thanks 

Dragoonat

**Comment by CreativeMD** [comment]
This issue has been reported already: https://github.com/CreativeMD/LittleTiles/issues/374
I hope I can fix it eventually.

**Comment by Dragoonat** [comment]
Okay thanks a lot! You have created an amazing mod!
