### ISSUE TITLE
Can't destroy sliding door and the door texture flashes

### ISSUE THREAD

**Issue by Avocado-Boi** [CreativeMD/LittleTiles#383]
I am playing Minecraft 1.12.2 and I have these mods active

chisels&bits ver14.31
creativecore ver1.9.74
flatcoloredblocks ver6.7
and littletiles ver1.5.0-pre180

I used a violet block #1038, made it somewhat thin, and saved the recipe as a sliding door, the sliding door was flashing white whenever it was moving, I then changed the recipe to always stay animated and now it still is flashing and I can't destroy it

![2020-04-17_22 44 52](https://user-images.githubusercontent.com/59325784/79626465-58516800-80fe-11ea-8cd2-d48666e64ea8.png)
![2020-04-17_22 45 05](https://user-images.githubusercontent.com/59325784/79626467-5ab3c200-80fe-11ea-9d4c-f2b7d44aa89c.png)

is there a way to fix this?

**Comment by Avocado-Boi** [comment]
I got rid of the sliding door by removing the mod, going back in the game, then back out, then adding the mod and going back in the game again, it's gone now but the flashing is still there

**Comment by kirokadura** [comment]
First of all, I suggest updating both CreativeCore and LittleTiles. Both are massively outdated. After doing that, tell us if the issue persist.

**Comment by Avocado-Boi** [comment]
I updated creative core to 1.10.10 and littletiles to 1.5.0 199_19, the problem is still there, and now when I try to place the door its not directly in the centre of my crosshair

**Comment by kirokadura** [comment]
Export the structure and post it here then.

**Comment by Avocado-Boi** [comment]
{tiles:[{boxes:[[I;0,0,0,16,16,9],[I;0,16,0,16,32,9],[I;0,32,0,16,48,9],[I;0,48,0,16,64,9]],tile:{block:"flatcoloredblocks:flatcoloredblock64:14"}}],min:[I;0,0,0],size:[I;16,64,9],count:4,structure:{duration:50,interpolation:0,distance:64,activateParent:0b,id:"slidingDoor",events:[],disableRightClick:0b,direction:1}}

**Comment by CreativeMD** [comment]
Structure is absolutely fine. Your world might be bugged, it would make more sense to upload that. Anyway, there will be a new littletiles version fairly soon (might fix your issues as well).

**Comment by CreativeMD** [comment]
New version is out now. Would be very happy if you could try it out.

**Comment by Avocado-Boi** [comment]
yeah my world probably is bugged, I updated to the new version it seems to be working well, thank you

**Comment by CreativeMD** [comment]
Nice!
