### ISSUE TITLE
LittleTiles crash, error when loading 'cable'

### ISSUE THREAD

**Issue by Ad-Blokker** [CreativeMD/LittleTiles#384]
A user in our discord has a problem with LittleTiles when joining a server.
The user is playing the modpack named **Tekxit 3 v.0972** which is using **LittleTiles v1.5.0-pre199_19**.
The user has **Java 1.8.0_251** installed and gets the following error:

**Client log**
Last part of the log: [https://hastebin.com/wanuputido.md](https://hastebin.com/wanuputido.md)
Full log: [https://www.dropbox.com/s/m3wr54z97rkc963/latest_3.log?dl=1](https://www.dropbox.com/s/m3wr54z97rkc963/latest_3.log?dl=1)

**Server Log**
[https://hastebin.com/aqeropajah.css](https://hastebin.com/aqeropajah.css)

Maybe the recent commits have something to do with it?
https://github.com/CreativeMD/LittleTiles/commit/e550f003deb904d7c49b475c1881cbf4886cedce
https://github.com/CreativeMD/LittleTiles/commit/58112b407cc4c6c26900407421943ce34022ad79

Maybe you know what it is. This user is the only one having this problem with joining this server.
Modpack has been reinstalled, java has been reinstalled and RAM allocation has been changed up and down.
Other servers result in the same problem.

**Comment by kirokadura** [comment]
We'll have to wait on CreativeMD's input on this, but the changes related to both commits were not released yet, as the lastest version of LittleTiles is from March 23th, so unless he somehow has an unreleased version, it's probably not that.

**Comment by CreativeMD** [comment]
This is not a crash, just a loading error. Can be completely ignored and has nothing to do with the problem.
I can't even see a connection problem in the log.

**Comment by Ad-Blokker** [comment]
Hmmm his client just freezes and closes at the end that is the strange thing about it. I know it is not a crash but this is the last part of the log and then it just stops

**Comment by CreativeMD** [comment]
Does it still happen if LT is not installed?

**Comment by Ad-Blokker** [comment]
The user in question didn't respond anymore. I will shoot him a DM and if there is no response in that, I will close the issue

**Comment by CreativeMD** [comment]
I will close this issue for now. The cable error should also not occur anymore. If it still happens and can be clearly connected to littletiles let me know and I will reopen the issue.
