### ISSUE TITLE
Slope Connected Texture Issue

### ISSUE THREAD

**Issue by Sgt2awsome4u** [CreativeMD/LittleTiles#385]
![2020-04-18_22 58 40](https://user-images.githubusercontent.com/7917847/79679109-9a46e080-81c8-11ea-92c7-2d3a09ddd849.png)

The connected texture for Chisel's Factory Blocks don't connect on all sides when using a slope.  I've tried using a normal block and a LittleTile block, but neither connected on the left side or the top of the right side.

For reference: I'm playing The 1.12.2 pack w/ LittleTiles added.  I do not have Connected Textures Mod or Optifine installed.  In the screenshot, i'm facing Southwest, exactly 45° towards positive Z.

**Comment by CreativeMD** [comment]
Sorry, but this cannot be fixed. The slope is basically a face of the block rotated around.
![](https://i.imgur.com/zZhWWNS.png)
As you can see there is no block to connect to on this side. You could place the slope differently to compensate it (make it cross the block grid). I know it's not really intuitive, but I just use the code of chisel and that one is not designed for slopes.

**Comment by Sgt2awsome4u** [comment]
I understand, thanks for letting me know!  I'll try what you said or just use a different block.
