### ISSUE TITLE
Minecraft Launcher Crashing on Hitting Play

### ISSUE THREAD

**Issue by Ironeagle675** [CreativeMD/LittleTiles#388]
I have downloaded LittleTiles_v1.5.0-pre199_19mc1.12.2.jar and I have Forge version 1.12.2-forge1.12.2-14.23.5.2838. But when I click play my launcher crashes and I'm presented with this error message:
![Crash report](https://user-images.githubusercontent.com/64060100/79828770-fc276600-83d3-11ea-8626-80d720434f7e.png)

**Comment by CreativeMD** [comment]
You forgot to install CreativeCore.
