### ISSUE TITLE
Crash with SpongeForge

### ISSUE THREAD

**Issue by DMCK96** [CreativeMD/LittleTiles#389]
Crashing on server start with the latest version of SpongeForge.

**SpongeForge:** 1.12.2-2838-7.2.1-RC4013
**Forge:** 1.12.2-14.23.5.2847
**LittleTiles:** v1.5.0-pre199_19_mc1.12.2

Apologies if this isn't caused by LittleTiles but it was the last mod to load in my console before the crash.

[debug.log](https://github.com/CreativeMD/LittleTiles/files/4522021/debug.log)

**Comment by CreativeMD** [comment]
Not sure if this is really an issue of my mods. Can you try it with only CreativeCore, LittleTiles and SpongeForge installed?

**Comment by DMCK96** [comment]
You're right, apologies! I'll close the task.

**Comment by CreativeMD** [comment]
Hope you find the mod causing the issue.
