### ISSUE TITLE
Can not open game

### ISSUE THREAD

**Issue by Nidero** [CreativeMD/LittleTiles#39]
No crash report was generated, so crash reports could not be provided
It is not clear that LittleTiles has a conflict with what mod
Although there is no crash report but i think game output should have provided information
Game output：
Exception in thread "main" [11:28:02] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: com/creativemd/littletiles/LittleTilesTransformer  [11:28:02] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at com.creativemd.littletiles.LittlePatchingLoader.getASMTransformerClass(LittlePatchingLoader.java:18)  [11:28:02] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:130)  [11:28:02] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)  [11:28:02] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)  [11:28:02] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.ClassNotFoundException: com.creativemd.littletiles.LittleTilesTransformer  [11:28:02] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)  [11:28:02] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at java.lang.ClassLoader.loadClass(Unknown Source)  [11:28:02] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at java.lang.ClassLoader.loadClass(Unknown Source)  [11:28:02] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     ... 4 more  [11:28:02] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoClassDefFoundError: com/creativemd/creativecore/transformer/CreativeTransformer  [11:28:02] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at java.lang.ClassLoader.defineClass1(Native Method)  [11:28:02] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at java.lang.ClassLoader.defineClass(Unknown Source)  [11:28:02] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at java.security.SecureClassLoader.defineClass(Unknown Source)  [11:28:02] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)  [11:28:02] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     ... 6 more  [11:28:02] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.transformer.CreativeTransformer  [11:28:02] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)  [11:28:02] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]:     at java.lang.ClassLoader.loadClass(Unknown Source) 

Modlist
OptiFine_HD_U_D7
InventoryTweaks-1.61-58
AkashicTome-1.0-5
AutoRegLib-1.0-2
Botania r1.9-341
Morph-o-Tool-1.0-12
Psi-r1.0-42
CustomSkinLoader_1.10-14.6a
Durability Show-1.9.4-3.1.1
Baubles-1.10.2-1.3.9
Calculator-1.10.2-3.2.1
Chisel-MC1.10.2-0.0.9.15
chiselsandbits-12.12
compatlayer-1.10-0.2.5
CorrelatedPotentialistics-1.1.3(1)
EnderCore-1.10.2-0.4.1.65-beta
EnderIO-1.10.2-3.1.180
ExtraBitManipulation-1.10.2-2.3.4
FluxNetworks-1.10.2-1.2.2
HammerCore_1.10.2-1.4.8
jei_1.10.2-3.14.5.406
LittleTiles v1.4.3 mc1.10.2
malisiscore-1.10.2-4.4.0
malisisdoors-1.10.2-5.2.0
mcjtylib-1.1x-2.3.11
MCMultiPart-1.4.0-universal
mod_voxelMap_1.6.21_for_1.10.2
OptiFine_1.10.2_HD_U_D6
PracticalLogistics2-1.10.2-2.0.1
PSIonicUpgrades-r1.15
rftools-1.1x-5.91
rftoolsctrl-1.1x-1.6.6
rftoolsdim-1.1x-4.55
SolarFluxReborn_1.10.2-2.16r
SonarCore-1.10.2-3.2.6
Surge-1.10.2-1.1.0.71
UBCOres-2.1.0
UndergroundBiomesConstructs-1.10-1.0-v.18
WailaHarvestability-mc1.10.2-1.1.9
Wawla-1.10.2-2.3.1.214

**Comment by mar-x1** [comment]
make sure to have creative core installed (same symptoms, installing coremod fixed it)

-creativecore
(sorry to necro, but google led me here and because this post was no help, I am posting the solution now)
