### ISSUE TITLE
Little Hammer Infinite Block deletion and protection plugin bypass 

### ISSUE THREAD

**Issue by frostie22** [CreativeMD/LittleTiles#390]
The little hammer can delete all blocks in what seems to be an infinitely scaling area.

![2020-04-24_14 07 15](https://user-images.githubusercontent.com/49459252/80211900-32b4e900-863f-11ea-96d1-5f3f229891fc.png)
![2020-04-24_14 07 31](https://user-images.githubusercontent.com/49459252/80211901-347eac80-863f-11ea-9643-a910b3f8c854.png)
![2020-04-24_14 07 36](https://user-images.githubusercontent.com/49459252/80211910-3b0d2400-863f-11ea-9495-54c3b93d2a1e.png)

Behind the spruce testing cube you can see vast damage, done by normal survival players

this is achievable in survival mode and players can bypass protection plugins deleting anything whatsoever 

It also creates Null blocks when turning leaves into little tiles and creates random textureless xray style blocks

version LittleTiles_v1.5.0-pre199_19_mc1.12.2

**Comment by kirokadura** [comment]
**1-** The following settings can be used to limit the max size of selection for the hammer and chisel, you just need to edit the "littletiles.json" file (for server and client).

 "survival": {
    **"strictMining": false,
    "limitEditBlocksSurvival": false,
    "maxEditBlocks": 10,**
    "highestHarvestTierSurvival": 10,
    "editUnbreakable": false,
    **"limitPlaceBlocksSurvival": false,
    "maxPlaceBlocks": 10,**
    "minimumTransparency": 255,
    "dyeVolume": 2.0
  }

Just set the tags to true and set a limit. 

**2-** To allow blocks such as leaves and grass to render when chiseled, you need to enable Mipmap by setting it to any level. 

**3-** We'll investigate the rendering issues.

**4-** What protection plugin are you using?

**Comment by clienthax** [comment]
The protection plugin is griefdefender, it's likely that you are not firing forge events to do block changes or are modifying the world in a non standard way for it to bypass

**Comment by CreativeMD** [comment]
LittleTiles fires block events. Looks like griefdefender is a plugin for spigot (that obviously doesn't work with forge events). 

You can also use the command /cmdconfig to configure all the settings ingame.

The rendering issues might be fixed in the upcoming pre-release.

I will close this issue for now, if you have any sorts of rendering issues, make sure to open a new one.

**Comment by clienthax** [comment]
Grief defender is a spigot and sponge plugin, I will look into this on that side and see what's going on

**Comment by CreativeMD** [comment]
If you post an issue there, make sure to link it here, so I can join the conversation.

**Comment by clienthax** [comment]
> If you post an issue there, make sure to link it here, so I can join the conversation.

I'm going to check if sponge is catching the events properly first, Where exactly is LittleTiles posting the event for the hammer?

I'm putting testing this on hold as your projects are near impossible to test against sponge in a dev environment due to gradle files being missing etc.

**Comment by CreativeMD** [comment]
Source can be found here: https://github.com/CreativeMD/LittleTiles/blob/1.12/src/main/java/com/creativemd/littletiles/common/action/block/LittleActionDestroyBoxes.java#L163

Yeah, I'm sorry for my setup, I don't know how I can have multiple mods in one eclipse workbench and using just gradle. Even did a video which explains how I do it: https://www.youtube.com/watch?v=7Ahshi_QjM4

**Comment by clienthax** [comment]
Does it not let you import them as submodules like intellij does?

**Comment by CreativeMD** [comment]
My setup is not pretty as I said. Unfortunately I don't know how to do it better. If you have any tutorial let me know.
