### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by WillisShek** [CreativeMD/LittleTiles#391]
[Crash Log #1](https://paste.dimdev.org/zinevosomi.mccrash): happened when I placed an advanced door structure with 4 doors as children.
[Crash Log #2](https://paste.dimdev.org/ipakajezeg.rb): happened when I right-clicked on an advanced door.

LittleTiles version: LittleTiles_v1.5.0-pre199_21_mc1.12.2

Only the client was crashed. The server was still running.

Thanks

**Comment by CreativeMD** [comment]
This issue should be fixed in the newest version!
