### ISSUE TITLE
Issue: Sloped concrete shaded incorrectly

### ISSUE THREAD

**Issue by lqkhoo** [CreativeMD/LittleTiles#392]
Concrete (of any type) created using the slope option from the little chisel tool renders with a jarring shading gradient. I've included sloped blocks from ArchitectureCraft [(link)](https://www.curseforge.com/minecraft/mc-mods/architecturecraft-tridev) as comparison.

[Screenshots](https://imgur.com/a/xqUr1Xx) in the following order:
- List of mods
- Without optifine
- With optifine

ArchitectureCraft blocks form the closer strip, and LittleTiles blocks are next to it. Block types from closest to farthest: concrete, light grey concrete, coal, quartz block. I've included the latter two only for contrast. Interestingly enough, the problem only seems to affect concrete.

The only resource pack I'm using [(link)](https://www.curseforge.com/minecraft/texture-packs/clear-glass-pack) does not affect concrete, and I'm using default shaders in the example.

Thanks, and keep up the great work!

**Comment by CreativeMD** [comment]
Remove Optifine and it will work. Sorry, but there is nothing I can do about it.

**Comment by lqkhoo** [comment]
I dug a little deeper: Setting smooth shadows to off completely removes the checkering effect, with or without Optifine.

Notice that the following is running Optifine with connected glass textures. I tested without Optifine too; it looks good too. However, smooth shadows to off displays hard borders between blocks with different light levels, so... it's still not really an option.

![2020-05-01_17 13 44](https://user-images.githubusercontent.com/2603573/80795546-5f34ac00-8bcf-11ea-86dd-b6c769bc058d.png)

I'm not sure if this information changes anything at all, but thanks for looking into the issue anyways.

**Comment by CreativeMD** [comment]
Yeah same with some shaders. I really hope those things don't occur in 1.15 anymore.

**Comment by Vodulm** [comment]
Just in case, same thing happens with non-slopes, without Optifine:
![2020-10-09_01 57 35](https://user-images.githubusercontent.com/73194834/96640166-7442fa00-132b-11eb-803b-5d3617488ebd.png)

But only if tiles are next to normal blocks:
![2020-10-09_03 26 01](https://user-images.githubusercontent.com/73194834/96640376-bf5d0d00-132b-11eb-9f9f-db99fe0fc5bd.png)
if ground is tiles too:
![2020-10-09_03 26 15](https://user-images.githubusercontent.com/73194834/96640425-cf74ec80-132b-11eb-9447-05cea4cf22e1.png)

**Comment by Vodulm** [comment]
So as it isn't possible to fix, can you add an option (in chisel and adv. recipe) to keep full block sized tiles as tiles as a workaround?

**Comment by CreativeMD** [comment]
Not entirely sure what is going on, but there are some issues which will be fixed in the next version.
