### ISSUE TITLE
Changes made to children are not saved

### ISSUE THREAD

**Issue by kirokadura** [CreativeMD/LittleTiles#393]
Reported by user **SF1NX** on Discord.

**LittleTiles version:** LittleTiles_v1.5.0-pre199_23_mc1.12.2
**CreativeCore version:** CreativeCore_v1.10.12_mc1.12.2

**Description:** Changes made to settings on Childrens in the Advanced Recipe via the hierarchy selector are not being saved. Changes made to the Parent structure are saved normally.

**Steps to reproduce:** 

1. Use the export provided;
2. Change the settings on one of the handles (children);
3. Save the recipe;
4. Open the recipe again. The values are back to their previous value.

[my_crappy_door.txt](https://github.com/CreativeMD/LittleTiles/files/4567833/my_crappy_door.txt)

**Comment by CreativeMD** [comment]
Fixed in the newest version
