### ISSUE TITLE
Cannot remove window made in previous version.

### ISSUE THREAD

**Issue by PurpleIvaylo** [CreativeMD/LittleTiles#395]
I haven't used LittleTiles in a while, but I remember that this window got glitched last time I did use it. Now I have installed the lasted LittleTiles and I tried using the wrench, going in creative and break this window, and nothing.
![2020-05-03_01 21 48](https://user-images.githubusercontent.com/57375359/80893746-c3de2c80-8cdd-11ea-8153-f52d787fa519.png)
This is what happens when I try to open the windows, and when I try to break them i finish to break the parts but nothing changes.

**Comment by CreativeMD** [comment]
The wrench should work, unless it works on server side. Which version are you using?

**Comment by PurpleIvaylo** [comment]
I am using v.1.5.0-pre199_21. And it is on a server.

**Comment by CreativeMD** [comment]
Please update there were some issues in this version.

**Comment by PurpleIvaylo** [comment]
I have put the newest version (pre199_25) and managed to fix the window that just broke out of nowhere ***different one, used it for my house*** but the one I sent pics with, didn't let me break it after breaking a few parts of it.
![2020-05-05_03 06 39](https://user-images.githubusercontent.com/57375359/81026024-684ca400-8e81-11ea-8455-98c499d33b19.png)
![2020-05-05_03 06 45](https://user-images.githubusercontent.com/57375359/81026025-697dd100-8e81-11ea-842c-a8d2bdc4a08a.png)
Tried fixing it with the wrench but didn't work after the few broken pieces.

**Comment by PurpleIvaylo** [comment]
I closed this by mistake. ^^'

**Comment by CreativeMD** [comment]
Sometimes you can only remove certain parts. Try to break different parts. Once you have removed them you can log in and out again to remove the rest. I had this issue as well, all doors placed in the version before have it.

**Comment by PurpleIvaylo** [comment]
I have tried twice but still unable to remove it. Maybe I have missed a part of it that can break though. I will try again.

**Comment by CreativeMD** [comment]
Maybe use worldedit to remove the blocks or the setblock command of minecraft. If you want to you can also send me the world, I can fix it and then send it back to you.

**Comment by PurpleIvaylo** [comment]
I finally remove it using world edit! Thank you for the help!
