### ISSUE TITLE
Left hand rotations for various tools inconsistent with right hand

### ISSUE THREAD

**Issue by DoomRater** [CreativeMD/LittleTiles#397]
I'm a lefty so I noticed the hammer was seemingly rotated wrong in the left hand when held.
![2020-05-06_14 29 18](https://user-images.githubusercontent.com/4010432/81214582-0fc2f700-8fa6-11ea-9b54-b7518b8789e3.png)
The little saw's rotation is also different, but I dunno it feels good in the left hand as opposed to the rotation in the right hand.  In fact, might wanna take a sweep through all the little tools for version 1.5.0. A lot of the tools do that.
Little Glove looks the same, as does the Little Chisel.

**Comment by CreativeMD** [comment]
Any other mods installed? This is definitely not normal and has never happened before.

**Comment by DoomRater** [comment]
I have reproduced with only Littletiles 1.5.0, CreativeCore 1.9.9, and JEI installed. This doesn't seem to be affected by which hand is main hand.  Edit: this is pre199_18_1.12.2, I see there's a pre199 available now that I didn't check for before filing.

Oddly enough Noobanidus had a similar rotation issue when he was adding some new tools in Roots 3.  It's probably just some numbers that need to be flipped when rendering in the left hand.

**Comment by DoomRater** [comment]
https://imgur.com/a/1PSgKRt
Here's a gallery after checking every tool with LittleTiles 1.5.0-pre199_25_1.12.2 and CreativeCore 1.10.13 for 1.12.2.

**Comment by CreativeMD** [comment]
Just realized you are talking about the off hand. Sorry for my confusion. Is it a real problem? You can't use the tools in the off hand anyway.

**Comment by DoomRater** [comment]
You mistunderstand.
This occurs in the left hand, regardless if the left hand is the main hand or not.  I am left handed, thus left hand IS my main hand.

Edit: There is a misconception floating around modded Minecraft, and I can see exactly how this misconception came about, as well as how hard it can be to actually fix rendering issues when they're done conditionally within an item, but the truth is that main hand != right hand.  If you go into options -> skin customization, inside is an option for which hand is the main hand.  But because lefties are super uncommon, nobody really looks to see if the left handed render works the same.

In this case, the fix is relatively minor- items are being rotated 90 degrees in the wrong direction when translated to the left hand.  You can see this most easily with the little bag. Rotating 90 degrees the other way, as the Little Glove and Little Chisel do, will fix it.

**Comment by CreativeMD** [comment]
I just had to extend a different model. It's fixed in the newest version (released just now). Thanks for reporting this issue!

**Comment by DoomRater** [comment]
On pre199-73, the chisel and glove are still backwards.  Easy enough to see from third person view, where they float.  Did something revert? I remember seeing these fixed.

**Comment by CreativeMD** [comment]
Willl be fixed in the next release.
