### ISSUE TITLE
"/lt-open X Y Z DoorName" Keep Animated does not keep structure name 

### ISSUE THREAD

**Issue by Doc-1** [CreativeMD/LittleTiles#398]
Just learned that the lt-open command has the option to specify which door you want to open based on the name. Which works perfectly without keep animated. But, when I do set each piano key(door) to keep animated it presses all keys in the block area I provide. 
![keys](https://user-images.githubusercontent.com/45431412/81476000-68c8a000-91dd-11ea-93dd-a326f465699a.gif)

**Comment by CreativeMD** [comment]
Oh right, no idea why I did that mistake, but it's definitely fixed now. Just get the newest version. Thank you very much for reporting this issue!

**Comment by Doc-1** [comment]
Thank you very much!
