### ISSUE TITLE
Hammer is, for lack of a better phrase, OVERPOWERED

### ISSUE THREAD

**Issue by TheMightyMcGrew** [CreativeMD/LittleTiles#399]
I shouldnt be able to survival mine an entire mountain with the littletiles hammer. It has absolutely no durability and in some unfortunate events have leveled my entire base because of its innate ability to never forget its last position regardless of swapping tools or logging out of a server/world. A tone down would be appreciated. Maybe a limit to how many tiles/blocks its allowed to break in survival would be a better idea
edit - Also wanted to point out that undo and redo or only good up to so many tiles, after the undo or redo becomes large enough theres a good chance it will misplace a giant cube of whatever block its trying to un/redo or will completely fall short and displace many tiles/block/entities.
P.S. Edit - Aside from all these issues I dont just want to sound like Im complaining and would like to say how much I adore this mod, and how thankful I am that you/you all would be so kind as to develop something so extraordinary for minecraft. Thank you for all the hard work and dedication you put into this <3

**Comment by kirokadura** [comment]
You can set a limit to the hammer and the chisel range in the config.

About the undo/redo issue, we'll look into it. If you find a reliable way to reproduce the problem, it would be a great help.

**Comment by CreativeMD** [comment]
Just type in /cmdconfig navigate to LittleTiles -> Survival. There are plenty of options to limit this tool. If you have requests for more configuration just post them here. Hope that solves your issue.
