### ISSUE TITLE
Little Tiles blocks turn invisible

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#40]
I used LittleTiles to make vertical slabs. Some of the placed slabs are invisible after relogging or reloading the chunk. Which ones is not reproducible. I suspected shaders, but the problem remains after disabling them.

![2017-04-13_01 30 34](https://cloud.githubusercontent.com/assets/22047030/24983978/c3b19bba-1fea-11e7-99aa-c7e85070f829.jpg)

Minecraft: 1.10.2
Forge: 12.18.3.2254
LittleTiles: 1.4.3
CreativeCore: 1.6.26
Optifine: HD U D7

**Comment by CreativeMD** [comment]
This is a known issue and i'm still not really sure what this is happening. Just place a block next to it and it will be rendered. Sorry maybe i will find a way to fix it some day.

**Comment by ghost** [comment]
Placing a block next to it doesn't make it render. The only thing that helps (in my case) is to remove the invisible block and replace it.

**Comment by CreativeMD** [comment]
Do those versions fix it:
https://www.dropbox.com/s/6fhq4766dlm7ot3/CreativeCore%20v1.7.2%20mc1.10.2.jar?dl=1
https://www.dropbox.com/s/p34mzrk2chr2mol/LittleTiles%20v1.4.7%20mc1.10.2.jar?dl=1
https://www.dropbox.com/s/p76go4w4lhhsf7v/OnlinePicFrame%20v1.3.5%20mc1.10.2.zip?dl=1

**Comment by ghost** [comment]
No, the bug is still there. I started a new game, built a little wall with vertical slabs, left the chunk and returned and it looked like this:

![2017-04-17_20 34 48](https://cloud.githubusercontent.com/assets/22047030/25099754/e1d73688-23ad-11e7-96aa-6a4e03976383.jpg)

**Comment by CreativeMD** [comment]
Does this version fix the bug?
https://www.dropbox.com/s/p34mzrk2chr2mol/LittleTiles%20v1.4.7%20mc1.10.2.jar?dl=1

**Comment by ghost** [comment]
Looks good. I quickly tested relogging and leaving the chunk 3 times and the wall is still intact.

**Comment by maxfreestyler** [comment]
Hi I know this was closed off but if anyone is still there I was wondering if you could possibly make this version for 1.12.2 because the version I use of this mod the blocks still turn invisible after I reload the world. Thanks

**Comment by CreativeMD** [comment]
Can you send me a screenshot and a list of mods (including forge version)?

**Comment by maxfreestyler** [comment]
Sorry only just opened my emails hope it’s not to late I’ll open the game up tomorrow and show you and the list of mods I use and the forge version ( I use 1.12.2)

Freestyler Out!😉

**Comment by CreativeMD** [comment]
Don't forget to update everything to the newest version

**Comment by Backoffson** [comment]
I know this is closed, but has he sent you the things yet and are you looking into fixing it?

**Comment by Backoffson** [comment]
Ok i just tried that version that worked for him, didn't work for me, blocks are still invisible, i mean EVERY hammered block is invisble

**Comment by CreativeMD** [comment]
Update CreativeCore and LittleTiles to the newest version and everything should work just fine.

**Comment by Backoffson** [comment]
Alright I try it

**Comment by Backoffson** [comment]
Can you send me a link to the latest download? The website I got the mod from probably wont have it

**Comment by CreativeMD** [comment]
Please only download mods from curseforge ... those other websites are scam.

https://minecraft.curseforge.com/projects/creativecore/files/2544567
https://minecraft.curseforge.com/projects/littletiles/files/2547125

**Comment by Backoffson** [comment]
Thank you very much for the advice

**Comment by Backoffson** [comment]
Thank you, it works just fine now!

**Comment by Backoffson** [comment]
Ok so downloaed it, everyworked fine. Relaunched the game in the morning, all the blocks were invisible again

**Comment by CreativeMD** [comment]
In rare cases this can happen, just place or remove a block or reload the world.

**Comment by Backoffson** [comment]
I'll be sure to try it, also thank you for always responding and caring. Love your mods!

**Comment by Backoffson** [comment]
erm, didn't work, reloaded the world, removed and placed blocks, still invisible

**Comment by CreativeMD** [comment]
Which versions are you using? Optifine and Forge?

**Comment by Backoffson** [comment]
Forge 1.12.2 and Optifine 1.12.2 ULTRA D1

**Comment by Backoffson** [comment]
1.12.2-14.23.2.2652 for the forge version

**Comment by Backoffson** [comment]
I just installed the latest forge version (1.12.2-14.23.2.2654) still invisible. Got any suggestions?

**Comment by CreativeMD** [comment]
Try to remove Optifine and see if it works then. Furthermore can you send me a screenshot of your mods folder?

**Comment by Backoffson** [comment]
Ok it works without Optifine but I can't live without my shaders, any other suggestions?

**Comment by CreativeMD** [comment]
Disable render regions, enable vbos.

**Comment by Backoffson** [comment]
Works now :) thanks!

**Comment by Alexandrou4** [comment]
Hey Creative, i have the same problem of the invisible blocks and i did all you said, but it still invisible the only thing i didnt do is disable optifine but i want the optifine and i also disabled render regions and enabled vbos but it still didnt work, pls help me

**Comment by Alexandrou4** [comment]
these are my mods
![2018-12-15](https://user-images.githubusercontent.com/45903140/50046560-f3a67900-0083-11e9-8cc7-0a612338ab6e.png)

**Comment by Alexandrou4** [comment]
no wait, it works now

**Comment by CreativeMD** [comment]
Just use Optifine E2. LT supports RenderRegions.

**Comment by Alexandrou4** [comment]
i will try

**Comment by RPJOF** [comment]
Hello, I know this post is closed but I have a huge problem with the renderings of my doors. The animation goes well but as soon as it returns to their basic position, they disappear. They are still there but we don't see them!
Here is my info:
JAVA: 14.23.5.2847
Little-tiles:
1.12.2 Pre 199_19
Creative Core:
V1.10.10
Screen of my mods and the bug.
Have a good day!
(I use the command "lt-open" to open my doors!)
![2020-04-11_21 05 00](https://user-images.githubusercontent.com/60546959/79052826-6f451580-7c39-11ea-904a-b3eeb5fdf0cd.png)
![2020-04-11_21 05 10](https://user-images.githubusercontent.com/60546959/79052838-78ce7d80-7c39-11ea-9b29-2844a828f381.png)
![Capture](https://user-images.githubusercontent.com/60546959/79052876-a9161c00-7c39-11ea-8966-46303e51d687.PNG)

**Comment by Alexandrou4** [comment]
wth why did i get this if im not a mod or creator lol

**Comment by Alexandrou4** [comment]
Hola.

Acabo de firmar la petición "Roblox: Remove Adopt-me from ROBLOX!" y pensé
que te podría interesar.

Estamos intentando conseguir 15.000 firmas y necesitamos todo el apoyo que
podamos conseguir. Puedes leer más y firmar la petición aquí:

http://chng.it/HRccJzfRJS

¡Gracias!
Alejandro
