### ISSUE TITLE
Crash when using both LittleTiles and OnlinePictureFrame simultaneously

### ISSUE THREAD

**Issue by Revyse** [CreativeMD/LittleTiles#401]
Using only LittleTiles or OnlinePictureFrame works fine, however when both mods are present at the same time only a few (about two) chunks are loaded around the player. All other chunks are invisible (with hitboxes still there) until you cause a block update at the border of one of the invisible chunks. This will either cause the chunk to reappear or it will freeze the game. Game has to be shut down manually, generating no crash report. The issue seems to be related to Optifine and its connected textures, causing the game to get into an endless loop resulting in a freeze and a massive log file. Removing either of the two CreativeMD mods solves the game from getting stuck after which it works fine again. Forge version is 1.12.2-14.23.5.2854. Screenshots and log file attached.
Log file: https://www.mediafire.com/file/dprih7gbt6p9ccb/latest.log/file
Screenshost: https://imgur.com/a/ZzioJog

**Comment by CreativeMD** [comment]
This seems to be an issue with Opitifine somehow. Normally this works, but for some reason the interaction between LT and Optifine doesn't work. I doubled checked your version and everything seems fine. So maybe with the addition of a resourcepack or modded blocks this seems to fail. Can you try to use the preview version Optifine?

**Comment by Revyse** [comment]
I just tested it, but using Optifine preview has the same effect. What I do think is peculiar is that everything works when I take out OPF and leave LT in.
Also, the issue seems to be directly linked to the use of the Conquest Reforged resource pack. When that pack is disabled, the world loads fine with all mods present, but when I enable it the issue shows up again.

So summarized, I cannot use LT, OPF and the CR resource pack at the same time, but disabling either of those fixes the issue.

**Comment by Revyse** [comment]
I should also note that if I use the Rojiura Mod resource pack (which also contains connected textures) all still works fine. It seems issues are only caused when using the Conquest Reforged resource pack.

**Comment by CreativeMD** [comment]
I have uploaded a new CreativeCore version which does not output this error to the log. Maybe this "fixes" the issue somehow. Would be happy if you could try it out: https://www.curseforge.com/minecraft/mc-mods/creativecore/files/2956475

**Comment by CreativeMD** [comment]
any news?

**Comment by Revyse** [comment]
I'm sorry for my late reply. I just ran some tests and this is my report:
Right now it does keep rendering the chunks, however after about 5 seconds of loading the game freezes and crashes. Sometimes the game does actually fully crash, sometimes it freezes and has to be closed. After having loaded a world that had not been loaded with this mod configuration before, it will freeze instantly when trying to load it again after the game has frozen/crashed.
I took one screenshot of how my game looked when it crashed and one screenshot of the crash notification itself. I also uploaded the latest and debug logs and the server and client crash report that got produced the time the game actually crashed instead of froze (all log and crash files are of the same crash). Things definitely changed and improved (since the game actually keeps loading the world) but the game still gets into a loop of some kind, creating massive crash and log files. I hope this was sufficient information. If you need any more information I would gladly supply this to you. Good luck!
https://www.mediafire.com/folder/cfknuha4mm8nm/

**Comment by CreativeMD** [comment]
Released a new version of CreativeCore, which includes an option called use-optifine-compat. If you set it to false it should solve your issue. 

I will close this issue, if this issue is still not fixed make sure to let me know.
