### ISSUE TITLE
Random Crashing

### ISSUE THREAD

**Issue by Dragoonat** [CreativeMD/LittleTiles#402]
When using little tiles chisel, minecraft randomly crashes giving this error report.
This is new since I updated littletiles:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.12_mc1.12.2.jar)
  FMLModule (mdxlib-3.0.0.24.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre199_27_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 5/12/20 6:44 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.creativemd.littletiles.common.entity.EntityAnimation.onUpdateForReal(EntityAnimation.java:657)
	at com.creativemd.littletiles.client.world.LittleAnimationHandlerClient.tickClient(LittleAnimationHandlerClient.java:500)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_523_LittleAnimationHandlerClient_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.common.entity.EntityAnimation.onUpdateForReal(EntityAnimation.java:657)
	at com.creativemd.littletiles.client.world.LittleAnimationHandlerClient.tickClient(LittleAnimationHandlerClient.java:500)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_523_LittleAnimationHandlerClient_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Dragoonat'/41, l='MpServer', x=3314.03, y=67.22, z=-3834.06]]
	Chunk stats: MultiplayerChunkCache: 1521, 1521
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (3654,58,-4097), Chunk: (at 6,3,15 in 228,-257; contains blocks 3648,0,-4112 to 3663,255,-4097), Region: (7,-9; contains chunks 224,-288 to 255,-257, blocks 3584,0,-4608 to 4095,255,-4097)
	Level time: 15923422 game time, 563422 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 62 total; [EntityPixelmon['Magikarp'/4866, l='MpServer', x=3259.40, y=51.15, z=-3844.60], EntityPixelmon['Magikarp'/4867, l='MpServer', x=3261.30, y=43.00, z=-3840.35], EntityPixelmon['Oricorio'/4894, l='MpServer', x=3293.04, y=64.00, z=-3811.35], EntityPainting['Painting'/3525, l='MpServer', x=3318.00, y=70.50, z=-4070.03], EntityPlayerSP['Dragoonat'/41, l='MpServer', x=3314.03, y=67.22, z=-3834.06], EntityOkapi['Okapi'/44, l='MpServer', x=3356.64, y=55.92, z=-3922.64], EntityOkapi['Okapi'/45, l='MpServer', x=3319.95, y=56.34, z=-3887.06], EntityMinecartChest['Minecart with Chest'/46, l='MpServer', x=3281.50, y=35.06, z=-3778.50], EntityOkapi['Okapi'/48, l='MpServer', x=3396.01, y=56.46, z=-3846.05], EntityPainting['Painting'/2433, l='MpServer', x=3318.00, y=70.50, z=-4070.03], EntityPixelmon['Pyukumuku'/4961, l='MpServer', x=3251.62, y=40.61, z=-3800.01], EntityPixelmon['Surskit'/4964, l='MpServer', x=3308.67, y=53.04, z=-3846.62], EntityPixelmon['Surskit'/4965, l='MpServer', x=3321.54, y=56.88, z=-3876.54], EntityHawksbillSeaTurtle['Hawksbill Sea Turtle'/2673, l='MpServer', x=3243.32, y=52.69, z=-3882.21], EntityPixelmon['Pyukumuku'/4980, l='MpServer', x=3293.64, y=56.54, z=-3790.77], EntityPixelmon['Oricorio'/4985, l='MpServer', x=3287.47, y=65.00, z=-3819.51], EntityPixelmon['Magikarp'/4994, l='MpServer', x=3285.33, y=50.00, z=-3808.03], EntityPixelmon['Magikarp'/4995, l='MpServer', x=3281.84, y=48.43, z=-3763.03], EntityPixelmon['Clamperl'/4998, l='MpServer', x=3302.47, y=49.00, z=-3836.59], EntityPixelmon['Luvdisc'/5007, l='MpServer', x=3311.84, y=49.00, z=-3785.82], EntityPixelmon['Clamperl'/5008, l='MpServer', x=3303.53, y=47.00, z=-3812.55], EntityTropicalFish['entity.zawa.marinetang.name'/2707, l='MpServer', x=3178.47, y=56.48, z=-3882.71], EntityPixelmon['Carvanha'/5011, l='MpServer', x=3318.50, y=49.69, z=-3864.94], EntityClownFish['Clownfish'/2708, l='MpServer', x=3168.11, y=56.36, z=-3847.83], EntityPixelmon['Oricorio'/5012, l='MpServer', x=3298.96, y=71.00, z=-3838.59], EntityPainting['Painting'/2433, l='MpServer', x=3318.00, y=70.50, z=-4070.03], EntityPixelmon['Oricorio'/5015, l='MpServer', x=3262.09, y=73.00, z=-3823.65], EntityTropicalFish['entity.zawa.marinetang.name'/2712, l='MpServer', x=3161.16, y=55.99, z=-3871.06], EntityPixelmon['Magikarp'/5016, l='MpServer', x=3243.02, y=43.42, z=-3849.74], EntityTropicalFish['entity.zawa.marinetang.name'/2713, l='MpServer', x=3160.02, y=56.02, z=-3848.42], EntitySockeyeSalmon['Sockeye Salmon'/2714, l='MpServer', x=3160.64, y=56.49, z=-3842.68], EntityPixelmon['Wingull'/5019, l='MpServer', x=3338.74, y=57.00, z=-3762.61], EntityPixelmon['Wingull'/5021, l='MpServer', x=3347.86, y=62.00, z=-3787.28], EntityPixelmon['Pyukumuku'/5022, l='MpServer', x=3335.52, y=49.00, z=-3786.55], EntityTropicalFish['entity.zawa.marinetang.name'/2721, l='MpServer', x=3141.25, y=55.83, z=-3866.85], EntityPixelmon['Pidgeotto'/5025, l='MpServer', x=3277.21, y=60.00, z=-3829.21], EntityPixelmon['Magikarp'/5027, l='MpServer', x=3346.00, y=49.00, z=-3831.98], EntityPixelmon['Wingull'/5028, l='MpServer', x=3337.41, y=75.00, z=-3809.18], EntitySockeyeSalmon['Sockeye Salmon'/2725, l='MpServer', x=3136.20, y=55.48, z=-3868.53], EntityCichlid['Cichlid'/2726, l='MpServer', x=3124.60, y=55.74, z=-3867.91], EntitySockeyeSalmon['Sockeye Salmon'/2727, l='MpServer', x=3124.85, y=56.02, z=-3876.46], EntityAnimation['entity.animation.name'/3496, l='MpServer', x=3322.00, y=84.00, z=-4083.00], EntityAnimation['entity.animation.name'/3497, l='MpServer', x=3321.00, y=84.00, z=-4083.00], EntityPixelmon['Finneon'/5035, l='MpServer', x=3306.30, y=49.44, z=-3754.38], EntityPixelmon['Crabrawler'/5036, l='MpServer', x=3304.72, y=49.00, z=-3764.68], EntityPainting['Painting'/2433, l='MpServer', x=3318.00, y=70.50, z=-4070.03], EntityPixelmon['Magikarp'/5041, l='MpServer', x=3332.54, y=55.67, z=-3856.62], EntityOkapi['Okapi'/178, l='MpServer', x=3337.13, y=57.00, z=-3663.67], EntityOkapi['Okapi'/183, l='MpServer', x=3361.15, y=62.27, z=-3661.86], EntityPainting['Painting'/2433, l='MpServer', x=3318.00, y=70.50, z=-4070.03], EntityAnimation['entity.animation.name'/3526, l='MpServer', x=3320.00, y=100.00, z=-4068.00], EntityAnimation['entity.animation.name'/3527, l='MpServer', x=3322.00, y=100.00, z=-4068.00], EntityOkapi['Okapi'/200, l='MpServer', x=3372.92, y=66.00, z=-3704.97], EntityPixelmon['Magikarp'/4814, l='MpServer', x=3313.49, y=52.45, z=-3854.65], EntityPainting['Painting'/2433, l='MpServer', x=3318.00, y=70.50, z=-4070.03], EntityPixelmon['Surskit'/4832, l='MpServer', x=3293.34, y=49.39, z=-3837.66], EntityPixelmon['Poliwag'/4833, l='MpServer', x=3281.49, y=49.19, z=-3826.66], EntityOkapi['Okapi'/230, l='MpServer', x=3453.99, y=71.00, z=-3723.05], EntityOkapi['Okapi'/233, l='MpServer', x=3447.36, y=49.00, z=-3818.29], EntityPainting['Painting'/3525, l='MpServer', x=3318.00, y=70.50, z=-4070.03], EntityPixelmon['Oricorio'/4859, l='MpServer', x=3317.48, y=67.00, z=-3898.91], EntityPainting['Painting'/2433, l='MpServer', x=3318.00, y=70.50, z=-4070.03]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1875755600 bytes (1788 MB) / 6106906624 bytes (5824 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_F5 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                           | Version           | Source                                         | Signature                                |
	|:------ |:-------------------------------------------- |:----------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                                    | 1.12.2            | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                                          | 9.42              | minecraft.jar                                  | None                                     |
	| LCHIJA | FML                                          | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                                        | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy                            | 1.0.0             | minecraft.jar                                  | None                                     |
	| LCHIJA | littletilescore                              | 1.0.0             | minecraft.jar                                  | None                                     |
	| LCHIJA | com.elytradev.movingworld.common.asm.coremod |                   | minecraft.jar                                  | None                                     |
	| LCHIJA | srm-hooks                                    | 1.12.2-1.0.0      | minecraft.jar                                  | None                                     |
	| LCHIJA | codechickenlib                               | 3.2.2.353         | CodeChickenLib-1.12.2.jar                      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ancientwarfare                               | 1.12.2-2.7.0.772  | ancientwarfare-1.12.2-2.7.0.772.jar            | None                                     |
	| LCHIJA | ancientwarfarestructure                      | 1.12.2-2.7.0.772  | ancientwarfare-1.12.2-2.7.0.772.jar            | None                                     |
	| LCHIJA | ancientwarfarevehicle                        | 1.12.2-2.7.0.772  | ancientwarfare-1.12.2-2.7.0.772.jar            | None                                     |
	| LCHIJA | ancientwarfarenpc                            | 1.12.2-2.7.0.772  | ancientwarfare-1.12.2-2.7.0.772.jar            | None                                     |
	| LCHIJA | ancientwarfareautomation                     | 1.12.2-2.7.0.772  | ancientwarfare-1.12.2-2.7.0.772.jar            | None                                     |
	| LCHIJA | architecturecraft                            | @VERSION@         | ArchitectureCraft-ElytraDev-Mod-1.12.2 (2).jar | None                                     |
	| LCHIJA | baubles                                      | 1.5.2             | Baubles-Mod-1.12.2.jar                         | None                                     |
	| LCHIJA | bookworm                                     | 1.12.2-2.5.1      | bookworm-1.12.2-2.5.1.jar                      | None                                     |
	| LCHIJA | ctm                                          | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                      | None                                     |
	| LCHIJA | chisel                                       | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar                   | None                                     |
	| LCHIJA | creativecore                                 | 1.10.0            | CreativeCore_v1.10.12_mc1.12.2.jar             | None                                     |
	| LCHIJA | customnpcs                                   | 1.12              | CustomNPCs_1.12.2-(01Oct19).jar                | None                                     |
	| LCHIJA | movingworld                                  | 1.12-6.342        | movingworld-1.12-6.342-full.jar                | None                                     |
	| LCHIJA | davincisvessels                              | @DVESSELSVER@     | davincisvessels-1.12-6.340-full.jar            | None                                     |
	| LCHIJA | dawnoftimebuilder                            | 1.0.7             | dawnoftime_builder_edition-1.0.7.jar           | None                                     |
	| LCHIJA | ptrmodellib                                  | 1.0.4             | PTRLib-1.0.4.jar                               | None                                     |
	| LCHIJA | props                                        | 2.6.3             | Decocraft-2.6.3_1.12.2.jar                     | None                                     |
	| LCHIJA | exoticbirds                                  | 1.0               | Exotic+Birds+1.12.2-3.1.0.jar                  | None                                     |
	| LCHIJA | cfm                                          | 6.3.1             | furniture-6.3.1-1.12.2.jar                     | None                                     |
	| LCHIJA | littletiles                                  | 1.5.0             | LittleTiles_v1.5.0-pre199_27_mc1.12.2.jar      | None                                     |
	| LCHIJA | mdxlib                                       | 3.0.0.24          | mdxlib-3.0.0.24.jar                            | None                                     |
	| LCHIJA | pixelmon                                     | 7.2.2             | Pixelmon-1.12.2-7.2.2-universal.jar            | None                                     |
	| LCHIJA | secretroomsmod                               | 5.6.4             | secretroomsmod-1.12.2-5.6.4.jar                | None                                     |
	| LCHIJA | worldedit                                    | 6.1.10            | worldedit-forge-mc1.12.2-6.1.10-dist.jar       | None                                     |
	| LCHIJA | zawa                                         | 1.12.2-2.0.35     | zawa-1.12.2-2.0.35.jar                         | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| LCHIJA | immersiveengineering                         | 0.12-92           | ImmersiveEngineering-0.12-92.jar               | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | llibrary                                     | 1.7.19            | llibrary-1.7.19-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CreativePatchingLoader (CreativeCore_v1.10.12_mc1.12.2.jar)
  
FMLModule (mdxlib-3.0.0.24.jar)
  com.asx.mdx.AccessTransformer
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LittlePatchingLoader (LittleTiles_v1.5.0-pre199_27_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 445.87' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 19
	Mipmaps: 3
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 445.87
	OpenGlRenderer: GeForce GTX 1080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

Many thanks for your work!
Any ideas what could be causing this? Can I fix it on my side i.e clashing with a mod etc.

**Comment by kirokadura** [comment]
CreativeCore is one version behind, so I suggest updating it before anything else.

**Comment by CreativeMD** [comment]
Seems like a random crash which happens very rarely. Not sure if I can do something against it. If it happens consistently make sure to send me your world.

**Comment by CreativeMD** [comment]
I will close this issue for now. Make sure to post more crash-reports if they occur.
