### ISSUE TITLE
Chisel Carpets are Little Tileable

### ISSUE THREAD

**Issue by SealTheTiel** [CreativeMD/LittleTiles#404]
### Issue
The chiseled carpets from the Chisel mod can apparently be little tiled,
They can be pick blocked by the chisel and placed normally, but it has to be placed as a full block or else funky stuff will happen.

### Steps to reproduce
[0] Have the Chisel mod installed (Not C&B)
[1] Chisel a normal carpet 
![image](https://user-images.githubusercontent.com/38400820/81918619-4c779980-9609-11ea-80cc-bc9fad0f0968.png)

[2] Place down the carpet
![image](https://user-images.githubusercontent.com/38400820/81918655-5c8f7900-9609-11ea-8643-caa814e17ef3.png)

[3] Do some Little Tiles stuff, in the pics below, I just hammered the corner bit.
![image](https://user-images.githubusercontent.com/38400820/81918822-952f5280-9609-11ea-8358-3fb8aacd8f6e.png)
![image](https://user-images.githubusercontent.com/38400820/81918847-9eb8ba80-9609-11ea-893a-87047ff3c1fe.png)

### Suggested Fix
[1] Blacklist the carpets from being little tiled as their full wool counterparts are far more superior and not limited by the carpet's scaling thing, also vanilla carpets are unable to be little tiled so the Chisel carpets should also be like that.

**Comment by CreativeMD** [comment]
Actually this is not a mistake of LittleTiles but from chisel. For some reason the block returns true for `isFullBlock()`. Pretty sure they have dropped support for 1.12 as well. Let's hope this issue will be fixed in 1.15. Sorry, hope you can live with it.

**Comment by SealTheTiel** [comment]
Ah I see, I can totally live with it as I barely use carpets anymore as little tiles are better than standard carpets. I happen to just use one a while ago and accidentally used the little hammer on it and weird stuff happened.
