### ISSUE TITLE
Little Workbench Crash

### ISSUE THREAD

**Issue by mxnmnm** [CreativeMD/LittleTiles#406]
I gave myself a little workbench using commands and I crashed
https://pastebin.com/c3mEwBaY
I tried logging back into the world and I got a slightly different crash
https://pastebin.com/qrwLKv9z

CreativeCore_v1.10.14_mc1.12.2
LittleTiles_v1.5.0-pre199_28_mc1.12.2.jar

**Comment by kirokadura** [comment]
Seems to be Obfuscate related as well. Can you try doing the same thing without Obfuscate installed to see if it still results in a crash?

**Comment by mxnmnm** [comment]
https://gist.github.com/mxnmnm/c8a0901821432c5c038d04c87efeb8c5
Without obfuscate

**Comment by CreativeMD** [comment]
You cannot give yourself a workbench using a command that easily. All premade structure have the exact same id. You probably forgot the nbt data. I hope the newest version fixes the crash so you can delete the item.
