### ISSUE TITLE
Entity Not Found Bug

### ISSUE THREAD

**Issue by endigma** [CreativeMD/LittleTiles#407]
> CreativeCore_v1.10.13_mc1.12.2.jar
> LittleTiles_v1.5.0-pre199_27_mc1.12.2.jar

The functionality of LittleTiles doors is impaired when used on my Forge 1.12.2 b2838 server, which is running WorldEdit serverside. Upon opening a door, it will complete its open animation, then bug and become invisible and cause collision bugging. 

[Video of reproducing](https://endigma.xyz/upload/vv2NcWhMRe.mp4)
[Logs surrounding error](https://endigma.xyz/upload/WeNm8YiPUf.txt)
[Modlist](https://endigma.xyz/upload/RxD5oTd550.html)

Server logs did not contain anything peculiar.

**Comment by CreativeMD** [comment]
I need the server log and the entire client log.

**Comment by CreativeMD** [comment]
I will close this issue for now. It might be fixed in the newer versions. If not make sure to send me the log file.
