### ISSUE TITLE
Mod not installing

### ISSUE THREAD

**Issue by SoullyB** [CreativeMD/LittleTiles#408]
I have moved the Mod in to the Mod folder but it is not showing on the Mod list and none of the Little Tiles items are available in game (e.g. little hammer).
I have installed the latest versions of Forge, CreativeCore and Little Tiles. Currently running 1.12.2

can you help?

**Comment by kirokadura** [comment]
If you open the Mod Options menu, does it show up? Does the other mods installed in the same folder show up as well?

Post a screenshot of your mod folder.

**Comment by CreativeMD** [comment]
I will close this issue for now. Feel free to ask for more help, we will still answer here.

**Comment by SoullyB** [comment]
Apologies,  email went to a junk folder.
It is in the mod folder, but not showing in the minecraft Mod Options. I will post a screenshot later
