### ISSUE TITLE
Premade Items not Found in JEI

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [CreativeMD/LittleTiles#409]
Minecraft: 1.12.2
Forge: 14.23.5.2854
Little Tiles version: 1.5.0-pre199_28
Creative Core version: 1.10.14
JEI version: 4.15.0.293

None of the premade structures, such as the Little Workbench, Little Importer, Little Exporter, and cables are visible in JEI. This makes it hard to use recipes, or import existing structures, as the required items are hard to access. In addition, since the crafting recipes are not shown, it makes it hard to make these items for people who do not have the recipes known beforehand. These items are available in the creative menu, but this is not a good enough solution for players that do not have access to the creative menu.

**Comment by CreativeMD** [comment]
Fixed in the newest version!
