### ISSUE TITLE
Crash after Creators Update Win 10

### ISSUE THREAD

**Issue by BSKCorp** [CreativeMD/LittleTiles#41]
Could you please help, I don't know what is going on and it just started after that stupid update. Was running fine before. But I now get very low FPS when in a area I have built with the little tiles and every so often I get this crash - https://pastebin.com/sLSRJCdD

Could you please give me some insight as to what is going on possibly? I can give you more info if needed I just like to fix this and have no idea how to.

**Comment by BSKCorp** [comment]
Extra info I am not sure is needed but might help

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
 I also keep getting a Open GL error, I am using shaders... 

Very sorry I am literally at a complete loss as to what to do, been searching everywhere.

**Comment by CreativeMD** [comment]
Are you using the newest version?

**Comment by BSKCorp** [comment]
I am, yes.

**Comment by BSKCorp** [comment]
Ok so I made a test pack, and have only the few mods that were used to build the area I keep crashing at. Nothing else, same world everything. And it still gives me that crash, except right now it hangs MC in a frozen state. But went in a checked crash logs and it shows the same error as in the paste above.

**Comment by BSKCorp** [comment]
[crash-2017-04-18_17.32.13-client.txt](https://github.com/CreativeMD/LittleTiles/files/931246/crash-2017-04-18_17.32.13-client.txt)

Full Crash Log

**Comment by CreativeMD** [comment]
The low FPS might be a cause of the creators about (consider reinstalling your graphic card driver), but the crash is an issue of my mod. Does this fix it?
https://www.dropbox.com/s/v5debkw26uajnf1/LittleTiles%20v1.4.8%20mc1.11.2.jar?dl=1

**Comment by BSKCorp** [comment]
Sorry have been busy with work, long days Just downloaded it and can test this afternoon.

**Comment by BSKCorp** [comment]
Lasted a little longer but have a different error code now - https://pastebin.com/2Bivnvn9

Full Crash Log
[crash-2017-04-21_17.38.44-client.txt](https://github.com/CreativeMD/LittleTiles/files/948461/crash-2017-04-21_17.38.44-client.txt)

**Comment by CreativeMD** [comment]
But now it has to work out:
https://www.dropbox.com/s/v5debkw26uajnf1/LittleTiles%20v1.4.8%20mc1.11.2.jar?dl=1

**Comment by BSKCorp** [comment]
Don't hate me, this was pretty instant this time, loaded up and within 30 seconds froze. 
 Is it that I am have made something too intricate for the mod itself?  
[crash-2017-04-22_09.59.52-client.txt](https://github.com/CreativeMD/LittleTiles/files/949055/crash-2017-04-22_09.59.52-client.txt)

**Comment by BSKCorp** [comment]
Would you also like me to upload the world so you may check it out yourself? it's not a large file,

**Comment by CreativeMD** [comment]
Yes might be a good idea :D

**Comment by BSKCorp** [comment]
besides the Little Tiles, I am also using Optifine HD U B7 and Rustic 0.1.2.2. Shader pack is Robobo 1221s High 6.1. I can add these in as well.

**Comment by BSKCorp** [comment]
Here is the link to my Technic Folder, my upload is slow so check it in about 15 mins and the world (New Bastok.7z) should be in there. it's only 318MB. but I have 2 mbps upload T_T lol

https://www.dropbox.com/sh/im73w7behm2iqtg/AACR6lOps9vQez8Cynf1dDX4a?dl=0

**Comment by CreativeMD** [comment]
Ok ... i know i said it already several times, but now it should be fixed :D if not you are allowed to hit in the face :P

https://www.dropbox.com/s/v5debkw26uajnf1/LittleTiles%20v1.4.8%20mc1.11.2.jar?dl=1

**Comment by BSKCorp** [comment]
LOL Will download and test as soon as I get back home, today was my little girls birthday. And I'm not a violent type so you're safe lol it's stuff like this anyways I enjoy doing as it helps the devs and makes better mods.

**Comment by BSKCorp** [comment]
actually on that note, if you ever want to toss me any dev builds I will always be glad to help test you them for you.

**Comment by BSKCorp** [comment]
Could it be a corrupt chunk in the world? Or the data itself in that save? Causing it to throw the error. I know very little about JAVA and how chunk loading works. I could make a new world rebuild the same build and see if it does the same?

But 
[crash-2017-04-22_22.07.08-client.txt](https://github.com/CreativeMD/LittleTiles/files/949441/crash-2017-04-22_22.07.08-client.txt)

**Comment by CreativeMD** [comment]
Optifine is the problem and i have no idea what Optifine is doing, because all this crashes are really strange.  I thought it would be fixed, since i didn't crash for me. All of this seems to be really strange, because Optifine seems to render a chunk simultaneously, which does not make any sense at all. I might have one last idea, if this will not work out i have to contact the author of Optifine. 

Thanks a lot for all your help, hopefully it will be fixed soon. Will upload another test version this day.

**Comment by BSKCorp** [comment]
No problem, glad I could help. I never thought of removing Optifine as it's kind of a put in and forget kind of mod for me as I always use shaders. Will run it without today as well just to see.

**Comment by BSKCorp** [comment]
Small update, ran it without Optifine, there is a bit of stuttering still in the Building with 60-57 FPS but no crash.. side note, with your mod and the design I had made it actually looks better without lmao I feel sorta stupid not thinking of optifine, I have heard some mods don't play well with it because it does change the rendering in MC. But, I would like to say this much you are a great Dev and I know I've been a pain in the ass and all but thank you for your time and your mod.

**Comment by CreativeMD** [comment]
Compatibility with Optifine is a must (at least for me). So i'm really really happy to have you. If i would be alone I probably would have thought the bug has been fixed already. Anyway, here we go, this one should really really work ... i promise :P
https://www.dropbox.com/s/v5debkw26uajnf1/LittleTiles%20v1.4.8%20mc1.11.2.jar?dl=1

**Comment by BSKCorp** [comment]
With about a full 2 minutes (which by then it normally crashes) we are still up and running. Not sure what you did this round, but it is fixed from what I can tell. Tested it with optifine so good deal! Again thank you for your hard work and if you ever need any other testing done, bug reproducing, etc just give me a holla. I have skype, discord, and FB so any one of those just msg me and I can give you the contact info, again thanks!

**Comment by CreativeMD** [comment]
Thanks for all your help! Feel free to join on my discord server: https://discord.gg/W9QM3fS
Would be really really cool to see you there :D
Will upload release this fix (along with some other small improvements later this day).
