### ISSUE TITLE
Stable enough for 1.12 ?

### ISSUE THREAD

**Issue by beaussan** [CreativeMD/LittleTiles#410]
Hello, just a quick question, is this mod stable enouth for minecraft 1.12 ? 

I see it's still in beta, and I wonder if it safe to include into my server.

Awesome mod by the way =)

**Comment by CreativeMD** [comment]
It's beta, because it's still a pre-release. It's quite stable at the moment. Just be aware that if new features are added they might cause a few issues. I recommend to wait before updating to the newest version (usually the fixes follow soon after).
