### ISSUE TITLE
Fake World Issues appearing up again with Sponge / Cant pass doors

### ISSUE THREAD

**Issue by CedeLovesKat** [CreativeMD/LittleTiles#411]
Mods and Sponge Version:
spongeforge-1.12.2-2838-7.2.2-RC4027
LittleTiles_v1.5.0-pre199_32_mc1.12.2
CreativeCore_v1.10.14_mc1.12.2

Server Log of the appearing error: https://hastebin.com/dehonudica.rb

Problem: as before on mohist, when making a sliding door I cant pass it when I open it

**Comment by CreativeMD** [comment]
Can you test if this one fixes it?
https://www.dropbox.com/s/ur4oqdqwr9egey0/CreativeCore_v1.10.15_mc1.12.2.jar?dl=1

**Comment by CedeLovesKat** [comment]
Works like a charm : )
Thank u so much <3

The bug is fixed :p

**Comment by CreativeMD** [comment]
Uploaded to curseforge. Thanks for your help!
