### ISSUE TITLE
Out of date tutorials

### ISSUE THREAD

**Issue by Krigeris** [CreativeMD/LittleTiles#412]
https://github.com/CreativeMD/LittleTiles/wiki/Little-Recipe

If you're gonna change the functionality of objects please update the guides involving them, I was sitting there annoyed for 10 minutes trying to figure out why the wrench wasn't working for recipes until I actually went over to the wrench page and read that the functionality was changed.

**Comment by CreativeMD** [comment]
This will be fixed once 1.5.0 is released. Sorry, but it's very hard to keep everything updated.
