### ISSUE TITLE
cant launch with little tiles

### ISSUE THREAD

**Issue by Luckyradkid1** [CreativeMD/LittleTiles#414]
i press launch and it dont work. it just crashes plz fix

**Comment by kirokadura** [comment]
Make sure to install the latest version of LittleTiles and CreativeCore, both downloaded from Curseforge. Also provide a crash-report, otherwise we cannot help you further.

**Comment by CreativeMD** [comment]
Will close this issue for now. If the newer versions don't fix your issue make sure to post a crash-report here.
