### ISSUE TITLE
Client setting maxSavedActions has no effect when on a server

### ISSUE THREAD

**Issue by NoxyNixie** [CreativeMD/LittleTiles#418]
Having the following `littletiles-client.json`
```
{
  "building": {
    "invertStickToGrid": false,
    "maxSavedActions": 256,
    "useALTForEverything": true,
    "useAltWhenFlying": true
  },
  "rendering": {
    "useQuadCache": false,
    "useCubeCache": true,
    "hideParticleBlock": false,
    "renderingThreadCount": 2,
    "highlightStructureBox": true,
    "previewLines": false,
    "enableRandomDisplayTick": false,
    "uploadToVBODirectly": true
  }
}
```

Does not give me `256` undo action; Instead it seems to be `10`. 

This is on `1.5.0-pre199_33` so not the latest but I didn't see anything in the Changelog related to saved actions (The server will update to the latest at some point and I can check again then).

**Comment by CreativeMD** [comment]
As the name of the config file suggests it's for clients, so if you change it on a server it won't have an effect on the clients.

Nonetheless there is an option to synchronize client settings. Use the command /cmdconfig and hit client settings. There you can select which options to synchronize, check `maxSavedActions` in `building`. Once you have done that you can go back to /cmdconfig and set a new value for this option and it will be automatically synchronized with every client.

**Comment by NoxyNixie** [comment]
The config is on the client side ... the server doesn't even have the file `littletiles-client.json`.

Where is this somewhat strange configuration stored on the server? I don't see any config file that stores these strangely "synchronized" settings?

(Also why does it need to be synchronized for the "client" setting (that is on the client not on the server) to take effect on a server?)

**Comment by CreativeMD** [comment]
Ok, let me explain it again.

These settings are client side only. The server does not care about it them at all. You can configure them ingame via the Mod Options Menu. You can also use the config file, but make sure minecraft is closed, otherwise your config might be overwritten.

All I said above is that you can synchronize client settings. So if you want to force everybody on the server to have 256 saved actions you can do that.

**Comment by NoxyNixie** [comment]
Ok then I'd like to report that the client setting does not work until you forcibly synchronize them with other people using the `/cmdconfig` command ... when you with your client settings as posted in the first post connect to a server.

**Comment by CreativeMD** [comment]
That would be very weird. Can you show me which options you have when you use /cmdconfig and navigate to littletiles?

**Comment by NoxyNixie** [comment]
Before I did the part where I mark a setting for synchronization with other clients it was just `general` and `survival`.

After toggling the setting as you described to be a force synchronization with other clients feature:
![image](https://user-images.githubusercontent.com/211381/83846280-a6e8af00-a70a-11ea-934b-c1e7c2ce40f5.png)

I now have the additional option in the UI: and the saved actions seem to be more than 10:
![image](https://user-images.githubusercontent.com/211381/83846422-da2b3e00-a70a-11ea-8f9b-b4e9a0628e14.png)

However before I even touched the `/cmdconfig` command I had the setting in my client config set to `256` and if this setting is pure client then it should have worked on the server (but it did not until I did the actions mentioned).

**Comment by CreativeMD** [comment]
Can you deselect it again, then set your client config back to 256. Hop on the server again and open the Mod Options Menu, what value do you see for maxSavedActions.

**Comment by NoxyNixie** [comment]
After closing the client completely and ensuring the client config is set to 256 (which it still was) I started and logged on the server again.

Before opening the UI I wanted to see if the setting persisted so I performed more than 10 actions (about 20) which wasn't undoable completely before I touched the `/cmdconfig` command the first time but are now still undoable. However the UI does not show the forced setting (Note the server has not been restarted): 
![image](https://user-images.githubusercontent.com/211381/83850857-cd5e1880-a711-11ea-92c0-8b3ab4a131c1.png)

I'll try a server restart to see if that changes things ...

**Comment by NoxyNixie** [comment]
Seems that whatever `/cmdconfig` did on the server made it persist now even post restart.

You'd probably assume I'm crazy and never had the issue in the first place but ... I tested it on multiple occasions and even verified it with another player that it for sure was 10 steps.

It was super easy to test as well as simply spam placing little tiles and undo'ing them one more than 10 times revealed the issue.

It is unfortunate that I can't reproduce the bug at this time (but it definitely was there).

**Comment by CreativeMD** [comment]
Hm ok, yeah maybe the config reset for some reason.
