### ISSUE TITLE
Shaders and Slices/Transparencies

### ISSUE THREAD

**Issue by zzed41** [CreativeMD/LittleTiles#421]
Hi there,

A bit of a combo issue, both related to shaders.

Basic info
Minecraft 1.12.2
Forge .2854
LittleTiles pre-199 (using this for compatibility with ALET mod)
CC 1.10.13 (same as above)
OptiFine 1.12.2 HD U F5

Issue #1
Sildur's Vibrant Sliders 1.27 (any quality version)

Edges of sliders in game are showing as black bits instead of it's normal color, reference image below. Issues are near headlights and wheelwells.

https://cdn.discordapp.com/attachments/276752456707473409/717407456048840754/2020-06-02_23.43.57.png

Issue #2 
SEUS Renewed 1.0.1
BSL v.7.1.04.1

Colored blocks with modified alpha transparency values in GUI does not show as transparent/translucent. Requires use of thin/thinne/thinnest blocks to allow transparency with these sliders.

Reference image below, left is with thin/thinner/thinnest, right is with colored blocks with modified transparency. First is BSL, second is SEUS.

https://cdn.discordapp.com/attachments/276752435869908993/718835429159469146/2020-06-06_22.32.57.png

https://cdn.discordapp.com/attachments/276752435869908993/718835430816219206/2020-06-06_22.33.19.png

**Comment by CreativeMD** [comment]
Sorry, but there is nothing I can do about that. Those things are up to the shaders. Some work better than others.
