### ISSUE TITLE
Little Tiles Not Loadin 1.12.2

### ISSUE THREAD

**Issue by SirNiall** [CreativeMD/LittleTiles#423]
When ever I launch minecraft through the launcher with this file in my mods folder, the game immediately crashes and takes me back to the launcher. There is no crash report however the launcher says "An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience." I am only running this mod alone with no other mod so I dont know what could be wrong.

I am running 1.12.2-forge-14.23.5.2854 with 16 gigabytes of RAM, an intel i3-8350k and a Radeon RX 580 Series. My machine is capable of running most modern games so I don't think it would have trouble running forge.

**Comment by kirokadura** [comment]
What LittleTiles and CreativeCore versions are you using?

**Comment by CreativeMD** [comment]
Make sure to download the newest version of CreativeCore and LittleTiles from curseforge. Most common problem is that people are using 9minecraft, something you should never do.
