### ISSUE TITLE
Dedicated server disconnecting players

### ISSUE THREAD

**Issue by Sereath** [CreativeMD/LittleTiles#425]
We have this issue where our server was preventing any player from joining:
```Network Disconnect: A fatal error has occurred, this connection is terminated```
No crashes, just that disconnection message whenever anyone tried to join.

And by reading the latest logs of the clients we deduced that the culprit was LittleTiles (Or maybe even CreativeCore)
[latest (3).log](https://github.com/CreativeMD/LittleTiles/files/4777599/latest.3.log)
And unlike the client logs the server one showed nothing. The server was still running fine, it's just that no one could join.

Once we removed LittleTiles from both the server and the client the issue was gone. 
We also removed CreativeCore from only the server, the clients are still running CreativeCore along with AmbientSounds 3 and EnhancedVisuals and everything seems fine for now. The server only ever had CreativeCore and LittleTiles, none of the client only mods were present.

v1.5.0-pre199_34_mc1.12.2

**Comment by CreativeMD** [comment]
You have to install EnhancedVisuals on the server as well (or remove it completely). That should fix your issue. Sorry for the inconvenience.

**Comment by Sereath** [comment]
Understood, wasnt aware of that.
