### ISSUE TITLE
chiseling and creating grass blocks makes it invisible

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#426]
Hi, so it appears creating or chiseling a grass block just make it invisible. I think this is a bug. Maybe happens on dirt blocks too. Here's my enviroment

OS : Windows 10
Minecraft Version : 1.12.2
Forge Version : ?

Mod List:
Albedo 1.1.0
BetterFps 1.4.8
ChunkAnimator 1.2
CreativeCore 1.10.16
CTM 1.0.2.31
Engineers Decor 1.0.20
Hwlya 1.8.26-B41
Immersive Engineering 0.12-98
Immersive Intelligence 0.1.1
Immersive Posts 0.2.1
Item Physic Full 1.4.34
JEI 4.1.15.0.293
Little Tiles 1.5.0-pre199_34
Optifine 1.12.2_HD_U_F4
Phosphor 0.2.6
Railcraft 12.0.0

**Comment by kirokadura** [comment]
Enable mipmap.

**Comment by ghost** [comment]
alright it works. but is there any other block that's affected by this? also why do i have to enable mipmap?
