### ISSUE TITLE
Is there a way to limit the scope

### ISSUE THREAD

**Issue by axin0452** [CreativeMD/LittleTiles#428]
Limit the scope of hammer and chisel.If there are no restrictions, Excessive range leads to collapse.There are always some players making trouble on the server.Hope to increase the limit options please!!

**Comment by kirokadura** [comment]
You can limit the range for both the chisel and hammer in the littletile.json config file. Just set **"strictMining"** to true and limit the chisel range in **"maxPlaceBlocks"** and the hammer range in **"maxEditBlocks"**. Make sure to update it on server and client side.

**Comment by axin0452** [comment]
`    "limitPlaceBlocksSurvival": true,
    "maxPlaceBlocks": 5,`

Even if it is set like this, there is still no way to limit the placement of the chisel. He will prompt not to exceed 5 but the placement is still successful
@kirokadura

**Comment by CreativeMD** [comment]
I highly recommend to configure it ingame. Just type in `/cmdconfig`.

**Comment by axin0452** [comment]
I mean, the function of restricting the placement of chisels is not effective
@CreativeMD

**Comment by CreativeMD** [comment]
The restriction does work in survival, but the blocks stay visible on client side. The reset is bugged. Fixed it but it will require some time until this will be released. But as I said it does work already (if you log out and in again the placed stuff will have disappeared).
