### ISSUE TITLE
Crash when attempting to open the Advanced Rocketry rocket inventory

### ISSUE THREAD

**Issue by AutumnalModding** [CreativeMD/LittleTiles#430]
So after LT was installed on a server I play on frequently, I started getting crashes every time I tried to open the Advanced Rocketry rocket inventory (which is a major issue, since I can't put a space station chip in there, or satellites in the satellite bay).

Crash report: https://pastebin.com/JLaTmEPs

Any help is appreciated. Thanks!

**Comment by CreativeMD** [comment]
Duplicate of this issue. I hope to fix it soon.

https://github.com/CreativeMD/CreativeCore/issues/75
