### ISSUE TITLE
Add a fence structure modifier

### ISSUE THREAD

**Issue by SemmelJochen** [CreativeMD/LittleTiles#432]
Today I was trying to create a fence structure that is not higher than 1 block. I think it would be useful to add a functionality where you can declare the structure like a fence, so you can not jump over it. 
Or is there may be a way to do it yet? I did not found an opportunity to create such a structure.

**Comment by kirokadura** [comment]
You can make the top part of the fence invisible. As long as its 1 block and 6 pixels tall it should be enough to not allow you to jump over.

**Comment by CreativeMD** [comment]
If you are in creative you can always can use the alpha value to make parts invisible. Otherwise you can use glass or just build the fence a little higher. A player can jump 1.25 blocks high.

**Comment by SemmelJochen** [comment]
Thank you for the help :)
