### ISSUE TITLE
Immersive Wire Coil Blocks not rendering

### ISSUE THREAD

**Issue by FreezePhoenix** [CreativeMD/LittleTiles#433]
So, I wanted to use some coils for a nice home-made motor, but as it turns out, they don't get rendered by LittleTiles.

I'd be glad to give screenshots but there just isn't anything to give a screenshot of! That's the problem!

Mods:
* Optifine Ultra F5
* LittleTilesCore 1.0.0
* LittleTiles 1.5.0
* Immersive Engineering 0.12-98
Minecraft version: 1.12.2
Forge version: 14.23.5.2854

**Comment by CreativeMD** [comment]
Uploaded your fix to curseforge!

**Comment by FreezePhoenix** [comment]
Thanks!
