### ISSUE TITLE
Odd crash that only happens on my server.

### ISSUE THREAD

**Issue by kieranthegoblin** [CreativeMD/LittleTiles#434]
This happens whenever I go into the LittleTiles tab in creative on my server. On singleplayer it's completely fine. Is this a server problem, or is it a mod problem? Thanks! (crash report below)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreModLoader (Sound-Physics-Mod-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2-1.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.33_mc1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre199_34_mc1.12.2-1.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 6/30/20 7:43 PM
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at com.creativemd.littletiles.common.util.grid.LittleGridContext.get(LittleGridContext.java:64)
	at com.creativemd.littletiles.common.item.ItemLittleChisel.getPreview(ItemLittleChisel.java:135)
	at com.creativemd.littletiles.common.item.ItemLittleChisel.applyCustomOpenGLHackery(ItemLittleChisel.java:176)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.handlePerspective(CreativeBakedModel.java:227)
	at net.minecraftforge.client.ForgeHooksClient.handleCameraTransforms(ForgeHooksClient.java:427)
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.call(Reflector.java:799)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:508)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:559)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.common.util.grid.LittleGridContext.get(LittleGridContext.java:64)
	at com.creativemd.littletiles.common.item.ItemLittleChisel.getPreview(ItemLittleChisel.java:135)
	at com.creativemd.littletiles.common.item.ItemLittleChisel.applyCustomOpenGLHackery(ItemLittleChisel.java:176)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.handlePerspective(CreativeBakedModel.java:227)
	at net.minecraftforge.client.ForgeHooksClient.handleCameraTransforms(ForgeHooksClient.java:427)
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.call(Reflector.java:799)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:508)

-- Item being rendered --
Details:
	Item Type: com.creativemd.littletiles.common.item.ItemLittleChisel@45f53ff6
	Registry Name: littletiles:chisel
	Item Aux: 0
	Item NBT: {}
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:559)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (174, 55). Absolute: (871, 1100)
	Screen size: Scaled: (512, 276). Absolute: (2560, 1377). Scale factor of 5

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['c00mer'/488, l='MpServer', x=-17.25, y=76.94, z=4.88]]
	Chunk stats: MultiplayerChunkCache: 440, 440
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 41490 game time, 26098 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 117 total; [EntityPlayerSP['c00mer'/488, l='MpServer', x=-17.25, y=76.94, z=4.88], EntityZombie['Zombie'/256, l='MpServer', x=52.50, y=35.00, z=-4.50], EntityZombie['Zombie'/258, l='MpServer', x=51.51, y=34.00, z=-0.30], EntityChicken['Chicken'/259, l='MpServer', x=48.23, y=71.00, z=37.46], EntityChicken['Chicken'/260, l='MpServer', x=56.19, y=69.00, z=43.60], EntityZombie['Zombie'/1044, l='MpServer', x=43.50, y=24.00, z=-36.50], EntityZombieVillager['Zombie Villager'/805, l='MpServer', x=-12.50, y=40.00, z=45.50], EntityZombie['Zombie'/557, l='MpServer', x=-74.50, y=15.00, z=50.50], EntityBat['Bat'/48, l='MpServer', x=-97.75, y=23.05, z=-3.47], EntityZombie['Zombie'/562, l='MpServer', x=-75.50, y=15.00, z=55.50], EntitySkeleton['Skeleton'/1081, l='MpServer', x=-14.50, y=24.00, z=-51.50], EntityZombieVillager['Zombie Villager'/1084, l='MpServer', x=30.50, y=33.00, z=-22.50], EntitySkeleton['Skeleton'/63, l='MpServer', x=-93.52, y=18.00, z=-39.43], EntityRabbit['Rabbit'/64, l='MpServer', x=-81.92, y=64.00, z=-43.50], EntityChicken['Chicken'/68, l='MpServer', x=-80.57, y=67.00, z=46.92], EntityChicken['Chicken'/69, l='MpServer', x=-82.65, y=73.00, z=35.87], EntityChicken['Chicken'/70, l='MpServer', x=-95.50, y=70.00, z=35.79], EntityItem['item.item.egg'/586, l='MpServer', x=-56.32, y=72.00, z=4.66], EntitySkeleton['Skeleton'/587, l='MpServer', x=-5.50, y=35.00, z=56.50], EntityZombieVillager['Zombie Villager'/588, l='MpServer', x=-2.50, y=35.00, z=59.50], EntityZombieVillager['Zombie Villager'/589, l='MpServer', x=-5.50, y=35.00, z=60.50], EntityRabbit['Rabbit'/81, l='MpServer', x=-73.50, y=65.00, z=-42.50], EntityRabbit['Rabbit'/82, l='MpServer', x=-64.82, y=71.00, z=-41.99], EntityChicken['Chicken'/85, l='MpServer', x=-66.81, y=72.00, z=9.30], EntityBat['Bat'/856, l='MpServer', x=-88.31, y=35.46, z=-69.32], EntityChicken['Chicken'/91, l='MpServer', x=-70.69, y=72.00, z=22.96], EntityChicken['Chicken'/93, l='MpServer', x=-74.56, y=72.00, z=28.11], EntityItem['item.item.egg'/94, l='MpServer', x=-76.45, y=72.00, z=21.86], EntitySkeleton['Skeleton'/95, l='MpServer', x=-78.49, y=15.00, z=47.31], EntityItem['item.item.rottenFlesh'/96, l='MpServer', x=-79.92, y=70.00, z=42.55], EntityChicken['Chicken'/97, l='MpServer', x=-77.80, y=72.00, z=39.58], EntityChicken['Chicken'/99, l='MpServer', x=-68.50, y=63.00, z=75.86], EntityCreeper['Creeper'/104, l='MpServer', x=-49.50, y=21.00, z=-67.50], EntityBat['Bat'/108, l='MpServer', x=-56.34, y=21.67, z=-65.66], EntityRabbit['Rabbit'/109, l='MpServer', x=-48.75, y=65.00, z=-74.03], EntityRabbit['Rabbit'/110, l='MpServer', x=-54.48, y=64.00, z=-70.33], EntityItem['item.item.arrow'/111, l='MpServer', x=-61.71, y=70.00, z=-24.61], EntityItem['item.item.arrow'/112, l='MpServer', x=-53.67, y=71.00, z=-29.18], EntityItem['item.item.bone'/113, l='MpServer', x=-52.63, y=70.00, z=-28.04], EntityChicken['Chicken'/114, l='MpServer', x=-57.21, y=72.00, z=4.47], EntityItem['item.item.rottenFlesh'/115, l='MpServer', x=-51.71, y=73.00, z=47.47], EntityBat['Bat'/894, l='MpServer', x=55.08, y=37.40, z=-9.54], EntityBat['Bat'/127, l='MpServer', x=-39.45, y=25.56, z=-73.33], EntityRabbit['Rabbit'/128, l='MpServer', x=-46.49, y=68.00, z=-69.49], EntityItem['item.item.arrow'/130, l='MpServer', x=-33.12, y=69.00, z=-31.88], EntityCow['Cow'/131, l='MpServer', x=-30.85, y=70.00, z=-30.47], EntityChicken['Chicken'/133, l='MpServer', x=-37.82, y=74.00, z=45.14], EntityChicken['Chicken'/134, l='MpServer', x=-42.16, y=74.00, z=42.54], EntitySkeleton['Skeleton'/1161, l='MpServer', x=-52.50, y=26.00, z=79.50], EntityBat['Bat'/397, l='MpServer', x=23.75, y=34.10, z=3.75], EntityChicken['Chicken'/142, l='MpServer', x=-30.50, y=70.00, z=-52.20], EntityBat['Bat'/398, l='MpServer', x=22.58, y=40.10, z=-6.29], EntityItem['item.item.egg'/143, l='MpServer', x=-30.39, y=70.00, z=-52.90], EntityChicken['Chicken'/144, l='MpServer', x=-17.87, y=72.00, z=-38.44], EntityChicken['Chicken'/145, l='MpServer', x=-25.26, y=71.00, z=-44.89], EntityZombie['Zombie'/147, l='MpServer', x=-9.30, y=44.00, z=-2.38], EntityVillager['Villager'/148, l='MpServer', x=-27.92, y=74.00, z=-6.49], EntityVillager['Villager'/149, l='MpServer', x=-28.93, y=74.00, z=-6.49], EntityItem['item.item.rottenFlesh'/150, l='MpServer', x=-20.89, y=75.00, z=-4.88], EntityZombie['Zombie'/151, l='MpServer', x=-18.85, y=74.94, z=-11.50], EntityItem['item.item.egg'/152, l='MpServer', x=-21.37, y=75.00, z=15.81], EntityVillager['Villager'/153, l='MpServer', x=-11.30, y=78.00, z=7.30], EntityVillager['Villager'/154, l='MpServer', x=-15.62, y=77.00, z=10.50], EntityChicken['Chicken'/155, l='MpServer', x=-25.51, y=74.00, z=0.54], EntityBat['Bat'/157, l='MpServer', x=-14.25, y=38.09, z=42.75], EntityVillager['Villager'/158, l='MpServer', x=-16.61, y=75.94, z=12.64], EntityBat['Bat'/159, l='MpServer', x=-1.45, y=50.65, z=58.68], EntityItem['item.item.egg'/416, l='MpServer', x=0.29, y=77.00, z=-19.36], EntityChicken['Chicken'/161, l='MpServer', x=-27.83, y=74.00, z=37.21], EntityWitch['Witch'/162, l='MpServer', x=-16.50, y=27.00, z=62.50], EntityChicken['Chicken'/163, l='MpServer', x=-24.79, y=71.00, z=56.58], EntityCreeper['Creeper'/164, l='MpServer', x=-19.79, y=13.00, z=75.87], EntityChicken['Chicken'/169, l='MpServer', x=-8.08, y=67.00, z=-53.74], EntityChicken['Chicken'/170, l='MpServer', x=-8.31, y=71.00, z=-42.17], EntityCow['Cow'/172, l='MpServer', x=-4.51, y=77.00, z=-13.90], EntityCow['Cow'/173, l='MpServer', x=-5.36, y=75.00, z=-29.77], EntityChicken['Chicken'/174, l='MpServer', x=6.85, y=75.00, z=-20.87], EntityItem['item.item.egg'/175, l='MpServer', x=-3.38, y=77.00, z=-3.06], EntityChicken['Chicken'/176, l='MpServer', x=-8.39, y=77.00, z=-8.11], EntityVillager['Villager'/177, l='MpServer', x=-13.70, y=78.00, z=7.30], EntityChicken['Chicken'/178, l='MpServer', x=-7.08, y=78.00, z=9.13], EntityVillager['Villager'/179, l='MpServer', x=-1.36, y=78.00, z=10.54], EntityVillager['Villager'/180, l='MpServer', x=-11.30, y=78.00, z=7.30], EntityVillager['Villager'/181, l='MpServer', x=-13.70, y=78.00, z=7.30], EntityVillager['Villager'/182, l='MpServer', x=-6.35, y=73.00, z=28.49], EntitySkeleton['Skeleton'/438, l='MpServer', x=58.50, y=34.00, z=-27.50], EntityZombieVillager['Zombie Villager'/183, l='MpServer', x=-13.47, y=40.00, z=39.77], EntityZombie['Zombie'/184, l='MpServer', x=-9.50, y=41.00, z=54.07], EntityChicken['Chicken'/192, l='MpServer', x=-10.99, y=70.00, z=84.51], EntityChicken['Chicken'/203, l='MpServer', x=14.15, y=66.00, z=-61.39], EntityZombie['Zombie'/207, l='MpServer', x=4.15, y=75.95, z=4.51], EntityVillager['Villager'/208, l='MpServer', x=2.49, y=69.02, z=3.30], EntityVillager['Villager'/209, l='MpServer', x=7.34, y=77.00, z=8.51], EntitySkeleton['Skeleton'/721, l='MpServer', x=54.50, y=16.00, z=81.50], EntityVillager['Villager'/210, l='MpServer', x=1.13, y=73.00, z=26.93], EntitySkeleton['Skeleton'/722, l='MpServer', x=56.50, y=16.00, z=79.50], EntityVillager['Villager'/211, l='MpServer', x=-5.42, y=78.00, z=-3.38], EntityVillager['Villager'/212, l='MpServer', x=8.50, y=76.00, z=10.24], EntityCreeper['Creeper'/986, l='MpServer', x=-51.80, y=16.00, z=75.44], EntityCow['Cow'/219, l='MpServer', x=17.79, y=71.00, z=-17.48], EntityCreeper['Creeper'/987, l='MpServer', x=-55.50, y=15.00, z=74.50], EntityVillager['Villager'/220, l='MpServer', x=22.67, y=70.00, z=-14.49], EntityCreeper['Creeper'/476, l='MpServer', x=41.50, y=71.00, z=-23.50], EntityChicken['Chicken'/221, l='MpServer', x=17.80, y=69.00, z=-14.80], EntitySheep['Sheep'/222, l='MpServer', x=29.76, y=73.00, z=-0.62], EntityItem['item.item.rottenFlesh'/223, l='MpServer', x=21.05, y=71.00, z=-6.75], EntityChicken['Chicken'/225, l='MpServer', x=21.70, y=73.00, z=19.90], EntitySheep['Sheep'/226, l='MpServer', x=24.69, y=72.00, z=25.83], EntityChicken['Chicken'/228, l='MpServer', x=13.86, y=71.00, z=83.35], EntitySpider['Spider'/487, l='MpServer', x=-85.50, y=17.00, z=-72.50], EntitySkeleton['Skeleton'/751, l='MpServer', x=-48.50, y=16.00, z=81.50], EntitySheep['Sheep'/242, l='MpServer', x=44.70, y=70.00, z=9.34], EntitySheep['Sheep'/243, l='MpServer', x=42.85, y=71.00, z=10.55], EntitySkeleton['Skeleton'/755, l='MpServer', x=-89.50, y=18.00, z=53.50], EntityChicken['Chicken'/244, l='MpServer', x=34.90, y=71.00, z=40.12], EntityBat['Bat'/254, l='MpServer', x=58.13, y=29.07, z=-65.57], EntityMinecartChest['Minecart with Chest'/255, l='MpServer', x=59.50, y=36.06, z=-17.50]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 286121656 bytes (272 MB) / 939524096 bytes (896 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                                      | Signature |
	|:------ |:----------------- |:------------ |:------------------------------------------- |:--------- |
	| LCHIJA | minecraft         | 1.12.2       | minecraft.jar                               | None      |
	| LCHIJA | mcp               | 9.42         | minecraft.jar                               | None      |
	| LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar               | None      |
	| LCHIJA | forge             | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar               | None      |
	| LCHIJA | creativecoredummy | 1.0.0        | minecraft.jar                               | None      |
	| LCHIJA | itemphysic        | 1.4.0        | minecraft.jar                               | None      |
	| LCHIJA | littletilescore   | 1.0.0        | minecraft.jar                               | None      |
	| LCHIJA | creativecore      | 1.10.0       | CreativeCore_v1.10.16_mc1.12.2-1.jar        | None      |
	| LCHIJA | fbp               | 2.4.1        | FancyBlockParticles-1.12.x-2.4.1.jar        | None      |
	| LCHIJA | journeymap        | 1.12.2-5.7.1 | journeymap-1.12.2-5.7.1.jar                 | None      |
	| LCHIJA | littletiles       | 1.5.0        | LittleTiles_v1.5.0-pre199_34_mc1.12.2-1.jar | None      |
	| LCHIJA | mousetweaks       | 2.10         | MouseTweaks-2.10-mc1.12.2.jar               | None      |
	| LCHIJA | neat              | 1.4-17       | Neat+1.4-17.jar                             | None      |
	| LCHIJA | soundphysics      | 1.0.4        | Sound-Physics-Mod-1.12.2.jar                | None      |

	Loaded coremods (and transformers): 
CoreModLoader (Sound-Physics-Mod-1.12.2.jar)
  com.sonicether.soundphysics.CoreModInjector
CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2-1.jar)
  
ItemPatchingLoader (ItemPhysic_Full_1.4.33_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
LittlePatchingLoader (LittleTiles_v1.5.0-pre199_34_mc1.12.2-1.jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 446.14' Renderer: 'GeForce GTX 1070 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

**Comment by CreativeMD** [comment]
What version is installed on the server?

**Comment by kieranthegoblin** [comment]
Thanks for responding. The minecraft version is 1.12.2, and the mod version I downloaded on curseforge was called LittleTiles_v1.5.0-pre199_34_mc1.12.2 which is the latest build on the site I believe.

**Comment by kieranthegoblin** [comment]
Also: If you haven't guessed already, this is a client crash and not a server crash.

**Comment by CreativeMD** [comment]
This crash occurs if the version of CreativeCore and LittleTiles are too old on the server. So are you using the same versions for the server as you have for the client?

**Comment by kieranthegoblin** [comment]
Yes, I am using versions of CreativeCore and LittleTiles that were both released on May 29 2020 so I would think they are both up to date with eachother.

**Comment by kieranthegoblin** [comment]
Sorry, I didn't read the entire question. The creative core and little tiles versions were both released at the same time, And I copied the files directly from my mods folder into the server's mod folder. Sorry if there was any confusion in the last comment.

**Comment by CreativeMD** [comment]
Can you send me the log of the server and client?

**Comment by kieranthegoblin** [comment]
This crash is a client only crash, not a server crash. I will still gladly share both files here to see if you can find something I cannot.
[ServerLog.log](https://github.com/CreativeMD/LittleTiles/files/4893914/ServerLog.log)
[ClientLog.log](https://github.com/CreativeMD/LittleTiles/files/4893937/ClientLog.log)

**Comment by CreativeMD** [comment]
The server log is of a vanilla server, so that is probably the reason for the crash. Make sure to start the forge jar in order to create a forge server.

Secondly your client log, shows an outdated version of CreativeCore which causes a crash with ItemPhysic (probably an old log).
