### ISSUE TITLE
Jei Broken Inside of Storage Blocks

### ISSUE THREAD

**Issue by mxnmnm** [CreativeMD/LittleTiles#435]
I much of JEI's functionality is broken inside of the storage block inventory or my inventory when the storage block is open (items displayed in JEI work like normal). Also I can't use More Overlay's highlight feature. The things that don't work are looking up uses/recipes and bookmarking things. 

Little Tiles: v1.5.0-pre199_34
Creative Core: v1.10.16
JEI: 4.15.0.297

**Comment by CreativeMD** [comment]
Sorry but I won't fix this. I have created my own gui api and that's why it doesn't work with these features.
