### ISSUE TITLE
The game crashes when I try to put a slice type structure in the world.

### ISSUE THREAD

**Issue by rnv812** [CreativeMD/LittleTiles#437]
The fact is that I'm trying to use your mod with another mod - Real Train Mod. These two mods work simultaneously well until I try to put a slice block. As soon as I select the second point for setting the slice block, the game immediately crashes. The problem is observed only with slice blocks. Structures such as box, cyl, sphere and other work well. It is important for me to use just these two mods. I wrote to many forums, trying to fix the conflict between the two mods, but no one could help. The crash report says that a java.lang.NoClassDefFoundError error occurs. As I understand it, this is due to the fact that in the real train mode there are also structures that can be located at different slopes, namely rails. I understand that you most likely will not begin to optimize your mod for other modifications, but I would like to ask if there is a solution to this conflict? And is it possible to solve it in any way not at the code level?

That's the crash report :

[crash-2020-07-04_10.38.32-client.txt](https://github.com/CreativeMD/LittleTiles/files/4872975/crash-2020-07-04_10.38.32-client.txt)

**Comment by CreativeMD** [comment]
There are plenty of issue with the Real Train Mod. I'm surprised you actually managed to start the game. I don't think I can do anything about it. The crash doesn't make any sense. This class exists and for some reason RTM is blocking it. Sorry, can't help you there :|
