### ISSUE TITLE
little tiles blocks not having collisions when NOT no colide structure type

### ISSUE THREAD

**Issue by MR-Spagetty** [CreativeMD/LittleTiles#439]
any little tiles structure I make acts as no collide even when I just place it with the little chisel

**Comment by MR-Spagetty** [comment]
now seems that chairs are obeying collisions

**Comment by CreativeMD** [comment]
Can you provide more information? Maybe a few screenshots? The version you use?

**Comment by MR-Spagetty** [comment]
the version of little tiles I am using is v1.5.0-pre199_34_mc1.12.2

**Comment by CreativeMD** [comment]
Screenshots. I don't really get your issue entirely.

**Comment by MR-Spagetty** [comment]
I'll give you something better
[https://youtu.be/MDAZqd6rdXs](https://youtu.be/MDAZqd6rdXs)

**Comment by CreativeMD** [comment]
That is a very weird issue. Can you try it out without any other mod installed?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it's still a problem in the newest version make sure to contact me here again.
