### ISSUE TITLE
Transparent until relog

### ISSUE THREAD

**Issue by ensis99** [CreativeMD/LittleTiles#44]
All placed tiles are invisible until relog, at which point only those placed before the relog become visible. Any new tiles placed still become invisible until the next relog.

Versions used:
LittleTiles v1.4.8 mc1.10.2
CreativeCore v1.7.3 mc1.10.2
Forge version 1.10.2-12.18.3.2221

Tested both with and without Optifine

**Comment by CreativeMD** [comment]
Does this fixes it?
https://www.dropbox.com/s/18bfc71wuat0xqo/LittleTiles%20v1.4.10%20mc1.10.2.jar?dl=1

**Comment by ensis99** [comment]
It does indeed. Thank you!

**Comment by CreativeMD** [comment]
Thanks for reporting this issue.
