### ISSUE TITLE
Door stuck in animation phase on multiplayer server (Mohist)

### ISSUE THREAD

**Issue by Noctree** [CreativeMD/LittleTiles#442]
Me and my friends are playing our modpack on a Mohist server and its hosted on Microsoft Asure. 

When I build a structure and make it into Axis Door it gets stuck as an animation and its hitbox remains the same server-side and NullPointerException is thrown in the console. 

The problem persists even with structures that remain in the same block and are just one block big (tried with a plane of wood)

**Server version:** 
Mohist-1.12.2-81a1939

**Installed plugins:**
EssentialsX
LuckPerms-Bukkit
PremiumVanish
ProtocolLib
ServerPropertiesIGE
SkinRestorer
SleepPercentage
Spark

**Server Log [here](https://pastebin.com/xQuLP03h)**

Door setup:
![2020-07-08_18 29 21](https://user-images.githubusercontent.com/17685682/86945644-8ff20e00-c149-11ea-9f98-323c1200b1d3.png)

GIF of the problem:
![LittleTilesDebug Gif](https://user-images.githubusercontent.com/17685682/86947547-32ab8c00-c14c-11ea-9a3e-e27058f8f312.gif)

**Comment by CreativeMD** [comment]
I'm sorry, but doors are not compatible with Mohist. You have to use SpongeForge if you want to have plugins and mods.
