### ISSUE TITLE
[suggestion] Special JEI Integration

### ISSUE THREAD

**Issue by mxnmnm** [CreativeMD/LittleTiles#443]
So I know you don't plan on making JEI work like normal in the storage blocks but would it be possible to have a slightly different way of integrating JEI? The JEI search bar works just fine so I was wondering if it would be possible to press control and left click a block to have it automatically searched in JEI? That way you don't have to constantly type up items when searching for a recipe and generally make it more user friendly with JEI.

**Comment by CreativeMD** [comment]
Sorry, I'm using my own gui api and that's why it doesn't work with JEI. Maybe things are different in 1.16, but for now I really need to finish 1.5.0 (that's why I have to cut some features sorry).
