### ISSUE TITLE
Optifine bad issue

### ISSUE THREAD

**Issue by Antipire** [CreativeMD/LittleTiles#449]
Mod: LittleTiles_v1.5.0-pre199_34_mc1.12.2 
Core: CreativeCore_v1.10.16_mc1.12.2. 
Optifine: OptiFine 1.12.2 HD U F5

Got issue with rendering textures properly. After restarting the game textures become invisible.
Works good without optifine, but we can't play without it. So we are looking for some troubleshooting.
![2020-07-25_23 44 26](https://user-images.githubusercontent.com/22982005/88466024-48a1a680-ced9-11ea-828c-f22224050857.png)

**Comment by kirokadura** [comment]
Which textures? If it's stuff like grass, leaves and glass, you'll have to set mipmap to at least level 1.

**Comment by kirokadura** [comment]
But I don't see anything wrong with your picture.

**Comment by Antipire** [comment]
> 
> 
> But I don't see anything wrong with your picture.

There are 2 blocks of grass on screenshot. Let me show my problem in gif
![Shish](https://user-images.githubusercontent.com/22982005/88475793-2f820f80-cf44-11ea-9b32-6a0c0228d1ab.gif)

**Comment by Antipire** [comment]
> 
> 
> Which textures? If it's stuff like grass, leaves and glass, you'll have to set mipmap to at least level 1.

It doesn't helped

**Comment by kirokadura** [comment]
I never seen that problem before but I'm pretty sure it's not caused by Optifine. I use the same versions as you and have not run into this, nor did we get any reports about it. 

Can you try with just LittleTiles, CreativeCore and Optifine in a separate profile?

**Comment by Antipire** [comment]
> 
> 
> I never seen that problem before but I'm pretty sure it's not caused by Optifine. I use the same versions as you and have not run into this, nor did we get any reports about it.
> 
> Can you try with just LittleTiles, CreativeCore and Optifine in a separate profile?

I've just reseted all graphics settings and now it works properly. So, I guess, trouble in one particular optifine setting.

Problem resolved
