### ISSUE TITLE
Crash when interacting a door.

### ISSUE THREAD

**Issue by Seyfettin1453** [CreativeMD/LittleTiles#45]
Version:1.10
I'm not using another mod.
Log:[crash-2017-05-01_18.26.58-client.txt](https://github.com/CreativeMD/LittleTiles/files/968189/crash-2017-05-01_18.26.58-client.txt)

Another issue: Tiles is not visible
I'm not using another mod.
Version:1.11

**Comment by CreativeMD** [comment]
Your LittleTiles and CreativeCore versions are not valid. You have not downloaded them from my official curseforge pages:
https://minecraft.curseforge.com/projects/creativecore
https://minecraft.curseforge.com/projects/littletiles

I do not support those versions and i have no idea where they come from. If this issue still persistent although you are using the newest versions, just reopen this issue.
