### ISSUE TITLE
Question about littleTiles json string exported from game

### ISSUE THREAD

**Issue by Cmyna** [CreativeMD/LittleTiles#450]
I am making a schematic-littleTiles converter tool. But I am not really understand the string exported by littleTiles exporter in game. What is the key "min" and its value means? And why the first element is always "I" in all arrays?
I would be appriciated if you could give me more information.

**Comment by CreativeMD** [comment]
Sorry for not responding earlier, i have overlooked your issue. The format is called snbt. The min and size are cached values. I can send you a complete overview of the meanings if you still need it.
