### ISSUE TITLE
Client crash, when rendering item.LTPremade that comes from emc.

### ISSUE THREAD

**Issue by metalim** [CreativeMD/LittleTiles#452]
MC 1.12.2

Have Minecraft instance with LittleTiles and ProjectE.
Optionally: AE2 and Equivalent Integrations.

1. Learn Tome of Knowledge in Transmutation Table to unlock all emc items, add some emc.
2. Type "item" into Transmutation Table search field. Click "right" button until crash.

Other ways to crash:
1. Set up AE2 system with terminal and storage bus on Transmutation Chamber from Equivalent Integrations with linked Talisman inside.
2. Learn Tome of Knowledge in Transmutation Table, add emc.
3. Open up AE2 terminal, type "item", observe render corruption like in screenshot. ![Screenshot](https://i.imgur.com/IvNzOJI.jpeg)
4a. Shift+click on first invisible item to get stack of it into your inventory. Crash. Also now it will crash whenever you open your inventory.
Or
4b. Click on first invisible item to hold one. You will crash, but item will drop into the world. So now you'll crash whenever you join the world.

Crashlog: [crash-2020-08-02_04.04.11-client.txt](https://github.com/CreativeMD/LittleTiles/files/5011490/crash-2020-08-02_04.04.11-client.txt)

If I understand correctly, the issue is in missing NBT, that causes LittleTiles to crash:

-- Item being rendered --
  Item Type: com.creativemd.littletiles.common.item.ItemPremadeStructure@4808bc8f
  Registry Name: littletiles:premade
  Item Aux: 0
  Item NBT: null
  Item Foil: false

**Comment by CreativeMD** [comment]
That issue should be fixed in the newest version. Can you update and test it?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists using the newest version contact me again.
