### ISSUE TITLE
[Question/suggestion] Mirror 1.12.2 LT structures

### ISSUE THREAD

**Issue by whatsapp2** [CreativeMD/LittleTiles#454]
LT version: LittleTiles_v1.5.0-pre199_25_mc1.12.2 
Forge Version: 14.23.5.2847 for Minecraft 1.12.2
So, here's my question. Is there any way I can mirror an LT structure? If there's any way to do it then, my suggestion is that if you could add a Mirror Structure Option

**Comment by kirokadura** [comment]
Press G while holding the structure and it'll mirror it. You can change the keybind in the settings.
