### ISSUE TITLE
Seems like some ASM error??

### ISSUE THREAD

**Issue by SIZStan** [CreativeMD/LittleTiles#455]
https://paste.ubuntu.com/p/k8bRQpqxw2/
I do not know what happen

**Comment by CreativeMD** [comment]
Can you send me the entire crash-report? I need the version of CreativeCore and the mod list. (Just send the full crash-report everything is include in there).

**Comment by SIZStan** [comment]
The server did not crash.
And it doesn't seem to trigger after that.
So the only thing I can offer is this
mod:
CreativeCore_v1.10.16_mc1.12.2.jar
A+Little+Extra+Tiles-1.0.7.jar
LittleTiles_v1.5.0-pre199_21_mc1.12.2.jar
littleopener-1.0.1.jar
log:
https://paste.ubuntu.com/p/4cWj2NYtN3/

**Comment by CreativeMD** [comment]
Update LittleTiles.

**Comment by CreativeMD** [comment]
I will close this issue for now it should be fixed in the newest version. If not make sure to notify me.
