### ISSUE TITLE
Crash report.

### ISSUE THREAD

**Issue by xombiekilla** [CreativeMD/LittleTiles#456]
[crash-2020-08-12_02.01.04-client.txt](https://github.com/CreativeMD/LittleTiles/files/5065378/crash-2020-08-12_02.01.04-client.txt)

It would seem that Dynamic Surroundings is conflicting with Little Tiles mod. Shame that, since both are incredible mods in their own right. If that's not the problem, then frankly I have no idea what would be.

**Comment by kirokadura** [comment]
Update CreativeCore and Dynamic Surroundings.
