### ISSUE TITLE
Block Whitelist

### ISSUE THREAD

**Issue by Cata-bre** [CreativeMD/LittleTiles#457]
Does Little Tiles have a block whitelist? In the modpack I'm currently playing I want to use several edge-less glass blocks (Managlass from Botania and Glaxx from Ztones), but none of them work with Little Tiles.

Is it possible to add compatibility between Little Tiles and blocks it doesn't already support?

**Comment by CreativeMD** [comment]
LT should accept all full blocks, but they must not have a tileentity. So if it doesn't work there is a probably a reason for it.
