### ISSUE TITLE
With the little chisel i am not right clicking but it automaticly creating suff, when i right click tho, i creates it.

### ISSUE THREAD

**Issue by Blahguy** [CreativeMD/LittleTiles#459]

**Comment by Blahguy** [comment]
Well actuly, its just when you log in your world for the first time. second time is fine, but still needs to be fixed.

**Comment by kirokadura** [comment]
I am not sure I understand. Can you explain in more detail?

**Comment by CreativeMD** [comment]
Maybe that's an issue with your moues? I  have never experienced an issue like that. I will close it for now, if it still persists provide some more information (mod list etc.)

**Comment by Blahguy** [comment]
nope

**Comment by CreativeMD** [comment]
Again I need more information
