### ISSUE TITLE
Bug or Feature

### ISSUE THREAD

**Issue by Seyfettin1453** [CreativeMD/LittleTiles#46]
Issue:Mallet splitting the structure. 
Gif: 1 FPS Gif
![issuegif](https://cloud.githubusercontent.com/assets/28264448/25756802/c7bde6bc-31d0-11e7-8b13-2db37cc31308.gif)
Can you do this? I think you can do this. :) (This is an example. Deleted after use)
![example](https://cloud.githubusercontent.com/assets/28264448/25757563/a4a2f1d8-31d3-11e7-9c62-e99ba636578e.gif)

Thank You.

**Comment by CreativeMD** [comment]
Yes the first one seems to be a weird issue, i will try to fix it soon, but what about the second thingy i couldn't really get what you mean?

**Comment by Seyfettin1453** [comment]
Sorry for my bad English. There must be a button and we have to change the pixel size by pressing on it.
This button should be a shortcut to the Config file. It's too bad to try to say something without your own language. :(

**Comment by CreativeMD** [comment]
Something like this is planned already, but it's a little bit difficult and other things have a higher priority at the moment. It will be there eventually.

**Comment by Seyfettin1453** [comment]
You can do it! I know :) Good Luck

**Comment by CreativeMD** [comment]
https://cdn.discordapp.com/attachments/256109634769780737/317688121460523008/Test.gif

Will be fixed in the next version. Thanks for reporting it.

**Comment by CreativeMD** [comment]
Fixed in v1.4.12.
