### ISSUE TITLE
LittleTiles problem - items that are interacted with are given a permission error 

### ISSUE THREAD

**Issue by MazeElwin** [CreativeMD/LittleTiles#463]
Been updating a server's mods and ran into a conflict; tracked it to 1.12.2 littletiles + creativecore.
The server runs with a dimension permission mod to manage over a bunch of things; the main one's (Build:false, Break:false, Interact:true).
for some reason when trying to open "littletiles" doors the players get an error "can not place block" and the door will not open (or will but you will be unable to move thought it).
It should allow the player to interact the the doors.
the problem only happens with the newer littletiles mod, works fine on the older version.

New (and current problem child)
-CreativeCore_v1.10.16_mc1.12.2
-LittleTiles_v1.5.0-pre199_34_mc1.12.2
-landmanager-1.12.2-1.5.0

Old (and currently working correctly)
-CreativeCore_v1.9.86_mc1.12.2
-LittleTiles_v1.5.0-pre195_mc1.12.2
-landmanager-1.12.2-1.5.0

land manager mod (https://www.curseforge.com/minecraft/mc-mods/land-manager)
Config file for landmanager -
[landmanager.txt](https://github.com/CreativeMD/LittleTiles/files/5085738/landmanager.txt)

is there some new setting I'm missing to update? or is this a bug?

Latest log-
[latest.log](https://github.com/CreativeMD/LittleTiles/files/5085718/latest.log)

**Comment by MazeElwin** [comment]
This is the complete server config + mods that currently run on the test server that's having the problem.
https://drive.google.com/file/d/1JBxpOl63fZyTtG21VBtToBt8HNpYOMSo/view?usp=sharing

**Comment by CreativeMD** [comment]
Sorry for not responding earlier.

The player needs the permission to "place" something there in order to open a door (because that is what technically happens). So is the player allowed to place something there? (if not he/she cannot open the door).

**Comment by CreativeMD** [comment]
Are you still there?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists just comment here and I will reopen it.
