### ISSUE TITLE
Sound bug with adding closing sound to sliding door

### ISSUE THREAD

**Issue by AresRedwod** [CreativeMD/LittleTiles#464]
sound doesnt trigger when right clicking the door (to close it) only when it is at its end point. When i put the closing sound on 50 tick, the sound comes even slower.

**Comment by CreativeMD** [comment]
Will be fixed in the next pre-release. Thank you very much for reporting this issue!

**Comment by CreativeMD** [comment]
New version is finally out on curseforge. Don't forget to update CreativeCore as well.
