### ISSUE TITLE
blocks goes invisible

### ISSUE THREAD

**Issue by Avox7** [CreativeMD/LittleTiles#465]
whenever i interact with a block with any of the tools that change the block itself, it goes invisible

**Comment by kirokadura** [comment]
What's the full file names for the Little Tiles, CreativeCore and Optifine (if you have it) that you're using? 

Also does this happen with any block such as cobblestone or sand or specific ones such as grass, glass and certain modded blocks?

**Comment by Avox7** [comment]
Oh sorry had only tried on grass blocks

**Comment by kirokadura** [comment]
If you're having trouble with grass, leaves and glass, enable mipmap in your settings.

**Comment by CreativeMD** [comment]
Looks like this issue is fixed right?

**Comment by BanditBloodwyn** [comment]
To be honest, it didn't help for me. I'm also using the Embeddium renderer, with 4 mipmaps. Grass blocks still go invisible. What to do?

**Comment by CreativeMD** [comment]
@BanditBloodwyn what version of LittleTiles and Embeddium are you using?
