### ISSUE TITLE
[Suggestion of Feature] having lower tier tools for better gating progress

### ISSUE THREAD

**Issue by Ethern8ai** [CreativeMD/LittleTiles#468]
Hi, as I am working on my modpack I wish to make the progression through LittleTiles more gateable, I would really love those features to give a early access to the mod but keeping half of its original functionnality for the endgame only.

The dream would be to have two hammers and two chisels, one of each being limited at 16 bits lenght instead of that possible huge zone that makes those items very overpowered to mine and to bridge, removing interest on other fun mods that are more expensive/slow/complex.
(With two tiers of tools i could gate the different tiers by adding endgame ingredients in the regular ones very easely)

Also a different workstation to build doors would be nice, or same as the tools to make the simple recepie not including doors and making a better recepie that has them, because the door system gives access to insanely cheap and powerfull elevators and with the redstonne addons it makes overpowered piston type blocks that rmoves the use of redstonne contraptions as flying machines and piston extenders.

Would be awesome features for any modpack creator being able to remove or make expensive the features that break the balance he is trying to setup, i beleive that many more creators would be up for the adventure with those extra features.

Anyway thank you for reading and for developping that amazing mod that brings beauty and creativity in our cubic worlds 🥇

**Comment by CreativeMD** [comment]
Hey there,
first of all thank you very much for your suggestions. First of all there are ways to nerf the tools in survival. Just type in /cmdconfig and go to littletiles.

There are currently no plans about different tiers of tools, but it's definitely not a bad idea. I planned some other changes in regards to crafting structures etc. but at the moment there is just too much other stuff. Maybe I will try to do something like that in 1.6.0 for 1.16.2. Unfortunately I can't guarantee anything. Hope the settings fixes your issue at least. If you need some assistance with that just ask here.

**Comment by Ethern8ai** [comment]
Hi,

Thanks for your answer, glad you like my idea, i checked up on those extra configs and there is not much to nerf there, i could nerf water or lava usage and its about it, but good to know anyway.

I hope this option will come through with the new version you are working on but sadly i think i will not be able to update my modpack to higher then 1.12.2 as it seem that few of my coremods will not be updated anymore.

No other idea to limit the size that can be digged with littlehammer and the number of bits that can be put down at once?
Or to nerf the use of doors?

No hopes on the 1.12.2 vesion getting extra configuration files at all?

Anyway thanks again and have a great time with that great piece of Art 🥇

**Comment by CreativeMD** [comment]
What kind of configuration would you need?

**Comment by Ethern8ai** [comment]
The ideal would be a way to make the door system separated somehow from the rest of the building system to have them in different tiers of progression, same with the capacity to dig or create structures of more then 16x16x16 bits in one click and drag.

Basically a way to split the nice aesthetic side from the overpowered capacity to mine/build huge components and moving structures, would be usefull for someone like me that want to give access to the basics at the start of the pack and the rest in endgame, aswell to the people that just want little tiles for the basic aesthetics.

**Comment by CreativeMD** [comment]
I was asking for configuration ... not new features. As I as said above maybe in future versions but not in 1.5.0.

**Comment by Ethern8ai** [comment]
I have no idea what can be just a configuration and not a feature, i guess configuration would be:
max distance a door can do to avoid insane elevators,
max pixels to be dig or placed at once.

if they are features i will wait and keep an eye on the changelog 👍

**Comment by CreativeMD** [comment]
Added max distance for doors to my todo list
The second one is already possible as mentioned above.

**Comment by Ethern8ai** [comment]
Oh damn, i had not seen the secound tab in /cmdconfig somehow, its not possible to have that cmd config as a file to be able to set it with default options for my pack?

Thank you very much for the support! Good luck with future progress :-D

**Comment by CreativeMD** [comment]
There is a file, but it's more convenient to configure it ingame and then take the file.

**Comment by Ethern8ai** [comment]
Oh thank you i dont know how but i had missed the maximum size removing and adding bits config in the /cmdconfig could it be possible to get a .cfg file that i can set the option by defaut for the modpack?

Thank you very much for the support and glad i made a cool suggestion for this great mod, good luck for the next updates, one of the best mod ever :D

**Comment by Ethern8ai** [comment]
Oh thank you again, seem that configuring ingame did create the file.
