### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by owo212** [CreativeMD/LittleTiles#469]
when im trying this mod it crashes and its saying:
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash:
Caught exception from LittleTiles (littletiles)
Exit code: -1

**Comment by CreativeMD** [comment]
I need the entire crash-report in order to help you.

**Comment by CreativeMD** [comment]
I will close this issue for now. Please make sure to install the newest version of CreativeCore and LittleTiles from curseforge. If it still crashes make sure to post the entire crash-report.
