### ISSUE TITLE
[1.10.2] Latest little tiles crashes with galacticraft pipes.

### ISSUE THREAD

**Issue by jawsawn** [CreativeMD/LittleTiles#47]
https://gist.github.com/JAWSAWN/b383d149eb3f123d9bb75254e41f04a1

Placing galacticraft fluid pipes crash only if there is little tiles in the pack. I also reported this to galacticraft. 
https://github.com/micdoodle8/Galacticraft/issues/2692

**Comment by CreativeMD** [comment]
Just reopen this issue if it still persists.
