### ISSUE TITLE
Is there any way i can make the guiding lines thicker?

### ISSUE THREAD

**Issue by Terra777** [CreativeMD/LittleTiles#470]
Hi so due to the shaders i use the lines that you get when you click to edit a block are really really reaaaaaaaaally hard to see. And i have to squint the entire time. Is there anything i can edit, or something to make it just a tiny bit thicker? The outline of the selection when i am trying to edit a block, you know? I have same issues with chisels and bits but that is not ur mod and dev of it is retired so i am guessing i can not get any help with that but maybe something can be done about this one. Is there anything i could do? If not i will keep using it as is, its pretty hard but at least it looks good.

**Comment by CreativeMD** [comment]
Added it to my todo list. Will be there soon.
