### ISSUE TITLE
Crash while startup

### ISSUE THREAD

**Issue by CallMeYuuuu** [CreativeMD/LittleTiles#471]
I have installes the newest Version of Little Tiles and the newest Version of Crative Core
here is the error code:
```The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: com/creativemd/creativecore/core/CreativeCoreClient
Exit Code: -1

**Comment by CallMeYuuuu** [comment]
[latest.log](https://github.com/CreativeMD/LittleTiles/files/5147068/latest.log)
this is the log file

**Comment by kirokadura** [comment]
Download LittleTiles from Curseforge only.

**Comment by CallMeYuuuu** [comment]
I downloaded it from Curseforge lol

**Comment by CreativeMD** [comment]
The filename suggest otherwise, just update CreativeCore and LittleTiles from curseforge and it should work just fine.

**Comment by CallMeYuuuu** [comment]
Hmm okey
