### ISSUE TITLE
Crash if tiles placed next to Railcraft Feeder Unit

### ISSUE THREAD

**Issue by HoasRiveor** [CreativeMD/LittleTiles#472]
If I use chisel in block space which is next to Railcraft's Admin Feeder Unit (The white with red and black frame block) it crashes when I confirm shape.

![2020-08-31_04 51 20](https://user-images.githubusercontent.com/70528724/91734281-71414e00-ebb3-11ea-8b48-1c5d5a19a72a.png)
^ if click > crash

[crash-2020-08-31_04.51.38-client.txt](https://github.com/CreativeMD/LittleTiles/files/5151034/crash-2020-08-31_04.51.38-client.txt)

**Comment by CreativeMD** [comment]
Fixed in the newest version of LittleTiles. Thanks for reporting this issue!
