### ISSUE TITLE
Crash when scrolling creative inventory

### ISSUE THREAD

**Issue by HoasRiveor** [CreativeMD/LittleTiles#473]
![2020-08-31_17 38 55](https://user-images.githubusercontent.com/70528724/91734920-3b509980-ebb4-11ea-9be0-1fddc3a9133e.png)

^ One more scroll-step and it crashes

There is no any LT stuff in this world
[crash-2020-08-31_17.33.25-client.txt](https://github.com/CreativeMD/LittleTiles/files/5151059/crash-2020-08-31_17.33.25-client.txt)

**Comment by HoasRiveor** [comment]
Doesnt seem to happen on any other tabs.

Also it freezes for ~10 sec. before crash

**Comment by HoasRiveor** [comment]
This happens only if OnlinePicFrame is installed 
[crash-2020-09-01_08.41.00-client.txt](https://github.com/CreativeMD/LittleTiles/files/5154179/crash-2020-09-01_08.41.00-client.txt)

**Comment by CreativeMD** [comment]
Update OnlinePictureFrame.
