### ISSUE TITLE
Block Resolution 

### ISSUE THREAD

**Issue by CobaltSystem67** [CreativeMD/LittleTiles#475]
Sorry about Google translate! 

I was faced with the problem of creating 512x512 blocks
(Why do I Need such a Large Resolution? - I'm going to do very large and beautiful projects, and I would like to have more fine-tuning of my projects!)
I looked at the configuration designation and even tried to configure it, but it didn't work! The resolution is still 16x16 :(

**Comment by kirokadura** [comment]
Change the "scale" setting in the littletiles.json config to 10. Don't change any other settings. That'll allow you to build up to 512. Then ingame you'll need to press CTRL+C while holding a LT tool to change the current grid size.
