### ISSUE TITLE
1.12 - Crash attempting to open LittleTiles Door after updating

### ISSUE THREAD

**Issue by anabsolutesloth** [CreativeMD/LittleTiles#477]
LittleTiles and CreativeCore versions:
Was: CreativeCore_v1.10.10_mc1.12.2 and LittleTiles_v1.5.0-pre199_19_mc1.12.2
Now: CreativeCore_v1.10.20_mc1.12.2 and LittleTiles_v1.5.0-pre199_44_mc1.12.2

Crash Log:
https://hastebin.com/viluhirohu.sql

Addtional info can be provided.

**Comment by CreativeMD** [comment]
Fixed in the newest version found on the discord server. I will try to release it on curseforge soon, but there is some more testing required.

**Comment by sukoshiotokonoko** [comment]
Can you pls update to curseforge I dont have discord and I want the mod it is wery goood and even better than chiselbits in my opion

**Comment by CreativeMD** [comment]
It's too buggy, I hope the issues can be solved the next days.

**Comment by CreativeMD** [comment]
The new version is finally out on curseforge.
