### ISSUE TITLE
Bug with Grid Size 12

### ISSUE THREAD

**Issue by scottosx** [CreativeMD/LittleTiles#48]
I am experimenting with a grid size of 12 which is much more useful for roof slopes. There is a bug though when you use the utility knife to trim off planes. Kind of hard to explain. But when you slice off the first layer it is fine. 

The second layer slices but then places an additional layer above the one you broke. You can break it and continue but it does this every other layer.

The layer count doesn't seem right either.

I am using v1.4.11 in 1.11.2 in creative mode.

I hope you can reproduce and fix this as a big advantage of LittleTiles is the configurable grid size. Let me know if you need more info or screenshots.

**Comment by scottosx** [comment]
On further inspection it appears that it is reverting to the 16 grid on alternative slices. The total layer count is still 16. I have also tried 24 and it does the same thing. You can see it in the selection bounding box as well.

The line and bar too work fine with the 12 grid size.

**Comment by CreativeMD** [comment]
I think you are talking about that bug:
![](http://i.imgur.com/FeA46Lv.png)
I will fix it soon.

**Comment by CreativeMD** [comment]
Fixed in v1.4.12.
