### ISSUE TITLE
Can't open door in server side

### ISSUE THREAD

**Issue by ChloePrime** [CreativeMD/LittleTiles#483]
LittleTiles version: `LittleTiles_v1.5.0-pre199_44_mc1.12.2`
Server Version: `CatServer-1973bbc-universal` (Forge&Bukkit Server)

Problem:
When opening a door, the door-opening animation is played, but you can't pass the door as the server pushes you back.
After the door is unloaded in the client and you load it again, it kept closed.

Expected:
Client opening a door, after the animation is played, you can pass the door without being blocked by the server, and the door should keep opened after client reloading that chunk.

**Comment by ChloePrime** [comment]
CreativeCore Version: `CreativeCore_v1.10.20_mc1.12.2`

**Comment by CreativeMD** [comment]
There is a new version of CreativeCore on the discord server which fixes this issue. I will try to release it on curseforge as soon as the other issues are fixed as well.

**Comment by CreativeMD** [comment]
Finally the new versions are out!
