### ISSUE TITLE
Crash upon entering my world 

### ISSUE THREAD

**Issue by Theamericanpilot** [CreativeMD/LittleTiles#485]
I had already used Little tiles several times in this World, both creativecore and littletiles are latest.
Before the crashes started happening I was using F3 + N to turn myself from creative to spectator. and flew around 25 blocks Before it started.

[crash-2020-09-14_18.28.24-client.txt](https://github.com/CreativeMD/LittleTiles/files/5220230/crash-2020-09-14_18.28.24-client.txt)

**Comment by CreativeMD** [comment]
Should be fixed in the newest version in the discord server. It will be released once it's stable enough.

**Comment by CreativeMD** [comment]
New version is out!
