### ISSUE TITLE
missing entities

### ISSUE THREAD

**Issue by EbolaHamster69** [CreativeMD/LittleTiles#486]
![CBCCCD18-B3D8-46D9-AA6E-93694F5541FF](https://user-images.githubusercontent.com/71333345/93220711-2ad01f80-f76d-11ea-967b-4c433e730cc0.jpeg)
i downloaded a world with little tiles mod installed and i got this, i dont know how to fix this issue
i have the latest version of little tiles and creative core

**Comment by CreativeMD** [comment]
That's not an issue.
