### ISSUE TITLE
Slice texture breaking when using CTM blocks

### ISSUE THREAD

**Issue by real-chair** [CreativeMD/LittleTiles#487]
When placing slices using blocks with connected textures, the texture appears to break and display random unconnected triangles instead of the usual slope. I'm using CTM blocks from the Chisel mod.

To recreate, launch up a world with Little Tiles and Chisel, and make a slope using a block with connected textures.

**Comment by CreativeMD** [comment]
Is fixed in a pre-release on the discord server. I will upload it to curseforge it ones it's stable enough.

**Comment by CreativeMD** [comment]
New version is available on curseforge.
