### ISSUE TITLE
Crash on activating/placing rotating door and double door blueprints after update

### ISSUE THREAD

**Issue by napstrike** [CreativeMD/LittleTiles#488]
Some creations that were working fine on the version 1.5.0-pre197_mc1.12.2 of little tiles are causing crashes on the latest v1.5.0-pre199_44_mc1.12.2 version. Some crashes do not happen all the time.
A basic rotating door blueprint that I used many times in my world causes crashes most of the time when activated (but not all the time, it is like 90%). The crash report of the activation event is here: [https://pastebin.com/zexdCJzF](https://pastebin.com/zexdCJzF)

I tried breaking and replacing the said doors, when I place them out in the open it is fine but when I place them within their usual frame the game crashes. The report of this placement event is here: [https://pastebin.com/qaFi3M0X](https://pastebin.com/qaFi3M0X)

When I place a grouped double door using its advanced blueprint the game crashes. The report is here:  [https://pastebin.com/S7C6GD6Q](https://pastebin.com/S7C6GD6Q)

All of these designs were working fine in the aforementioned older version. I have a video of them working [here](https://youtu.be/YkkS8qoI3cs). The generic door mentioned can be seen at 2:56, the double door mentioned is seen right at the beginning of the video and the front view is similar to the one in 3:09. Also, when coming close to the creation seen in 1:54 (close enough to see the bounding box) the game crashes and I can not re-enter the world without moving my character away from that device using MCedit. I had to break it using an older version of the mod, so I do not have a crash report for that event. All the tests were done in singleplayer.

**Comment by CreativeMD** [comment]
Should be fixed in the newest version on curseforge. If there are still problems just post them here and I will reopen the issue.

**Comment by napstrike** [comment]
The update fixed most of the crashes, however, not all. The custom elevator I made using little tiles used to crash the game on placement. Now I can place and activate it once, it takes me to the top floor. But when I activate it a second time to go down, the game crashes. (This used to work before). Also, when I activate it once, go 10 000 blocks away, and come back, the entire elevator contraption gets deleted. (It is not a ghost, it is completely gone.) When I paste a new copy of it, it stays there but the crashing on second use problem persists. The crash log of that is here: [https://pastebin.com/yBk91hMH](https://pastebin.com/yBk91hMH)

Another issue that I didn't report before has worsened with the update: Connected textures of chisel blocks start texture "skipping" when used with little tiles:

![2020-09-17_17 54 49](https://user-images.githubusercontent.com/63356429/93490144-c948b600-f910-11ea-8f6b-49b6755cc683.png)

![2020-09-17_17 56 04](https://user-images.githubusercontent.com/63356429/93490211-dbc2ef80-f910-11ea-9226-74083c06fe4e.png)

Before the update, looking at this structure below used to crash my game, now it doesn't crash it but the door stopped working, it seems it turned back into tiles. When I right-click on it with an empty hand, it says "link is valid". When I try to break it, it says "structure not loaded, I can only break one tile of it. After doing that, the rest starts to say "link is invalid".
![2020-09-17_18 17 17](https://user-images.githubusercontent.com/63356429/93491402-50e2f480-f912-11ea-8aa5-c8e81a24222f.png)
 I also noticed an increase in F3+A requiring "not loading in" issues. The pre199_44 version seemed to fix those issues, despite all of the crashes.

**Comment by CreativeMD** [comment]
Can you send me your world for testing?

**Comment by napstrike** [comment]
Okay, I've packaged the twitch modpack (if I send you just the world, you won't be able to open it properly), here is the link:
[https://mega.nz/file/T0cTTAxS#lL71X6u63j03KjEQ-qwGO5btLNbnVluQG2L6BlaEmBE](https://mega.nz/file/T0cTTAxS#lL71X6u63j03KjEQ-qwGO5btLNbnVluQG2L6BlaEmBE)
I wanted to send this in a private message since my pack is not complete yet but Github doesn't have that feature. So, can you please delete my message after getting the link?

**Comment by CreativeMD** [comment]
I fixed a crash, but not sure about the other issue. Can you send me the world which contains the chisel rendering issues? You can also contact me via discord to send me links privately.

**Comment by CreativeMD** [comment]
The rendering issue should be fixed now. How about the doors? Are there still any issues (make sure to use the newest version)?

**Comment by CreativeMD** [comment]
I will close this issue for now. If there are more issues just open a new one or post it here.
