### ISSUE TITLE
Custom Storage Blocks can't interact with Hopper

### ISSUE THREAD

**Issue by MasterEnderman** [CreativeMD/LittleTiles#489]
If you place a hopper above or below any custom storage block, it doesn't inser or extract any items. (same goes for any other modded pipe)

Forge: 14.23.5.2884
Creative Core: 1.10.0
LittleTiles: 1.5.0

**Comment by CreativeMD** [comment]
That's just not a feature. There might be something in the future, but not in 1.5.0, sorry.
