### ISSUE TITLE
I guess this is a texture glitch

### ISSUE THREAD

**Issue by Seyfettin1453** [CreativeMD/LittleTiles#49]
I'm using this mod with "chisels & bits" mod.

![new](https://user-images.githubusercontent.com/28264448/27012749-32316f16-4edf-11e7-94cf-10616988e12b.png)

Log:
[11 June 2017.txt](https://github.com/CreativeMD/LittleTiles/files/1066594/11.June.2017.txt)

I hope you understand these writings

**Comment by CreativeMD** [comment]
Could you send me the world?

**Comment by Seyfettin1453** [comment]
I deleted the world. Sorry :(

**Comment by CreativeMD** [comment]
Does this happen again? What exactly are you doing?

**Comment by Seyfettin1453** [comment]
OptiFine causes the problem. I am using OptiFine with Forge. 
I'm sorry for the inconvenience

**Comment by CreativeMD** [comment]
Oh okay
