### ISSUE TITLE
1.12 - Crash after Updating and using F3+A to reload chunks with LT blocks

### ISSUE THREAD

**Issue by anabsolutesloth** [CreativeMD/LittleTiles#490]
Mod versions:
Now: CreativeCore_v1.10.25, LittleTiles_v1.5.0-pre199_53
Was: CreativeCore_v1.10.10, LittleTiles_v1.5.0-pre199_19

Partial Latest.log: https://hastebin.com/ogiredisob.sql

Additional info can be provided if needed.

**Comment by CreativeMD** [comment]
Can you try out the newest version of CreativeCore and LittleTiles and see if it's fixed?

**Comment by anabsolutesloth** [comment]
Seems to still be crashing after F3+A on CreativeCore_v1.10.26 and LittleTiles_v1.5.0-pre199_54.

Partial Latest.log: https://hastebin.com/zotegeyipe.md

**Comment by CreativeMD** [comment]
It seems like CodeChickenLib is causing a couple of rendering problems. Can you test it with only CreativeCore and LittleTiles installed? I'm not sure if your graphic card might be the problem.

**Comment by ALongStringOfNumbers** [comment]
I am having similar issues after updating to LT: 1.5.0-pree199_54 and CC: 1.10.26 (After updating from LT 1.5.0-pre199_34 and CC 1.10.16), however I am not experiencing a crash, just that all structures are invisible on world load, and after using F3+A to reload, the structures appear briefly and then go invisible once again. When looking at the structures, the outline boxes can still be seen, and the structure is still there physically, it is just invisible. A partial latest.log is here with rendering errors that appeared: [Partial](https://pastebin.com/P7mwZ5mj) and the full latest.log can be found here: [Full](https://gist.github.com/ALongStringOfNumbers/1a4f5fc4691174ef858548110f5649ad) . This was tested in the Omnifactory modpack (development version on commit 129ac4e), link found here: [Omnifactory](https://github.com/OmnifactoryDevs/Omnifactory).

**Comment by CreativeMD** [comment]
The newest version of CreativeCore and LittleTiles should fix some of these issues. Can you test it?

**Comment by Kevadroz** [comment]
For me it's not a ChickenChunks Problem, but disabling VBO in Minecraft's vanilla options stops the issue from happening. (I don't have a log right now) (Didn't test on latest release)

**Comment by ALongStringOfNumbers** [comment]
After updating to LT: 1.5.0-pre199_57, there is still an invisible structure on world load, but it is only one structure that is invisible that I was standing on when loading into the world. Again after using F3+A to reload the chunks, the structure appeared briefly and then turned invisible again. All other structures were still visible after the chunk reload. Here is a full Latest.log: [Full Latest](https://gist.github.com/ALongStringOfNumbers/e9428d9114c31c46d332e92bfe66f786)

After turning VBOs off as mentioned in the comment above, the invisible structure loaded in correctly, and all other structures were correct. In addition, the GL errors seen at the end of the Latest.log stopped.

**Comment by CreativeMD** [comment]
If you use Optifine make sure to disable render regions. If VBO is disabled RAM usage is a lot higher unfortunately, so only use it if there is no way around it.

**Comment by ALongStringOfNumbers** [comment]
I am not using Optifine. In addition, these render errors persist after removing the structure, creating a new copy of the structure from a recipe in the workbench, and then re-placing the structure (With VBOs off that is).

Edit: In addition, re-enabling VBOs causes the issue to reappear for the structure.
Edit 2: The issue still persists after updating to LT 1.5.0-pre199_59 and CC 1.10.27

**Comment by CreativeMD** [comment]
@ALongStringOfNumbers what kind of graphic card do you have?

**Comment by ALongStringOfNumbers** [comment]
I am on a laptop with Integrated Graphics (Intel HD Graphics 5500)

**Comment by CreativeMD** [comment]
So do these issue still persists even if VBO is disabled?

**Comment by ALongStringOfNumbers** [comment]
The erroring structure is fixed if VBOs are disabled.

**Comment by CreativeMD** [comment]
Your graphic card is not able download render data from VRAM. No idea why, but you will have to play with vbo turned off. I will close this issue because there is nothing left to fix.
