### ISSUE TITLE
OpenPictureFrame will not load with LittleTiles installed

### ISSUE THREAD

**Issue by nycki93** [CreativeMD/LittleTiles#491]
**Environment:**
Windows 10 Home v12041.508
Oracle Java v1.8.0_51
Minecraft v1.12.2
Twitch Launcher v7.5.7419.39417

**Mods:**
Forge v14.23.5.2854
CreativeCore v1.10.25
LittleTiles v1.5.0
OpenPictureFrame v1.4.40

With just these mods, I get an error at launch:

>The game crashed whilst initializing game
>Error: java.lang.NoClassDefFoundError: com/creativemd/opf/OPFrame$1
>Exit Code: -1

If I uninstall LittleTiles or OpenPictureFrame, the game launches successfully.

**Comment by CreativeMD** [comment]
Update OnlinePictureFrame.
