### ISSUE TITLE
1.12.2 Crash while AFK after render errors occur

### ISSUE THREAD

**Issue by Nianor** [CreativeMD/LittleTiles#493]
In the new version of LT, we've had rendering errors after LT blocks spend too long on-screen, where the LT blocks vanish and other blocks start rendering in incorrect locations. Once this error triggers, an eventual crash seems to be inevitable. LT version is 199_51.
![2020-09-21_18 54 05](https://user-images.githubusercontent.com/11527859/93837699-062bea00-fc3c-11ea-86cb-9975bf16a247.png)
![2020-09-21_18 54 29](https://user-images.githubusercontent.com/11527859/93837701-088e4400-fc3c-11ea-81a0-ea5733fe8cff.png)
![2020-09-21_18 54 36](https://user-images.githubusercontent.com/11527859/93837703-09bf7100-fc3c-11ea-9f47-24a2befb8e7b.png)

[latest.zip](https://github.com/CreativeMD/LittleTiles/files/5258859/latest.zip)

**Comment by CreativeMD** [comment]
Can you please update to the newest version? Also are vbo's enabled?

**Comment by Nianor** [comment]
VBOs were enabled, and disabling them solved the issue, although it caused a noticeable performance drop. Will test with the new version when I can, which should be either later tonight or tomorrow.

**Comment by Nianor** [comment]
The newest build does absolutely nothing to fix the problem.

**Comment by Nianor** [comment]
The crashing, at least, seems sporadic and unreliable, not constant, but the render error is reliable as clockwork.

**Comment by CreativeMD** [comment]
Are you using Optifine if yes can you show me which settings you are using?

**Comment by Nianor** [comment]
No, Optifine is not installed.

**Comment by CreativeMD** [comment]
There is a new version of CreativeCore and LittleTiles, which might fix your issue.

**Comment by Nianor** [comment]
Trying with 55.

**Comment by CreativeMD** [comment]
Hm, there is an issue with Optifine and render regions. You can test the newest version if it still occurs try and disable VBO and see if it works.

**Comment by CreativeMD** [comment]
I will close this issue for now. Use the newest version disable render regions if you use Optifine, if that doesn't help you have to disable VBO.

**Comment by Nianor** [comment]
We don't use optifine and have no way to push updates to the VBO option without overriding all of people's options when they start the game. Do you know how frustrating it is having to walk every player on your server through disabling VBOs just so they can play without the world breaking around them?
