### ISSUE TITLE
Door error, latest version. Please fix.

### ISSUE THREAD

**Issue by xombiekilla** [CreativeMD/LittleTiles#494]
https://youtu.be/lyOnKDk-MK0  (Video link explaining the issue)
Forge version: 1.12.2 - 14.23.5.2854
Mod Version: LittleTiles_v1.5.0-pre199_52_mc1.12.2.jar  And  LittleTiles_v1.5.0-pre199_53_mc1.12.2.jar

**Comment by CreativeMD** [comment]
Are you on a server or is it singleplayer?

**Comment by xombiekilla** [comment]
Singleplayer

**Comment by xombiekilla** [comment]
This mod was downloaded to a client-side only server.

**Comment by CreativeMD** [comment]
Can you test the newest version of CreativeCore and LittleTiles, it might fix your issue.

**Comment by CreativeMD** [comment]
Discussion continues here: https://github.com/CreativeMD/LittleTiles/issues/496
