### ISSUE TITLE
Still a few errors. Full error summary.

### ISSUE THREAD

**Issue by xombiekilla** [CreativeMD/LittleTiles#496]
https://drive.google.com/drive/folders/19VwpBbyLeNcu0jWxYHZNVKybPcFGxyFA?usp=sharing

Mod version: LittleTiles_v1.5.0-pre199_56_mc1.12.2

Only the door for the factory. That sliding door is there and it shouldn't be. Everything was created after the most recent update changes.

**Comment by CreativeMD** [comment]
Where can I find the door? Is it in a another dimension?

**Comment by CreativeMD** [comment]
Still there?

**Comment by xombiekilla** [comment]
Sorry. I never got any notifications. So I never knew you commented here.

**Comment by xombiekilla** [comment]
Yes, I'm in a modded dimension -51, Huge Caverns Dimension.

**Comment by xombiekilla** [comment]
I'll see if I can get the Coordinates for the location.

**Comment by xombiekilla** [comment]
Destination Coordinates:
Dimension: Huge Cavern
Location: -374, 25, 523

**Comment by CreativeMD** [comment]
Solved in discord.
