### ISSUE TITLE
I believe little tiles is crashing my game

### ISSUE THREAD

**Issue by ShakeyShakes** [CreativeMD/LittleTiles#497]
I believe the little gloves in the LittleTiles mod is crashing my game when scrolling through JEI. I have the mod on a forge-1.12.2-14.23.5.2854 spongeforge server. I had this issue in singleplayer but I was recommended to install optifine and it fixed the issue. I can't do this for multiplayer so I'm stuck. https://pastebin.com/sV2SkgCv

**Comment by CreativeMD** [comment]
Fixed in the newest version of LittleTiles.
