### ISSUE TITLE
Little Glove on replace mode, Turn Tiles Invisible if all tiles are replaced at the same time.

### ISSUE THREAD

**Issue by Doc-1** [CreativeMD/LittleTiles#499]
Versions:  
LT-pre199_59
CC-v1.10.27

When using the Little Glove on the replace mode, upon replacing all tiles at the same time the tile turns invisible. They stay invisible if I use chunk update, block update, just undo, and the wrench. Only if I copy the invisible tiles then place them down, logout then log back in, or break the tiles then undo. Nothing appeared within the latest log nor debug log.
![bug](https://user-images.githubusercontent.com/45431412/94867061-77bf2180-040e-11eb-8dc6-278d13b927bd.gif)

**Comment by CreativeMD** [comment]
Should be fixed in the newest version of LittleTiles.
