### ISSUE TITLE
Colored Blocks break instantly

### ISSUE THREAD

**Issue by krwminer** [CreativeMD/LittleTiles#50]
I am using the latest LittleTiles as part of the Colonial Expansion modpack and noticed that the Colored Blocks, (specifically the Colored Clay Block but I think all blocks have this problem), break instantly if you hit with your hand.

**Comment by CreativeMD** [comment]
Oh yes, thanks for reporting. Totally forgot to add hardness to them. Will be fixed in the upcoming pre-release.

**Comment by CreativeMD** [comment]
A beta version for 1.5.0 is out.
