### ISSUE TITLE
Crash with Little Workbench in ProjectE Transmutation Table

### ISSUE THREAD

**Issue by ScottoMotto** [CreativeMD/LittleTiles#500]
Similar to issue https://github.com/CreativeMD/LittleTiles/issues/452

When the Little Workbench is added to the ProjectE Transmutation Table as EMC when typing 'Re' in the table search field the game crashes.

https://pastebin.com/w3f5FKtv

forge-14.23.5.2854
CreativeCore_v1.10.27_mc1.12.2.jar
LittleTiles_v1.5.0-pre199_59_mc1.12.2.jar
ProjectE-1.12.2-PE1.4.1.jar

Removing the NBT entry for littletiles:premade fixes it.

**Comment by CreativeMD** [comment]
Should be fixed in the newest version of LittleTiles.
