### ISSUE TITLE
I found another bug, maybe they stole this from Japan.

### ISSUE THREAD

**Issue by xombiekilla** [CreativeMD/LittleTiles#501]
![2020-10-02_19 54 49](https://user-images.githubusercontent.com/46688910/94987794-1050c100-0537-11eb-9bfa-fadfb9b32f96.png)
As you can see, CreativeMD, the problem persists. The new doors I made are overlapping with one another. But only if you place a new structure right where you have destroyed one. 

Mod version: LittleTiles_v1.5.0-pre199_60_mc1.12.2.jar

**Comment by CreativeMD** [comment]
Can you please reply to the old issue and it doesn't make sense to open a new issue for the same problem.

**Comment by xombiekilla** [comment]
Alright then.
