### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by axin0452** [CreativeMD/LittleTiles#502]
I added a name note,The client cannot start
https://paste.ubuntu.com/p/j6f6jWYjB2/

![image](https://user-images.githubusercontent.com/39695561/95007353-585c0a80-0641-11eb-99ed-0c3333152209.png)

**Comment by CreativeMD** [comment]
Pretty sure that's an issue of the filename, remove the prefex (the letters in the bracket) and it should work just fine.

**Comment by axin0452** [comment]
@CreativeMD Why not allow renaming？

**Comment by CreativeMD** [comment]
It's not forbidden just very likely that you run into issues
