### ISSUE TITLE
[Bug] Cannot save existing fixed structure to an Advanced Recipe.

### ISSUE THREAD

**Issue by Lgmrszd** [CreativeMD/LittleTiles#503]
Versions:
LT: LittleTiles_v1.5.0-pre199_62_mc1.12.2.jar
CC: CreativeCore_v1.10.28_mc1.12.2.jar
Forge: 14.23.5.2854

Steps to reproduce:
1. Have Advanced Recipe with you and fixed structure placed by another Advanced Recipe in world
2. Capture that structure with adv. recipe, open it's GUI, untick "Remember structures" box, 
3. Click "Save"
Nothing happens in game, and this error appears on server console:
https://gist.github.com/Lgmrszd/3ecabce1fea808bcacbc5770233f74ea

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thank you for reporting this issue!
