### ISSUE TITLE
Crash after Forge update

### ISSUE THREAD

**Issue by tolerus** [CreativeMD/LittleTiles#504]
[crash-2020-10-07_18.27.56-server.txt](https://github.com/CreativeMD/LittleTiles/files/5350336/crash-2020-10-07_18.27.56-server.txt)

I updated to newest 12.2.2 Forge release 14.23.5.2854 - did that cause the crash?

Should I stay on forge-1.12.2-14.23.5.2847-universal instead for compat w/ LittleTiles?

**Comment by CreativeMD** [comment]
Update OnlinePictureFrame to the newest beta version.

**Comment by tolerus** [comment]
Thanks!
