### ISSUE TITLE
Tiles Unload After Interacting with Doors

### ISSUE THREAD

**Issue by MRHLegacy** [CreativeMD/LittleTiles#505]

**Comment by kirokadura** [comment]
What LittleTiles and CreativeCore versions are you using? And if you have Optifine, is the Render Regions setting off?

**Comment by DrJigglyWiggly** [comment]
Render Regions is off and I'm using Creative Core 1.10.27 and LittleTiles 1.5.0

**Comment by kirokadura** [comment]
I'll need the full file name for Little Tiles. As for CreativeCore, it's one version behind.

**Comment by CreativeMD** [comment]
Should be fixed in the newest version of CreativeCore and LittleTiles.
