### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by Lambda-Theta-Mu** [CreativeMD/LittleTiles#506]
When Loading into a Multiplayer Server and or Singleplayer World Opaque tiles will fail to render properly and appear completely transparent, while transparent tiles, manually made to be transparent or transparent due to what block it is, will render properly.
In a Singleplayer world and in a Multiplayer Server the rendering issue will make itself apparent upon using F3+A to Reload all of the chunks rendered by the player, after which, when in a single player world, the opaque tiles will slowly render properly for the player. While in a Multiplayer Server random selections, 1m^3 in size, of Opaque tiles have a chance to not be properly rendered upon the first time the Player views the tiles, while other selections can be rendered properly by the player, in this situation using F3+A will worsen the rendering issue and eventually cause all opaque tiles to become completely transparent to the player.

[Build area rendered properly in a previous version for comparison] https://cdn.discordapp.com/attachments/276752435869908993/764909351156580363/2020-01-24_22.56.33.png

[Build area showcasing the rendering issue present] https://cdn.discordapp.com/attachments/276752435869908993/764909509688164402/unknown.png

**Comment by CreativeMD** [comment]
If you are using Optifine make sure to disable render regions. There are also some rendering issue with Phosphor so you mind what to remove that mod.

**Comment by Lambda-Theta-Mu** [comment]
I have uninstalled Phosphor and the issue persists, and I forgot to mention that I do indeed have render regions disabled within optifine

**Comment by CreativeMD** [comment]
Can you send me your modpack + your world? I really want to find out what mod is causing the issue. You could also try to just use LittleTiles and see if the issue still exists then.

**Comment by Szreku** [comment]
I have the same problem with my modpack. No matter if its on singleplayer or on a server, the problem still occurs.

My Modpack:
https://drive.google.com/drive/folders/1tX58Ov96avqOBdDgwf8L794HoTU290ch?usp=sharing

**Comment by Szreku** [comment]
[config - Copy.zip](https://github.com/CreativeMD/LittleTiles/files/5397500/config.-.Copy.zip)

**Comment by CreativeMD** [comment]
Should be fixed in the newest version of LittleTiles and CreativeCore. Would be very happy if you could test it and let me know here.

**Comment by CreativeMD** [comment]
I will close this issue for now, if there are any issue just post them here or open a new issue.
