### ISSUE TITLE
Serene Seasons Grass Color Glitch

### ISSUE THREAD

**Issue by StrawSonder** [CreativeMD/LittleTiles#507]
Upon changing the mipmap to anywhere between 1-4, with render regions off, with or without optifine, the grass would glitch so you could see through the ground.

Even if it was working at one point, as soon as you reload chunks (at least manually from hitting F3+a) the glitch would persist. From what I recall, it was only grass that had pixels from other blocks inside of it. 

Upon doing some research, I narrowed it down to one mod: Serene Seasons. Specifically, the grass color changing. Setting that option to "false" fixed my issue, with MipMap on 1.

Even upon reloading the chunks, over and over and over and over, no errors popped up, no see through grass!

While the glitch is fixed, I'm sad I can't have natural looking grass colors, so if this could be fixed in the LT mod I would be grateful!! Thank you for reading!
![image](https://user-images.githubusercontent.com/59989475/96184986-db614880-0efe-11eb-8ae8-3bc76df3b362.png)

Update (while typing this out):  Just found more see-through grass, despite reloading chunks. I'm unsure if serene seasons still has anything to do with it... All I know is, despite having found some errors, disabling the grass colors really helped.

**Comment by CreativeMD** [comment]
Sorry for not responding earlier, is it fixed now?

**Comment by StrawSonder** [comment]
Yes, I turned VBOs off (: I'll reopen this if I find it again even after this fix!

**Comment by CreativeMD** [comment]
The VBO issue should be fixed in the newer versions.
