### ISSUE TITLE
[1.12.2] Dynamic Surroundings and LittleTiles Crash

### ISSUE THREAD

**Issue by Vulant** [CreativeMD/LittleTiles#508]
Hello,

I did some research and it seems like this was an issue a while back and I'm sad to report that it has happened again.

I got a crash a few days ago in single player with little tiles and dynamic surroundings. It’s a previous bug where if you put a boat on littletiles water, it will sink to the ground and dynamic surroundings causes a crash. I’ve made sure creativecore, dynamic surroundings, and little tiles is up to date.

Crash Log: https://pastebin.com/1KsE6kPj

CreativeCore_v1.10.28_mc1.12.2.jar
DynamicSurroundings-1.12.2-3.6.1.0.jar
LittleTiles_v1.5.0-pre199_64_mc1.12.2.jar
Minecraft Version: 1.12.2
forge-14.23.5.2847

Let me know if I should post this in Dynamic Surrounding's github as well!

**Comment by CreativeMD** [comment]
Can you test if it's fixed in the newest version? (Also don't forget to update CreativeCore as well).

**Comment by Vulant** [comment]
I'll test it when I get the chance and let you know! Thanks for looking into this :)

**Comment by CreativeMD** [comment]
Any news?

**Comment by Vulant** [comment]
Just tested it. I crash upon entering the world, here is the crashlog:
https://pastebin.com/ELxfuQTZ

**Comment by Vulant** [comment]
Hold on, I see a new update for Dynamic Surroundings that says in the changelog to fix compat with little tiles. I'll let you know what happens

**Comment by Vulant** [comment]
Alright, it's fixed. Vanilla boats will float but other boat like entities like the boats from BOP will still sink to the ground.

Just to help others:

CreativeCore_v1.10.30_mc1.12.2.jar
DynamicSurroundings-1.12.2-3.6.2.0.jar
LittleTiles_v1.5.0-pre199_67_mc1.12.2.jar

**Comment by CreativeMD** [comment]
Can't do anything about the boats sorry.
