### ISSUE TITLE
Screen randomly will add red tint

### ISSUE THREAD

**Issue by NikolasGraham** [CreativeMD/LittleTiles#509]
I've just added LittleTiles_v1.5.0-pre199_64_mc1.12.2 with CreativeCore_v1.10.28_mc1.12.2. Now my screen will randomly shift hues to red for a random amount of time before returning to normal colorization. (This often repeats).

When this occurs all blocks with any opacity below 255 show as if they had 255.

**Comment by CreativeMD** [comment]
Any other mods installed?

**Comment by NikolasGraham** [comment]
This is my modpack: https://drive.google.com/drive/folders/19DD3svJqxNJ97Ngdk4vThZFyoED7fHWV?usp=sharing

Here's also a side-by-side comparison of how it's affected

![LittleTilsColorization](https://user-images.githubusercontent.com/39310301/96354518-6face600-108c-11eb-9d6f-0f69ab93a568.png)

**Comment by CreativeMD** [comment]
Is it bound to the block you hold in hand, or maybe caused by the block inspector?

**Comment by CreativeMD** [comment]
Still there?

**Comment by NikolasGraham** [comment]
Yes, sorry I have been busy. I am unsure about the block inspector, but it does occur regardless of the block in hand and including being empty handed.

**Comment by CreativeMD** [comment]
I could not reproduce this issue. Are you 100% this is caused by LT? Maybe try and remove it again?
