### ISSUE TITLE
Crash 16Oct2020

### ISSUE THREAD

**Issue by Potsukin** [CreativeMD/LittleTiles#512]
https://pastebin.com/Sunq5bkj

**Comment by CreativeMD** [comment]
There must be some kind of issue with the gui, I need your log file. Maybe it happens because you enabled stencil again?

**Comment by Potsukin** [comment]
I have never edited a Stencil in the past.
[2020-10-15-6.log.gz](https://github.com/CreativeMD/LittleTiles/files/5396799/2020-10-15-6.log.gz)

**Comment by Potsukin** [comment]
Fill mode does not work properly is happening to me too. Try testing with intricate shapes

**Comment by Potsukin** [comment]
This is probably a very rare bug. When I changed the shape to Cylinder, nothing other than Shape was displayed, so when I closed the window, Minecraft shut down. It happens many times, so I tried throwing away the Little Chisel and replacing it with a new one, but it didn't happen.

**Comment by CreativeMD** [comment]
Pretty sure this is not the right log file. I need the crashed one. I recommend to reproduce this issue and send the latest.log.

**Comment by Potsukin** [comment]
It is nearly impossible to reproduce this bug. It was happened in one Little Chisel in sudden, others was not. The error hasn't occurred since I replacing it with a new one.

**Comment by CreativeMD** [comment]
Ok, I will close this issue for now. If it happens again, make sure to send me your log file.

**Comment by Potsukin** [comment]
I was thinking of doing the same thing. The version is also 65 and may have been fixed. I will report any of the same bugs.
