### ISSUE TITLE
[Request] Armourer's Workshop support?

### ISSUE THREAD

**Issue by DoomRater** [CreativeMD/LittleTiles#514]
There are a few things that Armourer's Workshop does that I would love to see support for in LittleTiles.

First and foremost, Skin blocks do not factor into resizing when using the Advanced recipe, and doing so would mean understanding how a Skin Cube can be painted on all 6 sides.  I don't believe LT cubes can be painted uniquely on all 6 sides but taking the average of the colors would be more than sufficient at that scale.

Second, and especially if the former is just outside of the work flow, the ability to sample colors from Skin Cubes into the Little Paint Brush.  This would make it possible to manually copy most color designs from existing cosmetic pieces for the purpose of remaking statues of cosmetics in LittleTiles.

**Comment by CreativeMD** [comment]
Sorry, but I won't do that. At least not in 1.12.2. You can convert LT builds to c&b in order to use it.

**Comment by DoomRater** [comment]
I didn't ask anything about Chisels and Bits...?  In any case, it's more of a quality of life thing.  Also Armourer's Workshop is unlikely to update past 1.12.2.

I'll take a look at Extra Bit Manipulation and see if it can shrink Armourer's Skin Blocks into c&b blocks, even if it loses the color information.  That might speed up the process of recreating them...

**Comment by CreativeMD** [comment]
Again sorry, but I don't want to do it.
