### ISSUE TITLE
Slice Connection Bug

### ISSUE THREAD

**Issue by Sybertox** [CreativeMD/LittleTiles#515]
Hello, I recently discovered a bug where sometimes existing slices arbitrary connect to new-made slices 
and extend themselves if they both look in the same direction. 
If the slices look in opposite directions the existing slices will turn the new ones into non-slice tiles. The hammer can sometimes select non-existing tiles near these full tiles which cannot be removed by it. It can only remove the non-existent tiles when the selection 
has existent tiles.

This bug only happens when the already existent and new made slices are within the same block. It does not happen if they are on two different blocks.

Here are the forge and mod versions that I was using:

Forge: forge-1.12.2-14.23.5.2854-installer.jar
Creative Core: CreativeCore_v1.10.28_mc1.12.2.jar
LittleTiles: LittleTiles_v1.5.0-pre199_64_mc1.12.2.jar

I didn't use any other mod.

Here are two videos that show the bug:

https://streamable.com/hm81zc

https://streamable.com/5kplpq

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thank you very much for reporting this issue. It was quite a serious one.

**Comment by Sybertox** [comment]
I downloaded the newest versions of Creative Core (CreativeCore_v1.10.30_mc1.12.2.jar) and Little Tiles (LittleTiles_v1.5.0-pre199_67_mc1.12.2.jar). 
Slices that are facing opposite directions still sometimes turn the new-made slices into non-slice tiles. https://streamable.com/pbffub

**Comment by Sybertox** [comment]
But slices that look in the same direction don't extend the existing ones anymore.

**Comment by CreativeMD** [comment]
Fixed in the newest version :D

**Comment by Sybertox** [comment]
Now I am getting a crash whenever I try to place slices facing opposite directions next to each other with the newest version of little tiles. 
https://pastebin.com/vY9pMQxv

**Comment by CreativeMD** [comment]
Oh sorry, forgot to upload the new version of CreativeCore, should be available in a few minutes.
