### ISSUE TITLE
[Request] Limit the number of blocks that the Little Hammer can transform to tiles at a time

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [CreativeMD/LittleTiles#516]
Hello, I am working on the Omnifactory modpack, and have a request pertaining to events that have been going on in that modpack. As the modpack includes Gregtech Community Edition, ore veins are generated in massive clumps. Players are going to these large ore veins with their inventory full of Little Bags and a Little Hammer and simply selecting the entire ore vein for removal, filling the Little Bags in their inventory with near the entire vein of ore. 

I would like to ask for a limit on the number of blocks the Little Hammer can remove at a single time, to prevent the Little Hammer from being used as the best mining tool in the game. This limit can be configurable or hardcoded, it does not matter to me, as long as a limit exists.

**Comment by CreativeMD** [comment]
There are configuration options. Just use the command /cmdconfig and navigate to littletiles -> survival.
