### ISSUE TITLE
1.12 - Sudden Crash when staring at dislocated Grass texture after updating

### ISSUE THREAD

**Issue by anabsolutesloth** [CreativeMD/LittleTiles#517]
CreativeCore: 
Was: v1.10.10_mc1.12.2
Now: v1.10.29_mc1.12.2

LittleTiles:
Was: v1.5.0-pre199_19_mc1.12.2
Now: v1.5.0-pre199_65_mc1.12.2

latest.log*: https://hastebin.com/icutotopox.sql
*log was trimmed of earlier parts and some AE crafting errors

Additional Info can be provided if needed.

**Comment by CreativeMD** [comment]
I can't find a crash in there?

**Comment by anabsolutesloth** [comment]
I should specify, it was less of a crash, more of a lockup.

**Comment by CreativeMD** [comment]
You mean the game froze?

**Comment by CreativeMD** [comment]
Any news?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists just reply here.
