### ISSUE TITLE
Huge FPS drop when looking at structure

### ISSUE THREAD

**Issue by Vodulm** [CreativeMD/LittleTiles#518]
![2020-10-01_17 38 38](https://user-images.githubusercontent.com/73194834/96635221-40b0a180-1324-11eb-9ce5-9ecd4f9307a0.png)
![2020-10-01_17 38 51](https://user-images.githubusercontent.com/73194834/96635227-41e1ce80-1324-11eb-9392-47507eda781c.png)
![2020-10-01_17 38 58](https://user-images.githubusercontent.com/73194834/96635229-427a6500-1324-11eb-973a-f0f6fefa58cd.png)
![2020-10-01_17 41 27](https://user-images.githubusercontent.com/73194834/96635231-4312fb80-1324-11eb-89b7-60fd19dad27a.png)
![2020-10-01_17 41 33](https://user-images.githubusercontent.com/73194834/96635234-43ab9200-1324-11eb-97a5-b0a2a1727395.png)
![2020-10-01_17 42 32](https://user-images.githubusercontent.com/73194834/96635238-44dcbf00-1324-11eb-823e-d2a9b9165bce.png)

This yellow sphere is not a structure
![2020-10-01_17 42 36](https://user-images.githubusercontent.com/73194834/96635240-45755580-1324-11eb-8332-88b724d7f2e3.png)

Structures are imported

**Comment by Vodulm** [comment]
Seems fine in latest version

**Comment by CreativeMD** [comment]
This issue is caused by the WAILA mod. The mod which shows the tooltip at the top.
