### ISSUE TITLE
Rotating a crate makes the lid break

### ISSUE THREAD

**Issue by StrawSonder** [CreativeMD/LittleTiles#519]
On the left: Crate that **hasn't** been rotated so the axis of the lid hinge changes from  X to Y nor vise versa.

On the right: Crate that **has** been rotated so the axis of the lid hinge changes from X to Y (same with vise versa)

![image](https://user-images.githubusercontent.com/59989475/96942024-90fd4000-1499-11eb-898b-11eb1b830962.png)

Here are the settings for the lid:

![image](https://user-images.githubusercontent.com/59989475/96942166-f6513100-1499-11eb-9055-903e6f582de9.png)

If I change it to orientated instead of fixed, whenever the lid opens it clips then snaps off.

Thanks in advance for the help (:

**Comment by CreativeMD** [comment]
Can you export the structure, so I can test it myself?

**Comment by kirokadura** [comment]
This one. The textures require Biomes o Plenty. I was able to reproduce the issue by rotating an mirroring it. At certain rotations, the lid inverts the rotation and rotates inwards.

[crate.txt](https://github.com/CreativeMD/LittleTiles/files/5429639/crate.txt)

**Comment by CreativeMD** [comment]
Fixed in the newest version, unfortunately the code was executed in the wrong order which caused this issue to happen.
