### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by shishketti** [CreativeMD/LittleTiles#52]
Hey, could you make the texture of the tools a little bit more minecrafty? The optimization and features your mod adds completely beats chisel & bits, but chisel & bits has more of a "could be mistaken as actual minecraft" feel to it. Feel free to ignore the suggestion though, Great mod regardless.

**Comment by CreativeMD** [comment]
@starg09 has already worked on vanilla like textures:
https://minecraft.curseforge.com/linkout?remoteUrl=https%253a%252f%252fwww.dropbox.com%252fs%252fnilnmj51dnv66by%252fLittleTiles%2b16x16%2bTextures%2b(WIP)%2bby%2bStarg09.zip%253fdl%253d1
