### ISSUE TITLE
Bug of slice LittleTiles_v1.5.0-pre199_68

### ISSUE THREAD

**Issue by Potsukin** [CreativeMD/LittleTiles#520]
Bug of slice 

CreativeCore_v1.10.31
LittleTiles_v1.5.0-pre199_68

https://youtu.be/g5uIwHKfFVw 
https://youtu.be/6K_FIEQdKhA

**Comment by Potsukin** [comment]
Another slice bug video. Fill mode

https://youtu.be/-xyZZlaGfxU

**Comment by CreativeMD** [comment]
Can you send me your world? Would make it a lot easier for me to fix it.

**Comment by Potsukin** [comment]
which do you want, world only or world + modpack ?

**Comment by Potsukin** [comment]
Wait, I will check new version first if bugs was fixed or not

**Comment by Potsukin** [comment]
Some bugs were fixed but this one is still happening. 
https://github.com/CreativeMD/LittleTiles/issues/520#issuecomment-716101158

**Comment by CreativeMD** [comment]
Fixed a couple of issues. Download the newest CreativeCore and LittleTiles! Would be very happy if you could do some testing and tell me whether all of the issues are fixed or not.

**Comment by Potsukin** [comment]
Seems to be fixed, thank you!
