### ISSUE TITLE
Bug when deleting slices

### ISSUE THREAD

**Issue by Potsukin** [CreativeMD/LittleTiles#523]
https://youtu.be/vc9X_rgv5SQ

LittleTiles_v1.5.0-pre199_71_mc1.12.2.jar
CreativeCore_v1.10.33_mc1.12.2.jar

**Comment by CreativeMD** [comment]
Fixed in the newest version of CreativeCore. Thank you very much for posting it again and again. Really like the short videos they make it very easy for me to reproduce and fix the issue! Let's hope there will be an end soon :D
