### ISSUE TITLE
Some blocks are missing when pasting

### ISSUE THREAD

**Issue by Potsukin** [CreativeMD/LittleTiles#524]
Sometimes some blocks are missing when pasting

https://youtu.be/meCLlK05ToQ

**Comment by CreativeMD** [comment]
I could not reproduce it. Maybe try out the newest version and see if it's fixed. If not I really need the structure you used.

**Comment by Potsukin** [comment]
Going to try new version, thanks

**Comment by CreativeMD** [comment]
Any news on this?

**Comment by Potsukin** [comment]
This seems to happen with dence chunks (many blocks including slices).

**Comment by CreativeMD** [comment]
Can you record another video? I really need to know the exact circumstances in order to reproduce it.

**Comment by Potsukin** [comment]
https://youtu.be/sHYtqAr3qGE

Here is a video. It may look like a different issue, but I think the cause is the same.
 I was changed to a different block with the glove, some blocks disappeared (removed) before I knew it, and reloading the chunk did not fix it.

**Comment by Potsukin** [comment]
Another picture. Some slice blocks were lost - slice block only
![2020-11-19_bug](https://user-images.githubusercontent.com/11745850/99649187-399dc000-2a97-11eb-8f8f-7f36b233570b.jpg)

**Comment by CreativeMD** [comment]
Can you export the structure before placing it? I also need the structure you placed it against.

**Comment by CreativeMD** [comment]
I could some of the issues, not sure if all of them. We shall see when the new version is coming out.

**Comment by CreativeMD** [comment]
Should be fixed in the newest version.
