### ISSUE TITLE
Undo bug/misplaced structure randomly[LT_72 - CC_1.10.34]

### ISSUE THREAD

**Issue by Gixuu** [CreativeMD/LittleTiles#525]
Log
[latest.log](https://github.com/CreativeMD/LittleTiles/files/5471832/latest.log)
The video of this bug was in discord # issue
Mod used:
CreativeCore_v1.10.34
LittleTiles_v1.5.0-pre199_72
Optifine_1.12.2_HD_U_F5
replaymod-1.12.2-2.4.4
------------------------------
Some old bug/issue with slice
the paint tool doesn't cover all the highlighted parts for slice shape same as for hammertool

**Comment by CreativeMD** [comment]
https://cdn.discordapp.com/attachments/276752435869908993/772036675559489536/Undo_function_bugs.mp4

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
