### ISSUE TITLE
Some of the LittleTiles will not load in and I can see right though them (Forge 1.12.2-14.23.5.2847) Mod Pack

### ISSUE THREAD

**Issue by ItEsten** [CreativeMD/LittleTiles#526]
Me and my friends really love this mod and we hope that you can give us a way to fix this

**Comment by CreativeMD** [comment]
If you are using Optifine make sure render regions are turned off. Also which version of LittleTiles and CreativeCore are you using?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists post your mod list here (or provide a log file).
