### ISSUE TITLE
Huge lag spike with Little Tiles v1.5.0-pre199_43_mc.1.12.2

### ISSUE THREAD

**Issue by SrBits** [CreativeMD/LittleTiles#527]
After sometime in-game inside a world, the game freezes aswell most of my computer with it, and it keeps happening while Minecraft is open. My computer is a Samsung notebook with NVIDIA, Intel Core i5 8th Gen and 8GB of mémory. I don't know the real reasson of this since it seems to happen even with very little Tittle Tiles blocks in the world.

**Comment by CreativeMD** [comment]
I highly recommend to update to the newest version and see if it still happens. Also make sure you have enough ram assigned to minecraft.

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists in the newest version use the debug mode (F3) and send me a screenshot of it.

**Comment by SrBits** [comment]
> I will close this issue for now. If it still persists in the newest version use the debug mode (F3) and send me a screenshot of it.

![Error screenshot](https://user-images.githubusercontent.com/51025489/99189086-34124400-273e-11eb-81e9-b4c3a5571ff5.png)

In the screenshot above there's the result of the error, that usually is a game/computer freeze with or without the gray screen.
To try to solve this problem I instaled the mod FPSReducer which seemed to fix temporaly the issue, but when I remove the mod the problem comes back.

Now an error with the tape don't let me in my world:

---- Minecraft Crash Report ----
// My bad.

Time: 2020-11-15 12:21:40 GFT
Description: Unexpected error

java.lang.NullPointerException
    at com.alet.items.ItemTapeMeasure.tickPreview(ItemTapeMeasure.java:225)
    at com.creativemd.littletiles.client.render.overlay.PreviewRenderer.tick(PreviewRenderer.java:101)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_57_PreviewRenderer_tick_RenderWorldLastEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
    at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1952)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1614)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1385)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['FoxPedro2003'/40, l='MpServer', x=1141.94, y=2.00, z=-1029.62]]
  Chunk stats: MultiplayerChunkCache: 44, 44
  Level seed: 0
  Level generator: ID 01 - flat, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (1127,4,-1023), Chunk: (at 7,0,1 in 70,-64; contains blocks 1120,0,-1024 to 1135,255,-1009), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,0,-1024 to 1535,255,-513)
  Level time: 2209041 game time, 6000 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 7 total; [EntityAnimation['entity.animation.name'/48, l='MpServer', x=1130.00, y=3.00, z=-1020.00], EntityPlayerSP['FoxPedro2003'/40, l='MpServer', x=1141.94, y=2.00, z=-1029.62], EntityAnimation['entity.animation.name'/41, l='MpServer', x=1130.00, y=2.00, z=-1018.00], EntityAnimation['entity.animation.name'/42, l='MpServer', x=1130.00, y=2.00, z=-1019.00], EntityAnimation['entity.animation.name'/43, l='MpServer', x=1130.00, y=3.00, z=-1018.00], EntityAnimation['entity.animation.name'/44, l='MpServer', x=1130.00, y=3.00, z=-1018.00], EntityAnimation['entity.animation.name'/45, l='MpServer', x=1130.00, y=3.00, z=-1019.00]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 358716000 bytes (342 MB) / 771751936 bytes (736 MB) up to 2147483648 bytes (2048 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 11 mods loaded, 11 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                | Version       | Source                                    | Signature |
       |:------ |:----------------- |:------------- |:----------------------------------------- |:--------- |
       | LCHIJA | minecraft         | 1.12.2        | minecraft.jar                             | None      |
       | LCHIJA | mcp               | 9.42          | minecraft.jar                             | None      |
       | LCHIJA | FML               | 8.0.99.99     | forge-1.12.2-14.23.5.2847.jar             | None      |
       | LCHIJA | forge             | 14.23.5.2847  | forge-1.12.2-14.23.5.2847.jar             | None      |
       | LCHIJA | creativecoredummy | 1.0.0         | minecraft.jar                             | None      |
       | LCHIJA | littletilescore   | 1.0.0         | minecraft.jar                             | None      |
       | LCHIJA | creativecore      | 1.10.0        | CreativeCore_v1.10.34_mc1.12.2.jar        | None      |
       | LCHIJA | littletiles       | 1.5.0         | LittleTiles_v1.5.0-pre199_73_mc1.12.2.jar | None      |
       | LCHIJA | alet              | 1.0           | ALET-1.0.10.jar                           | None      |
       | LCHIJA | fpsreducer        | mc1.12.2-1.18 | FpsReducer-mc1.12.2-1.18.jar              | None      |
       | LCHIJA | vanillafix        | 1.0.10-150    | VanillaFix-1.0.10-150.jar                 | None      |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      CreativePatchingLoader (CreativeCore_v1.10.34_mc1.12.2.jar)
                                        
                                      LittlePatchingLoader (LittleTiles_v1.5.0-pre199_73_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 452.06' Renderer: 'GeForce MX110/PCIe/SSE2'
  Suspected Mods: A Little Extra Tiles (alet), LittleTiles (littletiles)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
  LWJGL: 2.9.4
  OpenGL: GeForce MX110/PCIe/SSE2 GL version 4.6.0 NVIDIA 452.06, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Client Crashes Since Restart: 2
  Integrated Server Crashes Since Restart: 0

**Comment by CreativeMD** [comment]
You should report this issue to the author of ALET: https://github.com/Doc-1/A-Little-Extra-Tiles
