### ISSUE TITLE
lost connection during replay (Replay mod)

### ISSUE THREAD

**Issue by Vodulm** [CreativeMD/LittleTiles#528]
https://github.com/ReplayMod/ReplayMod/issues/358#issuecomment-723603470

**Comment by CreativeMD** [comment]
This issue happens because the configuration is not loaded, maybe open a singleplayer world first and then try to load the replay.

**Comment by CreativeMD** [comment]
Any news?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists even if you log into singleplayer first just let me know here.
