### ISSUE TITLE
crash with embers broke my pack (1.12)

### ISSUE THREAD

**Issue by TandJ21** [CreativeMD/LittleTiles#53]
added little tiles to my pack as i love the mod and its causing a crash with embers so i disabled it and creative core but it still crashed my game afterwards even after disabling the mods
[crash-2017-07-20_18.18.58-client.txt](https://github.com/CreativeMD/LittleTiles/files/1163184/crash-2017-07-20_18.18.58-client.txt)

**Comment by CreativeMD** [comment]
This is an issue of CreativeCore and has been reported already. Unfortunately the author had no time to fix it yet: https://github.com/CreativeMD/CreativeCore/issues/18

LittleTiles creates a core mod inside the 1.12 folder inside your mods folder. So if you want to remove CreativeCore and LittleTiles you have to delete either the whole folder or the LittleTilesCore v1.0.0 file.
