### ISSUE TITLE
Phantom Tiles...

### ISSUE THREAD

**Issue by Vodulm** [CreativeMD/LittleTiles#530]
https://vimeo.com/478454349

**Comment by CreativeMD** [comment]
Can you send me your log file?

**Comment by Vodulm** [comment]
[2020-11-08-1.log](https://github.com/CreativeMD/LittleTiles/files/5564321/2020-11-08-1.log)

**Comment by CreativeMD** [comment]
There is nothing in the logs. Does this issue occur if you place other blocks than tnt?

**Comment by CreativeMD** [comment]
I will close it for now. If it's still an issue just reply here.

**Comment by Vodulm** [comment]
Sorry for not responding earlier.
Right now it doesnt happens with any block.
