### ISSUE TITLE
minecraft keeps crashing 

### ISSUE THREAD

**Issue by manolootje1010** [CreativeMD/LittleTiles#531]
ive tryed every version from 1.12.2 but it wont work

**Comment by manolootje1010** [comment]
it works now

**Comment by Imrtltrtl** [comment]
Did you ever find out why? Cause my game won't launch. It crashes immediately without a crash log. Also using 1.12.2.

**Comment by CreativeMD** [comment]
Make sure to install the newest version of CreativeCore, LittleTiles from curseforge (and if you are using onlinepictureframe use the newest beta).
