### ISSUE TITLE
odd glitches

### ISSUE THREAD

**Issue by zacharyhenry** [CreativeMD/LittleTiles#532]
when icolor alot of little tiles at once .... 
minecraft verision 1.12.2
forge version 14.23.5.2854
littletiles v1.50-pre199-73
![Screenshot (12)](https://user-images.githubusercontent.com/49297302/99005373-502ba080-2506-11eb-95a1-7569fb697676.png)
![Screenshot (13)](https://user-images.githubusercontent.com/49297302/99006593-56228100-2508-11eb-9502-1d059dbdcb95.png)

**Comment by CreativeMD** [comment]
I'm not sure, but maybe your graphics card is running out of VRAM. Maybe use the program GPUZ and send me a screenshot of it once the issue occurs again?

**Comment by CreativeMD** [comment]
Should hopefully be fixed in the newest version, if not just post it here again.
