### ISSUE TITLE
Blocks sometimes rendering transparant

### ISSUE THREAD

**Issue by Fureniku** [CreativeMD/LittleTiles#533]
Blocks will randomly not render/be entirely transparant. It's seemingly random, and can happen to some or all blocks in a given chunk. Couple of example images below.

CreativeCore_v1.10.34, LittleTiles_v1.5.0-pre199_73. No Optifine, but FoamFix, VanillaFix and BetterFPS are all installed which may cause problems.

Unfortunately I don't know the exact cause to reproduce it, but it does usually happen on the same blocks.

Note, in this one the railings along the top are Chisel & Bits, only the slopes which should be around the pillar are done with LT (the rest of this structure was made before adding LT :P)
![image](https://user-images.githubusercontent.com/856762/99152465-e0e6b580-2699-11eb-8192-75a0a716e12a.png)

Here, I used Glowstone on what's otherwise an ordinary block to make it light emitting (to prevent ice formation). All the brick blocks at water level are LT blocks, but only one chunks worth are not rendering. As they're solid blocks it gives that xray effect.
![image](https://user-images.githubusercontent.com/856762/99152494-14c1db00-269a-11eb-80fb-ab9c8946f575.png)

Full mod list:
![image](https://user-images.githubusercontent.com/856762/99152514-3b801180-269a-11eb-824a-c5893b30fcf1.png)
(This is also available as a modpack on Twitch: "Ultimatum Reloaded") 

Please let me know if there's any more information needed - I'm also in the Discord server if that's easier (Fureniku#4839)

**Comment by Fureniku** [comment]
Additional: I've started having the same issue on some slopes, and it seems to be doing some... weird texture offsetting above:

![image](https://user-images.githubusercontent.com/856762/99156093-421c8200-26b6-11eb-952a-8eaa38ce1100.png)

**Comment by DoomRater** [comment]
When you look at your latest log, are you seeing invalid buffer message spam from littletiles?  I am, and whacking multiple sections of misbehaving blocks with a wrench only seems to temporarily fix the issue.

I too am getting floating garbage on a server. littletiles 1.5.0-pre199_73.  Here's a snippet of the log messages I get which seem related:

https://pastebin.com/KGwFPVYU

**Comment by Yldales** [comment]
Hi, 
I'm encountering the same issues described by Fureniku.

![image](https://user-images.githubusercontent.com/50544935/100896652-23442b00-34bf-11eb-96c6-cce60e022c9d.png)

## Game Informations
**Forge**: [14.23.5.2847](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847-installer.jar)
**CreativeCore**: [1.10.34](https://media.forgecdn.net/files/3097/498/CreativeCore_v1.10.34_mc1.12.2.jar)
**LittlesTiles**: [1.5.0-pre199_73](https://media.forgecdn.net/files/3100/846/LittleTiles_v1.5.0-pre199_73_mc1.12.2.jar)

## Logs
https://pastebin.com/raw/S2ipwMJA - _Messages outputed to latest.log when the problem of invisible blocks occurs._

## Mods List
<details>
  <summary>Click to expand.</summary>

| Mod ID | Mod Name | Version |
|-|-|-|
| FML | Forge Mod Loader | 8.0.99.99 |
| bookshelf | Bookshelf | 2.3.590 |
| caliper | Caliper | 1.1.46 |
| carryon | Carry On | 1.12.3 |
| cfm | MrCrayfish's Furniture Mod | 6.3.1 |
| chisel | Chisel | MC1.12.2-1.0.2.45 |
| chiselsandbits | Chisels & Bits | 14.33 |
| crafttweaker | CraftTweaker2 | 4.1.20 |
| crafttweakerjei | CraftTweaker JEI Support | 2.0.3 |
| creativecore | CreativeCore | 1.10.0 |
| creativecoredummy | CreativeCoreDummy | 1.0.0 |
| ctgui | CT-GUI | 1.0.0 |
| ctm | CTM | MC1.12.2-1.0.2.31 |
| custommainmenu | Custom Main Menu | 2.0.9.1 |
| customnpcs | CustomNPCs | 1.12 |
| dsurround | Dynamic Surroundings | 3.6.1.0 |
| enchiridion | Enchiridion | 3.3.5 |
| **foamfix** | **FoamFix** | **0.10.10-1.12.2** |
| **foamfixcore** | **FoamFixCore** | **7.7.4** |
| forge | Minecraft Forge | 14.23.5.2847 |
| ftblib | FTB Library | 5.4.7.2 |
| ftbquests | FTB Quests | 1.9.0.12 |
| hardcoredarkness | Hardcore Darkness | 2.0 |
| iguanatweaks | IguanaTweaks Reborn | 1.4.20 |
| immersiveengineering | Immersive Engineering | 0.12-92 |
| itemfilters | Item Filters | 1.0.3.12 |
| jei | Just Enough Items | 4.15.0.269 |
| justenoughdimensions | Just Enough Dimensions | 1.6.0-dev.20191019.172643 |
| kubejs | KubeJS | forge-1.12.2-1.1.0.63 |
| ladylib | LadyLib | 2.1 |
| landmanager | Land Manager | 1.5.0 |
| littletiles | LittleTiles | 1.5.0 |
| littletilescore | LittleTilesCore | 1.0.0 |
| lumen | Lumen | 0.4.0 |
| malisiscore | MalisisCore | 1.12.2-6.5.1-SNAPSHOT |
| malisisdoors | MalisisDoors | 1.12.2-7.3.0 |
| mcmultipart | MCMultiPart | 2.5.3 |
| mcp | Minecraft Coder Pack | 9.42 |
| mekanism | Mekanism | 1.12.2-9.8.3.390 |
| mekanismgenerators | Mekanism: Generators | 1.12.2-9.8.3.390 |
| mekanismtools | Mekanism: Tools | 1.12.2-9.8.3.390 |
| minecraft | Minecraft | 1.12.2 |
| minemenu | MineMenu | 1.6.11 |
| mw | Modern Warfare 2.0 Contagion | 0.4.5.2 |
| opencomputers | OpenComputers | 1.7.5.192 |
| opencomputers\|core | OpenComputers (Core) | 1.7.5.192 |
| openfm | OpenFM | 0.1.0.19 |
| openscreens | OpenScreens | 1.0.1 |
| opframe | OnlinePictureFrame | 1.4.0 |
| **-** | **Optifine** | **HD_U_F6_pre1** |
| orelib | OreLib Support Library | 3.6.0.1 |
| ping | Ping | 1.4.5 |
| placebo | Placebo | 1.6.0 |
| realdrops | Realistic Item Drops | 1.2.14 |
| resourceloader | Resource Loader | 1.5.3 |
| scannable | Scannable | 1.6.3.24 |
| securitycraft | SecurityCraft | v1.8.19.1 |
| soundfilters | Sound Filters | 0.12_for_1.12 |
| toastcontrol | Toast Control | 1.8.1 |
| **vanillafix** | **VanillaFix** | **1.0.10-150** |
| worldedit | WorldEdit | 6.1.10 |
</details>

**Comment by CreativeMD** [comment]
Always make sure render regions is turned off.

**Comment by Yldales** [comment]
> 
> 
> Always make sure render regions is turned off.

Hi, thanks for your reply.
Optifine's Render Regions is set to OFF. Same for Fast Render and Fast Math.

**Comment by Fureniku** [comment]
I don't have Optifine installed at all, so I don't think that's the issue here.

**Comment by DoomRater** [comment]
Chalk up another non-user of Optifine.  I'll try disabling FoamFix next time I run around my server to see if anything changes there.

**Comment by CreativeMD** [comment]
I know that there are issues with Optifine render regions and Phosphor. Besides that if you have a very old graphics card you might need to disable VBO, but this will have a negative impact on your performance.

**Comment by Fureniku** [comment]
I have an RTX 3080 so hopefully I can rule that out too

**Comment by CreativeMD** [comment]
Does disable vbo change anything (you need to rejoin the world after changing the setting)?

**Comment by DoomRater** [comment]
I relaunched without Phosphor and went to the area that seemed to be messing up the most.  I still saw messages in the log about GL errors as pieces of a wall I was looking at disappeared.  So I disabled VBOs and... got a crash. https://pastebin.com/miTBSPGz  I'm going to see if I can collect any more crash reports after a full restart.

**Comment by DoomRater** [comment]
Full restart with no VBOs and no glitching or log messages so far.  Restarted with Phosphor enabled and still no issues with VBO off.  I'll update if I see anything after a day or so.

**Comment by Yldales** [comment]
> 
> 
> Does disable vbo change anything (you need to rejoin the world after changing the setting)?

After disabling VBO, the initial issue didn't occur during one game session of ~3-4 hours. However, [the second issue](https://user-images.githubusercontent.com/50544935/101133975-f7818c00-3609-11eb-806c-e67ee7311b8e.png) still occurs from time to time, without leaving any traces in the logs.

**Comment by DoomRater** [comment]
Dang the last version I was on where VBOs were on and I experienced no issues is pre199_34, probably quite a lot of changes back.  I'm going to slowly upgrade until I notice issues, and report back the earliest version I can find stuff like this going on.

**Comment by Shibva** [comment]
@CreativeMD this is the isssue I was having that I told you That I would mention back in the Enhanced Visuals Github

I think I found a way to recreate this
I have Weather2 Present and I think over time this issue exists when a Storm is being rendered, If you use the pack I gave you (provided if you still have it) You will be able to recreate this

**Comment by Shibva** [comment]
Furthermore, it might only have to do with modded blocks, for a Portal I made using your blocks does not have the issue (mod that I have noted this issue, Betwitchment Edited blocks)

Edit: VBO is on

**Comment by CreativeMD** [comment]
I have uploaded a new version in discord. I would be very happy if some of you could try it out. It's very buggy but I really hope it fixes these rendering issues ... just make sure vbo is on and backup your worlds.

**Comment by DoomRater** [comment]
Oh right I did mean to do this.  I just got a little off track...

**Comment by DoomRater** [comment]
I did some stress testing with pre295 on this very issue.  Situations that seemed to cause problems with pre199_73 have not triggered it on pre295.  Hopefully we get more people specifically testing VBOs On in their situations so we can hear back from them as well.

**Comment by CreativeMD** [comment]
Yep, the newest pre-release should be a lot better in that regard. Please turn on VBO ... I will close this issue for now. If it's still a problem either open a new issue or post it here (I will open it again).

**Comment by knobsam** [comment]
Hi, I think I can add to this issue (if necessary I can create a new issue...).

With VBOs "ON" the LT tiles are rendered transparent (or not).
I prepared a small video clip showing both settings (ON/OFF) while using and placing a torch:
-> https://youtu.be/hceKpAyFfO8

Same render problems occur when I try to place a structure from recipes or even single tiles using the Little Chisel.
Version here is latest from Curseforge (pre304).

**Edit**:
I'm unsure if maybe one of the other mods (e.g. Optifine) I use is the reason for this problem, if it is fixed for DoomRater already.
Please let me know if you need additional information (modlist, debug log etc.) which I'll provide then.

**Comment by knobsam** [comment]
**Update**:

In my settings I still had "Render Regions" set to "ON". After disabling it everything works fine (Fast Math/ Fast Render is still "ON").

**Comment by CreativeMD** [comment]
Yeah, I will add a warning if render regions is turned on at some point.

**Comment by knobsam** [comment]
Ja, that would be helpful for some users I think.

But I found another problem with blocks/tiles becoming transparent.
Sometimes, when opening/closing a door blocks/tiles/walls around the door are becoming transparent. When using a light source everything gets back to normal.

I'll play around today a little bit with my Optifine settings and check my log if I can find any useful information or output on this.
