### ISSUE TITLE
LittleStructure::tick() stops ticking after logging out and back in

### ISSUE THREAD

**Issue by Doc-1** [CreativeMD/LittleTiles#534]
In the Premade class for the forge, I am using the LittleStructure::tick() method. I've also set the attribute to Premade | Ticking. The tick method does activate after I first place the premade structure down. But, if I logout and log back in the method no longer activates. I have to place it down again.

**Comment by CreativeMD** [comment]
Will be fixed in the next version. Thanks for reporting this issue. Was a minor mistake.

**Comment by Doc-1** [comment]
Thank you as well.

**Comment by CreativeMD** [comment]
New version is finally out.
