### ISSUE TITLE
Little Paint Brush not safe to add to Morph-o-Tool

### ISSUE THREAD

**Issue by DoomRater** [CreativeMD/LittleTiles#535]
Shift-clicking on a block overwrites existing NBT data, erasing the tags a Morph-o-Tool (or Akashic Tome, if you're mad like me) uses to keep track of any item that should be a Morph-o-Tool.  It does keep its name though.

**Comment by DoomRater** [comment]
Add Little Hammer to the list of items that erase NBT tags too when going into the selection menu.  The Little Chisel, Little Saw, and Little Wrench work fine though...

Also mentioning I need to retry all of this on latest version, I'm using an out of date 1.5.0.

Edit: confirmed on pre199_73

**Comment by CreativeMD** [comment]
Is that really a bug from LT? I don't see a way to fix this ...

**Comment by DoomRater** [comment]
The key here is that NBT data is being wiped when the hammer's GUI is called to change items, but this doesn't happen with the chisel for some reason.  I'll take some closer looks through what they do when their GUIs are called and try to make sense of any differences between them to see if there's any insight I can add.

If it was consistent when calling the GUI from all tools, I might not have bothered to file a report...

**Comment by DoomRater** [comment]
https://github.com/CreativeMD/LittleTiles/blob/00af4bc8dfd0252f59632faa9f3dd3946003322c/src/main/java/com/creativemd/littletiles/client/gui/SubGuiHammer.java#L37

This is present in the hammer's SubGui's saveConfiguration() but not in the Chisel's.  I bet it's in the little paint brush's code too.

**Comment by CreativeMD** [comment]
Might be fixed in the next version, not sure if it works like that.

**Comment by DoomRater** [comment]
Seems to be working great in pre291!

**Comment by CreativeMD** [comment]
Perfect thanks!

**Comment by DoomRater** [comment]
pre298, Paint Brush ate the Tome when I changed the paint color.  Hammer doesn't.  When I revert just LT to pre291, I also see the paint brush eat the tome.  Wondering if I made a mistake, I reverted CreativeCore to 1.1.0.37.  Yikes, still eating the tome there.  I spoke too soon, the brush still has a lingering issue!  But the hammer seems completely fixed.

**Comment by CreativeMD** [comment]
Actually I have no idea. How can the hammer work and the paint brush not? I can't see a difference in code ...

**Comment by DoomRater** [comment]
I smell a mod conflict.  This scenario works in my main modpack using LT pre295 and CreativeCore 1.10.38, but not in the test modpack, which when I change LT and CreativeCore to match, the little brush gets eaten.  Since it also has A Little Extra Tiles, I tried removing that from the pack and the brush works once again without eating the Tome.

Mystery solved, I guess! Apologies for the heart attack, but now I gotta poke ALET.

**Comment by CreativeMD** [comment]
Ok nice, glad to hear that!
