### ISSUE TITLE
Grass portion of little blocks render in and out (1.12.2)

### ISSUE THREAD

**Issue by JasonFPV1** [CreativeMD/LittleTiles#539]
I'm working on making a set of advanced trapdoors for my rocket on a modified Tekxit 3 LE server, mod list below. I started with a grass block, then cut and added other little blocks to the bottom. After I finished making the door, the grass portion randomly comes in and out of visibility. I could be doing absolutely nothing and it appears or dissapears, or I could place a block next to it and it will appear. While open or moving, it's all visible and working correctly. 
When I didn't use optifine, all little tiles would go invisible after leaving line of sight to my player, so I decided to put my effort into getting it working with optifine. I have render regions disabled, VBOs enabled, and mipmap on.
Was redirected here after commenting on the curse page. I don't use git much at all, so sorry if I did anything incorrectly in this post.

![image](https://user-images.githubusercontent.com/70462817/102675647-349c6100-4168-11eb-8a11-5c6400f1510e.png)
![image](https://user-images.githubusercontent.com/70462817/102675670-47169a80-4168-11eb-8b86-2fecd5307f9b.png)
![image](https://user-images.githubusercontent.com/70462817/102675695-5564b680-4168-11eb-9a08-a7b05370688d.png)

EDIT: oops forgot in game screenshots

![image](https://user-images.githubusercontent.com/70462817/102675866-02d7ca00-4169-11eb-9654-89c27d37a39b.png)
![image](https://user-images.githubusercontent.com/70462817/102675886-1edb6b80-4169-11eb-8d3f-c20e91dab4fc.png)
![image](https://user-images.githubusercontent.com/70462817/102675918-3d416700-4169-11eb-8b85-e1329e9cde1e.png)

**Comment by CreativeMD** [comment]
Should be fixed in the newest pre-release. If it still occurs somehow just let me know here.
