### ISSUE TITLE
[1.12] CreativeMDcore crashes with embers 

### ISSUE THREAD

**Issue by jawsawn** [CreativeMD/LittleTiles#54]
https://gist.github.com/JAWSAWN/66464f6af4975773d4cf53b7300289a1

ASM'ing the tile entity list might be the cause.

**Comment by CreativeMD** [comment]
This issue has been reported already: https://github.com/CreativeMD/CreativeCore/issues/18 unfortunately the author of embers doesn't have time to fix it at the moment.
