### ISSUE TITLE
Black blocks and weird textures with World Edit and Mc Edit

### ISSUE THREAD

**Issue by Mikeman345** [CreativeMD/LittleTiles#540]
Hi, I am having this strange issue whenever I try to load a schematic with any little tiles blocks. I cannot work out what is going on at all. I am in Minecraft 1.12.2 latest forge instance too.

![2020-12-19_15 58 25](https://user-images.githubusercontent.com/76239881/102682151-15a6d900-4213-11eb-829f-4cfed8f369aa.png)

**Comment by CreativeMD** [comment]
That's not an issue of LittleTiles. Unfortunately the schematics don't really work with modded blocks, because these block ids can differ from world to world. If you want to use your builds across world it's highly recommended to use the import/ export feature of littletiles.
