### ISSUE TITLE
Blocks disappear when placing them in little bag

### ISSUE THREAD

**Issue by ftheriachab** [CreativeMD/LittleTiles#544]
Version: Little Tiles 1.5.0, Little Tiles Core 1.0.0

Blocks disappear when inserting into little bag. Maybe related issue, but each tile used cost 1 block, regardless of size.

**Comment by kirokadura** [comment]
Post the full file names for both LittleTiles and CreativeCore. As they are presented in the .jar files.

**Comment by ftheriachab** [comment]
> Post the full file names for both LittleTiles and CreativeCore. As they are presented in the .jar files.

CreativeCore_v1.10.34_mc1.12.2
LittleTiles_v1.5.0-pre199_73_mc1.12.2
forge-14.23.5.2855

**Comment by CreativeMD** [comment]
Can you show me watch kind of blocks? Maybe do a screenshot?

**Comment by ftheriachab** [comment]
I'm not at my computer at the moment, but it's all blocks. Vanilla and all modded disappear. I tried shift clicking them in as well as placing them in the bag manually. When I get home I'll try making a new pack with only the little tiles mod to test if it's a compatibility issue with another mod.

**Comment by ftheriachab** [comment]
Closing because I replicated my modpack with the same exact mods and was able to place blocks into the little bag again.  I'm unsure what mod or setting would have removed this functionality.
