### ISSUE TITLE
HELP! I added LittleTiles to my favorite modpack(don't worry. I used MultiMC) and the keybindings dont show up and when i press c nothing happens

### ISSUE THREAD

**Issue by FREINDYBEAR** [CreativeMD/LittleTiles#553]
Also, the modpack in question is world of dragons by kreezcraft.

**Comment by CreativeMD** [comment]
Make sure you are using the newest version. If that is the case optifine might block the key. You can find the key binding in the littletiles category.

**Comment by FREINDYBEAR** [comment]
Thanks! That will help!

**Comment by FREINDYBEAR** [comment]
I have the newest version. I cant find the littletiles category in the keybindings.

**Comment by CreativeMD** [comment]
Which version are you using?
