### ISSUE TITLE
Server crash Due to activate child events

### ISSUE THREAD

**Issue by MR-Spagetty** [CreativeMD/LittleTiles#556]
[crash-2021-01-03_23.23.24-server.txt](https://github.com/CreativeMD/LittleTiles/files/5767283/crash-2021-01-03_23.23.24-server.txt)
whenever a door that uses any amount of activate child events is activated the server crashes

**Comment by CreativeMD** [comment]
I don't this is an issue of LittleTiles ... looks like AdvancedRocketryPlugin is interfering somehow. Rather post this to them (maybe even at me there, so I can help them to figure out a fix).
