### ISSUE TITLE
Minecraft crashes with the latest versions in 1.12.2

### ISSUE THREAD

**Issue by Alalramrod** [CreativeMD/LittleTiles#558]
Hi there! First of all thank you for your impressive work, little tiles has always been a core mod of my builds, a really top notch mod.

I am trying to install Little Tiles in 1.12.2, but whenever I do the game crashes as soon as I load any worlds. That is, it manages to get to the main screen after loading all the mods but crashes while it loads any saves.

I believe I am using the latest of all three mod versions:

CreativeCore_v1.10.34_mc1.12.2
LittleTiles_v1.5.0-pre199_73_mc1.12.2
OnlinePicFrame_v1.5.0-pre1_mc1.12.2

The crash report summary states:
The game crashed whilst ticking entity
Error: java.lang.NoClassDefFoundError: com/creativemd/littletiles/common/blocks/BlockTile
Error code: -1

And here's a link for the detailed crash report:
[Crash report.txt](https://github.com/CreativeMD/LittleTiles/files/5770867/Crash.report.txt)

I will appreciate any help you can provide me, I am really looking forward to use your mod once more.

Thanks in advance!

**Comment by CreativeMD** [comment]
Update DynamicSurroundings
