### ISSUE TITLE
Crash when start game

### ISSUE THREAD

**Issue by Zarpyk** [CreativeMD/LittleTiles#559]
Forge version: 1.12.2-14.23.5.2838
CreativeCore version: v1.10.34_mc1.12.2
LittleTiles version: v1.5.0-pre199_73_mc1.12.2

Log: https://gist.github.com/GuerreroCraft61/48a5ec100c29f0bb892b9d7ac61fcaa3

**Comment by CreativeMD** [comment]
Whether BothSide-CreativeCore-LittleTiles_v1.5.0-pre199_73_mc1.12.2.jar is, that's not how it will work. Just download the newest version of CreativeCore and LittleTiles and it will just fine.

**Comment by Zarpyk** [comment]
The BothSide- I only add it to sort my mods, CreativeCore and LittleTiles already is the newest version
![image](https://user-images.githubusercontent.com/30746531/103667290-03989a80-4f76-11eb-96d5-ef4bccfc5df5.png)
![image](https://user-images.githubusercontent.com/30746531/103667309-0b583f00-4f76-11eb-9944-d1b744a5c788.png)
![image](https://user-images.githubusercontent.com/30746531/103667402-2c209480-4f76-11eb-81df-b1d352e4d93b.png)

**Comment by CreativeMD** [comment]
You shouldn't do that. This will mess up the launching order.

**Comment by Zarpyk** [comment]
If I'm not mistaken, in the main code, in the "@ Mod" part you can add launch it after some mod as dependency
~~(And apparently it also happens with online picture frame, but, now I see in the OPF it already have the required-after, but it crash xd)~~ (The OPF work, only I accidently added the LittleTiles again when I had previously removed it xd)

**Comment by Zarpyk** [comment]
#561
