### ISSUE TITLE
compatible issue

### ISSUE THREAD

**Issue by GeorgeClinton** [CreativeMD/LittleTiles#56]
i could just be doing something wrong but it says that the latest version works for 1.12.1 and 1.12 and i added it to my 1.12 modpack and it crashes it

**Comment by CreativeMD** [comment]
Could you send me the crash log? BTW you have to take care of CreativeCore, since there is a version for 1.12.1 and 1.12.

**Comment by CreativeMD** [comment]
I'm gonna close this issue, if this issue still persists just let me know.
