### ISSUE TITLE
[Suggestion] MC Multipart Support

### ISSUE THREAD

**Issue by juraj-hrivnak** [CreativeMD/LittleTiles#560]
Just like the title says...

#### Compatibility for basic cube-like Little tiles _(not Doors and slopes)_ for [MC Multipart](https://www.curseforge.com/minecraft/mc-mods/mcmultipart).

- Would be awesome what possibilities will be with Little Tiles and MC Multipart. _(You could do some crazy things with pipes)_

- Is good to point out that Chisels-and-Bits already has support for MC Multipart.
This is results in having both C&B and Little Tilles installed in modpacks. That can result in chaos! :D

- The Doors and Slopes will be probably nearly impossible to integrate so that's why they are not part of this suggestion.

_`side note: Thanks for making such awesome mod!`_

**Comment by CreativeMD** [comment]
Sorry, but I won't do that. C&B has it already and it works perfect. I don't see a reason to bother with it.
