### ISSUE TITLE
Blank menu when I try to make an Axis Door etc

### ISSUE THREAD

**Issue by WRXMK555** [CreativeMD/LittleTiles#562]
I press 'C' and the menu comes up, I scroll down to axis door and the menu is completely blank. I try press sliding door and then the game crashes. This has only started happening since I've updated to the latest version of Little Tiles and Creative Core.

**Comment by CreativeMD** [comment]
This should be fixed in the newest version on curseforge. Make sure to update both mods. If it still occurs just let me know here and provide a log file of it.
