### ISSUE TITLE
[pre294] Can't hammer objects in Creative

### ISSUE THREAD

**Issue by DoomRater** [CreativeMD/LittleTiles#566]
https://pastebin.com/zdF26uFW

Using the above config, I was unable to hammer stone, cobblestone, or grass in Creative mode.  After changing the creative value harvestLevelBlock to -1, I was able to once again hammer stone and grass in Creative Mode (but oddly enough, I could not hammer a block from A Little Extra Tiles, Borderless Brick Grout, even with that setting applied).

Seems limitAffectedBlocks isn't being applied when in Creative mode.

**Comment by DoomRater** [comment]
I should note that hammering this same block DOES work in survival with the above settings.

**Comment by kirokadura** [comment]
The setting that is causing this behavior is "editUnbreakable" in the Creative section.

**Comment by CreativeMD** [comment]
Delete your config file and download the newest version. I messed up the difficult configuration.
