### ISSUE TITLE
Rendering Ingredient Error

### ISSUE THREAD

**Issue by reddvilzz** [CreativeMD/LittleTiles#568]
I'm having a crash with LittleTiles showing up in the log screen when I try to search Portable Tank from Thermal Expansion.
When I type "Por" the game freezes a second and then crash. When I rejoin the world, now everytime I open my inventory it will crash directly with the same log.

Edit: Searching on the JEI @Littletiles also cause the crash.

The temporary fix is to remove the mod, open JEI and clear the search box. Then re-add the mod.

Version Tested: pre304 and pre300

Here is the [Log](https://gist.github.com/reddvilzz/cefa2231b80ba10da9440020bb7da2aa)

And the [Crash Report](https://gist.github.com/reddvilzz/2cf572f4ac26fff80e1ecff515b651ef)

**Comment by CreativeMD** [comment]
Just update CreativeCore that would fix it.

**Comment by reddvilzz** [comment]
Okay, that fixed it thanks!
