### ISSUE TITLE
LittleTiles Mod - Inventory Corrupts and Large Chunk Area Corrupts

### ISSUE THREAD

**Issue by Prochicken19** [CreativeMD/LittleTiles#57]
## Hello,
First off love the mod very useful. However during my time with the mods there have been alot of problems surrounding these two issues.
**The first issue** is a inventory corruption. This i found usually occurs after making a little recipe of something with too many tiles. The fix we found for this was just wiping the player's inventory.
**The second** issues isn't so easily fix. When placing a little recipe fixed that has alot of tiles (One of my pieces was 1300) a large area roughly 25ish chunks becomes corrupts. The fix we found is that we have to regenerate the area back to say 20 minutes ago removing the piece. My friend says its because of the amount of tiles allowed. Now when we searched for the config, we discovered there was none for our version. Is there ment to be a config?

**Game Details:**
Game Version: 1.7.10
Version Of Mod: LittleTiles v1.2.0 mc1.7.10.jar

**Thanks for your time
~Prochicken**

**Comment by CreativeMD** [comment]
Hey,
sorry for my late response. Those are issues which still exist in 1.3.0 & 1.4.0, but don't occur as fast as in 1.2.0. What happens is that you basically reach the storage limit, which will result in not saving the data. 1.5.0 (pre-release) is compromising the data, so this limit will not be reached even if you build a lot of stuff.

I'm sorry to disappoint you, but i will not port 1.5.0 back. I don't support any versions below 1.11.2 anymore :( Hope you can understand that.

**Comment by Prochicken19** [comment]
Ah thats fine that, i understand, Thanks for the response
