### ISSUE TITLE
Weird block rendering glitch Little Tiles 199_73 1.12.2

### ISSUE THREAD

**Issue by SrBits** [CreativeMD/LittleTiles#571]
I am working on a huge map where some of the Chisels and Bits blocks are being updated to Little Tiles', and I've been noticing these rendering glitches as the one shown bellow, I don't know it it's a C&B's error, Chisel's (Other building mod) or LT's...

There is also errors with huge chunks of blocks disapearing after a chunk is updated.
![image](https://user-images.githubusercontent.com/51025489/104379850-d6656280-5508-11eb-9a35-a6c173f22a44.png)

**Comment by kirokadura** [comment]
Update to the latest version and disable Render Regions.

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still happens just let me know here.
