### ISSUE TITLE
LittleTiles Client Crash

### ISSUE THREAD

**Issue by MrHermis** [CreativeMD/LittleTiles#572]
Hi!

I got an issue with LittleTiles. I've made a door like the one you made in your video, the problem for me is that it crashes my client. The crash occurs when the door itself get closed and on when the ''wheel/handle'' does it animation/spinning it crashes.
I've looked through this site for fixes and updated LittleTiles + CreativeCore without result. I have also removed nearly all mods just to see if they are interfering with the mod but it doesn't seem like it. Anyhow thought I'd see if you have any fix for it?

Forwarding my crash log if you wanna take a look at it.
[crash-2021-01-14_03.03.22-client.txt](https://github.com/CreativeMD/LittleTiles/files/5811999/crash-2021-01-14_03.03.22-client.txt)

**Comment by MrHermis** [comment]
Made another structure and I think the problem has to do with Position Events under Advanced Door cause every time I close a structure after opening it the game crashes.

**Comment by MrHermis** [comment]
Tried making another door with Keep Animated on both the handle and the door itself and it seems to work now.

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thank you very much for reporting this issue!
