### ISSUE TITLE
Trying to view recipe (in JEI) for Little Workbench crashes the game.

### ISSUE THREAD

**Issue by Lgmrszd** [CreativeMD/LittleTiles#573]
How to reproduce:
1) Open JEI
2) Try to check Little Workbench recipe

[Crash report](https://pastebin.com/Z3QaMBfM)

Versions:
Forge: 14.23.5.2854
LittleTiles: v1.5.0-pre309_mc1.12.2
CreativeCore: v1.10.42_mc1.12.2
JEI: 1.12.2-4.16.1.302

**Comment by mxnmnm** [comment]
A similar thing happened to me when I tried to look up a recipe for some of the new redstone stuff

https://gist.github.com/mxnmnm/4e9e6da31a610add984b67a31ab92052

**Comment by CreativeMD** [comment]
Fixed in the newest version, sorry for the inconvenience.
