### ISSUE TITLE
Display problem in the rendering window with the latest version of the mod.

### ISSUE THREAD

**Issue by HDL34** [CreativeMD/LittleTiles#575]
That's it, I updated to the latest version of the mod but there's a rendering display problem in the attached window.
![image](https://user-images.githubusercontent.com/61374058/104902208-bb6a7680-597e-11eb-963d-5315ea6a35ec.png)
My construction is simply not visible. So I don't know how to see whether I took it in the diagram or not. Nor see the animation if I create it.
I'm attaching my mod pack with the latest version of the mod.
https://www.transfernow.net/LRy1tQ012021

**Comment by CreativeMD** [comment]
it would be very good to have the log, as well as the structure you are actually trying to modify (if you can export it).

You might have posted that stuff on discord already, but it would be nice to have it here.

**Comment by HDL34** [comment]
With my any littletiles creation I have the problem. Even with new created with the latest version. DOnc if I give you my creations or if you create something, it's the same.

**Comment by CreativeMD** [comment]
So I guess I can close it now?
