### ISSUE TITLE
Door axis position bug

### ISSUE THREAD

**Issue by Achievable** [CreativeMD/LittleTiles#576]
When selecting Even mode _and_ a grid that's 32 or smaller in either the axis or advanced door, the axis position and size are changed after saving. Seems to behave fine if old one of the conditions is met. 
![2021-01-18_19 54 01](https://user-images.githubusercontent.com/43967785/104949069-04deb400-59c7-11eb-93c8-fb507b0200de.png)
![2021-01-18_19 54 14](https://user-images.githubusercontent.com/43967785/104949082-0a3bfe80-59c7-11eb-9b92-fec39d78166d.png)

**Comment by CreativeMD** [comment]
Fixed
