### ISSUE TITLE
Crash when using Colorize Mode with a recipe

### ISSUE THREAD

**Issue by kirokadura** [CreativeMD/LittleTiles#577]
**LittleTiles version:** LittleTiles_v1.5.0-pre314_mc1.12.2.jar
**CreativeCore version:** CreativeCore_v1.10.44_mc1.12.2.jar
[Crash_Letters.txt](https://github.com/CreativeMD/LittleTiles/files/5838924/Crash_Letters.txt)

When using colorize mode with a recipe, this crash was the result.

[Export](https://github.com/CreativeMD/LittleTiles/files/5838924/Crash_Letters.txt)

[Crash report](https://github.com/CreativeMD/LittleTiles/files/5838922/crash-2021-01-19_20.25.58-client.txt)

**Comment by CreativeMD** [comment]
Fixed
