### ISSUE TITLE
bug/crash pre311

### ISSUE THREAD

**Issue by Potsukin** [CreativeMD/LittleTiles#579]
https://youtu.be/n4zqxnu6Lu0

1.New items does not appear in JEI

2.　Crash when clicking the arrow on the right in Glove
https://pastebin.com/TskhFusv

**Comment by Potsukin** [comment]
2.　Crash when clicking the right arrow of Glove
https://pastebin.com/TskhFusv

**Comment by CreativeMD** [comment]
Update ALET.
