### ISSUE TITLE
The game crash after i place some modified blocks 

### ISSUE THREAD

**Issue by IRINEU31** [CreativeMD/LittleTiles#58]
heres the report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore-1.11.2 (1).jar)
  BIFLoader (BowInfinityFix-1.11.x-rv4.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+dev.92.jar)
  NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  LittlePatchingLoader (LittleTiles v1.5.0-pre25 mc1.11.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.2-3.4.7.jar)
  FarseekCoreMod (Farseek-1.11-2.2.jar)
  IC2core (industrialcraft-2-2.7.81-ex111.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 9/26/17 2:06 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: com.creativemd.creativecore.common.utils.HashMapList.getValues()Ljava/util/Collection;
	at com.creativemd.littletiles.common.utils.nbt.LittleNBTCompressionTools.writeTiles(LittleNBTCompressionTools.java:34)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.func_189515_b(TileEntityLittleTiles.java:658)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:392)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:184)
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:203)
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:231)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1015)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:366)
	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:325)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:647)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 208501312 bytes (198 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2476 Optifine OptiFine_1.11.2_HD_U_C3 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2476.jar) 
	UCHIJAAAA	forge{13.20.1.2476} [Minecraft Forge] (forge-1.11.2-13.20.1.2476.jar) 
	UCHIJAAAA	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJAAAA	littletilescore{1.0.0} [LittleTilesCore] (minecraft.jar) 
	UCHIJAAAA	bowinfinityfix{rv4} [Bow Infinity Fix] (minecraft.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJAAAA	uncraftingtable{1.7.5} [Uncrafting Table] ([1.11.2]UncraftingTable-1.7.5.jar) 
	UCHIJAAAA	adobeblocks{7.0.1} [Adobe Blocks 2] (AdobeBlocks-1.11.2-7.0.1.jar) 
	UCHIJAAAA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJAAAA	xaerobetterpvp{1.13.1} [Better PvP] (BetterPvP_1.13.1_Forge_1.11.jar) 
	UCHIJAAAA	biomesoplenty{6.2.0.2256} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.2.0.2256-universal.jar) 
	UCHIJAAAA	buildcraftlib{7.99.4} [BuildCraft Lib] (buildcraft-7.99.4.jar) 
	UCHIJAAAA	buildcraftcore{7.99.4} [BuildCraft] (buildcraft-7.99.4.jar) 
	UCHIJAAAA	buildcraftfactory{7.99.4} [BC Factory] (buildcraft-7.99.4.jar) 
	UCHIJAAAA	buildcrafttransport{7.99.4} [BC Transport] (buildcraft-7.99.4.jar) 
	UCHIJAAAA	buildcraftbuilders{7.99.4} [BC Builders] (buildcraft-7.99.4.jar) 
	UCHIJAAAA	buildcraftenergy{7.99.4} [BC Energy] (buildcraft-7.99.4.jar) 
	UCHIJAAAA	buildcraftrobotics{7.99.4} [BC Robotics] (buildcraft-7.99.4.jar) 
	UCHIJAAAA	buildcraftsilicon{7.99.4} [BC Silicon] (buildcraft-7.99.4.jar) 
	UCHIJAAAA	carryon{1.3} [Carry On] (CarryOn MC1.11.2 v1.3.jar) 
	UCHIJAAAA	cookingforblockheads{5.3.27} [Cooking for Blockheads] (CookingForBlockheads_1.11.2-5.3.27.jar) 
	UCHIJAAAA	creativecore{1.7.4} [CreativeCore] (CreativeCore-1.11.2 (1).jar) 
	UCHIJAAAA	thutcore{4.4.2} [ThutCore] (ThutCore-1.11.2.jar) 
	UCHIJAAAA	thuttech{5.0.0} [Thut's Tech] (Elevators-mod-by-thutmose-1.11.2.jar) 
	UCHIJAAAA	farseek{2.2} [Farseek] (Farseek-1.11-2.2.jar) 
	UCHIJAAAA	furniture{1.1.3} [How 'Bout That Furniture] (HowBoutThatFurniture-1.2.1.jar) 
	UCHIJAAAA	ic2{2.7.81-ex111} [IndustrialCraft 2] (industrialcraft-2-2.7.81-ex111.jar) 
	UCHIJAAAA	inventorytweaks{1.63+dev.92.4367155} [Inventory Tweaks] (InventoryTweaks-1.63+dev.92.jar) 
	UCHIJAAAA	ironchest{1.11.2-7.0.24.809} [Iron Chest] (ironchest-1.11.2-7.0.24.809.jar) 
	UCHIJAAAA	iv{2.0.5} [Improved Villagers] (iv-2.0.5.jar) 
	UCHIJAAAA	jei{4.5.1.296} [Just Enough Items] (jei_1.11.2-4.5.1.296.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.5.0} [JourneyMap] (journeymap-1.11.2-5.5.0.jar) 
	UCHIJAAAA	littletiles{1.5.0} [LittleTiles] (LittleTiles v1.5.0-pre25 mc1.11.2.jar) 
	UCHIJAAAA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.11.2-1.7.4.jar) 
	UCHIJAAAA	shetiphiancore{3.4.7} [ShetiPhian-Core] (shetiphiancore-1.11.2-3.4.7.jar) 
	UCHIJAAAA	silentlib{2.2.6} [Silent Lib] (SilentLib-1.11.2-2.2.6-66.jar) 
	UCHIJAAAA	silentgems{2.4.5} [Silent's Gems] (SilentsGems-1.11.2-2.4.5-213.jar) 
	UCHIJAAAA	streams{0.3} [Streams] (Streams-1.11-0.3.jar) 
	UCHIJAAAA	tombstone{1.3.6} [Corail Tombstone] (tombstone-1.3.6-1.11.2.jar) 
	UCHIJAAAA	bspkrscore{at_0.9} [bspkrsCore] (TreeCapitator-Mod-1.11.2.jar) 
	UCHIJAAAA	treecapitator{at_0.9} [Treecapitator] (TreeCapitator-Mod-1.11.2.jar) 
	UCHIJAAAA	wearablebackpacks{2.3.0} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.3.0.jar) 
	UCHIJAAAA	wit{1.0.22} [WIT] (WIT-1.11-1.0.22-41.jar) 
	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore-1.11.2 (1).jar)
  
BIFLoader (BowInfinityFix-1.11.x-rv4.jar)
  com.github.parker8283.bif.Transformer
Inventory Tweaks Coremod (InventoryTweaks-1.63+dev.92.jar)
  invtweaks.forge.asm.ContainerTransformer
NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
LittlePatchingLoader (LittleTiles v1.5.0-pre25 mc1.11.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
ShetiPhian-ASM (shetiphiancore-1.11.2-3.4.7.jar)
  shetiphian.core.asm.ClassTransformer
FarseekCoreMod (Farseek-1.11-2.2.jar)
  farseek.core.FarseekClassTransformer
IC2core (industrialcraft-2-2.7.81-ex111.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Grosvaldinho'/31, l='Testes', x=-1061.35, y=55.00, z=1258.47]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.11.2_HD_U_C3
	Render Distance Chunks: 5
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 20.19.15.4642
	OpenGlRenderer: Intel(R) HD Graphics 5500
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by CreativeMD** [comment]
Please don't download my mods from any other website than curseforge. Just watch this video, it might helps you to understand the situation: https://www.youtube.com/watch?v=QTh9ZN9SIp8

If this issue still persists just reopen it.
