### ISSUE TITLE
Suggestion: automatic placement rotation

### ISSUE THREAD

**Issue by juraj-hrivnak** [CreativeMD/LittleTiles#580]
- Instead of using arrows to rotate the little tiles structure, it will be done automatically ( if enabled)
The whole point is to be more intuitive for players who came from Chissels&Bits of TerraFirmaCraft.

- Here is an example:
https://user-images.githubusercontent.com/71150936/105179923-36bc5b80-5b2a-11eb-927a-c371306b32f7.mp4

`PS: I thought - rotation is already there, so checking for player rotation and rotating it wouldn't be a problem.`

Thanks

**Comment by CreativeMD** [comment]
I'm not really a fan of that. It used to be a feature very early, but I removed it. It just doesn't work with huge structures. I know the arrow keys feel a little weird but you will get used to it.
