### ISSUE TITLE
Crash with pre311+

### ISSUE THREAD

**Issue by knobsam** [CreativeMD/LittleTiles#581]
Hi,

I've encountered a weird crash ([log here](https://pastebin.com/YkmuwUWw)).
Interesting point is, that I do not have a "crash log", the client totally froze and I had to kill it.
Stack trace was in the normal log file (I cut everything which was just loading of Minecraft before the crash).

Here's what I did to get this crash:
- Cut parts out of LT block (and structure)
- Structure was removed instead of selected area
- Tried to replace structure (Ctrl-Z)
- Only half the removed items are back
- Copy block (Middle Mouse)
- Try to place block
- Crash

I'm on yesterdays update for both LittleTiles and CreativeCore.

Best regards,

Samuel

*Edit*: Added/replaced structure (instead of block)

**Comment by CreativeMD** [comment]
Make sure the same mods are installed on server and client (at least my mods). Mods like EnhancedVisuals, ItemPhysic have to be installed on the server otherwise the system doesn't work.

**Comment by knobsam** [comment]
Mh, I'm a little bit clueless here. Mods on client and server side do match and everything worked before I updated to latest CreativeCore and LittleTiles (now on pre315). I'll try a rollback to pre311 and .42 (CreativeCore).
**Update**: It also crashes, but MC does not freeze. After reconnecting to the server the LT structures are missing (which I tried to get back using Ctrl+Z).

For now, I've attached the full [latest.log](https://github.com/CreativeMD/LittleTiles/files/5850415/latest.log).

Another idea, I've also updated the mod foamfix to v0.10.11 (was 0.10.10 before). Maybe there is an incompatibility here?

Here are all my mods on server-side:
![server mods](https://user-images.githubusercontent.com/17403095/105375303-e7009180-5c08-11eb-8dbf-002d708c6896.png)

And on client-side (some are not required on the server):
![client mods](https://user-images.githubusercontent.com/17403095/105375721-3f379380-5c09-11eb-9854-13c4eaa4f2e0.png)

**Comment by CreativeMD** [comment]
I'm not sure about your list, Optifine is installed on server side? Can you send me the server log file?

**Comment by knobsam** [comment]
As far as I remember the Forge console said it is required.

But anyway... I set up a new Minecraft installation with just Forge and LittleTiles (pre319 now) and no server.
The crash is still there. I'll explain the steps I did to crash the client:

- Create a random 1x1x1 LT block with different tiles (I used Oak wood and dirt here)
- Create a fixed structure out of it using the recipe
- Place 2-3 of the structures in a row
- Place 1 vanilla block at the beginning and the end of the row (I used stone here)
- Configure the hammer to a grid size of 4 (for visibility)
- Cut a line from vanilla to vanilla block over all 5 (in my case) blocks
- Structures get removed (correct)
- Hit Ctrl+Z to get them back: Only one block shows up (not correct)
- Try to place anything in the gap (or invisible block space)
- Crash/Freeze happens

Latest [log](https://github.com/CreativeMD/LittleTiles/files/5859980/latest.log) is attached.

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thank you very much for your detailed description, made it very easy for me to reproduce this issue. Sorry that it took me so long to get here.

**Comment by knobsam** [comment]
No problems, RL has always priority. :+1: 

I just tested it, works like a charm. Thank you very much!
