### ISSUE TITLE
Bug with lighting on doors

### ISSUE THREAD

**Issue by djhatt0204** [CreativeMD/LittleTiles#582]
So I discovered while trying to make an elevator that doors have buggy lighting properties. The following screenshots show what is wrong. (Note: the lighting bug only occurs at night in game.)

Day:
![2021-01-21_12 41 59](https://user-images.githubusercontent.com/76971201/105389872-5dd86300-5be6-11eb-878d-3ab54b132e9d.png)
![2021-01-21_12 42 06](https://user-images.githubusercontent.com/76971201/105389933-78124100-5be6-11eb-83c7-4700c32a3911.png)

Night
![2021-01-21_12 46 22](https://user-images.githubusercontent.com/76971201/105390165-b9a2ec00-5be6-11eb-8b8f-458a63747a08.png)

![2021-01-21_12 42 49](https://user-images.githubusercontent.com/76971201/105389985-8b251100-5be6-11eb-8bf4-78951ebc4e3c.png)

**Comment by CreativeMD** [comment]
Sorry, but I don't think I can fix that. The lighting engine is not perfect :( maybe it's better in 1.16.
