### ISSUE TITLE
placement of cable in 32 skips placement

### ISSUE THREAD

**Issue by Doc-1** [CreativeMD/LittleTiles#583]
In grid 32 placing a 4-bit cable, it skips one spot when you go from one block to another. View the GIF below for a better explanation. 
[](url)
![placement jump](https://user-images.githubusercontent.com/45431412/105515481-bc631700-5ca2-11eb-81ba-20293df5f2ce.gif)

**Comment by CreativeMD** [comment]
Not a bug but a feature, you can just sneak to place it across multiple blocks.

**Comment by Doc-1** [comment]
Holding Shift doesn't work. Nor alt.

**Comment by Doc-1** [comment]
Never mind, For some reason, it is working after a restarting minecraft
