### ISSUE TITLE
Error when trying to place new Blank-o-matic in survival mode

### ISSUE THREAD

**Issue by tolerus** [CreativeMD/LittleTiles#584]
When trying to place the Blank-o-matic in survival mode the action fails with the prompt:

"You are not allowed to place something with Alpha below 255"

and the Blank-o-matic disappears from inventory. When quitting and rejoining the game the blank-o-matic shows up again in inventory.

`Mods installed:
Client attempting to join with 56 mods : quarkoddities@1,gardenstuff@1.12-2.1.1,dynamictreesbop@1.12.2-1.4.4,creativecoredummy@1.0.0,extrabitmanipulation@1.12.2-3.4.1,animania@2.0.0.23,locks@2.2.1,dynamictreesquark@1.12.2-1.0.6,jei@4.15.0.291,bibliocraft@2.4.5,craftstudioapi@1.0.0,mcp@9.42,ctm@MC1.12.2-1.0.2.31,chameleon@1.12-4.1.3,forgelin@1.8.2,xreliquary@1.12.2-1.3.4.786,stg@1.12.2-1.2.3,foamfixcore@7.7.4,joypadsplitscreenmod@1.12.0-0.22,carryon@1.12.1,mcmultipart@2.5.3,forge@14.23.5.2854,testdummy@1.12,storagedrawersextra@@VERSION@,worldgenerationprofiler@1.2.1.5,variedcommodities@1.12.2,minecraft@1.12.2,pecunia_mod@1.3,theoneprobe@1.4.28,biomesoplenty@7.0.1.2444,customstuff4@0.5.3,opticmanager@1.0,creativecore@1.10.0,littleopener@1.0.1,fairylights@2.1.10,astikorcarts@1.12.2-0.1.2.7,littletilescore@1.0.0,vanillafix@1.0.10-SNAPSHOT,quark@r1.6-179,autoreglib@1.3-32,storagedrawers@1.12-5.3.5,FML@8.0.99.99,dimdoors@3.0.9+287,customnpcs@1.12,edxmultipart@1.1.1,worldedit@6.1.10-SNAPSHOT,opframe@1.4.0,chisel@MC1.12.2-1.0.2.45,foamfix@0.10.5-1.12.2,forgeessentialsclient@12.3,impart@1.12.2,vtt@0.6.4,chiselsandbits@14.30,dynamictrees@1.12.2-0.9.21,playerrevive@1.0,littletiles@1.5.0`

**Comment by kirokadura** [comment]
The Blank o Matic contains tiles with alpha values lower than 255, which is causing this issue. We'll rework the model to not include anything that might be disable in the config. In the meantime, you can change the config to allow Alpha values.

**Comment by CreativeMD** [comment]
Fixed in the newest version.
