### ISSUE TITLE
Crashing.

### ISSUE THREAD

**Issue by whammmm** [CreativeMD/LittleTiles#586]
Minecraft won't even let me start up with this mod in the folder. Not sure what it is but if I could have some help that would be great.

Also the only other mod I have installed is Optifine.

**Comment by whammmm** [comment]
i have a crash report here:
[crash-2021-01-25_14.35.06-client.txt](https://github.com/CreativeMD/LittleTiles/files/5869247/crash-2021-01-25_14.35.06-client.txt)

**Comment by knobsam** [comment]
I think you forgot to install the mod "CreativeCore" as well. It is required.
At least I cannot find the mod in the mod list of your crash log.

-> https://www.curseforge.com/minecraft/mc-mods/creativecore/files


Best regards,

Samuel

**Comment by kirokadura** [comment]
Samuel is correct, you're either missing CreativeCore or are using an outdated version. I'll close the issue for now.
