### ISSUE TITLE
Display bug in the Little Blueprint window with the mod Just enough item.

### ISSUE THREAD

**Issue by HDL34** [CreativeMD/LittleTiles#588]
I found the origin of the bug I had each time (I couldn't see my construction in the window). This bug is related to "Just enougt items" mod. Here is a video showing my bug. 
https://user-images.githubusercontent.com/61374058/106109012-561a4080-6149-11eb-9f69-a295b96f3718.mp4

**Comment by CreativeMD** [comment]
Thanks for reporting this issue. It's fixed in the newest CreativeCore version!
