### ISSUE TITLE
[Suggestion] Create special method for manipulating microbits.

### ISSUE THREAD

**Issue by Dushess** [CreativeMD/LittleTiles#59]
I writing it, because mastering something detailed with LTtileentities is really hell. This mod have good future with planned functional and aestetic features, but absolute worse thing - in some cases operations here available only per bit. And new options like undo/redo not available for slightly outdated (but still in use) platforms like 1.10.2. In short, LT needs area-selection method for bits placing or deletion. For example - Chisels&Bits, it's more comfortable, but not so powerful.
Really, if i need to form a slot for something (in my example - space for screw) i need to remove bits from area one by one, because column/plane selection doesn't match here.

**Comment by CreativeMD** [comment]
1.5.0 will have all those things (already has some of them):
https://www.youtube.com/watch?v=Tjwa5Zd1zvY
https://www.youtube.com/watch?v=vJsCagmkstE

**Comment by Dushess** [comment]
Great!

**Comment by Dushess** [comment]
Oh yes, will ask also for resizing chiseled block during convert to LT-block, if grid isn't 16.

**Comment by CreativeMD** [comment]
I plan to rework the grid system, but not in the near future, sorry :(
