### ISSUE TITLE
gaps in my recipes

### ISSUE THREAD

**Issue by shadowlihtt** [CreativeMD/LittleTiles#596]
some of my finished recipes lose the blocks that make up the recipe when put into certain positions, this is my recipe, a floor tile
![Captura de pantalla (84)](https://user-images.githubusercontent.com/78767822/107295171-db043480-6a3c-11eb-9226-c7b89cb6673d.png)

![Captura de pantalla (85)](https://user-images.githubusercontent.com/78767822/107295174-db9ccb00-6a3c-11eb-82d4-e96acba3b7a7.png)
as you can see, in these blocks I can place them without any problem.
![Captura de pantalla (87)](https://user-images.githubusercontent.com/78767822/107295176-dc356180-6a3c-11eb-8eb2-28a4bff2881c.png)
I can even put it on the walls vertically. the problem comes in certain places (I don't know if it's specifically the little tiles blocks, it could be because I use the white blocks that come with the mod as a base, I don't know, although I remenber having experienced the same problem with normal blocks) the recipe has some gaps where the blocks should be, for exampke if i want to place it here
![Captura de pantalla (88)](https://user-images.githubusercontent.com/78767822/107295177-dc356180-6a3c-11eb-9940-de9c30a59c7b.png)
this is what happens...
![Captura de pantalla (89)](https://user-images.githubusercontent.com/78767822/107295179-dccdf800-6a3c-11eb-8afc-adc59613074c.png)
hole locations and patterns depend on how the recipe is rotated even if its placed in the same place
![Captura de pantalla (90)](https://user-images.githubusercontent.com/78767822/107295180-dccdf800-6a3c-11eb-83e3-741802c70f1a.png)
they usually also vary from the place where you place the recipe, although there are rare cases where the pattern is repeated in different blocks, as you can see the shape and place of the holes is the same in these three places.
![Captura de pantalla (91)](https://user-images.githubusercontent.com/78767822/107295181-dd668e80-6a3c-11eb-9661-ff28212f23f7.png)
but normally the patterns are not repeated, it also happens on some walls, the recipe also has gaps, but I don't have a screenshot of that, if it turns out to be necessary I will get it.
![Captura de pantalla (92)](https://user-images.githubusercontent.com/78767822/107295182-dd668e80-6a3c-11eb-81c3-d0c58e764808.png)
I apologise if there are grammatical mistakes, English is not my native language.

**Comment by CreativeMD** [comment]
Can you export it, so I can test it myself?

**Comment by shadowlihtt** [comment]
Do you mean tbe recipe?

**Comment by CreativeMD** [comment]
Yes

**Comment by shadowlihtt** [comment]
here you go 
[floor tile.txt](https://github.com/CreativeMD/LittleTiles/files/5954448/floor.tile.txt)

**Comment by CreativeMD** [comment]
It works absolutely fine for me. Are you using the newest version of LittleTiles? It feels like yours is outdated. Will close the issue for now. If this is still an issue in the newest version let me know.

**Comment by CreativeMD** [comment]
Never mind sorry ... wasn't doing it properly.

**Comment by CreativeMD** [comment]
Now it's fixed ... just download the newest version of CreativeCore.

**Comment by shadowlihtt** [comment]
now it crashes every time i place a recipe

**Comment by shadowlihtt** [comment]
Forget about it

**Comment by CreativeMD** [comment]
Forgot to update creativecore?
