### ISSUE TITLE
Help my game keeps crashing

### ISSUE THREAD

**Issue by NabiPlayZ** [CreativeMD/LittleTiles#597]
Hello i need help, when i start my game i crash instantly i dont know why but here is was i did so far.

i downloaded forge 1.12.2 and put creative core and little tiles {yes and latest versions} then i started my game and then came crash reports it said remove texture packs {i did} redownload java {did it} and then i started again and crashed here is the dev log

~ SNIP ~

And i am useing tlauncher but it worked on other mods so i dont know why not this one Thanks.

**Comment by CreativeMD** [comment]
Could you rather send me the crash-report? There was no real error in the log you send me.

**Comment by NabiPlayZ** [comment]
Nvm i found the crash report from yesterday but it had nothing in it

[crash-2021-02-10_21.17.22-server.txt](https://github.com/CreativeMD/LittleTiles/files/5964630/crash-2021-02-10_21.17.22-server.txt)

**Comment by NabiPlayZ** [comment]
> Could you rather send me the crash-report? There was no real error in the log you send me.

I dont know were to find the one today ,I already checked the one yesterday there was nothing in it

**Comment by CreativeMD** [comment]
This is also a crash report of the server that doesn't make sense either. Does the game still crash?

**Comment by NabiPlayZ** [comment]
> This is also a crash report of the server that doesn't make sense either. Does the game still crash?

yea still crashes

**Comment by CreativeMD** [comment]
Then there has to be a crash-report. Maybe you are not looking in the right folder.

**Comment by NabiPlayZ** [comment]
> Then there has to be a crash-report. Maybe you are not looking in the right folder.

maybe, im looking in User/Appdata/roaming/.minecraft/crash-reports

**Comment by CreativeMD** [comment]
If you are using the minecraft launcher then yes, but if you are using a different launcher then probably no.

**Comment by NabiPlayZ** [comment]
> If you are using the minecraft launcher then yes, but if you are using a different launcher then probably no.

i crashed with other mods and there crash reports are in the folder so i dont know why little tiles isnt in there

**Comment by CreativeMD** [comment]
Maybe it's not caused by LittleTiles? Can't you just send me the most recent crash-report?

**Comment by NabiPlayZ** [comment]
alright here it is 
[crash-2021-01-24_15.38.52-client.txt](https://github.com/CreativeMD/LittleTiles/files/5971925/crash-2021-01-24_15.38.52-client.txt)

**Comment by CreativeMD** [comment]
That crash-report is from 24th January ... and LT is not installed. Maybe your crash-reports are not sorted in the right way?

**Comment by NabiPlayZ** [comment]
i dont know were to find the latest ones but ill keep looking

**Comment by NabiPlayZ** [comment]
[debug-5.log](https://github.com/CreativeMD/LittleTiles/files/5971996/debug-5.log)

so i looked in this file and found this text and found creative core and little tiles in it

**Comment by CreativeMD** [comment]
Again there is no crash in there ... maybe the jvm crashes? Look for a file in the .minecraft folder called like hs_err_pid*number*.log.

**Comment by NabiPlayZ** [comment]
I found 6 do you want me to send them to you?

**Comment by CreativeMD** [comment]
the newest

**Comment by NabiPlayZ** [comment]
[hs_err_pid8944.log](https://github.com/CreativeMD/LittleTiles/files/5972058/hs_err_pid8944.log)
 this is the latest one i could find

**Comment by CreativeMD** [comment]
Weird, no idea what is going wrong there, but I kind of doubt it's related to any of my mods. The only possibility I can think of is your graphic card not being able to handle stencil. You can set useStencil in creativecore-client.json to false and see if it works, otherwise I can't really help you there. Maybe update graphic card driver ...

**Comment by NabiPlayZ** [comment]
Were do i find the creativecore-client.json file

**Comment by CreativeMD** [comment]
In the config folder.

**Comment by NabiPlayZ** [comment]
> In the config folder.

oh thats weird......... i dont see it in the folder

**Comment by CreativeMD** [comment]
Because the game never really starts for you. Again it's not related to my mods.

**Comment by NabiPlayZ** [comment]
do you have the json file if yes cant you just copy the folder and send it to me?

**Comment by CreativeMD** [comment]
That won't change anything. Your game crashes even before that.
