### ISSUE TITLE
weird colors

### ISSUE THREAD

**Issue by elachon** [CreativeMD/LittleTiles#598]
every little tile renders in weird colors, even the workbench
version 1.5.0-pre199_73_mc1.12.2

![image](https://user-images.githubusercontent.com/78901256/107615153-e6a45680-6c08-11eb-838e-663863d10f89.png)
left - little tiles  right - chisels and bits
same block on both

**Comment by kirokadura** [comment]
That's a very old version, try updating it along with CreativeCore.

**Comment by elachon** [comment]
![image](https://user-images.githubusercontent.com/78901256/107659055-fdb46a00-6c43-11eb-931f-fcf48198767a.png)


now it's not rendering and is making a little window where i can see the moon

updated to littletiles_v1.5.0-pre324_mc1.12.2 creativecore_v1.10.45_mc1.12.2

**Comment by elachon** [comment]
o i think it was optifine antialiasing...which is also something i really want @.@

**Comment by CreativeMD** [comment]
Sorry, but there is nothing I can do about it. Let's hope it will work in 1.16.
