### ISSUE TITLE
Corrupted doors on survival mode in Single Player mode

### ISSUE THREAD

**Issue by em411** [CreativeMD/LittleTiles#599]
I've found an issue with a Little Tile Doors made with transparent blocks. 

It's not working only on survival or adventure mode, everything is fine on creative.

https://youtu.be/XCbSZsy-AVk

CreativeCore_v1.10.45_mc1.12.2
LittleTiles_v1.5.0-pre324_mc1.12.2

**Corrupted doors export:**
`{tiles:[{boxes:[[I;0,0,1,8,8,3],[I;0,8,1,8,16,3],[I;0,16,1,8,24,3],[I;0,24,1,8,32,3],[I;8,0,1,16,8,3],[I;8,8,1,16,16,3],[I;8,16,1,16,24,3],[I;8,24,1,16,32,3],[I;16,0,1,24,8,3],[I;16,8,1,24,16,3],[I;16,16,1,24,24,3],[I;16,24,1,24,32,3]],tile:{color:1375017940,block:"littletiles:ltcoloredblock:10"}}],min:[I;0,0,1],size:[I;24,32,2],grid:8,count:12,structure:{duration:10,axisCenter:[I;0,0,0,1,1,1,8],interpolation:0,sounds:1b,blocks:[I;],activateParent:0b,opened:0b,id:"advancedDoor",state:{mode:"TOGGLE",state:0},events:[],disableRightClick:0b,animation:{rotX:[I;0,1,0,0,0],offGrid:16,rotZ:[I;0,1,0,0,0],rotY:[I;0,1,0,0,0],offX:[I;0,1,0,0,0],offY:[I;0,2,0,0,0,10,1078984704,0],offZ:[I;0,1,0,0,0]}}}`

**Comment by CreativeMD** [comment]
Can you try this out with the newest version of CreativeCore and LittleTiles to see if it still broken?

**Comment by em411** [comment]
Tested on:
Little Tiles: *.pre327
CreativeCore_v1.10.47_mc1.12.2

Issue still exists without any changes

**Comment by CreativeMD** [comment]
Corrupted doors won't fix themselves after updating, but if you place the same structure again does it will corrupt?

**Comment by em411** [comment]
I made a new world, imported structure mentioned above and yes, it's still corrupted

**Comment by CreativeMD** [comment]
That is very weird, it works absolutely fine for me.

**Comment by CreativeMD** [comment]
Pretty sure this is fixed in the newest version of LittleTiles, if not please respond here again including your world save.
