### ISSUE TITLE
Forsed convert chiseled block to LT-block results texturing fail.

### ISSUE THREAD

**Issue by Dushess** [CreativeMD/LittleTiles#60]
As sayed in title, when you trying to remove a part from chiseled block with utility knife, it successfully converts it to group of little tiles, without rescaling. But, then every tile is transparent, but is present and fully operational. Even game restart doesn't work (Seems to be not common render error, when fully chunk reloading helps fix this).
Yes, there's a way to safe converting, but "keep scale" option isn't implemented yet.

Some screens of that:
[https://imgur.com/a/EpARJ](https://imgur.com/a/EpARJ)

MC v1.11.2
Forge v13.20.1.2425
LT v1.5.0 pre26
CreativeCore v1.8.10
OptiFine v1.11.2 HD-U-C3

Used scale grid - 32

**Comment by CreativeMD** [comment]
chiseled block?

Changing the gridsize will result in weird issues. Currently it's not available to load worlds with a different gridsize (will result in scaling issues), but it's already on my todo list.

**Comment by Dushess** [comment]
I mean other, converting is successful, with no resizing, problem with textures, that won't load. (Also i seen what happens with grid value mismatch, i wrote about other kind of problem)

**Comment by CreativeMD** [comment]
Could you try to explain it again?

**Comment by Dushess** [comment]
Ye, i doing this: exist a chiseled block, i removing one bit from it with knife, block converts to LT-block, his size does not change, even with scale mismatch (C&B=16, LT=32), it just becomes LT-block (correct structure, if i remove one of 32768 microbits, but from source-block, having 4096, so scaling is ok), the problem is missing textures after this convert. It also moves on new LT-block, when i extend first one with saw.

**Comment by CreativeMD** [comment]
The utility knife cannot convert a c&b block into littletiles block

**Comment by Dushess** [comment]
But it does that, i will make video...
https://youtu.be/xIdTQiNnbic
Bandicam watermark is messed up, waila shows that tiles in the end really have 32 bits width.
Probably LT can't handle chiseled rock or something as block material, and it directly moves into LT-block. I mean result tiles made from chiseled rock instead of granite (for example, waila shown that, but watermark blocks the view)
Yes, problem confirmed.
[https://i.imgur.com/DFsvJGv.png](https://i.imgur.com/DFsvJGv.png)

**Comment by CreativeMD** [comment]
As i said already. The problem is not the gridsize. You should be able to convert those c&b blocks using a recipe. However the utility knife is not able to convert a c&b block. Actually it should just cancel it, but for some kind of reason it still tries to do something (which obviously cannot work). I will put this feature on my todo list, but i'm afraid for now you have to convert these blocks using the recipe.

**Comment by Dushess** [comment]
ok, if it's not excessive, i see that knife successfully converts it, but make straight transfer chiseled block's material into LT-block. Seems to be, of course LT-block doesn't support this material, it uses vanilla textures **directly** from those blocks and only they can be rendered right. anyway thanks for attention.
