### ISSUE TITLE
Need help setting stencil to false

### ISSUE THREAD

**Issue by NabiPlayZ** [CreativeMD/LittleTiles#600]
i need to get a file called creativecore-client.json but my game keeps crashing and it only works when i play the game with the mods but i have a idea, i just need someone to send me the file and then i can set it to false

Help please

**Comment by CreativeMD** [comment]
Again that is not the issue. Maybe try to reinstall Forge again watch a proper tutorial about it. Update your graphic card driver, make sure the game runs fine without my mods installed and then install CreativeCore and LittleTiles (newest versions).
