### ISSUE TITLE
Problem with opening

### ISSUE THREAD

**Issue by Mark23456666** [CreativeMD/LittleTiles#603]
When I downloaded the mod, it was fine and dandy, then I put it in to my mods folder and started my launcher. And it f-ing crashed. I downloaded a different version, and it didnt help. If you can help me, that would be awesome! and make a new version to fix that error.

**Comment by CreativeMD** [comment]
Make sure to get the newest version from CreativeCore and LittleTiles from curseforge, that will work.

**Comment by Mark23456666** [comment]
I tried that, but it dosent work too. Man, you need to update the beta build to a relase build.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by CreativeMD** [comment]
The newest version cannot be downloaded using the download button ... you always need to take care of the game version. The sidebar is a lot more useful. Unfortunately I can't remove the stupid download button.

**Comment by Mark23456666** [comment]
But it sAYS that its for f-ing 1.7.10 instead of like what 1.12.2. And I tried the relases, it worked, so bud relase the newsest beta to a relase already!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Mark23456666** [comment]
Nvm it now works!
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
