### ISSUE TITLE
Non-rendered Particle Emitter Spamming Error

### ISSUE THREAD

**Issue by Doc-1** [CreativeMD/LittleTiles#604]
When moving away from a particle tile to the point, it is no longer rendered. It produces a stream of the same error. 

`[07:35:48] [Thread-13/INFO] [STDERR]: [com.creativemd.littletiles.client.render.cache.RenderingThread:run:338]: com.creativemd.littletiles.client.render.cache.RenderingThread$RenderingException: Tileentity is not loaded yet

[07:35:48] [Thread-13/INFO] [STDERR]: [com.creativemd.littletiles.client.render.cache.RenderingThread:run:338]: 	at com.creativemd.littletiles.client.render.cache.RenderingThread.run(RenderingThread.java:178)
`

**Comment by CreativeMD** [comment]
Will be fixed in the official release which is scheduled for next week.

**Comment by CreativeMD** [comment]
New version is out!
