### ISSUE TITLE
Advanced Door Grid size does not save

### ISSUE THREAD

**Issue by Doc-1** [CreativeMD/LittleTiles#607]
When I pan through the options and hit the last grid size available I can no longer change it.
![doesn't save](https://user-images.githubusercontent.com/45431412/111230043-55385380-85bd-11eb-924d-31e50bb0c497.gif)

**Comment by Doc-1** [comment]
Looks like in LittleAdvancedDoor on line 432, moving "context = newContext;" bellow one bracket fixed it.

**Comment by CreativeMD** [comment]
Will be fixed in the release.

**Comment by CreativeMD** [comment]
New version is out!
