### ISSUE TITLE
BreakEvent called after replacement

### ISSUE THREAD

**Issue by LemADEC** [CreativeMD/LittleTiles#608]
As of CreativeCore_v1.10.45_mc1.12.2 + LittleTiles_v1.5.0-pre324_mc1.12.2, when using the Littlehammer to carve into a block, the BreakEvent is called after replacing the block with a `littletiles:blocklittletiles`, while forge will call this event before doing so.

This prevents to filter properly the cancel decision.

**Comment by CreativeMD** [comment]
In theory the event is fired before anything is edited. But the client performs the action anyway. Only the block is being converted before the event, not sure if that made a difference. Changed it now. Also the server should send a reset packet for the player.

**Comment by CreativeMD** [comment]
New version is out, can you test if anything has changed?

**Comment by LemADEC** [comment]
Issue is no longer reproduced with CreativeCore_v1.10.58_mc1.12.2 + LittleTiles_v1.5.8_mc1.12.2, so I guess that did the trick.

**Comment by CreativeMD** [comment]
Very good to hear! Thanks for testing and reporting this issue!
