### ISSUE TITLE
LittleTiles v1.5.0-pre29 [1.11.2] - bugged WAILA interaction.

### ISSUE THREAD

**Issue by Dushess** [CreativeMD/LittleTiles#61]
Testing this version now, and found one little issue: waila doesn't recieving tile sizes.
Yes, i read the changelog, but think something goes not as planned here.
[https://imgur.com/a/sblC2](https://imgur.com/a/sblC2)

**Comment by CreativeMD** [comment]
Both of your issues will be fixed in pre31 which should be approved in a few minutes.
