### ISSUE TITLE
Little Blueprint having the same recipe as buildcraft's Blueprint

### ISSUE THREAD

**Issue by velocityraptor-real** [CreativeMD/LittleTiles#610]
The Little Blueprint from LittleTiles has the same recipe as the Blueprint from buildcraft, resulting in players only being able to craft one of those 2 items.
Littletiles version: LittleTiles_v1.5.0-pre327_mc1.12.2
Buildcraft version: buildcraft-all-7.99.24.8

solution: just come up with another recipe. maybe keep the ingredients and just make it shapeless, or rearrange the items

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming release.

**Comment by CreativeMD** [comment]
New version is out!
