### ISSUE TITLE
Can't set slice and Can't choose Pyramid

### ISSUE THREAD

**Issue by oraant** [CreativeMD/LittleTiles#611]
Using the lastest version:
CreativeCore_v1.10.47_mc1.12.2
LittleTiles_v1.5.0-pre327_mc1.12.2

## Can't set slice:

![Base Profile Screenshot 2021 03 18 - 10 31 37 26](https://user-images.githubusercontent.com/12079340/111565124-ce11f800-87d5-11eb-8595-3e312f1aeacf.png)

![Base Profile Screenshot 2021 03 18 - 10 31 46 31](https://user-images.githubusercontent.com/12079340/111565130-d1a57f00-87d5-11eb-9411-faa6d42392a8.png)

I can't get the perfect slice, but got a long stright line.

## Can't choose Pyramid

![Base Profile Screenshot 2021 03 18 - 10 31 57 79](https://user-images.githubusercontent.com/12079340/111565135-d4a06f80-87d5-11eb-81d8-a7abced9adf1.png)

u can click it, but nothing happens.

**Comment by CreativeMD** [comment]
The slice issue is fixed in the pre328.
