### ISSUE TITLE
Little saw crash on slice block

### ISSUE THREAD

**Issue by Stellulare** [CreativeMD/LittleTiles#612]
Using the lastest version:
Forge v14.23.5.2855
LittleTiles_v1.5.0-pre327_mc1.12.2
CreativeCore_v1.10.47_mc1.12.2

When you make a slice and use the little saw's shift+rightclick until the slice has one layer the next shift+rightclick will crash the game. This is with only LittleTiles and CreativeCore installed. I can reproduce this crash every time.

[crash-2021-03-18_03.24.27-client.txt](https://github.com/CreativeMD/LittleTiles/files/6163290/crash-2021-03-18_03.24.27-client.txt)
[latest.log](https://github.com/CreativeMD/LittleTiles/files/6163292/latest.log)
![2021-03-18_03 33 52](https://user-images.githubusercontent.com/80755640/111612954-3db6c180-879b-11eb-97cd-44421b79c563.png)

**Comment by oraant** [comment]
Yeah, been there.

**Comment by CreativeMD** [comment]
This crash will hopefully be fixed in the big release.

**Comment by CreativeMD** [comment]
New version is out!

**Comment by oraant** [comment]
> New version is out!

Coooooooooooooooooool!!!
