### ISSUE TITLE
Little hammer allows players to bypass chunk claims made by the Grief defender plugin.

### ISSUE THREAD

**Issue by Warhand** [CreativeMD/LittleTiles#613]
I was talking to a friend of mine and they mentioned that while playing on a server, they found that the little tiles hammer allowed players to bypass chunk claims, and destroy blocks in other players areas.

The chunk claims in question were made by the Grief defender spigot plugin.

Sorry I don't have much more information, I just figured this would be good to mention in case y'all weren't already aware.

**Comment by CreativeMD** [comment]
Some plugins work some don't. This topic is very annoying. I fire events as forge does, so I don't think there is much more I can do about it.
