### ISSUE TITLE
Compatibility issue with Real Train Mod

### ISSUE THREAD

**Issue by viciscat** [CreativeMD/LittleTiles#617]
Incompatibility issue with the Real Train Mod.
Trying to build a slice result in a crash.
Here's the crash report:
[crash-2021-02-17_12.13.17-client.txt](https://github.com/CreativeMD/LittleTiles/files/6191004/crash-2021-02-17_12.13.17-client.txt)

**Comment by CreativeMD** [comment]
Sorry but I can't change anything about that. RTM does some weird stuff.
