### ISSUE TITLE
2 Problem with Item Holder

### ISSUE THREAD

**Issue by olegikoligik** [CreativeMD/LittleTiles#618]
Version:
LT pre 327
Core 1.10.47

Issues 1:
If optifine installed (G5 version) and Mipmap setting set more then 0 item placed in Item holder is invisible. If it 0 i have warning from mod "Optifine detected - Enable mipmap levels".

Issues 2:
Putted LT structure (or multi-tile structure) in item holder lost all colors painted by "Little Paint Brush".
https://i.imgur.com/aD498k3.png

**Comment by CreativeMD** [comment]
For me the item does not work entirely if Optifine is installed. I'm sorry but this won't be fixed in 1.12. I really hope things work out better in 1.16. Will close this issue for now anyway.
