### ISSUE TITLE
Crash with No Tree Punching mod

### ISSUE THREAD

**Issue by timothygremlin** [CreativeMD/LittleTiles#619]
Hi! I encountered a problem when right clicking tiles with an axe while having NTP installed. Normally with NTP you can right click wood with an axe to make planks. When I do that for the tiles (interestingly, any tiles - not just wood-based) the game crashes. I attached a crash-log. I suppose the solution is for now not to right click the tiles with an axe while having NTP on. Thanks for your work!

MC 1.12.2
LT 1.5.0-pre199_44
NTP 2.0.21
[crash-2021-03-30_02.07.36-client.txt](https://github.com/CreativeMD/LittleTiles/files/6225582/crash-2021-03-30_02.07.36-client.txt)

**Comment by CreativeMD** [comment]
Will be fixed in the big release.

**Comment by CreativeMD** [comment]
New version is out!
