### ISSUE TITLE
Looping door cloning itself every tick

### ISSUE THREAD

**Issue by Doc-1** [CreativeMD/LittleTiles#621]
I created a looping door using b0: !(b0) equal. And for some reason on this one tile door that I was having it look like it was floating up and down in the air. It places a copy of itself seemingly every tick. I use that signal logic for other moving platforms and they have never duplicated.
Export:
[dubbing door.txt](https://github.com/CreativeMD/LittleTiles/files/6238040/dubbing.door.txt)

**Comment by CreativeMD** [comment]
Will be fixed in the big release. Thank you very much for reporting it! Was actually a quite serious issue.

**Comment by CreativeMD** [comment]
New version is out!
