### ISSUE TITLE
Little Tiles items (Little Chisel and Little Blueprint) will not open the UI.

### ISSUE THREAD

**Issue by wasdsaq** [CreativeMD/LittleTiles#624]
Little Tiles items like the little chisel and little blueprint aren't usable. No amount of left-clicking, right-clicking or shift-clicking   will open the UI.
This means that the chisel will only work with stone and the blueprint is unusable.
Using Little Tiles 1.5.0-pre327
and CreativeCore 1.10.47.
Edit: The issue still happens in 1.5.0-pre328.

**Comment by kirokadura** [comment]
Set the keybind "Configure Tool" in your keybind settings. It should be defaulted to "C", but you'll have to make sure no other mod is using that key.

**Comment by wasdsaq** [comment]
Thanks!
