### ISSUE TITLE
Crash on startup error code 0

### ISSUE THREAD

**Issue by SteveHasAnIssue** [CreativeMD/LittleTiles#626]
Soon as I install any version of this mod to my currently modded game I crash before getting to the loading screen.
I'm running 
aether
aquaculture
bibliocraft
biomesoplenty
birdsnests
bookworm
chiselandbits
clumps
custommobspawner
decocraft
mocreatures
exotic birds
living enchantment
millenaire
optifine
twilight forests
and chisel and bits (but I thought this mod works with that?)

**Comment by CreativeMD** [comment]
You are most likely missing creativecore.
