### ISSUE TITLE
Crash when enter the world

### ISSUE THREAD

**Issue by MarcCrams** [CreativeMD/LittleTiles#627]
Hello, everytime I try to enter in my world my game crashes. I've tried all solutions I know but nothing works.

Here is the crash report:
[crash-2021-04-12_21.11.55-client.txt](https://github.com/CreativeMD/LittleTiles/files/6303687/crash-2021-04-12_21.11.55-client.txt)
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.7.0-232-universal.jar)
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre328_mc1.12.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
  CreativePatchingLoader (CreativeCore_v1.10.47_mc1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 4/12/21 9:52 PM
Description: Rendering item

java.lang.ArrayIndexOutOfBoundsException: 1
	at com.creativemd.littletiles.common.tile.preview.LittlePreview.getBlockName(LittlePreview.java:111)
	at com.creativemd.littletiles.common.tile.preview.LittlePreview.getBlock(LittlePreview.java:115)
	at com.creativemd.littletiles.common.tile.preview.LittlePreview.getCubeBlock(LittlePreview.java:150)
	at com.creativemd.littletiles.common.item.ItemBlockTiles.getItemRenderingCubes(ItemBlockTiles.java:127)
	at com.creativemd.littletiles.common.block.BlockTile.getRenderingCubes(BlockTile.java:966)
	at com.creativemd.littletiles.common.block.BlockTile.getRenderingCubes(BlockTile.java:876)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:155)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.func_188616_a(CreativeBakedModel.java:75)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:168)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:136)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:216)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:517)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:559)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:356)
	at net.minecraft.client.gui.GuiIngame.func_184044_a(GuiIngame.java:1248)
	at net.minecraft.client.gui.GuiIngame.func_180479_a(GuiIngame.java:611)
	at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:346)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:142)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1426)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.common.tile.preview.LittlePreview.getBlockName(LittlePreview.java:111)
	at com.creativemd.littletiles.common.tile.preview.LittlePreview.getBlock(LittlePreview.java:115)
	at com.creativemd.littletiles.common.tile.preview.LittlePreview.getCubeBlock(LittlePreview.java:150)
	at com.creativemd.littletiles.common.item.ItemBlockTiles.getItemRenderingCubes(ItemBlockTiles.java:127)
	at com.creativemd.littletiles.common.block.BlockTile.getRenderingCubes(BlockTile.java:966)
	at com.creativemd.littletiles.common.block.BlockTile.getRenderingCubes(BlockTile.java:876)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:155)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.func_188616_a(CreativeBakedModel.java:75)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:168)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:136)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:216)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:517)

-- Item being rendered --
Details:
	Item Type: com.creativemd.littletiles.common.item.ItemBlockTiles@5ba69733
	Registry Name: littletiles:blocklittletiles
	Item Aux: 0
	Item NBT: {}
	Item Foil: false

-- Item being rendered --
Details:
	Item Type: com.creativemd.littletiles.common.item.ItemBlockTiles@5ba69733
	Item Aux: 0
	Item NBT: {}
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.handleCaughtException(CCRenderItem.java:188)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:359)
	at net.minecraft.client.gui.GuiIngame.func_184044_a(GuiIngame.java:1248)
	at net.minecraft.client.gui.GuiIngame.func_180479_a(GuiIngame.java:611)
	at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:346)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:142)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1426)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['MarcCrams'/5712, l='MpServer', x=754.35, y=53.06, z=-719.76]]
	Chunk stats: MultiplayerChunkCache: 297, 297
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (721,64,-667), Chunk: (at 1,4,5 in 45,-42; contains blocks 720,0,-672 to 735,255,-657), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Level time: 6287097 game time, 18000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 44 total; [EntityAnimation['entity.animation.name'/5568, l='MpServer', x=738.00, y=50.00, z=-723.00], EntityPig['Cochon'/5632, l='MpServer', x=802.30, y=73.00, z=-752.62], EntityBat['Chauve-souris'/5569, l='MpServer', x=750.30, y=20.10, z=-705.53], EntityPig['Cochon'/5633, l='MpServer', x=813.56, y=71.00, z=-765.22], EntityBat['Chauve-souris'/5570, l='MpServer', x=748.97, y=49.10, z=-707.43], EntityPig['Cochon'/5634, l='MpServer', x=810.61, y=72.00, z=-739.71], EntityBat['Chauve-souris'/5571, l='MpServer', x=743.70, y=47.10, z=-700.58], EntityBat['Chauve-souris'/5572, l='MpServer', x=747.25, y=53.10, z=-703.45], EntityPig['Cochon'/5641, l='MpServer', x=820.51, y=70.00, z=-757.72], NPCTurret['Turret'/5583, l='MpServer', x=758.50, y=59.10, z=-723.50], EntityBat['Chauve-souris'/5584, l='MpServer', x=765.83, y=27.10, z=-713.13], NPCTurret['Turret'/5585, l='MpServer', x=758.50, y=59.10, z=-713.50], EntityAnimation['entity.animation.name'/5586, l='MpServer', x=765.13, y=50.00, z=-713.00], EntityAnimation['entity.animation.name'/5587, l='MpServer', x=756.00, y=53.00, z=-716.00], EntityBat['Chauve-souris'/5588, l='MpServer', x=767.46, y=27.10, z=-697.68], EntityBat['Chauve-souris'/5589, l='MpServer', x=753.75, y=54.10, z=-698.10], EntityPlayerSP['MarcCrams'/5712, l='MpServer', x=754.35, y=53.06, z=-719.76], EntityPig['Cochon'/5600, l='MpServer', x=771.55, y=71.00, z=-738.72], EntityMinecartChest['Wagonnet de stockage'/5537, l='MpServer', x=694.50, y=15.06, z=-756.50], EntityBat['Chauve-souris'/5601, l='MpServer', x=771.43, y=24.10, z=-720.98], EntityBat['Chauve-souris'/5538, l='MpServer', x=694.17, y=72.88, z=-687.25], EntityBat['Chauve-souris'/5602, l='MpServer', x=768.25, y=51.10, z=-726.25], EntityAnimation['entity.animation.name'/5539, l='MpServer', x=699.00, y=70.00, z=-586.00], EntityBat['Chauve-souris'/5603, l='MpServer', x=769.02, y=27.10, z=-707.31], EntityAnimation['entity.animation.name'/5540, l='MpServer', x=701.00, y=70.00, z=-586.00], EntityPig['Cochon'/5604, l='MpServer', x=782.55, y=80.50, z=-704.50], EntityBat['Chauve-souris'/5605, l='MpServer', x=768.75, y=27.10, z=-693.73], EntityBat['Chauve-souris'/5606, l='MpServer', x=769.68, y=27.10, z=-697.24], EntityBat['Chauve-souris'/5607, l='MpServer', x=770.75, y=49.10, z=-698.25], EntityBat['Chauve-souris'/5608, l='MpServer', x=769.25, y=49.10, z=-696.75], EntityPig['Cochon'/5609, l='MpServer', x=779.43, y=71.00, z=-679.28], EntityPig['Cochon'/5610, l='MpServer', x=775.78, y=79.75, z=-654.45], EntityRocket['Fusée'/5548, l='MpServer', x=704.50, y=67.00, z=-664.50], EntityAnimation['entity.animation.name'/5549, l='MpServer', x=707.00, y=67.00, z=-595.00], EntityPig['Cochon'/5616, l='MpServer', x=789.72, y=70.00, z=-784.50], EntityPig['Cochon'/5617, l='MpServer', x=793.80, y=84.00, z=-709.26], EntityPig['Cochon'/5618, l='MpServer', x=790.75, y=84.00, z=-712.59], EntityPig['Cochon'/5619, l='MpServer', x=795.21, y=84.00, z=-700.37], EntitySquid['Poulpe'/5559, l='MpServer', x=726.63, y=61.77, z=-747.52], EntitySquid['Poulpe'/5560, l='MpServer', x=728.60, y=60.84, z=-744.14], EntitySquid['Poulpe'/5561, l='MpServer', x=730.11, y=62.19, z=-743.25], EntityPig['Cochon'/5630, l='MpServer', x=803.83, y=75.00, z=-798.70], EntityAnimation['entity.animation.name'/5567, l='MpServer', x=738.00, y=50.00, z=-725.00], EntityPig['Cochon'/5631, l='MpServer', x=806.26, y=72.00, z=-756.51]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 9379040296 bytes (8944 MB) / 11307843584 bytes (10784 MB) up to 13757317120 bytes (13120 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx13092M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 56 mods loaded, 56 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                             | Version                 | Source                                             | Signature                                |
	|:------ |:------------------------------ |:----------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                      | 1.12.2                  | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                            | 9.42                    | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                            | 8.0.99.99               | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                          | 14.23.5.2854            | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | advancedrocketrycore           | 1                       | minecraft.jar                                      | None                                     |
	| LCHIJA | creativecoredummy              | 1.0.0                   | minecraft.jar                                      | None                                     |
	| LCHIJA | littletilescore                | 1.0.0                   | minecraft.jar                                      | None                                     |
	| LCHIJA | opencomputers|core             | 1.7.5.192               | minecraft.jar                                      | None                                     |
	| LCHIJA | techguns_core                  | 1.12.2-1.0              | minecraft.jar                                      | None                                     |
	| LCHIJA | securitycraft                  | v1.8.20.1               | [1.12.2]+SecurityCraft+v1.8.20.1.jar               | None                                     |
	| LCHIJA | redstoneflux                   | 2.1.1                   | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCHIJA | cofhcore                       | 4.6.6                   | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| LCHIJA | libvulpes                      | 0.4.2.-75               | LibVulpes-1.12.2-0.4.2-75-universal.jar            | None                                     |
	| LCHIJA | advancedrocketry               | 1.7.0.-232              | AdvancedRocketry-1.12.2-1.7.0-232-universal.jar    | None                                     |
	| LCHIJA | ctm                            | MC1.12.2-0.3.3.22       | CTM-MC1.12.2-0.3.3.22.jar                          | None                                     |
	| LCHIJA | appliedenergistics2            | rv6-stable-7            | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | architecturecraft              | @VERSION@               | architecturecraft-1.12-3.98.jar                    | None                                     |
	| LCHIJA | opencomputers                  | 1.7.5.192               | OpenComputers-MC1.12.2-1.7.5.192.jar               | None                                     |
	| LCHIJA | aunis                          | 1.9.12-alpha-2021-02-12 | aunis-1.12.2-1.9.12-alpha-2021-02-12.jar           | None                                     |
	| LCHIJA | biomesoplenty                  | 7.0.1.2444              | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar      | None                                     |
	| LCHIJA | codechickenlib                 | 3.2.3.358               | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | brandonscore                   | 2.4.19                  | BrandonsCore-1.12.2-2.4.19.214-universal.jar       | None                                     |
	| LCHIJA | chickenchunks                  | 2.4.2.74                | ChickenChunks-1.12.2-2.4.2.74-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chisel                         | MC1.12.2-0.2.1.35       | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
	| LCHIJA | cyclopscore                    | 1.6.6                   | CyclopsCore-1.12.2-1.6.6.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | commoncapabilities             | 2.4.8                   | CommonCapabilities-1.12.2-2.4.8.jar                | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | creativecore                   | 1.10.0                  | CreativeCore_v1.10.47_mc1.12.2.jar                 | None                                     |
	| LCHIJA | draconicevolution              | 2.3.27                  | Draconic-Evolution-1.12.2-2.3.27.353-universal.jar | None                                     |
	| LCHIJA | dynamictrees                   | 1.12.2-0.9.19           | DynamicTrees-1.12.2-0.9.19.jar                     | None                                     |
	| LCHIJA | jei                            | 4.16.1.301              | jei_1.12.2-4.16.1.301.jar                          | None                                     |
	| LCHIJA | forestry                       | 5.8.2.387               | forestry_1.12.2-5.8.2.387.jar                      | None                                     |
	| LCHIJA | dynamictreesforestry           | 1.12.2-1.0.6            | dynamictreesForestry-1.12.2-1.0.6.jar              | None                                     |
	| LCHIJA | integrateddynamics             | 1.1.10                  | IntegratedDynamics-1.12.2-1.1.10.jar               | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | dynamictreesintegrateddynamics | 1.12.2-1.0.3            | dynamictreesIntegratedDynamics-1.12.2-1.0.3.jar    | None                                     |
	| LCHIJA | fluxnetworks                   | 4.0.14                  | fluxnetworks-1.12.2-4.0.15-32.jar                  | None                                     |
	| LCHIJA | forgelin                       | 1.8.4                   | Forgelin-1.8.4.jar                                 | None                                     |
	| LCHIJA | integrateddynamicscompat       | 1.0.0                   | IntegratedDynamics-1.12.2-1.1.10.jar               | None                                     |
	| LCHIJA | littleopener                   | 1.0.1                   | littleopener-1.0.1.jar                             | None                                     |
	| LCHIJA | littletiles                    | 1.5.0                   | LittleTiles_v1.5.0-pre328_mc1.12.2.jar             | None                                     |
	| LCHIJA | malisiscore                    | 1.12.2-6.5.1-SNAPSHOT   | malisiscore-1.12.2-6.5.1.jar                       | None                                     |
	| LCHIJA | malisisadvert                  | 1.12.2-6.1.0            | malisisadvert-1.12.2-6.1.0.jar                     | None                                     |
	| LCHIJA | malisisblocks                  | 1.12.2-6.1.0            | malisisblocks-1.12.2-6.1.0.jar                     | None                                     |
	| LCHIJA | malisisdoors                   | 1.12.2-7.3.0            | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
	| LCHIJA | malisisswitches                | 1.12.2-5.1.0            | malisisswitches-1.12.2-5.1.0.jar                   | None                                     |
	| LCHIJA | mcjtylib_ng                    | 3.5.4                   | mcjtylib-1.12-3.5.4.jar                            | None                                     |
	| LCHIJA | mekanism                       | 1.12.2-9.8.3.390        | Mekanism-1.12.2-9.8.3.390.jar                      | None                                     |
	| LCHIJA | mekanismgenerators             | 1.12.2-9.8.3.390        | MekanismGenerators-1.12.2-9.8.3.390.jar            | None                                     |
	| LCHIJA | mekanismtools                  | 1.12.2-9.8.3.390        | MekanismTools-1.12.2-9.8.3.390.jar                 | None                                     |
	| LCHIJA | opframe                        | 1.4.0                   | OnlinePicFrame_v1.5.0-pre1_mc1.12.2.jar            | None                                     |
	| LCHIJA | openscreens                    | 1.0.1                   | openscreens-1.12.2-1.0.1.jar                       | None                                     |
	| LCHIJA | rftools                        | 7.73                    | rftools-1.12-7.73.jar                              | None                                     |
	| LCHIJA | rsgauges                       | 1.2.5                   | rsgauges-1.12.2-1.2.5.jar                          | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | scp                            | 2.3.1                   | SCP+Lockdown-1.12.2-2.3.1-dev.jar                  | None                                     |
	| LCHIJA | techguns                       | 2.0.2.0                 | techguns-1.12.2-2.0.2.0_pre3.2.jar                 | None                                     |
	| LCHIJA | theoneprobe                    | 1.4.28                  | theoneprobe-1.12-1.4.28.jar                        | None                                     |
	| LCHIJA | tlauncher_custom_cape_skin     | 1.4                     | tlskincape1.12.2-1.4.jar                           | None                                     |

	Loaded coremods (and transformers): 
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.7.0-232-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
LittlePatchingLoader (LittleTiles_v1.5.0-pre328_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  techguns.core.TechgunsASMTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
CreativePatchingLoader (CreativeCore_v1.10.47_mc1.12.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 1660 Ti/PCIe/SSE2'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:ON, OpenComputers:ON, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: Map Stargate
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Ressourcepack moddé for 1.12.2.zip
	Current Language: Français (France)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 456.71
	OpenGlRenderer: GeForce GTX 1660 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4`

**Comment by CreativeMD** [comment]
Update to the newest CreativeCore and LittleTiles version and it should work.

**Comment by MarcCrams** [comment]
It does not...
