### ISSUE TITLE
LittleTiles + Controllable conflict/crash

### ISSUE THREAD

**Issue by SlayerTheChikken** [CreativeMD/LittleTiles#628]
When both LittleTiles 1.5.0-327 and Controllable 0.11.2 are both present a hard crash occurs (no actual crash log.)
https://github.com/MrCrayfish/Controllable/files/6235248/latest.log line 357 is where the exception occurs, though I'm sure the rest of the log has some hints.

If you need any additional info let me know, the modpack is Tekxit 3.14 on Minecraft 1.12.2.

Crayfish says the issue is from your end of things but I have no opinion on that, the issue on his mod is here: https://github.com/MrCrayfish/Controllable/issues/175

**Comment by SlayerTheChikken** [comment]
Also I would like to say that I love this mod, and congrats on the 1.5.0 release :3

**Comment by CreativeMD** [comment]
https://github.com/MrCrayfish/Controllable/issues/186

**Comment by SlayerTheChikken** [comment]
Appreciate you, thanks

**Comment by CreativeMD** [comment]
Controllable is discontinued, so yeah this won't get fixed sorry.
