### ISSUE TITLE
Slopes issue

### ISSUE THREAD

**Issue by crazynachos** [CreativeMD/LittleTiles#629]
the new slopes have a bug, currently when placing inner and outer slopes and when cutting the inner and outer slope shapes out they simply appear as solid blocks or disappear completely

**Comment by CreativeMD** [comment]
Can you please share a series of screenshot explaining the issue?

**Comment by ghost** [comment]
i have the same. sometimes slopes are not correct placed. 
undo dont work correct when you place slopes or the new walls   and so on.

**Comment by CreativeMD** [comment]
@punkydie Send screenshots so I can reproduce it.

**Comment by CreativeMD** [comment]
If that was an issue related to the chisel then this is fixed. If it was something else make sure to post more information here.
