### ISSUE TITLE
Crash when loading the game.

### ISSUE THREAD

**Issue by modmuss50** [CreativeMD/LittleTiles#63]
https://gist.github.com/modmuss50/09908084f49ff65c5c968f2aba9aac44

LittleTiles v1.5.0-pre40 mc1.11.2.jar
CreativeCore v1.9.4 mc1.12.2.jar

This may be the result of another mod, but I would like to get your feedback first.

**Comment by CreativeMD** [comment]
Wrong LittleTiles version, you are using 1.11.2 instead of 1.12.2 :D

**Comment by modmuss50** [comment]
ah, sorry about that. I should really go to bed 👍

**Comment by CreativeMD** [comment]
Yeah same goes for me
