### ISSUE TITLE
Loading Crash: NoClassDefFoundError: com/creativecore/common/config/premade/Permission

### ISSUE THREAD

**Issue by anabsolutesloth** [CreativeMD/LittleTiles#630]
Crash Log
https://paste.gg/p/anonymous/efe83420a8244ed888cc8de73433b4a0

CreativeMD mod versions:
CreativeCorev.1.10.47_mc1.12.2
LittleTiles_v1.5.0_mc1.12.2

I tried deleting all CreativeCore and LittleTiles config files to let them auto-regenerate, but that did not fix the issue.

Additional Info can be provided if needed.

**Comment by CreativeMD** [comment]
Update CreativeCore.
