### ISSUE TITLE
stone duplication glitch

### ISSUE THREAD

**Issue by VoidBite1** [CreativeMD/LittleTiles#631]
when you have a Activation Plate (player) put it in the little bag (dont close yet) and get the stone pixels out close the bag and open it again and the pixels are stil in it as well as in your inventory

**Comment by VoidBite1** [comment]
https://user-images.githubusercontent.com/82763162/115147571-e9358900-a05b-11eb-89d0-be5d42f2074c.mp4

**Comment by CreativeMD** [comment]
It was just a sync issue. Fixed in the newest.
