### ISSUE TITLE
Unable to go to the menu of LittleLiles tools version 1.5.0 and 1.5.1

### ISSUE THREAD

**Issue by HDL34** [CreativeMD/LittleTiles#634]
Version 1.5.1 does not correct my problem with version 1.5.0. I still have the same bug when I want to open the menu of one of the tools. Especially the little chisel
every time, Minecraft freezes for 10 seconds and I get this after
![image](https://user-images.githubusercontent.com/61374058/115239202-c28c5680-a11e-11eb-8560-9182b6416483.png)
Then Minecraft crash
This is the crash log:
[crash-2021-04-19_14.44.46-client.txt](https://github.com/CreativeMD/LittleTiles/files/6336156/crash-2021-04-19_14.44.46-client.txt)

**Comment by CreativeMD** [comment]
Fixed by updating ALET.
