### ISSUE TITLE
Crashing custom modpack with the newest LT release

### ISSUE THREAD

**Issue by timothygremlin** [CreativeMD/LittleTiles#636]
As above, crashlog attached. Not sure what it is. Will appreciate greatly any response, thanks for your work!
[crash-2021-04-19_20.34.55-client.txt](https://github.com/CreativeMD/LittleTiles/files/6338661/crash-2021-04-19_20.34.55-client.txt)

**Comment by Desoroxxx** [comment]
Update Creative Core : https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3280299

**Comment by timothygremlin** [comment]
Many thanks, it works! Can't believe I didn't think of that hah *facepalm*
