### ISSUE TITLE
Cylinder Shape Not Working

### ISSUE THREAD

**Issue by Desoroxxx** [CreativeMD/LittleTiles#637]
Since the new 1.5, the cylinder shape has holes when the selection is uneven and only when the selection is uneven.

It's glitching on all grids.

Here is in action: 
![image](https://user-images.githubusercontent.com/82710983/115294142-7f4ed980-a158-11eb-9f7b-78b117541e92.png)

Here is my chisel settings:
![image](https://user-images.githubusercontent.com/82710983/115294267-b1603b80-a158-11eb-88c2-27046e2f23eb.png)

Logs: 
[latest.log](https://github.com/CreativeMD/LittleTiles/files/6338660/latest.log)

Little Tiles Version: 1.5.2
Forge Version: 2847

**Comment by CreativeMD** [comment]
Fixed in the newest version!
