### ISSUE TITLE
Version Not Updated In Mod Menu

### ISSUE THREAD

**Issue by Desoroxxx** [CreativeMD/LittleTiles#638]
The version is not updated in the forge menu.

Here is in action:
![image](https://user-images.githubusercontent.com/82710983/115294867-6eeb2e80-a159-11eb-90c2-60b97389fab2.png)

Little Tiles Version: 1.5.2
Forge Version: 2847

**Comment by CreativeMD** [comment]
Sorry, but I don't care about this number ... and I can't be bothered to update it every time.
