### ISSUE TITLE
Glitch When Changing To A Bigger Grid

### ISSUE THREAD

**Issue by Desoroxxx** [CreativeMD/LittleTiles#639]
In the new 1.5 version there is a glitch when you change to a bigger grid, let me explain.

Here is my current grid: 
![image](https://user-images.githubusercontent.com/82710983/115295648-44e63c00-a15a-11eb-8a9e-894a50e7ce31.png)

I changed to:
![image](https://user-images.githubusercontent.com/82710983/115295660-4879c300-a15a-11eb-8abc-e5776449d178.png)

And when I try placing:
![image](https://user-images.githubusercontent.com/82710983/115295729-5e878380-a15a-11eb-9c57-d55bc7e4585f.png)

After placing:
![image](https://user-images.githubusercontent.com/82710983/115295820-76f79e00-a15a-11eb-8344-5b5c1afff789.png)

If you do it the other way around (Changing to a smaller grid) it works perfectly!

**Comment by CreativeMD** [comment]
Thanks for reporting all of this issues! Very good description! Helps me to keep things organized. Fixed in the newest version.
