### ISSUE TITLE
Little Tiles - 1.10.2 - Fix Glitch

### ISSUE THREAD

**Issue by Prochicken19** [CreativeMD/LittleTiles#64]
Hello,
I am currently on V 1.4.12 and I've encountered a glitch. When attempting to make a creation fixed which has 300 tiles or over (roughly) the game kicks you for 'fatal error has occured' is there a  version where this doesn't happen/ upcoming version where this is getting fixed?

Thanks

Information:
This was done on a paid host server
Version: 1.4.12 
Game Version: 1.10.2

**Comment by CreativeMD** [comment]
This has been fixed in 1.5.0 (pre-releases). I can only recommend to update, since this will not be fixed in 1.4 anymore, sorry :(
