### ISSUE TITLE
Crash when opening doors then Ctrl+Z

### ISSUE THREAD

**Issue by Connorado07** [CreativeMD/LittleTiles#641]
Update: 1.5.1

When I made a 3x3 door and opened it and closed it 3 times, then pressed control+Z it crashed the game>

Crash Report: https://pastebin.com/7MdELSwS

**Comment by Desoroxxx** [comment]
Please update to the latest Little Tiles version and try again.

**Comment by CreativeMD** [comment]
Should be fixed in the newest version.
