### ISSUE TITLE
Crash When Undo

### ISSUE THREAD

**Issue by Desoroxxx** [CreativeMD/LittleTiles#642]
Crash when undo after placing a Multi Tiles Structure.

Structure That makes me crash:

Picture:
![image](https://user-images.githubusercontent.com/82710983/115435362-09a34600-a20a-11eb-8113-3092089568ca.png)

Export:
[Bench.txt](https://github.com/CreativeMD/LittleTiles/files/6345320/Bench.txt)

Crash Report:
[crash-2021-04-20_18.49.58-client.txt](https://github.com/CreativeMD/LittleTiles/files/6345282/crash-2021-04-20_18.49.58-client.txt)

Littles Tiles Version: 1.5.2
Forge Version: 2847

**Comment by CreativeMD** [comment]
Fixed in the newest version!
