### ISSUE TITLE
Crash when saving blueprint

### ISSUE THREAD

**Issue by tolerus** [CreativeMD/LittleTiles#644]
Great new features!!

https://paste.dimdev.org/eqikusacid.mccrash

**Comment by CreativeMD** [comment]
There must have been an issue prior, can you send me your log file?

**Comment by tolerus** [comment]
https://paste.dimdev.org/axasojeqem.md

**Comment by CreativeMD** [comment]
I don't need just any log file, I need the one where it did crash.

**Comment by SlayerTheChikken** [comment]
> I don't need just any log file, I need the one where it did crash.

Line 5594, vanillafix prevents full on crashing so he just continued playing it seems, this one seems to be a little low on giving details XD

**Comment by tolerus** [comment]
Slayer is correct; this is the log which includes the crash and playing resumed thereafter without closing the module completely and restarting.

If there are any further details I can provide please let me know! This crash happened only once and I have been able to make further blueprints without issues. I open this ticket only for the purpose of sharing info with you in case it is helpful in your dev!

Your mods are beyond great; I can't imagine playing without them now!! Keep up the awesome work!

Please let me know if there's any other details I can provide which might be useful for you I'm happy to help in any way I can :)

**Comment by CreativeMD** [comment]
Hopefully fixed in the newest CreativeCore version. Seems like it was very unlikely to happen.

**Comment by tolerus** [comment]
Awesome! Yeah, there have been no repeated problems and I have saved and
placed dozens of blueprints much more complicated with all of these new
*awesome* slice shapes. Truly amazing work and there aren't very many other
modders out there who are so tidy with their bug fixes and so dedicated to
streamlining system resources. You really deserve all of your accolades!
