### ISSUE TITLE
Game Freeze when remove large Structure

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#646]
If I build a large building in Grid 1 with the new Walls and then select it with the Little Hammer and the type "Connected" to delete it, the game stops. I then have to end it with the task manager. You can already see how the FPS drops when selecting the building and the type "connected".

Its the latest Version 1.5.3.

There is nothing in the logs or Crashlogs.

**Comment by CreativeMD** [comment]
Do you have enough RAM assigned? Also the question is how large is the building? Obviously there is a limit of what your pc can take.

**Comment by ghost** [comment]
Ich habe mir ein neuen Account gemacht. Ich war Punkydie. Und ja dem Spiel sind 13GB zugewiesen. Das Gebäude wurde wie gesagt mit Grid 1 gebaut. 18 Blöcke hoch und 36 Blöcke lang.

**Comment by CreativeMD** [comment]
Gut ich werde kein Limit einbauen aber die nächste Version wird die Performance in diese Richtung nocheinmal verbessern.
