### ISSUE TITLE
LittleTiles mod causes server crash

### ISSUE THREAD

**Issue by MayonezReyiz** [CreativeMD/LittleTiles#648]
MC Eternal's fresh server file crashes on the first try. I asked on their discord and they sent me here I think this mod causes it somehow here's crash report: https://paste.ee/p/SB2t5

**Comment by CreativeMD** [comment]
What kind of server are you using? This doesn't happen using normal forge servers ...

**Comment by MayonezReyiz** [comment]
I'm using https://www.curseforge.com/minecraft/modpacks/minecraft-eternal MC Eternal's official server pack and it crashes no matter what I do, modpack's mods recommended me to update your mod but it still did not fixed the problem. So basically even with fresh server pack it crashes.

**Comment by CreativeMD** [comment]
It's not an issue of my mod directly. It works absolutely fine normally, so something is wrong. Maybe an incompatibility with another mod, it's hard to tell with these many mods installed. Phosphor for example does not work well alongside LittleTiles.
If you want to make it work, remove half the mods and test if it works. Yes -> add more mods until it doesn't work again. No -> remove more mods until it works.

**Comment by CreativeMD** [comment]
I will close this issue for now. I don't think I can help you there. If you have any news make sure them to post it here.
