### ISSUE TITLE
sliced blocks facing opposite when updating world from "v1.5.0-pre47 mc1.11.2" to "v1.5.0-pre48 mc1.12.2"

### ISSUE THREAD

**Issue by timaute** [CreativeMD/LittleTiles#65]
There was an issue updating my world from 1.11.2 to 1.12.2. This world is using 32 pixel divisions per block. Updating from 1.11.2 to 1.12.2, I made completely sure that i set the config file to 32 grid size. As a result in the 1.12.2 version and using the same world, it did what was supposed to, there were no problems, even the door(multi-tiled structure) that i constructed was alright. The only problem was that the sliced blocks were facing the opposite pattern resulting in a jagged pattern. as seen in these photos. I hope this issue can be solved

from this:
![2017-11-20_20 55 17](https://user-images.githubusercontent.com/33834097/33020096-e3a99cbe-ce37-11e7-83db-5408699d2296.png)
![2017-11-20_20 54 27](https://user-images.githubusercontent.com/33834097/33020097-e410f18e-ce37-11e7-8232-352d099d5a27.png)

to this:
![2017-11-20_19 07 04](https://user-images.githubusercontent.com/33834097/33020115-f6dbd234-ce37-11e7-9433-9b21b3e1b659.png)
![2017-11-20_19 07 34](https://user-images.githubusercontent.com/33834097/33020116-f712bef2-ce37-11e7-99da-5f2d324b2411.png)

**Comment by CreativeMD** [comment]
Oh no, i actually thought i could prevent this from happening. I think you forgot to update CreativeCore, but it should have crashed in order to prevent this from happening. Do you have a backup?

**Comment by CreativeMD** [comment]
Looks there was an issue, which prevented LittleTiles from crashing ... this is a serious problem. I really hope you have a backup of your world.

CreativeCore had an important update which fixed numerous bugs. LittleTiles has to convert all sliced tiles to the new system, but if you are still using the old CreativeCore version everything will be mismatched and updating to the new system will ruin most of your sliced tiles. Please download the newest CreativeCore version, maybe it's working nonetheless (i don't know for sure).

I also deleted pre-48 from curseforge and fixed the issue of not crashing, the new version will be available soon. This should prevent other people from running into the same issue. If somebody uses the wrong CreativeCore version the game will instantly crash now as soon as there are sliced tile.

I'm really sorry for the mess ... this should have not happened ... damn.

**Comment by timaute** [comment]
oh thanks very much and i do have a backup. Thats probably it. I forgot to
download the newest creative core version

**Comment by CreativeMD** [comment]
That's good to hear.
