### ISSUE TITLE
In some cases LittleTiles bypasses many protection systems.

### ISSUE THREAD

**Issue by SlayerTheChikken** [CreativeMD/LittleTiles#650]
Tested in the latest versions (of LittleTiles and CQR) the little chisel is able to bypass protection of placement in CQR protected areas, at first it also seemed like the little hammer can bypass protection but the damage was only done clientside along with the little paintbrush, blueprints can also bypass protection. The common theme I'm seeing here is right clicking instead of left clicking.

This issue has been brought up before long ago (https://github.com/CreativeMD/LittleTiles/issues/390) though I'm not sure if anything has changed since then regarding it, and that issue referenced a different protection plugin and does not line up with this testing as there it says the little hammer bypassed claiming.

Edit: I will soon do testing using many antigrief plugins on spongeforge.

**Comment by CreativeMD** [comment]
Before anything will be placed the event `MultiPlaceEvent` will be fired. If it gets canceled nothing will be placed at all.
Same goes for `BreakEvent` before destroying/ editing anything.

**Comment by CreativeMD** [comment]
I suggest to join this issue, because it's kinda the same thing: https://github.com/CreativeMD/LittleTiles/issues/608
