### ISSUE TITLE
Crash while placing pillars

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#652]
https://pastebin.com/T2ks0Ych

Latest Little Tiles 1.5.4

**Comment by Desoroxxx** [comment]
Can you try without albedo?

**Comment by ghost** [comment]
I think it has nothing to do with Albedo.

**Comment by CreativeMD** [comment]
Can you tell me exactly what you do? I can place pillar shapes with any crashes ... so there must be a weird shape which causes this issue.

**Comment by CreativeMD** [comment]
Can you test if the newest version fixes that issue as well?

**Comment by ghost** [comment]
Nein ist leider immer noch vorhanden.

**Comment by CreativeMD** [comment]
Fixed in the newest version of CreativeCore.
