### ISSUE TITLE
You give sources but not the gradle project

### ISSUE THREAD

**Issue by Protoxy22** [CreativeMD/LittleTiles#653]
Why don't you make a gradle project instead of throwing your files without any instructions ?

I am taking hours and hours to update my version of LittleTiles, crashes, whole chunks disappear, my map doesn't work with your damn sources files ...

How can we imagine the setup for your coremod ?

**Comment by CreativeMD** [comment]
https://www.youtube.com/watch?v=7Ahshi_QjM4
