### ISSUE TITLE
latest version causes server & client crash (null pointer exception on load)

### ISSUE THREAD

**Issue by iceyrazor** [CreativeMD/LittleTiles#656]
with my current mod pack i have (witch i think you can see in the crash report) the client and server crashes.

however with LittleTiles_v1.5.0-pre199_73_mc1.12.2. i can load the pack just fine.

server crash file.
[crash-2021-04-28_18.06.30-server.txt](https://github.com/CreativeMD/LittleTiles/files/6395429/crash-2021-04-28_18.06.30-server.txt)

client crash
[crash-2021-04-28_18.08.50-client.txt](https://github.com/CreativeMD/LittleTiles/files/6395431/crash-2021-04-28_18.08.50-client.txt)

**Comment by CreativeMD** [comment]
If you want to update LittleTiles you also need to update CreativeCore.

**Comment by iceyrazor** [comment]
oh ok my bad XD. could you possibly code in somthing where it tells you that the library file is outdated, like most mods do?

**Comment by CreativeMD** [comment]
Not really possible, because it crashes too soon. It will definitely be different in 1.16
