### ISSUE TITLE
block duplication in little bag

### ISSUE THREAD

**Issue by Rainnifer** [CreativeMD/LittleTiles#657]
I noticed there seems to be a problem with structures and the little bag, I don't know if it's my structure specifically but I used less than 1 block of little storage block to make a chest, which also consists of a door and fixed structure all in one structure. The first problem I noticed was it told me I don't have enough little storage pixels to place the structure, even though I had the whole block in my inventory and the structure used less than a block. Then I noticed after getting a second block of the little storage blocks I was able to place the structure. When I broke the structure and put it in the little bag it gave back more little storage blocks than were used.

https://user-images.githubusercontent.com/83443525/116652316-8ccf4500-a94a-11eb-8cd6-c20ba06c20b6.mp4

**Comment by CreativeMD** [comment]
Unfortunately I can't view the video. Can you export your structure and send it here, so I can test it myself?

**Comment by Rainnifer** [comment]
I had converted the video using VLC (and it played through there) I'm not sure why it didn't work sorry about that but here's the structure
[simplechest.txt](https://github.com/CreativeMD/LittleTiles/files/6407823/simplechest.txt)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thank you very much for sharing issue! Your description made it very easy for me to reproduce and fix it.
