### ISSUE TITLE
Problem beim platzieren von Walls

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#660]
https://i.gyazo.com/thumb/1200/9c1a891afe3577a0e2adef6bf584abe9-jpg.jpg

in der luft ist der stuhl normal
nach dem placen mit dem blueprint haut er da noch zeug ran
die lehne ist mit walls gemacht
und beim undo lässt er das da

https://gyazo.com/d8e1ea4fb971a8e405284a6045c303a7

halte ich shift gedrück und platziere ihn im minecraft grid funktioniert es ohne probs

**Comment by Desoroxxx** [comment]
Are you using Latest Little Tiles Version?

**Comment by ghost** [comment]
yes

hier ist der blueprint zum testen

https://www.comgames.de/stuhl.txt

**Comment by Desoroxxx** [comment]
It's not happening in my testing.

For further troubleshooting please report all the mods in your modpack.
And if you have time tell us the specification of your computer.

**Comment by ghost** [comment]
Bitte teste es richtig. Ich habe es auch und gerade nochmal ohne Mods getestet. Es ist und bleibt vorhanden! Im Singleplay genauso. Es funktioniert nur ohne Probleme im Minecraft Grid aber nicht im Little Tiles Grid.

**Comment by Desoroxxx** [comment]
Weird i used 4 grid and 16 grid

**Comment by ghost** [comment]
https://gyazo.com/54f442659a4fc136ff8987fff5074354

Der Stuhl im Hintergrund ist im Minecraft Grid platziert ohne Probleme. 

Der Stuhl im Vordergrund nicht und bei dem ist die Lehne nicht mehr so wie sie sein soll.

**Comment by Desoroxxx** [comment]
I got no problem with any grid or placement.

**Comment by ghost** [comment]
with my blueprint ?

**Comment by ghost** [comment]
1.5.6 Little Tiles

**Comment by ghost** [comment]
ups wrong account :D

**Comment by CreativeMD** [comment]
Sollte behoben sein in der neusten Version.

Should be fixed in the newest version!
