### ISSUE TITLE
Using wrench on output not connected to a structure returns a null error

### ISSUE THREAD

**Issue by Doc-1** [CreativeMD/LittleTiles#661]
~As the title says. when right-clicking an output that is connected to a premade signal display with a wrench. I get the following error, no crash.~
Wait, scratch that. I had neglected to make the structure that contains the output into a fixed structure. So rather using the wrench on an output/input that is not a part of a structure returns a null. My apologies for misunderstanding that.
[null error.txt](https://github.com/CreativeMD/LittleTiles/files/6415987/null.error.txt)

**Comment by CreativeMD** [comment]
Fixed in the newest version!
