### ISSUE TITLE
LT 1.5.7: Crash when placing a MultidoorStructure with Inputs and Outputs

### ISSUE THREAD

**Issue by DonK4rma** [CreativeMD/LittleTiles#663]
[Game_Crash.txt](https://github.com/CreativeMD/LittleTiles/files/6422136/Game_Crash.txt)

I been making a piano and i needed to put inputs and outputs for the key, now i cant place them next to each other, if i do the game crashes, i tried increasing the limit of tiles in a block but dint do anything, still crash.

Structure Options and Details
Stay Animated
No Sound when door finish
Sound Player
Around 7 Doors in the structure

Hope you be able to fix it

**Comment by ghost** [comment]
But according to your crash log you are still using the old 1.5.6 version. 1.5.7 just came out today.

**Comment by DonK4rma** [comment]
> But according to your crash log you are still using the old 1.5.6 version. 1.5.7 just came out today.

Sorry that log was sent before i did upgrade the same thing with 1.5.7, has the same problem

**Comment by Desoroxxx** [comment]
Just to help troubleshooting the issue, some information need to be provided.

Can you give use your config files,
Can you export the structure you are trying to place.

That should be it for now

**Comment by DonK4rma** [comment]
> Just to help troubleshooting the issue, some information need to be provided.
> 
> Can you give use your config files,
> Can you export the structure you are trying to place.
> 
> That should be it for now



> Just to help troubleshooting the issue, some information need to be provided.
> 
> Can you give use your config files,
> Can you export the structure you are trying to place.
> 
> That should be it for now

This are the mods and the config files i am trying to use and also the structure that i cant place multiple of them in one block

https://drive.google.com/drive/folders/1tW2uNg14ErDjQzVlDHiHDgokc1E9oq7V?usp=sharing

**Comment by Desoroxxx** [comment]
Okay, it will not really help by try changing 62048 to 65536 in the config files.

**Comment by DonK4rma** [comment]
> Okay, it will not really help by try changing 62048 to 65536 in the con

**Comment by CreativeMD** [comment]
Is it fixed now?

**Comment by Desoroxxx** [comment]
No, he closed it by accident you can reopen it think.
![image](https://user-images.githubusercontent.com/82710983/117148138-3e8ccc80-adb6-11eb-996d-2d7852f7caf5.png)

**Comment by DonK4rma** [comment]
No problem still around

**Comment by CreativeMD** [comment]
Okay the problem is actually quite simple. Your recipe contains duplicated structures, which causes this issue. Normally this should not happen in the first place, but with the recently added feature of being able to pick up animations in the recipe it can happen.

Looks like you picked up the recipe while the structure was placed and an animation was there.

So you need to somehow remove the duplicates, which is quite difficult to be honest. I will also add a system which checks that something like this won't happen. 

Here is a fixed version of your structure:
[structure-fixed.txt](https://github.com/CreativeMD/LittleTiles/files/6435165/structure-fixed.txt)

Until the new system is in place be careful what you pick up in your recipe.

**Comment by DonK4rma** [comment]
> Okay the problem is actually quite simple. Your recipe contains duplicated structures, which causes this issue. Normally this should not happen in the first place, but with the recently added feature of being able to pick up animations in the recipe it can happen.
> 
> Looks like you picked up the recipe while the structure was placed and an animation was there.
> 
> So you need to somehow remove the duplicates, which is quite difficult to be honest. I will also add a system which checks that something like this won't happen.
> 
> Here is a fixed version of your structure:
> [structure-fixed.txt](https://github.com/CreativeMD/LittleTiles/files/6435165/structure-fixed.txt)
> 
> Until the new system is in place be careful what you pick up in your recipe.

Thanks ill try that and update the situation

**Comment by DonK4rma** [comment]
Great Seems to be working now, thanks for taking your time to this issue
