### ISSUE TITLE
Issue - 1.12.2 Preview Rendering at reduced brightness depending on time of day about 20% less bright

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CreativeMD/LittleTiles#664]
So I came across a strange issue that is affecting rendering brightness. 

![z9tj9D4 1](https://user-images.githubusercontent.com/10351221/117028155-0c4e7280-acc3-11eb-8b45-450184d5cfc2.png)

Now here is is in game.

![LaXjW4U 1](https://user-images.githubusercontent.com/10351221/117028217-1b352500-acc3-11eb-886b-4015a2ac9dd4.png)

For some reason this also affected by the time of day ...

Here is my modlist. Not sure it helps.

![tUPT3KM 1](https://user-images.githubusercontent.com/10351221/117028298-330ca900-acc3-11eb-9984-efe7f0c8c8ba.png)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
