### ISSUE TITLE
Overwrite Modus Problem

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#665]
Also 2 Sachen. 
Wenn der Modus auf Standart steht  konnte man immer mit strg gedrückt strukturen überschreiben. Das funzt nicht mehr. 

Und im Overwrite Modus kann man keine Strukturen platzieren. 

Mit dem kleinen Meisel usw funzt das im Overwrite Modus aber keine Strukturen.

**Comment by ghost** [comment]
Also wenn die Struktur auf None steht dann geht es. Aber nicht wenn man einen Typ vergibt.

**Comment by ghost** [comment]
{tiles:[{bBox:[I;24,240,12,28,244,16],tile:{block:"littletiles:ltcoloredblock"}}],min:[I;4,200,0],size:[I;56,48,25],children:[{tiles:[{bBox:[I;28,220,0,44,236,16],tile:{color:-13619152,invisible:1b,block:"littletiles:ltcoloredblock"}}],count:1,dynamic:1b,structure:{color:-13619152,facing:2,dynamic:1b,id:"single_output4",state:0}},{tiles:[{boxes:[[I;29,229,20,40,232,23],[I;35,228,20,40,229,23],[I;36,221,20,40,228,23],[I;36,222,23,37,227,24],[I;35,220,20,36,228,23],[I;29,219,20,35,229,23],[I;28,220,20,29,232,23],[I;27,221,20,28,232,23],[I;26,222,20,27,232,23],[I;27,222,23,28,227,24],[I;28,221,23,29,228,24],[I;35,221,23,36,228,24],[I;29,220,23,35,229,24]],tile:{block:"minecraft:concrete"}},{boxes:[[I;27,222,24,28,227,25],[I;28,221,24,29,228,25],[I;36,222,24,37,227,25],[I;35,228,24,36,229,25,-2147483630,-1],[I;36,227,24,37,228,25,-2147483630,-1],[I;36,221,24,37,222,25,-2147482496,65537],[I;35,220,24,36,221,25,-2147482496,65537],[I;28,220,24,29,221,25,-2142765056,65537],[I;27,221,24,28,222,25,-2142765056,65537],[I;28,228,24,29,229,25,-2147409920,-1],[I;27,227,24,28,228,25,-2147409920,-1],[I;35,221,24,36,228,25],[I;29,220,24,35,229,25],[I;44,204,16,52,244,24],[I;12,204,16,20,244,24],[I;4,216,16,8,232,24],[I;20,200,16,24,248,24],[I;8,240,16,12,244,24,-2147409920,-196612],[I;4,208,16,8,216,24,-2145124352,262148],[I;8,208,16,12,240,24],[I;8,204,16,12,208,24,-2142765056,262148],[I;12,200,16,20,204,24,-2142765056,262148],[I;24,200,16,44,216,24],[I;36,216,20,40,221,24],[I;40,216,16,44,232,24],[I;38,222,23,40,228,24],[I;35,229,23,40,230,24],[I;29,230,23,40,232,24],[I;24,216,20,26,232,24],[I;24,232,20,44,248,24],[I;27,229,23,29,232,24],[I;26,227,23,27,232,24],[I;26,216,20,27,222,24],[I;29,216,20,35,219,24],[I;27,216,20,28,221,24],[I;35,216,20,36,220,24],[I;37,221,23,40,222,24],[I;36,228,23,40,229,24],[I;37,227,23,38,228,24],[I;27,228,23,28,229,24],[I;28,216,20,29,220,24],[I;44,200,16,52,204,24,-2147482496,262148],[I;52,208,16,56,240,24],[I;56,216,16,60,232,24],[I;56,208,16,60,216,24,-2147483072,-196612],[I;52,204,16,56,208,24,-2147482496,262148],[I;52,240,16,56,244,24,-2147483630,-196612],[I;44,244,16,52,248,24,-2147483630,-196612],[I;24,216,16,40,248,20],[I;40,232,16,44,248,20],[I;4,232,16,8,240,24,-2147446784,262148],[I;56,232,16,60,240,24,-2147483639,-196612],[I;12,244,16,20,248,24,-2147409920,-196612]],tile:{block:"littletiles:ltcoloredblock"}},{boxes:[[I;29,229,23,35,230,24],[I;36,221,23,37,222,24],[I;35,220,23,36,221,24],[I;29,219,23,35,220,24],[I;28,220,23,29,221,24],[I;27,221,23,28,222,24],[I;26,222,23,27,227,24],[I;27,227,23,28,228,24],[I;28,228,23,29,229,24],[I;37,222,23,38,227,24],[I;36,227,23,37,228,24],[I;35,228,23,36,229,24]],tile:{color:-6645094,block:"littletiles:ltcoloredblock"}}],count:78,dynamic:1b,structure:{toActivate:[I;],activate:{mode:"TOGGLE",result:0,con:"p.o0",delay:1,bandwidth:1,before:0,state:0},dynamic:1b,id:"state_activator"}}],grid:256,count:1,structure:{name:"Schalter",id:"fixed",signal:[{mode:"EQUAL",con:"c1.b0",delay:1,index:0,state:0}]}}





Habe mal die Structur hochgeladen als Beispiel. Diese kann man nicht im Overwrite Modus placen auch mit mit STRG

**Comment by CreativeMD** [comment]
Ist in der neusten Version behoben.
