### ISSUE TITLE
Low Resolution Vorschau funktioniert nicht

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#667]
Wenn ich in kleinen Grids etwas bauen will und mit dem Markmod die Vorschau aktiviere ist die Vorschau nicht im Low resolution Modus und das Spiel fängt an komplett zu freezen.

**Comment by CreativeMD** [comment]
Low Resolution Mode soll verhindern, dass das Spiel überfordert wird. Deswegen muss es erst deaktiviert werden. Indem man mit CTRL + M die GUI aufruft und das Häkchen entfernt. Ich kann anhand deiner Beschreibung nicht genau entnehmen wann genau bei dir das Spiel freezt. Wäre gut wenn du das nochmal genauer erklären könntest.

**Comment by ghost** [comment]
Ja ich weiß das er verhindern soll dass das Spiel nicht überfordert wird. Das Problem ist, das er die ganze Zeit aktiviert ist aber in der Vorschau bei einem Grid von 128 und kleiner nicht aktiv ist. Also das Häckchen ist drin aber der Modus selbst irgendwie nicht aktiv. Wenn Du im 128 Grid eine Sphere machen willst im Markmode ist das nicht möglich. Irgendwann freezt das Bild. Also wenn du das Ganze immer mehr zur Kugel formst. Hoffe Du verstehst was ich meine.

**Comment by CreativeMD** [comment]
Ja ist keine gute Idee, ein Sphere mit 128 Grid killt sofort die Performance, niemals anzeigen lassen. Manche Shapes haben da eine Sicherung angebaut, die aber nicht vom Grid abhängt deswegen kann es da immer noch zu Problemen führen. Zusammengefasst wird die Kugel nur angezeigt wenn das Volumen kleiner als 4 Blöcke ist glaube ich. Ich würde ehrlich gesagt komplett davon abraten überhaut so etwas zu bauen.
