### ISSUE TITLE
Advanced Door Disappearing after re-logging into world

### ISSUE THREAD

**Issue by ricey125** [CreativeMD/LittleTiles#668]
I have an advanced door that stays activated to a 45 degree shift, but only it disappears when I log out of the world and not the other advanced doors I also have activated. I also want to note that it is COMPLETELY gone, no ghost blocks or invisible collision. Not even a blueprint floating on the ground. Just completely gone until replaced.

**Comment by CreativeMD** [comment]
Does it happen all the time consistently? If yes send me your world so I can reproduce it.

**Comment by ricey125** [comment]
> Does it happen all the time consistently? If yes send me your world so I can reproduce it.

It doesnt happen consistently, and then sometimes reappears in its proper place if I place the same door somewhere else. As of right now Im not having issues with it.
