### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#669]
https://pastebin.com/s75JdcpM

Das hatte gerade ein Spieler von mir nach dem er Undo gemacht hat. Keine Ahnung wie das passiert ist kann das nicht reproduzieren. Vielleicht reicht Dir ja schon der Report.

**Comment by CreativeMD** [comment]
Werde das Issue erstmal schließen, brauche mehr Informationen um da was machen zu können, dass ist ein absolut nichts aussagender Fehler.
