### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by saphsara** [CreativeMD/LittleTiles#67]
Love the mod... I been having a crashing issue and and i think it is something with LittleTiles. attached is link to crash report. since i installed mod on server , we had log in issue and when we can log in we randomly crash .  i removed mod and had no issue logging in . of cause it removed everything that had to do with mod, as soon as i added mod back we had issues the minute i placed a cut tile from mod. 
Crash Report Link
https://1drv.ms/t/s!AtL7UzgcOoZ3swAAUhljnHjSe5fd   

MC 1.12.2 
forge 2537
Thank for looking into this.

**Comment by CreativeMD** [comment]
Looks like the mod albedo is causing this issue, no idea what this mod is doing, but it might be a good idea to report this issue to him.

**Comment by saphsara** [comment]
Ok thank you. Sorry about that I read it wrong. Still learning .. 



null

**Comment by CreativeMD** [comment]
No no, this crash is related to LittleTiles, but the exception itself is thrown by Albedo. Your are not doing anything wrong, but we need @elucent in order to fix this issue properly.

Might be a good idea to continue the discussion over there: https://github.com/elucent/Albedo/issues/13

**Comment by saphsara** [comment]
Thank you  :)

**Comment by CreativeMD** [comment]
This crash seems to be fixed.
