### ISSUE TITLE
java.lang.NullPointerException: Unexpected error

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#672]
https://pastebin.com/ibx8vNMJ

Weiterer Fehler. Weiß nicht ob es mit dem Overwrite zu tun hat. Denn ich habe nochmal versucht irgendwas im Overwritemodus zu placen was nicht geht und bin dann nur etwas rumgeflogen und es kam zu dem Crash.

**Comment by CreativeMD** [comment]
Sehr komischer Fehler, update mal zur neusten CreativeCore version, wenn es dann nochmal passiert habe ich mehr Informationen. Werde aber bis dahin das Issue erstmal schließen.
