### ISSUE TITLE
Bugs and Crashes in V1.5.8

### ISSUE THREAD

**Issue by NikolajLindevall** [CreativeMD/LittleTiles#673]
some the tile types can cause the game to crash.
if place down the particle emitter the game crashes.
the rotation doesn't work.

**Comment by ghost** [comment]
Please add Crash-Reports here
You can find them in minecraft folder "crash-reports"

**Comment by NikolajLindevall** [comment]
[crash-2021-05-12_15.54.28-client.txt](https://github.com/CreativeMD/LittleTiles/files/6472045/crash-2021-05-12_15.54.28-client.txt)

**Comment by CreativeMD** [comment]
That's an issue with the RTM mod and I cannot do anything about it. I'm sorry but you have to decided between either one of the mods.
