### ISSUE TITLE
Pathfinding mobs 

### ISSUE THREAD

**Issue by Kerlann** [CreativeMD/LittleTiles#676]
hello is it possible to make littletiles compatible with the pathfinding of mobs ?

thanks

example:

blocked:
![image](https://user-images.githubusercontent.com/34661926/118343473-969b9f80-b529-11eb-8fe6-ff1a704faffe.png)

no blocked:
![image](https://user-images.githubusercontent.com/34661926/118343497-b9c64f00-b529-11eb-9fe8-9fc92950f021.png)

**Comment by ghost** [comment]
I had the same problem with Custom NPC. This is because the mobs or NPC's only know the standard Minecraft grid. Make sure that the opening of a door is in the standard Minecraft grid. You can test this by placing a block in the opening.

**Comment by CreativeMD** [comment]
I'm sorry, but this is not that easy to fix and definitely won't happen for 1.12. I will look into it in a later version, but no idea if I will ever implement something like this.
