### ISSUE TITLE
one of the keys is bind to "NONE"

### ISSUE THREAD

**Issue by Teebee21** [CreativeMD/LittleTiles#679]
When trying to pull out the configure menu for like the little blueprint the key to that is set to none. How to change the key bind?
See Screenshot.
![image](https://user-images.githubusercontent.com/84282153/118403297-81805700-b676-11eb-8758-2a8ab0ff9812.png)

**Comment by kirokadura** [comment]
In your Keybind settings. Same manu where you can change other Minecraft related keybinds. Should be Options -> Controls...
