### ISSUE TITLE
Something goes wrong when turning a pipe structure

### ISSUE THREAD

**Issue by TheRealRu** [CreativeMD/LittleTiles#680]
The pipe should look like this: 

https://cdn.discordapp.com/attachments/276752435869908993/843614359184080956/unknown.png

But after it has been turned a few times (or even just once) it becomes this:

https://cdn.discordapp.com/attachments/276752435869908993/843614509192708106/unknown.png

What I see happening here: the first outer slice type, seems to be tranforming into the next, as result of me turning it, for some reason.

https://cdn.discordapp.com/attachments/276752435869908993/843615777864810496/unknown.png (seen here)

Following is some extra information:

Pipe used: {tiles:[{boxes:[[I;5,7,5,7,9,6],[I;5,7,6,6,9,7],[I;6,6,5,7,7,6],[I;9,6,5,10,10,6],[I;10,7,5,11,9,7],[I;6,9,0,7,10,10],[I;5,7,0,11,9,5],[I;7,9,0,10,10,5],[I;6,6,0,10,7,5],[I;7,5,0,9,6,5],[I;5,9,0,6,10,6,-2147446784,65537],[I;6,10,0,7,11,5,-2147446784,65537],[I;5,0,6,6,6,7,-2147217408,65537],[I;6,0,5,7,5,6,-2147217408,65537],[I;6,5,0,7,6,5,-2145124352,65537],[I;5,6,0,6,7,6,-2145124352,65537],[I;9,10,0,10,11,5,-2147483639,-1],[I;10,9,0,11,10,6,-2147483639,-1],[I;9,5,0,10,6,5,-2147483072,-1],[I;10,6,0,11,7,6,-2147483072,-1],[I;9,5,5,10,6,6,-2147483584,-65536],[I;10,6,6,11,7,7,-2147483584,-65536],[I;10,0,6,11,6,7,-2147483583,-1],[I;9,0,5,10,5,6,-2147483583,-1],[I;5,0,9,6,9,10,-2145279982,393222,393217,393217],[I;6,0,9,7,9,10],[I;5,0,7,7,9,9],[I;6,0,10,7,10,11,-2145279982,327685,327681,327681],[I;7,0,9,9,10,11],[I;7,0,5,8,9,9],[I;6,0,6,7,9,7],[I;9,0,6,10,9,7],[I;9,0,9,10,9,10],[I;8,0,5,9,9,7],[I;7,9,5,9,10,9],[I;8,0,7,11,9,9],[I;9,0,10,10,10,11,-2147409382,393215,393215,327685],[I;10,0,9,11,9,10,-2147409382,458751,458751,393222],[I;9,9,6,10,10,10],[I;5,9,6,6,10,9,-2147409920,-1],[I;6,10,5,7,11,10,-2147409920,-1],[I;9,10,5,10,11,10,-2147483630,-1],[I;10,9,6,11,10,9,-2147483630,-1],[I;7,10,0,9,11,11],[I;10,9,9,11,10,10,-2147483127,-1,-65536],[I;5,9,9,6,10,10,-1876914176,65537,65536],[I;6,10,10,7,11,11,-1876914176,65537,65536],[I;6,5,5,7,6,6,-1090256896,65536],[I;5,6,6,6,7,7,-1090256896,65536],[I;9,10,10,10,11,11,-2147483127,-1,-65536]],tile:{block:"kirosblocks:colored_metal_block"}}],min:[I;5,0,0],size:[I;6,11,11],count:50}

Pipe used after it breaks: {tiles:[{boxes:[[I;10,7,5,11,9,7],[I;9,7,5,10,9,6],[I;10,6,6,11,7,7],[I;10,6,9,11,10,10],[I;9,7,10,11,9,11],[I;6,9,6,16,10,7],[I;11,7,5,16,9,11],[I;11,9,7,16,10,10],[I;11,6,6,16,7,10],[I;11,5,7,16,6,9],[I;10,9,5,16,10,6,-2097135612,65537],[I;11,10,6,16,11,7,-2097135612,65537],[I;9,0,5,10,6,6,-2097151740,65537],[I;10,0,6,11,5,7,-2097151740,65537],[I;11,5,6,16,6,7,-2096103168,65537],[I;10,6,5,16,7,6,-2096103168,65537],[I;11,10,9,16,11,10,-2097020896,-1],[I;10,9,10,16,10,11,-2097020896,-1],[I;11,5,9,16,6,10,-2088761344,-1],[I;10,6,10,16,7,11,-2088761344,-1],[I;10,5,9,11,6,10,-2097149952,-65536],[I;9,6,10,10,7,11,-2097149952,-65536],[I;9,0,10,10,6,11,-2097149920,-1],[I;10,0,9,11,5,10,-2097149920,-1],[I;6,0,5,7,9,6,-2096013294,393222,393217,393217],[I;6,0,6,7,9,7],[I;7,0,5,9,9,7],[I;5,0,6,6,10,7,-2096013294,327685,327681,327681],[I;5,0,7,7,10,9],[I;7,0,7,11,9,8],[I;9,0,6,10,9,7],[I;9,0,9,10,9,10],[I;6,0,9,7,9,10],[I;9,0,8,11,9,9],[I;7,9,7,11,10,9],[I;7,0,8,9,9,11],[I;5,0,9,6,10,10,-2088558574,327685,327685,-1],[I;6,0,10,7,9,11,-2088558574,393222,393222,-1],[I;6,9,9,10,10,10],[I;7,9,5,10,10,6,-2097143806,-1],[I;6,10,6,11,11,7,-2097143806,-1],[I;6,10,9,11,11,10,-2097086448,-1],[I;7,9,10,10,10,11,-2097086448,-1],[I;5,10,7,16,11,9],[I;6,9,10,7,10,11,-2088632288,-1,-65536],[I;6,9,5,7,10,6,-1827651580,65537,65536],[I;5,10,6,6,11,7,-1827651580,65537,65536],[I;10,5,6,11,6,7,-1140850432,65536],[I;9,6,5,10,7,6,-1140850432,65536],[I;5,10,9,6,11,10,-2088632288,-1,-65536]],tile:{block:"kirosblocks:colored_metal_block"}}],min:[I;5,0,5],size:[I;11,11,6],count:50}

My version of CC: CreativeCore_v1.10.58_mc1.12.2
My version of LT: LittleTiles_v1.5.8_mc1.12.2

I hope this can be fixed, because it's really annoying when making pipelines.

P.S:
It also looks weird in the inventory
![afbeelding](https://user-images.githubusercontent.com/50378605/118415494-ec4b8580-b6aa-11eb-8807-da00466117c4.png)

**Comment by ghost** [comment]
I have observed something similar. If you just place slices and put outer corners on it and then create it as a structure, it can't be rotated properly without looking different.

https://gyazo.com/de5640118d73d76d5de658220590e246

https://gyazo.com/de7025c3e55ca52fbbfcdf7e83324523

https://gyazo.com/eb517559a3d2797a586791980d174371

Maybe it has something to do with that, too.

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks a lot for reporting this issue, there was some code which should handle this, but it had some mistakes in there.
