### ISSUE TITLE
Blueprint building being weird

### ISSUE THREAD

**Issue by ablazingrace** [CreativeMD/LittleTiles#681]
LittleTiles_v1.5.10_mc1.12.2
CreativeCore_v1.10.59_mc1.12.2
Relevant discussion: https://discord.com/channels/256109634769780737/276752435869908993/843978529335148556

I'm not sure how to even say this. I was making a blueprint to test a couple other bugs involving lighting and size problems and found this one in the process. Basically I made a blueprint, 1 16bit high, and tried to build it up using the blueprint. This blueprint were made mostly with slices
Here's the original that I made the blueprint with, just the 1 bit high section.
![Screenshot (4)](https://user-images.githubusercontent.com/56435301/118569519-1737e700-b748-11eb-930a-b8f7fc8860eb.png)
The result.
![Screenshot (5)](https://user-images.githubusercontent.com/56435301/118569522-18691400-b748-11eb-87a1-b10537e34fff.png)

Like I said, I found this while I was trying to figure out a lighting and sizing issue earlier shown here
![Screenshot (3)](https://user-images.githubusercontent.com/56435301/118569670-5bc38280-b748-11eb-9f17-953bb4e87546.png)
For this part I had made a similar blueprint, except I made it 8 bits high. The blueprint itself seems to have either doubled itself vertically, or tried to fill in the space above the model to make it a full block high. I don't know. I figure the weird lighting seam was tied to that somehow.

**Comment by CreativeMD** [comment]
I'm sorry but I can't change anything about that lighting. Might be different in 1.16, but things definitely won't change in 1.12.
