### ISSUE TITLE
Problem mit Slices

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#682]
Ob es nun beim kopieren per Blueprint kommt oder auch in der live Benutzung, Slices werden manchmal einfach nicht platziert oder kopiert usw. 

Problem ist hier ziemlich gut erkennbar:

https://discord.com/channels/256109634769780737/276752435869908993/844591896869470229

**Comment by ghost** [comment]
https://gyazo.com/903f2739668b86543bf2cf69f16bf6d5

Einfach mal 3x 4-5 Tiles lange Linien mit diesem Slicetyp nach links und übereinander ziehen. Da erkennt man das Problem mit dem platzieren. Und wenn dann min 3 übereinander platziert sind blueprint erstellen oder mit shift kopieren und platzieren da fehlt dann eine linie.

**Comment by Mrredstone53** [comment]
Mahlzeit
ich möchte kurz freundlich anmerken 
ist ja ganz nett wie du es erklärst aber ich glaube das gesamte Team wäre glücklich, wenn du entweder einfache sinnvolle sätze bildest oder Englisch schreibst... es ist grad für die englischen teamler schwer zu verstehen bzw. schlecht zu übersetzen...
ich danke dir vielmals ^^ aber um dein Problem wird sich gerade gekümmert
MFG
der deutsch-englisch Übersetzer
~Shadow

PS:
(ich bin niemand direkt vom team möchte ich nur anmerken aber das Team besteht halt aus einigen deutschen und einigen englisch sprechenden)

**Comment by Mrredstone53** [comment]
Und bei dem ersten link -> Discord kann man nix sehen... oder ist der zweite link das gleiche? O.o
MFG

**Comment by ghost** [comment]
Ja, ich gehe von aus, dass den Fehler letztendlich sowieso CreativeMD fixt und er versteht ja Deutsch. Aber gut ich kann es auch zukünftig in Englisch schreiben. 

Und ja, der zweite Link zeigt nur den Slicetyp, mit dem man diesen Test, den ich beschrieben habe, vollziehen soll.

**Comment by Mrredstone53** [comment]
Ja ist ja an sich richtig aber auch er hat Helfer 
du wirst nicht glauben wie viele "Fehler" vom Benutzern selbst ausgelöst werden 
ich hab es wie gesagt fleißig es meinen englischsprachigen freund übersetzt
hast halt einfach bessere Karten schneller Hilfe zu bekommen ^^
ich danke dir vielmals für den bugreport und wie ich schon sagte, kümmert sich ein Helfer schon darum den Fehler zu reproduzieren

MFG
Shadow
(Kein offizieller helfer/teamler)

**Comment by CreativeMD** [comment]
@Mrredstone53 Hey, vielen Dank für deinen Einsatz. Hier Englisch zu schreiben ist sicherlich keine schlechte Idee, aber Deutsch ist auch okay (in dem Fall kann nur ich mich halt darum kümmern). Ansonsten bin ich @blakedj012 für seine Arbeit sehr denkbar, ich chatte mit ihm viel privat und kann ihn daher sehr schnell nach mehr Information fragen.

Grundsätzlich freue ich mich natürlich über jede Hilfe, also wenn du Lust hast ein Moderator zu werden kannst du mich ja mal auf Discord anschreiben.

Problem ist übrigens in der neusten Version behoben.
