### ISSUE TITLE
Pillar shape being weird

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#687]
https://gyazo.com/bcd493c84c3c909757e0a5cc83f13017

It doesn't matter if it's left or right of a pillar, the result is always the same, see picture. Also the grid does not play a role.

**Comment by ghost** [comment]
So here again similar problem:

normal:
https://gyazo.com/8eb8b1d92c5ed9e941c14401ac08c8c2


After I put a few strips on the pillars, the shape of the pillars changes. It is not always in the same place. Sometimes it doesn't happen at all but sometimes it does:
https://gyazo.com/8507dd18b59e7fcca145ff91dde1fe3b

And if I then do Undo this comes out:
https://gyazo.com/5d02d55fd165bb4de060ed8c83d3b5ea


The same phenomenon often happens with pillars on different building objects.

**Comment by CreativeMD** [comment]
I think you forgot to update CreativeCore. It works absolutely fine for me.

**Comment by CreativeMD** [comment]
Won't be fixed in 1.12.
