### ISSUE TITLE
game crashes when I press "R" which is the keybind for "Configure Tool"

### ISSUE THREAD

**Issue by Lyj4n** [CreativeMD/LittleTiles#688]
pretty much the title.
It crashes when I configure the Little Chisel tool
I'm using the latest version of LittleTiles

it doesn't seem to crash when I configure other tools such as the Little Blueprint
_Note: I didn't encounter this bug on the previous version_

**Comment by CreativeMD** [comment]
I need the crash-report.

**Comment by ghost** [comment]
I can't reproduce the problem on my end. A crash log would be really helpful.

**Comment by Lyj4n** [comment]
[crash-2021-05-24_13.10.33-client.txt](https://github.com/CreativeMD/LittleTiles/files/6529976/crash-2021-05-24_13.10.33-client.txt)

**Comment by CreativeMD** [comment]
Update ALET.
