### ISSUE TITLE
game crashes instantly

### ISSUE THREAD

**Issue by JariXXL25** [CreativeMD/LittleTiles#690]
the mod crashes my game instantly. it doesnt say why it crashed but i really wanna try out this mod
![Schermopname (89)](https://user-images.githubusercontent.com/84719458/119349731-c28ff100-bc9e-11eb-89d5-84b681ee87fc.png)

**Comment by CreativeMD** [comment]
Make sure to install CreativeCore as well.

**Comment by JariXXL25** [comment]
> Make sure to install CreativeCore as well.

it still crashes but now it says:The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: com/creativemd/creativecore/core/CreativeCoreClient
Exitcode: -1
