### ISSUE TITLE
Crash while placing Pillars in other Tiles 

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#691]
https://gyazo.com/4a07324036584341f64475cf928d6364

Its default Mode when i rightclick then it crashes

https://pastebin.com/GiaE5R5b

Here is the Structure: https://www.comgames.de/laube.txt

**Comment by ghost** [comment]
Sometimes place in Tiles worked but then it crashes with the same crash on Undo.

**Comment by CreativeMD** [comment]
Should be fixed in the newest version!
