### ISSUE TITLE
Tiles go transparent when the chunk reloads

### ISSUE THREAD

**Issue by davidmatias167** [CreativeMD/LittleTiles#692]
I built a structure but when the chunk reloads the structure goes transparent.

**Comment by CreativeMD** [comment]
Which version of the mod are you using?

**Comment by davidmatias167** [comment]
Im using the most recent version (LittleTiles_v1.5.13_mc1.12.2)

**Comment by CreativeMD** [comment]
Can you post me your mod list? I think the easiest way to do that is to send me the log file. If you want to you can also try to just run CreativeCore and LittleTiles to test if the issue still occurs.

**Comment by davidmatias167** [comment]
![Captura de ecrã 2021-05-27 182413](https://user-images.githubusercontent.com/84733151/119870061-da72a980-bf18-11eb-9714-a746e8beb7eb.png)

**Comment by davidmatias167** [comment]
[latest.log](https://github.com/CreativeMD/LittleTiles/files/6555749/latest.log)

**Comment by CreativeMD** [comment]
Update the ALET Mod that should fix your issue!
