### ISSUE TITLE
Game crashes when I click "I" which is the key bind to "configure tool"

### ISSUE THREAD

**Issue by davidmatias167** [CreativeMD/LittleTiles#693]
Game crashes when I click "I" which is the key bind to "configure tool".

**Comment by CreativeMD** [comment]
I need the crash-report to help you.

**Comment by davidmatias167** [comment]
[crash-2021-05-24_17.59.10-client.txt](https://github.com/CreativeMD/LittleTiles/files/6555757/crash-2021-05-24_17.59.10-client.txt)

**Comment by CreativeMD** [comment]
Update ALET.
