### ISSUE TITLE
Pillar Problem with Size

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#694]
When i have Grid 16 and Pillar Size 4 i cant place the Pillar direct to the wood on the left

https://gyazo.com/edf89eb4f0d5b6014c529e77b8ffc34d

But when i use Grid 4 and Pillar Size 1 (its the same size as Grid16 and Pillar Size 4) then it works:

https://gyazo.com/2fb018c7815ab6fc2828915ed77cbf96

But with Grid 4, unfortunately, you can't align the Pillar that well.

Structure for test: https://www.comgames.de/laube.txt

Maybe a option would be great to add height and width Sizes differently for pillars.

**Comment by CreativeMD** [comment]
I'm confused can't you just use mark mode for that?
