### ISSUE TITLE
Inner_Corner and Outer_Corner merging into tall inner_corner tile

### ISSUE THREAD

**Issue by D3construct** [CreativeMD/LittleTiles#696]
Placing outer_corner tiles above existing inner_corner tiles sometimes merges them together. In the preview image the white strip is half affected by it and half works normal. Placing a outer_corner tile into the empty white spots will create the bad tall tile seen to the right and the very left of the stripe there. The same happens in every single orange gap in this example.
That means that currently working on bigger scales with these corners is not possible.
![21 05 26_16;31;42](https://user-images.githubusercontent.com/31104587/119680556-93fe4b80-be41-11eb-8af3-94b50bab3321.png)

**Comment by CreativeMD** [comment]
Fixed in the newest version.
