### ISSUE TITLE
Crash with doors

### ISSUE THREAD

**Issue by kukk22** [CreativeMD/LittleTiles#697]
So I'm playing a modpack called MC Eternal(1.12.2) and I'm trying to make Little Tiles doors but when I try to activate any kind of door by right clicking it my game crashes,I tried switching to the latest version of Little Tiles(+CreativeCore) but that didn't solve anything so I'm gonna post a crash log here :)
[Crashlog.txt](https://github.com/CreativeMD/LittleTiles/files/6554902/Crashlog.txt)

**Comment by kukk22** [comment]
I tried changing some video settings in game just in case it gave different results but it didn't help,posting second crash log just in case, hope it helps
[Crashlog2.txt](https://github.com/CreativeMD/LittleTiles/files/6555003/Crashlog2.txt)

**Comment by CreativeMD** [comment]
It's caused by another mod, but I don't know which one. Probably a mod which changes some stuff regarding worlds. I guess there is no other way than to test which mod is causing it.

**Comment by kukk22** [comment]
Oof,I thought it might be a compatibility issue between mods,I guess my suspicion was correct, but this pack has so many ah well thank you anyway I will try finding out which one it is :D

**Comment by CreativeMD** [comment]
You know the trick? Remove half of the mods and check if it still works? It's a very annoying process I know.

**Comment by kukk22** [comment]
That's what I was thinking 😅

**Comment by kukk22** [comment]
Alright after like 3 hours of testing I have found out that Valkyrien Skies mod was causing the crashes.

**Comment by CreativeMD** [comment]
Oh damn ... I'm soo sorry, I have looked through the mod file and missed that one. I could have told you this earlier. Damn ... I should have looked more closely. There is a also a very outdated mod compatibility list: https://github.com/CreativeMD/LittleTiles/wiki/Mod-Compatibility

**Comment by kukk22** [comment]
It's alright I had nothing else to do anyway,I have looked at that compatibility list btw :D
