### ISSUE TITLE
Tiles not working

### ISSUE THREAD

**Issue by AccurateFranky** [CreativeMD/LittleTiles#698]
The tiles are invisible once i use the chisel. I don't know if I am doing anything wrong but once the tiles are placed, the hitbox exists but nothing can be seen.

**Comment by AccurateFranky** [comment]
I have done further testing and if I select slime block with the chisel, that chisel becomes unusable. Might want to fix that. Grabbing a new chisel solves the problem. But if I select a slime block I can't use that chisel anymore even on other blocks.

**Comment by AccurateFranky** [comment]
I have done further testing and if I select slime block with the chisel, that chisel becomes unusable. Might want to fix that. Grabbing a new chisel solves the problem. But if I select a slime block I can't use that chisel anymore even on other blocks.

**Comment by CreativeMD** [comment]
There are some mods which don't work with LittleTiles. Just to list a few RTM, Phosphor, Valkyrien Skies. Would help if you could provide your mod list.

**Comment by AccurateFranky** [comment]
Chisels & Bits and Worldedit.

**Comment by CreativeMD** [comment]
Can you send me your mod list?

**Comment by Stefanucci79** [comment]
When i install the little tiles mod i don't have the little recipe
even if i search it or try to give it to me with a command do not work it look's like the little recipe is not included in the mod

**Comment by CreativeMD** [comment]
@Stefanucci79 it's now called little blueprint.

**Comment by CreativeMD** [comment]
@AccurateFranky still there?

**Comment by AccurateFranky** [comment]
yes

**Comment by AccurateFranky** [comment]
My only mods are littletiles, chisels & bits, and worldedit.

**Comment by CreativeMD** [comment]
I need version numbers, so maybe send me one of your log files.

**Comment by Janhixy** [comment]
Did you solve it?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists please provide a log file.
