### ISSUE TITLE
Tiles turn invisible with Valkyrien Skies

### ISSUE THREAD

**Issue by EquityX** [CreativeMD/LittleTiles#699]
If you build a ship with the Valkyrien Skies mod with LT, the tiles become invisible when the ship is assembled & reappear when disassembled. Besides that they work perfectly together.

**Comment by CreativeMD** [comment]
Valkyrien Skies is incompatible with LittleTiles and there will be plenty of problems with doors. I'm sorry but they will not be fixed.
