### ISSUE TITLE
Putting an item into the Hammer GUI does not update the preview

### ISSUE THREAD

**Issue by githubuser28394** [CreativeMD/LittleTiles#7]
![](http://i.imgur.com/YH0nByw.png)
the preview gets updated as soon as you press any button
![](http://i.imgur.com/SNOJGFv.png)

**Comment by CreativeMD** [comment]
Thanks for reporting,
but i won't fix it for 1.7.10, but for 1.9 only (once it is released).

**Comment by CreativeMD** [comment]
Will be fixed in 1.10.2
