### ISSUE TITLE
Renderproblems

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#701]
`{tiles:[{boxes:[[I;3,13,4,16,15,5],[I;2,13,4,3,16,5],[I;3,15,4,5,16,5],[I;2,13,5,16,16,8],[I;2,27,4,16,30,5],[I;2,16,4,5,27,5],[I;2,16,5,16,30,8],[I;27,15,4,30,16,5],[I;16,13,4,30,15,5],[I;16,13,5,30,16,8],[I;16,27,4,30,30,8],[I;27,16,4,30,27,5],[I;16,16,5,30,27,8]],tile:{color:-10979152,block:"littletiles:ltcoloredblock"}},{boxes:[[I;3,13,8,16,16,10],[I;4,14,10,16,16,12],[I;5,15,12,16,16,14],[I;4,15,12,5,16,14,-2145279982,720907,720897,720897],[I;3,14,10,4,16,12,-2145279982,786444,786433,786433],[I;2,13,8,3,16,10,-2145279982,851981,851969,851969],[I;3,12,8,16,13,10,-2143287735,851981,851981,65537],[I;4,13,10,16,14,12,-2143287735,786444,786444,65537],[I;5,14,12,16,15,14,-2143287735,720907,720907,65537],[I;6,15,14,16,16,16,-2143287735,655370,655370,65537],[I;2,12,8,3,13,10,-1876656128,65537,65536],[I;3,13,10,4,14,12,-1876656128,65537,65536],[I;4,14,12,5,15,14,-1876656128,65537,65536],[I;5,15,14,6,16,16,-1876656128,65537,65536],[I;3,16,8,16,29,10],[I;4,16,10,16,28,12],[I;5,16,12,16,27,14],[I;6,16,14,16,26,16],[I;3,29,8,16,30,10,-2147417511,851981,-65523,917503],[I;4,28,10,16,29,12,-2147417511,786444,-65524,851967],[I;5,27,12,16,28,14,-2147417511,720907,-65525,786431],[I;6,26,14,16,27,16,-2147417511,655370,-65526,720895],[I;5,16,14,6,26,16,-2145353728,65537],[I;4,16,12,5,27,14,-2140633984,-1,131071,131071],[I;3,16,10,4,28,12,-2140633984,-65538,131070,131070],[I;2,16,8,3,29,10,-2140633984,-131075,131069,131069],[I;5,26,14,6,27,16,-2147409904,-1,-65536],[I;4,27,12,5,28,14,-2147409904,-1,-65536],[I;3,28,10,4,29,12,-2147409904,-1,-65536],[I;2,29,8,3,30,10,-2147409904,-1,-65536],[I;16,13,8,29,16,10],[I;16,14,10,28,16,12],[I;16,15,12,27,16,14],[I;29,13,8,30,16,10,-2147409382,917503,917503,851981],[I;28,14,10,29,16,12,-2147409382,851967,851967,786444],[I;27,15,12,28,16,14,-2147409382,786431,786431,720907],[I;16,12,8,29,13,10,-2140892160,131059,-786445,-851967],[I;16,13,10,28,14,12,-2140892160,131060,-720908,-786431],[I;16,14,12,27,15,14,-2140892160,131061,-655371,-720895],[I;16,15,14,26,16,16,-2140892160,131062,-589834,-655359],[I;29,12,8,30,13,10,-2004875232,-65538,-131072],[I;28,13,10,29,14,12,-2004875232,-65538,-131072],[I;27,14,12,28,15,14,-2004875232,-65538,-131072],[I;26,15,14,27,16,16,-2004875232,-65538,-131072],[I;28,16,8,29,29,10],[I;27,16,8,28,28,12],[I;16,28,8,28,29,10],[I;16,27,8,27,28,12],[I;26,16,8,27,27,14],[I;16,16,8,26,26,16],[I;16,26,8,26,27,14],[I;16,29,8,29,30,10,-2145021936,-13,-786433,-786445],[I;16,28,10,28,29,12,-2145021936,-12,-720897,-720908],[I;16,27,12,27,28,14,-2145021936,-11,-655361,-655371],[I;16,26,14,26,27,16,-2145021936,-10,-589825,-589834],[I;29,16,8,30,29,10,-2142763384,-3,-3,-131075],[I;28,16,10,29,28,12,-2142763384,-2,-2,-65538],[I;27,16,12,28,27,14,-2142763384,-1,-1,-1],[I;26,16,14,27,26,16,-2147483128,-1],[I;29,29,8,30,30,10,-2147350496,-65538,-131072],[I;28,28,10,29,29,12,-2147350496,-65538,-131072],[I;27,27,12,28,28,14,-2147350496,-65538,-131072],[I;26,26,14,27,27,16,-2147350496,-65538,-131072]],tile:{color:-14667680,block:"littletiles:ltcoloredblock"}},{boxes:[[I;6,15,4,16,16,5,-2146958647,655370,655361,655361],[I;5,15,4,6,16,5,-2146418432,65537,65536],[I;6,26,4,16,27,5,-2147474869,720895,655370,720895],[I;5,16,4,6,26,5,-2147217408,65537],[I;5,26,4,6,27,5,-2079309820,65537,65536],[I;6,25,4,7,26,5],[I;6,16,4,7,17,5],[I;7,25,4,9,26,5,-2147482496,65537],[I;6,23,4,7,25,5,-2147483072,-1],[I;6,17,4,7,19,5,-2147483639,-1],[I;7,16,4,9,17,5,-2147483630,-1],[I;16,15,4,26,16,5,-2144563072,131062,-589834,131062],[I;26,15,4,27,16,5,-2079325948,65537,65536],[I;26,16,4,27,26,5,-2147483583,-1],[I;16,26,4,26,27,5,-2145079294,-10,-10,-589834],[I;26,26,4,27,27,5,-2147467004,65537,65536],[I;25,16,4,26,17,5],[I;25,25,4,26,26,5],[I;23,16,4,25,17,5,-2147409920,-1],[I;25,17,4,26,19,5,-2147446784,65537],[I;25,23,4,26,25,5,-2145124352,65537],[I;23,25,4,25,26,5,-2142765056,65537]],tile:{color:-15722440,block:"littletiles:ltcoloredblock"}},{boxes:[[I;6,12,5,16,13,8],[I;10,12,4,16,13,5],[I;2,12,4,6,13,8],[I;8,12,4,9,13,5],[I;16,12,4,30,13,8]],tile:{color:-12035968,block:"littletiles:ltcoloredblock"}},{bBox:[I;9,12,4,10,13,5],tile:{color:-15194024,block:"littletiles:ltcoloredblock"}},{bBox:[I;6,12,4,8,13,5],tile:{color:-7325680,block:"littletiles:ltcoloredblock"}},{boxes:[[I;3,0,4,16,1,16],[I;3,11,4,16,12,16],[I;2,0,4,3,12,16],[I;3,1,15,16,11,16],[I;16,0,4,30,1,16],[I;16,11,4,30,12,16],[I;29,1,4,30,11,16],[I;16,1,15,29,11,16]],tile:{color:-7313368,block:"littletiles:ltcoloredblock"}},{boxes:[[I;15,1,4,16,11,15],[I;16,1,4,17,11,15]],tile:{color:-10991568,block:"littletiles:ltcoloredblock"}},{boxes:[[I;7,25,4,9,26,5,-2147409920,-1],[I;6,23,4,7,25,5,-2147446784,65537],[I;6,17,4,7,19,5,-2145124352,65537],[I;7,16,4,9,17,5,-2142765056,65537],[I;9,25,4,16,26,5],[I;6,19,4,7,23,5],[I;9,16,4,16,17,5],[I;7,24,4,8,25,5],[I;7,17,4,8,18,5],[I;7,22,4,8,24,5,-2147483072,-1],[I;8,24,4,10,25,5,-2147482496,65537],[I;7,18,4,8,20,5,-2147483639,-1],[I;8,17,4,10,18,5,-2147483630,-1],[I;25,23,4,26,25,5,-2147483639,-1],[I;23,25,4,25,26,5,-2147483630,-1],[I;23,16,4,25,17,5,-2147482496,65537],[I;25,17,4,26,19,5,-2147483072,-1],[I;25,19,4,26,23,5],[I;16,25,4,23,26,5],[I;16,16,4,23,17,5],[I;24,17,4,25,18,5],[I;24,24,4,25,25,5],[I;22,17,4,24,18,5,-2147409920,-1],[I;24,18,4,25,20,5,-2147446784,65537],[I;24,22,4,25,24,5,-2145124352,65537],[I;22,24,4,24,25,5,-2142765056,65537]],tile:{color:-15720384,block:"littletiles:ltcoloredblock"}},{boxes:[[I;7,18,4,8,20,5,-2145124352,65537],[I;8,17,4,10,18,5,-2142765056,65537],[I;8,24,4,10,25,5,-2147409920,-1],[I;7,22,4,8,24,5,-2147446784,65537],[I;7,20,4,8,22,5],[I;10,24,4,16,25,5],[I;10,17,4,16,18,5],[I;8,18,4,9,24,5],[I;9,23,4,16,24,5],[I;9,18,4,16,19,5],[I;9,19,4,10,20,5],[I;9,22,4,10,23,5],[I;10,22,4,12,23,5,-2147482496,65537],[I;9,21,4,10,22,5,-2142763328,-1,-1,-1],[I;9,20,4,10,21,5,-2147409893,-65535,-65535,65537],[I;10,19,4,12,20,5,-2147483630,-1],[I;22,17,4,24,18,5,-2147482496,65537],[I;24,18,4,25,20,5,-2147483072,-1],[I;24,22,4,25,24,5,-2147483639,-1],[I;22,24,4,24,25,5,-2147483630,-1],[I;16,24,4,22,25,5],[I;16,23,4,24,24,5],[I;24,20,4,25,22,5],[I;23,18,4,24,23,5],[I;16,17,4,22,18,5],[I;16,18,4,23,19,5],[I;22,22,4,23,23,5],[I;22,19,4,23,20,5],[I;20,19,4,22,20,5,-2147409920,-1],[I;22,20,4,23,21,5,-2147373038,65537,65537,65537],[I;22,21,4,23,22,5,-2140404608,-1,131071,131071],[I;20,22,4,22,23,5,-2142765056,65537]],tile:{color:-15194040,block:"littletiles:ltcoloredblock"}},{boxes:[[I;10,20,4,16,22,5],[I;10,22,4,12,23,5,-2147409920,-1],[I;9,21,4,10,22,5,-2142727040,-1,65537,-1],[I;9,20,4,10,21,5,-2143985386,131071,131071,131071,65537,-65535],[I;10,19,4,12,20,5,-2142765056,65537],[I;12,19,4,16,20,5],[I;12,22,4,16,23,5],[I;16,20,4,22,22,5],[I;22,21,4,23,22,5,-2142763895,-1,-1,-1],[I;20,22,4,22,23,5,-2147483630,-1],[I;20,19,4,22,20,5,-2147482496,65537],[I;22,20,4,23,21,5,-2146344106,131071,131071,-1,131071,131071],[I;16,19,4,20,20,5],[I;16,22,4,20,23,5]],tile:{color:-14667688,block:"littletiles:ltcoloredblock"}}],min:[I;2,0,3],size:[I;28,30,13],children:[{tiles:[{boxes:[[I;3,1,5,15,11,12],[I;17,1,5,29,11,12],[I;20,1,12,24,5,13],[I;24,2,12,28,10,13]],tile:{color:-10991568,invisible:1b,block:"littletiles:ltstorageblocktile"}}],count:4,dynamic:1b,structure:{stackSizeLimit:64,invisibleStorage:1b,lastSlot:0,filled:0,numberOfSlots:27,dynamic:1b,id:"storage",accessed:0,inventory:{size:27},inventorySize:1728}},{tiles:[{bBox:[I;12,6,3,14,7,4],tile:{color:-10991568,block:"littletiles:ltcoloredblock"}},{boxes:[[I;3,1,4,6,2,5],[I;14,10,4,15,11,5],[I;7,10,4,9,11,5],[I;9,7,4,10,8,5],[I;12,3,4,15,4,5],[I;14,4,4,15,5,5],[I;14,1,4,15,2,5],[I;3,3,4,4,4,5],[I;6,6,4,11,7,5],[I;3,5,4,7,6,5],[I;8,5,4,9,6,5],[I;3,10,4,4,11,5],[I;5,9,4,10,10,5],[I;12,9,4,14,10,5],[I;3,8,4,6,9,5],[I;8,8,4,15,9,5]],tile:{color:-7313368,block:"littletiles:ltcoloredblock"}},{boxes:[[I;11,3,4,12,4,5],[I;6,3,4,7,5,5],[I;9,1,4,11,2,5],[I;4,4,4,6,5,5],[I;7,4,4,8,5,5],[I;9,4,4,11,5,5],[I;13,2,4,14,3,5],[I;10,2,4,12,3,5],[I;6,2,4,9,3,5]],tile:{color:-5732328,block:"littletiles:ltcoloredblock"}},{boxes:[[I;7,3,4,11,4,5],[I;11,1,4,14,2,5],[I;6,1,4,9,2,5],[I;4,3,4,6,4,5],[I;3,4,4,4,5,5],[I;8,4,4,9,5,5],[I;12,2,4,13,3,5],[I;9,2,4,10,3,5],[I;5,2,4,6,3,5]],tile:{color:-5730272,block:"littletiles:ltcoloredblock"}},{boxes:[[I;9,10,4,14,11,5],[I;4,10,4,7,11,5],[I;3,7,4,9,8,5],[I;10,7,4,11,8,5],[I;11,4,4,14,5,5],[I;14,2,4,15,3,5],[I;3,2,4,5,3,5],[I;3,6,4,6,7,5],[I;7,5,4,8,6,5],[I;9,5,4,11,6,5],[I;3,9,4,5,10,5],[I;10,9,4,12,10,5],[I;14,9,4,15,10,5],[I;6,8,4,8,9,5]],tile:{color:-7315424,block:"littletiles:ltcoloredblock"}},{boxes:[[I;12,7,4,15,8,5],[I;11,6,4,12,7,5],[I;14,5,4,15,6,5]],tile:{color:-9416680,block:"littletiles:ltcoloredblock"}},{boxes:[[I;11,5,4,12,6,5],[I;11,7,4,12,8,5],[I;12,5,4,14,7,5],[I;14,6,4,15,7,5]],tile:{color:-9414632,block:"littletiles:ltcoloredblock"}}],count:56,dynamic:1b,structure:{noClip:1b,clockwise:1b,activateParent:1b,opened:0b,axis:1,rot-type:0,duration:6,axisCenter:[I;3,0,4,4,1,5,16],interpolation:0,sounds:0b,dynamic:1b,id:"door",state:{mode:"TOGGLE",delay:0,state:0},events:[],disableRightClick:0b}},{tiles:[{bBox:[I;18,6,3,20,7,4],tile:{color:-10991568,block:"littletiles:ltcoloredblock"}},{boxes:[[I;28,3,4,29,4,5],[I;20,10,4,21,11,5],[I;25,7,4,26,8,5],[I;17,1,4,18,2,5],[I;21,5,4,22,7,5],[I;23,6,4,29,7,5],[I;22,5,4,26,6,5],[I;28,5,4,29,6,5],[I;22,8,4,25,10,5],[I;25,8,4,29,9,5],[I;28,9,4,29,10,5],[I;18,9,4,21,10,5],[I;21,9,4,22,11,5],[I;17,8,4,19,9,5],[I;17,3,4,18,5,5],[I;27,1,4,29,2,5],[I;18,4,4,20,5,5]],tile:{color:-7313368,block:"littletiles:ltcoloredblock"}},{boxes:[[I;24,3,4,28,4,5],[I;21,3,4,23,4,5],[I;21,1,4,26,2,5],[I;18,1,4,20,2,5],[I;28,4,4,29,5,5],[I;24,4,4,25,5,5],[I;21,4,4,22,5,5],[I;25,2,4,26,3,5],[I;19,2,4,20,3,5],[I;22,2,4,23,3,5]],tile:{color:-5730272,block:"littletiles:ltcoloredblock"}},{boxes:[[I;20,3,4,21,4,5],[I;23,3,4,24,4,5],[I;20,1,4,21,2,5],[I;25,4,4,28,5,5],[I;22,4,4,24,5,5],[I;26,2,4,27,3,5],[I;18,2,4,19,3,5],[I;20,2,4,22,3,5],[I;23,2,4,25,3,5]],tile:{color:-5732328,block:"littletiles:ltcoloredblock"}},{boxes:[[I;22,10,4,29,11,5],[I;17,10,4,20,11,5],[I;21,7,4,25,8,5],[I;26,7,4,29,8,5],[I;17,2,4,18,3,5],[I;27,2,4,29,3,5],[I;22,6,4,23,7,5],[I;26,5,4,28,6,5],[I;25,9,4,28,10,5],[I;19,8,4,22,9,5],[I;17,9,4,18,10,5],[I;18,3,4,20,4,5],[I;26,1,4,27,2,5],[I;20,4,4,21,5,5]],tile:{color:-7315424,block:"littletiles:ltcoloredblock"}},{boxes:[[I;19,7,4,21,8,5],[I;18,5,4,20,6,5]],tile:{color:-9416680,block:"littletiles:ltcoloredblock"}},{boxes:[[I;17,5,4,18,8,5],[I;18,6,4,19,8,5],[I;19,6,4,21,7,5],[I;20,5,4,21,6,5]],tile:{color:-9414632,block:"littletiles:ltcoloredblock"}}],count:57,dynamic:1b,structure:{noClip:1b,clockwise:0b,activateParent:1b,opened:0b,axis:1,rot-type:0,duration:6,axisCenter:[I;28,0,4,29,1,5,16],interpolation:0,sounds:0b,dynamic:1b,id:"door",state:{mode:"TOGGLE",delay:0,state:0},events:[],disableRightClick:0b}}],count:187,structure:{blocks:[I;],activate:[I;1,2],activateParent:0b,opened:0b,id:"doorActivator",state:{mode:"TOGGLE",state:0},inMotion:0b,disableRightClick:0b}}
`

If you place this structure and open the doors then graphic errors appear when closing. This seems to have something to do with VBO.

**Comment by Desoroxxx** [comment]
After some testing this only happen with the door activator.
After even more testing it do not happen if I make both door close and open by using signal.

Need to precise here that there is a slight disappearance of the door when n opening/closing the doors at the same time with signal but not near as bad as door activator

It must be a problem with the door activator

**Comment by ghost** [comment]
If you give the doors "Stay Animated" and then connect them to the Door Activator there is no problem anymore. I didn't test this with this example but I had a similar one with another door.

**Comment by CreativeMD** [comment]
Fixed in the newest pre-release.
