### ISSUE TITLE
unreasonable error crash-report

### ISSUE THREAD

**Issue by KopieSlime** [CreativeMD/LittleTiles#704]
![image](https://user-images.githubusercontent.com/85485124/121091790-00932600-c804-11eb-830c-ecd5ce4002b2.png)
for some reasons it crashes with / by zero altought there is none

**Comment by CreativeMD** [comment]
Please send me the crash-report.

**Comment by KopieSlime** [comment]
[crash-2021-06-08_20.58.29-server.txt](https://github.com/CreativeMD/LittleTiles/files/6618710/crash-2021-06-08_20.58.29-server.txt)

**Comment by CreativeMD** [comment]
Should be fixed in the newest version. Thanks for reporting this issue!
