### ISSUE TITLE
Duplication bug with Little Wrench

### ISSUE THREAD

**Issue by AbstractMagi** [CreativeMD/LittleTiles#71]
If you place a single tile of any block, and paint it any color, then right click the tile with the wrench, the tile is changed to a normal unpainted version of the block, that you can then pick up. I triple checked to make sure it wasn't pulling the extra parts from anywhere, and it only works for tiles that are considered one solid piece and are painted.

![bug2](https://user-images.githubusercontent.com/35904428/35488481-96f61ffe-043e-11e8-874f-582d6c36c4ad.gif)

I am using Forge 1.12.2 v14.23.1.2555 with LittleTiles v1.5.0-pre66

**Comment by CreativeMD** [comment]
Will be fixed in pre67. Thanks for reporting this issue!

EDIT
Thanks for posting gifs! That way it's really easy for me to understand the problem. Much appreciated!
