### ISSUE TITLE
No line tool in 1.15+?

### ISSUE THREAD

**Issue by Synical42** [CreativeMD/LittleTiles#712]
Hey love what you've done with the new options for the chisel, especillly polygon xD
the pillar tool is nice... but tbh it's not even close to a replacement for the line tool, which was litirally the most useful tool before this update
being able to 'frame out' my builds with that line tool is really key to my building process and without it i can't use the new updates which is sad cause i like the new options

Love your work and will continue to enjoy your mods, but please add the line tool for little tiles again!?!? <3 thank you!

**Comment by CreativeMD** [comment]
It's called curve now.

**Comment by Synical42** [comment]
Oh, Thank you :)
