### ISSUE TITLE
Game crash before starting.

### ISSUE THREAD

**Issue by dhruvnnd** [CreativeMD/LittleTiles#714]
I have installed the proper versions of **LittleTiles** & **CreativeCore** but the game just won't start.

**Comment by CreativeMD** [comment]
Please post the crash-report here. Also make sure to install the newest versions of each mod from curseforge (that is the problem in 99% of the cases).

**Comment by dhruvnnd** [comment]
> Please post the crash-report here. Also make sure to install the newest versions of each mod from curseforge (that is the problem in 99% of the cases).

I have installed a previous version of LittleTiles and that has solved the problem for me.
