### ISSUE TITLE
Error executing task

### ISSUE THREAD

**Issue by juraj-hrivnak** [CreativeMD/LittleTiles#715]
### The issue
This error happened to me when I right-clicked on a door that way a little bit further.
And it was also one block higher from me.

### Info
- **LittleTiles_v1.5.15_mc1.12.2**
- **Crash report:** https://paste.dimdev.org/rebawexiwe.mccrash
- **Latest log:** https://paste.ee/p/X1xOb

### Screenshot
![2021-07-12_18 32 53](https://user-images.githubusercontent.com/71150936/125323914-a116c180-e33f-11eb-9873-0b142cef4e70.png)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
