### ISSUE TITLE
Crashing when interacting with doors

### ISSUE THREAD

**Issue by jpower123** [CreativeMD/LittleTiles#716]
May be a compatibility issue, however when I made a custom door using the little tiles mod, right clicking on it crashes the game for the client. It also crashes all players that are in render distance of the door. 
Here is the crash report from the client: https://pastebin.com/Zb0MMGaW
and here is a report on the server console when a player crashes: https://pastebin.com/S69kzDvU
This happened on the latest version as of right now.

**Comment by CreativeMD** [comment]
Unfortunately LittleTiles is not compatible with Valkyrien Skies.
