### ISSUE TITLE
Immersive Vehicles compatibility issues.

### ISSUE THREAD

**Issue by 012phuong** [CreativeMD/LittleTiles#719]
I just talk with Immersive Vehicles's Developer Don Bruce about the issues between LittleTiles and his mod, based on his knowledge, it's looks like you set the hardness level of LittleTiles's structures a little bit too low (0.1 he said), this made the structure extremely fragile, chiseled obsidian is still able to withstand tnt like normal but projectiles from his mod will cut through it like butter because his block-breaking mechanism is based on the hardness level of the block it hit, if it below a certain point, the projectile will simply destroy it, i wonder if it possible for you to set the level a little bit higher (atleast at the same level as stone block)? Currently his projectiles are able to destroy glass pane (which it's hardness level is 0.3).

**Comment by CreativeMD** [comment]
I set it to 1 in the next version. I hope it works now! Thanks for reporting this issue!
