### ISSUE TITLE
Little Container disappearing when open

### ISSUE THREAD

**Issue by AbstractMagi** [CreativeMD/LittleTiles#72]
When the Little Container is open, if you take it out of the slot it is in, and then place it back in that slot, when you close the Little Container, the Little Container disappears.

![bug3](https://user-images.githubusercontent.com/35904428/35490561-532bc37a-0455-11e8-87f1-b65de08288ee.gif)

I am using Forge 1.12.2 v14.23.1.2555 with LittleTiles v1.5.0-pre66

**Comment by CreativeMD** [comment]
Will be fixed in pre67. Thanks for reporting this issue!
