### ISSUE TITLE
modpack/fol'der (The system cannot find the file specified) [bug, but does not impeade with gameplay really]

### ISSUE THREAD

**Issue by iceyrazor** [CreativeMD/LittleTiles#720]
[latest.log](https://github.com/CreativeMD/LittleTiles/files/6873219/latest.log)

removing the ' from the folder name and destination fixed this. is a minor bug but other people may not be able to figure this out.

i think all you need todo is whatever the equivilant of dirnamestr.replace("'","\'") is to the director name your pulling librarys from. and what ever the escape character is.

edit: sorry didnt realize im using a older version. if this is patched simply close. i didnt find any relavent post so sorry if this is also a duplicate

**Comment by CreativeMD** [comment]
The problem most likely still exists, but I can't fix it. It's a forge thing. Sorry, you will have to use a different name.

**Comment by iceyrazor** [comment]
> The problem most likely still exists, but I can't fix it. It's a forge thing. Sorry, you will have to use a different name.

like a said. not a problem. figured it out pretty quickly. just thought id still report it.
