### ISSUE TITLE
strange crash on server only

### ISSUE THREAD

**Issue by BlizzardLight** [CreativeMD/LittleTiles#724]
well, i started my server before and it worked correctly, tonight i wanted to upgrade LT to latest. i download latest release for 1.12.2 from curseforge and install it. LittleTiles DOESN'T even create a config (i removed old configs of LT) - instead it just crashed... 
[crash-2021-08-04_00.30.21-server.txt](https://github.com/CreativeMD/LittleTiles/files/6927711/crash-2021-08-04_00.30.21-server.txt)
[latest.log](https://github.com/CreativeMD/LittleTiles/files/6927712/latest.log)

**Comment by BlizzardLight** [comment]
@CreativeMD  seems like to me, that LittleTiles try to load RenderingThread class on server-side

**Comment by briansgaming01** [comment]
its happening to me too can you explain how to fix the problem

**Comment by BlizzardLight** [comment]
> its happening to me too can you explain how to fix the problem

excuse me but if you asked me about this, instead, you should ask the mod author =) forgive my misunderstanding
'cause i just stop my server

**Comment by CreativeMD** [comment]
Fixed in the newest version. Please don't forget to update CreativeCore as well. Thanks for reporting this issue!

**Comment by BlizzardLight** [comment]
> Thanks for reporting this issue!

welcome ;)
