### ISSUE TITLE
Sometimes problems with UNDO

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#726]
https://gyazo.com/74014ffad69be9ee6c3c8c36c09453f2

place times such a wall on the floor
that does not work properly that is a problem but not a big
but then no undo works anymore
and so you have that sometimes when you do normal things like setting a blueprint 6-7 times and then undoing it
sometimes it works sometimes it only does 3 undo and no further

**Comment by CreativeMD** [comment]
It should be fixed in the newest version. If not let me know here.
