### ISSUE TITLE
Door disappearing

### ISSUE THREAD

**Issue by Masher414** [CreativeMD/LittleTiles#728]
I have a custom door made with little tiles on a platform that moves up and down (also made with little tiles) and sometimes rather the platform is up or down, it disappears (sometimes randomly and sometimes after I open and close it a few times), when I relog its back. Is there any way to keep this from happening? (I am also on the latest version of little tiles for 1.12.2, v1.5.19)

**Comment by CreativeMD** [comment]
Duplicate of https://github.com/CreativeMD/LittleTiles/issues/605
