### ISSUE TITLE
Parts of moving structures remains floating after removing by WorldEdit

### ISSUE THREAD

**Issue by crystheshard** [CreativeMD/LittleTiles#729]
When world edit works with structures in their basic position (not pressed levers, closed doors), everything's fine.

But when it comes to triggered structures, when removing by //set, the moveable part remains floating in air, says "Structure is not loaded" or "Missing Parent" and cannot be removed in any way.
And maybe i just can avoid operations like this in future, but i just don't know what to do with this parts that already floating in my world and i don't know ho to get rid of them:\

LittleTiles 1.5.19, Minecraft 1.12.2
[Screenshots](https://imgur.com/a/f32etAE)

**Comment by CreativeMD** [comment]
That's because some doors are not blocks, but remain in animation state (as an entity). This happens either if the animation is still going or if stay animated is set to true. Obviously WorldEdit does not remove entites. You can remove the doors with the wrench in hand.
