### ISSUE TITLE
Invalid items are deleted when Little Container is closed.

### ISSUE THREAD

**Issue by AbstractMagi** [CreativeMD/LittleTiles#73]
If you have an invalid item in the deposit slot of the Little Container when it is closed, the item disappears.

![bug4](https://user-images.githubusercontent.com/35904428/35490623-d642a0b2-0455-11e8-8021-0a51f1e8d888.gif)

I am using Forge 1.12.2 v14.23.1.2555 with LittleTiles v1.5.0-pre66

**Comment by CreativeMD** [comment]
Will be fixed in pre67. Thanks for reporting this issue!
