### ISSUE TITLE
Animated Objects randomly disappearing and duplicating

### ISSUE THREAD

**Issue by KokoteAdvice** [CreativeMD/LittleTiles#730]
Moving doors or any objects which has functional are getting duplicated and mostly cant used them because it says "Structure is not loaded" 
If an object successfully executed and then the world is reloaded, sometimes the entire object disappearing

-Played With:
LittleTiles_v1.5.19
CreativeCore_v1.10.62
Forge 14.23.5.2855
OptiFine_1.12.2_HD_U_G5

-video:
https://www.youtube.com/watch?v=d5DUlQv5dxg

-logs:
[logs.zip](https://github.com/CreativeMD/LittleTiles/files/6988534/logs.zip)

-have some crashes too:
[crashes.zip](https://github.com/CreativeMD/LittleTiles/files/6988578/crashes.zip)

**Comment by CreativeMD** [comment]
Duplicate of https://github.com/CreativeMD/LittleTiles/issues/605
