### ISSUE TITLE
Valkyrien skyes conflict

### ISSUE THREAD

**Issue by BluescreenDotEXe** [CreativeMD/LittleTiles#732]
The game work fine untile someone try to make a door (in or outside the ship). when opened the game crash

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  weaponlib (mw_2.0-0.4.6.2_mc1.12.2 (3).jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MixinLoaderForge ([[valkyrien-skies-1.1.7-all]].jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.2.1.jar)
  LittlePatchingLoader (LittleTiles_v1.5.19_mc1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  CreativePatchingLoader (CreativeCore_v1.10.62_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 8/17/21 4:29 AM
Description: Unexpected error

java.lang.IllegalStateException: We can't be accessing this manager since WorldEvent.load() was never called!
	at net.minecraft.world.World.getManager(World.java:5017)
	at net.minecraft.world.World.rayTraceBlocksIgnoreShip(World.java:4929)
	at net.minecraft.world.World.handler$zzj000$preRayTraceBlocks(World.java:4913)
	at net.minecraft.world.World.func_147447_a(World.java)
	at net.minecraft.world.World.func_72933_a(World.java:924)
	at com.creativemd.littletiles.client.world.LittleAnimationHandlerClient.getTarget(LittleAnimationHandlerClient.java:655)
	at com.creativemd.littletiles.client.world.LittleAnimationHandlerClient.getRayTraceResult(LittleAnimationHandlerClient.java:541)
	at com.creativemd.littletiles.client.world.LittleAnimationHandlerClient.holdClick(LittleAnimationHandlerClient.java:289)
	at com.creativemd.littletiles.common.world.WorldAnimationHandler.holdClick(WorldAnimationHandler.java:171)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_410_WorldAnimationHandler_holdClick_HoldLeftClick.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at com.creativemd.littletiles.client.event.InputEventHandler.onHoldClick(InputEventHandler.java:26)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2268)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.World.getManager(World.java:5017)
	at net.minecraft.world.World.rayTraceBlocksIgnoreShip(World.java:4929)
	at net.minecraft.world.World.handler$zzj000$preRayTraceBlocks(World.java:4913)
	at net.minecraft.world.World.func_147447_a(World.java)
	at net.minecraft.world.World.func_72933_a(World.java:924)
	at com.creativemd.littletiles.client.world.LittleAnimationHandlerClient.getTarget(LittleAnimationHandlerClient.java:655)
	at com.creativemd.littletiles.client.world.LittleAnimationHandlerClient.getRayTraceResult(LittleAnimationHandlerClient.java:541)
	at com.creativemd.littletiles.client.world.LittleAnimationHandlerClient.holdClick(LittleAnimationHandlerClient.java:289)
	at com.creativemd.littletiles.common.world.WorldAnimationHandler.holdClick(WorldAnimationHandler.java:171)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_410_WorldAnimationHandler_holdClick_HoldLeftClick.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at com.creativemd.littletiles.client.event.InputEventHandler.onHoldClick(InputEventHandler.java:26)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2268)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Bluescreen_exe_'/111, l='MpServer', x=-7.95, y=72.00, z=-371.48]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-55,77,-12), Chunk: (at 9,4,4 in -4,-1; contains blocks -64,0,-16 to -49,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 28527012 game time, 10749 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 122 total; [EntityPlayerSP['Bluescreen_exe_'/111, l='MpServer', x=-7.95, y=72.00, z=-371.48], EntityLatchedRenderer['unknown'/294, l='MpServer', x=8.50, y=65.00, z=8.50], EntityGib['unknown'/333, l='MpServer', x=-37.24, y=63.68, z=-403.49], EntityGib['unknown'/334, l='MpServer', x=-37.25, y=63.45, z=-403.84], EntityGib['unknown'/335, l='MpServer', x=-37.23, y=63.45, z=-403.14], EntityGib['unknown'/338, l='MpServer', x=-32.01, y=69.50, z=-400.50], EntityGib['unknown'/339, l='MpServer', x=-32.01, y=69.28, z=-400.85], EntityGib['unknown'/340, l='MpServer', x=-32.01, y=69.28, z=-400.15], EntityGib['unknown'/347, l='MpServer', x=-41.49, y=69.50, z=-399.80], EntityGib['unknown'/348, l='MpServer', x=-41.14, y=69.28, z=-399.78], EntityGib['unknown'/349, l='MpServer', x=-41.84, y=69.28, z=-399.82], EntityGib['unknown'/354, l='MpServer', x=-25.46, y=72.50, z=-402.82], EntityGib['unknown'/355, l='MpServer', x=-25.11, y=72.28, z=-402.79], EntityGib['unknown'/356, l='MpServer', x=-25.81, y=72.28, z=-402.86], EntityGib['unknown'/360, l='MpServer', x=-30.26, y=68.50, z=-402.18], EntityGib['unknown'/361, l='MpServer', x=-29.91, y=68.28, z=-402.20], EntityGib['unknown'/362, l='MpServer', x=-30.61, y=68.28, z=-402.15], EntityGib['unknown'/364, l='MpServer', x=-18.58, y=66.78, z=-405.87], EntityGib['unknown'/365, l='MpServer', x=-18.46, y=66.56, z=-405.54], EntityGib['unknown'/366, l='MpServer', x=-18.69, y=66.56, z=-406.20], EntityGib['unknown'/368, l='MpServer', x=-31.37, y=69.50, z=-400.51], EntityScent['entity.EntityScent.name'/112, l='MpServer', x=-6.50, y=72.50, z=-376.50], EntityGib['unknown'/369, l='MpServer', x=-31.36, y=69.28, z=-400.16], EntityGib['unknown'/370, l='MpServer', x=-31.38, y=69.28, z=-400.86], EntityGib['unknown'/373, l='MpServer', x=-31.06, y=72.50, z=-400.15], EntityGib['unknown'/374, l='MpServer', x=-31.27, y=72.28, z=-399.87], EntityGib['unknown'/375, l='MpServer', x=-30.84, y=72.28, z=-400.42], EntityGib['unknown'/377, l='MpServer', x=-21.67, y=72.50, z=-399.51], EntityGib['unknown'/378, l='MpServer', x=-21.48, y=72.28, z=-399.22], EntityGib['unknown'/379, l='MpServer', x=-21.87, y=72.28, z=-399.80], EntityGib['unknown'/381, l='MpServer', x=-28.66, y=73.50, z=-361.83], EntityGib['unknown'/382, l='MpServer', x=-28.68, y=73.28, z=-362.17], EntityGib['unknown'/383, l='MpServer', x=-28.63, y=73.28, z=-361.48], EntityGib['unknown'/391, l='MpServer', x=-11.70, y=69.50, z=-401.70], EntityPig['Pig'/136, l='MpServer', x=-70.22, y=71.00, z=-363.64], EntityGib['unknown'/392, l='MpServer', x=-11.40, y=69.28, z=-401.88], EntityChicken['Chicken'/137, l='MpServer', x=-53.81, y=71.00, z=-376.43], EntityGib['unknown'/393, l='MpServer', x=-12.00, y=69.28, z=-401.52], EntityPig['Pig'/138, l='MpServer', x=-34.45, y=71.00, z=-393.69], EntitySheep['Sheep'/139, l='MpServer', x=-49.77, y=71.00, z=-395.40], EntityGib['unknown'/395, l='MpServer', x=-10.30, y=69.50, z=-401.70], EntityCreeper['Creeper'/140, l='MpServer', x=-45.47, y=68.00, z=-398.79], EntityGib['unknown'/396, l='MpServer', x=-10.54, y=69.28, z=-401.95], EntityPig['Pig'/141, l='MpServer', x=-41.78, y=71.00, z=-385.27], EntityGib['unknown'/397, l='MpServer', x=-10.06, y=69.28, z=-401.45], EntityZombie['Zombie'/142, l='MpServer', x=-41.49, y=68.00, z=-399.80], EntityCow['Cow'/147, l='MpServer', x=-78.03, y=55.32, z=-384.45], EntitySheep['Sheep'/148, l='MpServer', x=-76.42, y=55.32, z=-385.55], EntityCow['Cow'/149, l='MpServer', x=-64.52, y=66.00, z=-390.55], EntityEyes['Eyes'/152, l='MpServer', x=-85.50, y=57.00, z=-377.50], EntityGib['unknown'/409, l='MpServer', x=16.50, y=66.50, z=-408.50], EntityChicken['Chicken'/154, l='MpServer', x=-42.89, y=55.68, z=-408.42], EntityGib['unknown'/410, l='MpServer', x=16.75, y=66.28, z=-408.74], EntityZombie['Zombie'/155, l='MpServer', x=-37.20, y=62.12, z=-403.49], EntityGib['unknown'/411, l='MpServer', x=16.25, y=66.28, z=-408.26], EntitySheep['Sheep'/156, l='MpServer', x=-40.70, y=67.00, z=-407.45], EntitySkeleton['Skeleton'/157, l='MpServer', x=-31.95, y=68.00, z=-400.50], EntitySheep['Sheep'/158, l='MpServer', x=-34.88, y=71.00, z=-402.24], EntityPig['Pig'/160, l='MpServer', x=-81.81, y=69.00, z=-362.64], EntitySheep['Sheep'/161, l='MpServer', x=-79.73, y=57.00, z=-382.49], EntityPig['Pig'/162, l='MpServer', x=-70.96, y=68.00, z=-378.49], EntityGib['unknown'/418, l='MpServer', x=69.61, y=67.50, z=-387.50], EntityCow['Cow'/163, l='MpServer', x=-59.47, y=65.00, z=-395.79], EntityGib['unknown'/419, l='MpServer', x=69.61, y=67.28, z=-387.15], EntityZombieVillager['Zombie Villager'/164, l='MpServer', x=-52.77, y=68.00, z=-385.51], EntityGib['unknown'/420, l='MpServer', x=69.61, y=67.28, z=-387.85], EntityChicken['Chicken'/165, l='MpServer', x=-52.69, y=81.00, z=-296.44], EntitySheep['Sheep'/166, l='MpServer', x=-39.61, y=78.00, z=-316.27], EntityPig['Pig'/167, l='MpServer', x=-34.89, y=80.00, z=-303.63], EntityGib['unknown'/423, l='MpServer', x=70.50, y=67.50, z=-365.50], EntityGib['unknown'/424, l='MpServer', x=70.26, y=67.28, z=-365.75], EntityGib['unknown'/425, l='MpServer', x=70.74, y=67.28, z=-365.25], EntityPig['Pig'/171, l='MpServer', x=-70.04, y=80.00, z=-305.48], EntityGib['unknown'/427, l='MpServer', x=70.50, y=67.50, z=-360.50], EntityChicken['Chicken'/172, l='MpServer', x=-43.07, y=73.00, z=-332.26], EntityGib['unknown'/428, l='MpServer', x=70.81, y=67.28, z=-360.34], EntityZombie['Zombie'/173, l='MpServer', x=-28.66, y=72.00, z=-361.83], EntityGib['unknown'/429, l='MpServer', x=70.19, y=67.28, z=-360.66], EntityGib['unknown'/431, l='MpServer', x=70.50, y=67.50, z=-350.50], EntityGib['unknown'/432, l='MpServer', x=70.29, y=67.28, z=-350.22], EntityGib['unknown'/433, l='MpServer', x=70.71, y=67.28, z=-350.78], EntityScent['entity.EntityScent.name'/436, l='MpServer', x=-5.50, y=72.50, z=-371.50], EntityAnimation['entity.animation.name'/438, l='MpServer', x=-7.00, y=72.00, z=-372.00], EntitySkeleton['Skeleton'/185, l='MpServer', x=-25.46, y=71.00, z=-402.82], EntityCreeper['Creeper'/186, l='MpServer', x=-23.84, y=68.00, z=-401.51], EntityCreeper['Creeper'/187, l='MpServer', x=-30.76, y=68.00, z=-400.50], EntityZombie['Zombie'/188, l='MpServer', x=-30.26, y=67.00, z=-402.18], EntitySkeleton['Skeleton'/189, l='MpServer', x=-18.61, y=65.00, z=-405.90], EntityZombie['Zombie'/190, l='MpServer', x=-31.33, y=68.00, z=-400.51], EntityScent['entity.EntityScent.name'/191, l='MpServer', x=-31.70, y=68.00, z=-400.51], EntityZombie['Zombie'/192, l='MpServer', x=-31.13, y=71.00, z=-400.21], EntitySkeleton['Skeleton'/193, l='MpServer', x=-21.67, y=71.00, z=-399.51], EntityHorse['Horse'/194, l='MpServer', x=-10.86, y=67.00, z=-409.89], EntityCreeper['Creeper'/195, l='MpServer', x=-2.43, y=67.92, z=-404.48], EntitySkeleton['Skeleton'/196, l='MpServer', x=-11.70, y=68.00, z=-401.70], EntitySkeleton['Skeleton'/197, l='MpServer', x=-10.30, y=68.00, z=-401.70], EntityEyes['Eyes'/198, l='MpServer', x=-10.82, y=66.00, z=-402.50], EntityBat['Bat'/199, l='MpServer', x=-8.25, y=69.10, z=-405.56], EntityCreeper['Creeper'/200, l='MpServer', x=-3.79, y=71.00, z=-400.42], EntityPig['Pig'/201, l='MpServer', x=-10.23, y=71.00, z=-403.46], EntityCow['Cow'/202, l='MpServer', x=-21.29, y=73.00, z=-335.86], EntityCustomMob10000['entity.bandit1.name'/203, l='MpServer', x=-7.29, y=72.00, z=-372.32], EntityCow['Cow'/204, l='MpServer', x=-4.83, y=72.00, z=-358.87], EntityChicken['Chicken'/205, l='MpServer', x=-30.24, y=73.00, z=-335.10], EntitySheep['Sheep'/206, l='MpServer', x=-23.77, y=73.00, z=-335.48], EntitySheep['Sheep'/207, l='MpServer', x=-27.82, y=73.00, z=-333.42], EntitySheep['Sheep'/208, l='MpServer', x=24.22, y=65.00, z=-413.45], EntityZombie['Zombie'/209, l='MpServer', x=16.50, y=65.00, z=-408.50], EntityCow['Cow'/210, l='MpServer', x=19.07, y=79.00, z=-298.61], EntityPig['Pig'/213, l='MpServer', x=-9.51, y=78.00, z=-315.78], EntitySheep['Sheep'/214, l='MpServer', x=9.79, y=75.00, z=-324.48], EntityCow['Cow'/215, l='MpServer', x=-0.53, y=80.00, z=-295.81], EntityPig['Pig'/216, l='MpServer', x=21.34, y=73.00, z=-336.20], EntityCow['Cow'/223, l='MpServer', x=56.14, y=55.49, z=-420.45], EntityRabbit['Rabbit'/225, l='MpServer', x=35.41, y=77.00, z=-308.54], EntityZombie['Zombie'/226, l='MpServer', x=70.50, y=66.00, z=-350.50], EntityCreeper['Creeper'/227, l='MpServer', x=66.50, y=66.00, z=-357.78], EntitySkeleton['Skeleton'/228, l='MpServer', x=70.50, y=66.00, z=-365.50], EntityZombie['Zombie'/229, l='MpServer', x=70.50, y=66.00, z=-360.50], EntityXPOrb['Experience Orb'/230, l='MpServer', x=63.44, y=71.00, z=-371.18], EntityZombie['Zombie'/231, l='MpServer', x=69.61, y=66.00, z=-387.50], EntityCreeper['Creeper'/244, l='MpServer', x=66.50, y=66.00, z=-307.50]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/294, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1170885472 bytes (1116 MB) / 3682598912 bytes (3512 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_F5 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version             | Source                                   | Signature                                |
	|:------ |:-------------------- |:------------------- |:---------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2              | minecraft.jar                            | None                                     |
	| LCHIJA | mcp                  | 9.42                | minecraft.jar                            | None                                     |
	| LCHIJA | FML                  | 8.0.99.99           | forge-1.12.2-14.23.5.2855.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2855        | forge-1.12.2-14.23.5.2855.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy    | 1.0.0               | minecraft.jar                            | None                                     |
	| LCHIJA | littletilescore      | 1.0.0               | minecraft.jar                            | None                                     |
	| LCHIJA | obfuscate            | 0.4.2               | minecraft.jar                            | None                                     |
	| LCHIJA | valkyrienskies       | 1.1.7               | [[valkyrien-skies-1.1.7-all]].jar        | None                                     |
	| LCHIJA | antiqueatlas         | 4.5.1               | antiqueatlas-1.12.2-4.5.1.jar            | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA | antiqueatlasoverlay  | 1.2                 | antiqueatlas-1.12.2-4.5.1.jar            | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA | badmobs              | 1.1.40              | BadMobs-1.12.2-1.1.40.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | bard_mania           | 0.15.0-alpha        | bard-mania_1.12.2-0.15.0-alpha.jar       | 999640c365a8443393a1a21df2c0ede9488400e9 |
	| LCHIJA | cookingforblockheads | 6.5.0               | CookingForBlockheads_1.12.2-6.5.0.jar    | None                                     |
	| LCHIJA | extendedrenderer     | v1.0                | coroutil-1.12.1-1.2.37.jar               | None                                     |
	| LCHIJA | coroutil             | 1.12.1-1.2.37       | coroutil-1.12.1-1.2.37.jar               | None                                     |
	| LCHIJA | configmod            | v1.0                | coroutil-1.12.1-1.2.37.jar               | None                                     |
	| LCHIJA | creativecore         | 1.10.0              | CreativeCore_v1.10.62_mc1.12.2.jar       | None                                     |
	| LCHIJA | ctm                  | MC1.12.2-1.0.2.31   | CTM-MC1.12.2-1.0.2.31.jar                | None                                     |
	| LCHIJA | ptrmodellib          | 1.0.5               | PTRLib-1.0.5.jar                         | None                                     |
	| LCHIJA | props                | 2.6.3               | Decocraft-2.6.3_1.12.2 (1).jar           | None                                     |
	| LCHIJA | orelib               | 3.6.0.1             | OreLib-1.12.2-3.6.0.1.jar                | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround            | 3.6.2.1             | DynamicSurroundings-1.12.2-3.6.2.1.jar   | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | exnihiloomnia        | 1.0                 | exnihiloomnia_1.12.2-0.0.2.jar           | None                                     |
	| LCHIJA | eyesinthedarkness    | 0.1.0               | EyesInTheDarkness-0.1.0.jar              | None                                     |
	| LCHIJA | firstaid             | 1.6.16              | firstaid-1.6.16.jar                      | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCHIJA | geckolib3            | 3.0.0               | forge-1.12.2-geckolib-3.0.0-beta.5.jar   | None                                     |
	| LCHIJA | forgelin             | 1.8.4               | Forgelin-1.8.4.jar                       | None                                     |
	| LCHIJA | ichunutil            | 7.2.2               | iChunUtil-1.12.2-7.2.2.jar               | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | improvedbackpacks    | 1.12.2-1.4.0.0      | ImprovedBackpacks-1.12.2-1.4.0.0.jar     | None                                     |
	| LCHIJA | jei                  | 4.16.1.301          | jei_1.12.2-4.16.1.301.jar                | None                                     |
	| LCHIJA | vehicle              | 0.44.1              | vehicle-0.44.1-mc1.12.2.jar              | None                                     |
	| LCHIJA | jev                  | 2.0.0               | jev-1.12.2-2.0.0.jar                     | None                                     |
	| LCHIJA | littletiles          | 1.5.0               | LittleTiles_v1.5.19_mc1.12.2.jar         | None                                     |
	| LCHIJA | mobamputation        | 7.0.0               | MobAmputation-1.12.2-7.0.1.jar           | None                                     |
	| LCHIJA | mobends              | 1.0.0-beta-20.06.20 | MoBends_1.12.2-1.0.0-beta-20.06.20.jar   | None                                     |
	| LCHIJA | mobsunscreen         | 1.12.2-2.1.3        | mobsunscreen-1.12.2-2.1.3.jar            | None                                     |
	| LCHIJA | mw                   | 0.4.6.2             | mw_2.0-0.4.6.2_mc1.12.2 (3).jar          | None                                     |
	| LCHIJA | neid                 | 1.5.4.4             | NotEnoughIDs-1.5.4.4.jar                 | None                                     |
	| LCHIJA | harvestcraft         | 1.12.2zb            | Pam's HarvestCraft 1.12.2zg.jar          | None                                     |
	| LCHIJA | vs_world             | 1.12.2-1.0.0        | vs-world-1.12.2-1.0.0.jar                | None                                     |
	| LCHIJA | vs_control           | 1.12.2-1.1.1        | vs-control-1.12.2-1.1.1.jar              | None                                     |
	| LCHIJA | waterstrainer        | 3.3.0               | WaterStrainer-1.12-3.3.0.jar             | None                                     |
	| LCHIJA | worldedit            | 6.1.10              | worldedit-forge-mc1.12.2-6.1.10-dist.jar | None                                     |
	| LCHIJA | zombieawareness      | 1.12.1-1.11.16      | zombieawareness-1.12.1-1.11.16.jar       | None                                     |

	Loaded coremods (and transformers): 
Plugin (NotEnoughIDs-1.5.4.4.jar)
  ru.fewizz.neid.asm.Transformer
weaponlib (mw_2.0-0.4.6.2_mc1.12.2 (3).jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MixinLoaderForge ([[valkyrien-skies-1.1.7-all]].jar)
  
TransformLoader (DynamicSurroundings-1.12.2-3.6.2.1.jar)
  
LittlePatchingLoader (LittleTiles_v1.5.19_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CreativePatchingLoader (CreativeCore_v1.10.62_mc1.12.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 1.12BetterVanillaBuildingV2.41.zip, Tissou's+Zombie+Pack+1.12.2.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Chocapic13_V8_Ultra.zip
	OpenGlVersion: 4.6.0 NVIDIA 456.71
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

**Comment by CreativeMD** [comment]
This is a known issue and will not be fixed. Sorry but there are too many problems between these two mods.
