### ISSUE TITLE
My game keeps crashing when I try to use the hammer

### ISSUE THREAD

**Issue by JaydeAlex** [CreativeMD/LittleTiles#733]
I have installed the mod as i was supposed to but when I try to use the hammer it crashes. I can get into Minecraft, make a new game, build with other things from different mods but when I try to use the hammer my game crashes, I have looked everywhere for a solution but cant find one, can someone help?

**Comment by CreativeMD** [comment]
Can you please send me the crash-report?

**Comment by CreativeMD** [comment]
Will close this issue for now. If it still persists just post the crash-report here.
