### ISSUE TITLE
issue with cables picking

### ISSUE THREAD

**Issue by crystheshard** [CreativeMD/LittleTiles#735]
By picking arrange of cables with shift+middle-click and placing it in the world, it places invisible "Dyeable Clean" instead of cables.
[Screenshots](https://imgur.com/a/IOxIBNy)

**Comment by ghost** [comment]
yes i can reproduce this

**Comment by CreativeMD** [comment]
This way of doing things does not remember any sort of structures and it's also not the intention behind it. You should rather create a recipe for that.
