### ISSUE TITLE
[Question] [Development] LittleTiles as camouflage for custom TileEntity

### ISSUE THREAD

**Issue by slava110** [CreativeMD/LittleTiles#736]
Hi. I have custom TileEntity in the mod I'm developing and it's possible to put camouflage on this TileEntity. I wanted to add optional compatibility with LittleTiles so it'll be possible to use LittleTiles as camouflage.
I have 2 approaches in my mind:
1. Get LittleTiles model from ItemStack and render it over custom TileEntity
2. Make fully compatible TileEntity so it will be possible to place little tiles directly into custom TileEntity in-world
What would be the best way to implement something like that if this compatibility should be optional? And what should I use from LittleTiles to implement it?

**Comment by CreativeMD** [comment]
That seems like a very difficult thing to do. There are just too many things to consider. I would rather recommend to add a new structure to LT, which is super easy. Just tell me what you think about that idea, I will close the issue for now (you can also contact me via discord). Also sorry for not responding earlier.

**Comment by slava110** [comment]
Wdym by adding new structure to LittleTiles tho?

**Comment by Dushess** [comment]
Create it by own components (or with another materials too) and save as item?

**Comment by CreativeMD** [comment]
Sorry for not responding earlier. There are structure types (door, chair, etc.). There are also premade once like the importer, exporter and workbench. ALET (an addon) does add a lot more structure types. You could do that as well, but then it would require LittleTiles to be installed in order to use it.

**Comment by slava110** [comment]
Ye, that wouldn't work because dependency should be optional... No way to achieve that with LT as optional dependency?

**Comment by CreativeMD** [comment]
Unfortunately not, it's just not the scope of the mod and would be way too much work.

**Comment by slava110** [comment]
Okay, thanks for help anyway
