### ISSUE TITLE
Little Blueprint doesn't remember signal converters

### ISSUE THREAD

**Issue by crystheshard** [CreativeMD/LittleTiles#739]
Why?

**Comment by CreativeMD** [comment]
Please provide more information. If Remember structures is enabled it should also remember all signal converters.

**Comment by crystheshard** [comment]
But it doesn't
https://imgur.com/a/YvrVJCL

Minecraft 1.12.2
Little Tiles 1.5.21

**Comment by ghost** [comment]
yes its the same as furnaces, enchant tables and more. But that has always been the case. 

So Blueprints only work with things that e.g. the little chisel can also pick up.

**Comment by CreativeMD** [comment]
Yeah, that's a block with tileentity, that cannot work as @blakedj012 stated.
