### ISSUE TITLE
Multi-Tile Structure Overwriting

### ISSUE THREAD

**Issue by Ricktrandom** [CreativeMD/LittleTiles#74]
I just built a Checkers/Chess set with this, but when I pick up the Quartz checkers pieces in survival and then pickup a Stone one, it stacks onto the Quartz one and changes their material to stone.

**Comment by Ricktrandom** [comment]
Oh, apparently if I pickup any multi-tile structure, regardless of the Size, Shape, or Material. It will stack and Overwrite the one I'm carrying, duplicating itself.

**Comment by Ricktrandom** [comment]
I just found a way around it, if I throw the object on the ground before picking up a new one it doesn't happen when I pick it back up

**Comment by CreativeMD** [comment]
Can you send me a few screenshots (or maybe the world itself)?

**Comment by CreativeMD** [comment]
Never mind I fixed it. I will release it in a few minutes.

**Comment by Ricktrandom** [comment]
Oh cool, Thanks

**Comment by Ricktrandom** [comment]
um, I just got rid of all my mods and got the new Littletiles and Creative core, then hopped onto a new test world for this, and it seems the issue's still here.

**Comment by Ricktrandom** [comment]
Perhaps you fixed a different issue, this one should be easy to replicate so I'll give a more in-depth description of it. When on a survival world, after I have made something out of little tiles, of which I have set the grid size to 32 if that makes any difference, And after I've used a blueprint to set it to something other than the default, for instance a Fixed object. then placed it, if I pick it up, then pickup another fixed object, the second one will stack on the first in my inventory, making the first become it, of course this only happens on Survival, since in creative you can just use pick block which automatically chooses the next available hotbar space.

**Comment by CreativeMD** [comment]
Sorry, i had no time to upload it yesterday. It is fixed now, new version should be available soon (You need to update CreativeCore). Thank you very very much for reporting this issue! It was a rather serious one.
