### ISSUE TITLE
Crashing issue

### ISSUE THREAD

**Issue by Alpha76543** [CreativeMD/LittleTiles#740]
When I click play in the Minecraft Launcher, it starts loading but just before Minecraft starts loading up, the Minecraft Launcher opens again and says that it crashed, it doesn't say why it crashed but when I took out the little tiles mod it worked again.

**Comment by CreativeMD** [comment]
Make sure to install CreativeCore as well. Also please download the newest version from curseforge and also make sure it's for Minecraft 1.12. For the future always provide a crash-report if a crash is your issue.
