### ISSUE TITLE
Config "build" subsection defaults after entering a world

### ISSUE THREAD

**Issue by tonyvranic** [CreativeMD/LittleTiles#741]
As mentioned above, the subsection "build" of the littletiles config defaults it's values to 0 (values I tested: maxAffectedBlocks, harvestLevelBlocks, maxPlaceBlocks). The values default to 0 as soon as I enter a world. But the first time a world is opened, the user-desired values are in-effect, and not the 0, even though the config says so.

**Comment by CreativeMD** [comment]
Unfortunately I don't get everything you say. You can in theory ignore the "default" configuration because you have a configuration for survival and creative, which is all you need. Not sure if there is an issue now? Could you please clarify what you mean?

**Comment by tonyvranic** [comment]
Thanks for the response.

I've set up an album of screenshots with descriptions of the problem:
https://imgur.com/a/rSuGiT4

Thought that may be the fastest way to explain.

**Comment by CreativeMD** [comment]
You should not use the config file. Rather use the command /cmdconfig, because if minecraft is still open it will ignore changes. Also the gui is easier to use.

**Comment by tonyvranic** [comment]
Yep, that did it. I wasn't aware of the "/cmdconfig" command at all.
I've added another subsection called "adventure" and set my desired values there. The placement now works like a charm
