### ISSUE TITLE
Cannot destroy fixed structures in Adventure Mode

### ISSUE THREAD

**Issue by tonyvranic** [CreativeMD/LittleTiles#742]
I've added the CanDestroy tag on a stick. I can interact with the fixed structure and "break" it, but it spawns right back in the next tick. An endless loop. If I placed the structure in-between 2 blocks and try to break it. The structure wouldn't render on 1 of the 2 blocks it was placed (while still being there). After I try to break it the second time I get a message "Structure is not loaded".

**Comment by CreativeMD** [comment]
Yeah pretty sure the server denies it. Can you send me your world so I can test it myself and see what is happening?

**Comment by tonyvranic** [comment]
I've got a handful of other mods so I can't really send you the world. You can recreate it pretty easily.

Album of screenshots with descriptions:
https://imgur.com/a/dl4lSor

I've made a "slab-like" structure out of stone that's fixed.
/give @p littletiles:multitiles 62 0 {tiles:[{bBox:[I;1,0,1,15,8,15],tile:{block:"minecraft:stone:6"}}],min:[I;1,0,1],size:[I;14,8,14],count:1,CanPlaceOn:["minecraft:stone"],structure:{blocks:[I;],name:"test1",id:"fixed"}}

And I've got a stick that has permission to break wooden buttons and tiles in adventure mode.
/give @p minecraft:stick 1 0 {CanDestroy:["minecraft:wooden_button","littletiles:blocklittletiles"]}


If you need anything else, shout :)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Sorry that it took me so long.
