### ISSUE TITLE
Replace Slice Struktur with Slice Replace Mod undo/redo = crash

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#744]
When I replace a slice structure with a new slice structure in replace mode and then undo it, weird tiles are created that go through a section of the map.

If I redo afterwards the game crashes with the following error message:

https://pastebin.com/pJ5GEfj6

**Comment by CreativeMD** [comment]
Took quite some time to figure out what's wrong. I managed to fix it. Btw it also affected other modes, such as overwrite, stencil and colorize. Thanks for reporting this issue!
