### ISSUE TITLE
Struktur Animation weird behavior

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#745]
Structure: https://pastebin.com/90bb5bsq

If you place this structure and run the animation once it starts to flicker and is faulty. And after a while it just dissolves. Sometimes there is also the following crash.

Crash: https://pastebin.com/xz3jE2da

**Comment by ghost** [comment]
When you log out and log in again property and structure is gone so it shows it then. And the building dissolves.

**Comment by CreativeMD** [comment]
The crashed for me as I attempted it the first time and then it worked just fine. I'm in singleplayer so it's probably an issue with the server. Sorry, but I won't fix it. Huge doors cause so many different issues. I will enhance the system during the update, which will hopefully fix many of the issues, but fixing it for 1.12 would hold me back for too long.

**Comment by CreativeMD** [comment]
I will close this issue for now, because it's very similar to https://github.com/CreativeMD/LittleTiles/issues/745.
