### ISSUE TITLE
Little Hammer Slice Cut not work

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#746]
This:

https://gyazo.com/74f00fb44f9e4e614d092cd2455c683b

makes this:

https://gyazo.com/fbe8d628aa18d0d7b0eaa7b923feba3a

**Comment by ghost** [comment]
The same on all other variants like Corners and so on...

**Comment by CreativeMD** [comment]
Yeah, that's not a thing. A feature like this does not exist because it would not work in all cases. Might be added in the future, but not sure if the problem behind it can be solved.
