### ISSUE TITLE
Perma-lit lamps crash the game when placed

### ISSUE THREAD

**Issue by SteampsonJake** [CreativeMD/LittleTiles#748]
As per Kopie's suggestion, I've decided to just connect "1" to the output instead of struggling with the booleans.

![image](https://user-images.githubusercontent.com/47562841/133823392-d89a9225-127e-4de2-9f41-d800f16528c5.png)

I've placed roughly 600 of these lamps in my world without an issue, but for some reason I'm now crashing whenever I place down a new one.

[crash-2021-09-16_20.52.28-server.txt](https://github.com/CreativeMD/LittleTiles/files/7187122/crash-2021-09-16_20.52.28-server.txt)

**Comment by CreativeMD** [comment]
Should be fixed in the newest version. Also a small hint, you shouldn't use the signal mode toggle, use equal instead.
