### ISSUE TITLE
Crash with door higher than the normal world height

### ISSUE THREAD

**Issue by Desoroxxx** [CreativeMD/LittleTiles#751]
Hello, the issue in #258 #247 are still here, tested with latest Little Tiles and Cubic Chunk and also latest Forge

Crash report: https://hastebin.com/lifolixomo.rb

**Comment by CreativeMD** [comment]
No idea why this is happening again ... sorry but I won't fix it. The focus is on the port.

**Comment by CreativeMD** [comment]
Should be fixed in the newest version. As I did all the changes for the door already I finally realized why this is happening and fixed it.
