### ISSUE TITLE
Dupe Bug with Little Glove

### ISSUE THREAD

**Issue by TheBlueCrystal** [CreativeMD/LittleTiles#753]
MC-version: 1.12.2
Forge-version: 14.23.5.2850
Little-Tiles version: LittleTiles_v1.5.24_mc1.12.2

When using the Little Glove to replace Little Tiles blocks then the replacing block is placed into the Little Bag instead of the replaced one. 

Steps to reproduce:

1. Place any block as Little Tiles block (for example a dirt block).
2. Replace (parts of) it using the Little Glove with another block (for example a diamond block).

You now got the amount of replaced little tiles of the replacing block (in the example above the diamond block) in your Little Bag.

**Comment by CreativeMD** [comment]
Thanks a lot for reporting this issue. There were several issues related to ingredients. It should all be fixed in the newest version.

**Comment by TheBlueCrystal** [comment]
Thank you very much! :)
