### ISSUE TITLE
crash by java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by EVgenyGP** [CreativeMD/LittleTiles#755]
So, i found bug in littletiles, so the issue manifests itself because of some item that I had in my inventory, when I cleared the inventory the problem went away. I do not know what kind of tile I had in my inventory

[crash-2021-10-02_16.58.32-client.txt](https://github.com/CreativeMD/LittleTiles/files/7272882/crash-2021-10-02_16.58.32-client.txt)

i was use latest versions of littletiles and creativeCore

**Comment by EVgenyGP** [comment]
So, today i take this block again, so there is dat file from the world, my nickname - EVgenyGP

[6033e11c-1aa9-305d-8844-1a337dff5003.dat.txt](https://github.com/CreativeMD/LittleTiles/files/7276549/6033e11c-1aa9-305d-8844-1a337dff5003.dat.txt)

**Comment by CreativeMD** [comment]
Hopefully fixed in the newest version. If not just post the new crash-report here again. Thanks for reporting this issue.
