### ISSUE TITLE
Emit light glowstone not work :(

### ISSUE THREAD

**Issue by DCCross** [CreativeMD/LittleTiles#756]
Hello, I have been trying for several days to make a lamp with little tiles and that emits light, but when I put a bright block on it, it emitted little or no light.

So I investigated and discovered this function of modifying the light emitted by a block with the luminous stone. I followed the instructions on how to modify the light with the glowstone, but it didn't work. so i gave up and decided to post my issue :(

Version: 1.12.2
Littletiles version: LittleTiles_v1.5.21_mc1.12.2.jar

Screen:
https://imgur.com/a/HKmz2aT

My spec:
https://imgur.com/gallery/dMHbwth

Excuse me if my English is bad, I use google translate. :)

**Comment by Desoroxxx** [comment]
The glow stone feature has been replaced by a structure type.

You need to create a blueprint then set the structure type [none] by default to light and then select the light level.

If you when the light to always stay on you can follow this tutorial: https://imgur.com/a/t2suksT

**Comment by DCCross** [comment]
> La característica de piedra brillante ha sido reemplazada por un tipo de estructura.
> 
> Debe crear un plano, luego establecer el tipo de estructura [ninguno] de forma predeterminada en luz y luego seleccionar el nivel de luz.
> 
> Si cuando la luz permanezca siempre encendida puedes seguir este tutorial: https://imgur.com/a/t2suksT

Understood, Thanks for the quick answer I will try it :)
