### ISSUE TITLE
"c2.b0" state donest give output but "b0 state" does "bug"

### ISSUE THREAD

**Issue by DonK4rma** [CreativeMD/LittleTiles#757]
![image](https://user-images.githubusercontent.com/82897907/136720104-2468e09f-5fdd-4b55-af1c-59a902c20b67.png)
![image](https://user-images.githubusercontent.com/82897907/136720118-0c2bded7-9874-4c3e-aac8-494b228f01d4.png)
![image](https://user-images.githubusercontent.com/82897907/136720131-b79160e1-199f-480c-b2c5-d2c70e36e5fd.png)
![image](https://user-images.githubusercontent.com/82897907/136720143-392962b3-55e3-44d0-814f-f5de1411f246.png)

**Comment by Desoroxxx** [comment]
Can you write what you expect to happen and what really happen cause even with the picture I don't understand

**Comment by DonK4rma** [comment]
The whole concept of this door its that the input can only close the door, not open it, an at the same time the door has to give and output to the 4 bit output

**Comment by CreativeMD** [comment]
Can you show the structure hierarchy? No idea how things are build.

**Comment by CreativeMD** [comment]
any news?
