### ISSUE TITLE
Update CurseForge version for MC1.7.10

### ISSUE THREAD

**Issue by andrewminer** [CreativeMD/LittleTiles#765]
I've created [a modpack](https://www.curseforge.com/minecraft/modpacks/istari) which combines the Lord of the Rings Mod with Thaumcraft.  Unfortunately, the full version of the LotR mod is only available in Minecraft 1.7.10, so I'm stuck on that version.  Even more unfortunately, the most recent version of LittleTiles available in CurseForge for 1.7.10 is 1.2.  As you know, this version of LittleTiles is dramatically inferior to later versions.  

Is it possible to post a newer version of LittleTiles (ideally > 1.5) to CurseForge for MC 1.7.10?

**Comment by CreativeMD** [comment]
There is a version for 1.7.10. Just click on Files, then hit "View all" and select the minecraft version you are searching for.

**Comment by andrewminer** [comment]
Understood. That's the version we currently have in the modpack. Unfortunately, v1.2 (the version available for 1.7.10) is missing a lot of what makes LittleTiles so great in later versions. The request is to get newer version for MC 1.7.10 than the one currently available.  (sorry for the comment churn... differnet users in different browsers is confusing)

**Comment by CreativeMD** [comment]
I have dropped support for 1.7.10 years ago. I won't port 1.5.0 back if that is what you are asking for. The version on curseforge is the latest version for 1.7.10.

**Comment by andrewminer** [comment]
I completely understand.  It's a *really* old version at this point!  Thanks, anyway!
