### ISSUE TITLE
How do I have LT blocks block out light?

### ISSUE THREAD

**Issue by WildArticunoAppeared** [CreativeMD/LittleTiles#768]
I like to use LittleTiles to make buildings with different walls on the inside from the outside. But this comes at the cost of these blocks letting light through, even if they are full blocks that fences can connect to or torches can be placed on. 
![image](https://user-images.githubusercontent.com/34997555/138584034-001ad6b4-4378-44c6-a3f2-4dd6c231aa50.png)
Is there any way to make these blocks stop light from getting through?

**Comment by CreativeMD** [comment]
Unfortunately that is not possible in 1.12, I hope it will be different in 1.17/1.18.
