### ISSUE TITLE
Crashing When Activating 'Sliding' Block

### ISSUE THREAD

**Issue by c5001481cepheus** [CreativeMD/LittleTiles#769]
Using latest version of **LittleTiles** and dependencies, and I can't seem to use the '**sliding**' function for an object. When the crafted block is placed, and ready to use, I right-click to activate it, but it crashes **every** time, even in the older versions I've tested.

Here is the crash log file: 

[crash-2021-10-24_08.10.51-client.txt](https://github.com/CreativeMD/LittleTiles/files/7406526/crash-2021-10-24_08.10.51-client.txt)

**Comment by CreativeMD** [comment]
LittleTiles is incompatible with valkyrienskies.
