### ISSUE TITLE
Dupe with Little Wrench

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#77]
I'm not sure if this mod is indeed causing the bug, or just making it easier to replicate (The Little Wrench inventory seems to have a little delay when moving things around), but if I keep moving a stack of items around for a while inside the Little Wrench GUI (It happens faster if I also press shift to move the items up while clicking), it has a chance of giving me a different amount of items at the end.
I've tried to replicate it in other GUIs and inventories, but all of them gave (so far) only visual bugs that fix themselves up when you open a chest or sort your inventory.
GIF with it happening:
https://i.imgur.com/Or4QqBL.gifv

The testing was done on a server environment with about 70 other mods, tick time was ~25ms and I get about 160ms of latency on it. The other mod that I believe could also be connected to this is SpongeForge and perhaps Quark or JEI.

CreativeCore_v1.9.18_mc1.12.2 and LittleTiles_v1.5.0-pre72_mc1.12.2 being used, no exceptions or logs fired on the console.

**Comment by ghost** [comment]
I've setup a server with only CreativeCore, LittleTiles and Forge to test and was still able to replicate it.
New GIF: (Last one got a weird quality)
https://media.giphy.com/media/PLJeEPnfEvUwGGUPSE/giphy.gif

For some reason it was even easier to dupe this time, and I didn't even need to press shift to make it faster.
Also, it doesn't necessarily give you more items, sometimes you lose a few in the process.

Update: It is also present in older versions (LittleTiles v1.4.12 mc1.10.2 at least), but while in the latest version you rarely crash when trying to dupe, you crash almost every time in this version.

**Comment by CreativeMD** [comment]
Does this version fixes it?
https://www.dropbox.com/s/suwqp0ie9p0ohb6/CreativeCore_v1.9.20_mc1.12.2.jar?dl=1

**Comment by ghost** [comment]
Tested with CreativeCore_v1.9.20 and LittleTiles_v1.5.0-pre80 and still could dupe. 
I tried to replicate it again in other inventories and there seems to be something similar happening in the player inventory, but while in the little wrench inventory you tend to gain extra items, in the player inventory you always seem to lose items when trying to replicate it. (Perhaps I wasn't lucky enough)

My best guess is that if you mess with Item Stacks fast enough you might desynchronize your inventory with the server for a short while and if you put part of that stack somewhere else before it fixes itself again you're going to mess it for good and get more or less items than you originally had. I just don't get why you can get more or less items in the Little Wrench inventory while in the normal player inventory you always seem to get less.

Couldn't replicate it with a chest open (Neither inside the chest nor in the player inventory) and it can't be performed in single player since the internal server has no latency with the client, making it a multiplayer only issue.

**Comment by CreativeMD** [comment]
There is a difference between this inventory and ordinary vanilla inventory. I created my own gui api, which is completely self written (this bug is purely my mod).

Can you try out another version?
https://www.dropbox.com/s/suwqp0ie9p0ohb6/CreativeCore_v1.9.20_mc1.12.2.jar?dl=1

I tried to reproduce using that version, but couldn't.

**Comment by ghost** [comment]
Updated server and client with this version and still could do it.

If you wish you can use the server I've set up for this to test it. From what I've seem you're from Germany and the datacenter it's being hosted at is in Canada, you would probably get 100ms and at least for me this is enough to replicate it without trouble. In case you wanna try it, add me on Discord (Vohario#4826) or Twitch (Vohario) so I can pass further information about the server.

**Comment by CreativeMD** [comment]
Fixed in v1.9.22. Thank you very much for reporting this issue and testing it!
