### ISSUE TITLE
Loading Little Tiles Blocks sometimes doesn't work some times

### ISSUE THREAD

**Issue by gameusefly** [CreativeMD/LittleTiles#771]
Sometimes LittleTiles Blocks doesn't load corretly.
Like this:
![2021-10-28_20 01 40](https://user-images.githubusercontent.com/77025397/139310977-4df470af-ca76-486f-ba89-1ac298d10373.png)
When i press F3+A for reloading chunks LittleTiles Blocks load correctly at the first time
Like this:
![2021-10-28_20 06 41](https://user-images.githubusercontent.com/77025397/139311126-69a0217f-a2d2-4e6c-a5fc-af6d6c38e632.png)

Some Data:
LittleTiles Version -> LittleTiles_v1.5.20_mc1.12.2

**Comment by CreativeMD** [comment]
LittleTiles sometimes requires some time to load all blocks. You can use the command /lt-debug to see how many blocks are in the rendering queue. Besides that there are some mods which cause rendering glitches like Phosphor.

Also make sure to update to the newest version.
