### ISSUE TITLE
Shift-lmb clicking a dyed tile with Paint Brush just paints instead of copying colour.

### ISSUE THREAD

**Issue by Kiefy** [CreativeMD/LittleTiles#773]
**MC Eternal Modpack v1.5**
MC 1.12.2
Forge 14.23.5.2854
LittleTiles_v1.5.0-pre327_mc1.12.2

I haven't rebound Shift from Sneak or anything.
Surface is definitely dyed with Little Tiles.
Had a friend try it and he couldn't figure it out either.

**Comment by Kiefy** [comment]
Wow, I just realised how old that version is.  Going to close for now and update. see if the problem is still there.

**Comment by CreativeMD** [comment]
You can get the color by clicking the mouse wheel button.
