### ISSUE TITLE
Half-transparent Pillars culling is broken

### ISSUE THREAD

**Issue by juh9870** [CreativeMD/LittleTiles#778]
![2021-11-03_19 39 25](https://user-images.githubusercontent.com/15922601/140163019-f7bec11f-9a45-48d6-b4a3-268b6848437f.png)
Structure: https://pastebin.com/vycwYADb

Similar thing happens to slices at block boundaries
![2021-11-03_19 39 51](https://user-images.githubusercontent.com/15922601/140163641-3c83e03f-636a-48dd-89d6-8f4bd69b5585.png)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
