### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by axin0452** [CreativeMD/LittleTiles#779]
https://srcb.in/zM7xR6ZcKN

I don't know what more information I need to provide to help you fix this bug,
Please let me know if you need anything

**Comment by CreativeMD** [comment]
Normal forge servers do work. Furthermore I support SpongeForge, but I don't support any of the other server types. Sorry but you will need to switch or not build doors with LittleTiles.

**Comment by axin0452** [comment]
@CreativeMD How do I prohibit players from making doors?

**Comment by CreativeMD** [comment]
Unfortunately not possible.
