### ISSUE TITLE
Game crash with Little Chisel and Slice tool

### ISSUE THREAD

**Issue by Opoas** [CreativeMD/LittleTiles#78]
I've experienced game crash while using Little Chisel with Slice tool. The game crashes when I place one block slice through another block slice as shown on the image. (in Creative mode)
I've tried using different materials, as well. The game crashed in 9/10 cases.
Images right before crash:
![Crash one](https://user-images.githubusercontent.com/37119411/37050467-3c5a562a-2174-11e8-8af8-5406354f6f05.png)
![Crash two](https://user-images.githubusercontent.com/37119411/37050494-4c78edf0-2174-11e8-9cd0-49012abe6aff.PNG)
Fortunately, the crash doesn't corrupt map file and when I connect back into the game, the block that caused the crash just isn't there as if I never placed it.
Crash report files:
[crash-2018-03-06_19.05.36-client.txt](https://github.com/CreativeMD/LittleTiles/files/1786201/crash-2018-03-06_19.05.36-client.txt)
[crash-2018-03-06_19.07.49-client.txt](https://github.com/CreativeMD/LittleTiles/files/1786202/crash-2018-03-06_19.07.49-client.txt)
[crash-2018-03-06_19.12.57-client.txt](https://github.com/CreativeMD/LittleTiles/files/1786203/crash-2018-03-06_19.12.57-client.txt)
[crash-2018-03-06_19.21.01-client.txt](https://github.com/CreativeMD/LittleTiles/files/1786204/crash-2018-03-06_19.21.01-client.txt)
I'd also want to say that I love your mod and I hope that most of the issues will be fixed soon.

**Comment by CreativeMD** [comment]
Will be fixed in the next version. Thanks for reporting this issue. You made it really easy for me to find the case of it. Unfortunately I couldn't fix it earlier.

**Comment by CreativeMD** [comment]
Fixed in pre85 available on my discord server (will upload it to curseforge tomorrow). Again thank you very much for your kind documentation!
