### ISSUE TITLE
Weird shading on slopes

### ISSUE THREAD

**Issue by juh9870** [CreativeMD/LittleTiles#780]
![2021-11-05_11 50 49](https://user-images.githubusercontent.com/15922601/140491996-b8262542-4559-4844-8000-320c57458877.png)
Sloped structure (left) have weird shading (doesn't get removed when clicking with chisel).
Expected behavior can be seen in a voxel cylinder on a right
Structure: https://pastebin.com/ckVWTaSF

**Comment by CreativeMD** [comment]
Sorry, can't do anything about that. The rendering is weird, I hope it's better in 1.17.
