### ISSUE TITLE
All mod tools behave like shovel when right-clicking dirt block

### ISSUE THREAD

**Issue by juh9870** [CreativeMD/LittleTiles#781]
![2021-11-05_12 06 49](https://user-images.githubusercontent.com/15922601/140494015-7db6a728-d16e-41c3-b56d-69cc7d1550d6.png)
![2021-11-05_12 06 50](https://user-images.githubusercontent.com/15922601/140494019-4c70db6e-1721-4fa9-9417-246039c1f8a2.png)

**Comment by CreativeMD** [comment]
That's not an issue of LittleTiles but a different mod. Somebody said it was quark, not sure if I remember it correctly though.
