### ISSUE TITLE
Conflicting Doors dupe

### ISSUE THREAD

**Issue by juh9870** [CreativeMD/LittleTiles#782]
I found a way to dupe blocks using multiple conflicting doors
Dm'd you details trough discord

**Comment by CreativeMD** [comment]
I will get to this problem once https://github.com/CreativeMD/LittleTiles/issues/605 is solved.

**Comment by CreativeMD** [comment]
Is the duplicating bug still a thing after the recent fixes?

**Comment by juh9870** [comment]
Just checked, it's still here and works the same

**Comment by CreativeMD** [comment]
Thanks for reporting this issue. It's fixed now!
