### ISSUE TITLE
Tiles stack then blueprint being removed.

### ISSUE THREAD

**Issue by creamIcec** [CreativeMD/LittleTiles#784]
When I try to place a structure through blueprint made by structure builder, Something weird happend. The steps to reproduce this bug goes here:
1. create a little blueprint in the structure builder.
![image](https://user-images.githubusercontent.com/42510470/140601965-68434824-3957-432b-954f-9ab2d6edf1e1.png)
2.  place this blueprint. Everything is normal until now.
![image](https://user-images.githubusercontent.com/42510470/140601978-050ab30c-309d-42b0-94ab-0f7c6fedac91.png)
3. Try to click the same area of the already placed structure, then two tiles stacked(actually crossed) and the little blueprint will be removed from my inventory. 
![image](https://user-images.githubusercontent.com/42510470/140601988-d59613a1-1226-455b-8914-d16da6fd1f91.png)

If I use a blueprint made by myself, it will work normally. This makes me a little troubled because everytime I click there carelessly I have to go back to the builder and make a new one. Please help me.

MC version: 1.12.2
LT version: 1.5.0
CreativeCore version: 1.10.0
Other mods installed: WorldEdit, WorldEdit Forge CUI 3

**Comment by CreativeMD** [comment]
It's fixed in the newest version. The rightclick has been reworked and it will now work more consistent.
