### ISSUE TITLE
Rendering issue when door is opened

### ISSUE THREAD

**Issue by s185948** [CreativeMD/LittleTiles#785]
When I click on a sliding door, the door goes crazy when the coordinate of the door is far away from x0 z0. The issue seems to get worse when the player is further away from x0 z0.
https://streamable.com/afsut3

I am currently using CreativeCore_v1.10.68_mc1.12.2, LittleTiles_v1.5.45_mc1.12.2, forge 1.12.2 14.23.5.2855, with or without Optifine G5.

**Comment by CreativeMD** [comment]
Sorry but I won't fix this issue. There is no reason to go so far away from the center. This is a float number precision issue and the amount of work it would require to fix it, is not worth. Maybe in a future update, but I doubt anyone would care anyway.
