### ISSUE TITLE
Game Crashed Before Start

### ISSUE THREAD

**Issue by zhangzishuai1995** [CreativeMD/LittleTiles#786]
I have tried several mods for version 1.12.2, but they all showed game crashed and exit code 0 right after I click "play". 
<img width="995" alt="截屏2021-11-28 上午11 29 52" src="https://user-images.githubusercontent.com/34459292/143727740-4ea35a76-bdbc-4fe1-a5fe-c568cc2715ea.png">

**Comment by CreativeMD** [comment]
Don't forget to install CreativeCore.
