### ISSUE TITLE
Half-transparent Pillars culling is broken (again)

### ISSUE THREAD

**Issue by juh9870** [CreativeMD/LittleTiles#788]
Structure: https://pastebin.com/6nRMupJz
Mod file: LittleTiles_v1.5.46_mc1.12.2
![2021-11-30_19 32 30](https://user-images.githubusercontent.com/15922601/144098446-950f5db6-7ca1-4f42-a610-8b5979ace058.png)
![2021-11-30_19 32 33](https://user-images.githubusercontent.com/15922601/144098448-4d11966a-9caf-45e8-bd0c-029ec21d8719.png)
![2021-11-30_19 34 41](https://user-images.githubusercontent.com/15922601/144098449-d3c11860-e82f-462b-9ab1-7768e319d932.png)

**Comment by CreativeMD** [comment]
I know this sounds weird, but this is not a bug, but a missing feature. There is no face culling for tilted faces. It's on my todo list for 1.18, but will most likely not added in 1.12.
