### ISSUE TITLE
Collision issues

### ISSUE THREAD

**Issue by juh9870** [CreativeMD/LittleTiles#789]
While testing various boosting pads design, I noticed that my designs often fails to work in negative X direction, because structure just passes through the player without pushing him.
Here is an example contraption that works in all direction excepts for negative X.
Contraption: https://pastebin.com/wKrMsb2b

And another example of wall that can push you in any direction other than negative X: https://pastebin.com/1neCQvhV (you need to touch it to trigger)

**Comment by CreativeMD** [comment]
I will rework collision in the future, but not for 1.12. I appreciate the time you invested! I will close this issue for now and get back to it when I tackle collision again for 1.18.
