### ISSUE TITLE
Crush when place little particle block.  

### ISSUE THREAD

**Issue by olegikoligik** [CreativeMD/LittleTiles#79]
Trouble in RTM mod, i know. But maybe you can fix this. Crush going when i place particle block

[crash-2018-03-17_19.45.15-client.txt](https://github.com/CreativeMD/LittleTiles/files/1821911/crash-2018-03-17_19.45.15-client.txt)

**Comment by CreativeMD** [comment]
RTM? The crash report is quite odd. Looks like it's caused by another mod. Can you do some testing to figure out which mod is causing it?

**Comment by olegikoligik** [comment]
Real Train mod from [here](http://forum.minecraftuser.jp/viewtopic.php?t=13633)

**Comment by CreativeMD** [comment]
Sorry there is nothing i can do about it. The crash doesn't make sense and i cannot contact the author. I doubt that this is an issue of my mod.
