### ISSUE TITLE
Large storage structures and JEI/InventoryTweaks

### ISSUE THREAD

**Issue by The-Forge-Master** [CreativeMD/LittleTiles#790]
For some reason, I can't use the double-click search with JEI while in a LT multiblock storage, and InventoryTweaks' shortcuts don't work. For instance, I can't space-click or shift-click-drag to move more than one stack at once, either in or out.

**Comment by CreativeMD** [comment]
LT uses the gui-api of CreativeCore which has it's own inventory system. InventoryTweaks does not support it.
