### ISSUE TITLE
Little Tiles Door Issue

### ISSUE THREAD

**Issue by PioIsNotAvailable** [CreativeMD/LittleTiles#791]
I've already reported it on the discord some time ago, but after some updates the issue is still occurring. Here is the video that shows what's the problem: https://youtu.be/xpNUh5KXzvg

It started occurring when I updated to the newest version of little tiles and creative core on 12/11/2021 and since then all of the updates that came afterwards still had the issue. One thing that fixes it partially is when the door is in opened state I log out of the world and log back in (CreativeMD said it has something to do with client server synchronization).

I also attached an export of the door so you can test it for yourself and see if the same thing happens that was shown on the video. Any help would be appreciated and I'll be happy to provide any more details that could be needed.

[SlidingDoorExport.txt](https://github.com/CreativeMD/LittleTiles/files/7649096/SlidingDoorExport.txt)

**Comment by CreativeMD** [comment]
Should also be fixed in the newest version!
