### ISSUE TITLE
Little Tiles Mod crashing 

### ISSUE THREAD

**Issue by sjhdsgdusg** [CreativeMD/LittleTiles#792]
I am have crash problem of little tiles mod. When I choose 'slice' in chisel it crashes..
Pls help me 😦

**Comment by CreativeMD** [comment]
Make sure to download the newest version of CreativeCore and LittleTiles from curseforge.

**Comment by sjhdsgdusg** [comment]
I have the newest version then too it's crashing..
CreativeCore_v1.10.69_mc1.12.2 version
LittleTiles_v1.5.46_mc1.12.2 version
