### ISSUE TITLE
world disappearing after crash

### ISSUE THREAD

**Issue by yitzhak480** [CreativeMD/LittleTiles#795]
hey my game crashed (probably cause littletiles) and now my world is not in the game, it's in the saves folder but i don't see it in game 
although i have vanillafix the game crashed entirely and sent me back to the launcher
here's my latest crash-report (although i'm not sure it's the actual one)
it happen when i tried to renamed some bluprints on an anvil, i named several
when you have time pls look at this
[crash-2021-12-09_00.32.30-client.txt](https://github.com/CreativeMD/LittleTiles/files/7681056/crash-2021-12-09_00.32.30-client.txt)

**Comment by CreativeMD** [comment]
Hey there, sorry for not responding earlier.
Sometimes the level.dat file in your world gets corrupted. In that case you can use the backup file level.dat.old. Just make sure to do a backup of the original one first and the rename the old one to the proper name.

**Comment by yitzhak480** [comment]
Oh i thought io closed thata issue, i just re did my job from the previous
backup, thanks anyway

‫בתאריך יום ד׳, 15 בדצמ׳ 2021 ב-12:46 מאת ‪CreativeMD‬‏ <‪
***@***.***‬‏>:‬
