### ISSUE TITLE
incorrect texture mapping

### ISSUE THREAD

**Issue by vladislav12384** [CreativeMD/LittleTiles#796]
![16392434980148479494878327760499](https://user-images.githubusercontent.com/48276093/145685826-bd0fe43d-e9a2-4913-8fa9-59087ab0d53a.jpg)

**Comment by CreativeMD** [comment]
Yeah ... actually this is not an issue by itself, that's just how the shape was formed. It depends on which side is actually transformed. Not sure how to change that to be honest. I might need to rewrite some of the code, but for now just rotate it again or flip it and the texture issue should be fixed. Will close this issue for now.
