### ISSUE TITLE
Crash when activate door

### ISSUE THREAD

**Issue by CookieG77** [CreativeMD/LittleTiles#797]
Recap of what happened:
Me and my friends created a server to have fun however when we interact with a little tile door the server crashes and crashes again when a player joins after a restart. The only way to get back to the server was to remove the mod.

[crash-2021-12-12_17.18.24-server.txt](https://github.com/CreativeMD/LittleTiles/files/7699133/crash-2021-12-12_17.18.24-server.txt)

**Comment by CreativeMD** [comment]
Sorry, but I don't support Magma. Either use SpongeForge or Forge. Mohist might also work.
