### ISSUE TITLE
Door Activator with 2 Sliding Doors Problems

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#798]
Structure: https://pastebin.com/MSKemQ3P

When I want to close this door, which consists of 2 sliding doors and is connected to the door activator, after opening it, the following error occurs: https://gyazo.com/df2b9a3b29319fdbb85a43dc4c46516c

I have also tried Stay Animated and it is always the same.

**Comment by ghost** [comment]
So the error only occurs when I place the door in the Minecraft grid with Shift pressed. Outside the grid there are no problems.

**Comment by CreativeMD** [comment]
It's fixed in the newest version. Thanks for reporting this issue!
