### ISSUE TITLE
LittleTiles blocks invisible

### ISSUE THREAD

**Issue by xdeadshot** [CreativeMD/LittleTiles#80]
I am new to this mod so i don't know much about it but when i place littletiles blocks they appear invisible.
My game, forge and mod version is 1.12.2. Thanks.

**Comment by Dushess** [comment]
Giving 90%, you have outdated mod, taken from some [number]minecraft.net
Can you give full names of both files?

**Comment by Dushess** [comment]
And checksums, if you can get those.

**Comment by CreativeMD** [comment]
As @Dushess already said, please download mods (in general) from curseforge:
https://minecraft.curseforge.com/projects/creativecore
https://minecraft.curseforge.com/projects/littletiles
