### ISSUE TITLE
Missing parent

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#800]
I cannot link several sliding doors. I have created a structure consisting of 2 sliding doors with the door activator. Then I placed this structure on my test lift and made the lift itself a sliding door. 

The result is that I can open the door but after I have operated the lift myself, missing child and missing parent errors occur again.

Here is a pic of the structure: https://gyazo.com/57a8d0c9eace9a2689460e335dd278af

And here is the structure itself: https://pastebin.com/GTMjLW7J

**Comment by CreativeMD** [comment]
Make the elevator stay animated ... I won't fix this issue for 1.12, sorry.
