### ISSUE TITLE
Crashes while trying to place bits.

### ISSUE THREAD

**Issue by Hazard-Hat** [CreativeMD/LittleTiles#803]
I can take bits out, but trying to place the block back down crashes the game.
I only have LittleTiles Optifine and Creative Cor
[crash-2021-12-31_19.25.21-client.txt](https://github.com/CreativeMD/LittleTiles/files/7797250/crash-2021-12-31_19.25.21-client.txt)
e

**Comment by Hazard-Hat** [comment]
Okay, turns out it only crashes on the latest version of this mod, for some reason...

**Comment by Hazard-Hat** [comment]
So I tried going down the version of which ones actually work, and it seems 1.5.34 (and probably under) works, everything above crashes when placing bits down.

Which is odd...
I have installed more mods on 1.12.2, but I don't think any of them are the culprit.

**Comment by Hazard-Hat** [comment]
So I tried going down the version of which ones actually work, and it seems 1.5.34 (and probably under) works, everything above crashes when placing bits down.

Which is odd...
I have installed more mods on 1.12.2, but I don't think any of them are the culprit. (for obvious reasons)

**Comment by ghost** [comment]
Please install the latest Creative Core Version. its 69 you have 68

**Comment by Hazard-Hat** [comment]
> Please install the latest Creative Core Version. its 69 you have 68

It's working now, but I don't know why I had 68...
Anyways thank you, I apologize about making a thread of something I could have easily found out about.
