### ISSUE TITLE
Crash while trying to create LT doors.

### ISSUE THREAD

**Issue by Okeanor** [CreativeMD/LittleTiles#805]
Tried to combine different (most downloaded on curseforge) builds or newest ones, but every time using little blueprint to create doors, minecraft crashes after clicking "save" in little blueprints GUI
[crash-2022-01-09_10.12.48-client.txt](https://github.com/CreativeMD/LittleTiles/files/7834757/crash-2022-01-09_10.12.48-client.txt)
[crash-2022-01-04_14.36.10-client.txt](https://github.com/CreativeMD/LittleTiles/files/7834758/crash-2022-01-04_14.36.10-client.txt)
.

**Comment by kirokadura** [comment]
Both CreativeCore and LittleTiles are outdated. Please use the most recent versions and try again.

[LittleTiles](https://www.curseforge.com/minecraft/mc-mods/littletiles/files/3584330)

[CreativeCore ](https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3537907)

If it still crashes, post the new crash-report here.
