### ISSUE TITLE
Crashing problem again.

### ISSUE THREAD

**Issue by Okeanor** [CreativeMD/LittleTiles#807]
After using newest versions (for 1.12.2) of LittleTiles and CreativeCore, I still have problems when trying to create doors, game still crashes again and again.
[crash-2022-01-10_09.59.06-client.txt](https://github.com/CreativeMD/LittleTiles/files/7837720/crash-2022-01-10_09.59.06-client.txt)

**Comment by CreativeMD** [comment]
Something is wrong. Either the structure you are using is corrupted somehow or there is a mod interfering. Try to create a new door. Otherwise provide a screenshot and explain what exactly you are doing.
