### ISSUE TITLE
Crashing problem with LT doors.

### ISSUE THREAD

**Issue by Okeanor** [CreativeMD/LittleTiles#808]
Again I tried to do something, but I have no idea what to do. Problem is still identical.
![Zrzut ekranu (25)](https://user-images.githubusercontent.com/97383194/149144465-6e4b9176-3700-43a4-a4ba-a33866ee84e6.png)
 As you see on picture, I try to create blueprint for axis doors (in that case, with simple minecraft stone as material)  After clicking "save" game crashes. In any world, even most simple.
[crash-2022-01-12_13.54.24-client.txt](https://github.com/CreativeMD/LittleTiles/files/7854690/crash-2022-01-12_13.54.24-client.txt)
I attach crash report from last trial of making doors.
I hope that is possible to do something.

**Comment by kirokadura** [comment]
Something is off. You selected the Axis Door structure type, but none of the options (Axis, angle, speed, etc) are showing up on the GUI. Can you try reproducing the issue and generating the crash with only LittleTiles and CreativeCore installed? That way we can rule out the possibility of a mod causing it. Remove OptiFine as well.

**Comment by Okeanor** [comment]
[crash-2022-01-12_20.21.29-client.txt](https://github.com/CreativeMD/LittleTiles/files/7857136/crash-2022-01-12_20.21.29-client.txt)
I triggered crash forcefully, cause I could make doors without any problems when only LT and CreativeCore.

**Comment by kirokadura** [comment]
Then I suggest readding the mods in batches until the original crash happens again. Then filter out the mods until you find the culprit.  

Then we can check what compatibility issue is happening.

**Comment by CreativeMD** [comment]
@kirokadura pointed out there is a problem before. Can you please provide the latest.log? Also don't open a new issue every time we respond. You can still comment the old one.

**Comment by Okeanor** [comment]
Here is latest.log and new crash report. This time crash occured when trying to open door configuration - I used modpack used before.
[crash-2022-01-13_11.42.25-client.txt](https://github.com/CreativeMD/LittleTiles/files/7862078/crash-2022-01-13_11.42.25-client.txt)
[latest.log](https://github.com/CreativeMD/LittleTiles/files/7862084/latest.log)

**Comment by CreativeMD** [comment]
You are using the RTM mod, unfortunately it's not compatible with LittleTiles. Either remove LT or the RTM Mod. Sorry, can't help your there.
