### ISSUE TITLE
MCMultipart Support?

### ISSUE THREAD

**Issue by brisingraerowing** [CreativeMD/LittleTiles#81]
Are there plans for MCMultiPart support? I would like to use this to create covers for different cables. I currently use Chisels and Bits for that, but would like to use this mod instead.

**Comment by brisingraerowing** [comment]
Also, are sloped tiles implemented in 1.12.2? I noticed people on reddit using them in builds, and would like to do so as well.

EDIT: Nevermind. I just figured out how to do them. Also, this mod is absolutely awesome!

**Comment by Dushess** [comment]
There is already MCMP support, if i not mixed it up with C&B, going to check.

**Comment by Dushess** [comment]
Idk, what your mods uses MCMP for cables, but manually creating MCMP-block in 1.11.2+ impossible, SimpleCovers latest compatible version is 1.10.2. I can't check.

**Comment by brisingraerowing** [comment]
Mekanism Supports it, but doesn't require it. I can easily use other cables / pipes for now.

**Comment by CreativeMD** [comment]
It would take really long to do so. i think there are other more important things.
