### ISSUE TITLE
LT advanced door bug

### ISSUE THREAD

**Issue by EdgewalkerBlue** [CreativeMD/LittleTiles#813]
Jre1 8 0 331 2022 06 13   15 58 44 02
Minecraft 1.12.2
forge 14.23.5.2860
LittleTiles_v1.5.58
CreativeCore_v1.10.70
![{YDRPFD9UCDK6AGYFQ }O6F](https://user-images.githubusercontent.com/34803152/173360532-bf5d23aa-37b2-4ea9-b253-68a3851703c7.png)
It's a structure like this, an advanced door with a sub advanced door
When the sub-advanced door is not moving, it can be animated normally
After moving the sub-advanced door
The parent level advanced door cannot be moved directly

Here is the BUG video：https://www.youtube.com/watch?v=FNN-B6gjeQI

**Comment by DonK4rma** [comment]
Doors on doors can be very buggy if they have stops to open, if you want to have door on doors you need to follow the same path as you open it

**Comment by CreativeMD** [comment]
Interesting. I thought this issue was fixed ... but looks like it is not. Doors in doors which work independent from each other don't work great. I would avoid it for now, if you really want it make all doors stay animated, that will fix it for now.
