### ISSUE TITLE
The mod is crashing and not wanting to boot

### ISSUE THREAD

**Issue by HittDust** [CreativeMD/LittleTiles#814]
If anyone can please help me to solve the problem of crashing, reply to this comment

And when I try to initialize the mod it ends up giving this:
![imagem_2022-06-30_075609876](https://user-images.githubusercontent.com/108464469/176660690-22f8e9c2-2bc5-4a37-9065-1d47f5a32986.png)

**Comment by CreativeMD** [comment]
Install CreativeCore as well.
