### ISSUE TITLE
Game crashes on f3+a

### ISSUE THREAD

**Issue by TacoRedneck** [CreativeMD/LittleTiles#817]
Title. Game crashes after breaking some LT tiles, but after they stuck around on screen I tried to reload the chunks and the game crashed
[crash-2022-07-21_21.31.31-client.txt](https://github.com/CreativeMD/LittleTiles/files/9163776/crash-2022-07-21_21.31.31-client.txt)

**Comment by TacoRedneck** [comment]
of course it might be a beta forge issue

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting the issue.
