### ISSUE TITLE
My game crashes after using any item of LittleTiles

### ISSUE THREAD

**Issue by G1ll0u** [CreativeMD/LittleTiles#818]
Hello everyone,

As you could read, my game crashes....
the game crashes at the moment I use any item of your mod

Same crash in MP/SP
Here's the [crash report](https://mclo.gs/MCqdewp) :

<details>
  <summary>CRASH REPORT</summary>
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Don't be sad, have a hug! <3

Time: 2022-08-03 23:15:02 CEST
Description: Unexpected error

java.lang.NullPointerException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.creativemd.littletiles.client.render.world.RenderUtils.getRenderChunk(RenderUtils.java:52)
    at com.creativemd.littletiles.client.render.cache.RenderingThread.addCoordToUpdate(RenderingThread.java:103)
    at com.creativemd.littletiles.client.render.world.TileEntityRenderManager.queue(TileEntityRenderManager.java:136)
    at com.creativemd.littletiles.client.render.world.TileEntityRenderManager.tilesChanged(TileEntityRenderManager.java:79)
    at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateTiles(TileEntityLittleTiles.java:266)
    at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateTiles(TileEntityLittleTiles.java:249)
    at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.updateTiles(TileEntityLittleTiles.java:279)
    at com.creativemd.littletiles.common.action.block.LittleActionDestroyBoxes.action(LittleActionDestroyBoxes.java:169)
    at com.creativemd.littletiles.common.action.block.LittleActionDestroyBoxes.action(LittleActionDestroyBoxes.java:199)
    at com.creativemd.littletiles.common.action.block.LittleActionBoxes.action(LittleActionBoxes.java:87)
    at com.creativemd.littletiles.common.action.block.LittleActionDestroyBoxes.action(LittleActionDestroyBoxes.java:211)
    at com.creativemd.littletiles.common.action.LittleAction.execute(LittleAction.java:263)
    at com.creativemd.littletiles.common.item.ItemLittleHammer.onClickBlock(ItemLittleHammer.java:110)
    at com.creativemd.littletiles.common.event.LittleEventHandler.onLeftClick(LittleEventHandler.java:137)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1135_LittleEventHandler_onLeftClick_LeftClickBlock.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1130)
    at net.minecraft.client.multiplayer.PlayerControllerMP.clickBlock(PlayerControllerMP.java:222)
    at net.optifine.override.PlayerControllerOF.clickBlock(PlayerControllerOF.java:49)
    at net.minecraft.client.Minecraft.clickMouse(Minecraft.java:1518)
    at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2249)
    at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2020)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1808)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4614)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['Jubitus'/4876, l='MpServer', x=255.75, y=4.00, z=1039.91]]
  Chunk stats: MultiplayerChunkCache: 519, 519
  Level seed: 0
  Level generator: ID 01 - flat, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (253,4,1039), Chunk: (at 13,0,15 in 15,64; contains blocks 240,0,1024 to 255,255,1039), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
  Level time: 165 game time, 165 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 8 total; [MoCEntityButterfly['ButterFly'/33989, l='MpServer', x=177.50, y=4.00, z=968.50], MoCEntityMaggot['Maggot'/34006, l='MpServer', x=279.49, y=4.00, z=1017.72], MoCEntityMaggot['Maggot'/34007, l='MpServer', x=281.31, y=4.00, z=1017.62], MoCEntityMaggot['Maggot'/34008, l='MpServer', x=280.50, y=4.00, z=1013.50], MoCEntityMaggot['Maggot'/34009, l='MpServer', x=278.50, y=4.00, z=1011.50], EntityPlayerSP['Jubitus'/4876, l='MpServer', x=255.75, y=4.00, z=1039.91], EntityLatchedRenderer['inconnu'/4878, l='MpServer', x=8.50, y=65.00, z=8.50], EntitySlime['Slime'/19294, l='MpServer', x=181.81, y=4.00, z=963.33]]
  Retry entities: 1 total; [EntityLatchedRenderer['inconnu'/4878, l='MpServer', x=8.50, y=65.00, z=8.50]]
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_332, Temurin
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
  Memory: 5976873928 bytes (5699 MB) / 9297199104 bytes (8866 MB) up to 9297199104 bytes (8866 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms9216m -Xmx9216m
  IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
  FML: MCP 9.42 LoliASM 5.6 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G6_pre1 119 mods loaded, 119 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                       | Version                      | Source                                                         | Signature                                |
       |:------ |:------------------------ |:---------------------------- |:-------------------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                | 1.12.2                       | minecraft.jar                                                  | None                                     |
       | LCHIJA | mcp                      | 9.42                         | minecraft.jar                                                  | None                                     |
       | LCHIJA | sampler                  | 1.84                         | sampler-1.84.jar                                               | None                                     |
       | LCHIJA | FML                      | 8.0.99.99                    | forge-1.12.2-14.23.5.2859-universal.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                    | 14.23.5.2859                 | forge-1.12.2-14.23.5.2859-universal.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | creativecoredummy        | 1.0.0                        | minecraft.jar                                                  | None                                     |
       | LCHIJA | itemphysic               | 1.4.0                        | minecraft.jar                                                  | None                                     |
       | LCHIJA | littletilescore          | 1.0.0                        | minecraft.jar                                                  | None                                     |
       | LCHIJA | otgcore                  | 1.12.2-v9.4                  | minecraft.jar                                                  | None                                     |
       | LCHIJA | mixinbooter              | 5.0                          | minecraft.jar                                                  | None                                     |
       | LCHIJA | foamfixcore              | 7.7.4                        | minecraft.jar                                                  | None                                     |
       | LCHIJA | obfuscate                | 0.2.6                        | minecraft.jar                                                  | None                                     |
       | LCHIJA | randompatches            | 1.12.2-1.22.1.7              | randompatches-1.12.2-1.22.1.7.jar                              | None                                     |
       | LCHIJA | customskinloader         | 14.14-SNAPSHOT-323           | CustomSkinLoader_ForgeLegacy-14.14-SNAPSHOT-323.jar            | 52885f395e68f42e9b3b629ba56ecf606f7d4269 |
       | LCHIJA | ageofweapons             | 0.13.5                       | Age+of+Weapons+1.12.2++(v.0.13.5).jar                          | None                                     |
       | LCHIJA | aiimprovements           | 0.0.1.3                      | AIImprovements-1.12-0.0.1b3.jar                                | None                                     |
       | LCHIJA | akashictome              | 1.2-12                       | AkashicTome-1.2-12.jar                                         | None                                     |
       | LCHIJA | codechickenlib           | 3.2.3.358                    | CodeChickenLib-1.12.2-3.2.3.358-universal.jar                  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | ancientwarfare           | 1.12.2-2.7.0.772             | ancientwarfare-1.12.2-2.7.0.772.jar                            | None                                     |
       | LCHIJA | ancientwarfarestructure  | 1.12.2-2.7.0.772             | ancientwarfare-1.12.2-2.7.0.772.jar                            | None                                     |
       | LCHIJA | ancientwarfarevehicle    | 1.12.2-2.7.0.772             | ancientwarfare-1.12.2-2.7.0.772.jar                            | None                                     |
       | LCHIJA | ancientwarfarenpc        | 1.12.2-2.7.0.772             | ancientwarfare-1.12.2-2.7.0.772.jar                            | None                                     |
       | LCHIJA | buildcraftlib            | 7.99.24.8                    | buildcraft-all-7.99.24.8.jar                                   | None                                     |
       | LCHIJA | buildcraftcore           | 7.99.24.8                    | buildcraft-all-7.99.24.8.jar                                   | None                                     |
       | LCHIJA | ancientwarfareautomation | 1.12.2-2.7.0.772             | ancientwarfare-1.12.2-2.7.0.772.jar                            | None                                     |
       | LCHIJA | applecore                | 3.2.0                        | AppleCore-mc1.12.2-3.2.0.jar                                   | None                                     |
       | LCHIJA | jei                      | 4.16.1.302                   | jei_1.12.2-4.16.1.302.jar                                      | None                                     |
       | LCHIJA | appleskin                | 1.0.9                        | AppleSkin-mc1.12-1.0.9.jar                                     | None                                     |
       | LCHIJA | betteranimals            | 5.3.0                        | betteranimals-1.12.2-5.3.0.jar                                 | None                                     |
       | LCHIJA | quark                    | r1.6-179                     | Quark-r1.6-179.jar                                             | None                                     |
       | LCHIJA | autoreglib               | 1.3-32                       | AutoRegLib-1.3-32.jar                                          | None                                     |
       | LCHIJA | ichunutil                | 7.2.2                        | iChunUtil-1.12.2-7.2.2.jar                                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | backtools                | 7.0.1                        | BackTools-1.12.2-7.0.1.jar                                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | backups                  | 1.5.7                        | Backups-1.12.2-1.5.7.jar                                       | None                                     |
       | LCHIJA | badmobs                  | 1.1.40                       | BadMobs-1.12.2-1.1.40.jar                                      | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | base                     | 3.13.0                       | base-1.12.2-3.13.0.jar                                         | None                                     |
       | LCHIJA | betterthirdperson        | 1.8.1                        | BetterThirdPerson-Forge-1.12.2-1.8.1.jar                       | None                                     |
       | LCHIJA | openterraingenerator     | v9.4                         | OpenTerrainGenerator-1.12.2-v9.4.jar                           | None                                     |
       | LCHIJA | biomebundle              | 5.1                          | Biome_Bundle-1.12.2-v6.1.jar                                   | None                                     |
       | LCHIJA | blockcraftery            | 1.12.2-1.3.1                 | blockcraftery-1.12.2-1.3.1.jar                                 | None                                     |
       | LCHIJA | buildcraftbuilders       | 7.99.24.8                    | buildcraft-all-7.99.24.8.jar                                   | None                                     |
       | LCHIJA | buildcrafttransport      | 7.99.24.8                    | buildcraft-all-7.99.24.8.jar                                   | None                                     |
       | LCHIJA | buildcraftsilicon        | 7.99.24.8                    | buildcraft-all-7.99.24.8.jar                                   | None                                     |
       | LCHIJA | buildcraftcompat         | 7.99.24.8                    | buildcraft-all-7.99.24.8.jar                                   | None                                     |
       | LCHIJA | buildcraftenergy         | 7.99.24.8                    | buildcraft-all-7.99.24.8.jar                                   | None                                     |
       | LCHIJA | buildcraftfactory        | 7.99.24.8                    | buildcraft-all-7.99.24.8.jar                                   | None                                     |
       | LCHIJA | buildcraftrobotics       | 7.99.24.8                    | buildcraft-all-7.99.24.8.jar                                   | None                                     |
       | LCHIJA | campfire                 | 1.2                          | campfire-1.12-v1.2.jar                                         | None                                     |
       | LCHIJA | cfm                      | 6.3.0                        | cfm-6.3.0-mc1.12.2.jar                                         | None                                     |
       | LCHIJA | chameleon                | 1.12-4.1.3                   | Chameleon-1.12-4.1.3.jar                                       | None                                     |
       | LCHIJA | charm                    | 1.12.2-1.3.7                 | Charm-1.12.2-1.3.7.jar                                         | None                                     |
       | LCHIJA | chickenchunks            | 2.4.2.74                     | ChickenChunks-1.12.2-2.4.2.74-universal.jar                    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | chiselsandbits           | 14.33                        | chiselsandbits-14.33.jar                                       | None                                     |
       | LCHIJA | clumps                   | 3.1.2                        | Clumps-3.1.2.jar                                               | None                                     |
       | LCHIJA | comforts                 | 1.4.1.3                      | comforts-1.12.2-1.4.1.3.jar                                    | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | configmod                | v1.0                         | coroutil-1.12.1-1.2.35.jar                                     | None                                     |
       | LCHIJA | extendedrenderer         | v1.0                         | coroutil-1.12.1-1.2.35.jar                                     | None                                     |
       | LCHIJA | coroutil                 | 1.12.1-1.2.35                | coroutil-1.12.1-1.2.35.jar                                     | None                                     |
       | LCHIJA | corpse                   | 1.12.2-1.0.8                 | corpse-1.12.2-1.0.8.jar                                        | None                                     |
       | LCHIJA | creativecore             | 1.10.0                       | CreativeCore_v1.10.70_mc1.12.2.jar                             | None                                     |
       | LCHIJA | customloadingscreen      | 1.12.2-1.5.7                 | CustomLoadingScreen-1.12.2-1.5.7.jar                           | None                                     |
       | LCHIJA | customspawner            | 3.11.4                       | CustomMobSpawner-3.11.4.jar                                    | None                                     |
       | LCHIJA | ptrmodellib              | 1.0.5                        | PTRLib-1.0.5.jar                                               | None                                     |
       | LCHIJA | props                    | 2.6.3.7                      | Decocraft-2.6.3.7_1.12.2.jar                                   | None                                     |
       | LCHIJA | doggytalents             | 1.15.1.5                     | DoggyTalents-1.12.2-1.15.1.5.jar                               | None                                     |
       | LCHIJA | mocreatures              | 12.0.5                       | DrZharks Mocreatures Mod-12.0.5.jar                            | None                                     |
       | LCHIJA | entityculling            | 6.0.2                        | EntityCulling-1.12.2-6.0.2.jar                                 | None                                     |
       | LCHIJA | epicfight                | 1.12.2-2.2.8                 | EpicFightMod-1.12.2-2.2.8.jar                                  | None                                     |
       | LCHIJA | extrabitmanipulation     | 1.12.2-3.4.1                 | ExtraBitManipulation-1.12.2-3.4.1.jar                          | None                                     |
       | LCHIJA | falling_tree             | 2.4.0                        | FallingTree-1.12.2-2.4.0.jar                                   | None                                     |
       | LCHIJA | foamfix                  | 0.10.14-1.12.2               | foamfix-0.10.14-1.12.2.jar                                     | None                                     |
       | LCHIJA | forgelin                 | 1.8.4                        | Forgelin-1.8.4.jar                                             | None                                     |
       | LCHIJA | futuremc                 | 0.2.6                        | future-mc-0.2.10.jar                                           | None                                     |
       | LCHIJA | grapplemod               | 1.12.2-v12.3                 | grapplemod-1.12.2-v12.3.jar                                    | None                                     |
       | LCHIJA | guardscraft              | 1.0.5                        | guardscraft-1.12.2-1.0.5.jar                                   | None                                     |
       | LCHIJA | hw_inv                   | 1.12.1-1.1.13                | hostileworlds_invasions-1.12.1-1.1.13.jar                      | None                                     |
       | LCHIJA | waila                    | 1.8.26                       | Hwyla-1.8.26-B41_1.12.2.jar                                    | None                                     |
       | LCHIJA | llibrary                 | 1.7.20                       | llibrary-1.7.20-1.12.2.jar                                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | iceandfire               | 1.9.1                        | iceandfire-1.9.1-1.12.2.jar                                    | None                                     |
       | LCHIJA | incontrol                | 3.9.18                       | incontrol-1.12-3.9.18.jar                                      | None                                     |
       | LCHIJA | jeiintegration           | 1.6.0                        | jeiintegration_1.12.2-1.6.0.jar                                | None                                     |
       | LCHIJA | journeymap               | 1.12.2-5.7.1                 | journeymap-1.12.2-5.7.1.jar                                    | None                                     |
       | LCHIJA | littletiles              | 1.5.0                        | LittleTiles_v1.5.58_mc1.12.2.jar                               | None                                     |
       | LCHIJA | spark                    | 1.5.2                        | spark-forge1122.jar                                            | None                                     |
       | LCHIJA | loliasm                  | 5.6                          | loliasm-5.6.jar                                                | None                                     |
       | LCHIJA | mcwdoors                 | 1.3                          | mcw-doors-1.0.3-mc1.12.2.jar                                   | None                                     |
       | LCHIJA | mcwfences                | 1.0.0                        | mcw-fences-1.0.0-mc1.12.2.jar                                  | None                                     |
       | LCHIJA | mcwfurnitures            | 1.0.1                        | mcw-furniture-1.0.1-mc1.12.2beta.jar                           | None                                     |
       | LCHIJA | mcwroofs                 | 1.0.1                        | mcw-roofs-1.0.1-mc1.12.2.jar                                   | None                                     |
       | LCHIJA | mcwtrpdoors              | 1.0.2                        | mcw-trapdoors-1.0.2-mc1.12.2.jar                               | None                                     |
       | LCHIJA | mcwwindows               | 1.0                          | mcw-windows-1.0.0-mc1.12.2.jar                                 | None                                     |
       | LCHIJA | millenaire               | Millénaire 8.1.2             | millenaire-8.1.2.jar                                           | None                                     |
       | LCHIJA | modnametooltip           | 1.10.1                       | modnametooltip_1.12.2-1.10.1.jar                               | None                                     |
       | LCHIJA | guilib                   | $version                     | morepaintings-paintings-1.12.2-5.0.1.2.jar                     | None                                     |
       | LCHIJA | paintingselgui           | $version                     | morepaintings-paintings-1.12.2-5.0.1.2.jar                     | None                                     |
       | LCHIJA | morepaintings            | $version                     | morepaintings-paintings-1.12.2-5.0.1.2.jar                     | None                                     |
       | LCHIJA | mousetweaks              | 2.10                         | MouseTweaks-2.10-mc1.12.2.jar                                  | None                                     |
       | LCHIJA | mowziesmobs              | 1.5.8                        | mowziesmobs-1.5.8(1).jar                                       | None                                     |
       | LCHIJA | nmsot                    | 1.2.2-mc1.12.2               | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar                        | None                                     |
       | LCHIJA | renderlib                | 1.1.1                        | RenderLib-1.12.2-1.1.1.jar                                     | None                                     |
       | LCHIJA | nothirium                | 0.1.7-beta                   | Nothirium-1.12.2-0.1.7-beta.jar                                | None                                     |
       | LCHIJA | particleculling          | v1.3                         | particleculling-1.12.2-v1.3.1.jar                              | None                                     |
       | LCHIJA | performant               | 1.12.2-1.5                   | performant-1.11.jar                                            | None                                     |
       | LCHIJA | placeableitems           | 3.3                          | placeableitems-3.3.jar                                         | None                                     |
       | LCHIJA | randomtweaks             | 1.12.2-2.8.3.1               | randomtweaks-1.12.2-2.8.3.1.jar                                | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
       | LCHIJA | roost                    | 2.0.10                       | roost-1.12.2-2.0.10.jar                                        | None                                     |
       | LCHIJA | rustic                   | 1.1.4                        | rustic-1.1.4.jar                                               | None                                     |
       | LCHIJA | sekcphysics              | 0.1.0                        | sekcphysics-0.1.0.jar                                          | None                                     |
       | LCHIJA | soundfilters             | 0.12.1_for_1.12              | SoundFilters-0.12.1_for_1.12.jar                               | None                                     |
       | LCHIJA | storagedrawers           | 5.2.2                        | StorageDrawers-1.12.2-5.4.2.jar                                | None                                     |
       | LCHIJA | stupidthings             | 1.1.5                        | Stupid+Things-1.12.X-1.1.5.jar                                 | None                                     |
       | LCHIJA | torchslabmod             | v1.5.2                       | torchslabmod-1.12.2-v1.5.2.jar                                 | None                                     |
       | LCHIJA | vanillavistas            | 1.0                          | Vanilla_Vistas+1.1.jar                                         | None                                     |
       | LCHIJA | wearablebackpacks        | 3.1.4                        | WearableBackpacks-1.12.2-3.1.4.jar                             | None                                     |
       | LCHIJA | worldedit                | 6.1.8                        | worldedit-forge-mc1.12-6.1.8-dist.jar                          | None                                     |
       | LCHIJA | worldeditcuife2          | 2.1.2-mf-1.12.2-14.23.5.2768 | WorldEdit+CUI+Forge+Edition+2-2.1.2-mf-1.12.2-14.23.5.2768.jar | None                                     |
       | LCHIJA | worldutils               | 0.4.2                        | worldutils-1.12.2-0.4.2.jar                                    | 2b03e1423915a189b8094816baa18f239d576dff |
       | LCHIJA | phosphor-lighting        | 1.12.2-0.2.7                 | phosphor-forge-mc1.12.2-0.2.7-universal.jar                    | None                                     |
       | LCHIJA | mysticallib              | 1.12.2-1.3.7                 | mysticallib-1.12.2-1.3.7.jar                                   | None                                     |
  Loaded coremods (and transformers): AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.3.1.jar)
                                        
                                      CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
                                        
                                      ItemPatchingLoader (ItemPhysic_Full_1.4.37_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.excluded.OTGClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
                                        
                                      ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      iceandfire (iceandfire-1.9.1-1.12.2.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      ClsPlugin (CustomLoadingScreen-1.12.2-1.5.7.jar)
                                        alexiil.mc.mod.load.coremod.ClsTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      CharmLoadingPlugin (Charm-1.12.2-1.3.7.jar)
                                        svenhjol.charm.base.CharmClassTransformer
                                      RenderLibPlugin (RenderLib-1.12.2-1.1.1.jar)
                                        meldexun.renderlib.asm.RenderLibClassTransformer
                                      LittlePatchingLoader (LittleTiles_v1.5.58_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      RandomPatches (randompatches-1.12.2-1.22.1.7.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      MixinBooter (!mixinbooter-5.0.jar)
                                        
                                      LoliASM (loliasm-5.6.jar)
                                        
                                      EntityCullingPlugin (EntityCulling-1.12.2-6.0.2.jar)
                                        meldexun.entityculling.asm.EntityCullingClassTransformer
                                      NothiriumPlugin (Nothirium-1.12.2-0.1.7-beta.jar)
                                        meldexun.nothirium.mc.asm.NothiriumClassTransformer
                                      FutureMC (future-mc-0.2.10.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
                                      CustomSkinLoader (CustomSkinLoader_ForgeLegacy-14.14-SNAPSHOT-323.jar)
                                        customskinloader.forge.loader.LaunchWrapper
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 516.59' Renderer: 'NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2'
  Suspected Mods: LittleTiles (littletiles), Forge Mod Loader (FML), Minecraft Forge (forge)
  Launched Version: 1.12.2
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 516.59, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: millenaire-shields-128x128.zip, millenaire-hd-1.0.3.zip, Conquest+Reforged+RP.zip, Conquest_1.12 - Copie (2).zip
  Current Language: Français (France)
  Profiler Position: N/A (disabled)
  CPU: 24x AMD Ryzen 9 3900X 12-Core Processor
  Client Crashes Since Restart: 2
  Integrated Server Crashes Since Restart: 0

</details>

I think a mod is incompatible but I dont find any of mine in incompatibilities list found here :
[https://github.com/CreativeMD/LittleTiles/wiki/Mod-Compatibility](https://github.com/CreativeMD/LittleTiles/wiki/Mod-Compatibility)

Have a nice day my frienbs !

**EDIT:**

<details>
  <summary>Off-topic, just a question</summary>

I test this mod for replacing C&B because I think i have performance issues with C&B.
My entire village is made with C&B bits can I convert it to LittleTiles with the blueprint without too much problems ?
Because someone on your discord told me that it is possible and that there is no size limit. But what if it's a whole village ?
</details>

**Comment by Doc-1** [comment]
Try to remove Nothrium, someone else in the Discord channel found that to be their issue.

**Comment by CreativeMD** [comment]
About your off-topic question. As you can use the blueprint and it can be quite big. I recommend to backup the world first. Maybe can also split it into smaller parts.

**Comment by G1ll0u** [comment]
@Doc-1 For the above problem, I quickly disabled some mods and it worked. I'll reactivate it one by one to see if Nothirium causes problems.

I'll give an answer another day, I'm too busy at this moment.

If the problem is related to Nothirium will I have to submit a ticket to the mod owner ?

@CreativeMD I DID IT !
I had to restore many backups but I successfully replaced my ENTIRE village from C&B to LittleTiles with the Blueprint. It was really hard to do, it was awfully lagging but it worked.

I just had to be precise on the edge of the razor when placing the blueprint.

I think that adding something to convert a large amount of C&B should be a good idea, no? A command like `/littletiles convertCB x y z x' y' z'` I don't know if this is feasible from a developer's point of view but it could be a good idea.

![2022-08-09_22 49 50](https://user-images.githubusercontent.com/36129824/183758280-3f2b7bd4-011d-4311-8ec7-a9b2ea532ae2.png)
![2022-08-09_22 50 02](https://user-images.githubusercontent.com/36129824/183758303-6938676e-a8ca-4179-9df4-e2c325c6de90.png)
![2022-08-09_22 57 09](https://user-images.githubusercontent.com/36129824/183760005-ad440566-0527-4303-a1af-3e82871ee37a.png)

Every paths of my village are chiseled blocks. every houses contains chiseled blocks. I'm surprised it worked so well !


Thanks for everything my frienbs.



Jubitus

**Comment by CreativeMD** [comment]
> If the problem is related to Nothirium will I have to submit a ticket to the mod owner ?

No that is not necessary. LittleTiles would need a change, but I have dropped support for 1.12. So this issue won't be fixed, sorry.


> I think that adding something to convert a large amount of C&B should be a good idea, no? A command like `/littletiles convertCB x y z x' y' z'` I don't know if this is feasible from a developer's point of view but it could be a good idea.

I have create a version of LT which converts all blocks from C&B to LT ones once they are loaded, but it's a bit outdated. A command would only work if the area is loaded. I will think about it.

**Comment by G1ll0u** [comment]
The problem was indeed Nothirium. However, on the server side, I left Nothirium by mistake and I was able to connect without Nothirium installed on my client and littletiles seems to work perfectly.

I don't think this is the right place to ask the question, I already asked it somewhere but I don't remember if someone answered.
Don't feel obliged to answer :

I have a 1.12.2 private server that I created in 2018.
I plan to upgrade it to 1.13+ but as you know, there's a big problem called ["1.13 flattening"](https://minecraft.fandom.com/wiki/Java_Edition_1.13/Flattening) 😭 

When LittleTiles 1.13+ will be released, will it be possible to keep the littletiles of a 1.12 world ?


Have a nice day.

**Comment by CreativeMD** [comment]
@G1ll0u sorry for not responding earlier. This is an issue for LittleTiles and I still got no idea how to fix it (I have not looked at it yet), but I will definitely try to. In worst case you will have to export the structures and import in the new version again. I hope I can figure out a way to convert the entire world, but not sure how plausible this is. I first need to readd all the features, before I can think about the world issue. I will post some news about it on my discord once I get to it.
