### ISSUE TITLE
[1.12.2] [pre94] Weird chair behavior on non-standard floor height

### ISSUE THREAD

**Issue by kirokadura** [CreativeMD/LittleTiles#82]
Creative Core:1.9.22
Little Tiles: 1.5.0 pre94
Forge:14.23.0.2515

When placing a Chair type structure on a non standard (default minecraft) height block, your location when sitting will be below the chair (you'll be basically sitting on the floor). It only happens between the tile heights of 5 and 15.

To illustrate:

![2018-03-29_17 22 24](https://user-images.githubusercontent.com/29471180/38111777-56a1aac4-3376-11e8-864d-b37e1d6e7eb6.png)

The first two work fine as they are between 1 and 4 height:

![2018-03-29_17 22 49](https://user-images.githubusercontent.com/29471180/38111907-bd08cad6-3376-11e8-8b2f-667e093aae57.png)

The other two don't work as intended:

![2018-03-29_17 23 03](https://user-images.githubusercontent.com/29471180/38111940-d0f53d90-3376-11e8-9fa0-181104a148bf.png)

That red line in the middle is the red part of the chair. I can't take a third person picture because it's just a closeup of Steve's head.

P.S.: This was tested with 16 grid structures. I don't know if it happens on 32 grid or higher.

**Comment by Dushess** [comment]
Seems to be mod trying to mount Steve on chair inside starter block. (Where chair model bottom layer is located)

**Comment by CreativeMD** [comment]
Thanks for reporting this issue, will be fixed in 1.5.0pre95 (should be available soon).
