### ISSUE TITLE
Invisible frame not updating

### ISSUE THREAD

**Issue by Mustached-Man** [CreativeMD/LittleTiles#823]
When disabling "visible frame" and saving the image, the frame is still visible until you update it with a block.
![update](https://user-images.githubusercontent.com/49171078/185773395-c20c3340-803f-46b3-b7cb-1e939330c876.gif)

**Comment by CreativeMD** [comment]
It's an issue of LittleFrames and I have already abandoned 1.12 some time ago. Sorry, this issue won't be fixed.

**Comment by Mustached-Man** [comment]
Ah ok, no worries then.
