### ISSUE TITLE
Crash when placing line

### ISSUE THREAD

**Issue by Chryfi** [CreativeMD/LittleTiles#826]
[crash-2022-09-18_20.00.04-client.txt](https://github.com/CreativeMD/LittleTiles/files/9594944/crash-2022-09-18_20.00.04-client.txt)
When placing a line it crashes. I dont know if it also crashes with other special modes.

**Comment by CreativeMD** [comment]
Your CreativeCore version is out of date. Update it and everything should work just fine.
