### ISSUE TITLE
Door incompatibility with Terra Plusplus

### ISSUE THREAD

**Issue by Potsukin** [CreativeMD/LittleTiles#827]
terraplusplus-1.1.0.619-1.12.2
CubicChunks-1.12.2-0.0.1249.0-SNAPSHOT-all
CubicWorldGen-1.12.2-0.0.169.0-SNAPSHOT-all
LittleTiles_v1.5.58_mc1.12.2
CreativeCore_v1.10.70_mc1.12.2

LittleTiles door not working properly in Terra PlusPlus world.

**Comment by CreativeMD** [comment]
Doors only work within the vanilla block height limits from 0 to 255. Maybe you are too high?

**Comment by Potsukin** [comment]
No, it won't work properly below that altitude.

**Comment by CreativeMD** [comment]
Is there an error? A message? Something in the log?

**Comment by Potsukin** [comment]
I've confirmed that at altitudes above 256, I get a message saying Door can't move and it doesn't move slightly, but at lower altitudes, the door flies around in the air and becomes uncontrollable.

**Comment by CreativeMD** [comment]
Ok? Any other mods installed?

**Comment by Potsukin** [comment]
Ambient Sounds,Journey Map, customdisc, ALET, CWGFarPlaneView-0.4.0, JEI, It3dimporter, Optifine, worldedit

**Comment by CreativeMD** [comment]
I only now the weird door issue from Valkyrien Warfare. None the mods you use look suspicious. Maybe make a short video showing how it moves?

**Comment by Potsukin** [comment]
Now making a video

**Comment by Potsukin** [comment]
https://www.youtube.com/watch?v=jOKp_CFbkWE

**Comment by CreativeMD** [comment]
Is there anything in the log file when you right click the door?

**Comment by CreativeMD** [comment]
Have you tried it without terraplusplus installed?

**Comment by Potsukin** [comment]
I just tested it and it seems to work fine if only CubicChunk is used, since Malisis Core was needed to create Cubic World, I installed it on Terra PlusPlus and checked again, but the same bug occurred. From these results it appears there is a problem with Terra PlusPlus.

Is log in the log folder? I have debug, latest, "date".log and debug-"number".log in the folder, which one is it?

**Comment by CreativeMD** [comment]
latest.log should work as long as you reproduced this issue the last time it happened. But to be honest I doubt that there is something in the logs folder. I have no idea what the Terra PlusPlus mod does. Maybe contact them? I don't see a way to fix it from my end.

**Comment by Potsukin** [comment]
[latest.log](https://github.com/CreativeMD/LittleTiles/files/9620378/latest.log)

**Comment by Potsukin** [comment]
https://github.com/BuildTheEarth/terraplusplus

**Comment by CreativeMD** [comment]
I will close this issue as it cannot be fixed. Very sorry :|
