### ISSUE TITLE
[Suggestion] Emissive bit

### ISSUE THREAD

**Issue by olegikoligik** [CreativeMD/LittleTiles#83]
May you add the block which won't radiate light, but itself will be shines (only texture) and which will work with bits?
P.S. On animation the block the texture of which shines thanks to optifine (texture with the termination _e)
![javaw 2018-04-01 17-36-22-975_1](https://user-images.githubusercontent.com/22132987/38175328-b6a0c670-35e3-11e8-8107-73fdb57eab9f.gif)

**Comment by Dushess** [comment]
I talked to him about this (as part of suggested lamp light simulation), likely it will be implemented.
First we need to wait redstone update, lamps should be part of it.

**Comment by ghost** [comment]
When I suggested that on mc forums, he said that it would take too much time/too hoard to implement (that it doesnt worth it).

**Comment by CreativeMD** [comment]
I'm on it, just as a reminder this doesn't have anything to do with a glow effect or similar stuff. This is just about an additional color scheme added to the texture.

**Comment by Dushess** [comment]
Creative, i wrote this inaccurate and now it's more correct.

**Comment by CreativeMD** [comment]
Looks like this will be supported in the upcoming pre-release.

**Comment by CreativeMD** [comment]
You still need to test it, but it should work with the pre-pre-release on my discord server.
