### ISSUE TITLE
Blocks disappeared after updating LT and CC

### ISSUE THREAD

**Issue by Sintokii** [CreativeMD/LittleTiles#830]
After updating Little Tiles and Creative Core, a ton of custom blocks disappeared. I've tried relogging, and reloading chunks, neither have worked. Can't break them, can't walk through _or_ on them. Wrench doesn't work either. Reverting to the versions I was using before, LT 1.5.2 & CC 1.10.55, fixes the issue. What gives? I can't use this old version of LT anymore, as it is so buggy when it comes to custom doors (usually causing both client and server crashes upon closing them) that it's unusable. Any help would be greatly appreciated.

![2022-09-27_03 56 09](https://user-images.githubusercontent.com/48268846/192471664-388cb781-d0e3-4eca-a8ef-265c2648f3a4.png)
![2022-09-27_04 01 16](https://user-images.githubusercontent.com/48268846/192471667-dc0e71bd-f370-4657-a00b-09697b4ef108.png)
![2022-09-27_04 01 58](https://user-images.githubusercontent.com/48268846/192471671-39197184-1b3f-4f28-8432-c5e3e99a8646.png)

I don't know if this will make a difference, but here's my mods list.

- AutoRegLib-1.3-32
- BetterFps-1.4.8
- blockbuster-2.5-1.12.2
- camera-1.0.10
- cfm-6.3.0-mc1.12.2
- chiselsandbits-14.33
- CMDCam_v1.4.12_mc1.12.2
- CreativeCore_v1.10.70_mc1.12.2
- CustomNPCs_1.12.2-(05Jul20)
- Decocraft-2.6.3.7_1.12.2
- ExtraBitManipulation-1.12.2-3.4.1
- flatcoloredblocks-mc1.12-6.8
- FullscreenWindowed-1.12-1.6.0
- ItemPhysic_Full_1.4.34_mc1.12.2
- jei_1.12.2-4.16.1.301
- LittleTiles_v1.5.61_mc1.12.2
- malisiscore-1.12.2-6.5.1
- malisisdoors-1.12.2-7.3.0
- mclib-2.4-1.12.2
- metamorph-1.3-1.12.2
- mod_voxelMap_1.7.1_for_1.12.2
- MorePlayerModels_1.12.2-(05Dec19)
- OnlinePicFrame_v1.5.0-pre1_mc1.12.2
- OptiFine_1.12.2_HD_U_G5
- pa1.11
- Pam's+HarvestCraft+1.12.2zg
- PTRLib-1.0.5
- Quark-r1.6-179
- Tails-1.12-1.10.0
- worldedit-forge-mc1.12.2-6.1.10-dist

**Comment by CreativeMD** [comment]
These blocks are literally gone. Maybe you removed another mod? In theory this should have nothing to do with LittleTiles.

**Comment by Sintokii** [comment]
The only thing I changed was updating Little Tiles and Creative Core. Nothing else has been changed at all. Again, going back to the previous versions I was using before brings them back. I don't think they're gone; it's like they're not loaded. Like I said, I can't walk on or through them, exactly how you try to walk on an unloaded chunk and your character just bobs in place until the chunk is loaded. The blocks that are missing are the same ones I used for the rest of the red carpet, so if I had removed something, _all_ of the red carpet would be gone, not just several parts of it, no?

Here's a screenshot where the outline of the missing block is visible
![2022-09-28_06 06 01](https://user-images.githubusercontent.com/48268846/192752112-3a345633-a09f-43c2-8b95-a20546e6ec8f.png)

**Comment by Sintokii** [comment]
I wouldn't mind replacing all the blocks, but I can't even do that. After replacing them and reloading the world, it all goes missing again in the same places.

**Comment by CreativeMD** [comment]
I see. Maybe these blocks have a specific color? What happens if you use the middle mouse click on them? You could also try to pick the block using the chisel. Maybe the alpha is set to 0

**Comment by Sintokii** [comment]
Weird. So, highlighting the blocks with the chisel causes the outlines to disappear, but they still have the same properties when I try to walk onto or through them. Middle clicking on a block with nothing equipped however doesn't result in anything. If I had to guess, I'm thinking this problem is happening solely after updating CreativeCore, as the same thing is happening with another mod I have that uses CC.

Also, I really appreciate you trying to help. I'm sure it's frustrating to deal with such a weird issue.

**Comment by CreativeMD** [comment]
If the anything in the logs? Maybe you can send me the works so i can test some stuff myself?

**Comment by Sintokii** [comment]
The world size is rather large at 476 mb. Is that okay with you? Unless you have all of the mods I'm using for this world, I'm not sure exactly how it'll work out. 

I'm almost 100% the problem is caused by updating CreativeCore, because using the new version of LittleTiles with the old version of CreativeCore works fine (apart from crashing when trying to build using LT for obvious reasons,) but switching to the new updated version of CreativeCore brings the issue back.

Here's the log. 
https://pastebin.com/iV7GJ3Ah

**Comment by CreativeMD** [comment]
Ok there is definitely something wrong here. There is an error in the update tileentity packet. Can you redownload the newest version of CreativeCore and LittleTiles from curseforge? Something seems to be corrupted for some reason.

**Comment by Sintokii** [comment]
Just tried again with the new files but still nothing. Could something have corrupted in the world's files? Also, I could record a video of how the blocks behave in-game. I don't know if that would help, but I'm running out of ideas. Let me know if there's anything else I could send to help figure things out.

**Comment by CreativeMD** [comment]
Probably be best to upload the world file somewhere and post the link.

**Comment by Sintokii** [comment]
Here's the world. Here are the coords for where it's mainly happening: '1132 78 10', although, it is happening almost everywhere I've used LT. I'm sorry that you might have to go and get the mods that I mentioned before. I really appreciate all of this. https://drive.google.com/file/d/1sRGRvl5QhSbQL5Zj5sn_HqhpkevGmXH6/view?usp=sharing

**Comment by Sintokii** [comment]
I FIXED IT!!! The problem is being caused by the Online Picture Frame mod! Now that I think of it, of course, because it's the abandoned version and I'm using it with the updated version of Creative Core! I'm so happy right now. I'm also so thankful for your help! THANK YOU for being so patient and trying to help me fix this silly issue. Is there any way I can support you, like a Ko-fi or Patreon?

**Comment by CreativeMD** [comment]
Great! Love to hear it is fixed. Haven't done anything ... glad you could figure it out yourself. Had no time to look at your world yet. I have patreon you can find it on a curseforge page of any of my projects.

Really hope things work from here on. Feel free to join our discord server and share some stuff.
