### ISSUE TITLE
Messages - Multiline Support?

### ISSUE THREAD

**Issue by toastonrye** [CreativeMD/LittleTiles#832]
Are multiline messages possible? I realize this is for an old version of Minecraft, just wondering if I missed something.

Playing the Nomifactory modpack for 1.12.2
LittleTilesCore 1.0.0
LittleTiles 1.5.0

I have a short video clip, highlighting why I'm interested. Thanks,
https://youtu.be/j3vNw7XAzz8?t=86

**Comment by CreativeMD** [comment]
To be honest I don't think so. Maybe try to add an \n and see if that causes a linebreak. Besides that I will add it to my todo list for 1.19.
