### ISSUE TITLE
Add required files for 1.12.2

### ISSUE THREAD

**Issue by Desoroxxx** [CreativeMD/LittleTiles#833]
On the 1.19 branch there is all the required files for doing PR's and actually helping the project, could you add the same files for 1.12.2 here is a list:

- build.gradle
- gradle.properties
- gradlew
- gradlew.bat
- .gitignore

And the gradle/wrapper folder and its content.

Just remove it from your .gitignore and push.

**Comment by CreativeMD** [comment]
Unfortunately that does not work. I have reworked my entire setup for 1.19. The setup for 1.12 is quite bad and does not work like that. There is a video of how the workspace is setup: https://www.youtube.com/watch?v=7Ahshi_QjM4
