### ISSUE TITLE
crash with forge 2642 and up

### ISSUE THREAD

**Issue by collwee** [CreativeMD/LittleTiles#84]
with forge 2642 and up if little tiles is present i get this crash https://paste.ee/p/LT53P

**Comment by CreativeMD** [comment]
I tested it using forge 2654 and it works just fine, looks like it's an incompatibility with another mod? Can you try to figure out which mod is causing the problem?

**Comment by collwee** [comment]
hum strange its not happening anymore yesterday it was crashing whit forge 2642 and above when littletiles was present and now i try again and its not happening anymore and i did not change anything.


really minecraft modding can be strange sometime.

**Comment by CreativeMD** [comment]
Ok, that's weird, just reopen this issue if it happens again.
