### ISSUE TITLE
Little hammer doesn't work with CustomSelectionBox mod

### ISSUE THREAD

**Issue by steve12621** [CreativeMD/LittleTiles#841]
It cause the hammer fail to do anything to the block, but surprisingly the little screwdriver still works fine
1.12.2 Forge 14.23.5.2860
LittleTiles 1.5.64
CustomSelectionBox 1.4.6

**Comment by CreativeMD** [comment]
I don't see a way to make it compatible. Sorry. You will not be able to use both mods at the same time.
