### ISSUE TITLE
how do I set up the control panel? the c button does not work.

### ISSUE THREAD

**Issue by andreishego** [CreativeMD/LittleTiles#842]
I installed a lot of mods on minecraft, but when I installed the Little Tikes mod, I couldn't configure the tools because the c button doesn't work, and I wanted to configure my buttons, but I didn't find such a feature.

![image](https://user-images.githubusercontent.com/94469887/207065398-5d19a88a-b325-4bbb-b425-e675ced1c1a7.png)

**Comment by CreativeMD** [comment]
You need to go to controls and set a new key for the keybind.
