### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by ProTapGames** [CreativeMD/LittleTiles#843]
I have a error every time I used the little tiles mod for minecraft java, it never loads properly and gives a error or crashes
using vanilla fix it doesn't crash but gives a error, may I have help? thx

**Comment by Desoroxxx** [comment]
Do you have creative core installed?

**Comment by ProTapGames** [comment]
Yes I do have creative core installed

**Comment by Desoroxxx** [comment]
Could you upload a crash report or a log

**Comment by CreativeMD** [comment]
The crash-report can be found inside the minecraft folder.

**Comment by ProTapGames** [comment]
I just got a new pc, now it works

**Comment by CreativeMD** [comment]
Good to hear!
