### ISSUE TITLE
Doors In Doors Are Broken

### ISSUE THREAD

**Issue by billyboblikeboom** [CreativeMD/LittleTiles#845]
When I try to make a door a child of another door it just breaks when I open it.
The door I made uses modded blocks and glass.
What happens is I open the parent door and everything is fine but when I open the child door and close it again it breaks. And when I try to open the parent door when the child door is open it breaks.

**Comment by CreativeMD** [comment]
Doors in Doors don't work well. I have dropped support for 1.12 quite some time ago. I will redo the entire system for 1.19 to prevent this kind of issue. You can however configure the doors to stay animated, that might help for the doors not to break ... but for now I cannot recommend to work with doors in doors :| sorry
