### ISSUE TITLE
Advanced config keybinding is not configurable on 1.12 version

### ISSUE THREAD

**Issue by xeals** [CreativeMD/LittleTiles#848]
The "advanced config" keybind, which defaults to CTRL+C, cannot be configured on 1.12. The binding is not available in the controls menu and manually setting the binding via options.txt does not work.

I'm unfamiliar with Forge in general, but it appears that the binding is created (`configureAdvanced`) but not registered with the registry; is this deliberate?

https://github.com/CreativeMD/LittleTiles/blob/96c5fb92a152a7bd663a80467379cb702471cf24/src/main/java/com/creativemd/littletiles/client/LittleTilesClient.java#L158-L171

**Comment by CreativeMD** [comment]
Oh that is not intended. I have fixed it, but I am not able to compile and release it. So someone else need to do it. Not sure when this will happen, but hopefully soon. Thank you very much for reporting this issue!

**Comment by CreativeMD** [comment]
New version has been uploaded by @Doc-1!
