### ISSUE TITLE
[1.12.2] Mod interaction issue with Nuclearcraft

### ISSUE THREAD

**Issue by GuntherDW** [CreativeMD/LittleTiles#85]
There appears to be an issue with NuclearCraft's fusion reactor when I have this mod installed in my instance.
I've been discussing this on the NuclearCraft discord as well but haven't made an issue report on their tracker yet. I'm not sure who is "responsible" for this issue yet.

NuclearCraft is a mod that as the name would suggest adds power generation methods through Nuclear Reactors.
One of these is a Fusion reactor, in which you assemble a multiblock "ring" structure around the reactor itself.

When LittleTiles is not installed the ring forms correctly and the Reactor detects said ring.
If LittleTiles is installed the magnets fail to "turn on" and hence the reactor can't start.

The magnets that were in place before (or after removing the mod) installing the mod seem to still work, but newly placed electromagnets fail to activate, causing the reactor to malfunction.

![screenshot](https://i.imgur.com/pVIE0SM.png)

The blocks placed that do not have the green ring around them are the blocks I placed after adding LittleTiles back into the pack.

Versions:

- Minecraft: 1.12.2
- Forge : 14.23.3.2669
- LittleTiles : 1.5.0-pre97_mc1.12.2
- NuclearCraft : 2.10j

**Comment by CreativeMD** [comment]
Release a pre-pre-release on my discord server.
