### ISSUE TITLE
Use Alt For Everything

### ISSUE THREAD

**Issue by tonyvranic** [CreativeMD/LittleTiles#850]
Little Tiles - 1.5.68.
CreativeCore - 1.10.70.

"Use Alt For Everything" is currently useless because the radial menu is assigned to the alt key,
thus holding/pressing the alt key, always opens up the radial menu.

Suggestion: make radial menu user re-bindable.

**Comment by CreativeMD** [comment]
What kind of radial menu? LittleTiles does not have something like this.

**Comment by tonyvranic** [comment]
Sorry, seems like I mixed up Chisels and Bits with Little Tiles.

Everything is fine, thanks!
