### ISSUE TITLE
Placing tiles crashes the game

### ISSUE THREAD

**Issue by FrodobagginsTNT** [CreativeMD/LittleTiles#851]
Hello, I've been experiencing constant game crashes, which happen every single time I try to create or place tiles, or use ctrl+z (regardless if there's anything to undo). 

What appears in my brief testing to cause the game to crash is any use of the little chisel or little glove, which appear to crash the game any time they are used.
Further, using the undo command on a tile removed with the hammer also crashes the game. 
The saw and paintbrush appear to work fine. I haven't tested the blueprinting tools.

I've tried disabling all mods save for Littletiles, CreativeCore and Chisels and Bits but still haven't had any luck getting the mod to place anything without crashing.
I've also updated both creativecore, forge and the littletiles mod, to no avail. I'm not really sure what's causing this, but I'm using the latest version of both LT (LittleTiles_v1.5.68_mc1.12.2.jar) and CC (CreativeCore_v1.10.70_mc1.12.2.jar) from curseforge.

I've also attached two crash logs - one induced by trying to use the chisel, the other by attempting to undo a use of the hammer.
Thanks so much for your help.

https://paste.ee/p/Opzd7
https://paste.ee/p/KxgZe

**Comment by CreativeMD** [comment]
You are not using the newest version of CreativeCore. The crash shows you have `CreativeCore_v1.10.61_mc1.12.2.jar` installed. Make sure to update this should fix your crash.
