### ISSUE TITLE
WorldGuard And Little Tiles Error

### ISSUE THREAD

**Issue by Sarocesch** [CreativeMD/LittleTiles#857]
Use WorldGuard and Little Tiles and can't open the user-differentiated doors because there is no flag for it but there are also no errors

so somehow you can not open little tiles doors with it 

do you have any idea how i could fix this ?

**Comment by CreativeMD** [comment]
Sorry for not responding earlier. It is a difficult thing. LittleTiles handles stuff a lot different than vanilla. I have tried implement a few hooks to enhance the compatibility with these plugins, but there are still quite a few issues. I don't think there is a way to fix it currently. I assume you are using 1.12. I have dropped support for this version a while ago. I will see what I can do for the newer versions.
