### ISSUE TITLE
Game crashes when loading world...

### ISSUE THREAD

**Issue by gobinator98** [CreativeMD/LittleTiles#858]
MC 1.19.4, Forge 45.1.0

Game crashes upon loading world with or without other mods. Seems to be due to sponges.

Log:
[latest.log](https://github.com/CreativeMD/LittleTiles/files/11742711/latest.log)

Screenshot:
![Screenshot (157)](https://github.com/CreativeMD/LittleTiles/assets/136560862/368b47a9-4e59-4218-b50e-5c5f66e21560)

**Comment by CreativeMD** [comment]
LittleTiles is not compatible with Optifine.
