### ISSUE TITLE
[1.20.1] LittleTiles Crash when ModernFix is installed

### ISSUE THREAD

**Issue by lays24mc** [CreativeMD/LittleTiles#859]
Hi,

when I use LittleTiles and ModernFix together in 1.20.1 the client crashes because of a "priority" conflict. I don't really need ModernFix, but it might be interesting for LittleTiles. Here is the log from my launcher console, since there is no crash log, nor is it recorded in the debug log : https://pastebin.com/uwDjbWuw

**Comment by CreativeMD** [comment]
You can ask the author of ModernFix whether he can change this mixin easily: https://github.com/embeddedt/ModernFix/blob/1.20/common/src/main/java/org/embeddedt/modernfix/common/mixin/perf/cache_strongholds/ServerLevelMixin.java#L42

**Comment by lays24mc** [comment]
Have fix created a request there. Let's see what will be the result :)

**Comment by embeddedt** [comment]
This can be fixed for now by disabling `mixin.perf.cache_strongholds` in the ModernFix config. ModernFix will do this automatically in the next release.

**Comment by lays24mc** [comment]
@embeddedt thank you :D

**Comment by CreativeMD** [comment]
@embeddedt Wow that's an easy and fast fix. Great work!
