### ISSUE TITLE
File for 1.20 won't load

### ISSUE THREAD

**Issue by DekuKid64** [CreativeMD/LittleTiles#860]
I have downloaded the file **LittleTiles_ALPHA_v1.6.0-pre042_mc1.20.1** from the curseforge website. 

You have it listed as an option that would work for 1.20, However when I try to load the pack I get the error:

Failure message: **Mod File LittleTiles_ALPHA_v1.6.0-pre042_mc1.20.1.jar needs language provider javafml:47 or above to load
		We have found 46**

I'm sure it's likely user error on my end but any help would be super appreciated! Longtime fan of your mod <3 
[crash-2023-06-26_19.13.45-fml.txt](https://github.com/CreativeMD/LittleTiles/files/11876992/crash-2023-06-26_19.13.45-fml.txt)

**Comment by ProsperCraft** [comment]
Use 1.20.1 loads fine for me, when using creativecore

You have the wrong version of forge.

**Comment by CreativeMD** [comment]
Use pre044, it should fix your issue.
