### ISSUE TITLE
[1.20.1] NPE Stacktrace in log on client on a dedicated server.

### ISSUE THREAD

**Issue by ProsperCraft** [CreativeMD/LittleTiles#861]
Stacktrace
https://gist.github.com/Reveter/0c9a46d8c1dc36a8a344f2217afccb01

full log- https://gist.github.com/Reveter/6e0ce572063bab005863a678d48d1b04

forge/1.20.1-47.0.19

LittleTiles_ALPHA_v1.6.0-pre042_mc1.20.1

**Comment by ProsperCraft** [comment]
Player on multiplayer server on changing dims from nether to overworld stayed in the portal and would not load in, on being kicked from the server client closed with this error

https://gist.githubusercontent.com/ProsperCraft/2bfed2d2454dcc153f0f7d6cd35167ff/raw/118770132f44bac99a4d2efadac9f0f692db8449/gistfile1.txt

**Comment by CreativeMD** [comment]
Can you try out pre044 and test if it fixes your issue?

**Comment by lays24mc** [comment]
@CreativeMD I tested it once with the new alpha and the bug still remains that you get stuck in the portal and have to restart the client.

**Comment by CreativeMD** [comment]
I have uploaded a new version: https://modrinth.com/mod/littletiles/version/nEgf0CRv
This should fix the issue (hopefully).

**Comment by lays24mc** [comment]
Now you can join, but the client crashes as soon as you enter the nether: https://pastebin.com/mRkjG5Mb

**Comment by CreativeMD** [comment]
Alright ... yeah things worked out totally different than I expected. New version should fix it now. This time for sure.

**Comment by lays24mc** [comment]
Now it works fine. Thank you :)

**Comment by CreativeMD** [comment]
Nice, glad it is finally solved. Thank you so much for reporting this issue and staying around to test it. Very much appreciated!
