### ISSUE TITLE
[1.12.1] Dedicated server crash - java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag team.creative.littletiles.common.entity.level.LittleLevelEntity.saveExtraClientData()'

### ISSUE THREAD

**Issue by ProsperCraft** [CreativeMD/LittleTiles#862]
https://gist.github.com/ProsperCraft/54a2a29102a9c8136c0be36d10931ff0

Forge: net.minecraftforge:47.0.19
LittleTiles_ALPHA_v1.6.0-pre047_mc1.20.1.jar

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
