### ISSUE TITLE
Running water destroys tiles without dropping them as items. (v2.10.26, 1.20.1)

### ISSUE THREAD

**Issue by Doc-1** [CreativeMD/LittleTiles#863]
As the name implies, when flowing water hits tiles, it is destroyed without dropping the tile in item form.

CC- CreativeCore_FORGE_v2.10.26_mc1.20.1 
LT- LittleTiles_ALPHA_v1.6.0-pre048_mc1.20.1

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks a lot for reporting it!
