### ISSUE TITLE
Crash when using premade switch.

### ISSUE THREAD

**Issue by TomBombTom** [CreativeMD/LittleTiles#865]
Loaded up a new world with No mods other than LittleTiles_ALPHA_v1.6.0-pre048_mc1.20.1, and CreativeCore_FORGE_v2.10.26_mc1.20.1. Placed the premade switch. It looked a bit strange, as the switch part was too big and not in the correct spot. Clicked on the switch, and then the game crashed.

Launcher error:
The game crashed whilst unexpected error
Error: java.lang.UnsupportedOperationException: Attempted to call Event#setCanceled() on a non-cancelable event of type: net.minecraftforge.client.event.RenderLevelStageEvent

Crash report:
[crash-2023-07-09_07.23.48-client.txt](https://github.com/CreativeMD/LittleTiles/files/11992428/crash-2023-07-09_07.23.48-client.txt)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
