### ISSUE TITLE
Game crash with exit code -1 (unexpected error)

### ISSUE THREAD

**Issue by vinnyg0621** [CreativeMD/LittleTiles#866]
when I created a new world on 1.20, it just quit with this crash report:
[crash-2023-07-18_20.18.55-client.txt](https://github.com/CreativeMD/LittleTiles/files/12090752/crash-2023-07-18_20.18.55-client.txt)

**Comment by CreativeMD** [comment]
This is quite weird. Can you update Forge and see if it still crashes?

**Comment by Thomarius214** [comment]
I have the same issue and updating Forge didn't seem to work. Maybe an incompability issue?

**Comment by CreativeMD** [comment]
Can you try it with just CreativeCore and LittleTiles installed?

**Comment by Thomarius214** [comment]
It works as it should with only LittleTiles and CreativeCore. No crashes. So some incompability issue most likely

**Comment by CreativeMD** [comment]
Can you figure out which mod is causing the issue? Maybe it is geophilic?

**Comment by Thomarius214** [comment]
> Can you figure out which mod is causing the issue? Maybe it is geophilic?

I'll check it out later. It probably isn't geophilic (for me at least) since I don't have it downloaded

**Comment by Thomarius214** [comment]
> Can you figure out which mod is causing the issue? Maybe it is geophilic?

Seems like it's Optifine.
It's probably on Optifines behalf since the Create mod is also currently not compatible with Optifine.

**Comment by Thomarius214** [comment]
I also created a bug report in the official Optifine github.

**Comment by CreativeMD** [comment]
Oh right ... I completely forgot about this. You should not report it to Optifine. LittleTiles does not support Optifine anymore. Use Rubidium and Oculus instead. Sorry for the trouble I should have seen this earlier. I can only recommend to switch over to the alternatives.

**Comment by Thomarius214** [comment]
Alright, no problem. Thanks for giving me some other alternatives. :)
