### ISSUE TITLE
Door-Texture problem

### ISSUE THREAD

**Issue by Duo-TritiumDioxide** [CreativeMD/LittleTiles#867]
I Updated Versions of CreativeCore and Little Tiles, Minecraft Version 1.12.2
Mods:
Coroutil-1.12.1-1.2.13
creativecore_v1.10.70
CTM-MC1.12.2-1.0.2.31
littletiles_v1.5.73
Mekanism_1.12.2_9.8.3.390
NTM_Extended-1.12.2-1.9.7
NuclearCraft-2o.6.2
OptiFine_1.12.2_HD_U_G5
weather2_1.12.1-2.6.12

**Comment by Duo-TritiumDioxide** [comment]
And not only texture...
![2023-07-20_19 24 15](https://github.com/CreativeMD/LittleTiles/assets/139563472/cc0d39a1-7175-49a8-80c7-9be92a69b82a)
![2023-07-20_19 21 56](https://github.com/CreativeMD/LittleTiles/assets/139563472/2b68df14-50bd-4b61-bb38-73e1a6a683ea)
![2023-07-20_19 21 47](https://github.com/CreativeMD/LittleTiles/assets/139563472/04448ffa-51ee-4ce3-a14e-6e729abdd258)

**Comment by Duo-TritiumDioxide** [comment]
Tested only Creative Core and Little Tiles, Problem is still here
![2023-07-20_19 48 45](https://github.com/CreativeMD/LittleTiles/assets/139563472/f10c0626-6139-4622-8858-1114a678f747)

**Comment by CreativeMD** [comment]
Weird, not sure why this is happening. But I have dropped support for 1.12 quite some time ago. Sorry but this will not be fixed. You can use F3 + A to reload.
