### ISSUE TITLE
Slope tile problem

### ISSUE THREAD

**Issue by kazumadh** [CreativeMD/LittleTiles#869]
![2023-07-23_20 45 49](https://github.com/CreativeMD/LittleTiles/assets/140326816/ec441b0a-f87e-416f-989e-8bbd524fc6ba)
Sometimes when I make a slope, I walk on it and suddenly sink in it (like a "quicksand block"). I hope you will fix this bug, thanks !!!

**Comment by CreativeMD** [comment]
Which version are you using 1.12 or 1.20?

**Comment by kazumadh** [comment]
It happened in 1.12.2...And It's very sad to hear that you stopped supporting 1.12.2. Anyway, thanks for your response. I hope this bug will not happen in 1.20.1

**Comment by CreativeMD** [comment]
Hope so too. Normally this should work. Never heard of this issue before except if your slope is very very long. How long is it (want to test this in 1.20.1)?

**Comment by kazumadh** [comment]
I usually make 1/16 slopes (Height = 1 block, Length = 16 blocks)

**Comment by kazumadh** [comment]
I found out that this bug usually happens when it's placed from Little Blueprint, or when you use Little Hammer to interact with it. Another thing I guess is that if I make a slope by just only Little Chisel Tool, it doesn't happen (or rarely, actually), even it's a long slope. I haven't tested this in 1.20.1, but maybe I will do when Little Tiles for 1.20.1 is officially released.

**Comment by kazumadh** [comment]
I found out that this bug usually happens when I go up.

**Comment by CreativeMD** [comment]
This issue has been fixed for 1.20 in e0907c3. _Doc will try to fix it for 1.12 as well. Not sure when it will be out, but maybe probably in a few days. I will close this issue for now. Thanks a lot for reporting and taking the time!
