### ISSUE TITLE
[Suggestion] Sliced/sloped blocks are too difficult to create/place

### ISSUE THREAD

**Issue by Captainaviator** [CreativeMD/LittleTiles#88]
There's no easy way to control the size/angle with any kind of precision.  I'd like to be able to make specific sized angled pieces consistently, quickly, easily, and in large amounts

**Comment by CreativeMD** [comment]
You probably used the grabber for it. I don't recommend it. You should use the chisel instead left click and select the slice shape.

**Comment by Captainaviator** [comment]
I was not using the grabber

**Comment by CreativeMD** [comment]
Ok, so what is the problem with the slice shape? (Grabber is also called glove)

**Comment by Captainaviator** [comment]
I updated my original description.  There's no easy way to get a consistent size/angle.  I also don't know what dictates the height of the angled piece being created.

**Comment by CreativeMD** [comment]
You can pick a slice you already placed (by clicking the mouse wheel). If you are in survival you can use the glove (recipe mode).

**Comment by Dushess** [comment]
The way to set angle is easy, as main action this type in LT. Arrow left and arrow right. It works in forming phase for sliced tile mode. Angle for this mode is consistent, placed(final) angle and size depends from where you placed tile corners. 
And little offtopic
Creative, you've said about shape calculation(tile combining) issue fix, in next pre version?
