### ISSUE TITLE
Issue with color transfer in blueprint and chisel

### ISSUE THREAD

**Issue by Cairnock** [CreativeMD/LittleTiles#883]
I'm not sure if that one is already known, at least i couldn't really find anything by searching the titles, so here I go. 
I noticed, that blueprints don't seem to safe color changes made with any tool, like they are colored correctly in the preview inside the blueprint but not shown when the blocks are placed down. Also the picking up colored Blocks with the chisel by using the mouse weel and looking at the according block seems not to work. It picks up the uncolored version of the block but not the color change (This funtion works perfectly for the brush tho).

**Comment by CreativeMD** [comment]
Fixed the chisel pick, but I have no idea what the first issue is about the blueprints. I have tested it and it worked just fine for me. Maybe try out the newest version, if the issue still occurs maybe provide a few screenshots to clarify what is going wrong.

**Comment by CreativeMD** [comment]
New version is out. If the other issue still persist just reply here and maybe explain it a bit further.
