### ISSUE TITLE
Crash when placing LT Blocks underwater (MC 1.20.1, LT Alpha Pre058, CreativeCore v2.10.34)

### ISSUE THREAD

**Issue by kazumadh** [CreativeMD/LittleTiles#884]
I made a column with LT and placed it underwater, then the game froze and crashed 😦
I hope when this issue is fixed, LT blocks can still be waterlogged without using Debug Stick. 
Here the crash report:
[crash-2023-08-23_17.08.22-server.txt](https://github.com/CreativeMD/LittleTiles/files/12421031/crash-2023-08-23_17.08.22-server.txt)

**Comment by CreativeMD** [comment]
Fixed already in my dev environment but I cannot release it due to issue with rubidium. Not sure when these will solve, but I hope the next days. Thanks for taking the time to report this issue!

**Comment by CreativeMD** [comment]
New version is out!
