### ISSUE TITLE
[mc1.20.1, LT Alpha Pre058] recipe gui preview is broken with create mod

### ISSUE THREAD

**Issue by Blendzx** [CreativeMD/LittleTiles#885]
If there is a create mod, the preview shows nothing

**Comment by CreativeMD** [comment]
Are you sure this is related to create mod? This can happen normally as well. Just open the gui several times, usually it works again after a few tries.

**Comment by Blendzx** [comment]
Yes, i literally just spammed the gui and preview still not works when there is an Create mod.

Preview works normally without Create

And pressing a button causes crash

**Comment by CreativeMD** [comment]
Can you send me the log file?

**Comment by Blendzx** [comment]
[crash-2023-08-27_13.19.52-client.txt](https://github.com/CreativeMD/LittleTiles/files/12447222/crash-2023-08-27_13.19.52-client.txt)

Tested on Forge 47.1.44
It goes same for Forge 47.1.0
Using latest version of Create (v0.5.1d)

There's just Create and LittleTiles, no other mods

**Comment by CreativeMD** [comment]
That is the crash-report. Can you reproduce this crash and then send the latest.log? Sorry for not responding earlier. I kind of forgot about this problem.

**Comment by Blendzx** [comment]
[latest.log](https://github.com/CreativeMD/LittleTiles/files/12561550/latest.log)

**Comment by CreativeMD** [comment]
Thanks a lot. Fixed the issue, but unfortunately I cannot release it at the moment. I wait for rubidium to release another update.

**Comment by Blendzx** [comment]
alright, thanks!
