### ISSUE TITLE
Little Tiles Alpha version 1.20.1, Issue after building window

### ISSUE THREAD

**Issue by Himenou** [CreativeMD/LittleTiles#887]
I've been building only using LT tiles but when i make windows (making a frame and filling with glass) the frame tiles tend to disappear, but are still visible? (It's possible to walk through them) 
Sometimes the tiles become normal after placing some tiles inside the frame and then pressing ctrl + z, but it feels a bit weird to build like that.
Additionally, some invisible tiles usually appear near the window (ones that you can't walk through)

**Comment by CreativeMD** [comment]
Can you provide some screenshots or maybe even a video? I have to fix some other stuff first, but I hope to get to it next week.

**Comment by Himenou** [comment]
https://github.com/CreativeMD/LittleTiles/assets/142178543/14dc13a5-f9fb-4c9d-9eb6-cd0d93b574c9

Well, the tiles were acting like this. But the box tiles seem more stable after i reinstalled minecraft, so i haven't encountered it as much. (just with pillars)

**Comment by CreativeMD** [comment]
Sorry for not responding earlier. Can you try out the newest version of embeddium, littletiles and oculus? Maybe it works now.

**Comment by Himenou** [comment]
It seems to work better now

**Comment by CreativeMD** [comment]
Better, but still not perfect?

**Comment by Himenou** [comment]
Well, I haven't been able to make it appear again, so I would say it works perfectly :)

**Comment by CreativeMD** [comment]
Nice! Very good. I will close this issue for now. If it appears again just let me know.
