### ISSUE TITLE
At least i make it up to the main menu now 

### ISSUE THREAD

**Issue by Leclowndu93150** [CreativeMD/LittleTiles#891]
https://pastebin.com/0NAaNxCv  
https://github.com/CreativeMD/LittleTiles/issues/888#issuecomment-1726225321

**Comment by CreativeMD** [comment]
That is a very weird issue. Can you please test it with just CreativeCore, LittleTiles and Embeddium installed? Seems like there is another mod causing an issue. Might be mixin extras, I do not know for sure. Would be happy if you can test it.

**Comment by Leclowndu93150** [comment]
okay np

**Comment by Leclowndu93150** [comment]
yeah so it still doesn't work

https://pastebin.com/FLKYbaLG

**Comment by Leclowndu93150** [comment]
![image](https://github.com/CreativeMD/LittleTiles/assets/73310949/da4d0338-cbba-426f-9982-b87d09f74ed4)

**Comment by CreativeMD** [comment]
Can you send the crash-report?

**Comment by Leclowndu93150** [comment]
I sent it already

**Comment by Xing-C** [comment]
> I sent it already

Perhaps you should send a crash report with only these three mods

**Comment by Leclowndu93150** [comment]
> > I sent it already
> 
> Perhaps you should send a crash report with only these three mods

bro i literally sent it ... look https://pastebin.com/FLKYbaLG

**Comment by Xing-C** [comment]
> > > I sent it already
> > 
> > 
> > Perhaps you should send a crash report with only these three mods
> 
> bro i literally sent it ... look https://pastebin.com/FLKYbaLG

I have also encountered similar issues. You can try using version v1.6.0-pre58, but if it still doesn't work, please use rubidium 6.9.5

**Comment by Xing-C** [comment]
> > > I sent it already
> > 
> > 
> > Perhaps you should send a crash report with only these three mods
> 
> bro i literally sent it ... look https://pastebin.com/FLKYbaLG

sorry rubidium 0.6.5

**Comment by CreativeMD** [comment]
Rubidium 0.6.5 is not support anymore.
@Leclowndu93150 sorry, I missed it. I'm trying to fix the issue currently.

**Comment by Xing-C** [comment]
> Rubidium 0.6.5 is not support anymore. @Leclowndu93150 sorry, I missed it. I'm trying to fix the issue currently.

If completed, this can replace rubidium 🤤

**Comment by Leclowndu93150** [comment]
have fun

**Comment by CreativeMD** [comment]
New version is out and finally fixes it, but you have to update embeddium as well.
