### ISSUE TITLE
Incompatible with Rubidium 0.7.0a

### ISSUE THREAD

**Issue by kazumadh** [CreativeMD/LittleTiles#895]
I installed Little Tiles Alpha 1.6.0 Pre061 with Creative Core v2.11.1 & Rubidium 0.7.0a, then the game crashed at startup as shown in this picture.
![Capture](https://github.com/CreativeMD/LittleTiles/assets/140326816/f154116b-a737-42f4-9a06-0a040bf3a0d1)
Also, here's the crash log:
[crash-2023-09-22_12.41.33-fml.txt](https://github.com/CreativeMD/LittleTiles/files/12697215/crash-2023-09-22_12.41.33-fml.txt)

**Comment by CreativeMD** [comment]
Please use embeddium instead: https://www.curseforge.com/minecraft/mc-mods/embeddium
