### ISSUE TITLE
Conflict with Flywheel

### ISSUE THREAD

**Issue by tobi1449** [CreativeMD/LittleTiles#896]
When trying to load a world with LittleTiles, Create and Embeddium, the game crashes because of a mixin conflict:

`@Redirect conflict. Skipping littletiles.mixins.json:rubidium.ChunkBuilderMeshingTaskMixin->@Redirect::getRendererRedirect(Lnet/minecraft/client/renderer/blockentity/BlockEntityRenderDispatcher;Lnet/minecraft/world/level/block/entity/BlockEntity;)Lnet/minecraft/client/renderer/blockentity/BlockEntityRenderer; with priority 1000, already redirected by flywheel.sodium.mixins.json:ChunkBuilderMeshingTaskMixin->@Redirect::flywheel$redirectGetRenderer(Lnet/minecraft/client/renderer/blockentity/BlockEntityRenderDispatcher;Lnet/minecraft/world/level/block/entity/BlockEntity;)Lnet/minecraft/client/renderer/blockentity/BlockEntityRenderer; with priority 1000`

Mods:
- create-1.20.1-0.5.1.e
- embeddium-0.1.11+mc1.20.1
- CreativeCore_FORGE_v2.11.1_mc1.20.1
- LittleTiles_ALPHA_v1.6.0-pre062_mc1.20.1

**Comment by Xiarno** [comment]
Can confirm. I have the same issue too.

**Comment by Xing-C** [comment]
Please let me know if this is resolved.  I have the same issue too.

**Comment by Xiarno** [comment]
Btw could this possibly be a 1.20.1 patch too?
I want to add it to a modpack I'm playing on but this conflict prevent me and the modpack is in 1.20.1.

**Comment by Xing-C** [comment]
I've been waiting for this for a long time, any info or solutions?

**Comment by CreativeMD** [comment]
New version is out for 1.20.1. Update CreativeCore as well. Can you try if that one works?

**Comment by CreativeMD** [comment]
Any news? Has somebody tested it?

**Comment by Xing-C** [comment]
> Any news? Has somebody tested it?


Sorry, I forgot to reply. Everything is working fine now, here is my list of mods.

LittleTiles_ALPHA_v1.6.0-pre067_mc1.20.1.jar
CreativeCore_FORGE_v2.11.7_mc1.20.1.jar
oculus-flywheel-compat-1.20.1-0.2.0.jar
create-1.20.1-0.5.1.e.jar
oculus-mc1.20.1-1.6.9.jar
textrues_embeddium_options-0.1.2+mc1.20.1.jar
embeddium-0.2.2+mc1.20.1.jar

**Comment by CreativeMD** [comment]
Nice! Thanks for testing and letting me know!
