### ISSUE TITLE
Interactive object (e.g., door) copy bug

### ISSUE THREAD

**Issue by LastDice** [CreativeMD/LittleTiles#902]
--- English ( with translate ) ---
There is a bug in Little Tale when right-clicking on interactable objects (e.g., doors). When multiple players right-click, it's fine. However, when player A is continuously interacting and player B goes far away, the number of doors increases to two or more.

I may feel a bit awkward and inexperienced since I'm posting a GitHub issue for the first time.

--- Korean ---
리틀타일에서 우클릭 시 작동 가능한것(예시: 문)에 버그가 있습니다.
여러명이서 우클릭했을때는 괜찮은데, A라는 플레이어가 상호작용을 계속 하고 있을 때, B라는 플레이어가 멀리 다녀올 경우, 문이 2개 이상으로 늘어납니다.

제대로 된 깃허브 이슈를 처음 올려봐서, 조금 어색하고 미숙할 수 있습니다.

https://youtu.be/lTR6PG3n60Y

**Comment by CreativeMD** [comment]
Hey, sorry for not responding earlier. I have stopped developing for 1.12. Sorry this issue won't be fixed. It should work in 1.20 however. If not I will fix it there.
