### ISSUE TITLE
Little tiles causing black square around sun/moon with ComplementaryShaders

### ISSUE THREAD

**Issue by Learwin** [CreativeMD/LittleTiles#903]
Minecraft: 1.20.1
Forge: 47.1.3
CreativeCore Forge 2.11.6
Oculus 1.6.9
Little Tiles: 1.6.0-pre067
ComplementaryReimagined r5.0

Installing Little tiles causes the sun/moon to look like the image below when choosing the Reimagined style for Sun and Moon
![grafik](https://github.com/CreativeMD/LittleTiles/assets/6223515/d4aeed76-370a-4544-a841-e8937292384b)

If I change the style to unbound the issue does not happen
![grafik](https://github.com/CreativeMD/LittleTiles/assets/6223515/87c3da91-8540-4b6c-82ac-dafe06f46f12)

As soon as I uninstall Little Tiles the issue is no longer present.

I'm not completely sure if I should report this issue here or on complementaries github.

**Comment by CreativeMD** [comment]
This is a known issue. Thanks for posting it. I should have responded earlier. I thought I would get to it sooner, but there are some other things I want to fix first. Then I will try to tackle this issue.

**Comment by IvorAmlug** [comment]
Same with BSL tought ive gone crazy

**Comment by CreativeMD** [comment]
This issue finally got fixed. Was a small mistake, but it was a big struggle to find it. Get the newest version (you also need to update CreativeCore). If it still does not work report it here and I will reopen the issue.
