### ISSUE TITLE
conflict with Flywheel(?)

### ISSUE THREAD

**Issue by MANUXAL** [CreativeMD/LittleTiles#906]
in an attempt to try an already compatible combination of Creativecore and Littletiles with Create, i tried the exact versions mentioned by "Xing-C" in https://github.com/CreativeMD/LittleTiles/issues/896 , with and without embeddium and the rest, i get this error: 

![imagen](https://github.com/CreativeMD/LittleTiles/assets/94775018/b0815510-6c63-432c-be5e-26c783b62796)

the conflict is between littletiles and create specifically

**Comment by CreativeMD** [comment]
Can you send me the entire crash-report?

**Comment by CreativeMD** [comment]
Update to the newest version should fix this issue. Will close it for now.
