### ISSUE TITLE
Little tiles in in my Mod folder but will not show up on Minecraft

### ISSUE THREAD

**Issue by rachelw357** [CreativeMD/LittleTiles#907]
I am new to using mods and also playing on my computer so this might just be some silly mistake I made, but I tried troubleshooting and could not seem to get the LittleTiles to show up when I clicked the mod button on my Minecraft launcher. I have tried removing the mod from the folder, closing everything out and doing it a again but unfortunately it will still not show up on Minecraft. I have not had this issue with any of my other mods so thought I would reach out. Thankful in advance for whatever advise you could give me! 
<img width="2239" alt="Screenshot 2023-11-01 at 3 30 54 PM" src="https://github.com/CreativeMD/LittleTiles/assets/149621148/b647a6b0-4e9b-458c-b20a-694fc3aaf28a">
<img width="2239" alt="Screenshot 2023-11-01 at 3 31 20 PM" src="https://github.com/CreativeMD/LittleTiles/assets/149621148/14a7de7c-40f4-44dd-8cfc-c50dfb57b066">

**Comment by DN2048** [comment]
You downloaded LittleTiles for Minecraft 1.12.1 when you are on 1.20.1.

**Comment by CreativeMD** [comment]
I guess this is fixed. Will close it.
