### ISSUE TITLE
1.20.1 Alpha Ghost Blocks (Sometimes difficult to get rid of)

### ISSUE THREAD

**Issue by YeetboiPro** [CreativeMD/LittleTiles#908]
Sometimes when I place slopes, it makes flat tiles close to it invisible. Doesn't crash the game but it's just annoying.

**Comment by CreativeMD** [comment]
Can you provide a few screenshots. I'm not quite sure what this is about.

**Comment by CreativeMD** [comment]
It the issue similar to this one: https://github.com/CreativeMD/LittleTiles/issues/887

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists just post it here.
