### ISSUE TITLE
Mod Unusable - Game keeps crashing

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#91]
Even when disabling all other Mods (besides Creative Core, of course), I can barely use anything that comes from the Mod. Placing a downsized Block? Game crashes. Recolouring one of those coloured Blocks? Crash. Trying to use the Chisel? You guessed it, the Game crashes again.

In Case this is Relevant, the last thing I see before the entire Process dies is the Message "Shutting internal Server..."

**Comment by CreativeMD** [comment]
Which versions are you using? Can you send me the crash reports?

**Comment by Syphenion** [comment]
Gonna piggyback on this since I'm crashing sometimes when using the hammer.

https://pastebin.com/Vz46QcT9

**Comment by CreativeMD** [comment]
@Syphenion thanks! This crash occurs when you destroy a structure and undo it. I will try to fix it, but it still does not explain all of the other issues.

**Comment by ghost** [comment]
Oh geez ... Turned out i didn't use the correct Version. 😅 This explains pretty much everything. Sorry for the inconvenience mate.

**Comment by BlackThursday** [comment]
However ... why can't I use the Hammer in Survival Mode? Everytime I try to use it the game says "not enough Space"
