### ISSUE TITLE
[1.20.1 Forge] Crazy visual glitch when using shaders (makes game unplayable)

### ISSUE THREAD

**Issue by VOLKOUL** [CreativeMD/LittleTiles#911]
**This only happens when Little Tiles is installed and ONLY in the Nether** (maybe the End too, I didn't test that). Disabling the mod fixes the issue. I am using Chocapic13' Shaders. I am also using Connector but I don't think it's the cause of the problem. ~~(p r e s u m a b l y)~~ Yeah, it's not connector. (I checked) **The issue is most definitely with Little Tiles mod and Oculus or something. This visual glitch is most noticable when loading chunks or spinning the player's camera.**

![2023-11-05_14 27 12](https://github.com/CreativeMD/LittleTiles/assets/97387920/bac37d32-8652-4fc4-a8ba-47b3b020b11e)
![2023-11-05_14 27 25](https://github.com/CreativeMD/LittleTiles/assets/97387920/3aa3c6d3-6679-4ad5-85da-805d4a033dbd)

**Comment by CreativeMD** [comment]
This issue finally got fixed. Thanks for reporting it. Was a small mistake, but it was a big struggle to find it. Get the newest version (you also need to update CreativeCore). If it still does not work report it here and I will reopen the issue.

**Comment by VOLKOUL** [comment]
YEAAAH! Thank you! Everything seems to be working fine.
