### ISSUE TITLE
[1.20.1 Forge] LittleTiles makes ladders in VS Eureka Ships not working

### ISSUE THREAD

**Issue by miscellaneousgt** [CreativeMD/LittleTiles#913]
I made ships using Valkyrien Skies Eureka Ships mod, the ships have ladders in them and the ladders worked, I can climb the ladders

But the moment I install LittleTiles, the ladders of the ship don't work anymore, I can't climb, I'm talking about the ladders used on the ship or inside the ship, I also tried vines but same result.

I have no problem with the ladders used outside of the ships that are placed in the static world, they still work properly.

CreativeCore is not the one causing this, the ladders still work with only CreativeCore, it is LittleTiles that caused this issue.

I've used 3 different LittleTiles versions and they all have the same result:
1. the latest (LittleTiles_ALPHA_v1.6.0-pre067_mc1.20.1.jar)
2. the second latest (LittleTiles_ALPHA_v1.6.0-pre066_mc1.20.1.jar)
3. and the other one (iirc LittleTiles_ALPHA_v1.6.0-pre064_mc1.20.1.jar)

Other mods:
1. CreativeCore (CreativeCore_FORGE_v2.11.9_mc1.20.1.jar)
2. Kotlin for Forge (kotlinforforge-4.5.0-all.jar)
3. Eureka! Ships! for Valkyrien Skies (eureka-1201-1.3.0-beta.2.jar)
4. Valkyrien Skies (valkyrienskies-1201-2.3.0-beta.4.jar)

I really want both of these mods in my minecraft, I tried not to make them conflict with each other by using them separately, I wanted to use normal blocks for VS Eureka Ships that moves and have physics, but I also wanted to use LittleTiles for the static builds of the world, but then the ladder issue happened, how can this be fixed?

Thank you

**Comment by CreativeMD** [comment]
I have an idea why this is happening. You should report this issue to Valkyrien Skies. It's because LittleTiles set a config option of forge to true: https://github.com/CreativeMD/LittleTiles/blob/1.20/src/main/java/team/creative/littletiles/LittleTiles.java#L208
Seems like Valkyrien Skies cannot handle this config option. I do not really see a different reason why this is not working, but still would be good if you can test it. Don't install LittleTiles and set this config to true and see if the same issue appears.

**Comment by miscellaneousgt** [comment]
You mean set the config to false? It is already true by default which created the bug

`ForgeConfig.SERVER.fullBoundingBoxLadders.set(false);`
I have changed it to false and tested it, and it works, I can climb all types of ladders that are attached to VS Eureka Ships now
I don't know if this change will introduce more bugs and problems, but thanks anyways
version: LittleTiles_ALPHA_v1.6.0-pre077_mc1.20.1.jar

Should I still inform this to Valkyrien Skies?

**Comment by CreativeMD** [comment]
Yes. It is actually not a problem with LittleTiles. Just tell them that they have to enable this config to see the issue.
Hope they can fix it.
