### ISSUE TITLE
Any chance for a 1.18.2 version?

### ISSUE THREAD

**Issue by Octelly** [CreativeMD/LittleTiles#917]
I'm expecting a no, since the modern versions seems to all be using NeoForge as the loader and I don't believe NeoForge is even available on 1.18.2, but it is atm probably the modding version with the most support. To be fair, so far it looks like 1.20.x could be the next one, but that will probably still take a while.

_(1.18.2 is currently the only version with Project Red, Tinker's Construct and up to date Create that I can think of (among other mods))_

**Comment by CreativeMD** [comment]
Nope sorry, LittleTiles will not be ported back. It's way too much work. The version for 1.20.1 is still not out of alpha. At the moment I can only focus on one version. My goal is to get this mod out of alpha as soon as possible, then I can think about supporting the two newest versions, but all the versions before will not be considered.
