### ISSUE TITLE
Weird door behavior causing crash 1.20.1

### ISSUE THREAD

**Issue by miscellaneousgt** [CreativeMD/LittleTiles#919]
Crash recreated in 8 Dec 2023

only 2 mods: CreativeCore and LittleTiles

Minecraft version: 1.20.1
LittleTiles version: LittleTiles_ALPHA_v1.6.0-pre070_mc1.20.1.jar
Forge version: 4.7.25
CreativeCore version: CreativeCore_FORGE_v2.11.11_mc1.20.1.jar

1. First of all, notice that there's a lighting problem causing dark spots (the crash happened before in this world, I entered this world again to recreate it and record it)
2. Weird door behaviour, teleports me if I close it while standing in the doorway
3. I can walk through the door when opened, I also went prone at some point for some reason
4. The crash is triggered when the door is fully covered in dirt like in the video

video link: https://youtu.be/oR2yk3TZ8jk
crash report: [crash-2023-12-08_18.40.25-server.txt](https://github.com/CreativeMD/LittleTiles/files/13622256/crash-2023-12-08_18.40.25-server.txt)

Thanks, looking forward to the full 1.20.1+ release

**Comment by CreativeMD** [comment]
Collision for doors does not work yet, but the crash occurred because the door did not have space to place itself. This has been fixed in the newest version. Thanks for reporting this issue!
