### ISSUE TITLE
Sliding door (1.12.2)

### ISSUE THREAD

**Issue by Cocoro98** [CreativeMD/LittleTiles#92]
Hello Dev, I have a request for the next update of the mod. In the mod we can create door who rotate on one axis and I will make a japan door but this door slide. So if is possible to add this feature.

Xanox

**Comment by CreativeMD** [comment]
There is a sliding door: https://www.youtube.com/watch?v=9dP-LeMOiWg

**Comment by Cocoro98** [comment]
Ahhaha yeah sorry
