### ISSUE TITLE
Crash by open creative tab

### ISSUE THREAD

**Issue by agentwolf88** [CreativeMD/LittleTiles#920]
[crash-2023-12-12_16.30.02-client.txt](https://github.com/CreativeMD/LittleTiles/files/13649997/crash-2023-12-12_16.30.02-client.txt)

**Comment by CreativeMD** [comment]
That seems to be an issue of the graveyard mod. You should report it to them. Still struggle to understand how this can happen. Have you used a graveyard block to build with LittleTiles? There was a bug which allowed you to use block which littletiles does not really work with. More context would be very nice.

**Comment by CreativeMD** [comment]
Still there?

**Comment by CreativeMD** [comment]
Will close this issue for now. If it is still there please provide more information.
