### ISSUE TITLE
Little Bag duplicating blocks

### ISSUE THREAD

**Issue by HeVeronos** [CreativeMD/LittleTiles#921]
Little Tiles: v1.6.0-pre064_mc1.20.1
CreativeCore: v2.11.5_mc1.20.1
Forge: 1.20-46.0.14

The video shows it all, little bag duplicates every block you put in it. Also it doesn't serve it's primary purpose and if I try to build something with the chisel it shows "Not enough ingredients". It's not a compatibility issue, because I made a version only for Little Tiles.

https://github.com/CreativeMD/LittleTiles/assets/144208474/b0855a43-bc2e-4004-8bd5-6e203a6b782e

**Comment by CreativeMD** [comment]
Update LittleTiles this issue has been fixed.
