### ISSUE TITLE
Crash when creating new world/join existing world

### ISSUE THREAD

**Issue by kazumadh** [CreativeMD/LittleTiles#922]
I've recently updated CreativeCore to v2.11.15 & LittleTiles to Alpha Pre075 but this crash still happened, here's the crash log
[crash-2023-12-16_07.43.56-client.txt](https://github.com/CreativeMD/LittleTiles/files/13690913/crash-2023-12-16_07.43.56-client.txt)

**Comment by kazumadh** [comment]
Oh wait, I think I've posted in a wrong place. Please close this and move to this new issue link:
https://github.com/CreativeMD/CreativeCore/issues/199

**Comment by CreativeMD** [comment]
It was an issue of LittleTiles. Should be fixed in the newest version released yesterday. Make sure to update CreativeCore as well.
