### ISSUE TITLE
Dissapearing / ghost blocks, disappearing / ghost slopes and their weird behavior 1.20.1

### ISSUE THREAD

**Issue by miscellaneousgt** [CreativeMD/LittleTiles#923]
Dissapearing block / ghost block: https://youtu.be/S_JFQ2peM0g
1. The blocks around the working door disappear at some point for some reason
2. These ghost blocks also have weird collisions where it blocks movement but also gives kind of like a weird stuck feeling.
3. If I right click a ghost block, it went back to normal (the previously disappeared block reappear along with its normal block collision)
4. If I place a block on a ghost block position, it won't place the block that I'm placing but will make the previously disappeared block reappear instead (similar to when I right click it)
6. I also have tested these ghost blocks collisions with tridents and arrows but not recorded in the video, the moment the tridents/arrows hit the ghost block, the hit sound plays which is a correct behavior but the tridents/arrows entities themselves went through the ghost block, but shortly after that, they teleport back to the ghost block position which is kind of like correcting themselves a bit late, and even after that, they still moving glitchy on the spot.

Disappearing / ghost slope and texture loss: https://youtu.be/2bDR5TKlY1g
1. Slopes sides lose texture (transparent, not rendered) if placed near working doors
2. Somehow the slopes also disappear around working doors
3. I can't place blocks on these ghost slopes position, I have to /fill with air before I could place blocks
4. The door also loses textures

LittleTiles version: LittleTiles_ALPHA_v1.6.0-pre078_mc1.20.1.jar
CreativeCore version: CreativeCore_FORGE_v2.11.16_mc1.20.1.jar

Thanks again, this doesn't cause crash but I just wanna let you know

**Comment by CreativeMD** [comment]
Can you export the door so I can do the tests myself?

**Comment by miscellaneousgt** [comment]
I think any type of door can make that happen, I've tried many doors, a simple 2 blocks tall stone door with only 1 tile thickness, those copper doors in the videos, the other one I used the other day that have combinations of brick, stained glass, and wood, and many others. I also tried many sizes, I trimmed the edge of the door by 1 tile or 2, make it smaller and yet the ghost blocks still happened.

But here is the door I used in the video
{boxes:7,min:[I;9,0,0],s:{aS:-1,cS:0,center:[I;9,0,0,10,1,1,16],du:10,hand:1b,id:"axis",in:3,rotation:{a:1,c:1b},s:[{b:1b,n:"closed"},{b:1b,n:"opened",rY:90.0d}],sound:1b,state:{mode:"TOGGLE",state:0b},t:[]},size:[I;2,32,16],t:{"minecraft:copper_block":[[I;-1],[I;9,16,0,11,20,16],[I;9,20,0,11,32,4],[I;9,20,12,11,32,16],[I;9,28,4,11,32,12],[I;9,0,0,11,16,16]],"minecraft:netherite_block":[[I;-1],[I;9,20,5,11,28,7],[I;9,20,9,11,28,11]]},tiles:2}

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks you very much for reporting this issue!
