### ISSUE TITLE
Spam with [FATAL] errors in console

### ISSUE THREAD

**Issue by GamerGoBC** [CreativeMD/LittleTiles#926]
When entering the world, the mod starts spamming it with an error in the console:
[error.txt](https://github.com/CreativeMD/LittleTiles/files/13804589/error.txt)

Forge 1.20.1, Latest version of LittleTiles and Creative Core. No Optifine\Sodium
It doesn't cause a crash, but it seems to me that something is not working correctly...
No crash-report bc no crash ._.

**Comment by CreativeMD** [comment]
Should be fixed in the newest version. Thanks for taking the time to report this issue!
