### ISSUE TITLE
Entities don't get registered client-side

### ISSUE THREAD

**Issue by Octelly** [CreativeMD/LittleTiles#928]
```
[15:49:44] [Render thread/ERROR] [minecraft/BlockableEventLoop]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "team.creative.littletiles.client.level.LittleAnimationHandlerClient.pollEntityInTransition(net.minecraft.network.protocol.game.ClientboundAddEntityPacket)" because "team.creative.littletiles.client.LittleTilesClient.ANIMATION_HANDLER" is null
```
[Full context _(log, including Prism Launcher mod list)_ on mclo.gs](https://mclo.gs/R0txzF7#L11447)

The pack is a modified version of ATM 9, recently updated to the latest version. I am not sure what causes this, but entities do seem to get correctly registered after initial login, but don't appear again after switching dimensions.

_I also cannot see Ars Nouveau lights anymore, which seems to be related as it started happening around the same time. (this happens both with and without shaders)_

IMPORTANT NOTE:
**This happens with the latest versions as well!** I forgot to mention that downgrading to the previous ones was me trying to troubleshoot.

**Comment by CreativeMD** [comment]
This is quite confusing. This should be fixed in the newer versions. Is there anything you have done before this crash appeared? Have you built a structure which has doors in doors? Maybe that is the issue. Tried to replicate it myself, but it worked all fine for me.

**Comment by CreativeMD** [comment]
Never mind, fixed the issue in the newest version. Thanks for reporting this issue!
