### ISSUE TITLE
Re : sliding and rotating door Bug 

### ISSUE THREAD

**Issue by Cocoro98** [CreativeMD/LittleTiles#93]
Hi it's me again ^^ finally I have a bug during the animation of the door link of view on youtube.
I report the mod of Valkyrien Warfare (0.9 prerelease) cause that bug and if is possible can you look to try repair. Thanks you
https://youtu.be/_ixvToVB76Y
https://minecraft.curseforge.com/projects/valkyrien-warfare

**Comment by CreativeMD** [comment]
Is it placed on an airship? No idea what causes this issue and I don't see a way to fix it :(

**Comment by Cocoro98** [comment]
no sadly just mod activate x(

**Comment by CreativeMD** [comment]
Sorry, but there is nothing I can do from my end. You should report it to Valkyrien Warfare, maybe they know how to fix the issue.
