### ISSUE TITLE
Crash after creating a world in 1.20.1

### ISSUE THREAD

**Issue by vinnyg0621** [CreativeMD/LittleTiles#930]
I'm using the latest forge version and all, but there is some mod that does not wanna load little tiles...
exit code: -1

[crash report](https://gist.github.com/vinnyg0621/619719f8072cdcef83f1166580ebcecb)

**Comment by CreativeMD** [comment]
LittleTiles is incompatible with Optifine in 1.20.1. Use Embeddium (and Oculus) instead.
