### ISSUE TITLE
Trying to place a blueprint with a 4-bit input requires a "dyeable clean" block

### ISSUE THREAD

**Issue by alwayswright16** [CreativeMD/LittleTiles#931]
MC 1.12.2
MC Forge: 14.23.5.2846
Creative core v1.10.70
Little Tiles v1.5.73

On a friend's SMP server, I have created a large door activator with a 4-bit input block inside of the frame, so that it can receive cabling and be activated by redstone. However, whenever I try to place the blueprint, it states "Missing 1p dyeable clean 1 black unit" and will not let me place the blueprint.

I replicated this several times with different blueprints, and see attached photos for a small scale example with 1 block that has 1 input tile and the error message. We were able to place the blueprint in creative no issue, only survival causes problems.

![Screenshot 2024-01-05 224407](https://github.com/CreativeMD/LittleTiles/assets/155796367/c973c80e-e854-4dd9-aca1-9b3ae91138b9)
![Screenshot 2024-01-05 224432](https://github.com/CreativeMD/LittleTiles/assets/155796367/1a927b70-bc80-4930-a97b-a44afdc32f9f)

Confirmed we are able to place the exact same blueprints without issue if we leave out the 4-bit input tile.

**Comment by kirokadura** [comment]
That's intentional. The signal input and outputs are premade structures, as such they can't be used as materials for the blueprints and can't be added to the Little Bags. So when you try to place the blueprint, it requires 1 tile of dyeable clean and 1 black unit instead (because the signal input is essentially a dyeable clean tile painted black).

**Comment by alwayswright16** [comment]
I see, then how does one use the input/output block in conjunction with a door activator blueprint? Do I just need to attach it to a block adjacent to the door activator? 

I'm sorry if this isn't the place to ask that kind of question, but there aren't many tutorials out there on how to use little tiles and the one video I saw had someone put the input in a door frame, "door activator" blueprint. They also created their own pressure plate blueprints using the input/output blocks.

**Comment by CreativeMD** [comment]
Actually this is a bug. It should require the structure as an item and not what the input is made out of. This is fixed in 1.20 in the newest version.
![image](https://github.com/CreativeMD/LittleTiles/assets/1353495/4259f65d-84aa-40df-9272-e4cab3fa0840)
