### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by BanditBloodwyn** [CreativeMD/LittleTiles#932]
MC 1.20.1
MC NeoForge: 1.20.1 - 47.1.84

Creative core v1.10.70
Little Tiles v1.5.73
Rubidium: mc1.20.1-0.7.1a

With the 3 mods above I always get the following error during startup:

_Failure message: LittleTiles (littletiles) encountered an error during the sided_setup event phase
		java.lang.IncompatibleClassChangeError: class team.creative.littletiles.client.mod.rubidium.level.LittleWorldSlice cannot inherit from final class me.jellysquid.mods.sodium.client.world.WorldSlice_

The crash only happens when using Rubidium.
The log is attached. 

[crash-2024-01-09_23.42.58-fml.txt](https://github.com/CreativeMD/LittleTiles/files/13880894/crash-2024-01-09_23.42.58-fml.txt)

**Comment by CreativeMD** [comment]
LittleTiles is not compatible with Rubidium please use Embeddium instead.
