### ISSUE TITLE
Issues with rendering, breaking/placing, and world not loading

### ISSUE THREAD

**Issue by LittleTilesFan** [CreativeMD/LittleTiles#933]
(1.20.1, Heavily modded, LittleTiles versions ALPHA v1.6.0-pre071 and pre088)

I have two distinct (and potentially unrelated) issues that arise when I am using LittleTiles:

1. After some time using the mod, some tiles will:

- Disappear
- Reappear
- Have sides that are transparent
- Appear out of nowhere
- Become un-targetable

These bugs are shown in the first four of the attached pictures. I also sometimes can target tiles that don't exist and have never been created in the first place. This is shown in the last of the attached pictures. I am able to reproduce this issue with LittleTiles versions pre071 and pre088 in Minecraft 1.20.1. These bugs are also not dependent on the blocks that I am placing, i.e., this issue occurs when I am using vanilla blocks as well as modded blocks.

2. I am unable to reproduce this problem, but I was having an issue after making some tiles, essentially my world froze:

- All but a few of the chunks in my world weren't loading
- I could not break or place any blocks
- I was seeing "Waiting for server" on my "The One Probe" tooltip whenever I looked at any blocks.
- If I exited my world, I would be stuck on the "Saving world" page until killing the Minecraft process using task manager.

My mod list is the Direwolf20 1.20 modpack (https://www.feed-the-beast.com/modpacks/119-ftb-presents-direwolf20-120?tab=mods), except with Oculus and Embeddium installed. Because these are significant issues and I don't see anyone else having them, I suspect they could be related to compatibility, so I have tried disabling Oculus, Embeddium, and Chisels and bits. This did not solve anything though.

Happy to provide more information. Thanks!

![2024-01-21_23 24 09](https://github.com/CreativeMD/LittleTiles/assets/157342422/2a0f5d72-12a9-4292-92f6-24d5485d3b0a)
![2024-01-21_23 25 13](https://github.com/CreativeMD/LittleTiles/assets/157342422/59e5ed55-ba0e-4cf3-926d-f27b1eafa208)
![2024-01-21_23 24 51](https://github.com/CreativeMD/LittleTiles/assets/157342422/6fea75ee-b3fc-46bd-9e56-2fa8fb5bf589)
![2024-01-21_23 25 08](https://github.com/CreativeMD/LittleTiles/assets/157342422/7e102803-10c6-4db8-a36b-aa9fbdde2b9b)
![2024-01-21_23 40 22](https://github.com/CreativeMD/LittleTiles/assets/157342422/c97e7a59-44af-4e1a-9d17-eb4b04d68f0d)

**Comment by CreativeMD** [comment]
Are you sure these issues are still there in pre088, because a lot of these have been fixed? In particular the transparent side issue. You can also hit "F3 + D" to reload all chunks to fix the issue. If the world is not loading send the log file, otherwise I cannot really tell what is going on.

**Comment by LittleTilesFan** [comment]
Thanks for the response. Regarding the crashes, I can't reproduce the problem at all and I no longer have the world file which was causing the crash because I just reverted to a backup world file when I was having the issue.

Per your advice I have started using F3 + A (D doesn't appear to do anything) to reload the chunks when an error appears. This causes the visual errors to stop momentarily, with many tiles disappearing and appearing. When I break the tiles that appear, I get the notification "Tile not found." Sometimes, my client stops responding and I have to kill the process to exit. However, errors reappear when I try to place more tiles.

I have realized that this error is occurring at the same point in my build no matter where I am building it or what blocks I am using. I have attached another image with three renditions of this piece of the build. On the far left of this image is the piece created using chisels and bits. To the right are two pieces that were made with Little Tiles, but if I add any more tiles to either piece I start to get visual errors, appearing and disappearing tiles across both of the pieces. I tried making these with cobblestone + stone too, same exact errors. Is this interesting?

I tried removing all but a handful of mods to try to see if I can complete this build in a superflat world. The mods that I kept were: Oculus, Embeddium, LittleTiles, Rechiseled, Chipped, and the corresponding libraries. I am still having the same issues, and I crashed outright after using F3 + A, so I have attached a crash report and the logs. I am thinking this could be more informative?

I am trying to think of more ways to prod this to learn more about it. If you have any suggestions let me know.

Thanks again!

![2024-01-23_17 42 39](https://github.com/CreativeMD/LittleTiles/assets/157342422/cdc9d021-656c-4f4f-a240-c114ba8b32a4)
[log.txt](https://github.com/CreativeMD/LittleTiles/files/14030911/log.txt)
[crash.txt](https://github.com/CreativeMD/LittleTiles/files/14030912/crash.txt)

**Comment by kazumadh** [comment]
Have you updated Embeddium to the newest version? 0.2.2 is a very old version.

**Comment by LittleTilesFan** [comment]
Thanks for the suggestion, kazumadh. I had tried updating Embeddium as well as not using it entirely, but the issues remained.

As far as the first issue I presented in this thread, the incompatibility is with the mod "The One Probe," which is just a mod that gives you a tooltip for the name of the block that you're looking at.

I stated earlier in the thread that I removed all but a handful of mods and found the same issues - I was actually just dealing with graphical issues and a crash. The graphical issues go away with F3 + A as suggested, as long as no crash occurs of course. This time around, I just tried deactivating groups of mods and isolated the issue that way.

I can just stop using the one probe. For what it's worth though, the problem does seem to be a result of tiles joining together automatically. I was having these issues on many different builds, but not when a build was either fragmented or manually made to be hollow (the hollow setting in the little chisel had the same issues).

The second issue presented in this thread has not been reproduced at all, but I did cut down the number of mods I am using from ~300 to ~100.

**Comment by CreativeMD** [comment]
The new version might help out. Can you update CreativeCore and LittleTiles to see if it is fixed?

I will add support for the one probe again (as I have in 1.12), added it to my todo list. I hope I can get to it soon.

**Comment by LittleTilesFan** [comment]
I've tried updating and re-adding the one probe, but it seems that I crash whenever I try to load into my world. By now my world has many tiles already placed, so maybe that's partially responsible. Here's the crash report:

[crash-2024-02-15_17.26.20-client.txt](https://github.com/CreativeMD/LittleTiles/files/14304705/crash-2024-02-15_17.26.20-client.txt)

Otherwise everything's been working just fine without the one probe.

**Comment by CreativeMD** [comment]
Please update Embeddium, that is the reason for the crash.

**Comment by CreativeMD** [comment]
Are the issue mentioned above still there? If yes can you send me your world so I can do some testing myself?

**Comment by LittleTilesFan** [comment]
Ok, I have updated Embeddium and everything works fine now. Thanks!

**Comment by CreativeMD** [comment]
Very cool. Thanks for taking the time to report these issues. Glad it works now!
