### ISSUE TITLE
using the Exporter crashes the game

### ISSUE THREAD

**Issue by TheMysteriousGray** [CreativeMD/LittleTiles#934]
When attempting to use the Exporter, Minecraft crashes within a few seconds of opening the GUI.

Mods installed:

Embeddium
Oculus
WorldEdit
Distant Horizons
CreativeCore 2.11
LittleTiles 1.6.0 pre089
Xaero's Minimap
Xaero's World Map 

Minecraft version 1.20.1

[MultiMC version 0.7.0-3813 CrashLog.txt](https://github.com/CreativeMD/LittleTiles/files/14030481/MultiMC.version.0.7.0-3813.CrashLog.txt)

**Comment by CreativeMD** [comment]
Sorry, forgot to upload CreativeCore. It has been uploaded now! Thanks for reporting this issue!
