### ISSUE TITLE
crash in 1.12.2

### ISSUE THREAD

**Issue by XvaleX10** [CreativeMD/LittleTiles#935]
[crash-2024-01-29_16.31.10-client.txt](https://github.com/CreativeMD/LittleTiles/files/14086249/crash-2024-01-29_16.31.10-client.txt)
[crash-2024-01-29_16.31.11-client.txt](https://github.com/CreativeMD/LittleTiles/files/14086250/crash-2024-01-29_16.31.11-client.txt)
[crash-2024-01-29_16.31.12-client.txt](https://github.com/CreativeMD/LittleTiles/files/14086251/crash-2024-01-29_16.31.12-client.txt)
[crash-2024-01-29_16.31.17-client.txt](https://github.com/CreativeMD/LittleTiles/files/14086252/crash-2024-01-29_16.31.17-client.txt)
[crash-2024-01-29_16.31.19-client.txt](https://github.com/CreativeMD/LittleTiles/files/14086253/crash-2024-01-29_16.31.19-client.txt)
[crash-2024-01-29_16.31.20-client.txt](https://github.com/CreativeMD/LittleTiles/files/14086254/crash-2024-01-29_16.31.20-client.txt)
[crash-2024-01-29_16.31.22-client.txt](https://github.com/CreativeMD/LittleTiles/files/14086255/crash-2024-01-29_16.31.22-client.txt)
[crash-2024-01-29_16.31.23-client.txt](https://github.com/CreativeMD/LittleTiles/files/14086256/crash-2024-01-29_16.31.23-client.txt)
[crash-2024-01-29_16.31.24-client.txt](https://github.com/CreativeMD/LittleTiles/files/14086257/crash-2024-01-29_16.31.24-client.txt)
[crash-2024-01-29_16.31.28-client.txt](https://github.com/CreativeMD/LittleTiles/files/14086258/crash-2024-01-29_16.31.28-client.txt)
[crash-2024-01-29_16.31.42-client.txt](https://github.com/CreativeMD/LittleTiles/files/14086259/crash-2024-01-29_16.31.42-client.txt)
[crash-2024-01-29_16.31.43-client.txt](https://github.com/CreativeMD/LittleTiles/files/14086260/crash-2024-01-29_16.31.43-client.txt)
[crash-2024-01-29_16.31.07-client.txt](https://github.com/CreativeMD/LittleTiles/files/14086262/crash-2024-01-29_16.31.07-client.txt)
[crash-2024-01-29_16.31.08-client.txt](https://github.com/CreativeMD/LittleTiles/files/14086263/crash-2024-01-29_16.31.08-client.txt)

**Comment by CreativeMD** [comment]
No idea why this crash occurs,  but I also do not support 1.12.2 anymore. Sorry.
