### ISSUE TITLE
Crashing when using doors in LittleTiles_ALPHA_v1.6.0-pre089_mc1.20.1.jar

### ISSUE THREAD

**Issue by BeeBento** [CreativeMD/LittleTiles#936]
I have a heavily modded game, so that may be my issue. But when I create a door entity, place it, and try to open it, the game either crashes or the door clips out and completely disappears, leaving behind a big floating blue line in the world. Occasionally when it crashes, I get this error:

The game crashed whilst keypressed event handler
Error: java.lang.NullPointerException: Cannot invoke "team.creative.creativecore.common.gui.IGuiParent.closeTopLayer()" because the return value of "team.creative.creativecore.common.gui.GuiParent.getParent()" is null

I've updated Embeddium to the latest version. Sometimes when I open the door it pushes me far back and there's some blocks stuck on the screen.
![2024-01-30_21 24 11](https://github.com/CreativeMD/LittleTiles/assets/158243525/f4219eaa-44fc-46a4-9c82-b71b34cd1308)
![2024-01-30_21 32 29](https://github.com/CreativeMD/LittleTiles/assets/158243525/ab781479-7175-4e14-8fbc-5b2f1e6c2811)
![2024-01-30_21 33 04](https://github.com/CreativeMD/LittleTiles/assets/158243525/e2737715-0ad3-4731-bba2-6c20a0e793c9)

**Comment by CreativeMD** [comment]
Can you try out the newest version of CreativeCore and LittleTiles and see if this issue still occurs? Also please provide the entire crash-report otherwise it is very difficult for me to debug it.

**Comment by BeeBento** [comment]
It looks like the most recent updates fixed it! I occasionally get knocked back by the door but it doesn't glitch out like before.
