### ISSUE TITLE
Blueprint saving crashes the game.

### ISSUE THREAD

**Issue by hay-dude007** [CreativeMD/LittleTiles#937]
When I try to save a blueprint, it crashes the game. And I have no idea how to read logs, and would rather have professionals look at it.

https://mclo.gs/fJDHV6O
I think the error begins at line 788

Thanks in advance.

**Comment by CreativeMD** [comment]
Seems like there is an issue with FlyWheel. Can you try it without and see if it works then? If we can pinpoint it to flywheels I can contact them to figure out a solution.

**Comment by hay-dude007** [comment]
There is no flywheel... There never was

**Comment by hay-dude007** [comment]
nvm there is but i can't remove it, it would remove create.

Gonna try regardless

**Comment by hay-dude007** [comment]
It is Create. Don't contact the Flywheel devs, contact Create devs. They integrated flywheel in .5.1

**Comment by CreativeMD** [comment]
I have reported this issue to flywheel. I hope it can be fixed soon: https://github.com/Jozufozu/Flywheel/issues/227

**Comment by CreativeMD** [comment]
Fixed in the newest version.
