### ISSUE TITLE
[1.20.1] LittleStructure#use method doesn't have hand or itemstack parameters

### ISSUE THREAD

**Issue by slava110** [CreativeMD/LittleTiles#938]
Hi. Trying to port my mod to 1.20.1. I want to add custom `LittleStructure` representing slot (place) for another structure. Player should be able to click this structure with LittleTiles item in his hand to place tiles from his hand into this slot. However, as you see in
https://github.com/CreativeMD/LittleTiles/blob/df03e9399b6426f92c56f256bb19d4e371d333f9/src/main/java/team/creative/littletiles/common/structure/LittleStructure.java#L960
method `LittleStructure#use` doesn't have `ItemStack` or `EnumHand` as an argument. So I cannot get LittleTiles from player's hand to place into my slot structure :c
Should I use something else to get item from player's hand in 1.20.1?

**Comment by CreativeMD** [comment]
Will be part of the next pre-release. Cool to hear that you are using it. If you need any further help let me know. I'm happy to help out.
