### ISSUE TITLE
[1.12.2] Three bugs

### ISSUE THREAD

**Issue by kirokadura** [CreativeMD/LittleTiles#94]
**Using the latest versions for LT and CreativeCore.**

**1 -** The first one is that most shapes for the hammer are broken. Trying to use Line, Wall, Sphere and Cylinder always result in the Dragbox selection.

First click:
![2018-06-30_22 01 07](https://user-images.githubusercontent.com/29471180/42145038-1ad7b858-7d95-11e8-88fd-be4078f95fec.png)

After second click. Instead of the Wall it makes a Dragbox:
![2018-06-30_22 01 12](https://user-images.githubusercontent.com/29471180/42145039-1b8dad2a-7d95-11e8-83c9-cea1c3e78a62.png)

----------------------------------------------------------------------------------------------------------
**2 -** The second one is that I made this floor and wanted to sneak+middle click to pick it up and place it somewhere:
![2018-06-30_22 33 34](https://user-images.githubusercontent.com/29471180/42145075-641e33e8-7d95-11e8-98e6-c3bc0c34ebbf.png)

But when I place it snapped to grid, this happens:

![2018-06-30_22 33 49](https://user-images.githubusercontent.com/29471180/42145088-8084acd8-7d95-11e8-8869-2e7e8e3aced1.png)

Placing it between 2 blocks:

![2018-07-01_16 18 14](https://user-images.githubusercontent.com/29471180/42145098-9225986c-7d95-11e8-9b32-61f9c14c63c3.png)

Placing it between 4 blocks:

![2018-07-01_16 18 41](https://user-images.githubusercontent.com/29471180/42145101-94666494-7d95-11e8-9dd2-9a2b7f18f975.png)

The issue happens when picking it up by sneak+middle click and extracting from a Recipe. The block is made in the 32 grid size. Here's the file for import: 

[Floor.txt](https://github.com/CreativeMD/LittleTiles/files/2153748/Floor.txt)
----------------------------------------------------------------------------------------------------------
**3-** Lastly, mark mode is not placing correctly:

Here the block is snapped to the grid by holding sneak:
![2018-07-01_16 18 28](https://user-images.githubusercontent.com/29471180/42145144-dde1d8b0-7d95-11e8-89fc-67ef81424aea.png)

When I press M the center of the block relocates to the corner:
![2018-07-01_16 18 30](https://user-images.githubusercontent.com/29471180/42145145-de029668-7d95-11e8-8029-690e274dd7be.png)

**Comment by Dushess** [comment]
3rd problem also occurs before pre85, when i performing copy of something (with mirroring and placing to non-flat surface) and try to place with fixed positioning (like same structure on another side), it always shifted on 1/2 block.
Actually it happening due to placing inside cuboud (no free space in it), solved by markmode.

**Comment by kirokadura** [comment]
@Dushess That problem was actually fixed past pre85, it's just happening again. It's not as intense as it was before, tho.

**Comment by CreativeMD** [comment]
All of them will be fixed in the upcoming pre-release.

**Comment by CreativeMD** [comment]
Released on the discord server.
