### ISSUE TITLE
[Question] LittleTiles 1.20.1

### ISSUE THREAD

**Issue by accessdenied0** [CreativeMD/LittleTiles#941]
Hey sorry but I really have a question about some features in this version of Little Tiles:

I saw/know in a few older 1.12.2 versions of this mod, that it is possible to make [angled slopes ](https://github.com/Nomi-CEu/Nomi-CEu/blob/main/overrides/resources/minecraft/textures/gui/title/background/extracoolcat_2.png)
as well as actual circles/cylinders?
I might be wrong here, but I wanted to ask if those features where (being scrapped), been (have been in little tiles), or will be (ported)?

I was like trying to replicate some builds, but they seem not too be in 1.20.1.

Like the Title suggests, I am not here to request or complain/report, but more that I really am a bit confused if these are possible or will be possible again in future versions...

I apologize for all inconvenience, I really love your mod!

**Comment by CreativeMD** [comment]
Yeah it's still possible. You can use the chisel to build slopes. You can also checkout the wiki here. Lots of stuff have changed, but still the tutorials should be enough to get going.

**Comment by accessdenied0** [comment]
Yes I know, but what about angled slopes? And Circles? The wiki seem to be a bit out of date on that.
![image](https://github.com/CreativeMD/LittleTiles/assets/8020013/7565c79b-f55e-441c-8bf9-3dfb5a57b1c1)
![image](https://github.com/CreativeMD/LittleTiles/assets/8020013/1e30e18b-4dff-493f-8a56-f34bd80a0a95)
[Those are not slopes in the regular sense, but rather angled ones](https://github.com/Nomi-CEu/Nomi-CEu/blob/main/overrides/resources/minecraft/textures/gui/title/background/extracoolcat_3.png)

**Comment by CreativeMD** [comment]
There are corner slopes as well. These angled slopes are not really possible. You can use a pillar, but it will not work in all cases. This might be added in the future.

**Comment by accessdenied0** [comment]
Ahh I thank you alot for the info! Also glad those are might getting add! The Mod is already really cool!

But I am not sure how these are made... It looks like someone do them in this example... at least I am wondering [how one did it](https://www.youtube.com/shorts/fBvr2cE-0u4)

**Comment by CreativeMD** [comment]
I mean just try it out, seems like it is possible already and I just don't know how.
