### ISSUE TITLE
[Issue] [1.20.1] Some Actions create Ghost Blocks

### ISSUE THREAD

**Issue by accessdenied0** [CreativeMD/LittleTiles#942]
I played one the recent newest version and encountered some Issues with simple actions,
Like if making a line-cut with the Hammer in a block or even by leaving a line out of a block.
Similar like dragging a Pillar or Slope through a block, cause a part of a Tile to just "vanish"
The Block is still there and it is also not possible with reload or other means to destroy it, except to like going through it again with different chisel, adding something/ breaking some close part or setting the block to something else (/setblock)

![2024-02-13_17 43 48](https://github.com/CreativeMD/LittleTiles/assets/8020013/6a4f4aea-0535-4137-8416-ff3c2ad4e44e)

As visible in this screenshot one part of the block doesn't have any collision, can even walk though it, but the part still exist.

I do not have any crash report, since it doesn't crash, but can upload the log if wished.

**Comment by CreativeMD** [comment]
It is fixed in the newest version of LittleTiles. If it is still an issue even after the update please let me know.
