### ISSUE TITLE
Crash whit Colored Lux when enterin Dimensions

### ISSUE THREAD

**Issue by IvorAmlug** [CreativeMD/LittleTiles#943]
Since Albedo had semi Compatability i thougth that Colored Lux a more Up to date version also works and it does ALMOST perfectly. 

Sadly, Whenever i enter a Dimension near any Little tiles block the game just crashes. Odly only if Colored Lights from Colored Lux are active during or direclty after entering a Portal. I also dont Land anywhere near my Supposed exit Portal for the most part i just get spawned somewhere.
When using Vanilla fix for playing after crash its sometimes names Colored Lux, Hammercore and Little tiles as potentional causes even though most times naming "unkown" to be the cause.

Mods and Versions used to Reproduce:
Coloured Lux 1.12.2-12.6.33
CreativeCore 1.12.2 1.10.71
Hammerlib 1.12.2 12.2.48
Little Tiles 1.12.2 1.5.85
Forge 1.12.2 14.23.5.2860

Its pretty Odd especially considering that Blocks affectet by Colored Lux for example if u have HyperLights installed will Glow in correct color even if Used as Little Tiles Components. Yet the Game still crashes on Dimension switch regardless if any Coloured Lighting is involved in the Little Tiles block being near. Can be a Importer or one tiny bit of sand it dosnt seem to matter.

I decidet to post this here too as the Colored Lux/Hammerlub devs say its on this mods end.

Some Crash logs:
[crash-2024-02-17_23.10.42-client.txt](https://github.com/dragon-forge/HammerLib/files/14320353/crash-2024-02-17_23.10.42-client.tx
[crash-2024-02-17_22.41.02-client.txt](https://github.com/dragon-forge/HammerLib/files/14320354/crash-2024-02-17_22.41.02-client.txt)
t)
Idk if this can be fixed or not since its sadly 1.12.2 or if there is anything i can do it all feels pretty odd to me either way thx for any help regardless.

**Comment by CreativeMD** [comment]
Seems like the crash occurs because the block has not been loaded or already unloaded. I uploaded a fix for it. Not sure how good that will work. Furthermore there are some serious performance issues with Colored Lux mod.
