### ISSUE TITLE
Little tile blocks/entities not having a physical hitbox, unless they're perfect cubes.

### ISSUE THREAD

**Issue by Ketari-G** [CreativeMD/LittleTiles#944]
Hello there! I am having an issue where after using little hammer on any block, it becomes walk-through-able, unless they're a perfectly shaped cube.

Minecraft version: 1.20.1
Little tiles version: ALPHA_v1.6.0-pre098

Here is an example of a cube little tiles block working perfectly:
![image](https://github.com/CreativeMD/LittleTiles/assets/136245246/56223ed2-4f7f-4d3b-98bd-795da2b3b07b)

And here is a random non-cube structure thingy:
![image](https://github.com/CreativeMD/LittleTiles/assets/136245246/25186aca-94ce-49ac-926b-ad14a4478b1e)

I am using other mods as well, here's a list:
    Resourceful Config (by ThatGravyBoat)
    Thermal Dynamics (by TeamCoFH)
    Architectury API (Fabric/Forge/NeoForge) (by shedaniel)
    Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)
    Almost Unified (by AlmostReliable)
    Trash Cans (by SuperMartijn642)
    Iron Chests (by ProgWML6)
    ModernFix (by embeddedt)
    CB: Compressed Blocks (by sa_shiro)
    Formations Overworld (by SuperMartijn642)
    Controlling (by Jaredlll08)
    LittleTiles (by CreativeMD)
    Oculus (by Asek3)
    Lithostitched (by Apollo)
    Iron Shulker Boxes (by ProgWML6)
    Ad Astra (by AlexNijjar)
    SuperMartijn642's Config Lib (by SuperMartijn642)
    Forgified Fabric API (by Su5eD)
    Geophilic – Vanilla Biome Overhauls (by bebebea_loste)
    Embeddium++ (by SrRapero720)
    Mekanism (by bradyaidanc)
    Ultimate Car Mod (by henkelmax)
    Incendium (by Starmute)
    ChoiceTheorem's Overhauled Village (by ChoiceTheorem)
    ProjectE (by SinKillerJ)
    Chunky (Forge/NeoForge) (by pop4959)
    Searchables (by Jaredlll08)
    Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)
    BCLib (by Quiqueck)
    Titanium (by Buuz135)
    FerriteCore ((Neo)Forge) (by malte0811)
    Better Advancements (by way2muchnoise)
    Prism [Forge] (by Grend_G)
    Konkrete [Forge] (by Keksuccino)
    Radium Reforged (by Asek3)
    Mekanism Generators (by bradyaidanc)
    Embeddium (by embeddedt)
    Krypton (by tuxed)
    Pam's HarvestCraft 2 - Food Extended (by pamharvestcraft)
    Collective (by Serilum)
    Ksyxis (by VidTu)
    Just Zoom [Forge] (by Keksuccino)
    Lazurite (by Su5eD)
    BetterEnd (by Quiqueck)
    Curios API (Forge/NeoForge) (by TheIllusiveC4)
    Pam's HarvestCraft 2 - Trees (by pamharvestcraft)
    Jade 🔍 (by Snownee)
    Resourceful Lib (by ThatGravyBoat)
    CreativeCore (by CreativeMD)
    e4mc (by skyegreen)
    Super Saturation (by ArcAios26)
    SuperMartijn642's Core Lib (by SuperMartijn642)
    Alternate Current (by SpaceWalkerRS)
    Sinytra Connector (by Su5eD)
    AppleSkin (by squeek502)
    Iceberg [Forge] (by Grend_G)
    Patchouli (by Vazkii)
    Formations Nether (by SuperMartijn642)
    Thermal Expansion (by TeamCoFH)
    Angel Block Renewed (by LaidBackSloth)
    Pam's HarvestCraft 2 - Crops (by pamharvestcraft)
    Item Borders [Forge] (by Grend_G)
    Kotlin for Forge (by thedarkcolour)
    Formations (Structure Library) (by SuperMartijn642)
    Mouse Tweaks (by YaLTeR)
    Create (by simibubi)
    Inventory HUD+ (by dmitrylovin)
    Botarium (by CodexAdrian)
    Full Brightness Toggle (by Serilum)
    Industrial Foregoing (by Buuz135)
    Just Enough Items (JEI) (by mezz)
    TexTrue's Embeddium Options (by TexTrue)
    Thermal Foundation (by TeamCoFH)
    Botania (by Vazkii)
    CoFH Core (by TeamCoFH)
    
P.S. Everything else seems to be working fine.

**Comment by Ketari-G** [comment]
Wanted to update this, as I have managed to find the cause of the issue,
It was a mod called "Radium Reforged", as removing it removed the problem.
https://www.curseforge.com/minecraft/mc-mods/radium-reforged

**Comment by CreativeMD** [comment]
I tried to figure it out but just could not. Glad you found the issue!
