### ISSUE TITLE
Some structures make tile loading extremely slow (scale 128).

### ISSUE THREAD

**Issue by MattyWalker1** [CreativeMD/LittleTiles#945]
1.12.2 Forge 14.23.5.2859

Modlist:
A_Little_Extra_Tiles-1.1.0-pre024
CreativeCore_v1.10.71_mc1.12.2
kirosblocks-1.2.2
LittleTiles_v1.5.86_mc1.12.2

[video](https://github.com/CreativeMD/LittleTiles/assets/55023627/de1a1636-e248-4467-a40c-b0d2dc131eb5)
[blueprint.txt](https://github.com/CreativeMD/LittleTiles/files/14436380/blueprint.txt)

**Comment by CreativeMD** [comment]
Sorry but I do not support 1.12.2 anymore. If there are lots of tiles inside a block it will take longer to render the structure, therefore others might appear later as well. You can use the command /lt-debug to see how many blocks are are queued in rendering.
