### ISSUE TITLE
Crash Report LittleTiles_ALPHA_v1.6.0-pre098_mc1.20.1

### ISSUE THREAD

**Issue by Wuppertaler93** [CreativeMD/LittleTiles#946]
Crash report from our server to support the further development of Little Tiles

https://pastebin.com/yMXwPjf7

**Comment by CreativeMD** [comment]
Is that the entire crash-report? It is quite a weird crash and it does not include any context. Maybe you can send the latest.log of this crash as well?

**Comment by Wuppertaler93** [comment]
Yes, this is the complete crash report.

Here is the latest log
[https://pastebin.com/YGSQt4Gq](https://pastebin.com/YGSQt4Gq)

**Comment by CreativeMD** [comment]
Sorry for not responding earlier. I cannot see any connection to LittleTiles at all. It's a very weird crash, if it is related to LittleTiles it must be an incompatibility. Does this crash appear at random? Can you reproduce it somehow?

**Comment by Wuppertaler93** [comment]
Sorry for not responding earlier.  It always crashes when it starts to rain

I don't know who built what where on the server, so I can't say anything more precise

**Comment by CreativeMD** [comment]
Hey, sorry for not responding earlier. This is fixed in the newest pre-release. Thanks for reporting this issue!
