### ISSUE TITLE
LittleTiles does not render with Vintagium/Sodium 1.12.2

### ISSUE THREAD

**Issue by medcorn** [CreativeMD/LittleTiles#947]
Now I know this is very early to mention, as it is very WIP, but I figured I would make it known that there is a port for Sodium in 1.12.2 CleanroomMC. I wanted to know if compat was an issue on their end or on this end, and if it would be possible? 

I use LittleTiles so much in building that I wouldn't really want to do so without it, and the performance boosts that Sodium provides is just so good. Again, wanted to notify just in case.

**Comment by CreativeMD** [comment]
Sorry, but 1.12 is not supported anymore. I added compatibility for embeddium (which is sodium for forge) in 1.20.1, this will not be done for 1.12. Way too many changes would be necessary and as I said I also do not support it anymore. Sorry to disappoint you on that.
