### ISSUE TITLE
[ 1.12 ][ v1.5.87 ] net.minecraft.util.ReportedException: Rendering item , invalid gridsize 32

### ISSUE THREAD

**Issue by Sethgno** [CreativeMD/LittleTiles#949]
tested with latest LT and CC 1.10.71 in isolated instance

crash when opening creative tab and config "scale" = 5
https://gist.github.com/Sethgno/9a5673d067f3c1ca5385f3e489357303

something with one of the multitiles items requiring grid min of 32
or i misunderstanding config settings idk, i just wanna disable 32x size

config settings:
"core": {
    "defaultSize": 16,
    "minSize": 1,
    "scale": 5,
    "exponent": 2,
    "forceToSaveDefaultSize": false
  }

**Comment by CreativeMD** [comment]
Yep exactly, you can replace these structures. They can be found in the assets folder. By default disabling 32 grid is not possible.

**Comment by Sethgno** [comment]
deleting them works too, thanks! :3c
