### ISSUE TITLE
[1.20] LittleBlueprint no Interface when empty

### ISSUE THREAD

**Issue by Klebestreifen** [CreativeMD/LittleTiles#951]
![image](https://github.com/CreativeMD/LittleTiles/assets/23450823/090f7128-b6cc-48a3-b1cb-0104e03ebdc2)

Most of the time I have no interface for empty blueprints. the error is not always there but most of the time. I have not yet found out what causes it. All other interfaces of LittleTiles work. Possibly also an error in connection with REI.

**Comment by CreativeMD** [comment]
Can you send me the log file? There has to be an error.

**Comment by CreativeMD** [comment]
I will close this issue due to inactivity. Feel free to respond here if it is still there.
