### ISSUE TITLE
[1.20] Problems with Collision

### ISSUE THREAD

**Issue by Klebestreifen** [CreativeMD/LittleTiles#952]
[out.webm](https://github.com/CreativeMD/LittleTiles/assets/23450823/03646e15-212f-48c9-b0e4-694a52658ad7)

LittleTiles blocks do not recognize the collision correctly.

**Comment by Klebestreifen** [comment]
The problem comes from Radium
https://github.com/Reforged-Hub/radium-upstream/issues/26

**Comment by CreativeMD** [comment]
Unfortunately I don't see a way to fix it on my end. I do some optimisations for the collision, because minecraft cannot handle the amount of boxes my blocks have. Seems like Radium does something quite similar.

**Comment by MichelJonkman** [comment]
In the Radium settings (lithium.properties)
`mixin.shapes.specialized_shapes = false`
To fix the collisions, not sure if this breaks anything else though

**Comment by CreativeMD** [comment]
@MichelJonkman thanks for your hint. I will close the issue for now as it cannot be fixed unfortunately.
