### ISSUE TITLE
Build Sources 1.12.2

### ISSUE THREAD

**Issue by PoweredByAndrox** [CreativeMD/LittleTiles#955]
Hello, may be it will stupid question but how i can build it with Forge? I tried it with https://github.com/Aizistral-Studios/ForgeWorkspaceSetup/tree/1.12.2-standalone repo but got 
![image](https://github.com/CreativeMD/LittleTiles/assets/38520826/6e4da326-1998-4d20-ba7e-976681300af5)

Also tried adding sources in my main MCP Forge 1.12.2 but i have issues with rendering (ghost models) but mod chiselsandbits works perfectly...

**Comment by CreativeMD** [comment]
There is a video which explains how my workspace used to work: https://www.youtube.com/watch?v=7Ahshi_QjM4

It's a messy setup for 1.12, things are lot better in 1.20 however (if you ever want to switch).
