### ISSUE TITLE
A couple bugs I've seen. (1.20.1)

### ISSUE THREAD

**Issue by yobanyvrod** [CreativeMD/LittleTiles#958]
I'm pretty sure beta 1.20.1 version (LittleTiles_BETA_v1.6.0-pre100_mc1.20.1) has a bug where you cannot alter the state of a structure with an external input. e.g. I make a door with a parent frame with an input on it, link it in signals and link to a pressure plate with output on it. No matter what I do I can't get it to work and I'm pretty sure it should work because everything looks right, but it doesn't. Output always returns false when what I do. Either that or I don't know how to use it. 

Other known bugs:
Game sometimes crashes when changing signal mode from 'Toggle' to anything else.

Game sometimes crashes when changing length of animation of Advanced Door to empty when having points on the graph and the points go off screen.

Please help/fix. Especially first one.

**Comment by yobanyvrod** [comment]
Also: A bug where if you making an Advanced Door where the door travels some distance then goes back to the original position is not possible. (Doesn't move at all)

**Comment by yobanyvrod** [comment]
![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/03a6558f-3b82-4ced-b432-12e6abda3714)

**Comment by yobanyvrod** [comment]
![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/cb56ebdd-b9c1-4925-b020-5d189ab00a96)
![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/b565b405-44cf-4c4f-aeae-74c73446c82d)
![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/c0032e6e-034a-468a-81e4-3534d47d049b)
![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/e9a0b860-8a22-4019-b185-df05795daed0)

Another example of the first bug. Both outputs are wired the same in signals and one returns 1 when the switch is on, how it should, the other doesn't.
________
_using 4-bit outputs
been having similar problems with other iterations of the same idea on other structures_

**Comment by yobanyvrod** [comment]
Another example of the bug. Both outputs are wired the same and one returns 1 when the switch is on, how it should, the other doesn't.

**Comment by yobanyvrod** [comment]
![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/5f9c96a4-f4fe-4af9-a8ab-8c2957f586f4)
![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/90c8e93a-6a98-4152-a412-f3656fe1d55e)
![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/8c9d74ba-1534-45f6-9f00-37c4c9044140)
![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/29c9e2ac-9bab-4054-8bc8-5cc2b73274ec)


Another example of the signal bug. Both outputs are wired to return 1 when Master and Double switch are active. Both switches return true when on, false when off, but outputs always return 0.

I tried removing 'and' gate and just putting the number 1 and into the output and the output returned '1000' so maybe it is just a problem with the logic. Same goes for the 'or', 'b-and', 'xor' gates, they don't return 1 when they should, I don't know about the gates though.

__________
_outputs 12,13 unused- ignore
master switch is the uppermost one with the white indicator
double switch is the 3-unit long one
all other are unused_

**Comment by yobanyvrod** [comment]
Output 10 still doesn't seem to work
Output 11 only returns 1 if and only if Double Switch is on and Output 10 is linked to Double Switch
Output 11 ignores Double Switch if Output 10 is not linked to Double Switch
__________

![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/3191cdf3-d781-4624-8ca1-1e2a92645195)
![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/d4acab27-84f9-485f-b728-81cbc3d2a518)
![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/481855eb-6ab7-4da4-bfe3-8054f4805aa4)
_o10 unlinked, o11 linked, switch on. o11 returns '0000' , master switch on - o10 returning '0000'_
__________
![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/0184ae4e-88af-41b8-b819-3b49785a747c)
![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/c13e8ba8-ad34-4f38-805b-f79a7e52ea2d)
![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/dec244fd-4117-436e-9e32-2d66cbba414d)
_o10 linked, o11 linked, switch on. o11 returns '1111' , o10 still returning '0000'_

**Comment by CreativeMD** [comment]
Hey, very sorry for now responding for the first time. There have been plenty of signal bug fixes in the mean time. I would be very happy if you have the time to test it again and tell me which of these issues is still there. Best would be if you could open a new issue for each bug. I will close this issue for now, feel free to respond here anyway. Again so sorry for leaving this without any answer for more than half a year. It's been busy times and there was just so much other stuff to do.
