### ISSUE TITLE
Rendering bug(1.20.1)

### ISSUE THREAD

**Issue by yobanyvrod** [CreativeMD/LittleTiles#959]
A rendering issue is present where if a tool has been set to replace mode (e.g. chisel) and one tries to place down a structure from a blueprint that has a rotation axis e.g. an Axis Door.

It is also impossible to place down the structure while replace mode is still on. (Not sure if this is a feature or bug)
![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/7b5e24dd-e1ec-4426-9fb7-ce39866ee86b)
![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/81d69f9a-aeb8-4bb5-94a5-bf06a1778fd3)
![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/0190f7a2-d9b6-44ff-ab3c-f8c622363c59)

version LittleTiles_BETA_v1.6.0-pre100_mc1.20.1

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue and taking the time to provide screenshots!
