### ISSUE TITLE
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from LittleTiles (littletiles) Caused by: java.lang.VerifyError: Inconsistent stackmap frames at branch target 47

### ISSUE THREAD

**Issue by ProsperCraft** [CreativeMD/LittleTiles#96]
I have a player that can't load my pack, any ideas?

https://paste.dimdev.org/toneremida.mccrash

**Comment by CreativeMD** [comment]
I guess this crash is caused by another mod, but I don't know which one. The transformer causing this crash will be removed in the upcoming pre-release anyway, I hope I can release it the next 2 weeks, until then you can either try to remove the mod which causes the conflict or wait.

**Comment by Cyprex** [comment]
Does this only happen to one person? Do they have any additional (client-side) mods or is their installation the same as that of other players?

**Comment by CreativeMD** [comment]
Released a fix for it on my discord server.

**Comment by ProsperCraft** [comment]
And curse?

**Comment by CreativeMD** [comment]
Will be available in a few days, there are still a few bugs to be solved.
