### ISSUE TITLE
Grid problem

### ISSUE THREAD

**Issue by yobanyvrod** [CreativeMD/LittleTiles#963]
A small bug where a structure is sometimes put on 32-bit grid where tool has 16-bit grid selected and cannot be snapped to grid unless you crouch or just switch to the 32-bit grid.
<details><summary>Images</summary>
<p>

![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/bdeae91c-1d95-4095-a1e9-7d061b8660cb)
![image](https://github.com/CreativeMD/LittleTiles/assets/66252573/7de19707-7ec0-4625-9114-abd12eb2588b)

</p>
</details>

**Comment by CreativeMD** [comment]
That can happen if the structure has been saved in 32 grid. For example if you place it done in a misaligned way for the 16 grid (meaning in between the pixels) the offset will remain if you pick it up. I don't see a way to fix it properly to be honest. Just switch the grid and align it correctly (you can then pick it up again using the mouse wheel to get the aligned version).
