### ISSUE TITLE
Preview Crash holding little structure door

### ISSUE THREAD

**Issue by WenXin20** [CreativeMD/LittleTiles#967]
```
Minecraft v1.20.1
Forge v47.2.20
Little Tiles v1.6.0-pre102
Creative Core v2.11.27
```

After placing a axis door structure using the blueprint, and then breaking it to pick it up, holding it in your hand will crash the game.
[Crash Report ](https://gist.github.com/WenXin20/97ac1ac37caa49a9c0e61d2d6a4e9f41)

**Comment by CreativeMD** [comment]
Does this issue still persists? If yes can you send export the blueprint and send it here? Sorry for not responding earlier.

**Comment by CreativeMD** [comment]
Will close this issue due to inactivity.
