### ISSUE TITLE
Scaffolding on 1.20.1 breaks (blueprint) structure

### ISSUE THREAD

**Issue by lnkset** [CreativeMD/LittleTiles#969]
When using scaffolding, if you rightclick on the structure, the block above it in the structure breaks and drops the scaffolding. Scaffolding breaks as well. This does not crash, but it is not possible to break and re-place the structure using the Little Blueprint, saying `Structure is not loaded`.

**Comment by CreativeMD** [comment]
Sorry for responding incredible late. I could not reproduce this issue. Does it still persist in the newest version?

**Comment by lnkset** [comment]
No, only on 1.20.1. I posted this when the latest version was 1.20.1, and it does not break in 1.21.1.

**Comment by CreativeMD** [comment]
Unfortunately this is a vanilla bug and there is little I can do to fix it. If you can update to 1.21. Problem is that vanilla passes in the wrong block position which results in LT thinking there is no block.
