### ISSUE TITLE
Everything is black (1.7.10 )

### ISSUE THREAD

**Issue by CrystalWolfGaming** [CreativeMD/LittleTiles#97]
I am on a server that my friends made, when adding the mod everything was fine. A few months later, I got back on and placed a block, it was pitch black but to my friends, it looked normal. Is there any way of fixing this? 

![2018-07-11_13 10 59](https://user-images.githubusercontent.com/41124509/42588729-a1974858-850c-11e8-800f-00223312f63d.png)

**Comment by CreativeMD** [comment]
Enable smooth lighting.
