### ISSUE TITLE
Animated structures are invisible when nvidium is enabled

### ISSUE THREAD

**Issue by zFERDQFREZrzfq** [CreativeMD/LittleTiles#972]
Steps to reproduce :
- Have an Nvidium compatible GPU
- Install LittleTiles + Nvidium
- Place a LittleTile door (axis or sliding)
- Open the door

Witnessed on :
- Minecraft 1.20.1
- Forge 47.2.32
- LittleTiles 1.6.0-pre103
- CreativeCore 2.11.28

The door should be invisible as long as it is in entity state.

Nvidium disabled :
![image](https://github.com/CreativeMD/LittleTiles/assets/155321034/8648d33e-192f-46d0-abe7-135515501cfa)

NVidium enabled :
![image](https://github.com/CreativeMD/LittleTiles/assets/155321034/cc314252-8b2a-4476-a12a-c786c72c8aa2)

**Comment by CreativeMD** [comment]
Sorry, but at the moment I do not plan to add support for NVidium. I just don't have the time and there are other things to focus on.
