### ISSUE TITLE
Major survival bug (Duplication)

### ISSUE THREAD

**Issue by Glytch10** [CreativeMD/LittleTiles#978]
When using slope mode on tiny chisels in survival, specifically when placing sloped tiles that span multiple blocks, instead of consuming pixel amounts of blocks, it duplicates the selected material, giving the survival player _multiple stacks_ of selected material. This proceeds to happen when undone and repeated. I've tested similar behaviors with full tiles, box, cylinder, and sphere modes, it only happens with slopes and only across multiple blocks at odd angles (2x3x2 or larger)

Another much smaller balance issue, not quite a bug, but the hammer removes tiles in the same way a silk touch tool would, as well as being able to break high hardness blocks with ease.

**Comment by CreativeMD** [comment]
Has finally been fixed. Thanks a lot for reporting this duplicate issue. Was a small oversight. Sorry for not responding earlier.
