### ISSUE TITLE
[1.12.2] Storage GUI opens if opening a door that's right next to it

### ISSUE THREAD

**Issue by kirokadura** [CreativeMD/LittleTiles#98]
Reported by Zth404 on Discord.

Issue is present on latest LT and Core.

Opening a door that's right in front of a storage unit causes to GUI for the storage to open as well, as if you're clicking through the door. Clicking through an angle where the storage is not in your aim won't open the GUI.

![desk1](https://user-images.githubusercontent.com/29471180/42720274-9b543290-86fa-11e8-8842-6e1faea15b15.gif)

As you can see, the first and third time he opens the little door the storage opens with it.

I prepared some objects to facilitate the test:

[Storage.txt](https://github.com/CreativeMD/LittleTiles/files/2194609/Storage.txt)
[Door.txt](https://github.com/CreativeMD/LittleTiles/files/2194610/Door.txt)
[Container.txt](https://github.com/CreativeMD/LittleTiles/files/2194611/Container.txt)

Arrange them like so and you can then reproduce the issue (the door closes, covering the hole):

![2018-07-14_00 03 11](https://user-images.githubusercontent.com/29471180/42720290-d85eef90-86fa-11e8-9585-7d78d4dbeb1e.png)

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming pre-release.

**Comment by CreativeMD** [comment]
Also fixed on the discord server.
