### ISSUE TITLE
1.20.1forge embeddium bug

### ISSUE THREAD

**Issue by LCEN1361** [CreativeMD/LittleTiles#980]
Install embeddium and turn on semi-transparent sort
Place a small piece of stained glass and the F3+T reload game will crash
lt106,embeddium0.3.19
安装嵌入并打开半透明排序
放置一小块彩色玻璃，F3+T重新加载游戏将崩溃

**Comment by CreativeMD** [comment]
Can you send me the crash-report?

**Comment by LCEN1361** [comment]
[2024-06-27-7.log.gz](https://github.com/user-attachments/files/16008765/2024-06-27-7.log.gz)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
