### ISSUE TITLE
Bug:360 degrees angle door isn't opening it

### ISSUE THREAD

**Issue by ArtCrafter2999** [CreativeMD/LittleTiles#981]
When you set exactly 360 degrees angle, the door isn't reacting to it at all

Version: Beta 1.6.0 pre 106

https://github.com/CreativeMD/LittleTiles/assets/92592800/202ae097-50d8-4c95-9ff5-c99d61f6ba24

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks a lot for reporting this issue! Also sorry for responding that late.
