### ISSUE TITLE
Suggestion: Door Activator option to activate indirect children

### ISSUE THREAD

**Issue by ArtCrafter2999** [CreativeMD/LittleTiles#982]
In this scenario I have a handler and a door itself. I don't want to move the handler, just to move the door, and the handler will be moved because it's door's child, but I can't pick the children of the door from the frame (Door Activator) to open a door

![image](https://github.com/CreativeMD/LittleTiles/assets/92592800/94fea58b-184c-4074-8d7f-0e33b4371348)

In fact I could represent the desired behaviour in preview by setting the handler as a direct children, toggling it in the activator and move the handler back in the tree not reloading the activator and here it is

https://github.com/CreativeMD/LittleTiles/assets/92592800/1e5f778d-da99-4562-8e21-eaf4556600cb

**Comment by CreativeMD** [comment]
I'm not sure entirely sure if I get your question. Is the behavior shown in the video the intended result? Doors can also be activated via signals which allows for different arrangements. Besides that you can always use an advanced door to time when happens what. Maybe you can explain further what exactly is that you want to do?

Sorry for responding that late.

**Comment by CreativeMD** [comment]
I will close this issue due to inactivity. Feel free to respond here anyway.
