### ISSUE TITLE
Lag spike with Embeddium installed

### ISSUE THREAD

**Issue by Boonk1229** [CreativeMD/LittleTiles#983]
Mods Used:
Embeddium 0.3.19, 0.3.20
CreativeCore 2.11.30
Little Tiles 1.6.0 pre106
Oculus 1.7.0

FPS drops from 100 to 40 when placing/breaking blocks near large amount of tiles that are in render distance. The lag continues for about 5 seconds before going back to normal fps.

This problem is solved when Embeddium is removed.

Test Method:
The test world has around 4.8 million tiles within 4 chunks.
After moving 2 chunks away from the tile chunk (so that there is no chunk update for tile chunk), place/break blocks.
Result: huge lag spike for 3-5 seconds.

![2024-06-13_19 41 14](https://github.com/CreativeMD/LittleTiles/assets/142818049/2ba40b95-b9e2-4389-95a2-4794a3cd3fdd)

**Comment by CreativeMD** [comment]
Does this issue still appear in the newest version of Embeddium and LittleTiles? If yes can you send me your test world?

**Comment by Boonk1229** [comment]
Tried again with newer versions
Mods Used:
Embeddium 0.3.25
CreativeCore 2.11.31
Little Tiles 1.6.0 pre110
Oculus 1.7.0

The issue is still there, fps drops from 400 to 50 when placing blocks near large amount of tiles. The issue can be seen better when shader is turned on, dropping from 100 to 2-5 fps. Again, it comes back to normal after few seconds

Here is the test world


[lagtest.zip](https://github.com/user-attachments/files/16203410/lagtest.zip)

**Comment by CreativeMD** [comment]
Sorry for responding that late. I have downloaded your test world and tried it in 1.21.1 using Embeddium 1.0.11 and there is no lag spike. Can you still reproduce it in 1.21?

**Comment by CreativeMD** [comment]
Will close this issue due to inactivity.
