### ISSUE TITLE
Vivecraft with Little Tiles crashes before launch completes.

### ISSUE THREAD

**Issue by freddyguythe10th** [CreativeMD/LittleTiles#985]
Everytime I try to launch Little Tiles with the Vivecraft mod installed (even if I'm not in VR), the game will crash because of some sort of priority thing. The issue is also outlined with a issue on the Vivecraft Issues page (https://github.com/Vivecraft/VivecraftMod/issues/278) and (https://github.com/Vivecraft/VivecraftMod/issues/268).

**Comment by CreativeMD** [comment]
This issue is hopefully resolved by the use of MixinExtras wrapper operator. Sorry for not responding earlier. Thanks for reporting this issue. New version is out.
