### ISSUE TITLE
Error in 1.20.1 Forge with Embeddium/Embeddium addons

### ISSUE THREAD

**Issue by Heitorzex** [CreativeMD/LittleTiles#986]
Error when playing LittleTiles with one of the following mods (idk which of them tho): Embeddium (0.3.14), Embeddium (Rubidium) Extra (0.5.4.3), Embeddium/Rubidium Dynamic Lights (1.6.0), Embeddium/Rubidium Extras (2.0.0), TexTrue's Embeddium Options (0.1.5). The error happening is whenever i try to open/create a world the game crashes, making it unplayable.

-Heitorzex

**Comment by CreativeMD** [comment]
What kind of error? If it crash can you post the crash-report?

**Comment by Zanthyn** [comment]
I'm also experiencing crashes related to Embeddium. I'm playing ATM9 with a few additions. Game only crashes when I try to add Little Tiles. Tried a couple different version of LT and Creative Core. Log attached.

[crash-2024-06-27_22.35.59-client.txt](https://github.com/user-attachments/files/16023943/crash-2024-06-27_22.35.59-client.txt)

**Comment by Zanthyn** [comment]
Update from previous post. Updating to latest version of Embeddium and removing EmbeddiumExtras and EmbeddiumOptions has resolved the crashing.

**Comment by CreativeMD** [comment]
Yeah. LittleTiles does not support the addons for Embeddium. They might work, but might not. I would rather not use them at the moment.
