### ISSUE TITLE
Structure is not loaded

### ISSUE THREAD

**Issue by Tony0705** [CreativeMD/LittleTiles#988]
After loading into my world, I realized that a portion of a garage door I made were missing, as well as the blocks above that portion.
![2024-06-25_15 01 22](https://github.com/CreativeMD/LittleTiles/assets/173850825/dab792c0-e5b9-47f0-a472-8dc62b8ecfdc)
 When I tried to open it, it didn't work, and I got a message that says "Block is missing/ replaced BlockPos{coordinates}".
![2024-06-25_15 05 25](https://github.com/CreativeMD/LittleTiles/assets/173850825/8d897713-0b72-4ca2-8bdd-697475cb12a7)
 When I tried to break it, I got the message "Structure is not loaded".
![2024-06-25_15 05 43](https://github.com/CreativeMD/LittleTiles/assets/173850825/a15226c3-45dd-42da-9a94-d7edd8604ff1)
 I was able to remove the door with a /kill entity command, but that didn't work for the door frame. The door was working before I left my world. 
I created the door as an advanced door that can be opened by right-click or an activator that was right-clicked, which was the door frame.
![2024-06-25_15 10 43](https://github.com/CreativeMD/LittleTiles/assets/173850825/fffbd6ec-fdba-4953-8ae3-c37174e04f54)
![2024-06-25_15 10 52](https://github.com/CreativeMD/LittleTiles/assets/173850825/a3ad9127-01ae-4e9d-b23c-39a9e3fc6cd9)
I am using the most recent version of Little Tiles for Forge on 1.20.1.

**Comment by CreativeMD** [comment]
You can remove broken structures using the wrench or via /setblock commands.
Does this issue appear more than once? Like does it come back after some time you place a new one?

**Comment by Tony0705** [comment]
Ok thanks. That fixed it.
