### ISSUE TITLE
Boat goes down when placed on LT water

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#99]
![2018-07-22_15 17 10](https://user-images.githubusercontent.com/32820765/43050174-4a26c95e-8e0d-11e8-9e21-59d89550a70e.png)
![2018-07-22_15 17 14](https://user-images.githubusercontent.com/32820765/43050175-4a4c954e-8e0d-11e8-94de-e727f62c6764.png)

**Comment by CreativeMD** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/5086

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming pre-release, make sure to update Forge as well.
