### ISSUE TITLE
Ctrl only way to build up in mark mode

### ISSUE THREAD

**Issue by anzestrela** [CreativeMD/LittleTiles#990]
I want to place a 2 high line in one place. I selected one corner and dragged it over the x axis 5 tiles forward (now the line is 5x1x1) then I pressed mark and wanted to make the line be (5x2x1) but the only way to make the arrow keys control the Y axis appears to be holding down CTRL, but that makes the line be (5x16x1) in 1 click.

**Comment by CreativeMD** [comment]
You can move it along the Y axis by sneaking. Seems like you might have bound your sneak to CTRL? If that is the case there does not seem to be solution there at the moment. Is that the case for you?

**Comment by anzestrela** [comment]
yes, it is. But when placing a blueprint ALT appears to be the one that changes to the Y axis?

**Comment by CreativeMD** [comment]
Yeah, you can switch that in the config using /cmdclientconfig, there you can configure to use ALT for the second mode. I guess this should fix your issue.
