### ISSUE TITLE
Mixin error

### ISSUE THREAD

**Issue by Skylash777** [CreativeMD/LittleTiles#993]
Alright so I've been wanting to play this mod for a long time but every time I've been having this crash report. It only happens with this mod, although it does seem to have a dependant mod with it. It isn't any other mod i've installed as it works fine without it, although it may be some compatibility issues.

Here's the crash report and error:

The game crashed whilst unexpected error
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[crash-2024-07-08_16.26.05-fml.txt](https://github.com/user-attachments/files/16315142/crash-2024-07-08_16.26.05-fml.txt)

**Comment by CreativeMD** [comment]
LittleTiles is not compatible with Optifine. Please use Embeddium and Oculus instead.

**Comment by Skylash777** [comment]
Thanks!
