### ISSUE TITLE
problems with lights and shaders

### ISSUE THREAD

**Issue by raesOTAKU** [CreativeMD/LittleTiles#994]
I have a problem when I put a torch or whatever light creating block, the ilumination is bugged, I´m on 1.20.1, using oculus
![imagen_2024-07-19_171902561](https://github.com/user-attachments/assets/7b4905b3-daaf-473b-9a50-90ee12a978d8)

**Comment by CreativeMD** [comment]
Are the blocks below normal vanilla blocks or ones from LittleTiles? If there are from littletiles does it work if you reload all chunks?

**Comment by kazumadh** [comment]
> Are the blocks below normal vanilla blocks or ones from LittleTiles? If there are from littletiles does it work if you reload all chunks?

I'm definitely sure it's from Little Tiles, even if you aren't using shader, you have to F3 + A to make it update the light level.

**Comment by CreativeMD** [comment]
I will close this issue due to inactivity. But I'm aware that there is still no proper system to react to light changes. It's still on my todo list.

**Comment by maxime-jeanson** [comment]
Hi @CreativeMD, I experience the same behaviour on LittleTile 1.6.0-pre150 on MC 1.21.1 NeoForge v21.1.90 and confirm that doing `F3 + A` fixes this until a new light source is added, or an existing one is removed. Is there anything I can help with resolving this issue?

Before adding light source:

![Image](https://github.com/user-attachments/assets/8db9b381-9ef8-47d7-94e5-9ceaebacbd72)

After adding light source:

![Image](https://github.com/user-attachments/assets/473ef622-e09a-44b4-8986-3a73f1828d6f)

After doing `F3 + A`:

![Image](https://github.com/user-attachments/assets/23b6e018-bed7-4145-bd2a-8854e26a5ef7)

**Comment by CreativeMD** [comment]
Finally fixed it in the newest version.

**Comment by zinx10** [comment]
> Finally fixed it in the newest version.

Is this fix applied to **LittleTiles_BETA_v1.6.0-pre155_mc1.20.1**?
Because I am using that version now and still running into the issues.

![](https://i.imgur.com/HmNAE98.png)

**Comment by CreativeMD** [comment]
Actually forgot to apply this fix to 1.20. A new version is out which contains the fix.
