### ISSUE TITLE
Crash while in advanced door GUI

### ISSUE THREAD

**Issue by Mrbadplayer** [CreativeMD/LittleTiles#995]
When making an advanced door my game crashes while trying to adjust the 2nd point of the offset X value in the animation timeline 
[crash-2024-07-20_14.32.39-client.txt](https://github.com/user-attachments/files/16322125/crash-2024-07-20_14.32.39-client.txt)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Sorry for not responding earlier. Thanks for reporting this issue!
