### ISSUE TITLE
LittleTiles crashed with diet when interact with LittleTiles block in server

### ISSUE THREAD

**Issue by paletteOvO** [CreativeMD/LittleTiles#996]
[diet](https://github.com/illusivesoulworks/diet)

[crash-2024-07-21_10.48.11-server.txt](https://github.com/user-attachments/files/16322908/crash-2024-07-21_10.48.11-server.txt)

Step to reproduce:
Make a little tiles block,
Use a normal block and right click on the little tiles block.

![image](https://github.com/user-attachments/assets/577e736c-e82d-41f2-8a1f-1ea62b6a74ab)

**Comment by CreativeMD** [comment]
Is fixed in the newest version of LittleTiles. Thanks for reporting this issue. Sorry for responding that late.
