### ISSUE TITLE
[1.20.1 & 1.21.1] Game crashed when placing down LT-Pressure Plate & other issues of signal-related items

### ISSUE THREAD

**Issue by kazumadh** [CreativeMD/LittleTiles#997]
**Only Creative Core 2.11.31 & Little Tiles 1.6.0 Beta Pre110 are installed**
_**[Update] (8/21/2024):
For 1.20.1: Only CreativeCore v2.11.37 & Little Tiles v1.6.0 Beta Pre113 are installed
For 1.21.1: Only CreativeCore v2.12.8 & Little Tiles v1.6.0 Alpha Pre113 are installed**_
1. Placing down LT-pressure plate (stone or wood) next to/on top of each other will cause the game to crash (crash logs included)

2. Some premade structures like Switch, Light, Door don't have their own name, they're just named "Little Structure".

3. Some premade structures like Single Input, Single Output, Cable disappear and become something called "structure" when changing gird size.
 
[crash-2024-07-18_14.21.22-client.txt](https://github.com/user-attachments/files/16394269/crash-2024-07-18_14.21.22-client.txt)
[crash-2024-07-18_14.26.13-server.txt](https://github.com/user-attachments/files/16394271/crash-2024-07-18_14.26.13-server.txt)

https://github.com/user-attachments/assets/46d51999-7fb0-47fd-9acc-f475ccbf2b97

https://github.com/user-attachments/assets/644320d7-6a06-4487-9e67-ecca5aaa2075

**Comment by CreativeMD** [comment]
That was a good way to figure out a deep problem with signals. Was a small mistake, but hard to trace it down, but thanks to your report I could find it quite fast. Thanks a lot for all your work, cannot state this enough ... you are helping out a lot. The other two issues are also fixed. New version is out!
