### ISSUE TITLE
[1.20.1 & 1.21.1] Crashed when picking up blocks from Framed Blocks Mod

### ISSUE THREAD

**Issue by kazumadh** [CreativeMD/LittleTiles#998]
**Only CreativeCore v2.11.31, LittleTiles 1.6.0 Beta Pre110 and FramedBlocks v9.3.0 (FB) MC 1.20.1 are installed**
_**[Update] (8/21/2024):
For 1.20.1: Only CreativeCore v2.11.37 & Little Tiles v1.6.0 Beta Pre113 & FramedBlocks v9.3.1 are installed
For 1.21.1: Only CreativeCore v2.12.8 & Little Tiles v1.6.0 Alpha Pre113 & FramedBlocks v10.1.4 are installed**_
Hold LT-Chisel, middle click to pick up a FB block having a dimension of a 1 x 1 x 1 block will cause the game to crash
Someone posted this on Discord server, but sadly he didn't put it in Issue, so I did it for him.
Please contact with the author of FramedBlocks mod (XFactHD) if necessary.
https://www.curseforge.com/minecraft/mc-mods/framedblocks
https://github.com/user-attachments/assets/362bbf4c-785f-4c77-88a3-d36314e3061f
Crash log 1.20.1:
[crash-2024-07-26_23.33.05-client.txt](https://github.com/user-attachments/files/16394441/crash-2024-07-26_23.33.05-client.txt)
Crash log 1.21.1:
[latest.log](https://github.com/user-attachments/files/16643400/latest.log)
[crash-2024-08-17_08.35.04-client.txt](https://github.com/user-attachments/files/16643401/crash-2024-08-17_08.35.04-client.txt)

**Comment by CreativeMD** [comment]
The main issue here is that you should not able to build with these blocks. Problem is that it is not that easy anymore to detect whether a block is compatible or not. Either I only allow mods that work or I somehow try to keep up with the mods that don't work. In general it is adviced to only use normal full blocks with LittleTiles as everything else will not work.

For now I will exclude all blocks from this mod to prevent this issue in the future. I hope in the future there are better ways to detect whether blocks can be used, so I do not have to exclude invalid blocks individually.
