### ISSUE TITLE
[Bug] 1.20.1 - Ghost blocks delete placed blocks.

### ISSUE THREAD

**Issue by CelestialAbyss** [CreativeMD/LittleTiles#999]
One of my modpack players has encountered an issue with LittleTiles as shown in this video with an explanation.

https://www.youtube.com/watch?v=j-4xTgF2XhQ

- Mod version: `LittleTiles_BETA_v1.6.0-pre110_mc1.20.1`
- CreativeCore version: `v2.11.33_mc1.20.1`
- Forge: 47.3.1

Apologies if this is the result of a mod conflict with LittleTiles and another mod in my modpack which can be found [here](https://www.curseforge.com/minecraft/modpacks/finality-genesis-1-20-1).

**Comment by CreativeMD** [comment]
Will be fixed in the newest version. Thanks for reporting this bug! The video was quite helpful. Sorry for responding so late.
